### ISSUE TITLE
Participation Site unresponsive

### ISSUE THREAD

**Issue by krusche** [ls1intum/ArTEMiS#1]
If there are many participations, the corresponding site gets unresponsive, because all participations are loaded. Is there a quick fix that solves the problem? I could imagine the following solutions:
1) Paging: Only load a predefined number of participations (e.g. 20, 50, 100, maybe even configurable)
2) Immediately filter: before loading the results, the user has to filter the exercise
3) Data loading happens in the background and the site stays responsive

With respect to performance, I would prefer options 1 or 2.

**Comment by josiasmontag** [comment]
I think it makes little sense to view all Participations unfiltered. Therefore I have chosen the following solution: 

<img width="1119" alt="participations" src="https://cloud.githubusercontent.com/assets/1945577/21498189/b7fc9bee-cc2a-11e6-8eeb-dc4e916986ed.png">

**Comment by krusche** [comment]
Looks good to me. Do you deactivate the participants page (with all unfiltered participants) then?

**Comment by josiasmontag** [comment]
Yes. Is there any reason to keep it?

**Comment by krusche** [comment]
No. You can get rid of it. Can you instead add a link to the participations page in the exercise dashboard? (e.g. <BASE_URL>/course/4/exercise/49/dashboard)
Because this is what we usually use to navigate.
