### ISSUE TITLE
Restore build plan when archived in triggerBuild

### ISSUE THREAD

**Issue by thilo-behnke** [ls1intum/Artemis#1001]
### Describe the bug

When triggerBuild in the ContinuousIntegrationService is executed, we don't check if the build plan still exists. This is an issue because in this case the CIS should throw an exception as it is unable to build (?).
Concrete behavior needs to be verified.

A fix would be to clone and configure the build plan if the trigger call fails.

**Comment by thilo-behnke** [comment]
@ungaralex Thanks for looking into this!

**Comment by thilo-behnke** [comment]
This was fixed by: https://github.com/ls1intum/Artemis/commit/c355cf614deeef1941c9dba633b5aa66cb7f782a

There is one open issue atm: Because an empty commit is made ("Setup"), a failed submission is generated in this process. The solution would be to ignore commits with the setup message: https://github.com/ls1intum/Artemis/commit/bb14e979c288f16f6310ff1836664c52c359772c#diff-8aa52d2352002de4834b97e439d7ff23R116

**Comment by thilo-behnke** [comment]
Unfortunately the commit message is not included in the webhook payload of Bitbucket: https://jira.atlassian.com/browse/BSERV-10278
The easiest alternative I see would be to a add a parameter to `resumeExercise` as e.g. `createSetupCommit` to turn of the commit creation for this use case: https://github.com/ls1intum/Artemis/commit/c355cf614deeef1941c9dba633b5aa66cb7f782a#diff-8aa52d2352002de4834b97e439d7ff23R106.

**Comment by krusche** [comment]
then let's discuss this tomorrow

**Comment by krusche** [comment]
This issue has been fixes
