### ISSUE TITLE
Text Submission is not loaded when starting new Assessment

### ISSUE THREAD

**Issue by maxr96** [ls1intum/Artemis#1002]
### Describe the bug

Text Submission is not loaded when you start new Assessment (500 HTTP Error is thrown). If you go back from text assessment and click 'Continue Assessment' everything works, because we are requesting different endpoint.

#### To Reproduce

1. Go to 'Course Administration'
2. Click on 'Tutor Course Dashboard'
3. Go to 'Exercise dashboard' on exercise with text submission
4. Click on 'Start new Assessment'
5. See the error, submission is not loaded.
#### Expected behavior

Text Submission is shown and no error is thrown.

#### Screenshots

![Screenshot_2019-10-29 Text Exercises(1)](https://user-images.githubusercontent.com/17262376/67756394-3e31a980-fa3a-11e9-9d9e-d50efdaec690.png)

### Environment

<details><pre>
</pre></details>

#### Output in Web Console

<details><pre>
Http failure response for http://localhost:9000/api/exercise/36/participation-without-assessment: 500 Internal Server Error
</pre></details>

**Comment by krusche** [comment]
@maxr96 can you please fix this bug in a separate PR that is independent of #890?
