### ISSUE TITLE
Score listing: Overlapping buttons

### ISSUE THREAD

**Issue by Garfield96** [ls1intum/Artemis#1009]
### Describe the bug
The buttons for the repository and build plan of students in the scores page overlap for smaller window sizes:
![image](https://user-images.githubusercontent.com/15248220/67899142-f7d76a00-fb61-11e9-9d71-c12d38ad5d88.png)

#### To Reproduce
1. Go to 'Scores' page
2. Decrease window width

#### Expected behavior
No overlapping (possible fix: add margin at the top)

### Environment
<details><pre>
 - OS: Debian Buster
 - Browser: Mozilla Firefox
 - Version: 60.9.0esr (64-bit)
 - Browser: Konqueror
 - Version: Version 5.0.97
</pre></details>

**Comment by lovaiible** [comment]
Hi @Garfield96, we have updated the scores table (customizable paging and search with autocomplete) with the latest release. The display of the buttons is now also optimized for smaller screens, see screenshot below:
![image](https://user-images.githubusercontent.com/33764166/68125273-7f7df980-ff11-11e9-911a-aecbd9491930.png)

I'm therefore closing this issue :)
