### ISSUE TITLE
Participation listing: add filter option for failed submissions

### ISSUE THREAD

**Issue by Garfield96** [ls1intum/Artemis#1010]
### Is your feature request related to a problem?
For huge courses, it is difficult to find failed submissions in the participation listing, since there is no filter or sorting option for this property.

### Describe the solution you'd like
Add sorting or filter option to find failed submissions quickly.

### Additional context
Might be related to the solution of #999

**Comment by krusche** [comment]
@madwau you have worked with the participations page. This should be easy to filter. Could you please have a look?

**Comment by madwau** [comment]
I'm assuming this refers to the "Scores" page and not the "Participations" page since only the former  has results on it at all and the linked issue also refers to "Scores" rather than "Participations".

**Comment by madwau** [comment]
I added the filter option "Show Build Failed" to the programming exercise scores page in PR #1152.

**Comment by madwau** [comment]
@krusche just clarified that I misunderstood the point of your issue and that it was indeed refering to the participations page. I'll add this functionality to the PR.

**Comment by krusche** [comment]
This is already implemented
