### ISSUE TITLE
Allow multiple submissions for file upload exercises

### ISSUE THREAD

**Issue by 13XxM1CHA3lxX37** [ls1intum/Artemis#1012]
### Is your feature request related to a problem?
Currently it is only possible to upload a solution to a file upload exercise exercise once (resp. submit a modeling exercise once) (e.g. PGdP W03 H02: https://artemis.ase.in.tum.de/#/overview/37/exercises/769). This can lead to problems, especially for courses with lots of participants.

Examples where this could lead to problems:
- "uploaded the wrong file"
- "file is corrupt/empty"
- connection issues while uploading
- wrong orientation (gives malus points) and want to fix it
- misunderstood exercise
- exercise was updated and now my submission is wrong etc.

In an exam this would be the equivalent to crossing out and therefore it would be important to have this for courses with "immanenter Prüfungscharakter".

### Describe the solution you'd like
I think it would be good if one could upload/edit files/models as often as needed until the deadline and let the last submission count like one is used to from pushing to the git repo. I thought I saw this in some PR/issue, but could not find any, so either I misread or it's a duplicate.

![Снимок экрана 2019-11-02 в 18 57 04](https://user-images.githubusercontent.com/20713070/68075116-e4b3dc80-fda3-11e9-8cbc-febea0e81d36.png)
![Снимок экрана 2019-11-02 в 18 57 11](https://user-images.githubusercontent.com/20713070/68075120-e8476380-fda3-11e9-936b-1e05196ce335.png)
![Снимок экрана 2019-11-02 в 19 06 54](https://user-images.githubusercontent.com/20713070/68075129-fd23f700-fda3-11e9-9365-32717258e6c6.png)

**Comment by jpbernius** [comment]
We are currently implementing this behavior for modeling (#977) and text (#976) exercises.
This could be implemented in a similar fashion. So far, we did not start working on this for file upload.

It might be part of #890 (@maxr96?) as this will unify submission handling for modeling,  text and file upload. But this will most likely ship well after the former mentioned improvements.

**Comment by maxr96** [comment]
> We are currently implementing this behavior for modeling (#977) and text (#976) exercises.
> This could be implemented in a similar fashion. So far, we did not start working on this for file upload.
> 
> It might be part of #890 (@maxr96?) as this will unify submission handling for modeling, text and file upload. But this will most likely ship well after the former mentioned improvements.

Yes, this can be a part of #890 , but only after we finish #977 and #976. I will take care of it

**Comment by jerhard** [comment]
Can you please notify me at least 11 days before this feature is integrated into the working instance?
It is crucial for us to know this in advance in order to correctly announce this in the exercises.

**Comment by krusche** [comment]
@jerhard Then I suggest we ship this feature on Tuesday, 19.11.2019, ok?
I think we could ship it earlier as well, but then we would not keep your 11 days... What do you think?

**Comment by jerhard** [comment]
Our team will discuss this tomorrow whether this day works for us.  

When do you think the feature would be ready to be shipped, assuming there were no such restrictions?

**Comment by krusche** [comment]
@jerhard I think we could also deploy it next Tuesday (12.11.2019) or next Thursday (14.11.2019)

**Comment by jerhard** [comment]
For those students who already submitted files for an ongoing exercise before that feature is unrolled, will they be able to submit new files afterwards, too?

**Comment by krusche** [comment]
Yes. Until the deadline, they can submit as often as they want. The file on the server will then be overridden
