### ISSUE TITLE
Properly handle skipped tests for programming exercises

### ISSUE THREAD

**Issue by krusche** [ls1intum/Artemis#1016]
Bamboo can identify and report skipped tests. Artemis does not handle those correctly at the moment and assumes that those tests have passed.

Artemis should handle skipped tests to make sure the calculation of the score is correct!

Error report from one of the instructors:
I have a bug regarding the calculation of the score in Artemis found. If the Compile Test failed, all further tests will be skipped. This is also displayed in Bamboo/Bitbucket. On Artemis, however, skipped tests are classified as successful. Here the students passed 0 of 12 tests but apparently 91% of all points.

![image](https://user-images.githubusercontent.com/744067/68115547-ec38ca00-fef8-11e9-9b4a-52f57cc970e0.png)

![skipped](https://user-images.githubusercontent.com/744067/68115471-c0b5df80-fef8-11e9-9334-773f39acd349.png)
![skipped2](https://user-images.githubusercontent.com/744067/68115474-c1e70c80-fef8-11e9-84f3-afd52bff13f2.png)

**Comment by sleiss** [comment]
@thilo-behnke @ungaralex The bamboo-plugin supports skipped test cases (at least in theory, we might have to check it), so I think this is an error in Artemis then, can you confirm this?

**Comment by ungaralex** [comment]
Yes, this is definitely a problem on the Artemis client side. I am currently investigating it.
