### ISSUE TITLE
Trying to submit files where file upload is disabled crashes Chrome

### ISSUE THREAD

**Issue by flodt** [ls1intum/Artemis#1019]
### Describe the bug
In tasks where submitting a file is explicitly not possible, the file selector and "Browse" button is still shown, with the file type "NICHT/MÖGLICH" specifying the former.
When you try to submit a file anyway by clicking on "Browse", Chrome crashes.

#### To Reproduce
1. Go to a course where file upload is disallowed
2. Click on "Upload a file"
3. Click "Browse"

#### Expected behavior
potential error message; "Browse"-button missing altogether

#### Screenshots
n/a

### Environment

<details><pre>
 - OS: macOS 10.15
 - Browser Chrome
 - Version 78.0.3904.70
</pre></details>

#### Additional context
n/a

#### Output in Web Console
n/a

**Comment by krusche** [comment]
what do you mean with "disabled"?

**Comment by flodt** [comment]
Some "Präsenzaufgaben" in the PGdP course are of the type "File Upload", but explicitly rule out submissions in the task description (ex.: [here](https://artemis.ase.in.tum.de/#/overview/37/exercises/789)), as the solution will be discussed on campus in the relevant class.

Thus, file submission is ruled out/disabled by the description, and the file type for the upload is set to "NICHT/MÖGLICH" (see [screenshot](https://pasteboard.co/IFjy9JB.png)). However, the file selector and "Browse" button are still available; clicking that button triggers the crash.

**Comment by 13XxM1CHA3lxX37** [comment]
Can confirm this in Chrome and Chrome Canary. No problems in Safari tho. I think it has got something to do with the "/"

**Comment by krusche** [comment]
Sorry, but that's a misuse of the file pattern. It was never intended to insert "nicht/möglich" here.
We can definitely prevent the crash by not allowing something like this in the future.

To be honest: I don't really understand the intention behind this. Why would you add a file upload exercise on Artemis, if you don't want the students to submit something? This is NOT the purpose of an exercise on Artemis! 

If you only want to discuss and solve these exercises in a tutor class, then please distribute the description of the exercise differently, e.g. by adding a PDF as file attachment to a lecture on Artemis!

**Comment by krusche** [comment]
@beatrisbu can you make sure that instructors cannot write wrong file extensions into the text field? I think file extensions can only include ascii letters and need to have 2-4 letters.
Everything else should be forbidden. I think we should check this on the client and on the server side

**Comment by krusche** [comment]
I added a check so that special characters cannot be used in the file pattern
