### ISSUE TITLE
no graded result

### ISSUE THREAD

**Issue by Tenuro** [ls1intum/Artemis#1028]
### Describe the bug

Artemis shows me that I have no graded results but when clickung on the exercise I got all green checkmarks.

#### Expected behavior

Seeing that I got a result :)

### Environment

<details><pre>
</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by krusche** [comment]
That's too unspecific. Please provide more information, otherwise we cannot help you here!
