### ISSUE TITLE
Programming Exercise Export Results: Include more

### ISSUE THREAD

**Issue by COM8** [ls1intum/Artemis#1034]
### Is your feature request related to a problem?
We would like to process exported and anonymised results from programming exercises further (average submissions count, which test case is the test case the most people had problems with, ...).

### Describe the solution you'd like
The ```Export Results``` button should offer more information that can be exported.
* Submission Count
* How many test cases failed/were skipped
* Which test case failed (name)
* Duration

Perhaps offer some kind of flyout where we can select which information we would like to export.

### Describe alternatives you've considered
Extracting it from the ```Scores``` page with a python script.

**Comment by COM8** [comment]
Any plan when this will be done?
At the beginning of next year we would like to create those statistics.
This also would help us finding people that manipulate our tester or that upload plagiarisms.

**Comment by krusche** [comment]
@COM8 we are currently very busy with other feature request and bugfixes, but this is definitely something that we are interested in as well. 

Feel free to implement it on your own ;-)

**Comment by COM8** [comment]
OK good to know 😉

**Comment by kappelmann** [comment]
As written on slack, our team would very much need that kind of data too :)

**Comment by krusche** [comment]
The grading page was updated with more information about the test cases that pass. We could add an export button here

**Comment by COM8** [comment]
Yes, this would be a nice addition.

**Comment by krusche** [comment]
partly addressed in #4135
statistics about tests can be seen in the Grading page
