### ISSUE TITLE
"Show the complaint" and "Show the Request" does nothing

### ISSUE THREAD

**Issue by 13XxM1CHA3lxX37** [ls1intum/Artemis#1037]
### Describe the bug
When I click on Instructor/Tutor dashboard and select Complaints or More Feedback Requests (for programming exercises), I'm redirected to a List of complaints/List of More Feedback Requests. When I click on Show the complaint/Show the Request - nothing happens

#### To Reproduce
![Снимок экрана 2019-11-10 в 16 04 28](https://user-images.githubusercontent.com/20713070/68546218-92db0a00-03d4-11ea-896d-5b38cf7343c2.png)
![Снимок экрана 2019-11-10 в 16 12 27](https://user-images.githubusercontent.com/20713070/68546307-1694f680-03d5-11ea-9694-6c357941fdcc.png)
![Снимок экрана 2019-11-10 в 16 05 59](https://user-images.githubusercontent.com/20713070/68546219-92db0a00-03d4-11ea-9d9f-8a0095312976.png)
![Снимок экрана 2019-11-10 в 16 07 12](https://user-images.githubusercontent.com/20713070/68546220-9373a080-03d4-11ea-8651-2a7321e3a61f.png)

possibly related: #1030

**Comment by krusche** [comment]
Yes. Resolving complaints and feedback requests for programming exercises is not yet fully implemented and will be possible soon. @maxr96 is working on it in #1030

**Comment by maxr96** [comment]
It was fixed in #1030
