### ISSUE TITLE
Bulk Download and show submission for File Upload exercises

### ISSUE THREAD

**Issue by m1337v** [ls1intum/Artemis#1039]
### Is your feature request related to a problem?
Currently it is not possible to download all submissions of a file upload exercise (and also not to view them as an instructor or am I doing something wrong?) It would be good if one could download them and view them one by one if needed.

![Снимок экрана 2019-11-11 в 6 45 06](https://user-images.githubusercontent.com/20713070/68563949-834cd700-044f-11ea-8172-cac2065541fa.png)
![Снимок экрана 2019-11-11 в 6 45 27](https://user-images.githubusercontent.com/20713070/68563950-83e56d80-044f-11ea-8639-8a7373807410.png)
![Снимок экрана 2019-11-11 в 6 45 40](https://user-images.githubusercontent.com/20713070/68563951-83e56d80-044f-11ea-8b4e-9666cfc2167f.png)

**Comment by krusche** [comment]
this is now possible
