### ISSUE TITLE
Seperate Tutor and Homework exercises in the stats tab

### ISSUE THREAD

**Issue by jefryyy** [ls1intum/Artemis#1040]
I think it might be helpful to separate the tutor exercises from the homework exercises in the statistics section, so that we can get a better visual representation of how we are doing.

**Comment by krusche** [comment]
I think tutor exercises, in the course you are implicitly referring to, are all scored with 0 points, so they should not count into the statistics.
You can ask your instructors to use tags with different colors to make sure the exercises can be distinct more easily.
In the future we might allow to sort exercises after tags in the statistics, but for now this is out of scope
