### ISSUE TITLE
Link to the participation/submission page from exercise scores page

### ISSUE THREAD

**Issue by krusche** [ls1intum/Artemis#1043]
If instructors / tutors want to inspect the number of submissions and results in the exercise scores page, they have to navigate to the participations page first. Then they need to find the students and can click on the page (e.g. `participation/{participationId}/submissions`)

It would be much easier, if instructors / tutors could click on the name of the student in the exercise scores page to navigate to the participation/submission page

**Comment by jpbernius** [comment]
Implemented in #1046.
