### ISSUE TITLE
Improve the file assessment page layout

### ISSUE THREAD

**Issue by Isigiel** [ls1intum/Artemis#1052]
### Is your feature request related to a problem?

When the Instructions for an exercise are long the current layout of the file assessment is a very narrow column on the right and a lot of whitespace on the left. If the right column is collapsed it's even worse.

### Describe the solution you'd like

It seems like a file upload exercise needs almost no space on the left side, I'd consider mving to a column layout instead of the current row layout

### Additional context

While working on this. also consider making the file download button more obvious, right now it's only a text link.

This screenshot shows a full size page and all the wasted space
![artemis ase in tum de_](https://user-images.githubusercontent.com/3612748/69062937-e9bb9180-0a1b-11ea-88f9-bf088e9f5eb8.png)

**Comment by Isigiel** [comment]
I opened a regular PGdP submission to demonstarte this issue and _closed_ the right bar
![artemis ase in tum de_ (1)](https://user-images.githubusercontent.com/3612748/69062895-d6a8c180-0a1b-11ea-8eae-1e9eeb1eae3a.png)

**Comment by krusche** [comment]
You can resize the right column to make it larger.
If the column is collapsed, there should be no content. This is a bug that we need to fix this.

**Comment by krusche** [comment]
I fixed the problem and reduced the whitespace in case there is a large problem statement
