### ISSUE TITLE
Adjust feedback UI for file submissions

### ISSUE THREAD

**Issue by Isigiel** [ls1intum/Artemis#1053]
### Is your feature request related to a problem?

Currently I can give multiple feedbacks with their seperate scores for file submissions, if I understand correctly this was meant for text submissions to grade parts of the text.

### Describe the solution you'd like

Make sure that the UI fits the task of grading file submissions with #1052 and only allowing one score and feedback.

### Describe alternatives you've considered

Otherwise, it would maybe make sense to figure put a way, that allows me to give feedback for certain areas on an image file, I don't see the additional value though.

**Comment by Minh13** [comment]
It's fine if you just give one feedback but others might give multiple ones
