### ISSUE TITLE
Rename exercise title not working for Bitbucket 

### ISSUE THREAD

**Issue by Garfield96** [ls1intum/Artemis#1054]
### Describe the bug
I recently changed the title of a programming exercise. Afterwards, the title was correctly changed in all Artemis dialogs. However, in ~Bamboo~Bitbucket, the old title was still used.

#### To Reproduce
1. Create a programming exercise
2. Change Title
3. Click on a repo
4. Bamboo still shows old name in the upper left corner

#### Expected behavior
The title should also change in ~Bamboo~Bitbucket.

#### Screenshot
Old name: Hausaufgabe 1
New title: Hausaufgabe 1 Neuer Titel

![image](https://user-images.githubusercontent.com/15248220/68618792-70c3b380-04ca-11ea-9585-f63f2848faf0.png)
left: Artemis exercise listing  right: ~Bamboo~Bitbucket

**Comment by jpbernius** [comment]
This would require to update the Display Name when updating Programming Exercises by calling the respective Bitbucket API.
As it is only a display name, updating it does not have implications on e.g. integration with Bamboo or clone URLs.

**Comment by krusche** [comment]
this is out scope for now. the purpose of the short name is to make the connection between bitbucket project, bamboo project and Artemis exercise fixed, so in case you want to rename an exercise, please use the short name to find the ones in Bitbucket and Bamboo
