### ISSUE TITLE
Markdown Editor: Quotes formatting not working correctly

### ISSUE THREAD

**Issue by beatrisbu** [ls1intum/Artemis#1057]
### Describe the bug

The markdown editor does not display correctly the Quotes formatting
#### To Reproduce

1. Go to Course Administration
2. Click on Exercises
3. Click on Create Text Exercise
4.  In the markdown editor for the problem statement use quotes 
5. See formatting in the Preview 

#### Expected behavior

> Ref Test

#### Current behavior

Quotes

![problem statement ref edit](https://user-images.githubusercontent.com/33368508/68666748-c9379700-0544-11ea-8dee-467a02a901c7.png)

![problem statement ref preview](https://user-images.githubusercontent.com/33368508/68666776-d3f22c00-0544-11ea-857d-8f3285e2fb5f.png)

### Environment
Independent

**Comment by krusche** [comment]
@filip-gregurevic this is a small bug, maybe you can have a look while further refining the markdown editor
