### ISSUE TITLE
Creation of new manual results still possible after a manual result has been added

### ISSUE THREAD

**Issue by Haspamelodica** [ls1intum/Artemis#1059]
### Describe the bug
After a manual result has been created, more manual results can be created by manually making HTTP requests to the Artemis API. This allows tutors to "farm" points for the Tutor Course Leaderboard.

#### To Reproduce

As a tutor, do the following:
1. As soon as manual grading is possible for a programming exercise, go to the Exercise Scores page for this exercise. (https://artemis-instance.example.com/#/course/123/exercise/456/dashboard)
2. Open the Developer tools of your browser and go to the Network section.
3. Click on "New result" for a participant of your choice. Fill in the required forms and click on "Save". (Observe the tutor's score in the Tutor Course Leaderboard being incremented by the amount of maximal points of this exercise)
4. In the Developer tools, a POST request should show up. This request can be duplicated as often as the tutor wishes. (On Firefox: Right-click -> Copy -> Copy as cURL; paste to terminal) With every time this request is sent to Artemis, the tutor's score is increased again.

#### Expected behavior
Creation of new manual results should not only be prohibited by replacing the 

#### Screenshots
![image](https://user-images.githubusercontent.com/46954095/68668849-672d6080-0549-11ea-87b5-820dad9196ce.png)
![image](https://user-images.githubusercontent.com/46954095/68668911-89bf7980-0549-11ea-91aa-6f77d833fd48.png)

### Environment

<details><pre>
 - OS: Tested on Debian 10, but probably works on other environments too.
 - Browser: Firefox Quantum (68.2.0esr 64-bit)
 - Artemis version: 3.9.0
</pre></details>

#### Additional context
For an example, see the score in the Tutor Course Leaderboard of Daniel Kirschten (ID: 7198) in the course "Praktikum: Grundlagen der Programmierung WS19/20" (ID: 37) of the Artemis instance used at the TUM (https://artemis.ase.in.tum.de/). See also the (manual) results for Daniel Kirschten (ID: 7198) in the exercise "Woche 03 H 03 - Schliess die Box" (ID: 745).

**Comment by krusche** [comment]
Nice finding and thanks for the detailed report. We will prevent this in the future and hope that tutors do not misuse the Artemis REST API just to get more points in the tutor dashboard.

**Comment by krusche** [comment]
should be fixed since the last release
