### ISSUE TITLE
Improve sorting of exercises on the course overview

### ISSUE THREAD

**Issue by oberrich** [ls1intum/Artemis#1061]
### Is your feature request related to a problem?
In courses with a lot of exercises with no due date associated (tutorial exercises) it can get frustratingly hard to find exercises due to the sorting of exercises.

To give you an expression of how dire this can get, here's a screenshot of the list of tutorial exercises of the PGdP course

![suboptimal](https://i.imgur.com/UoRKMwj.png)

### Describe the solution you'd like
Possible solutions
- Always alphabetically sort exercises with no due date assigned alphabetically
- Add some kind of button to allow users to sort alphabetically and remember which sorting method they have chosen

**Comment by krusche** [comment]
Exercise are sorted by due date.

The problem here was that exercises without due date are not placed into a collapsable "week". We talked to the instructors of the course and they set a due date for all exercises, so this problem should be solved.
