### ISSUE TITLE
Cannot change file-upload assessment after submission

### ISSUE THREAD

**Issue by baueko** [ls1intum/Artemis#1064]
After submitting an assessment there is no option to delete or edit the assessment. You can delete and edit the feedback(s) but there is no option to submit the changes.

There is a popup warning you that you won't be able to change the assessment when you click on submit but there should be a way to still change it somehow if you accidentally submitted the wrong assessment.

**Comment by baueko** [comment]
(I refer to file upload exercises)

**Comment by 13XxM1CHA3lxX37** [comment]
A workaround is getting the submission id and inserting it in the following link:
https://artemis.ase.in.tum.de/#/file-upload-exercise/770/submission/<id goes here>/assessment

**Comment by HanyaElhashemy** [comment]
Issue resolved in PR #1085
