### ISSUE TITLE
Missing execution of build tasks

### ISSUE THREAD

**Issue by tosoikea** [ls1intum/Artemis#1066]
### Describe the bug
Build generation (after push / manual via failed build trigger) is not possible and it seems like no 
new build is enqueued.
This behavior was noticed by multiple students in the Betriebssysteme WS19/20 course.

#### To Reproduce
1. Go to https://artemis.ase.in.tum.de/#/overview/38/exercises/777
2. Try to enqueue new build task
3. See error

#### Expected behavior
Execution of new build

#### Screenshots
![image](https://user-images.githubusercontent.com/35578078/68751294-a0c1a280-0601-11ea-890d-4055fc4ec555.png)

**Comment by krusche** [comment]
This problem was related to the fact that the continuous integration server Bamboo was not working correctly. After restarting Bamboo, it should work again.
