### ISSUE TITLE
Programming Exercise: Show warning if more than 15 tasks get created

### ISSUE THREAD

**Issue by Garfield96** [ls1intum/Artemis#1070]
### Describe the bug
Due to student feedback, we recently increased the number of test cases/tasks. Unfortunately, this causes the step-wizard to cut-off test cases.

#### To Reproduce
1. Create a programming exercise with 50 tasks.
2. See the error on all pages with step-wizard

#### Expected behavior
Options:
1. Break step-wizard into multiple lines if needed
2. Scale down the step-wizard to fit the available space

#### Screenshots

![image](https://user-images.githubusercontent.com/15248220/68786891-d8037400-0640-11ea-9c0b-c81c9d82ae60.png)

**Comment by krusche** [comment]
A programming exercise should not have 50 tasks.
You can connect multiple test cases with the same task by writing

`[task][description](testcase1,testcase2)`

**Comment by Garfield96** [comment]
Ok. We'll do that in the future. Does this have any other consequences besides the grouping of test cases (especially on the amount of shown test output)?
It would be useful if the number of tasks is checked by Artemis to prevent users (like me) from creating too many tasks.

**Comment by krusche** [comment]
No, there are no other consequences. It's only how the test case results are displayed in single tasks.

**Comment by krusche** [comment]
I thinks we can show a warning when you edit the problem statements in case we have more than 15 tasks
