### ISSUE TITLE
Bugs in Pagination

### ISSUE THREAD

**Issue by Garfield96** [ls1intum/Artemis#1072]
### Describe the bug
Follow up to #999 

I tested the new scores page with pagination and found the following issues:
- I like the preview of search results while typing a student id. Unfortunately, if the preview list is very long it gets cut off at the end of the screen. To avoid this problem, the length of the preview list should be limited to the screen height and if there are more entries, the list should be scrollable (without scrolling the whole page)
- I don't think that it is reasonable to have a setting to show 2000 students per page. I would recommend to replace this option by "all"
- Many students have multiple given names but use only one of them. If I try to find a student by only entering the first given name and surname, the student is not shown when he/she has a second given name.
- ~~**Sorting is not working** or takes extremely long (number of students per page does not influence that)~~ (fixed in #1082)
- To improve the performance of sorting, it would be nice when the sorting is only done by the server if not all scores are shown. If all scores are shown, then the sorting should be done on the client-side (like before)
- The feature set and look should be equal for all lists in Artemis. Therefore, the participation listing should be changed as well.
- Nice to have: wildcard support in search strings

Due to data protection laws, I cannot post screenshots of these effects. If those are needed, I could send screenshots via email.

#### Environment
 - OS: Debian Buster
 - Browser: Mozilla Firefox
 - Version: 68.2.0esr (64-bit)

**Comment by madwau** [comment]
Thank you for testing the new scores pages and providing your feedback here, much appreciated!

I agree with pretty much all your points and implemented them in #1100.

The exception is server-side pagination and sorting. That is on the roadmap but it is too big of a change to include it with the other small improvements in this PR.

**Comment by madwau** [comment]
@Garfield96 The PR #1100 has been merged into develop and will be part of [release 3.9.6](https://github.com/ls1intum/Artemis/milestone/16).
