### ISSUE TITLE
Tutor and Instructor submissions are assigned to Tutors for correction

### ISSUE THREAD

**Issue by 13XxM1CHA3lxX37** [ls1intum/Artemis#1075]
### Describe the bug
My (test) submission for a file upload exercise and another submission of an instructor got graded by a tutor. I think it's a waste of time for our tutors to grade submissions from tutors and instructors as our submissions don't count anyways. Saw this only for a file upload exercise, but could imagine that this is also the case for programming exercises with the new dashboard.

I think it would benefit us if the submissions of tutors and instructors would be omitted from the assignment process

![Снимок экрана 2019-11-16 в 11 57 51](https://user-images.githubusercontent.com/20713070/68992188-9228f480-0868-11ea-9a53-e3666e6faa57.png)

**Comment by krusche** [comment]
This is out of scope for now, because in some exercises it might be intended that tutors should grade instructor. If you don't want this, ask your tutors and instructors to not submit here, but use one of the test courses.
