### ISSUE TITLE
Exercise table: Sorting table by column does not work

### ISSUE THREAD

**Issue by lgerhardt45** [ls1intum/Artemis#1078]
### Describe the bug
On the exercise-score page, the sorting buttons on the column names don't affect the sorting of the table. 

#### To Reproduce
1. Go to Course Administration
2. Click on Exercises for a course
3. Click on Scores for an exercise
4. Click on the sorting buttons next to a column-attribute and see the error

#### Expected behavior
Clicking the sorting buttons should sort the table (first click ascending, second time descending)

#### Screenshots
![image](https://user-images.githubusercontent.com/40395744/69036177-9c243200-09e5-11ea-937c-a5ad53625d4c.png)

### Environment
<details><pre>
 - OS: MacOS Catalina
 - Browser: Chrome
</pre></details>

**Comment by Garfield96** [comment]
I can confirm that. I already mentioned this bug in #1072

**Comment by krusche** [comment]
You can sort by clicking on the title. The sort icon (next to the title) is currently a static icon and it would be quite some effort to change it and to allow clicking on it.

Normally the ngx-datatable provides sorting out of the box, however this does not work for custom templates as we use it. Therefore, we would need to implement the correct sort status display and the click handling for each column on our own.

**Comment by krusche** [comment]
Seems that it was easier to fix than expected. Thanks for @madwau we will ship this in the next release!
