### ISSUE TITLE
Grading UI is wrong after having submitted a grade

### ISSUE THREAD

**Issue by Isigiel** [ls1intum/Artemis#1080]
### Describe the bug

If I open an assessment after I have submitted my feedback there are multiple issues.
1. I can start a new feedback and now have two locks
2. I can still add and delete/edit feedback but can't save it anymore

#### To Reproduce

Give feedabck to any file upload submission, submit it and via the overview open that submission again.

#### Expected behavior

The UI should not provide me with interaction options that have no effect or shouldn't be allowed.

### Environment

<details><pre>
 - OS: win10
 - Browser chrome
 - Version 78
</pre></details>

**Comment by krusche** [comment]
Please add a screenshot and and the url where this error occurs.
Also more details would be helpful, otherwise we cannot reproduce and fix this error!

**Comment by Isigiel** [comment]
![artemis ase in tum de_](https://user-images.githubusercontent.com/3612748/69062495-4e2a2100-0a1b-11ea-99b4-30e030479f0a.png)
THis is my view when looking at https://artemis.ase.in.tum.de/#/file-upload-exercise/835/submission/522069/assessment

In my opinion, the add feedback button, otion to delete feedback and option to change texts should not be present since I can't save my changes.
Also the _Assess next Submission_ button instead of redirecting me to my next draft submission opens a new one for me, which is unexpected but I guess fine.

**Comment by HanyaElhashemy** [comment]
Issue resolved in PR #1085
