### ISSUE TITLE
Course-wide scores are incorrect

### ISSUE THREAD

**Issue by jerhard** [ls1intum/Artemis#1086]
### Describe the bug
The overall scores of course participants are not reported correctly under certain circumstances in the web-interface and the exported CSV. In particular, the scores are not up-to-date for programming exercises with both tests and manual assessments after the due-date. In these cases, only the results for the tests run before the deadline are present. Additionally, the scores for file-upload exercises are missing in both the web-interface and the exported CSV. 

#### To Reproduce
1. a) Create an exercise with tests and manual assessments after the due date
    b) Create a file upload exercise
2. After the due date is passed and the tests and assessments are done, go to
Course Administration -> Scores 
To export the CSV, go to "Export as CSV"

#### Expected behavior
The most recent scores for programming exercises should be contained in the CSV and displayed in the web-interface. Scores for file-upload exercises should be present as well.

**Comment by krusche** [comment]
I think I could improve the scores. I have to verify it during testing.

**Comment by krusche** [comment]
Can you verify if it works correctly now? Please reopen the issue if there are still wrong or missing scores.

**Comment by jerhard** [comment]
Looks good from what I see!
