### ISSUE TITLE
Submitted Correctly, ahnee doch nicht..

### ISSUE THREAD

**Issue by mathisfoxius** [ls1intum/Artemis#1087]
### Describe the bug
Wenn man bei einer "File Upload"-Hausaufgabe eine Datei abgibt, kann es dazu kommen, dass die Aufgabe anfangs als "Correctly Submitted" bewertet wird, nach der Deadline aber "You have missed the Deadline" stehen kommt.

### Environment

<details><pre>
</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by krusche** [comment]
Thanks for reporting, but the description is too vague to understand it. Please add more details and and fill out the full issue template. A screenshot helps of the different views would also help (course overview, exercise details, submission page).

Feel free to provide this information and reopen the issue!
