### ISSUE TITLE
Delete Student Submission Results in Scores Page not Loading

### ISSUE THREAD

**Issue by COM8** [ls1intum/Artemis#1088]
### Describe the bug
If I delete a submission of a students programming exercise, the scores page does not load any more.

#### To Reproduce

1. Go to a students programming exercises submissions
2. Click on `Delete`
3. Go back to the scores page
4. Scores won't load

#### Expected behavior
Scores page should load.

#### Screenshots
![Annotation 2019-11-19 193942](https://user-images.githubusercontent.com/11741404/69175865-dc2e0680-0b04-11ea-95ee-4f7642a03487.png)
![Annotation 2019-11-19 193844](https://user-images.githubusercontent.com/11741404/69175862-da644300-0b04-11ea-9011-3f63dcc3ef71.png)

### Environment

<details><pre>
 - OS: Windows 10, Fedora 30
 - Browser: Firefox, Edge (the new one)
</pre></details>

#### Additional context
Refreshing the page does not help.
It takes up to a 20 minutes for it to work again/load.

**Comment by krusche** [comment]
I think I could fix the bug. I need to verify this.

**Comment by krusche** [comment]
This should work again. Could you verify? Please reopen in case it still does not work

**Comment by COM8** [comment]
Works. Thanks!
