### ISSUE TITLE
Email notification for successful file submit

### ISSUE THREAD

**Issue by F42J** [ls1intum/Artemis#1089]
A few people from our course of studies reported about 
Problems with submitting files for tasks. They told that Artemis showed the file as correctly submitted before the deadline expired, but after the deadline, Artemis said that they had missed the deadline The files also couldn't be found in the system.

It would be very useful, if there was a reliable confirmation of the submit. This could for example be realized as confirmation email.

As an additional feature it would be desirable if the confirmation is implemented in a forgery-proof manner, as this would make it possible to prove that the document in question was submitted before the deadline in a doubt. This could be important in case of graded exams.

**Comment by krusche** [comment]
@sascha11110 this might fit into your bachelor thesis
