### ISSUE TITLE
Grading instructions disappear from programming exercise's tutor dashboard

### ISSUE THREAD

**Issue by oberrich** [ls1intum/Artemis#1090]
### Describe the bug
After clicking the "I read and understood the instructions" in the tutor dashboard for programming exercises the grading instructions disappear from the dashboard.

This is very much problematic because unlike the `file-upload-exercise/{id}` view, the `programming-exercise/{id}/view` does *not* show the grading instructions.

The only way to retreive the grading instructions at this point is via the quite hidden "Edit" view (which possibly shouldn't even be available for regular tutors I suppose)

#### To Reproduce
1. Go to a programming exercise in the tutor dashboard
2. Click on the 'I read and understood the instructions' button
3. Watch the grading instructions disappear
4. Regret clicking the button

#### Expected behavior
- Show grading instructions in the `programming-exercise/{id}/view` just like it does for file upload exercises
- Continue to display the grading instructions in the tutor dashboard

**Comment by HanyaElhashemy** [comment]
@oberrich Could you please elaborate more and insert some screenshots as reference?
You should be able to see the grading instructions in the tutor dashboard when you start grading a submission aka when you click on "New Result"
![image](https://user-images.githubusercontent.com/50635005/69567760-6b7e6280-0fba-11ea-8484-593aeeaf7a09.png)

**Comment by oberrich** [comment]
On the left we have the `file-upload-exercise/{id}` and on the right the `programming-exercise/{id}/view`

![Comparison of exercise view](https://i.imgur.com/uxlcoEw.png)

Unlike the file exercise view the programming exercise view does not show the grading instructions which is inconsistent.

The grading instructions are also not displayed in the tutor dashboard (e.g. https://artemis.ase.in.tum.de/#/course/37/exercise/867/tutor-dashboard) after you click the "I read and understood the instructions" which is in my opinion the most useful and convenient view as we have the problem statement as well as the grading instructions nicely rendered in full width on the same page.

While it's true that one can see the grading instructions on the "New Score" pop-up but leaving the pop-up open during our grading process is not very handy and simply doesn't reflect the workflow of a lot of tutors.
Quite a few of us prepare our assessments locally and only enter the grades and feedbacks at the end of the grading process, some of us even use [scripting](https://github.com/oberrich/artemis_cli) to upload our grades.

I hope this is not out of scope and we can at least get the grading instructions in the `programming-exercise/{id}/view` route which shouldn't be too hard to implement considering it's already implemented that way for file uploads.

**Comment by HanyaElhashemy** [comment]
@oberrich Thank you for your detailed response, I will work on it!
