### ISSUE TITLE
Trying out the program in a sandbox

### ISSUE THREAD

**Issue by orkunispir** [ls1intum/Artemis#1091]
I would really appreciate, if there would be something like a sandbox where you can test the program with different values and arrays. An example would be the EdX Course of Harvard cs50: Introduction to Computer Science, the assignments you need to do. They offer a sandbox where you can just test out the program without actually seeing the code behind it. More examples would do the deal too.

Thank you

**Comment by krusche** [comment]
I don’t understand your request. Please describe more details and feel free to reopen the issue then
