### ISSUE TITLE
Programming exercise: Grade highest score

### ISSUE THREAD

**Issue by Garfield96** [ls1intum/Artemis#1101]
### Is your feature request related to a problem?
Some students want to experiment with their code after they gained a high or even full score. In some cases, these experiments lead to a degradation of achieved points and are finally graded, which is not fair, since they already had a correct answer once. 

### Describe the solution you'd like
Add an option to use the highest score of all submissions as a final result.

**Comment by krusche** [comment]
After the due date of an exercise, students can already play around with programming exercise, when test run after due date and manual results are deactivated.
Then they can still participate, submit their code and create as many "ungraded" results as they want. The logic then is that the last graded result (i.e. the last result before the deadline or any additional instructor builds afterwards) will be taken for their final score.

These results are shown in the result history at the bottom of the exercise details page.
