### ISSUE TITLE
All courses missing and reenrollment is possible

### ISSUE THREAD

**Issue by 13XxM1CHA3lxX37** [ls1intum/Artemis#1103]
### Describe the bug
This already happened more than 5 times. I am doing something and out of a sudden all my courses are gone and I see empty rows in course administration. I can even sign up for them. When I sign up for PGdP (I am an instructor there) I'm enrolled as a normal student.
A logout and login fixed this

#### To Reproduce
Go to https://artemis.ase.in.tum.de/#/text/871/assessment click on a random submission (you may have to try multiple ones, can't say for sure when exactly this occurs) and see this:
![Снимок экрана 2019-11-28 в 17 39 21](https://user-images.githubusercontent.com/20713070/69822208-12a30a00-1206-11ea-9e92-1cd9eea1b518.png)

now all your courses are gone

![Снимок экрана 2019-11-26 в 17 17 07](https://user-images.githubusercontent.com/20713070/69821968-5b0df800-1205-11ea-9a82-15363f721302.png)
![Снимок экрана 2019-11-26 в 17 17 18](https://user-images.githubusercontent.com/20713070/69821977-619c6f80-1205-11ea-9f7e-c48c315b03a3.png)
![Снимок экрана 2019-11-26 в 17 17 36](https://user-images.githubusercontent.com/20713070/69821985-69f4aa80-1205-11ea-99bd-59c9b8cb75c5.png)
This message was spammed on every page I opened even though I clicked close every times. Got "fixed" by opening the tutorial again. It doesn't happen when I just logout and login, but seems to be connected to the re-enrollment.
![Снимок экрана 2019-11-26 в 17 18 06](https://user-images.githubusercontent.com/20713070/69821995-6eb95e80-1205-11ea-817e-fc2a7d75c60a.png)

**Comment by krusche** [comment]
Thanks for reporting this bug. If it happens again, could you please open the browser developer tools (see e.g. https://support.airtable.com/hc/en-us/articles/232313848-How-to-open-the-developer-console)

The console output would really help us to spot the issue

**Comment by krusche** [comment]
I just recognized that the mentioned page should only be visible to instructors. Tutors should actually grade in the tutor course dashboard and not here!

We will make this page unavailable for tutors

**Comment by 13XxM1CHA3lxX37** [comment]
Could reproduce it (the "courses gone issue"). This is a Screenshot of the console (hope that's enough for you, else I'd be willing to provide detailed logs if you tell me how). Very strange is that it seems like it occured even before I opened any submission.

I'm an instructor so I don't know how it affects tutors. In general I'd say that we (as instructors at least) need a page like this. I'd recommend to add both Ids (submission and idk) as this caused problems already. e.g. a tutor contacted us about a submission but only had an Id that wasn't the Id one could change in the link to directly asses it. So our submission Id in the link started with a 2 and the Id the tutor had started with a 4
![Снимок экрана 2019-12-02 в 1 13 06](https://user-images.githubusercontent.com/20713070/69922972-11d9d480-14a1-11ea-8064-0f32defb8f0f.png)
Id stuff

**Comment by krusche** [comment]
Thanks for the additional details. I investigated the issue and I think it is already resolved due to a refactoring of transactional contexts during certain REST calls. In the next release 3.9.5, this should not happen anymore.

In case it occurs again, please let us know by reopening the issue.
