### ISSUE TITLE
"Complain" about ungraded submission

### ISSUE THREAD

**Issue by 13XxM1CHA3lxX37** [ls1intum/Artemis#1118]
### Is your feature request related to a problem?
Currently there are several ungraded submissions because of different reasons. We have a poll to identify these submissions, but that's not a nice solution.

### Describe the solution you'd like
It would be useful if students could complain (~2 weeks after the grading deadline) (without using a complaint or with a simple button) that their submissions wasn't graded  and/or let Artemis issue an automatic complaint (this would be a better solution). 

I was told, that currently there is no complain button if the submissions wasn't graded, so this seems to be problematic.

**Comment by jpbernius** [comment]
Thanks for raising this feature request.
This information on ungraded submission is already available in the tutor and instructor dashboards. As you can derive this information from the system, we do not plan a complaint functionality for this.
<img width="689" alt="image" src="https://user-images.githubusercontent.com/6382716/70326891-e440b280-1835-11ea-8915-2f1ba9f262cb.png">

**Comment by 13XxM1CHA3lxX37** [comment]
Well if the numbers were at least correct I would agree (see some examples):
![Снимок экрана 2019-12-08 в 18 47 03](https://user-images.githubusercontent.com/20713070/70393541-6c1bed80-19eb-11ea-9fb3-c7aca219561a.png)
![Снимок экрана 2019-12-08 в 18 47 27](https://user-images.githubusercontent.com/20713070/70393542-6c1bed80-19eb-11ea-8b3e-1e66f42fe434.png)
![Снимок экрана 2019-12-08 в 18 48 02](https://user-images.githubusercontent.com/20713070/70393543-6c1bed80-19eb-11ea-86b1-64b3bbf195f2.png)
![Снимок экрана 2019-12-08 в 18 48 46](https://user-images.githubusercontent.com/20713070/70393544-6c1bed80-19eb-11ea-9a10-87ada92f1b8c.png)

**Comment by krusche** [comment]
Yes, the numbers are not 100% correct. We will look into it and fix it.

**Comment by krusche** [comment]
by the way: for programming exercise, there is an alternative: you can filter for automatic and manual results in the exercise scores page, e.g. https://artemis.ase.in.tum.de/#/course/37/exercise/833/dashboard

Basically the last result is shown, if this is manual, a tutor already corrected the submission of the student. If the last result is automatic, there was not manual correction yet

**Comment by krusche** [comment]
In der Fußzeile der Tabelle steht hier z.B. dann, dass es 105 automatische Ergebnisse gibt (noch nicht bewertet) und 1406 manuelle Ergebnisse gibt (bereits bewertet)

<img width="105" alt="image" src="https://user-images.githubusercontent.com/744067/70433047-f6faf780-1a80-11ea-8877-0692925e7df4.png">
