### ISSUE TITLE
View/Link File Upload/Text submission from Scores/Participations page

### ISSUE THREAD

**Issue by 13XxM1CHA3lxX37** [ls1intum/Artemis#1120]
### Is your feature request related to a problem?
Currently it's not possible to view submissions for the file upload and text exercises like it is possible for programming exercises. It would be good if this was possible as we only have an unnecessary complicated workaround by replacing the submission id and it gets even more complicated with the 2 different submission/participation ids.

Clicking on the name on the submissions page
![Снимок экрана 2019-12-04 в 5 07 12](https://user-images.githubusercontent.com/20713070/70112308-324a9000-1655-11ea-875c-d798fcb1f2c9.png)
Leads us to this page, but not to the actual submission
![Снимок экрана 2019-12-04 в 5 07 19](https://user-images.githubusercontent.com/20713070/70112309-324a9000-1655-11ea-89d6-834aef3cc696.png)
Clicking on the Id (notice, that the click on the student name has no effect by the way)
![Снимок экрана 2019-12-04 в 5 07 45](https://user-images.githubusercontent.com/20713070/70112310-324a9000-1655-11ea-95f9-b34d4e2502f8.png)
Leads us to this page, but not to the actual submission
![Снимок экрана 2019-12-04 в 5 07 58](https://user-images.githubusercontent.com/20713070/70112311-32e32680-1655-11ea-920f-c3d0f3906023.png)
For programming exercises one can just click on the Repository link and view the submission (this would be very helpful for file upload/text exercises) while a click on the name leads us to
![Снимок экрана 2019-12-04 в 5 08 57](https://user-images.githubusercontent.com/20713070/70112312-32e32680-1655-11ea-8e66-f9a5983ad872.png)
This page where one can see how often it was submitted and the results
![Снимок экрана 2019-12-04 в 5 20 57](https://user-images.githubusercontent.com/20713070/70112549-f9f78180-1655-11ea-862f-d6a6a59b1bfb.png)

**Comment by krusche** [comment]
@madwau what is the current status of this issue? Can we implement this until Monday so that we can integrate it into the next release 3.9.7 on Tuesday?

**Comment by madwau** [comment]
@krusche PR #1151 is ready for review. I added buttons for file upload, modeling and text exercise results on the scores page. Clicking one of them either opens the assessment page for the submission (in the case of modeling and text exercises) or shows/downloads the file (in the case of a file upload exercise).
