### ISSUE TITLE
The hierarchy is not visible in Firefox

### ISSUE THREAD

**Issue by jefryyy** [ls1intum/Artemis#1125]
In the firefox browser, the hierarchy in exercise w07h03 is not visible.

**Comment by jpbernius** [comment]
Please provide all information requested in the [Bug Report Template](https://github.com/ls1intum/Artemis/raw/develop/.github/ISSUE_TEMPLATE/bug-report.md). We cannot respond to incomplete bug reports. Feel free to reopen this issue after updating the description.
