### ISSUE TITLE
It's not possible to see the code in a complaint

### ISSUE THREAD

**Issue by Isigiel** [ls1intum/Artemis#1129]
### Describe the bug

When working on a complaint for a programming exercise it is currently not possible to see the code. It would be very helpful to evaluate the complaint if the actual submission could be accessed

#### To Reproduce

1. Go to 'tutor exercise dashboard' for a programming task
2. Click on 'evaluate the complaint'

#### Expected behavior

I expect to have an option to download the submission as I do when grading it or at least a link to the repository so I can clode it myself

#### Screenshots

![image](https://user-images.githubusercontent.com/3612748/70448989-80babd00-1aa1-11ea-97db-65fabd611582.png)

### Environment

<details><pre>
Not that kind of bug
</pre></details>

**Comment by jpbernius** [comment]
Thanks for raising this issue @Isigiel.
This is a valid request, we will ad this to our backlog.

**Comment by 13XxM1CHA3lxX37** [comment]
Same goes for More Feedback requests. See Screenshots in #1134
