### ISSUE TITLE
Cannot change Score by assessing a More Feedback request

### ISSUE THREAD

**Issue by 13XxM1CHA3lxX37** [ls1intum/Artemis#1134]
### Describe the bug
If I assess a More Feedback request and change the score it won't be updated. Maybe that's intentional, but I think it would benefit the students if there is e.g. serious error in the previous correction that one sees right away.

#### Score changed to 99%
![Снимок экрана 2019-12-10 в 14 59 34](https://user-images.githubusercontent.com/20713070/70535819-000dc680-1b5e-11ea-9c3a-0163d5612031.png)
### "request has been resolved"
![Снимок экрана 2019-12-10 в 14 59 45](https://user-images.githubusercontent.com/20713070/70535822-000dc680-1b5e-11ea-87a4-dfca7d9f4627.png)
### Score is the same like before
![Снимок экрана 2019-12-10 в 15 00 09](https://user-images.githubusercontent.com/20713070/70535823-00a65d00-1b5e-11ea-9245-5a1f5f94556d.png)

**Comment by maxr96** [comment]
> ### Describe the bug
> 
> If I assess a More Feedback request and change the score it won't be updated. Maybe that's intentional, but I think it would benefit the students if there is e.g. serious error in the previous correction that one sees right away.
> #### Score changed to 99%
> 
> ![Снимок экрана 2019-12-10 в 14 59 34](https://user-images.githubusercontent.com/20713070/70535819-000dc680-1b5e-11ea-9c3a-0163d5612031.png)
> ### "request has been resolved"
> 
> ![Снимок экрана 2019-12-10 в 14 59 45](https://user-images.githubusercontent.com/20713070/70535822-000dc680-1b5e-11ea-87a4-dfca7d9f4627.png)
> ### Score is the same like before
> 
> ![Снимок экрана 2019-12-10 в 15 00 09](https://user-images.githubusercontent.com/20713070/70535823-00a65d00-1b5e-11ea-9245-5a1f5f94556d.png)

Thank you for reporting this issue. However, More Feedback Request is meant only for providing more feedback. If the student does not agree with the score he should create a Complaint

**Comment by krusche** [comment]
Yes, this is intentional! In such cases, instructors could still override the original result, but this should be an exception, because this can lead to a lot of efforts otherwise and students would basically use the more feedback request to complain about their results
