### ISSUE TITLE
Crash happens when trying to evaluate a complaint

### ISSUE THREAD

**Issue by Isigiel** [ls1intum/Artemis#1135]
### Describe the bug

In a text exercise, whenever I try to open a complaint there seems to be a crash folowwoed by infinite loading.

#### To Reproduce

1. Go to 'a text exercise' (https://artemis.ase.in.tum.de/#/course/37/exercise/871/tutor-dashboard)
2. Click on 'Evaluate the Complaint'

#### Expected behavior

I expected to just be able to see the complaint.

#### Screenshots

![image](https://user-images.githubusercontent.com/3612748/70545872-8fbb7100-1b6e-11ea-8098-ed07d251e0e9.png)

### Environment

<details><pre>
 - OS: Microsoft Windows 10 Pro 10.0.18362 Build 18362
 - Browser Google Chrome
 - Version 78.0.3904.108 (Official Build) (64-bit)
</pre></details>

#### Output in Web Console

<details><pre>
  zone.js:3331 GET https://artemis.ase.in.tum.de/api/text-assessments/exercise/871/submission/234461 400
O @ zone.js:3331
e.scheduleTask @ zone.js:417
onScheduleTask @ zone.js:304
e.scheduleTask @ zone.js:410
t.scheduleTask @ zone.js:241
t.scheduleMacroTask @ zone.js:264
d @ zone.js:1192
(anonymous) @ zone.js:3364
I.i.<computed> @ zone.js:1510
(anonymous) @ breadcrumbs.js:386
(anonymous) @ http.js:2581
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
call @ tap.js:16
subscribe @ Observable.js:23
call @ tap.js:16
subscribe @ Observable.js:23
call @ tap.js:16
subscribe @ Observable.js:23
i @ subscribeToResult.js:9
_innerSub @ mergeMap.js:59
_tryNext @ mergeMap.js:53
_next @ mergeMap.js:36
next @ Subscriber.js:49
(anonymous) @ subscribeToArray.js:3
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
call @ mergeMap.js:21
subscribe @ Observable.js:23
call @ filter.js:13
subscribe @ Observable.js:23
call @ map.js:16
subscribe @ Observable.js:23
(anonymous) @ text-assessment.component.ts:139
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
_subscribe @ BehaviorSubject.js:14
_trySubscribe @ Observable.js:42
_trySubscribe @ Subject.js:81
subscribe @ Observable.js:28
ngOnInit @ text-assessment.component.ts:113
(anonymous) @ core.js:31910
(anonymous) @ core.js:44367
Kv @ core.js:44306
_C @ core.js:45160
(anonymous) @ main.2da10f8df663db3d6f91.bundle.js:2
updateDirectives @ core.js:44780
Gv @ core.js:44271
lC @ core.js:44637
nC @ core.js:44594
Gv @ core.js:44272
lC @ core.js:44637
eC @ core.js:44565
Gv @ core.js:44278
detectChanges @ core.js:31126
tick @ core.js:41045
(anonymous) @ core.js:40893
e.invoke @ zone.js:396
onInvoke @ core.js:39699
e.invoke @ zone.js:395
t.run @ zone.js:153
run @ core.js:39511
next @ core.js:40890
l @ core.js:35336
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:35298
Ib @ core.js:39642
onHasTask @ core.js:39719
e.hasTask @ zone.js:451
e._updateTaskCount @ zone.js:472
t._updateTaskCount @ zone.js:294
t.runTask @ zone.js:215
b @ zone.js:611
t.invokeTask @ zone.js:517
b @ zone.js:1671
m @ zone.js:1697
Show 52 more frames
breadcrumbs.js:64 Http failure response for https://artemis.ase.in.tum.de/api/text-assessments/exercise/871/submission/234461: 400 OK
</pre></details>

**Comment by krusche** [comment]
Thanks for finding and reporting this. This is a regression due to #1030. I fixed it and we will deploy a hot fix as soon as possible.
