### ISSUE TITLE
Results column in scores view broken when searching/sorting

### ISSUE THREAD

**Issue by oberrich** [ls1intum/Artemis#1136]
### Describe the bug
When searching for students or sorting the list in the scores view the 'Results' column always stays the same

#### To Reproduce
1. Go to some exercises' scores list
2. Sort by different keys
3. Search for a specific students
4. See that the Result column doesn't update

#### Expected behavior
- Result column should stay in sync when manipulating list

#### Screenshots
![](https://i.imgur.com/TGOK2IM.gif)

#### Environment
- Windows 10 Pro Version 1909
- Chromium Version 74.0.3729.108 (Official Build) (64-bit)

**Comment by krusche** [comment]
Thanks for noticing and reporting this. This is a regression.

@madwau could you please quickly fix this, then we can deploy a hotfix release today.

Thanks!

**Comment by madwau** [comment]
Yes, I'm looking into it right now.

**Comment by madwau** [comment]
Fix is created: #1137.

**Comment by krusche** [comment]
@madwau thanks, we will deploy a hot fix as soon as possible
