### ISSUE TITLE
Back button on notification details page doesn't work

### ISSUE THREAD

**Issue by sascha11110** [ls1intum/Artemis#1145]
### Describe the bug
Back button in notification management detail view does not work.

#### To Reproduce

1. Go to `Server Administration` > `Notfication Management`
2. Click on `View` button
2. Click the `Back` button

#### Expected behavior
Go back to previous page (*Notification Management* page).

#### Screenshots

![70793634-0a1d0880-1d9c-11ea-9993-a4b80d5ec616](https://user-images.githubusercontent.com/15168372/70808037-22524f00-1dbf-11ea-9f47-572b1a396145.png)

#### Output in Web Console

<details><pre>
instrument.js?ea14:102 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'notification-management'
Error: Cannot match any routes. URL Segment: 'notification-management'
</pre></details>

**Comment by madwau** [comment]
Looks like the router link of the button is simply wrong. It should be `/admin/notification-management` instead of `/notification-management`. Just tested it locally.

**Comment by sascha11110** [comment]
You're right. Thanks for pointing it out! Since it's such a small change I incorporated it into my existing PR: https://github.com/ls1intum/Artemis/pull/1132/commits/a21835cfcd7315abd7263c76eab012d27a07652f
