### ISSUE TITLE
Allow instructors to cancel assessments

### ISSUE THREAD

**Issue by krusche** [ls1intum/Artemis#1150]
Tutors lock assessments when they start to assess a submission. Then other tutors cannot start this assessment any more. While tutors can release the lock by clicking on `Cancel`, instructors cannot do that in case the tutor does not finish the assessment or some other tutor should do it.

Therefore, it would be good, if the submission and assessment page (e.g. `file-upload-exercise/835/assessment`) has a button `Cancel assessment` which invokes the existing `.../cancel-assessment` REST call on the specific exercise type.

It would be great if the submission and assessment page also gets the new ngx-datatable style with paging, sorting and filtering. Filter options would be:
* With result
* Without result
* With lock

**Comment by krusche** [comment]
We should then also link the submission and assessment page in the course administration page so that it is more accessible for instructors

**Comment by madwau** [comment]
New PR for filtering submissions by locked assessment: https://github.com/ls1intum/Artemis/pull/1183
