### ISSUE TITLE
Submissions appearing in Tutor Dashboard+Participations but not in "Scores"

### ISSUE THREAD

**Issue by 13XxM1CHA3lxX37** [ls1intum/Artemis#1154]
### Describe the bug
I tried to locate unassessed submissions on the "Scores" page by filtering for automatically graded submission, but got no results. In the Instructor/Tutor dashboard it was shown, that there still are unassessed submissions, so I tried to assess it using the Tutor dashboard. Here I was shown a "NEW" submission, that could be assessed with "new result". When I looked the LRZ Id up in the "Scores" page there were no results found. It only appeared in "Participations". I don't know why this happens, as the submissions seems to be correct.

![Снимок экрана 2019-12-16 в 14 12 47](https://user-images.githubusercontent.com/20713070/70914862-211c5e80-2019-11ea-935d-e269d5a8d696.png)
![Снимок экрана 2019-12-16 в 15 23 40](https://user-images.githubusercontent.com/20713070/70914865-21b4f500-2019-11ea-8df5-df39c4edf53b.png)
![Снимок экрана 2019-12-16 в 15 23 47](https://user-images.githubusercontent.com/20713070/70914866-21b4f500-2019-11ea-9025-1918a51fdf66.png)
![Снимок экрана 2019-12-16 в 15 23 55](https://user-images.githubusercontent.com/20713070/70914869-21b4f500-2019-11ea-99ec-08594af76379.png)
![Снимок экрана 2019-12-16 в 15 24 26](https://user-images.githubusercontent.com/20713070/70914870-224d8b80-2019-11ea-8b87-7f8e64382eac.png)

**Comment by ungaralex** [comment]
Could it be the case that you retroactively changed or set the due date for this exercise?

**Comment by madwau** [comment]
@ungaralex and I investigated this issue a bit.

The student started this exercise after the currently set due date of the exercise but our strong assumption is that this due date was retroactively set since it is not possible to start a programming exercise after the due date. The reason why this submission had no result was most likely due to connectivity issues between Bamboo and Artemis.
