### ISSUE TITLE
Exercise sequence, dark mode and number of points

### ISSUE THREAD

**Issue by laert-06** [ls1intum/Artemis#1195]
### Is your feature request related to a problem?

1. It is a bit annoying that the sequence of the assignments is fixed and I can't change it
2. Most of the people in computer science (in my experience, however short it may be) use dark mode generally, and the contrast between the programming language IDE and the Artemis white page can be a bit tiresome to the eyes, especially while working at night.
3. We can see the percentage of an exercise but not the exact number of points

### Describe the solution you'd like

1. I would like an option where we can sort the assignments ourselves, or at least have a way we can filter them so that we can choose ourselves what should and should not be shown.
2. A simple dark mode would suffice, I am not sure how hard that is to implement but I think it would make a lot of people suffer less
3. I wish we were able to see not only the percentage of the assignments, but also the exact number of points, in the statistics menu at least

**Comment by krusche** [comment]
parts of the issue have been implemented
