### ISSUE TITLE
CSV export format broken for scores >= 1000 Points

### ISSUE THREAD

**Issue by COM8** [ls1intum/Artemis#1197]
### Describe the bug
When students have more than 1000 points the CSV export, exports an invalid CSV file.
This is caused by using a `,` as delimiter for the CSV as well as indentation for numbers >= 1000 (e.g. 1,028.5).

#### To Reproduce
1. Have students with more than 1000 points.
2. Export the results to a CSV file.

#### Expected behavior
Do not use `,` as indentation for 1000.
1,028.25 -> 1028.25

#### Screenshots
In Artemis:
![artemis](https://user-images.githubusercontent.com/11741404/72710539-9d014d80-3b67-11ea-9f6e-ae5ffac1a7be.png)
The results .csv file:
![csv](https://user-images.githubusercontent.com/11741404/72710541-9d99e400-3b67-11ea-973d-c4c29740b3cc.png)

### Environment

<details><pre>
 - OS: Fedora 30
 - Browser Firefox
 - Version 72.0.1 (64-bit)
</pre></details>

**Comment by krusche** [comment]
I implemented a fix by rewriting some parts of the export using an external framework to export the results to a csv file.
This means, all values of the csv file are not quoted with `"`.
Depending on the used language, the values will be exported with different decimal separators:
English --> `.`
Germany --> `,`
So you can choose now which format suites you best.
In addition, Artemis now uses `;` as separator to avoid inferences with `,`

The rewrite will allow us to offer more customizations regarding the export in the future. Then users will be able to choose:
* separator between values (e.g. `tab`, `,`, `;`)
* rounding accuracy (how many digits after the comma)
* decimal separator (`.` or `,`)
