### ISSUE TITLE
Text exercise assessment: Only first occurrence of selected text is marked

### ISSUE THREAD

**Issue by jerhard** [ls1intum/Artemis#1207]
### Describe the bug
In the assessment for text exercises, it is possible to mark a particular line of text and assess it.
When some text is selected, a hover "Assess" will appear. When clicking on it, a new assessment form will be created. 
However, after clicking the hover, the _first occurrence_ of the selected text will be marked, which may or may not be the same as the location where the text has been selected.

#### To Reproduce
1. Start the assessment of a text exercise where there are multiple occurrences of the same text
2. Select one of the multiple text occurrences that is not the first.
3. Click on "Assess", when it appears
4. Now the first occurrence of the text will be marked, and not the one you selected. 

#### Expected behavior
The selected occurrence should be marked after the click on "Assess".

#### Additional context
In some text-exercises, e.g. where the task is to write some pseudo-code, it is important to be able to exactly mark the erroneous occurrence of text (e.g. an instruction), and not just the first occurrence of the text (instruction).

**Comment by jpbernius** [comment]
Thanks for reporting this. This is a known problem we will be addressing in a future release.
Currently we are storing the "reference" as a copy of the selected text. Therefore we can only find the first occurrence.
In the future, we will store indexes to circumvent this limitation. (e.g. in #729).
Unfortunately, there is not an easy fix, so this will take some more time to implement.

**Comment by jpbernius** [comment]
This is supported with Text Assessments V2 #1286.
