### ISSUE TITLE
API: After posting a manual result with incorrect data, submission is broken

### ISSUE THREAD

**Issue by Haspamelodica** [ls1intum/Artemis#1215]
### Describe the bug
After making a `PUT` request to `api/participations/12345/manual-results` with a JSON that does not contain a `completionDate`, no additional manual results can be added for that submission. (The server returns a 500 Internal Server Error)

#### To Reproduce
(See bug description)

#### Expected behavior
The server should do more sanity checking.

### Environment

<details><pre>
 - OS: n/a
 - Browser n/a
 - Version 3.10.0
</pre></details>

**Comment by krusche** [comment]
This should be resolved in the newest version. Please double check this.
