### ISSUE TITLE
Add support for middle mouse button.

### ISSUE THREAD

**Issue by joschahenningsen** [ls1intum/Artemis#1236]
As a tutor, I regularly try to open resources such as the assessment-scores page in a new tab. However, since Artemis is built with reactive paradigms in mind, using the middle mouse button does not work. 

The current solution is opening a new instance of Artemis and navigate to the desired resource. This is very Inconvenient.

If possible, I'd love to see a solution in one of the future releases. 
Thanks!

**Comment by jpbernius** [comment]
Thanks for raising this issue @joschahenningsen.
We have investigated into this in #611 already.
For now we are using HTML Buttons in many places which do not support this behavior. 

I am closing this issue as this a duplicate. We will check to reprioritize this issue!
