### ISSUE TITLE
File-upload: Some stored submission files are empty

### ISSUE THREAD

**Issue by jerhard** [ls1intum/Artemis#1243]
### Describe the bug
For some file-upload submissions, the submission file is empty (has a size of 0 Bytes).

#### To Reproduce
It is unclear how this behavior is triggered.
There are some of these submissions on the PGdP course, however. We assume that the students tried to upload files of non-zero size, although it cannot be guaranteed that this was the case. 

#### Additional context
We don't know the exact context when this occurs.
Maybe this has to do with the file size limit and affects files around that size?

**Comment by krusche** [comment]
We improved the file upload to specifically prevent such cases: https://github.com/ls1intum/Artemis/pull/1114 

This improvement was released on December 18, 2019 (see https://github.com/ls1intum/Artemis/releases/tag/3.9.7) 

Can you point us to some concrete examples, so that we can investigate this in more detail?
It would be interesting, if there are such cases after the fix has been deployed.

**Comment by jerhard** [comment]
For examples, see the private message on Slack.

**Comment by Trattue** [comment]
This bug occurred to my EIST team recently. The team member who uploaded the image used Chrome and confirmed a few days after the upload that the picture was there. I checked about a day after the upload with Firefox and saw it as well.

After the due date neither the tutor, nor we could open the file. This GIF depicts this behavior in Firefox (third-party cookies disabled, do not track me and some other privacy settings are enabled):
![artemis_file_upload_bug_2](https://user-images.githubusercontent.com/63713970/82831625-36938f80-9eb9-11ea-8270-b188adf66874.gif)

And here is the 404 error message when trying to open the file with Chrome (factory settings):
![grafik](https://user-images.githubusercontent.com/63713970/82831345-7b6af680-9eb8-11ea-9668-b1846252d6c6.png)

**Comment by krusche** [comment]
should be fixed by #2473
