### ISSUE TITLE
Enable complaints for team-based exercises

### ISSUE THREAD

**Issue by madwau** [ls1intum/Artemis#1278]
### Is your feature request related to a problem?
Right now, complaints are not supported yet for team-based exercise participations.

### Describe the solution you'd like
Every student of the team should have the ability to create complaints and see the responses to those. Questions that need to be considered:
- Is it important to know which of the students in the team created the complaint?
- Is the max complaint limit scoped to each student or to the team?

**Comment by krusche** [comment]
This was already implemented
