### ISSUE TITLE
Live Quiz: Result does not load automatically

### ISSUE THREAD

**Issue by clemenszuck** [ls1intum/Artemis#1293]
### Describe the bug

During a live quiz, if the time runs out and the quiz ends, the solution is submitted automatically, the editing is disabled and a message with "The Quiz has ended. Please wait. The results will be loaded automatically." is displayed. The results however are not loaded automatically and you have to refresh the page to see the results.
#### To Reproduce

1. Go to 'Course Management'
2. Create a simple Quiz Exercise (with a short duration), set it to visible and start it
3. Participate in the Quiz and let the time run out
4. See the message "The Quiz has ended. Please wait. The results will be loaded automatically."
5. Results are not loaded automatically, but are visible after refreshing the page

#### Expected behavior

The results should be loaded automatically after the time has run out.

#### Screenshots

The screen on which you are stuck after the time has run out.
![live-quiz](https://user-images.githubusercontent.com/33415047/78656513-cf4d5c00-78c7-11ea-9643-c4b9bf43d64c.png)

**Comment by krusche** [comment]
Thanks for the bug report. I fixed it.
