### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by MarcServat** [ls1intum/Artemis#1295]
### Describe the bug
The compiler does not recognice Java jdk-8 syntax on Usability User Interface exercise
#### To Reproduce
1. push code

#### Expected behavior
compiler worked

#### Screenshots
![canvas](https://user-images.githubusercontent.com/11317965/78677707-5d393f00-78e8-11ea-9646-3dc46088544b.png)

### Environment
<details><pre>
 - OS: Ubuntu 18.02
 - Browser Chrome
 - Version 80
</pre></details>

**Comment by jpbernius** [comment]
This issue is related to an SEEC exercise and **not** the Artemis Platform. Please report problems regarding the exercises with the instructors.
