### ISSUE TITLE
Purge build plans on CI server

### ISSUE THREAD

**Issue by krusche** [ls1intum/ArTEMiS#13]
After the due date of an exercise, it would be good, if Artemis can delete all student build plans on the CI server without deleting data in the Artemis database so that statistics and results are still available. Another possibility would be to manually start this purge mechanism.

The repositories in the VCS don't need to be deleted, so that student could theoretically resume their exercise (in this case only the build plan would be recreated).

To allow for better statistics, Artemis should store the following CI date in its database:
- Results of each test case (this would require a change of the object model / database)
- maybe: build log (but this should not be interesting)

important: in case of build output files (e.g. jars in release management exercises), the build outputs would be lost, but in this case students could resume the exercise and create the build output again

**Comment by jpbernius** [comment]
I think @krusche implemented this in 3c97e3ab, d760683a and 95ba5204.

**Comment by krusche** [comment]
Yes. We can close it.
