### ISSUE TITLE
No show results

### ISSUE THREAD

**Issue by mpabad** [ls1intum/Artemis#1329]
### Describe the bug
I completed the tasks for showing the course titles, but the tasks doesn´t shows as completed. Y try the same code in Eclipse and works well.

#### To Reproduce

1. Go to´ main page´´
2. Click ´Save´
3. Click ´Submit

#### Expected behavior

Graded message to show 100%

#### Screenshots
![image](https://user-images.githubusercontent.com/6589848/79897895-f6c81c80-83cf-11ea-98b8-1b24f6856b13.png)

![image](https://user-images.githubusercontent.com/6589848/79897960-0c3d4680-83d0-11ea-8ad3-8e6e7507239f.png)

### Environment

<details><pre>
 - OS: Windows 10
 - Browser Chrome
 - Version 80.0.3987.163 (Official Build) (64-bit)
</pre></details>

#### Additional context
Just completing the tasks

#### Output in Web Console

<details><pre>

No show results in the otuput screen

</pre></details>

**Comment by krusche** [comment]
1 Test fails. Please read the feedback by clicking on „0 of 1 tests passing“, this is not a bug in Artemis. If you think the feedback or test is wrong, please contact the instructor of the course
