### ISSUE TITLE
Reflect Gitlab URL changes

### ISSUE THREAD

**Issue by sleiss** [ls1intum/Artemis#1336]
Check if we already use the new URL with the seperator `/-/` and adjust if we do not.

https://gitlab.com/gitlab-org/gitlab/-/issues/214217

**Comment by dfuchss** [comment]
@sleiss is this issue still active :) ?

**Comment by sleiss** [comment]
@dfuchss It seems that no issues with this occurred in the last 2 years, so I'll close it :wink:
