### ISSUE TITLE
Lost focus when hitting enter in assessment

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#1345]
### Describe the bug
When I hit enter in a textfield of the assessment (in a diagram) the enter will occurr (the cursor moves one line down) but the input field immeadiatly looses focus. To write the new line of text you have to click in the input field again to reset the focus.

#### To Reproduce
1. Start diagram assessment (possibly on other exercise types as well)
2. Doubleclick an element of the diagram to add some comment
3. Write some text, enter
4. See how the cursur moves and how the focus shifts
5. Try to write something again
6. Get annoyed :P

#### Expected behavior
Simple enter, you're able to continue writing in the next line.

### Environment
<details><pre>
 - OS: Win 10 Pro
 - Browser Chrome 81.0.4044.122
</pre></details>

#### Output in Web Console
Nothing

**Comment by TobiasPr** [comment]
@julian-christl thank you for pointing out so many usability bugs. Please continue reporting when you find issues, I really appreciate it. This issue is resolved in the next Apollon Version and will be included in the next Artemis deployment
