### ISSUE TITLE
Unexpected Authorization Error

### ISSUE THREAD

**Issue by paul-schaaf** [ls1intum/Artemis#1349]
### Describe the bug
When I click on the the course "Grundlagen: Algorithmen und Datenstrukturen" and then on Aufgabe 1 - Labyrinth. Un "Unauthorized" error message appears even though I am authorised since I enrolled in the course. It disappears after some seconds. Also, even though I get the error message, the page loads just fine with all the content. I've been able to reproduce this behaviour when clicking on exercises in my pgdp course as well but it seems to appear on *programming* exercises only.

#### To Reproduce
see above.

#### Expected behavior
no error message

#### Screenshots
<img width="1665" alt="Screenshot 2020-04-25 at 16 14 22" src="https://user-images.githubusercontent.com/29666990/80282324-16817c80-8711-11ea-9cc5-db39d81b0618.png">
<img width="1659" alt="Screenshot 2020-04-25 at 16 21 20" src="https://user-images.githubusercontent.com/29666990/80282329-1b463080-8711-11ea-80e6-5bba1a549aee.png">

### Environment

<details><pre>
 - OS: MacOS 10.15.3
 - Browser: Chrome
 - Version 81.0.4044.113 (Official Build) (64-bit)
</pre></details>

#### Output in Web Console

<details><pre>
zone.js:3324 GET https://artemis.ase.in.tum.de/api/programming-exercises/1171 403:

detail: "Access is denied"
message: "error.http.403"
path: "/api/programming-exercises/1171"
status: 403
title: "Forbidden"
type: "https://www.jhipster.tech/problem/problem-with-message"

instrument.js:110:
{
  "headers": {
    "normalizedNames": {},
    "lazyUpdate": null
  },
  "status": 403,
  "statusText": "OK",
  "url": "https://artemis.ase.in.tum.de/api/programming-exercises/1171",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for https://artemis.ase.in.tum.de/api/programming-exercises/1171: 403 OK",
  "error": {
    "type": "https://www.jhipster.tech/problem/problem-with-message",
    "title": "Forbidden",
    "status": 403,
    "detail": "Access is denied",
    "path": "/api/programming-exercises/1171",
    "message": "error.http.403"
  }
}
</pre></details>

**Comment by krusche** [comment]
not reproducible any more / was fixed
