### ISSUE TITLE
Option to hide a course

### ISSUE THREAD

**Issue by fyassine** [ls1intum/Artemis#1370]
### Is your feature request related to a problem?

In the main menu there is no option to hide a course
### Describe the solution you'd like

an option or a field when clicked the course disapears

**Comment by LadnerJonas** [comment]
Every time you open the Artemis home page, you are greeted by the tutorial course, on which most students have a score of 5.6%. This leads to a moment of shock at first glance. Could therefore this feature be reconsidered again?
![image](https://user-images.githubusercontent.com/92096842/165636190-799992b7-5554-48a3-ba5d-ee1332a6eac0.png)

**Comment by krusche** [comment]
We think about a solution for this issue, we could treat the tutorial course in a special way and move it e.g. down into a separate section that you can then collapse

**Comment by ge65cer** [comment]
#334
