### ISSUE TITLE
Assess next submission takes forever on Safari

### ISSUE THREAD

**Issue by JohannesStoehr** [ls1intum/Artemis#1378]
### Describe the bug
After assessing a text exercise pressing "assess next submission" starts a loading animation but nothing else happens on Safari.
Firefox and Chrome continue after a few seconds.

#### To Reproduce

1. Assess an text exercise
2. Click on "assess next submission"
3. Wail till eternity

#### Screenshots
![Bildschirmfoto 2020-05-03 um 13 30 17](https://user-images.githubusercontent.com/38322605/80913687-ccb71880-8d46-11ea-8c17-210bfab118b4.png)

### Environment

<details><pre>
 - OS: MacOs
 - Browser: Safari
 - Version: newest stable versions
</pre></details>

**Comment by chinmay5** [comment]
Clicking on the `Assess Next Submission` is not causing any request to be sent.

![image](https://user-images.githubusercontent.com/16525717/81052469-c4d0b300-8ec3-11ea-85fe-7c1e9ff369be.png)

**Comment by julian-christl** [comment]
@chinmay5 
Actually it is sent. You can see this in your screenshot as well. It's the "submit" request which was made ca. 10s prior to your screenshot.

I had this issue just recently and check the content of the request, all feedbacks were there.
I then went back to the dashboard and reopended the submission, the assessment was sent and all feedback was there.

If this description does not fit your case maybe provide better proof to your case in order for them to find the source of the problem.

**Comment by jpbernius** [comment]
The request is not sent in some cases. We are currently testing the fix for this.
