### ISSUE TITLE
Non existing lock presented on complaint view

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#1383]
### Describe the bug
If you assess a complaint on the top right corner will be displayed who had the lock for the original assessment, the complaint function ifself has no lock feature though.

#### To Reproduce
1. Submit something (e.g. a Text Exercise) with P1
2. Assess it with P2
3. Complain on this assessment with P1
4. Assess the complaint with P3
5. Have a look on the top right corner. This should state "Locked by P2" or something

#### Expected behavior
There is no lock message or there is something stated, maybe not in red, like "Assessment by P2"
"Lock by ..." makes people think there is a lock on the complaint which they don't have access on.

In addition: if you are the Person that was complained about it shoud probably explain why you don't have access to it (beeing able to update or reject) to prevent confusion.

#### Additional Information ####
![4405acb8492eb4f21150755efd9b4596](https://user-images.githubusercontent.com/64264938/80957719-07cb5180-8e04-11ea-92de-f3486356eb2e.png)
This is not an active complaint but a resolved one but the view is the same.
I blacked out the name of the tutor who assessed the submission originally, the submission itself and the grading criteria.

You can see the lock message on the top right corner. It relates only to the assessment itself, bit is quite misleading in my opinion.

### Environment

<details><pre>
 - OS: Windows Pro
 - Browser: Chrome v81.0.4044.129
</pre></details>

**Comment by krusche** [comment]
I do not fully understand this bug. Could you please add a screenshot (and black out / blur the confidential parts). I think this would help a lot

**Comment by julian-christl** [comment]
@krusche I've edited the original post and extended it by a subtopic "additional information". 
Regarding the view of the original assessor I think it still says that "You have the lock for this assessment", not sure for a 100% though since it was not my assessement someone complained about.
I hope this helps you understand, if not, let my know what you need.

**Comment by krusche** [comment]
Yes, this helps. We should fix this!

**Comment by krusche** [comment]
@HanyaElhashemy could you please take a look? We should hide this information in the user interface and also remove it from the server response

**Comment by julian-christl** [comment]
Could be linked to #1450

**Comment by julian-christl** [comment]
@krusche thb I would not hide this information since often if this is a tricky situation I like to get back to the original assessor and ask him why he did xyz. This helps to improve the quality of the complaint assessment.
