### ISSUE TITLE
Artemis wasn't able to display the points accumulated by the drag and drop function in text exercises

### ISSUE THREAD

**Issue by amahmario** [ls1intum/Artemis#1388]
### Describe the bug

When you want to assess text exercises from the students, and use the drag and drop function with the assessment templates which are located under "Assessment of the Definition", the points are not counted and accumulated directly. The students points count stays by "**0/2**"
At first you have to manually click on the points (Increase or Decrease) and just then the points get counted and accumulated correctly and displayed (e.g "**2/2**").

#### To Reproduce

1. Go to 'Tutor Course Dashboard'
2. Click on "Exercise Dashboard' of a Test Exercise
2. Click on 'Start new assessment'
3. Drag and Drop the assessment templates provided by the instructors which are located under "Assessment of the Definition" on the right side
4. Now you can see no change in the points the student would have at the moment. The Counter stays at "**0/2**"

#### Expected behavior

After dragging and dropping the assessment templates, the points for the student should directly match the points given by the used assessment templates

#### Screenshots
![Bildschirmfoto 2020-05-04 um 18 53 00](https://user-images.githubusercontent.com/64026264/80992719-3bc16980-8e3a-11ea-91fe-d1db6ea3fde6.png)

### Environment

<details><pre>
 - OS: macOS Catalina
 - Browser safari
 - Version 13.1
</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by krusche** [comment]
Thanks for the bug report, I think this is a duplicate
@HanyaElhashemy can you confirm?
