### ISSUE TITLE
Duration Selector for Quiz Exercises has unexpected bahvior

### ISSUE THREAD

**Issue by niclasschuemann** [ls1intum/Artemis#1391]
### Describe the bug
The duration for quiz exercises must be set with a minute and a seconds selector. 
If you increase the seconds selector by one if it is on 59, 60 seconds will be displayed. After increasing again, the minute selector will increase by 3. 
If you decrease the seconds selector by one if it is on 00, -1 seconds will be displayed. After decreasing again, the minute selector will be decreased by 3.
This applies if the focus is held on the specific selector.

#### To Reproduce

As an Instructor
1. Go to Course Management > Exercises > Quiz Exercises
2. Create a new Quiz Exercise
3. In the editor, set the seconds selector to 59 and the minute selector to 0
4. Increase the seconds selector by one and again by one.
5. In the editor, set the seconds selector to 00 and the minute selector to 3
6. Decrease the seconds selector by one and again by one.

#### Expected behavior
If you increase the seconds selector, that is set to 59, by one, 00 should be displayed in the seconds selector and the minute selector should increase by one.
If you decrease the second selector, that is set to 00, by one, 59 should be displayed in the seconds selector and the minute selector should decrease by one.

#### Screenshots

![1](https://user-images.githubusercontent.com/45300855/81026434-63d0bd00-8e7a-11ea-98d4-df8f17682d12.PNG)
![2](https://user-images.githubusercontent.com/45300855/81026436-66331700-8e7a-11ea-8204-8cffa45a4531.PNG)
![3](https://user-images.githubusercontent.com/45300855/81026439-67644400-8e7a-11ea-80b9-ea985af8c9b1.PNG)

### Environment

<details><pre>
 - OS: Windows 10 Pro
 - Browser: Google Chrome
 - Version  81.0.4044.129
</pre></details>

**Comment by krusche** [comment]
Thanks for finding the issue, should be fixed, but is not urgent, instructor should be careful when entering the duration
