### ISSUE TITLE
Drag-And-Drop Question Preview loads forever on empty background image

### ISSUE THREAD

**Issue by niclasschuemann** [ls1intum/Artemis#1392]
### Describe the bug
The preview of Drag-And-Drop questions in quiz exercises loads forever if no background image is set.

#### To Reproduce

As an instructor
1. Go to 'Course Management' > 'Exercises' > 'Quiz Exercises'
2. Create a new quiz exercise
3. Add a Drag-And-Drop question
4. Open the preview of this question by clicking the 'Preview' button.

#### Expected behavior

The 'Preview' button should be disabled with a tooltip similar to "A background image must be set before a preview can be generated"

#### Screenshots
![preview](https://user-images.githubusercontent.com/45300855/81026949-3127c400-8e7c-11ea-8aeb-e6363193cfd5.PNG)
![loading](https://user-images.githubusercontent.com/45300855/81026952-32f18780-8e7c-11ea-962b-c8c7fbb76d70.PNG)

### Environment

<details><pre>
 - OS: Windows 10 Pro
 - Browser: Google Chrome
 - Version  81.0.4044.129
</pre></details>

**Comment by krusche** [comment]
The picture is not available then. I don't consider this as a real bug, but we should probably show a warning here that the preview only works if the image was uploaded before.
Another alternative would be to only display the Preview button if the image was uploaded before
