### ISSUE TITLE
Question score can be set to a negative number

### ISSUE THREAD

**Issue by niclasschuemann** [ls1intum/Artemis#1393]
### Describe the bug
The score of Multiple-Choice, Drag-And-Drop and Short-Answer questions on quiz exercises can be set to a negative number. Scoring 100% on that quiz leads to a decrease in total points for the student.

#### To Reproduce
As an instructor
1. Go to Course Management > Exercises > Quiz Exercises
2. Create a new Quiz Exercise
3. Add a Multiple-Choice question
4. Set the score of that question to -100
5. Save the quiz exercise

#### Expected behavior
It should not be possible to save the quiz exercise if the Max. Score of that quiz is <= 0
It should not be possible to enter a negative number into the score input box.

#### Screenshots
![negative](https://user-images.githubusercontent.com/45300855/81027439-0e96aa80-8e7e-11ea-9b75-45a6caf6ecab.PNG)

### Environment

<details><pre>
 - OS: Windows 10 Pro
 - Browser: Google Chrome
 - Version  81.0.4044.129
</pre></details>

**Comment by krusche** [comment]
good catch, should be fixed. I hope instructors do not do that though ;-)
