### ISSUE TITLE
Enable scrolling while dragging predefined feedback in modeling and text exercise assessments

### ISSUE THREAD

**Issue by niclasschuemann** [ls1intum/Artemis#1394]
### Is your feature request related to a problem?
When assessing text and modeling exercises, the predefined drag and drop feedback boxes are a great way to speed up the process for similar submissions. However, these drag and drop boxes do not always fit on the screen together with the submission. This is especially the case for text-based exercises with short answers. In this case, not every predefined feedback box is reachable anymore and therefore cannot be used.

### Describe the solution you'd like
Enable scrolling while you are dragging a predefined feedback box.

### Describe alternatives you've considered
Using the built-in zoom feature of the browser. Zooming out makes everything visible and draggable, but this only works to a certain extent. Users on small laptops won't be able to read the submission anymore if they have to zoom out in order to reach the predefined feedback and drag it onto the submission.

### Additional context
I talked to Hanya about details on Slack.

**Comment by krusche** [comment]
@niclasschuemann I had to remove your screenshots. Please do not upload them in case they include real solutions or real grading instructions of courses on Artemis. Please use fake or example data

**Comment by HanyaElhashemy** [comment]
@niclasschuemann Could you please elaborate more? As seen in the screencast below it is indeed possible using a small screen to scroll while dragging the grading instruction. Maybe you need to adapt your browser settings?
![78889936-f8efba00-7a64-11ea-871d-5d1edcdc2605](https://user-images.githubusercontent.com/50635005/81429549-3af04680-915e-11ea-8d30-ad7431ffafb3.gif)
