### ISSUE TITLE
Not able to copy from text exercises

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#1399]
### Describe the bug
Since the primary usage of the mouse is clicking on a text segment in order to place a feedback it's no longer possible to mark text.

This results in not beeing able to copy from the submission to check the length of the submission or check wether something's copied. This results in having to retype all the text you would usually copy.

#### To Reproduce
1. Assess one text submission
2. Try to mark text

#### Expected behavior
Differ between trying to select (Mouse hold) and clicking for a feedback box.

#### Screenshots
Best to try it yourself.

### Environment

<details><pre>
 - OS: Windows 10 Pro
 - Browser: Chrome v81.0.4044.129
</pre></details>

**Comment by jpbernius** [comment]
It is not possible to copy the text when defining manual text blocks, also the length is now displayed.
Therefore closing this issue.
