### ISSUE TITLE
Hints not shown in problem statement

### ISSUE THREAD

**Issue by sleiss** [ls1intum/Artemis#1400]
### Describe the bug
Hints added to a problem statement should be shown in the problem statement to students.
Currently it is only visible in the Code editor but not in the problem statement in the exercise view.

#### To Reproduce
Follow the steps described in TC345 (TP4, TS53) in TestQuality.

#### Expected behavior
![image](https://user-images.githubusercontent.com/5084100/81067538-19355c00-8edf-11ea-8a9b-3dd048d93c41.png)
Here, a question mark should be added like it is in the code editor view:
![image](https://user-images.githubusercontent.com/5084100/81067601-336f3a00-8edf-11ea-9caa-68b82cc5ef5e.png)

**Comment by krusche** [comment]
I guess this feature was not fully developed. Maybe @thilo-behnke can say something about it?

**Comment by krusche** [comment]
I just tested it and this issue still occurs
