### ISSUE TITLE
Modeling Exercise visibile to student before release

### ISSUE THREAD

**Issue by TobiasPr** [ls1intum/Artemis#1404]
### Describe the bug

Modeling Exercise is visible to students before they are released (release date passed)

#### To Reproduce

1. Create an Modeling Exercise with release Date 15 mins in future
2. Change account to student account and navigate to course overview 
3. Exercise is visible and the student can start the exercise (see screenshot)

#### Expected behavior

Exercise is not visible for student before release date has passed

#### Screenshots

![image](https://user-images.githubusercontent.com/22955066/81081709-90282000-8ef2-11ea-938a-ccc59997201c.png)

![image](https://user-images.githubusercontent.com/22955066/81081397-2576e480-8ef2-11ea-9b7f-dbc16d3b9af7.png)

![image](https://user-images.githubusercontent.com/22955066/81081496-43444980-8ef2-11ea-80fc-14f752ec3d70.png)

### Environment
https://artemistest.ase.in.tum.de/

**When fixed please update https://ls1intum.testquality.com/project/10165/plan/17385/test/239506**

**Comment by krusche** [comment]
Are you 100% sure that you tried it out as a student? In the second image there is a "Not released" tag, which is only shown to tutors / instructors

**Comment by TobiasPr** [comment]
Yeah you are right, I had a wrong mapping of course tutors to the student group
