### ISSUE TITLE
Creating a Lecture with Empty Fields

### ISSUE THREAD

**Issue by Varnika-Tyagi** [ls1intum/Artemis#1407]
### Describe the bug
At the moment, it is possible to create a lecture with all fields empty (incl. title, description, start and end dates). 
Perhaps, a constraint "Title of lecture should be specified" needs to be enforced.

#### To Reproduce

1. Log in to Artemis as instructor and navigate to the "Course Management"
2. Click on "Lectures"
3. Click on "Create Lecture"
4. Leave all fields empty and press "Save"
5.  A new lecture is created with an identifier.

#### Screenshots
![Creating a lecture with empty fields](https://user-images.githubusercontent.com/17163093/81091956-362e5700-8f00-11ea-8208-799af3f5e852.PNG)

**Comment by krusche** [comment]
I agree, the title should not be empty, this does not make sense!
