### ISSUE TITLE
View Exercise Score Details as an instructor

### ISSUE THREAD

**Issue by amahmario** [ls1intum/Artemis#1408]
### Describe the bug
When an instructor profile clicks on an exercise and then on "score", there is shown no submission by any student profile.

#### To Reproduce
1. Go to an exercise
2. Click on 'Score'
3. See 0 displayed student submissions.

#### Expected behavior
All student submissions should be displayed after clicking on score of an exercise.

#### Screenshots
![Bildschirmfoto 2020-05-05 um 19 29 47](https://user-images.githubusercontent.com/64026264/81096702-19495200-8f07-11ea-96ae-2c35e7bc6d67.png)

### Environment

<details><pre>
 - OS: macOS Catalina
 - Browser safari
 - Version 13.1

</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by krusche** [comment]
@amahmario Can you please specify more details. 
Which exercise type did you use?

The score page is supposed to only show results, not submissions. So in case of modeling, text and file upload exercises: if the student submits, instructors won't be able to see this on the Scores page. They can view it in the participation and in the submission page though. (The submissions page is currently hard to find, which is something that we should improve in the future!)

I will close this issue for now. In case you think something is definitely wrong here, please provide more information and then reopen the issue.
