### ISSUE TITLE
Make Quiz Exercises Test run for TAs more visible when exercise is not released

### ISSUE THREAD

**Issue by laramarie** [ls1intum/ArTEMiS#141]
Currently, tutors can see quiz exercises, but they cannot test them if they are not yet released. To get a feeling for the quiz and to be able to (easily) check the quiz setup and content, it would be good if tutors would be able to participate in quizzes before they are released, similar to the coding exercises.

**Comment by laramarie** [comment]
UPDATE: I just noticed that there is this functionality under Course Administration - might be good to move it to the overview so that it's accessible the same way as programming exercises, right now it's very hard to find (and none of us tutors knew about it)

**Comment by krusche** [comment]
We have made the arrangements of the buttons a bit more obvious (I hope so at least) in the latest release.
