### ISSUE TITLE
Strange Behaviour of Step Indicator in Guided Tour

### ISSUE THREAD

**Issue by stefanwaldhauser** [ls1intum/Artemis#1411]
### Describe the bug

The step indicator at the bottom of the tutorial window exhibits unexpected behaviour:

- the number of dots sometimes change when the next step is clicked
- the number of dots does not correspond to the number of steps in the guided tour
- the active dot does not change even though the next step is clicked

#### To Reproduce

Start a tour with many steps like the general tour of the tutorial course and just click through the tour and watch the step indicator below

#### Expected behavior

- the number of dots should be equal to the number of steps
- the active dot should change when the next / previous button is clicked

#### Screenshots

![image](https://user-images.githubusercontent.com/29718932/81108577-30913b00-8f19-11ea-8659-f44ce791a078.png)
![image](https://user-images.githubusercontent.com/29718932/81108594-371fb280-8f19-11ea-982f-470e77723c98.png)

### Environment

<details><pre>
 - OS: [e.g. iOS] OSX
 - Browser [e.g. chrome, safari] Chrome 
 - Version [e.g. 22] Version 84.0.4128.3 (Official Build) dev (64-bit)
</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by ge65cer** [comment]
@stefanwaldhauser Please re-check if this is still an issue or close it.
