### ISSUE TITLE
Contact Us Mail is undefined

### ISSUE THREAD

**Issue by stefanwaldhauser** [ls1intum/Artemis#1412]
### Describe the bug
The "Contact Us" Mail is undefined. 

#### Expected behavior

Some Mail Address should be there

#### Screenshots

![image](https://user-images.githubusercontent.com/29718932/81109378-494e2080-8f1a-11ea-9535-e1a9d6ea2739.png)
![image](https://user-images.githubusercontent.com/29718932/81109394-50752e80-8f1a-11ea-8547-86bf13181f25.png)

### Environment

<details><pre>
</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by krusche** [comment]
Thanks for spotting this error. I'll fix it

**Comment by krusche** [comment]
fixed!
