### ISSUE TITLE
Lecture Attachment without Release Date visible to student

### ISSUE THREAD

**Issue by Varnika-Tyagi** [ls1intum/Artemis#1413]
### Describe the bug
Creating an attachment without adding any release date causes the attachment to immediately be visible to the test user (with student status)
#### To Reproduce

1. As Instructor, Go to Course Management->Lectures->Add Attachment
2.  Leave the "Release Date" field empty and press "Save"
3. Log In as Student and select the course in the Course Overview. 
4. Click on Lectures, select the relevant lecture (e.g. Test Lecture 01) and view the lecture attachments.
5. The attachment without release date is visible to the student. (see screenshot)

####Screenshot
![Attachment without release date still visible to student](https://user-images.githubusercontent.com/17163093/81120288-b10d6700-8f2c-11ea-8dd0-e139e45abdac.PNG)

**Comment by Varnika-Tyagi** [comment]
In the same context, right now, it is also possible to set the Release date to some past date. Perhaps, it would be better if a constraint such as "Set an appropriate Release date" can be implemented.

**Comment by krusche** [comment]
I think this behavior is fine. There might be lectures in the future in which instructors want to release the attachment immediately, i.e. without release date. Also setting it into the past is not harmful (even if it does not make much sense), so I do not consider this as a bug
