### ISSUE TITLE
Quiz Multiple Choice Preview breaks page layout

### ISSUE THREAD

**Issue by niclasschuemann** [ls1intum/Artemis#1414]
### Describe the bug
Using a long question text results in the layout being broken when displayed in preview mode.

#### To Reproduce

1. Go to 'Course Management' > 'Exercises' > 'Quiz Exercises'
2. Create a new quiz exercise
3. Add Multiple Choice Question
4. Add a very long question description
4. Click on 'Preview'.

#### Expected behavior
The formatting of the page should scale with the length of the question. Other UI elements should not cover parts of the question text.

#### Screenshots
![formatting](https://user-images.githubusercontent.com/45300855/81123547-9c809d00-8f33-11ea-9262-fe9789cda5e4.PNG)

### Environment

<details><pre>
 - OS: Windows 10 Pro
 - Browser: Google Chrome
 - Version  81.0.4044.129
</pre></details>

**Comment by krusche** [comment]
Quiz questions should rather be short, so this is a low priority issue, but we should definitely fix it.
@filip-gregurevic you are working with the Markdown Editor, could you have a look when you have time?

**Comment by filip-gregurevic** [comment]
> Quiz questions should rather be short, so this is a low priority issue, but we should definitely fix it.
> @filip-gregurevic you are working with the Markdown Editor, could you have a look when you have time?

That definitely should not look like that. I'll have a look into it 🤓
