### ISSUE TITLE
Problem with defining drop locations for different image sizes in DnD quiz exercises

### ISSUE THREAD

**Issue by niclasschuemann** [ls1intum/Artemis#1415]
### Describe the bug
Uploading a small image as a background image for DnD questions works fine. If another, larger image is uploaded, drop locations cannot be drawn at the locations that have not been covered by the smaller image. Apparently Artemis does not reset the new possible draw locations after uploading a new image. This also happens with larger to smaller images. In this case, it is possible to create drop locations on top of Artemis UI elements, like the preview button. This leads to these buttons being unusable.

#### To Reproduce

1. Go to 'Course Management' > 'Exercises' > 'Quiz Exercises'
2. Create a new quiz exercise
3. Add a Drag-And-Drop Question
4. Pick a small image as the background image
5. Upload another, larger image as the background image
6. Try to create a drop location on the new large background image that would not have been covered by the small image

#### Expected behavior
Artemis should recalculate possible locations for drop locations whenever a new image is uploaded.

#### Screenshots
It cannot really be shown through screenshots.

### Environment

<details><pre>
 - OS: Windows 10 Pro
 - Browser: Google Chrome
 - Version  81.0.4044.129
</pre></details>

**Comment by krusche** [comment]
Thanks for thoroughly testing DnD questions, we should fix this at some point, but it's not a high priority. Instructors should only replace images with similar sizes, otherwise they need to recreate drop locations

**Comment by julian-christl** [comment]
Just tested, this issue has been fixed in the meantime.
