### ISSUE TITLE
Adding presentation score doesn't work

### ISSUE THREAD

**Issue by JohannesStoehr** [ls1intum/Artemis#1419]
### Describe the bug
Adding a presentation score leads to an error message and after reloading the page the score is gone again.

#### To Reproduce

1. Add a presentation score to a student
2. See error and increased score
3. Reload page
4. Score is gone again

#### Screenshots
![Bildschirmfoto 2020-05-06 um 10 15 08](https://user-images.githubusercontent.com/38322605/81152692-7a623b80-8f82-11ea-9e00-2a9774b58039.png)
### Environment

<details><pre>
 - OS: Windows 10, MacOs
 - Browser: Chrome, Safari, FireFox
 - Version: newest stable versions
</pre></details>

**Comment by krusche** [comment]
Do you see a more detailed error message in the console or network response?

**Comment by krusche** [comment]
The server seems to have a parsing error:

```
Bad Request: JSON parse error: Cannot deserialize value of type `java.time.ZonedDateTime` from String ""2020-04-17T15:19:19.000Z"": Failed to deserialize java.time.ZonedDateTime: (java.time.format.DateTimeParseException) Text '"2020-04-17T15:19:19.000Z"' could not be parsed at index 0; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.time.ZonedDateTime` from String ""2020-04-17T15:19:19.000Z"": Failed to deserialize java.time.ZonedDateTime: (java.time.format.DateTimeParseException) Text '"2020-04-17T15:19:19.000Z"' could not be parsed at index 0
May 06 10:28:27 vmbruegge106 java[126860]:  at [Source: (PushbackInputStream); line: 1, column: 88] (through reference chain: de.tum.in.www1.artemis.domain.participation.StudentParticipation["initializationDate"])
```

**Comment by krusche** [comment]
So apparently, the quotes are inserted twice here, which is really a weird error
<img width="535" alt="image" src="https://user-images.githubusercontent.com/744067/81154947-b5fe0500-8f84-11ea-8c04-b2293677636b.png">

**Comment by krusche** [comment]
I think I found the problem and fixed it. I'll deploy a hot fix in a few minutes after verifying the fix

**Comment by tiffca** [comment]
Not sure how to officially "link" this to Test Quality, but it does have a test case and failed in the test env during yesterday's testing. 
https://ls1intum.testquality.com/project/10165/plan/17385/run/137794/result/fullscreen/1986643

**Comment by krusche** [comment]
fixed!

**Comment by tiffca** [comment]
I probably should've created a bug for this yesterday, sorry about that - I didn't think of it at the time! Thanks Johannes and Stephan!
