### ISSUE TITLE
Alert the creator of a quiz question if the (short) question title is too long.

### ISSUE THREAD

**Issue by laramarie** [ls1intum/ArTEMiS#142]
The (short) question title seems to be limited to a certain length. However, this is not visible to the creator of a quiz question. Saving of the question will fail with a very unspecific error message.

The console shows the following:
- Failed to load resource: the server responded with a status of 500 ()
- Saving Quiz Failed! Please try again later.

Ideally, the question creator should be directly informed if the text field's data is longer than the allowed amount of characters before trying to save.

**Comment by krusche** [comment]
Is fixed in the newest release 2.3.3
