### ISSUE TITLE
Embedded example solution is cut off for modeling exercises

### ISSUE THREAD

**Issue by pzdr7** [ls1intum/Artemis#1437]
### Describe the bug

In some cases, not the entire example solution is shown when assessing a modeling exercise. It appears to ignore labels on associations and only show the area delimited by objects and associations. This seems to occur both in the 'Exercises' view (when viewing the details of the exercise) and when assessing submissions.

#### To Reproduce

1. Create a modeling exercise that has a sample solution that fulfills the description above (an example can be found as a screenshot below - in our case, this was a communication diagram)
2. Navigate to 'Course Management'.
3. Go to 'Exercises' of the corresponding course
4. Click the ID of the newly created exercise.
5. Scroll to the embedded sample solution. Its labels should be cut off.

Additionally, you may follow the following steps to find another occurrence of this:

6. Submit a solution to the exercise
7. Navigate to 'Course Management' and go to the Tutor Course Dashboard of the corresponding course.
8. Navigate to the Exercise Dashboard of the exercise in question.
9. If available, start an assessment on any submission (or, alternatively: click on "Instructions" on the right)
10. Scroll to the embedded sample solution. Its labels should be cut off without the ability to scroll.

#### Expected behavior

The entire sample solution should be shown, including the labels on associations (including the ability to scroll if necessary).

#### Screenshots

This is an example solution that has caused this issue. Note that there are messages/labels that are above the topmost association. Note that I have cropped the screenshots in order to prevent revealing too much about the exercise (this task is the L03E03 Model a Communication Diagram exercise from EIST 2020 - if you need the full images, please contact me directly)

![image](https://user-images.githubusercontent.com/38403547/81438018-582c1180-916c-11ea-8db7-76370c207c17.png)

This is the resulting view of the example solution in the assessment view. The corresponding messages/labels are now gone and there is a label on the left that is cut off by the surrounding container (without the ability to scroll).

![image](https://user-images.githubusercontent.com/38403547/81438058-6c700e80-916c-11ea-9095-661643803826.png)

### Environment

<details><pre>
 - OS: Windows 10
 - Browser: Google Chrome v81.0.4044.138
</pre></details>

**Comment by krusche** [comment]
I guess this problem also occurs when creating drag and drop model quizzes for communication diagrams. Please also double check if something is cut off then
