### ISSUE TITLE
Hitbox of Associations during Assessment

### ISSUE THREAD

**Issue by tobiasschamel** [ls1intum/Artemis#1438]
### Is your feature request related to a problem?
When assessing modeling exercises using the drag & drop elements, it is really difficult to drop the elements on associations, as their hitbox is really small.
This is especially frustrating on straight lines. Angular lines seem to have a larger hitbox (the whole highlighted area).
<img width="1010" alt="Ohne Titel" src="https://user-images.githubusercontent.com/58089908/81469696-bdbce400-91e6-11ea-902e-d38469dd4582.png">

### Describe the solution you'd like
Increase the hitbox of association/lines between entities.

**Comment by TobiasPr** [comment]
@tobiasschamel this is fixed in Apollon version 2.0.15 and will be included in Artemis today
