### ISSUE TITLE
Text Exercise Assessment not Saved & Text messed up

### ISSUE THREAD

**Issue by tobiasschamel** [ls1intum/Artemis#1439]
### Describe the bug
When assessing text exercises and returning to the dashboard, everything looks fine. But after re-entering a finished assessment, some of the assessment blocks (incl. points) disappear. Sometimes the text appears to be messed up, too (at the former position/edges of assessment boxes).

#### To Reproduce

1. Assess H01E02 Change in Software Development
2. Submit grading
3. Return to Dashboard (points are correct)
4. Open Assessment again
5. See error (points & boxes partly missing)
5.1 Sometimes formatting of text messed up.

#### Expected behavior
Results are saved permanently, the text stays the same.

#### Screenshots

<img width="1676" alt="Ohne Titel1" src="https://user-images.githubusercontent.com/58089908/81472792-70e30880-91fa-11ea-8e2e-418b0c058481.png">

### Environment

<details><pre>
 - OS: macOS Catalina 10.15.4 (19E287)
 - Browser: Safari Version 13.1 (15609.1.20.111.8), Chrome 81.0.4044.138
</pre></details>

**Comment by julian-christl** [comment]
From the API's perspective it seems again that it' the same like here:
https://github.com/ls1intum/Artemis/issues/1372#issuecomment-622607998
Feedbacks were saved correctly but the references/textblocks are messed up.

**Comment by julian-christl** [comment]
@jpbernius Since you were responsible for the #1372 this might interest you.
