### ISSUE TITLE
Modeling exercise: diagram type is reset to UML Class Diagram

### ISSUE THREAD

**Issue by krusche** [ls1intum/Artemis#1461]
When saving the example solution of a modeling exercise (with diagram type other than class diagram), the diagram type is reset to class diagram. This means that suddenly other model elements are shown on the right side. This should not happen, the diagram type should stay the same.

**Comment by krusche** [comment]
This also happens when students model in team exercises and the model is automatically synced over web socket:
https://i.imgur.com/oeZqevf.gifv

**Comment by TobiasPr** [comment]
Solved in Apollon
