### ISSUE TITLE
Backspace in General Feedback box removing multiple characters

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#1465]
### Describe the bug
Backspace removes two characters in the General Feedback box if the letter before the last letter is a space character.
This is reproducable as well if there are multiple space characters but not if the last character is a space character itself.

#### To Reproduce
1. Start an assessment (tested with text assessments)
2. Write something in General Feedback
3. Hit Spacebar
4. Write one more character
5. Hit Backspace
6. See that the space character was removed as well

#### Expected behavior
Only one character gets removed.

### Environment

<details><pre>
 - OS: Windows 10 Pro
 - Browser: Chrome v81.0.4044.138
</pre></details>

### Video
[![Screenshot from Gyazo](https://gyazo.com/21c4124c26a5f6b7cdc9078e74a177b9/raw)](https://gyazo.com/21c4124c26a5f6b7cdc9078e74a177b9)

#### Additional context
This behaviour looks like there could be some trimming happening on backspace.

#### Output in Web Console
n/a

**Comment by tiffca** [comment]
I want to assign this to myself

**Comment by tiffca** [comment]
I'm not sure why the text is trimmed in assessment-general-feedback.component.ts but I'll try debugging it 
<img width="635" alt="image" src="https://user-images.githubusercontent.com/63906424/82038574-015e9480-96a4-11ea-8d75-b0ecc9734d1c.png">
