### ISSUE TITLE
Text exercise (assessment): when using "Next Assessment" the complete next assessment is marked

### ISSUE THREAD

**Issue by florian-glombik** [ls1intum/Artemis#1466]
### Describe the bug

When assessing the next submission by using the "Next Assessment" button, the students submission is marked as one sentence. 
_(Reloading the page seems to resolve the issue in most cases.)_
#### To Reproduce

1. Go to the tutor's exercise dashboard for a text exercise _(with at least 2 submissions)_
2. Click on _Start new assessment_ and assess the first submission
3. Click on _Next Assessment_
4. The new submission will be recognized as one sentence

#### Expected behavior

It should be possible to assess each sentence on its own.
#### Screenshots

![Assessment komplett markiert](https://user-images.githubusercontent.com/63976129/81857225-3c58af00-9562-11ea-913d-99185d7f9363.PNG)

![Assessment komplett markiert - 2](https://user-images.githubusercontent.com/63976129/81857232-3d89dc00-9562-11ea-8d52-774651572de4.PNG)

### Environment

<details><pre>
- OS: Windows 10 Pro
- Browser: Google Chrome
- Version 81.0.4044.138 
</pre></details>

**Comment by julian-christl** [comment]
As some tutors pointed out this usually happens with German submissions.
Sometimes it happens with English ones as well but tbh sometimes English ones are marked as German.
Therefore it might be a good start to check if it has something to do with submissions marked as German.

Besides: a workaround is to simply reload the page. Then the selection of the text is back to normal.
