### ISSUE TITLE
Incorrect automatic assessment

### ISSUE THREAD

**Issue by Alexanderkrp** [ls1intum/Artemis#1467]
### Describe the bug
When assessing the Analysis Object Model, some parts of the submission are wrongfully awarded points. Also there is some false Feedback that isnt represented by the example Solution.

#### To Reproduce

1. Go to H02E02 Bumpers Analysis Object Model
2. Start Assessing Submissions
3. Find the following errors:

#### Expected behavior

If in doubt the system should not be using automatic assessment, when it creates double the work for the user: user has to remove the wrong feedback/points and then he can start assessing.

#### Screenshots

![image](https://user-images.githubusercontent.com/52030186/81904157-2a5b2880-95c3-11ea-803b-72a38b39635b.png)
![image](https://user-images.githubusercontent.com/52030186/81904198-3b0b9e80-95c3-11ea-84cd-da24359f6aca.png)
![image](https://user-images.githubusercontent.com/52030186/81905067-7d81ab00-95c4-11ea-930b-4a42e362a166.png)

in contrast to:
![image](https://user-images.githubusercontent.com/52030186/81904231-48288d80-95c3-11ea-9dc5-2cc721850339.png)

**Are those maybe coming from the example submissions that you must do before one can start assessing submissions?**

### Environment

<details><pre>
 - OS: [Windows]
 - Browser [chrome]
 - Version [81.0.4044.138 ]
</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by tobiasschamel** [comment]
Imo the main reason for this issue is wrong input by tutors. It would be beneficial to have a 'clear assessment' button which just removes the whole automatic assessment (in the beginning, when I was the only one assessing, it worked really good - in the end, I was constantly removing the whole 'auto-assessment' stuff).

**Comment by krusche** [comment]
we are changing how the automatic assessments for modeling exercises work
