### ISSUE TITLE
Repeated copypasting in UML editor doesn't work

### ISSUE THREAD

**Issue by halbGefressen** [ls1intum/Artemis#1470]
When trying to copy-paste with Ctrl-C and Ctrl-V, it works as intended. But if you try to paste again without copying before (Ctrl-C, Ctrl-V, Ctrl-V), it moves the previously pasted element to the new location instead of creating a new element.

**Comment by TobiasPr** [comment]
@halbGefressen This will be fixed in the next version of Apollon 2.0.17 which should be included in the next Artemis release
