### ISSUE TITLE
Modeling Assessments: update pop-up on Submit "You will not be able to change it afterwards." 

### ISSUE THREAD

**Issue by tiffca** [ls1intum/Artemis#1479]
### Describe the bug
When you submit/override an assessment before the due date, you receive the following pop-up "You have not assessed all model elements. Are you sure you want to submit this assessment? You will not be able to change it afterwards." with the options to Cancel or press OK.

This could be improved to at least remove "You will not be able to change it afterwards." - because this is untrue (tutors can update assessments before the assessment due date). 
Or to remove the pop-up altogether, because it seems redundant. Especially for large models, tutors are unlikely to assess every single model element. 

#### To Reproduce

1. Start a new modeling assessment in Artemis 
2. Add one feedback on a model element, but don't give feedback on all of the elements
3. Click Submit
4. See the pop-up 

This happens for "Override assessment" button as well

#### Expected behavior
This will be improved to only show the pop-up if the submission is after the assessment due date. 

#### Screenshots
After hitting Submit
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/63906424/82118055-e871e400-9774-11ea-97e9-b400df76ecee.png">

### Environment
<details><pre>
 - Browser Firefox
 - Version 4.0.4 in Prod/live
</pre></details>

**Comment by tiffca** [comment]
Should we only update the text or remove the pop-up altogether?

**Comment by krusche** [comment]
I would only show it after the assessment due date (in case this is set)

**Comment by tiffca** [comment]
Cool, thank you! I'll look into it.
