### ISSUE TITLE
'Go To Repository' links just to Artemis Homepage in Update Manual Result

### ISSUE THREAD

**Issue by stefanwaldhauser** [ls1intum/Artemis#1480]
### Describe the bug

When you want to update the assesment of a programming exercise you have already assesed, the 'Go To Repository' Link just links to the Artemis Homepage but not to the repository any more.

#### To Reproduce

1. Evalute a programming exercise for the first time (go to repository works)
2. Finish it and open it again to reevalute (go to repository link is broken)

#### Expected behavior

Link should link to repository

#### Screenshots

![image](https://user-images.githubusercontent.com/29718932/82119149-7c937980-977c-11ea-8f02-9a2ced8f2bcc.png)

### Environment

<details><pre>
</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by stefanwaldhauser** [comment]
I just found out that it sometimes loads the url and sometimes does not. I have to reload the whole page and try again and then sometimes the link works to the repository. Maybe some issue with asynchronous loading?

**Comment by krusche** [comment]
we have re-implemented this feature and it should work now.
@fde312 if this is still an issue, please fix it
