### ISSUE TITLE
Artemis keeps disconnecting and reconnecting in a short time.

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#1487]
### Describe the bug
See the title and the screenshots.

#### To Reproduce
Generally just wait for it to happen on artemis, it does not happen always though.

#### Expected behavior
Not beeing disconnected since there are no failed calls.

#### Screenshots
First alert:
[![Screenshot from Gyazo](https://gyazo.com/f1451a1bd2898eaca4504061fa262638/raw)](https://gyazo.com/f1451a1bd2898eaca4504061fa262638)
Second alert right after, replacing the first one:
[![Screenshot from Gyazo](https://gyazo.com/420738aa09fa9fb76214ed2103d5821d/raw)](https://gyazo.com/420738aa09fa9fb76214ed2103d5821d)

Latest Response (connected):
[![Screenshot from Gyazo](https://gyazo.com/c38026a83ca8c8e6abbf13345e555417/raw)](https://gyazo.com/c38026a83ca8c8e6abbf13345e555417)
Failed Response (disconnect):
[![Screenshot from Gyazo](https://gyazo.com/32f020002dd2190f373c8201e4c51789/raw)](https://gyazo.com/32f020002dd2190f373c8201e4c51789)
Next Response (reconnect):
[![Screenshot from Gyazo](https://gyazo.com/7fba786de10f8220272412ca53204c8d/raw)](https://gyazo.com/7fba786de10f8220272412ca53204c8d)

### Environment

<details><pre>
 - OS: Windows 10 Pro
 - Browser: Chrome v81.0.4044.138
</pre></details>

#### Additional context
It appears to be due to negative entropy. The recurring call to /websoccet/tracker/info suddenly returns a negative entropy (see screenshots). Just right after this happens a new call will be sent with a positive entropy. => Disconnect, Reconnect.

Either the entropy itself is the issue or it should not just disconnect when one call had a negative entropy.

#### Output in Web Console
None

**Comment by krusche** [comment]
does this issue still occur?

**Comment by julian-christl** [comment]
Confirm, happend the last time one to two days ago. It's not a 24/7 thing though.
