### ISSUE TITLE
Programming exercise (assessment): entering long result text returns internal server error

### ISSUE THREAD

**Issue by florian-glombik** [ls1intum/Artemis#1506]
### Describe the bug

Manual assessment of a programming exercise:
When entering a long result text (>255 characters) the server response is an internal server error.

#### To Reproduce

1. Go to _Tutor Exercise Dashboard_ of a programming exercise with activated manually assessment
2. Click on _New Result_
3. Enter a long result text (>255 characters)
4. "Internal server error"

#### Expected behavior

The user interface should indicate that the result text has to be shorter.
The error message should not be an internal Server error, it should tell the user that the entered result text is too long.

### Environment

<details><pre>
- OS: Windows 10 Pro
- Browser: Google Chrome
- Version  81.0.4044.138
</pre></details>

#### Additional context

![Tutor Exercise Dashboard - Google Chrome 22 05 2020 15_21_01](https://user-images.githubusercontent.com/63976129/82672166-45234200-9c40-11ea-8bd3-489a72f04cc0.png)

#### Output in Web Console
<details><pre>
{type: "https://www.jhipster.tech/problem/problem-with-message", title: "Internal Server Error",…}
detail: "could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.DataException: could not execute statement"
message: "error.http.500"
path: "/api/participations/329953/manual-results"
status: 500
title: "Internal Server Error"
type: "https://www.jhipster.tech/problem/problem-with-message"

</pre></details>

**Comment by krusche** [comment]
we don't use this editor any more
