### ISSUE TITLE
Automatic text selection range is wrong when assessing text exercises

### ISSUE THREAD

**Issue by ossner** [ls1intum/Artemis#1508]
### Describe the bug
When assessing parts of a text exercise, often times the pre-selected text selects too much or too little text. Especially when students list arguments the only selectable range sometimes covers two listings, which makes the assessment very confusing for the students.

#### To Reproduce
1. Go to any text exercise from the dashboard
2. Click on 'Start new assessment'
3. See error (not always but often)

#### Expected behavior
Text selection **only** selects entire sentences or points.

#### Screenshots
![image](https://user-images.githubusercontent.com/42720856/82729548-b6bec700-9cf8-11ea-8f29-f53889954bb0.png)

![image](https://user-images.githubusercontent.com/42720856/82729724-208ba080-9cfa-11ea-94b2-f104d37b11a3.png)

### Environment

<details><pre>
 - OS: Windows 10 / macOS catalina
 - Browser: Firefox 76.0.1 / Chrome 83.0.4103.61
 - Version: 4.1.1
</pre></details>

**Comment by krusche** [comment]
@jpbernius is this still relevant?
