### ISSUE TITLE
Display internally who assessed the complaint

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#1511]
### Is your feature request related to a problem?
If you want to discuss why a complaint was resolved in a specific way you could theoretically have a look in the webconsole but there is no official way. @HanyaElhashemy initially suggested to remove the reviewer from the response but I actually think it would be better to officially display who reviewed.
You can see who assessed as well.

### Describe the solution you'd like
Display internally (not to the student) who reassessed/reviewed the complaint.

### Describe alternatives you've considered
Yeah, cheating via the webconsole. Is not a great usability though ^^

**Comment by krusche** [comment]
Instructors can see who has reviewed a complaint
