### ISSUE TITLE
Add Back arrow to text Assessments

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#1512]
### Is your feature request related to a problem?
When I assessed a submission I like to go back to the dashboard sometimes to check another submission I did, the count my submissions or whatever. I alway have to click me back to the dashboard however since there is no back arrow.

### Describe the solution you'd like
Add an arrow like on other pages to lead back to the dashboard

### Additional context
No button here (text assessment)
[![Screenshot from Gyazo](https://gyazo.com/6577492dca06b7c37090c7c540d602af/raw)](https://gyazo.com/6577492dca06b7c37090c7c540d602af)
A nice back button (model assessment)
[![Screenshot from Gyazo](https://gyazo.com/0af0a7313c8c32100f7f7e1af648f493/raw)](https://gyazo.com/0af0a7313c8c32100f7f7e1af648f493)

**Comment by jpbernius** [comment]
We recently removed this, as it was unclear where this should go. Maybe we can "Dashboard" button?

**Comment by julian-christl** [comment]
I'm not sure how to undestand this because such a back button already exists for other exercise types just not for text exercises.

**Comment by bendavdam** [comment]
I am facing the same situation. Two examples here: When I am working on a team exercise together with my teammates (e.g. preparation of a homework) while using a shared screen and I have to switch between two tasks, I am supposed to use 
a) the "back button" of my browser which reloads the complete page.
b) the Course Overview button in the top right-hand corner.
Especially when many users are doing "a)" simultaneously, artemis is unable to handle all requests in a proper time (see EIST course). But if I am about to use option "b)" I return to my course overview screen which shows my current percentages of any course. When sharing the screen I don't really like that.

So one solution might be to add a backward arrow that takes the user back to the "Task Page" where he started the process of its task. From this page, one can further return to the main course page without using the back button of the browser or the indirect way via the course overview.
