### ISSUE TITLE
Text cut if it's to long on a example model

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#1513]
### Describe the bug
In an example model the frame boundary will be cut to the relation lines/arrow on the outside of the diagram. However if the text on the line is longer than the the lines position it will be cut (see screenshot)

#### Expected behavior
You are able to see everything.

#### Screenshots
[![Screenshot from Gyazo](https://gyazo.com/a630763ab23cfd4f9a7816e63c5acf4a/raw)](https://gyazo.com/a630763ab23cfd4f9a7816e63c5acf4a)

### Environment

<details><pre>
 - OS: Windows 10 Pro
 - Browser: Chrome v83.0.4103.61
</pre></details>

###Additional context
I'm not sure if this is an Apollon issue or an Artemis issue. Tell me then I'll create a new issue for Apollon.

**Comment by TobiasPr** [comment]
@julian-christl this is a duplicate of #1437 . Please follow the other ticket for developments on the fix

**Comment by julian-christl** [comment]
My bad, sorry.
