### ISSUE TITLE
Internal Server Error shown three times (on test server)

### ISSUE THREAD

**Issue by tessaRuckstuhl** [ls1intum/Artemis#1518]
### Describe the bug

When opening the details page, 3 error-messages are shown: "Internal server error"
#### To Reproduce

1. Go to Course Management
2. Click on Exercises of a course
3. Click on View of a Programming Exercise
4. See error. They disappear after a few seconds by themself.

#### Expected behavior

I did not expect the warnings to be shown. 
#### Screenshots

![image](https://user-images.githubusercontent.com/50466283/82818425-017a4380-9e9f-11ea-9bd6-952a671d8c9a.png)

### Environment

<details><pre>
 - OS: [e.g.Windows]
 - Browser [e.g. chrome]
 - Version [81.0.4044.138]
</pre></details>

**Comment by krusche** [comment]
This issue is resolved on `develop`. Please merge the latest version into your feature branch
