### ISSUE TITLE
Complaint resize automatically

### ISSUE THREAD

**Issue by rgatuzov** [ls1intum/Artemis#1520]
### Is your feature request related to a problem?
Sort of. I'm in second semester and sent a few complaints already but have marked just now that you can resize "Complaints" window on Artemis. This is mainly my fault but I struggled quite a bit, writing everything in a small window. ._.

### Describe the solution you'd like
Therefore, my suggestion would be to resize the complaint windows automatically, it would be much more user-friendly. Thanks!

**Comment by krusche** [comment]
It is intentionally small so that students don't write too long texts here 😉
