### ISSUE TITLE
Add a Lecture with a past End Date, but no Starting Date 

### ISSUE THREAD

**Issue by Varnika-Tyagi** [ls1intum/Artemis#1523]
### Describe the bug

At the moment, it is possible to successfully create such a lecture with past End date, but no starting date.

#### To Reproduce

1. Logged in as 'Instructor', head over to Course Management and click on Lectures of the course
2. Click on ' Create lecture'
3. Insert the details, and set the end date but NO starting date
4. Press Save.

#### Expected behavior

An error should be shown that you have to specify a starting date also if there is an end date

**Comment by krusche** [comment]
not a real issue
