### ISSUE TITLE
Set the Starting Date Past the End Date on a Lecture

### ISSUE THREAD

**Issue by Varnika-Tyagi** [ls1intum/Artemis#1524]
### Describe the bug

No error prompt "Start date must be prior to end date" displayed. The lecture is saved even if the start date is past the end date.

#### To Reproduce

1. Log in as Instructor, Go to 'Course Management' and click on Lectures of a course
2. Click on 'Create Lecture'
3. Fill out the details and specify an End Date which is before the starting date and press Save

#### Expected behavior

An Error should be shown which lets the user know that the starting date needs to be before the end date

#### Screenshots

![Failing test cases in the Lectures Test Suite as on May 26](https://user-images.githubusercontent.com/17163093/82892971-a7d25180-9f50-11ea-9711-50894af8f5b5.PNG)

**Comment by krusche** [comment]
not a real issue
