### ISSUE TITLE
Word count

### ISSUE THREAD

**Issue by Mauku99** [ls1intum/Artemis#1528]
### Describe the solution you'd like
I would like to be shown my word count while typing in the text editor.

**Comment by tobiasschamel** [comment]
As far as I understood it:
We ask students to limit their answers to approximately 1000 characters in EIST - thus it would be nice, if there would be a character/word count in the artemis text editor. Currently students need to utilize external character counters to check the length of their submissions.

**Comment by julian-christl** [comment]
I second this. It would be great for the tutors as well just to get a better feeling if the submission is within bounds or completely off.
The issue should be primarily be about "character count" but I think "word count" would be a nice addition as well (more for the student side).

**Comment by stefanwaldhauser** [comment]
Opened a branch and will work on it over the weekend 👍

**Comment by stefanwaldhauser** [comment]
Finished and is in pull review
