### ISSUE TITLE
No UML Class Properties shown in Artemis

### ISSUE THREAD

**Issue by Makki93** [ls1intum/Artemis#1538]
### Describe the bug
When I open up fullscreen in a modeling exercise, I can't open up the dialog for changing a class's properties.

#### To Reproduce

1. Go to https://artemis.ase.in.tum.de/#/courses/48/modeling-exercises/1250/participate/352939
2. Click on Fullscreen
3. Doubleclick on a class object
4. No properties displayed

#### Expected behavior
Properties displayed (the second screenshot).

#### Screenshots

![image](https://user-images.githubusercontent.com/44347047/83350353-d333b280-a33b-11ea-947d-1e1ab483d218.png)
![image](https://user-images.githubusercontent.com/44347047/83350364-e47cbf00-a33b-11ea-92bc-77ca57ae7ff4.png)

### Environment

<details><pre>
Windows 10
![image](https://user-images.githubusercontent.com/44347047/83350393-0d04b900-a33c-11ea-951a-7054ac57f5ac.png)

Chrome
Version 83.0.4103.61 (Offizieller Build) (64-Bit)
</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by TobiasPr** [comment]
I implemented a fix for this in apollon -> popups are not added to document but to apollon-editor root element instead -> makes them visibile in full screen.

Will be included in Apollon 2.1.1
