### ISSUE TITLE
Faulty mobile display for started exercises

### ISSUE THREAD

**Issue by tessaRuckstuhl** [ls1intum/Artemis#1539]
### Describe the bug

Whenever the exercises are shown on the below mentioned mobile devices, the exercise title of a started exercise is narrowed down. This makes the title very difficult/impossible to read. 
#### To Reproduce

Do this using the following phones/using the dev tools with Iphone 6/7/8; IPhone 6/7/8; IPhone X; Plus Pixel 2 (XL)
1. Go to Course Overview
2. Click on a Course
3. Start an exercise
4. Go back to exercise overview
5. See error

#### Expected behavior

I expected the Exercise Title to be readable and not narrowed down so much. 

My suggestion would be to either move the "Submitted, you can still submit updates." below the exercise title or to narrow its space down. 
#### Screenshots

![5xVsaA8WEx](https://user-images.githubusercontent.com/50466283/83350887-88b43500-a33f-11ea-987c-4d3dc424804b.gif)

### Environment

<details><pre>
- DevTool Browser Chrome V. 83.0.4103.61
-Iphone 6 Plus

**Comment by MaisiKoleni** [comment]
Note: This is the same problem mentioned in #1646 and that #1647 relates to.

**Comment by krusche** [comment]
not reproducible any more / was fixed
