### ISSUE TITLE
Locks keep getting increased when leaving text exercise dashboard

### ISSUE THREAD

**Issue by tessaRuckstuhl** [ls1intum/Artemis#1545]
### Describe the bug

Whenever a tutor assesses the Exercise Dashboard of a text exercise (and/or goes back), a new lock is generated.
#### To Reproduce

Preconditons: Created text exercise, some students participated, due date is over
1. Go to Course Management
2. Click on Tutor Course Dashboard
3. Click on Exercise Dashboard
4. Go Back

Repeat Step 3 and 4 and see error

#### Expected behavior

I would not expect the automatic lock generation.
#### Screenshots

![er0tYcok1y](https://user-images.githubusercontent.com/50466283/83394804-7e567180-a3f9-11ea-811d-b17d64be76b7.gif)
### Environment

<details><pre>
 - OS: Windows
 - Browser Chrome
 - Version 83.0.4103.61
</pre></details>

**Comment by balazs-czopf** [comment]
Here is another example for that behavior where assessments are locked automatically when visiting the tutor exercise dashboard:

![Tutor Exercise Dashboard](https://user-images.githubusercontent.com/63286106/83396544-70562000-a3fc-11ea-958b-d98d73f67cd5.gif)

**Comment by tessaRuckstuhl** [comment]
This bug **does not** happen for file upload exercises or modeling exercises!

**Comment by stefanwaldhauser** [comment]
I think i found the reason for this bug, see the associated pull request

**Comment by stefanwaldhauser** [comment]
![Jun-01-2020 15-05-51-min](https://user-images.githubusercontent.com/29718932/83412316-29772300-a41a-11ea-8681-94a44083e041.gif)
