### ISSUE TITLE
Always N locked submissions in assessment overview

### ISSUE THREAD

**Issue by FuchsDominik** [ls1intum/Artemis#1553]
### Describe the bug

After finishing the example submission. Immediately 5 locked students submissions are shown. Furthermore, when assessing the submissions by clicking on "continue assessment". The locked submssion is indeed asessed, but another submission got locked so that there are still 5 locked submissions (and 1 assessed submission now for example).

#### Expected behavior

Now submissions should be locked automatically.

#### Screenshots

Jun 1, 2020 11:28 AM here locked:
![image](https://user-images.githubusercontent.com/44401560/83525585-7bd14600-a4e5-11ea-814b-1bc5a5f7e120.png)

Jun 1, 2020 11:28 AM now assessed:
![image](https://user-images.githubusercontent.com/44401560/83525944-fac67e80-a4e5-11ea-836e-1fbf84a54afd.png)

May 25, 2020 now locked, which was the submission for "start new assessment" earlier.

UPDATE:
After re-visiting the page, even more submission got locked: 
![image](https://user-images.githubusercontent.com/44401560/83526823-46c5f300-a4e7-11ea-98e5-a9548e7a27d5.png)

### Environment

<details><pre>
 - OS: Windows
 - Browser Chrome (Version 83.0.4103.61)
</pre></details>

**Comment by krusche** [comment]
Does this happen only for text exercises? (we just fixed a bug here that could explain your problem, which is not yet released) or also for other exercise types?

**Comment by julian-christl** [comment]
It seemed to appear on some Team exercises. I did my assessments and cleared all my locks from other submissions since I was aware of that issue. After one day I saw that some were locked by me which doesn't make any sense since I didn't open any submissions after this.
Hovever I'm afraid I don't have any further data but wanted to let you know that it was not only about this specific exercise.

**Comment by krusche** [comment]
please double check if this bug still occurs after the release 4.1.3 and report back. Thanks!

**Comment by julian-christl** [comment]
Today I had two locks which was weird, but maybe it was my fault. Therefore I'll get back in a week if it persists or not. Thanks to that new lock overview I can now see this way better.

**Comment by krusche** [comment]
Then I'll close this for now. Please reopen it, if the problem persists

**Comment by FuchsDominik** [comment]
I checked again and no new locked assessments appear after assessing the falsely locked ones. Also, the others can be assessed correctly. Seems to be fixed in the new release, good job.
