### ISSUE TITLE
Artemis hidden associations bug

### ISSUE THREAD

**Issue by ihebss** [ls1intum/Artemis#1559]
### Describe the bug

The associations between components or between a component and an inteface do not appear as intentded.
#### To Reproduce

1. Go to 'artemis'
2. Drag a component 
3. Drag another component and put it inside the old one
4. Do the same with two more components (drag one and put the other one inside it)
5. Make an association between the two inner components
6. Submit and check the submission again
7. The association only appears to be between the two outer components

#### Expected behavior

There should be an association between the two inner components
#### Screenshots

![image](https://user-images.githubusercontent.com/66373552/83656521-f1114980-a5bf-11ea-8733-b335b45bb2e7.png)

### Environment

<details><pre>
 - OS: Windows 10
 - Browser:  Chrome
 - Version 83.0.4103.61
</pre></details>

**Comment by TobiasPr** [comment]
Was fixed in this hotfix https://github.com/ls1intum/Artemis/pull/1557
