### ISSUE TITLE
Notify student upon manual assessment

### ISSUE THREAD

**Issue by just-max** [ls1intum/Artemis#1576]
### Is your feature request related to a problem?
Often by the time a manual assessment is available (on a programming, modelling, text, or file upload exercise), that exercise will be buried by newer exercises so that it is easy to miss. This can lead to frustration if the student would have liked to submit a complaint but missed the 7-day deadline. Even if the student is vigilant in checking submitted exercises for assessments, the process of expanding every week's exercise list, checking each exercise and remembering if they have already seen the assessment is tedious at best.

### Describe the solution you'd like
Upon receiving a manual assessment of an exercise, the student should receive a notification through the existing notification system. Additionally, exercises with new assessments should be marked to indicate a new assessment.

This could also be expanded to new Complain and Additional Feedback responses.

### Describe alternatives you've considered
Notification by email would also be possible, but probably excessive or bothersome. Having the option to send emails for the existing notification system could be a separate feature.

### Additional context
An example of how the notification could look:
![Notify on assessment](https://user-images.githubusercontent.com/17551908/83872585-8c2a3080-a732-11ea-81f6-45012b169b89.png)
An example for how the marked assessment could look:
![Exercise with new assessment](https://user-images.githubusercontent.com/17551908/83874713-39527800-a736-11ea-8782-dde96af83a71.png)

**Comment by julian-christl** [comment]
It might be worth a thought when implementing this to implement it for receiving a feedback request as a tutor as well.
