### ISSUE TITLE
[Exam] Client: Start View

### ISSUE THREAD

**Issue by tessaRuckstuhl** [ls1intum/Artemis#1582]
When students participate in exams in Artemis, the first page of this exam should display the following: 

- display text produced with the markdown editor [create start and final page](https://github.com/ls1intum/Artemis/issues/1583)
- tick to confirm that students will obey the stated rules/demands
- start exam button (should be disabled while confirmation is not ticked, button is also disabled if the current date is before the 'visible date' but the exam is already loaded to the storage)

### Mock Up View
![image](https://user-images.githubusercontent.com/50466283/83917177-b867a080-a776-11ea-89ed-bbbc31c79bbe.png)

**Comment by julian-christl** [comment]
**Used terms:**
- Start: A non interactive information page before the exam
- End: A non interactive information page after the exam
- Confirm Start: An information page before the exam the user has to confirm
- Confirm End: An information page after the exam the user has to confirm

**Suggestion:**
Would it be interesting to offer instructors the option to change the order?
Confirm Start -> Start -> Exam -> End -> Confirm End **or**
Start -> Confirm Start -> Exam -> End -> Confirm End **or**
Confirm Start -> Start -> Exam -> Confirm End -> End **or**
Start -> Confirm Start -> Exam -> Confirm End -> End

This could be resolved in two simple checkboxes (or simliar solutions) e.g. "[X] Start confirmation first", "[X] End confirmation first". In this example each "Start" and "End" would be at the beginning of each section in case the checkboxes would get unchecked.

**Comment by krusche** [comment]
I would argue that the information text should come first and then the confirmation text (which can also be very short, e.g. "I confirm to obey the rules"). Allowing to change the order is something that we could consider in the next iteration. Let's get the most important functionality done first!

**Comment by julian-christl** [comment]
Sounds good. Should I mention the suggestion for the next iteration somewhere or is it enough here?

**Comment by krusche** [comment]
I guess it is enough here
