### ISSUE TITLE
[Exam] Client: Create Start and Final View

### ISSUE THREAD

**Issue by tessaRuckstuhl** [ls1intum/Artemis#1583]
### Describe the solution you'd like

- the instructor should be able to define the general information displayed on the start/final page 
- the instructor should be able to define the information displayed next to the confirmation tick on the start/final page 
- the instructor should be able to use the markdown editor to create this text

**To be discussed:** Necessity to create indiviudal Confirmation Text
### Mock Up View (Scroll down)
![image](https://user-images.githubusercontent.com/50466283/83942507-3ddd6600-a7f4-11ea-9b1f-9c35f7a2a43a.png)

**Comment by filip-gregurevic** [comment]
Closed via https://github.com/ls1intum/Artemis/issues/1582
