### ISSUE TITLE
Displaying commit hash at build results

### ISSUE THREAD

**Issue by danbachar** [ls1intum/Artemis#1594]
### Is your feature request related to a problem?
Nope.

### Describe the solution you'd like
It would be helpful to see commit hashes at the build results component.

### Describe alternatives you've considered
parsing through `git log`, `git diff HEAD~n`, should be easy to implement.

### Additional context

<img width="886" alt="image" src="https://user-images.githubusercontent.com/17069732/83981584-a1b07d80-a91f-11ea-8c68-f93e0457d13d.png">

attaching screenshot for `git log` for the relevant exercise
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/17069732/83981606-b856d480-a91f-11ea-8a04-5a166863f455.png">

**Comment by krusche** [comment]
Why would this be helpful?

**Comment by danbachar** [comment]
It would enable users to easily see commit hashes of their builds, easily accessible through Artemis instead of bitbucket.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________
