### ISSUE TITLE
"Start new assesment" button still visible for team exercises.

### ISSUE THREAD

**Issue by Nadel1** [ls1intum/Artemis#1597]
### Describe the bug
The button to start a new assesment for the team exercises can still be accessed, eventhough it should have been fixed. This has occured for all team exercises.

#### To Reproduce
1. Select a team exercise.
2. Select a team.
3. Open/start the assesment for any exercise.
4. When clicking on the back arrow on Artemis, you are redirected to the Tutor Exercise Dashboard, where the "Start new assesment" button is visible.

#### Expected behavior
When using the back button on the mouse, you are redirected to the overview of the team submissions, and not the Tutor Exercise Dashboard. 

#### Screenshots
![newAssesmentButton](https://user-images.githubusercontent.com/51209890/84025670-4bc5ef00-a98c-11ea-8e5a-4cfbd0366b9f.gif)

### Environment
-Windows 10 Pro
-Chrome 83.0.4103.61

**Comment by krusche** [comment]
thanks for providing the details and the screencast for this issue
