### ISSUE TITLE
Present Sample Solution

### ISSUE THREAD

**Issue by andreasseitz** [ls1intum/Artemis#16]
As Instructor, I want to be able to provide a sample solution for an exercise.
As Student, I want to see a sample solution of an exercise after the exercise deadline has passed.

**Comment by krusche** [comment]
We have this in the database, but need to work on how instructors can insert sample solutions and how this is presented to students after the deadline

**Comment by Garfield96** [comment]
What's the current status of this feature?

**Comment by krusche** [comment]
Instructors can provide sample solutions for programming, text and modeling exercises, but they cannot be displayed to students automatically.

**Comment by COM8** [comment]
This was one of the biggest criticisms of Artemis in our lecture evaluation.

**Comment by krusche** [comment]
Thanks for the feedback! You can already use the solution repository and simply give  the student group of the course read permissions. Then you could simply distribute this link using the problem statement. In the future, we will integrate this into Artemis so that at a specific date the solution is automatically readable to all students and properly linked in the exercise details page

**Comment by axel1200** [comment]
Would also be interesting for our use case

**Comment by krusche** [comment]
I think the easiest implementation would be to 

1) add a button to the course management --> (programming) exercise details page “Publish solution” (only visible after due date and with a confirmation dialog). 
2) If this button was pressed and confirmed, the student group will get read access to the solution repo and the link will be displayed in the student exercise details page.

This also means we need a new attribute in Exercise.java (as this would also be useful for other exercise types in the future) and a new column in the exercise table to save if the solution is available.

An alternative would be to allow instructor to store a solutionPublicationDate in the exercise itself. Then, they could setup the solution publication even before the exercise due date has passed. This would then need to be automatically scheduled

**Comment by axel1200** [comment]
@krusche your work around does not work for GitLab because there is no student group there
