### ISSUE TITLE
Missing columns

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#1601]
### Describe the bug
The tutor leaderboard within an exercise is missing two columns. It appears to be the "accepted complaints" and "Open requests". I know for sure that the column which is currently labled with "Accepted complaints" should be "Complaint responses" and therefore it's quite logical that current "Open requests" should be "Answered requests" => the two columns in the middle are missing.

#### To Reproduce

1. Go on any exercise dashboard
2. Scroll down to the leaderboard
3. See the error

#### Expected behavior
Either add the respective columns back or remove the two column headers.
However I would like to see at least the column "Open request" back since it's then very easy to notify the respective tutors in case they didn't see the feedback request.

#### Screenshots
![68817d736c5a74d454891c7b17ffc482](https://user-images.githubusercontent.com/64264938/84059069-4f706a80-a9ba-11ea-8342-ef2b77a85f8d.png)

### Environment

<details><pre>
 - OS: Windows 10 Pro
 - Browser: Chrome v83.0.4103.97
 - Role: Instructor
</pre></details>

#### Output in Web Console
[![Screenshot from Gyazo](https://gyazo.com/6c8b18cdf6c78e81fa4bc51660a20edd/raw)](https://gyazo.com/6c8b18cdf6c78e81fa4bc51660a20edd)
[![Screenshot from Gyazo](https://gyazo.com/e956e34b793fe710f817532fc433a882/raw)](https://gyazo.com/e956e34b793fe710f817532fc433a882)
![4697abf58f8297ea6ca3668621826e91](https://user-images.githubusercontent.com/64264938/84059482-fce37e00-a9ba-11ea-82bd-ab40d081f6ef.png)

**Comment by krusche** [comment]
already fixed
