### ISSUE TITLE
[Exam] Exam management: Adjust exercise create/update dialogues

### ISSUE THREAD

**Issue by sascha11110** [ls1intum/Artemis#1621]
- The create/update dialogues for all exercise types (model, text, programming, file upload, quiz) has to be adjusted so that 
- Most of the work most be put into the implementation of the the assignment to an exercise group.
- [This](https://github.com/ls1intum/Artemis/issues/1615) might be relevant here.
- Use the same components but create new client routes.
- Existing REST calls can be reused as they do not depend on the course id.
- Optional: implement the _Exam_ and _Exercise group_ fields as select fields

![image](https://user-images.githubusercontent.com/15168372/84212595-9051a780-aabe-11ea-8f21-48b6a8e6fdfa.png)

**Comment by sascha11110** [comment]
Implemented for text exercises: https://github.com/ls1intum/Artemis/pull/1633

**Comment by kloessst** [comment]
PR for file upload exercises: https://github.com/ls1intum/Artemis/pull/1658
