### ISSUE TITLE
Exercise information on Tutor Exercise Dashboard is not displayed correctly

### ISSUE THREAD

**Issue by niclasschuemann** [ls1intum/Artemis#1626]
### Describe the bug
When assessing submissions as an instructor, the number of "submissions assessed by you" on the tutor course dashboard is not displayed correctly. It always shows 0, even after submissions have been assessed. This happens with accounts that only have the instructor group, but it does not happen with accounts that have the instructor group as well as the tutor group.

### To Reproduce
**Prerequisites:**
 - You need one Instructor account
 - You need a submission for an exercise that you can assess

**Steps:**
1. Go to the Tutor Course Dashboard
2. Locate your exercise and open the tutor exercise dashboard
3. Assess your prepared submission
4. Go back to the tutor exercise dashboard
5. "Submissions assessed by you" is still at 0

### Expected behavior
The correct amount of assessed submissions must be displayed next to "Submissions assessed by you" in the tutor exercise dashboard.

### Screenshots
![m](https://user-images.githubusercontent.com/45300855/84277650-178d3280-ab34-11ea-974a-5a2e3649e9a1.PNG)

### Additional context
This issue is related to [this PR](https://github.com/ls1intum/Artemis/pull/1598) and [this comment](https://github.com/ls1intum/Artemis/pull/1598#issuecomment-641366146)

**Comment by niclasschuemann** [comment]
This view does not exist anymore, therefore this issue can be closed.

**Comment by krusche** [comment]
outdated
