### ISSUE TITLE
Late submissions of non programming exercises

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#1627]
### Describe the issue
I'm not 100% sure. Either the issue is that when the student submits that his hold submission gets overridden or the issue is that if you submit late the submission gets still overridden.

#### To Reproduce
1. Submit a exercise (Text, Modeling) multiple times until the deadline
2. Submit after the deadline
3. Assess the submission
4. Check the participation of the student and see that there is only one submission and it's a late one

#### Expected behavior
Either you have multiple submissions for one participation and the last one before due date counts or you can't override the submission after due date but must return an error.

I don't know why it's implemented this way but I think it's unfair if you try until the end and get punished for it because you don't know the exact server time.

**Comment by julian-christl** [comment]
I tried the following setup:
- Create a new Text exercise with the duedate in some minutes.
- Submit multiple times until the "Submit" button gets deactivated
Deadline was 19:00
[![Screenshot from Gyazo](https://gyazo.com/86e006a61f88b26561eaf89e2edad4be/raw)](https://gyazo.com/86e006a61f88b26561eaf89e2edad4be)

However when I assess it, it counts as a normal (not late submission) in contrary to what is stated in the screenshot
[![Screenshot from Gyazo](https://gyazo.com/29e10385e6711c2512fd91ff923f6603/raw)](https://gyazo.com/29e10385e6711c2512fd91ff923f6603)
[![Screenshot from Gyazo](https://gyazo.com/acbfce18760719c461db30b06979811f/raw)](https://gyazo.com/acbfce18760719c461db30b06979811f)

However this is not what a student has experienced (4 seconds late, graded with full points but doesn't count). I'll update this issue as soon as I know more.

**Comment by Strohgelaender** [comment]
Fixed by #7258
