### ISSUE TITLE
Sorting in Submission View is broken

### ISSUE THREAD

**Issue by JohannesStoehr** [ls1intum/Artemis#1629]
### Describe the bug
The sorting of the submission view seems to be broken.
Sometimes nothing happens at all, othertimes the view get sorted by a completly different category.

#### To Reproduce

1. Open the submission view of any exercise
2. Try to sort after one of the columns
3. See an unsorted view of submissions

### Environment

<details><pre>
 - OS: MacOs and Windows
 - Browser: Safari and Firefox
</pre></details>

**Comment by MaisiKoleni** [comment]
I am now not able to reproduce that in Chromium or Firefox on Win 10. I guess this was now already fixed by #1501 that got merged six days after this bug was reported. Should the bug still appear or I overlooked something, just reopen this bug report.
