### ISSUE TITLE
Different component for submission view on modeling and text exercises

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#1631]
### Describe the bug
Described in the screenshots

#### Expected behavior
Same component for all exercises. Progresscounter, loading animation and table hader for all models would be the best, I guess.

#### Screenshots
Modeling exercise:
![c40e658e1ec7b505a983bc53944c6470](https://user-images.githubusercontent.com/64264938/84319752-cd767200-ab70-11ea-9d42-b9e3c6f9f83f.png)
Here you have no loading animation, until everything is loaded no table hader is shown only the progress placeholder (0 out of 0).
After loading the progress will be updated accordingly, if no submission was found no table will be displayed.

Text exercise:
![f9c99dae33b17b7fd91f0b9434e204e0](https://user-images.githubusercontent.com/64264938/84319771-d8310700-ab70-11ea-9d62-cf436fad459b.png)
Here you have a loading animation and a table header even if no submission is displayed, no Progress counter.

### Environment
<details><pre>
 - OS: Windows 10 Pro
 - Browser Chrome v83.0.4103.97
</pre></details>

#### Additional context
Most probably this effects all exercise types.
Depending on the solution it might affect #1630

**Comment by krusche** [comment]
we removed the submission page and have a common scores page with all functionality now
