### ISSUE TITLE
One Submission to be assessed but not assessable

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#1632]
### Describe the bug
As you can see in the first screenshot there is still one submission to be assessed. However if I open the exercise dashboard I can't start a new assessment. If I then take a look into all locked submissions the list is empty. Even if it's not a real list.
#### To Reproduce
Unknown. At least I can give the following parameters:
- Modeling exercise
- all assessed what is possible to be assessed
- it's the H04E04 in the live system

#### Expected behavior
You are able to assess the last one or the submission count is correct.

#### Screenshots
One Submission to assess
[![Screenshot from Gyazo](https://gyazo.com/6edb3ae8a4e8233e984ec8485955f638/raw)](https://gyazo.com/6edb3ae8a4e8233e984ec8485955f638)

No "Start new Assessment" Button visible
![767a3e2eb53b27f3a2300bb32d31aec4](https://user-images.githubusercontent.com/64264938/84319256-06621700-ab70-11ea-8dc3-8ed0b409a4bf.png)

Nothing locked
[![Screenshot from Gyazo](https://gyazo.com/2021ef1b3ccb665b3ab03ac9b06c809e/raw)](https://gyazo.com/2021ef1b3ccb665b3ab03ac9b06c809e)

### Environment
<details><pre>
 - OS: Windows 10 Pro
 - Browser Chrome v83.0.4103.97
</pre></details>

**Comment by krusche** [comment]
I think this issue was addressed in another PR
