### ISSUE TITLE
No submission found when clicking on the "Start new assessment button"

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#1636]
### Describe the bug
As you can see in the first screenshot there is still one submission to be assessed. If I open the dashboard I do have the option to start a new assessment. however if I do so I get an error message.

#### To Reproduce
Unknown. At least I can give the following parameters:
- Text exercise
- all assessed what is possible to be assessed
- it's the H04E02 in the live system

#### Expected behavior
You are able to assess the last one or the submission count and the "Start new assessment" button are correct.

#### Screenshots
One Submission to assess
[![Screenshot from Gyazo](https://gyazo.com/812f7cf6ca37a58f5ba690a5cb4452ab/raw)](https://gyazo.com/812f7cf6ca37a58f5ba690a5cb4452ab)

The "Start new Assessment" button visible
[![Screenshot from Gyazo](https://gyazo.com/8d60386a35a5f6f8b4559ad55599bdc0/raw)](https://gyazo.com/8d60386a35a5f6f8b4559ad55599bdc0)

Error message
[![Screenshot from Gyazo](https://gyazo.com/75656e80ebdc910b424cc197dcff1477/raw)](https://gyazo.com/75656e80ebdc910b424cc197dcff1477)

### Environment
<details><pre>
 - OS: Windows 10 Pro
 - Browser Chrome v83.0.4103.97
</pre></details>

#### Additional information
There are no locks on this exercise.

**Comment by krusche** [comment]
This issue was resolved
