### ISSUE TITLE
Complaints can't be accepted

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#1637]
### Describe the bug
When assessing a complaint it can't be accepted

#### To Reproduce
1. Go to a complaint
2. Accept it
3. Reload
4. See that the complaint wasn't saved

#### Expected behavior
The complaint gets saved

#### Screenshots
Faild Network call
[![Screenshot from Gyazo](https://gyazo.com/56fbdf97341c2e53f1baaeae91c8bb11/raw)](https://gyazo.com/56fbdf97341c2e53f1baaeae91c8bb11)
[![Screenshot from Gyazo](https://gyazo.com/8a30d0f8951efba4b91aaab5415353dc/raw)](https://gyazo.com/8a30d0f8951efba4b91aaab5415353dc)
### Environment

<details><pre>
</pre></details>

#### Additional context
Actually there appears to be an error as well with the reject, however it gets saved:
[![Screenshot from Gyazo](https://gyazo.com/2c1b661e2363b0711f318b092a8f48d2/raw)](https://gyazo.com/2c1b661e2363b0711f318b092a8f48d2)
[![Screenshot from Gyazo](https://gyazo.com/ae4dc0c1f78577611b8649352dfbbd19/raw)](https://gyazo.com/ae4dc0c1f78577611b8649352dfbbd19)
[![Screenshot from Gyazo](https://gyazo.com/81222ab30a7b827d0c34a104f23bd1a1/raw)](https://gyazo.com/81222ab30a7b827d0c34a104f23bd1a1)

#### Output in Web Console
[![Screenshot from Gyazo](https://gyazo.com/70644b2cb37e91b312dfe25538e97bb9/raw)](https://gyazo.com/70644b2cb37e91b312dfe25538e97bb9)

**Comment by krusche** [comment]
Seems to be related to text exercises
