### ISSUE TITLE
Name of the excercise isn't shown correctly

### ISSUE THREAD

**Issue by HardMax71** [ls1intum/Artemis#1646]
After opening the browser not in full screen, the name of the T2E4 excercise is shown vertically (expected : horisontally).

#### To Reproduce

1. Open browser at most 70% of the full screen.
2. Open EIST page on Artemis 
3. Scroll down to T2E4
4. The name of T2E4 is shown vertically, however all other names are shown horisontally.

#### Expected behavior
The name of T2E4 is expected to be written horisontally.

#### Screenshots

After step 2.
![image](https://user-images.githubusercontent.com/66359507/84603068-3c670a00-ae94-11ea-9666-c59ec6c76272.png)
After step 4.
![image](https://user-images.githubusercontent.com/66359507/84598166-60652400-ae71-11ea-8a47-e47d692e495e.png)

### Environment

<details><pre>
 - OS: Windows 10
 - Browser: Chrome
 - Version: 83.0.4103.97 (Official Build) (64-bit)
 - Screen resolution : 1920x1080, Scale 125%
</pre></details>

**Comment by krusche** [comment]
not reproducible any more / was fixed
