### ISSUE TITLE
position of the tutor's comment is "over" other buttons

### ISSUE THREAD

**Issue by HardMax71** [ls1intum/Artemis#1647]
### Describe the bug
After opening the excercise with huge comment from the tutor (in my case, it's T2E4) in Chrome on about 30-45% of the full screen, orange text of the tutor's comment is above "team" and "clone repository" buttons.

#### To Reproduce

1. Open Chrome in full screen
2. Open Artemis on EIST page
3. Open any excercise with comment more than 5-7 words.
4. Open Chrome in window mode (instead of full screen mode)
5. Orange text of the comment will be crossing the "team" and "clone repository" buttons

#### Expected behavior
Orange text of the comment is expected to stay in its borders.

#### Screenshots
After step 3.
![image](https://user-images.githubusercontent.com/66359507/84598410-2f85ee80-ae73-11ea-8257-297946adc74e.png)
After step 5.
![image](https://user-images.githubusercontent.com/66359507/84598428-4f1d1700-ae73-11ea-86bc-8f27e3d8c583.png)

### Environment

<details><pre>
 - OS: Windows 10
 - Browser: Chrome
 - Version: 83.0.4103.97 (Official Build) (64-bit)
 - Resolution : 1920x1080, Skale 125%
</pre></details>

#### Additional context

Looks like the bug comes only if the place taken by Chrome page with T2E4 is not strictly less than 1/2 of the screen.
1/2 of the screen : 
![image](https://user-images.githubusercontent.com/66359507/84598464-9e634780-ae73-11ea-8568-1ea856de7f8a.png)
full screen : 
![image](https://user-images.githubusercontent.com/66359507/84598471-a7ecaf80-ae73-11ea-9175-7c771fcd9af5.png)

**Comment by MaisiKoleni** [comment]
Related to #1646.

**Comment by krusche** [comment]
not reproducible any more / was fixed
