### ISSUE TITLE
date-time-picker.component.ts doesn't set seconds to 0

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#1649]
### Describe the bug
See https://github.com/ls1intum/Artemis/pull/1640#pullrequestreview-430224669
Seconds are not selectable but they will be saved anway. Apparently the seconds of DateTime.now() get used.

#### To Reproduce
1. Go to a entity form where you can select a date and time without seconds
2. Select a date
3. Save and reopen the entity
4. See that seconds are set so something != 0 (in case it is 0, try again - you were lucky)

#### Expected behavior
Seconds are set to 0. If I can't set the seconds I expect them to be 0. If they are not it could be an issue with exercises/exams starting to early, ending to late. Even though it's only about at max 59 this should be fixed.

#### Screenshots
[![Screenshot from Gyazo](https://gyazo.com/ca3da36af6eb784d75235f3a510c887e/raw)](https://gyazo.com/ca3da36af6eb784d75235f3a510c887e)

**Comment by MaisiKoleni** [comment]
You can change the seconds in the text field directly as far as I know, should you require them to be 0. At least that's what I often did for PGdP. But first setting them to zero is a good Idea, I guess.
