### ISSUE TITLE
When the user was added first time to a course as a tutor can't access course dashboard

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#1654]
### Describe the bug
See title

#### To Reproduce
Roles: I1:Instructor, T1:Tutor
1. T1 and I1 log in
2. I1 adds T1 to course A as a tutor
3. T1 reloads the page and accesses the course dashboard
4. See error with missing translation
5. T1 logs out and signs in again
6. T1 accesses the course dashboard
7. Working as intended

#### Expected behavior
1. Translation is displayed
2. The error isn't actually shown but the dashboard.

#### Screenshots
[![Screenshot from Gyazo](https://gyazo.com/8a25f03148dc1887c16d70caa51c3a87/raw)](https://gyazo.com/8a25f03148dc1887c16d70caa51c3a87)

### Environment
<details><pre>
 - OS: Windows Pro
 - Browser: Chrome v83.0.4103.97
</pre></details>

#### Additional context
This happend when the user had no access on the dashboard before and does not happen if the user already had.

**Comment by krusche** [comment]
logout and login is necessary in this case and we cannot easily fix this
