### ISSUE TITLE
Inability to click on any attribute of class in modelling editor

### ISSUE THREAD

**Issue by HardMax71** [ls1intum/Artemis#1663]
### Describe the bug
After creating a class with >3 attributes and clicking on second attribute, i can't directly open line with first attribute. Instead of it, it goes through all other attributes (here : from second to third, from third to fourth and then from fourth to first).

#### To Reproduce

1. Open any excercise with modelling editor (in my case - H6E2)
2. Create new class and add more than 3 attributes to it.
3. Click on any attribute (let's say 3) (but not first one).
4. Click on first attribute.
5. The editor will open not the first attribute, but instead it will go to 3+1 attribute, 3+2 and so on to the end and only then it will open the line with first attribute.

#### Expected behavior
Clicked on first attribute -> Line with first attribute opened.

#### Screenshots
After step 2.
![image](https://user-images.githubusercontent.com/66359507/84765796-6a556700-afd8-11ea-825b-eca8d265ec6b.png)
After step 3.
![image](https://user-images.githubusercontent.com/66359507/84765844-7c370a00-afd8-11ea-8405-ee8b4e30dd2e.png)
After step 4.
![image](https://user-images.githubusercontent.com/66359507/84765894-953fbb00-afd8-11ea-9390-5c8efeddc4ec.png)

### Environment

<details><pre>
 - OS: Windows 10 
 - Browser Chrome
 - Version 83.0.4103.97 (Official Build) (64-bit)
</pre></details>

**Comment by TobiasPr** [comment]
@HardMax71 This issue was fixed by the latest Artemis update, which happened yesterday morning. Feel free to reopen if
