### ISSUE TITLE
Result for text exercies displays additional letters

### ISSUE THREAD

**Issue by NiOHar** [ls1intum/Artemis#1692]
### Describe the bug
When viewing the result for a team text exercise, some characters stand  isolated from all other text blocks with - for me at least - no clear pattern

#### To Reproduce

so far, I have only seen this in EIST T02E01. The T01 text exercises and all "normal" text exercises worked without a flaw. Maybe @MaisiKoleni could comment further on what he did

#### Expected behavior

The text should be displayed "normally" as in the other text exercises.

#### Screenshots

![grafik](https://user-images.githubusercontent.com/52559465/85264212-a5401a80-b470-11ea-92ef-c9139160d361.png)

### Environment

<details><pre>
 - OS: Windows 10 x64
 - Browser: Firefox
 - Version77.0.1
</pre></details>

**Comment by FlorianGlombik** [comment]
I might be mistaken, but I do not see a bug here.

From my experience of assessing text exercises, the assessing tutor made use of the automatic text block detection and did not manually mark the text blocks. _(So for the headlines - Usability, Portability, ... - that are useful for structuring the contribution but do not contribute to the content of the explanation, no points are awarded)_

As the headlines have not been assessed, they are not highlighted. Do I miss your point @NiOHar?

**Comment by ge65cer** [comment]
This is fixed.
