### ISSUE TITLE
NullpointerException: Generate StudentExams after deleting Exercise Groups

### ISSUE THREAD

**Issue by TobiasPr** [ls1intum/Artemis#1702]
### Describe the bug

Nullpointer when trying to generate student exams after deleting some exercise groups
java.lang.NullPointerException: null
	at de.tum.in.www1.artemis.service.ExamService.generateStudentExams(ExamService.java:167)

#### To Reproduce

1. Create an Exam
2. Create Exercise Groups
3. Add Students
4. Delete some Exercise Groups
5. Try generate StudentExams
6. NullpointerException occurs

#### Expected behavior

generate student exams

### Environment

<details><pre>
</pre></details>

#### Additional context

![image](https://user-images.githubusercontent.com/22955066/85420577-af970d00-b573-11ea-9230-6ae33db98ff8.png)

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by sascha11110** [comment]
Should be solved by https://github.com/ls1intum/Artemis/pull/1698

**Comment by sascha11110** [comment]
Solved by https://github.com/ls1intum/Artemis/pull/1698
