### ISSUE TITLE
Additional Feedback not displayed on team exercises for students

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#1708]
#### To Reproduce
1. Create a team exercise
2. Participate with a student
3. Assess this with additional feedback
4. Check as student and see that you have no feedback

#### Expected behavior
The feedback gets presented

#### Additional context
It seems like the content of the feedback doesn't event get passed in the call.

**Comment by julian-christl** [comment]
This is apparently only an issue with modeling exercises (team) it works for text exercises (team).
It was tested with a component, deployment and one usecase diagram.

**Comment by julian-christl** [comment]
Okay apparently there is an issue in the templates.
If you remove the hidden attribute here the feedback get's shown:
[![Screenshot from Gyazo](https://gyazo.com/caf17c07971874c11cdd514a30973024/raw)](https://gyazo.com/caf17c07971874c11cdd514a30973024)

**Comment by tiffca** [comment]
Viewing the assessment of team exercises worked for me for class/component modelling exercises. I wasn't able to reproduce this

**Comment by julian-christl** [comment]
@tiffca Just to double-check: You added "additional feedback" (not just the already existing text box)?

**Comment by krusche** [comment]
@julian-christl could you provide a screenshot and highlight what exactly you would expect?

**Comment by krusche** [comment]
and is it really team specific or does it also happen for individual modeling exercises?

**Comment by krusche** [comment]
I just looked into the code and I don't think that we display any additional feedback here

**Comment by EneaGore** [comment]
I am not sure if i understand correctly what exactly is missing but for me it shows all the kinds of Feedback(Elements,add new Feedback,general Feedback) and for different model types, solo or team so i could not reproduce it either it seems.

**Comment by julian-christl** [comment]
@EneaGore Then the issue was already fixed. I just wanted to make this sure because @tiffca didn't mention this explicitly.

@krusche Since it's apparently fixed then I'll just close this issue. Thanks for looking into it though.

**Comment by krusche** [comment]
We still found an issue with "additional feedback" and refactored how it is displayed and made it more consistent in all exercise types in #2953
