### ISSUE TITLE
Quiz, Short-Answer Question: question is marked as invalid when a answer option is correct for multiple fields

### ISSUE THREAD

**Issue by florian-glombik** [ls1intum/Artemis#1711]
### Describe the bug

This bug appears during the creation of a quiz when adding new short-answer questions.
When adding an answer option that is correct in multiple fields, the quiz can't be saved, since the short-answer question is marked as invalid.

#### To Reproduce

1. Go to Course Management
2. Go to Exercises
3. Click on Create Quiz
4. Click on Add Short-Answer Question
5. add a title for the quiz and a title for the question
6. see that the template is still marked as invalid
_(7. let each answer only be valid for one field -> the question is valid)_

#### Expected behavior

It should be possible to save the quiz with an answer option for a short-answer question that is valid for multiple fields.

#### Screenshots

![distributetQuizScheduling#1644-templateFor](https://user-images.githubusercontent.com/63976129/85712245-6caa7600-b6e8-11ea-8bb8-73b3800d5512.gif)

### Environment

<details><pre>
 - OS: Windows 10 Pro
 - Browser: Google Chrome 83.0.4103.116
</pre></details>

**Comment by jerhard** [comment]
This is indeed irritating; if you don't know why the template is considered invalid input, you will spend some time wondering about it. 
I think just changing the template to not contain an short-answer that is valid for multiple fields, i.e. 
the line:
`[-option 1,2] correctInBothFields`
might save people quite some time.

**Comment by jerhard** [comment]
The drag-and-drop interface for answering is not shown to students anyway, right? 
So having a field that is applicable to multiple gaps is not something that needs to be modeled explicitly by this type of exercise anyway? Because one could just enlist it as a possible solution for each gap where it is applicable.

**Comment by fde312** [comment]
@jerhard The problem should be fixed with #2836. We explicitly wanted to support also multiple mappings, e.g. to support exercises like "Name 4 Patterns". Without multiple mappings the order of the entered student answers would be taken into account.
