### ISSUE TITLE
Random password generation not working correctly with Chrome 83 on windows

### ISSUE THREAD

**Issue by eduardfrankford** [ls1intum/Artemis#1725]
### Describe the bug

The random password generation is not working on Chrome, because Chrome automatically fills in a saved password.

#### To Reproduce

1. Let chrome save your password for the admin account
2. Generate a new account in Artemis user management
3. Chrome will not allow the random generation, but will send your admin account password as a newly generated password to the new users email address 

#### Expected behavior
Same password should be used everytime altough random generation is activated

### Environment

 - OS: Windows 10
 - Browser: Chrome
 - Version: 83

**Comment by krusche** [comment]
I don't really understand the issue. Artemis does not send emails to users when creating accounts.
What do you mean with "Let chrome save your password for the admin account" --> this is not a functionality of Artemis.
Which configuration do you use for user management?

Please specify more details and let us know which pages exactly you are using. It also helps if you add screenshots.

Feel free to reopen the issue when you have a better explanation.

**Comment by eduardfrankford** [comment]
### _"I don't really understand the issue. Artemis does not send emails to users when creating accounts."_

Not usually, but the function is available and only has to be uncommented. 
However, the same problem applies for your user generation as well as you generate random passwords if the password field is empty, but it won't be empty because Chrome is able to autofill this field all the time. (with the passwords I saved in chrome password management)

### _"What do you mean with "Let chrome save your password for the admin account" --> this is not a functionality of Artemis."_

Not a functionality of Artemis, but necessary to reproduce the bug and therefore mentioned here.

 ### _"Which configuration do you use for user management?"_

We are using the internal user management of Artemis.

### Screenshots

![bug3](https://user-images.githubusercontent.com/44503138/85984286-4424c380-b9e9-11ea-9571-e34a554785df.PNG)

![bug2](https://user-images.githubusercontent.com/44503138/85984290-46871d80-b9e9-11ea-9819-7f4018b3bd72.PNG)

![bug4](https://user-images.githubusercontent.com/44503138/85984306-4d159500-b9e9-11ea-8751-0e296b2a3b14.PNG)

![bug5](https://user-images.githubusercontent.com/44503138/85984316-50a91c00-b9e9-11ea-9699-e706c6b1ad0a.PNG)
