### ISSUE TITLE
Students cannot see Exam Tab with active Exam

### ISSUE THREAD

**Issue by jpbernius** [ls1intum/Artemis#1734]
### Describe the bug
Students cannot see the Exam Tab in the Course Overview if an exam is visible.

#### To Reproduce

1. Create an Exam with a future visible date
2. Check with **Student** permissions that exam tab is visible
3. Wait until the exam is visible
4. Check with **Student** permissions that exam tab not visible

#### Expected behavior
The exam should be visible to the student.

**Comment by filip-gregurevic** [comment]
Should be fixed with https://github.com/ls1intum/Artemis/pull/1740 and https://github.com/ls1intum/Artemis/commit/c845c7eee6f99bb4eb2b957b50904e7ab0e5eb4f
