### ISSUE TITLE
Exercise indicator misbehaviour on saving issues

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#1735]
### Describe the bug
Exercise

#### To Reproduce
Precondition: You are on a quiz and are getting a 403 on save.
1. Submit & continue
2. The exercise indicator turns checked but stays yellow

#### Expected behavior
The indicator stays unchecked.

#### Screenshots
Didn't made a screenshot during the test exam but I think it's pretty straight forward.

### Environment
<details><pre>
 - OS: Windows 10 Pro
 - Browser: Chrome v83.0.4103.116
</pre></details>

#### Additional context
This happend due to the wrong permissions for students (which was already reported) however in case something goes wrong with saving without going offline I think this should be fixed to prevent confusion.

#### Output in Web Console
Only output regarding the 403 itself but nothing after it regarding the indicator.

**Comment by krusche** [comment]
is fixed now
