### ISSUE TITLE
Exercise indicator misbehaviour on (last) programming exercise

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#1736]
### Describe the bug
When having a programming exercise at the end and you actually finish it (100%) the indicator on the top is not checked. You have to manually click on "Continue" for it to be checked.

This could potentially happen with programming exercises all over the place.

#### To Reproduce
1. Add programming exercise to the end of the exam
2. Solve the programming exercise to 100%
3. See that the exercise is still in progress even though everything is saved and submitted and on 100%

#### Expected behavior
The indicator gets checked once the exercise is on 100% and unchecked again in case the exercise goes to less than 100% again

#### Screenshots
Didn't made a screenshot during the test exam but I think it's pretty straight forward.

### Environment

<details><pre>
 - OS: Windows 10 Pro
 - Browser: Chrome v83.0.4103.116
</pre></details>

**Comment by krusche** [comment]
I think this should be fixed now, can you test it again and reopen in case the specific error that you describe occurs again?
(Please also note then, if it was an offline IDE programming exercises or an online editor one)
