### ISSUE TITLE
No error shown then saving fails

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#1738]
### Describe the bug
When saving changes fails (e.g. like in the 403 case during the tutor test exam) there is no visible error shown.
Sure, it's indicated by the exam indicators not turning blue however this might not be clear for everyone. An error should state that saving the exam failed to the student can act as quick as possible and lose as little time as possible.

#### To Reproduce
1. Force a 403 on save of the exam
2. Try to save the exam
3. See that no error is shown.

#### Expected behavior
An error indicates the issue.

### Environment

<details><pre>
 - OS: Windows 10 Pro
 - Browser: Chrome v83.0.4103.116
</pre></details>

#### Additional context
I don't know it this is a general issue or only one with the 403 that should be checked.

**Comment by krusche** [comment]
we now show errors when saving a submission does not work.
