### ISSUE TITLE
Visual: Start new assessment button mimics event of Open assessment button

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#1750]
### Describe the bug
When clicking on "Open assessment" on the tutor dashboard the Start new assessment button mimics the on click event and starts "loading". It's only a visual bug though.

#### To Reproduce
1. Go to the tutor dashboard
2. Open an exercise
3. Assess one and get back to the exercise overview
4. Click on the open assessment button and see the issue

#### Expected behavior
The Start new assessment button does nothing since no one l

#### Screenshots
[![Screenshot from Gyazo](https://gyazo.com/98fdcf0c1d307bd934db9d721e72acce/raw)](https://gyazo.com/98fdcf0c1d307bd934db9d721e72acce)

### Environment

<details><pre>
 - OS: Windows 10 Pro
 - Browser: Chrome v83.0.4103.116
</pre></details>

**Comment by willergeorg** [comment]
I was not able to reproduce the behavior described locally nor on test server 2. In my attempts, the loading circle is not displayed in the start new assessment button at all.

**Comment by julian-christl** [comment]
Thanks for testing, I mean it's quite an old issue so probably that component was refactored a thousand times already :D Quite possible that it was fixed in the meantime.
