### ISSUE TITLE
Exam mode: Progress is sometimes not stored for multiple choice questions

### ISSUE THREAD

**Issue by jerhard** [ls1intum/Artemis#1770]
### Describe the bug
Students reported that progress was lost on some exercises when they reloaded the page, even when they clicked on the "submit & continue" button and when they worked on the exercise more than 60 seconds ago before they reloaded the page.

#### To Reproduce
1. participate in exam
2. work on multiple choice questions
3. Click on "submit & continue" and additionally wait > 60 seconds
4. Some of the progress (e.g. check marks in MC questions) may be lost

#### Expected behavior
Progress should not be lost. 
Additionally, it would be nice that, when some of the current state is not stored, it were indicated to the user.

#### Additional context
Some users reported that at the end of the exam, their summary did not contain some of the work they did on the exercises.
I am not sure whether this is related and e.g. caused by progress that has not been stored.

**Comment by ghagerer** [comment]
Thank you for marking this as critical @MaisiKoleni :).

**Comment by krusche** [comment]
We are already looking into this and will fix this ASAP

**Comment by jerhard** [comment]
After having reread the student remarks, there indeed seem to be only reports of this issue affecting quizzes (and not other exercise types). Might still be worthwhile to check the other exercise types.
