### ISSUE TITLE
Using Artemis internal user management: No mails are sent

### ISSUE THREAD

**Issue by snowball77** [ls1intum/Artemis#1779]
### Describe the bug
I have created a couple of users. When selecting "random password" I was expecting the users get a mail with the generated password. However, no mails have been sent. Also I did not find a link for those users to reset their password on their own. Looking into the code a bit, I found MailService.java. However, that is using the templates from the resources which are the JHipster templates and not even Artemis templates.

#### To Reproduce
None existing functionality. Cannot be reproduced.

#### Expected behavior
A mail is sent for every user created with a random password. A "Reset password" link on the login page.

### Environment
<details><pre>
 - OS: Linux server, Mac Client
 - Browser Firefox
 - Version HEAD
</pre></details>

#### Additional context
Gitlab and Jenkins connector

**Comment by sleiss** [comment]
@snowball77 I believe that at least the password-reset mail is now working after https://github.com/ls1intum/Artemis/pull/2143 has been merged. Could you maybe verify if the "Random password" mail is still not working?

**Comment by snowball77** [comment]
Password reset works in development branch now and resets the users password in Artemis and Gitlab. At least with that feature the issue is no longer severe. Nevertheless, the new user with the random password is still not informed via mail. Not that she/he exists now, neither that she/he should set a new password or provide the random one.
