### ISSUE TITLE
Support for JPlag

### ISSUE THREAD

**Issue by snowball77** [ls1intum/Artemis#1781]
### Describe the solution you'd like
I am evaluating Artemis for my first semester course with >650 students. Usually they copy quite a lot from each other. Support for a tool like JPlag (https://jplag.ipd.kit.edu/) would be nice to have.

### Describe alternatives you've considered
None yet.

### Additional context
None.

**Comment by krusche** [comment]
You can download all students repos of one exercise as zip file and do the JPlag checks on your local computer.
We talked to instructors who also use JPlag and they told us that there are so many config options that might need to be adapted dynamically, that starting JPlag within Artemis does not really make sense.

**Comment by krusche** [comment]
I just implemented this directly in Artemis in #1995

**Comment by snowball77** [comment]
This sounds great! Another item to test. I will report whether it works in our setting too.
