### ISSUE TITLE
Bulk user subscription into the interal user management

### ISSUE THREAD

**Issue by snowball77** [ls1intum/Artemis#1783]
### Describe the solution you'd like
I have all my students in an external system. However, I can export a CSV with names and mail addresses. I would like to bulk import them. All in one group and ideally all already into the course. All get generated passwords which they should reset themselves.

### Describe alternatives you've considered
Creating another user management system, e.g., LDAP, and populate it via script. However, that are even more systems to setup and configure. Maybe the students can join the course on their own and only the users need to be created? However, I did not figure out yet how to join an open course.

### Additional context
None.

**Comment by sleiss** [comment]
Hi, 
I'm not sure if Artemis supports importing users from a CSV file (@krusche should know that), but the self registration you described is already.
When creating/editing a course, you have to make sure that the option `Student Registration Enabled` is activated (see screenshot 1).
Students can then self-register them to the course on the course overview (see screenshot 2).

Maybe that already helps a bit.

Screenshot 1:
![image](https://user-images.githubusercontent.com/5084100/86294089-2d9e8800-bbf4-11ea-90b3-b54131a27f59.png)
Screenshot 2:
![image](https://user-images.githubusercontent.com/5084100/86294177-54f55500-bbf4-11ea-8e86-12b5de032347.png)

**Comment by snowball77** [comment]
@sleiss Thank you. I have noticed this check box before but was unable to make it work. I have activated it for my test course. When I create a new user in the USER_ROLE and log in using that user, the course overview of this user is empty. I did not find a way to self-register to the course. I am not sure, what mistake I made here when configuring it.

This is my current config:
![Screenshot_2020-07-02 Courses](https://user-images.githubusercontent.com/6409197/86306781-66028e00-bc15-11ea-8515-4e17c0b16d58.png)

This is what my new user sees:
![Screenshot_2020-07-02 Course overview](https://user-images.githubusercontent.com/6409197/86306786-6864e800-bc15-11ea-9ec6-6af93255e4c8.png)

**Comment by b-fein** [comment]
@snowball77 Did you find a solution to that problem? If not, I’m going to submit this as a separate bug report as we currently have the same issue one in our setup with no external user management enabled.

**Comment by snowball77** [comment]
I have not tried with the latest version recently. Maybe leave it open until I next can test it again?

**Comment by snowball77** [comment]
I tested it again with the latest release version. Still no success. Can you file a new bug for this?

**Comment by b-fein** [comment]
CSV import of users exists now on the admin page for the user management:

![image](https://github.com/user-attachments/assets/1c7509b0-6bc4-4d9b-bc38-6e69615e3f99)
