### ISSUE TITLE
Build Output Text Escaping Problems

### ISSUE THREAD

**Issue by kappelmann** [ls1intum/Artemis#1788]
### Describe the bug

When using the online editor, the build output is printing `&nbsp;`, `&quot;`, etc. instead of the corresponding symbols.

Note: We have an exam on Saturday morning and quite a few students seem to prefer using the online editor as their git knowledge is limited. It would hence be wonderful if this could be solved by then :crossed_fingers: otherwise, students will have to fight through a jungle of escaping madness.

#### To Reproduce
Go to https://artemis.ase.in.tum.de/#/courses/65/programming-exercises/1446/code-editor/383935 and put
```haskell
module Exercise where

-- Implement the fibonacci numbers function with initial values fib 0 = 0 and fib 1 = 1
fib :: Integer -> Integer
fib = "hi"
```
in `Exercise.hs`. Press Save and Submit, wait for the build. The build will fail due to a type error and the text with escaped symbols appears.

#### Expected behavior

Show the symbols, not the escaped versions.

#### Screenshots

![image](https://user-images.githubusercontent.com/7101032/86245872-6fa2dc00-bbaa-11ea-9944-a044ed40a866.png)

### Environment

<details><pre>
</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by sleiss** [comment]
Hey @kappelmann ,

I've fixed this in https://github.com/ls1intum/Artemis/pull/1791:

![image](https://user-images.githubusercontent.com/5084100/86270057-ed76df80-bbca-11ea-9ec2-3a52ca32aa2c.png)
