### ISSUE TITLE
After assessment deadline tutors can't assess programming exercises anymore

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#1794]
### Describe the bug
The inputs are readonly and you have no option to add more feedback.
This should however only apply when there already was feedback given. Without feedback a tutor should still be able to assess.

#### To Reproduce
Precondition: User1:Tutor
1. Create a programming team exercise with assessment due date X
2. Participate in the exercise
3. Wait for date X to pass
4. Try to assess the submission
5. See you can't assess

#### Expected behavior
You can assess even after the deadline but then only once

#### Screenshots
<img width="397" alt="screenshot_2020-07-02_at_00 40 53" src="https://user-images.githubusercontent.com/64264938/86346366-1778e200-bc5d-11ea-8d7e-e6d77fc3ff1b.png">

#### Additional context
It is possible to remove the readonly attribute from the inputs to circumvent this => This is only a client side issue, the server accepts any input from the tutors even after the deadline.

**Comment by julian-christl** [comment]
I labeled it critical since it prevents tutors from easily giving feedback if the deadline was missed.
If you think it's not critical due to the workaround (keep in mind you still can't add more feedback with the workaround) then remove it.

**Comment by krusche** [comment]
We completely changed the implementation of manual assessments in programming exercises so this should not be an issue any more
