### ISSUE TITLE
[Exam] Exams only clickable upon browser refresh

### ISSUE THREAD

**Issue by tiffca** [ls1intum/Artemis#1796]
### Describe the bug
As a student/instructor/tutor, go to the "exams" tab and try to select any visible exam. 
Expected: we should be able to select an exam
Actual: we cannot select any exam. Clicking any 'exam' button does not work. After clicking the 'refresh' button, the exam is still not selectable. After refreshing the browser, then we can select an exam. 

#### To Reproduce
Tested on test server 1 in Chrome browser
1. (As a student/instructor/tutor) Go to Course Overview -> Select a Course -> Select the 'Exams' tab 
2. Try to select any visible exam 
3. We are not able to select an exam 
4. Try the refresh button and selecting an exam -> also does not work
5. Refresh the browser and try selecting an exam -> does work

#### Expected behavior
Expected: we should be able to select an exam without having to refresh the browser

#### Screenshots

![exam button](https://user-images.githubusercontent.com/63906424/86401416-7749aa00-bcaa-11ea-876f-44633e1e77e5.gif)

### Environment
Browser: Chrome

#### Additional context
Workaround: Refresh the browser 

#### Output in Web Console
Stack trace from web console: 
```
instrument.js:110 ERROR Error: Uncaught (in promise): DataCloneError: Failed to execute 'pushState' on 'History': function(t){var n=t%10;return t+(1===G(t%100/10)?"th":1===n?"st":2===n?"nd":3===n?"rd":"th")} could not be cloned.
Error: Failed to execute 'pushState' on 'History': function(t){var n=t%10;return t+(1===G(t%100/10)?"th":1===n?"st":2===n?"nd":3===n?"rd":"th")} could not be cloned.
    at History.pushState (instrument.js:286)
    at m.pushState (common.js:159)
    at P.pushState (common.js:481)
    at x.go (common.js:634)
```

```
51 websocket subscriptions:  MapIterator {"/topic/management/feature-toggles", "/topic/course/1/INSTRUCTOR", "/topic/course/21/INSTRUCTOR", "/topic/course/28/INSTRUCTOR", "/topic/course/33/INSTRUCTOR", …}
```

**Comment by krusche** [comment]
There was an issue with the state being set with a probably way too large object. I removed this part and added a TODO that we should implement this differently
