### ISSUE TITLE
Save, Submit, Refresh files not available in exam mode after being offline

### ISSUE THREAD

**Issue by pzdr7** [ls1intum/Artemis#1797]
### Describe the bug

The buttons "Save", "Submit", and "Refresh files" do not become available again after having triggered a save while offline. Refreshing in this state discards the changes that were made offline.

#### To Reproduce

1. Create an exam with one programming exercise (make sure the code editor is enabled) and one other exercise
2. Participate in the exam and navigate to the programming exercise
3. Disconnect and wait until Artemis says you are disconnected
4. Make some changes, e.g. type some text into a file
5. Hit save or wait for the automatic save to trigger, this will lock the Save, Submit and Refresh files buttons
6. Reconnect
7. If you do not do anything (or just switch between exercises), the save, submit, refresh files buttons will not unlock, if you refresh the page, the changes you made offline are lost. I also did not observe a navigation bar change here.

(Workaround: If you make additional changes in the code editor, the buttons will unlock again)

#### Expected behavior

The "Save", "Submit" and "Refresh files" buttons should unlock again after it is clear that saving did not work. There should also be an error message.

#### Screenshots

After reconnecting, the buttons remain unavailable despite there being unsaved changes.

![image](https://user-images.githubusercontent.com/38403547/86444655-5ec0aa80-bd11-11ea-8a2d-7dc6713d65bb.png)

**Comment by JonasSC** [comment]
I had the same issue. Changing between the exercises did not re-enable the buttons. However, making a push from the local repository triggered a new build. After this build was finished, the Submit-button was enabled again.
