### ISSUE TITLE
Exam, programming exercise, "Nachteilsausgleich": after deadline of the exam (without extension) pushing from the local repo not possible

### ISSUE THREAD

**Issue by florian-glombik** [ls1intum/Artemis#1804]
### Describe the bug

A student with a "_Nachteilsausgleich_" _(more time for the exam)_ is not able to work on a programming task from the cloned repository after the _normal_  exam submission deadline is reached.
_Right now the student would have to switch to the online editor, committing something to the remote repository from there is possible until the adjusted working time runs out._

#### To Reproduce

1. Create an exam with a programming exercise
2. give the student that you're using a _Nachteilsausgleich (more time)_
3. Clone the repository and work with your IDE
4. Wait until the _normal_ exam deadline is reached _(without of the extension)_
5. Change something in the online editor and submit it _-> works_ 
6. Try to push from the local repository -> does not work

#### Expected behaviour

The student with a _Nachteilsausgleich_ should be able to work with the local IDE until the end of the adjusted time for the exam.

#### Screenshots

![2020-03-07-testingTheProduction-pushingFromLocalRepoNotWorkingAfterDeadlineWithNachteilsausgleich](https://user-images.githubusercontent.com/63976129/86478094-06f26580-bd4a-11ea-99f4-75c6ee494719.gif)

**Comment by krusche** [comment]
Thanks for finding this issue. I assume this has happened, because the schedule for the programming exercise was set, before the student exam working time was changed.

So when the student working time changes, we should reschedule the task to lock the repository for the specific student

**Comment by krusche** [comment]
When did you actually set the individual working time?

**Comment by krusche** [comment]
I just found out together with @MaisiKoleni that the lock operation is planned at the unlock time, which is the visible. So if you change the working time of one student due to "Nachteilsausgleich" after the visible date of the exam, this will not change the time of the planned lock operation.

Can you please double check when you have actually set the individual working time?

**Comment by krusche** [comment]
This was working successfully for the first exam on Artemis, so I'll close this PR. Please notice that there might be rare edge cases where the automatic lock and unlock might not work, therefore @sleiss added buttons to manually trigger this as well in #1812
