### ISSUE TITLE
The summary can be manipulated after the exam has finished

### ISSUE THREAD

**Issue by JonasSC** [ls1intum/Artemis#1809]
### Describe the bug
The summary, that is displayed after the end of an exam, can be manipulated after the exam has finished.

#### To Reproduce
Either:
1. Finish an exam and wait to be taken to the summary page.
2. Use the browser's developer tools to manipulate the page.

Or:
1. Finish an exam and wait to be taken to the summary page.
2. Change your system time to a point in time, when the exam was still running.
3. Edit your answers.
4. Wait until the system time reaches the exam end time, which will take you to the summary page.
5. Now the summary page contains the edited answers.

#### Expected behavior
Maybe, including a hash of the answers in the summary helps to detect manipulations. However, this hash cannot be computed on the client side, whenever the summary page is displayed, because that would not protect from manipulations of the system time.

### Environment
The manipulations with the developer tools were probably made with Chrome on Windows and MacOS.
The manipulations of the system time were made with Firefox on MacOS.

**Comment by krusche** [comment]
**Just to clarify, the saved answers on the server cannot be changed with such a manipulation!** 
The server returns an error when students try to save / submit answers after the (individual) exam has finished.

However, we should still prevent that students can do the described behavior by simply changing the system time.
It would be best, if the summary page is created as PDF by the server (with some kind of signature to prevent manipulation) and then shown to the students
