### ISSUE TITLE
Refreshing the page can delete checkmarks in quizzes

### ISSUE THREAD

**Issue by JonasSC** [ls1intum/Artemis#1825]
### Describe the bug
When refreshing the page (with the Browser, e.g. by pressing F5) immediately after checking a checkbox in a quiz, the new check mark is gone on the refreshed page.

This issue might be related to Firefox. It did not occur on Chrome.

#### To Reproduce
1. Start a quiz in an exam.
2. Check a checkbox and immediately refresh the page (e.g. press F5).
3. After confirming the message on the start page again and navigating to the quiz, the new check mark is missing.

#### Expected behavior
Refreshing the page should automatically save all current input, so it will be there after the refresh.

### Environment
Firefox on MacOS

**Comment by krusche** [comment]
It takes a few ms until the changes are sent to the server. I consider this as an edge case that does not happen in reality. I also don't think we can easily solve this issue.
