### ISSUE TITLE
Bugs with connections between fork-and-join node and other nodes

### ISSUE THREAD

**Issue by HardMax71** [ls1intum/Artemis#1826]
### Describe the bug

After connecting adding a connection betwenn fork-and-join and action nodes and clicking on the added node (not fork-and-join), changing the position of this added node will also change the position of fork-and-join node.
#### To Reproduce

No1 : 
1. Open UML Activity diagram modelling editor.
2. Add fork-and-join node.
3. Add action node.
4. Add second action node.
5. Firstly, add connection betwenn FnJ and 1st action node.
6. Add connection between FnJ and 2nd action node.
7. Try to move 2nd action node to another position.
8. FnJ node will also change its position.

#### Expected behavior

It's expected, that FnJ node can't change its position in this case.

#### Screenshots
After step 4
![image](https://user-images.githubusercontent.com/66359507/86815790-bb162800-c08b-11ea-9659-4af9c28b9bc7.png)

After step 6
![image](https://user-images.githubusercontent.com/66359507/86815860-d08b5200-c08b-11ea-8cfe-1ee1e2b14756.png)

After step 8
![image](https://user-images.githubusercontent.com/66359507/86815946-ec8ef380-c08b-11ea-8506-edfffc849850.png)

### Environment

<details><pre>
 - OS: Win10
 - Browser : Chrome
 - Version  83.0.4103.116 (Official Build) (64-bit)
</pre></details>

**Comment by tobiasschamel** [comment]
This is related to Apollon - I already created a bug report there: https://github.com/ls1intum/Apollon/issues/113

**Comment by HardMax71** [comment]
@tobiasschamel sorry, didn't notice your post. I've found another bug concerning fork-and-join node, will change this post in 5min.

**Comment by HardMax71** [comment]
@tobiasschamel fixed the bug report. Pls check

**Comment by krusche** [comment]
resolved in Apollon
