### ISSUE TITLE
Original assessors are not able to assess team complaints/complaints show up for non original assessors

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#1834]
### Describe the bug
When trying to assess a complaint of the team exercise (tested with programming exercise) I am not authorized (see errors on screenshot).

#### To Reproduce
1. Open complaint on team programming exercise
2. Assess comlaint
3. See the error

#### Expected behavior
I and every tutor except the one who assessed is capable of assessing the complaint.

#### Screenshots
[![Screenshot from Gyazo](https://gyazo.com/f4ac9f8b283fffdd271cbe5643caa390/raw)](https://gyazo.com/f4ac9f8b283fffdd271cbe5643caa390)

#### Additional context
I do have instructor permissions, even with those it's not working. Possibly just an statement á la if(userIsOwnerOfTeam()) then ...

**Comment by tiffca** [comment]
I thought this was as designed - such that, the same person who assessed should not be able to evaluate their own complaint. Did instructors approve this logic change? Sorry if I missed the discussion.

**Comment by julian-christl** [comment]
As I stated this is the expected behaviour:
> I and every tutor except the one who assessed is capable of assessing the complaint.

It's not my assessment. I just tried to assess the complaint about the assessment of another tutor.

**Comment by krusche** [comment]
We changed this logic for team exercises, because the tutor is really bound to the team.
Therefore, only the tutor of the team (who should also have done the initial assessment), should be able to work on the complaint. Please double check that this intended logic is working.
If this is not the case, please reopen the issue.

**Comment by julian-christl** [comment]
I spoke with a tutor which had an open complaint, she was not able to assess the complaint.

By the way what is the intended way a tutor should realise that there is a complaint? I think no one actually expects to assess the complaints about them and in the Team Overview nothing indicates a complaint. Maybe we should think about something there as well.

**Comment by krusche** [comment]
The complaint should be visible on the team overview page.
@madwau can you please fix this issue?

**Comment by krusche** [comment]
@julian-christl is this related to specific exercise types or to all of them?
Can the other tutor share a screenshot here and some console logs (if available), so that it is easier to fix the issue? Thanks

**Comment by julian-christl** [comment]
For now these two screenshot from the tutor. Both from the submission, no controls available.
![issue1834_1](https://user-images.githubusercontent.com/64264938/87540762-7fd5b380-c6a0-11ea-8c9e-b82d95979cd4.png)
![issue1832_2](https://user-images.githubusercontent.com/64264938/87540770-8106e080-c6a0-11ea-8934-f2a40ef66bf2.png)
She was able to open the submission without any errors, she says.

However we are not sure where exactly this should be shown in the Team Overvew none of us can see something related to complaints.
Besides the team overview is related to one specific exercise. It it intended that you can see there all complaints of your teams or only those relating the current selected exercise because the latter could cause problems since you have to check all the exercises all the time.

I'll check some other exercises to see if it happens only with modeling like this submission.

**Comment by julian-christl** [comment]
Here another tutors assessment of a programming exercise:
![bildschirmfoto_2020-07-15_um_13 55 47](https://user-images.githubusercontent.com/64264938/87544809-579d8300-c6a7-11ea-9b7e-a8008c39b96b.png)
And my view on it:
![a6014599e82020d6e80e59c2b3022483](https://user-images.githubusercontent.com/64264938/87544823-5cfacd80-c6a7-11ea-8110-4f292391808f.png)

However if I try to update the assessmet myself: I get these errors:
[![Screenshot from Gyazo](https://gyazo.com/314e59869f59d8489d1d1fd8edbd8dbd/raw)](https://gyazo.com/314e59869f59d8489d1d1fd8edbd8dbd)
[![Screenshot from Gyazo](https://gyazo.com/29ff92c6f7882b0d01bc0ae1a23b0168/raw)](https://gyazo.com/29ff92c6f7882b0d01bc0ae1a23b0168)
Which is then intended I guess however the other tutor should have my view and vice versa.

**Comment by julian-christl** [comment]
Here now the last part, the text exercises.
<img width="1430" alt="issue1832_3" src="https://user-images.githubusercontent.com/64264938/87659879-7ca0fd00-c75e-11ea-9023-39109d4a15ae.png">
You can see that fact that there is a complaint is shown at the top
<img width="1107" alt="issue1832_4" src="https://user-images.githubusercontent.com/64264938/87659884-7e6ac080-c75e-11ea-9180-6878469c011a.png">
Bot there is nothing to reassess.
Btw it's the same view as for me. So here is no difference at all!

**Comment by madwau** [comment]
For programming exercises I was able to determine the issue: The assessment for programming exercises uses its own dialog and the assessor logic was not adapted to team exercises which explains the reverse behavior observed.

> However we are not sure where exactly this should be shown in the Team Overvew none of us can see something related to complaints.
> Besides the team overview is related to one specific exercise. It it intended that you can see there all complaints of your teams or only those relating the current selected exercise because the latter could cause problems since you have to check all the exercises all the time.

I added an icon that indicates a complaint or a more feedback request (see [here](https://github.com/ls1intum/Artemis/pull/1933)). It will be shown for all exercises in the participation table (not just the current exercise), however, each team page has to be checked.

For the other exercise types, the assessor logic should generally work as intended. If there is a case where the original assessor of a team submission is not allowed to respond to a complaint or feedback, this would need to be investigated on an individual basis.

**Comment by julian-christl** [comment]
Thanks for your work!
> however, each team page has to be checked.

This might be useful to be resolved in a follow up what you think?

>For the other exercise types, the assessor logic should generally work as intended. If there is a case where the original assessor of a team submission is not allowed to respond to a complaint or feedback, this would need to be investigated on an individual basis.

What do you mean? I asked two random tutors with a complaint on the corresponding exercise types and both were not able to assess the complaint (as stated above).
