### ISSUE TITLE
Bug with adding pictures in Quiz excercise

### ISSUE THREAD

**Issue by HardMax71** [ls1intum/Artemis#1839]
### Describe the bug

In L4E1 Quiz, there is an exercise, which requires adding "extends" and "includes" to the Use Case Diagram given. However, after placing "extends" and "includes", their sizes and displacement are not correct (size is smaller, displacement - shifted to the right).

#### To Reproduce

1. Open L4E1 Quiz.
2. Add some nodes to the picture in excercise with Use Case Diagram.
3. Added nodes are placed not correctly.
#### Expected behavior

The size of the node should stay the same and the displacement of added text in UML Diagram should be in the center (not shifted).

#### Screenshots

Before 2.
![image](https://user-images.githubusercontent.com/66359507/86979087-167a1000-c189-11ea-9292-adb9dc87b464.png)
After 3.
![image](https://user-images.githubusercontent.com/66359507/86979128-2eea2a80-c189-11ea-831b-23003f602fd8.png)

### Environment

<details><pre>
 - OS: Win10
 - Browser: Chrome
 - Version: 83
</pre></details>

**Comment by krusche** [comment]
not reproducible any more / was already fixed
