### ISSUE TITLE
Initially wrong and empty files in the online code editor

### ISSUE THREAD

**Issue by JonasSC** [ls1intum/Artemis#1848]
### Describe the bug
In exams with multiple programming exercises, the files in the first programming exercise are often buggy:
- Usually, the bug appears in the first programming exercise. In one case, the first programming exercise was broken (see below), there this big appeared in the second programming exercise.
- The files in the file browser are those of the subsequent exercise.
- When opening a file, the content is not shown. (You can see a 404 error in the browser's developer tools)
- Pressing "Submit" in the broken exercise triggers the build for the exercise, from which the files are shown in the file browser.
- Pressing "Refresh files" fixes the issue.

There was an exam with a broken programming exercise, that allowed to recreate the buggy state, even after fixing the issue with the "Refresh files" button. Here, it was necessary to press the "Retry" button to break the other programming exercise again. Nadine knows more about the broken programming exercise.

#### To Reproduce
1. Prepare an exam with multiple programming exercises.
2. Take that exam and work on the programming exercises with the online code editor.

#### Expected behavior
The online code editor should show the correct files, non-empty files should not be displayed as empty and submitting shoult work for the selected exercise.

#### Screenshots
The broken programming exercise looked like this during the exam:
![Screenshot_2020-07-10 Exam(2)](https://user-images.githubusercontent.com/2746810/87140681-32250980-c2a2-11ea-980d-4782d3c15879.png)

### Environment
Tested with multiple Browsers on multiple operating systems.
Chrome on Windows
Firefox on MacOS
Safari on MacOS

**Comment by krusche** [comment]
Does this only occur when the instructor did **not** click on "Prepare exercise start" before the exam starts?

**Comment by JonasSC** [comment]
We have tested it in both situations. However, the exam, in which we clicked the "Prepare exercise start" was the one with the broken exercise. However, the issue also occured from the very beginning and not only when clicking on "Retry" in the broken exercise. So we concluded, that this was a valid test and that the issue is independent of whether "Prepare exercise start" was clicked.

**Comment by krusche** [comment]
Ok, that's weird. Then it seems, that some changes in the last release broke something here. In my last tests this morning, I could not find such a strange behavior like this, that's why I am confused now.

The screenshot should definitely only occur if the exercise was not prepared yet.

Can you provide additional screenshots for the behavior when the exercise was prepared? E.g. screenshots that show the file browser and the empty files?

It would also help to see entries of the browser console

**Comment by JonasSC** [comment]
Here is a little comic strip about what happens with this bug:
We used an exam with two programming exercises and without clicking on "Prepare exercise start". The screenshots are done with Firefox on MacOS from an account with instructor rights. Similar observations were made with Chrome on Windows with instructor and with student rights.

When starting the exam, the first programming exercise looks as expected. The filebrowser shows the correct files and opening a file works:
![01 - Bumpers works initially](https://user-images.githubusercontent.com/2746810/87149123-f3964b80-c2af-11ea-8f39-b704313f9f5f.png)
When selecting the second exercise, everything is looking good, too.
![02 - Strategy pattern works](https://user-images.githubusercontent.com/2746810/87149168-06a91b80-c2b0-11ea-86bc-8e251017ee75.png)
When going back to the first exercise, the file browser shows the files from the second exercise.
![03 - Bumpers shows files of strategy pattern](https://user-images.githubusercontent.com/2746810/87149203-1c1e4580-c2b0-11ea-8981-a2d04494bec4.png)
Also, when attempting to open the files, the files are shown as empty (404 error in the browser console).
![04 - Bumpers files are empty](https://user-images.githubusercontent.com/2746810/87149269-335d3300-c2b0-11ea-8b51-dcd3316bd030.png)
Pressing the "Submit" button works, and it seems to be working on the correct exercise (note how the question marks in the instructions became red crosses).
![05 - Submitting bumpers](https://user-images.githubusercontent.com/2746810/87149446-86cf8100-c2b0-11ea-9717-5ce071258e9e.png)

**Comment by JonasSC** [comment]
There is also a screenshot of the browser console when clicking on the incorrectly displayed files in the file browser.
![image2020-7-10_10-12-20](https://user-images.githubusercontent.com/2746810/87150483-686a8500-c2b2-11ea-9391-16b233f73764.png)

**Comment by krusche** [comment]
This looks like cloning the repository on the Artemis server did not work properly.

**Comment by krusche** [comment]
Just looked into the server logs: there are many exceptions when you have created the programming exercises.
I assume that something in the setup did not work properly. Here is an example:

2020-07-10 12:51:11.753  WARN 8578 --- [io-8080-exec-12] d.t.in.www1.artemis.service.ExamService  : Start exercise for student exam 2900 and exercise 1648 and student 9170
Jul 10 12:51:11 node1 java[8578]: 2020-07-10 12:51:11.762  INFO 8578 --- [io-8080-exec-12] d.t.i.w.a.s.connectors.BitbucketService  : Try to copy repository ATESTPROXYPASDDASASD/repos/atestproxypasddasasd-exercise into atestproxypasddasasd-ge97vez
Jul 10 12:51:11 node1 java[8578]: 2020-07-10 12:51:11.771 ERROR 8578 --- [io-8080-exec-12] d.t.i.w.a.s.connectors.BitbucketService  : Could not fork base repository on https://bitbucket.ase.in.tum.de/rest/api/1.0/projects/ATESTPROXYPASDDASASD/repos/atestproxypasddasasd-exercise using name=atestproxypasddasasd-ge97vez,project={key=ATESTPROXYPASDDASASD}

I am not sure what happened here, but this means that something really went wrong here.

Can you share some information which exercises (course id, exam id, exercise id) have this problem?

**Comment by krusche** [comment]
Here is an example
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/744067/87151503-43771180-c2b4-11ea-9415-fce949faba48.png">

The status "not active" means that something went wrong when "starting" the exercise

**Comment by JonasSC** [comment]
About the many exceptions in the server logs: Those might have been caused by issue #1857. We assume, that the broken programming exercises, that are mentioned in the description are also caused by that issue. However, the screenshots have been made with an exam, where this issue did not occur.

**Comment by krusche** [comment]
I tested this and could not reproduce it. I am pretty sure the problem is related to a wrong configuration of the programming exercises due to https://github.com/ls1intum/Artemis/issues/1857 
Feel free to reopen the issue in case the error appears again after https://github.com/ls1intum/Artemis/issues/1857 has been fixed and deployed.
