### ISSUE TITLE
The icon in the navigation bar does not become yellow, when using the online editor

### ISSUE THREAD

**Issue by JonasSC** [ls1intum/Artemis#1850]
### Describe the bug
Usually, unsaved edits during an exam are highlighted by a yellow icon in the exam's navigation bar. However, when working on a programming exercise with the online editor, the icons are not becoming yellow.

#### To Reproduce
1. Take an exam with a programming exercise
2. Edit a file with the online code editor and observe the navigation bar for the exercises of the exam.

#### Expected behavior
Every unsaved change should be highlighted by a yellow icon.

#### Screenshots
Notice the "Unsaved" at the bottom of the file browser and the all-blue navigation bar for the exercises.
![Screenshot_2020-07-10 Exam(1)](https://user-images.githubusercontent.com/2746810/87142249-91841900-c2a4-11ea-93a1-b601b81fcec1.png)

### Environment
Chrome on Windows
Firefox on MacOS (shown in the screenshot)

**Comment by krusche** [comment]
This has worked before and seems to be a regression
