### ISSUE TITLE
Online editor not displayed correctly when changing the width of the browser

### ISSUE THREAD

**Issue by florian-glombik** [ls1intum/Artemis#1851]
### Describe the bug

As soon as the width of the windows is smaller than 949 pixel, the online code editor is not adjusted correctly.
_(e.g. 735x873 makes the bug visible)_

#### To Reproduce

1. Participate in an exam with a programming exercise with enabled _online code editor_
2. Adjust the size of the window
3. drag the width of the window smaller than 949 pixels and see that the online code editor is not adjusted properly

#### Expected behavior

The online code editor should be adjusted in the same way as the navigation bar.

#### Screenshots

![2020-07-10-6thTesterMeeting-screenSizeNotAdjustedProperly](https://user-images.githubusercontent.com/63976129/87142293-a2cd2580-c2a4-11ea-8a96-770520660559.gif)

### Environment

<details><pre>
 - OS: Windows 10 Pro
 - Browser: Chrome 83.0.4103.116
</pre></details>

**Comment by krusche** [comment]
I guess this is really hard to fix, as we assume a certain min width. I also think this is an edge case. Not even sure if we should try to fix this (because this might break existing functionality and make it even worse)

**Comment by ge65cer** [comment]
Tracked in: https://github.com/ls1intum/Artemis/issues/1460
