### ISSUE TITLE
Add a margin in the summary of the modeling exercises

### ISSUE THREAD

**Issue by JonasSC** [ls1intum/Artemis#1852]
### Describe the bug
In the summary of an exam, the pictures models are cropped so much, that the models touch the frame of the image. This makes it hard to view thin elements like connections, that run along the edged of the image.

#### To Reproduce
1. Take an exam with a modeling exercise
2. Build a model, in which a connection is along at the top, the bottom, the very left or the very right.
3. Look at the model in the exam summary

#### Expected behavior
Adding a little margin between the picture of the model and the frame will solve this issue

#### Screenshots
<img width="986" alt="grafik" src="https://user-images.githubusercontent.com/2746810/87143729-df9a1c00-c2a6-11ea-9542-74d380b86f1b.png">

### Environment
Firefox on MacOS

**Comment by krusche** [comment]
fixed by https://github.com/ls1intum/Artemis/pull/1900
