### ISSUE TITLE
The online editor does not submit automatically at the end of an exam

### ISSUE THREAD

**Issue by JonasSC** [ls1intum/Artemis#1853]
### Describe the bug
When working on a programming exercise with the online editor, the results are note submitted automatically at the end of the exam.

#### To Reproduce
1. Take an exam with a programming exercise.
2. Work on the exercise with the online editor and don't submit your changes.
3. Either save your changes or wait for the automatic saving at the end of the exam.
4. Check the repository with the link, that is shown in the summary. The saved but not submitted changes are missing there.

#### Expected behavior
Since all other types of exercises are automatically saved, when the exam time runs out, the programming exercises should show a similar behavior. However, since last-minute changes are likely to produce build errors, the desired behavior depends on how the exercise is graded.
Here is one proposal:
- At the end of the exam, all unsubmitted changes are submitted into the repository and a build is triggered.
- If this automatic submission builds, this is the one, that is graded.
- If it does not build and there is a previous submission, that builds, that one will be graded.
- If there is no building submission, the automatic submission will be graded (because that is the latest one).

### Environment
Firefox on MacOS

**Comment by krusche** [comment]
This behavior is on purpose. Programming exercises are sensitive to typos. It could happen that students accidentally change something in a file even if they already have 100% and they do not submit it.
If there would be an auto-commit behavior, this could lead to build failed = 0%.
