### ISSUE TITLE
Summary of programming exercise sometimes not displayed correctly

### ISSUE THREAD

**Issue by florian-glombik** [ls1intum/Artemis#1856]
### Describe the bug

It can sometimes happen that programming exercises are not displayed correctly in the summary. "You didn't submit any solution for this exercise." is written in the summary for each programming exercise, even though changes were committed. After reloading the page, the summary is displayed correctly.
_(It seems to be independent from the exam being prepared or not)_

#### To Reproduce (not reliably reproducable)

1. Create an exam with a programming exercise _(when it occurred the exam had multiple programming exercises)_
2. Generate individual exams
3. Prepare the exercises / don't prepare them, they bug can occur in bought cases 
4. Participate in the programming exercises
5. See that the summary displays "You didn't submit any solution for this exercise." for each exercise
6. refresh the page to see the correct summary and get the link to the repository

#### Expected behavior

The correct link should be displayed without the student having to reload the page.
_Since the bug was not reliably reproducible it might also be an option to display a little hint on the summary, that the student might have to reload the page._

#### Screencast
I have only submitted something for Exercise 1, so after reloading the page everything is displayed correctly!

![2020-07-10-6thTesterMeeting-summaryNotDisplayedCorrectly](https://user-images.githubusercontent.com/63976129/87148871-7ec31180-c2af-11ea-9128-1d28a37bf9e6.gif)

#### Screenshot description
1. The summary is displayed after the time for the exam is up
<img width="1378" alt="Did not submit" src="https://user-images.githubusercontent.com/63976129/87149303-43751280-c2b0-11ea-98a8-8911dd290e02.png">

[Did not submit.pdf](https://github.com/ls1intum/Artemis/files/4902813/Did.not.submit.pdf)

2. After reloading the page the correct summary is displayed
<img width="1378" alt="Did submit" src="https://user-images.githubusercontent.com/63976129/87149407-728b8400-c2b0-11ea-9e1f-a5547968e04e.png">

[Did Submit.pdf](https://github.com/ls1intum/Artemis/files/4902819/Did.Submit.pdf)

**Comment by krusche** [comment]
This has been fixed recently
