### ISSUE TITLE
Programming exercise import not working properly

### ISSUE THREAD

**Issue by florian-glombik** [ls1intum/Artemis#1857]
### Describe the bug

The programming exercise import does not work reliably. An internal server error can occur which leads to the template and the solution not being imported.

#### To Reproduce

1. Create an exam
2. Import a programming exercise
3. See the error message

(In case you can't produce this, it occurred on the production server when importing e.g. _H05E01 Layered Architecture_ from the current EIST course - _Introduction to Software Engineering (Summer 2020)_ )

#### Expected behavior

There shouldn't be an error.
The template and the solution should be imported correctly.

#### Screencast
_The last frame shows that the original exercise has a template and a solution._
![2020-07-10-6thTesterMeeting-importNotWorking](https://user-images.githubusercontent.com/63976129/87151484-378b4f80-c2b4-11ea-9a3e-7461dc65098c.gif)

### Environment

<details><pre>
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: 83.0.4103.116
</pre></details>

#### Output in Web Console

<details>
when importing the exercise:
<pre>Request URL: https://artemis.ase.in.tum.de/api/programming-exercises/import/1245
Request Method: POST
Status Code: 500 
</pre>
when trying to build the template result / solution result in the exercise view
<pre>Request URL: https://artemis.ase.in.tum.de/api/programming-submissions/399693/trigger-build?submissionType=INSTRUCTOR
Request Method: POST
Status Code: 404 </pre></details>

**Comment by krusche** [comment]
short names have to be unique. Did you double check that you did not use a short name that was already used before?

**Comment by florian-glombik** [comment]
> short names have to be unique. Did you double check that you did not use a short name that was already used before?

Yes, I have checked that.

1. When entering an already used shortname the following error message appears
![image](https://user-images.githubusercontent.com/63976129/87154078-dade6380-c2b8-11ea-9e52-dbf98300640a.png)
2. I guess that nobody gave this shortname to a task: "thisShouldBeAUniqueShortnameSinceItsVeryLongqqqqqmmmanyxvxy"

**Comment by krusche** [comment]
I cannot reproduce this problem.
I tried it locally and on the test / production server.

I also checked the programming exercises that you have generated with the import. 
The problem seems to be that no repositories and build plans have been generated, but I do not really understand why.

I will try to find the logs with your errors, however this is a bit difficult because we now have 6 server nodes running on production.

Any additional infos would be highly appreciated in order to identify the problem you have experienced and fix it!

**Comment by krusche** [comment]
Ok, I think I found the issue. The project name has to be unique as well.

de.tum.in.www1.artemis.exception.BitbucketException: Error while creating Bitbucket project. Try a different name!
	at de.tum.in.www1.artemis.service.connectors.BitbucketService.createProjectForExercise(BitbucketService.java:588)

Seems that our error checks are not good enough here. I will implement a fix and better error reporting to the client




2020-07-11 12:26:12.758 ERROR 434 --- [http-nio-8080-exec-7] d.t.i.w.a.s.connectors.BitbucketService  : Could not create Bitbucket project atest layered with key ATESTLAYERIMPORTE01

org.springframework.web.client.HttpClientErrorException$Conflict: 409 : [{"errors":[{"context":"name","message":"The project name is already in use","exceptionName":null}]}]
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:125)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:184)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:782)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:740)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:674)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:583)
	at de.tum.in.www1.artemis.service.connectors.BitbucketService.createProjectForExercise(BitbucketService.java:574)

**Comment by krusche** [comment]
I fixed it. Imports will give error messages when the short name or title is already used. I also added some other validations that we use during the generation of new programming exercises
