### ISSUE TITLE
Score view: filters get reset and middle click not working

### ISSUE THREAD

**Issue by lukasstevens** [ls1intum/Artemis#1859]
### Describe the bug
In the score view, you can't middle click on the button `Online editor`. Therefore, you have to open the editor in the same tab. The problem is that the filters (e.g. `Show Build Failed`) get reset if you navigate back.

#### To Reproduce
1. Go to the `Score` view of an exercise.
2. Select `Show Build Failed`
3. Click on `Online Editor` for a submission
4. Go back.

#### Expected behavior
- `Show Build Failed` is still selected
- Online editor is middle-clickable

### Environment

<details><pre>
 - OS: Linux
 - Browser: Firefox
 - Version: 72.0.1
</pre></details>

**Comment by Strohgelaender** [comment]
The buttons on this page now support clicking them with the middle mouse button to open the link in a new tab.
