### ISSUE TITLE
Manual grading: incorrect go to repository link

### ISSUE THREAD

**Issue by lukasstevens** [ls1intum/Artemis#1860]
### Describe the bug
When grading code submission manually, the `Go to repository` is incorrect.

#### To Reproduce
1. Go to tutor dashboard
2. Select an exercise
2. Start a new result
3. Click on `Go to repository`
4. Get a warning that the certificate of bitbucket does not match the URL. (This is due to the URL having the LRZ-id of the student in front, e.g. `ga11mib@url` instead of `url`).

#### Expected behavior
The link should directly lead to the student repository.

### Environment

<details><pre>
 - OS: Linux
 - Browser: Firefox
 - Version: 72.0.1
</pre></details>

**Comment by krusche** [comment]
did you sort the results? There might be an issue in the sorting functions so that the elements in this column are not sorted,
Same might be valid for filtering with the search

**Comment by lukasstevens** [comment]
I didn't do anything else other than clicking on new result.

**Comment by krusche** [comment]
This was fixed
