### ISSUE TITLE
Peer Review.

### ISSUE THREAD

**Issue by sebwolf-de** [ls1intum/Artemis#1861]
### Is your feature request related to a problem?
I, as a course instructor, would like to give the students the possibility to give peer review.

### Describe the solution you'd like
I want to enable peer review for a course. After the submission deadline has ended, student A gets the possibility to see the solution of a randomly chosen and anonymous student B. This could be done by downloading the zip of the assignment repository. Student A has an online editor to give feedback. As soon as A has submitted the feedback, B is notified and can view the feedback. 

### Describe alternatives you've considered
Download the student repositories, anonymize them and manually distribute among all students. Gather and redistribute the feedback manually.

### Additional context
Code Review is common practice for software projects. We should teach students how to work with peer review (getting and giving it).

### Open question
How to deal with students who do not give feedback. If student A does not give feedback to B, B has a disadvantage against a student C, who got feedback from someone else.

**Comment by krusche** [comment]
We currently do not plan this feature as part of Artemis.
