### ISSUE TITLE
Exams appear empty and you cannot particiapte

### ISSUE THREAD

**Issue by Alexanderkrp** [ls1intum/Artemis#1869]
### Describe the bug
Exams appear empty 

#### To Reproduce

1. Go to Artemis
2. Create an exam
3. See that the button 'Create individual Exams' causes error message
4. participate in the exam: enter name and press start

#### Expected behavior

When participating in the exam as student, (artemis_test user1) or as instructor (ga27jip) you cannot see the exercises of the exam. 

![image](https://user-images.githubusercontent.com/52030186/87255871-c8b61e00-c48e-11ea-8519-4441b5231365.png)

### Environment
Browser: Chrome

**Comment by krusche** [comment]
You have to enter the number of exercises in the exam, otherwise this won't work.
I just added a validation if the value is not set, will be fixed in the next release

**Comment by krusche** [comment]
This was resolved!
