### ISSUE TITLE
[exam] asessment of empty modeling exercises not possible

### ISSUE THREAD

**Issue by stefanwaldhauser** [ls1intum/Artemis#1870]
### Describe the bug

Empty Modeling Exercises show up for tutors to correct in a exam, but a correction is not possible as a error is thrown when trying to give 0 points

#### To Reproduce

1. Create Exam with Modeling Exercise
2. Do not enter anything
3. Try to assess the empty submission as a tutor, an error will be thrown

#### Expected behavior

No error thrown.
Best solution: After the exam is finished all empty submission will be automatically given 0 points

#### Screenshots

![image](https://user-images.githubusercontent.com/29718932/87256958-4a11ae80-c497-11ea-8a86-62bfd450b55b.png)
![image](https://user-images.githubusercontent.com/29718932/87256965-57c73400-c497-11ea-8495-92d6389ce241.png)

### Environment

<details><pre>
</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by krusche** [comment]
We will have many empty submissions in exam modeling exercises, so this should rather be fixed quickly (also for course / team exercises) in case this is still an issue
