### ISSUE TITLE
[Student] Exam Mode: Accept terms at the end of an exam

### ISSUE THREAD

**Issue by nvf** [ls1intum/Artemis#1873]
### Describe the solution you'd like

The student's name should also be displayed to be able to copy-paste it in the text field (consistency-wise, similar to the start view).

### Steps:
1. Create an exam & participate
2. When the time is over, the student needs to accept the end terms by typing their name into a text field (& selecting Finish)

**Comment by krusche** [comment]
Fixed 👍
