### ISSUE TITLE
Summary sometimes falsely displays "You didn't submit a solution for this exercise". A page refresh solves this.

### ISSUE THREAD

**Issue by JonasSC** [ls1intum/Artemis#1874]
### Describe the bug
In some cases, the summary shows "You didn't submit a solution for this exercise", even though a solution was submitted. After refreshing the page (with F5), the summary is displayed correctly.

This has been observed in modeling exercises, but it might be related to #1856 , where it occured in programming exercises.

#### To Reproduce
This happened relatively rarely, so it is hard to reproduce reliably. I assume, it has something to do with last second changes, that cause the summary page to be rendered from a different submission than the latest one.

1. Work on an exam
2. Pick an exercise, that is **not** a programming exercise
3. Don't make any changes until the second to last second (to prevent the autosave functionality to make a submission)
4. Make some second to last second changes (don't press save, let the autosave functionality at the end of the exam do the work)
5. Check the summary page
6. If the error occurred, refresh the page and see, if the submission is displayed, now

This procedure uses "second to last second changes" instead of "last second changes" to work arount this issue: https://github.com/ls1intum/Artemis/pull/1867#issuecomment-657621459

#### Expected behavior
Every submission should be displayed in the summary page, because this issue might cause students to panic.

#### Screenshots
Initial summary page after finishing the exam:
![Screenshot_2020-07-13 Exam](https://user-images.githubusercontent.com/2746810/87322857-44b37300-c52e-11ea-86cd-fee5209c6830.png)
After refreshing the page:
![Screenshot_2020-07-13 Exam(1)](https://user-images.githubusercontent.com/2746810/87322865-467d3680-c52e-11ea-8111-b985ff79f85d.png)

### Environment
Firefox on MacOS

**Comment by krusche** [comment]
I think this problem is fixed now. If you experience this again, please reopen the issue!
