### ISSUE TITLE
Store Feedback Consistency in Artemis

### ISSUE THREAD

**Issue by bigultekin** [ls1intum/Artemis#1877]
### Feature

Current system lacks a mechanism to check consistency between tutors' feedback. To solve this, we developed a system in Athene that can detect inconsistencies between feedback comments and scores for text exercises based on the text similarities. [Related PR in Athene](https://github.com/ls1intum/Athene/pull/18). 

**Athene**
In short, Athene part works as follows:

1. Gets a set of text block - feedback pairs
2. Checks the consistency between each new feedback and old feedback in the database.
3. Stores the new feedback
4. Returns the inconsistencies (if there is one)

 **Artemis**
On Artemis side, we want to:

1. Send the text block - feedback pairs (TextAssessmentDTO) of text exercises to Athene after each submission is assessed. 
2. Store the feedback inconsistencies (conflicts).

The ER Diagram of the proposed system looks like this:
<img width="803" alt="ER Diagram - Feedback Conflict" src="https://user-images.githubusercontent.com/60740930/87347060-e056da80-c552-11ea-9365-7d718290aca9.png">
**feedback** entity is already present in the current system. We will only add the **feedback_conflict** entity that represents inconsistency between feedback pairs. The relation between **feedback** and **feedback_conflict** is Lazy. Conflicts are only loaded when needed by the application logic.

### Additional context

 **Analysis**
 So far, we simulated our approach with datasets of old exercises. We grouped text block - feedback pairs based on their submission ids and sent them to Athene group by group. Each execution took 3-4 secs average and we could detect 215 inconsistent pairs promisingly out of 1107 assessment. Since, each request to Athene will be done asynchronously we are not expecting any performance issues. 

 **Current Goal**
Our current goal is to store inconsistencies for one of the upcoming exercise/exam assessments and then check the trustability and performance of our approach. 

 **Future Goal**
Next step will be showing these inconsistencies to tutors in the user interface.

**Note**: Consistency check is only going to be done if the automatic text assessment is enabled.

**Comment by krusche** [comment]
this database change was implemented
