### ISSUE TITLE
Introduce data model change to add achievements

### ISSUE THREAD

**Issue by balazs-czopf** [ls1intum/Artemis#1882]
The goal of my bachelor thesis is to integrate gamification with achievements into Artemis ([Proposal on Confluence page](https://confluence.ase.in.tum.de/display/ArTEMiS/Home)). 

Achievements should be introduced as a new entity with properties as seen in the model down below: a title, a description, an icon, and a rank. The title and description are used to describe the achievement while the icon would be used to display an achievement in the browser. The rank should represent the degree of difficulty of attaining an achievement, gold could represent the highest level, silver and bronze the levels below. For example "Score a 100%  in an exercise" would be golden rank. At the beginning the few achievements should be predefined, but later there could be the possibility to add more new ones.

Now a user can receive several achievements while using artemis throughout the semester and an achievement may have been received by several users. For example user A can hold achievements "Score a 100% in an exercise" and "Hand in your solution within the first day of the exercise´s release" while user B holds achievements "Score a 100% in an exercise" and "Hand in 3 submissions in a row". So in this case it would make sense to link the achievement entity to the already existing user entity by a many-to-many mapping. Also the user should be able to access the list of the achievements he/she earned so far.

For the courses the link to achievements is quite similar: the courses should be able to give an overview of which achievements can be achieved within the course. Also in one course several achievements can be achieved by users and one achievement can possibly be achieved in several courses. For example course A could contain achievements "Score a 100% in an exercise" and "Hand in your solution within the first day of the exercise´s release" while course B contains achievements "Score a 100% in an exercise" and "Hand in 3 submissions in a row". So this link can also be modeled by a many-to-many mapping.
![dm](https://user-images.githubusercontent.com/63286106/87446750-01bed180-c5fa-11ea-9743-3cd888bf46a5.png)

To realize this on database level, we need a new table `achievement`, which persists all achievements contained in Artemis with their attributes and a table `user_achievement` which links achievements to users by their respective IDs. Once again the same goes for courses only that the connecting table for that would be `course_achievement` with columns `course_id` and `achievement_id`.

![db](https://user-images.githubusercontent.com/63286106/87447055-667a2c00-c5fa-11ea-81a9-944d5827d15c.png)

### Alternative Options
- Omit the display of all accessible achievements in a course to make it more like a hidden easter egg hunt.
- Link achievements to exercises to be able to show which achievements can be achieved on an exercise level.
- Link achievements to participations, submissions and/or results to have further information about the submission/participation/result by which the achievement was obtained.

**Comment by TobiasPr** [comment]
Sounds good. I like in this approach, that you also have the opportunity to create Artemis wide achievements, like "ask your first question" or "complete the artemis tutorial", which are not necessarily bound to a course. But I don't really get the rank property of achievements. I mean the achievement itself determines the difficulty. Why is the rank necessary, what is the concept there?
Another question: How was your decision making to go for achievements? Why are we not doing levels or a leaderboard?

**Comment by balazs-czopf** [comment]
While the ranks are not essential, they are a nice way to highlight the different difficulties visually. Also they add the possibility to implement leaderboards based on who has the most golden achievements and so on.

Since @sjagla27 and me both applied for the topic of integrating gamification, we split it up. He is responsible for the leaderboards while I take care of the achievements.

**Comment by anditurdiu** [comment]
I agree with the achievement model proposed, it looks good to me. The user-achievement link is clear and I especially like the association with the course as this can leading to "reusing" achievements for different courses.

**Comment by kloessst** [comment]
I like your proposed changes and the way you presented them. It doesn't change existing entities and can be extended by links to other entities as described in alternative options. Good job!
How are you planning to check, if an user has earned an achievements? For the example 'Score a XX% in an exercise' XX could be 80 for bronze, 90 for silver and 100 for gold. This mapping must be defined either in code or in the database. Do you think it would make sense store these kinds of conditions in the database or do you need more flexibility for more creative achievements?

**Comment by balazs-czopf** [comment]
The checks can be very different depending on what kind of achievement we are talking about, point based (reach 80% of the points), time based (submit your work within 3 days) or progress based (work on your first exercise, hand in three submissions in a row). My approach would be to check certain parameters of the submissions/results mainly after the assessment. Regarding your suggestion for checks on point based achievements that was quite my idea 😄 And I would define criteria like this in code for more flexibility, but it could also make sense to store them in the database.  So that´s actually a good point.

**Comment by krusche** [comment]
It is not clear to me why you need a many-to-many relationship between courses and achievements. No example in your text affects multiple courses.
Instead your examples reference exercises which are not linked at all to the achievements.

I suggest to use a `many-to-one` relationship between achievement and course and between achievement and exercise. Both of them could even be unidirectional because we will always navigate from a user to his/her achievements and are then interested in a course. 

The navigation from a course (or exercise) to many achievements is typically not necessary (but would also be possible then).

Also I suggest to add more details about the different use cases / features related to achievements. When do you calculate that a user receives an achievement? where do you display it? These is important information to understand how this should be modeled in the database.

Your proposal above does not include enough information!

**Comment by balazs-czopf** [comment]
I suggested a `many-to-many` relationship between achievements and courses because I considered that it should be possible to get the same achievements in different courses. My concrete examples may not have been the best to illustrate this. Nevertheless it would probably make sense for a `many-to-many` relation to store the course in which the achievement was received in the achievement in order to be able to distinguish the achievements from each other if a user received the same ones in different courses.

So it might actually be easier if we simply assume that an achievement can only occur in one course and therefore use a `many-to-one` relation as @krusche suggested. In other words, in two different courses there could be achievements with the exact same properties but without them being the exact same instance (das Gleiche nicht dasselbe).

The navigation from a course to many achievements would make sense if we want to display all achievements within a course as a list so that the user can see which achievements he has earned already and which ones not yet. By displaying all achievements we could trigger the impression of autonomy in students by giving them the possibility to decide for themselves which achievements they want to attain and in which order (how should you be able to decide if you don't know the options?). And autonomy is one of the basic demands of intrinsic motivation. So while of course not being necessary this could still be a useful feature.

The calculation whether someone received an achievement depends on the criterion for the achievement. Most of it I would check if the result is calculated, because then we can check for example for scored points or the submission date. I'm not sure if it makes sense to check the submission date earlier, because I would not give an achievement for an empty or completely wrong submission, even if it would have earned one just by looking at the submission date. If there are achievements like "give a correct answer" (in the questions and answers feature) or "participate in your first task" I would award the achievement when the answer is marked as correct or when the participation is started.

As mentioned earlier I would display a list of all achievements in a course in its dashboard with the achievements not yet received grayed out and the earned ones in color. Otherwise it would be an option to implement an overview page for the user, where he can see all his achievements e.g. grouped by courses.

**Comment by balazs-czopf** [comment]
Here is the updated data model:
![analysis_object_model](https://user-images.githubusercontent.com/63286106/95015328-7f6c0980-064c-11eb-8484-e62fca9b5820.png)
