### ISSUE TITLE
[Exam] Tutor Leaderboard Views have to be adapted to support exam exercises

### ISSUE THREAD

**Issue by stefanwaldhauser** [ls1intum/Artemis#1890]
### Describe the bug

Currently the data for tutor leaderboards come from 5 views in the database:
![image](https://user-images.githubusercontent.com/29718932/87582898-5f771a80-c6db-11ea-8512-a47ce50b38e9.png)
These do not work for exam exercises currently because `exercise.course_id = null` for exam exercies. 

Let's look at the definition of `view_tutor_leaderboard_assessments`:

```<createView replaceIfExists="true" viewName="view_tutor_leaderboard_assessments">select count(*) as assessments, sum(e.`max_score`) as points, u.id as user_id, u.first_name, c.id as course_id, e.id as exercise_id from jhi_user u, user_groups g, course c, exercise e, participation p, result r
            where g.`user_id` = u.id and g.`groups` = c.`teaching_assistant_group_name` and c.id = e.course_id and p.`exercise_id` = e.id and e.`discriminator` in ('M', 'T', 'F') and r.`participation_id` = p.id and r.`assessor_id` = u.id and r.`completion_date` is not null group by u.id, e.id</createView>```

This will not contain exam exercises because the part `c.id = e.course_id` will never be true for the above mentioned reason

**The goal of this ticket would be to either create new views for exam exercises or modify the current views to support both course exercises and exam exercises.**

**Comment by krusche** [comment]
@stefanwaldhauser this is related to the new tutor score table we recently talked about, hence I assign this to you for now.
