### ISSUE TITLE
[Exam] Quiz Results in summary

### ISSUE THREAD

**Issue by fde312** [ls1intum/Artemis#1892]
### Describe the bug

When the publish result date is reached, all answer options are marked as wrong.
![image](https://user-images.githubusercontent.com/41108487/87588293-acf78580-c6e3-11ea-9b0c-1d6fc601dcee.png)

This is the failed server call:
![image](https://user-images.githubusercontent.com/41108487/87588431-f0ea8a80-c6e3-11ea-92fe-e8b28c2beb1d.png)

This is only for user that are students, for admins the call worked fine
<img width="981" alt="image" src="https://user-images.githubusercontent.com/41108487/87588526-1d060b80-c6e4-11ea-883d-df781257d7d5.png">

Probably there is a false permission check in `QuizExerciseResource`

#### To Reproduce

1. Participate in Exam and wait until the result release date
2. Answer options of quiz are all marked as wrong

#### Expected behavior

Answer options that are correct are marked as correct and all that are false are marked as false

**Comment by sascha11110** [comment]
Clicking the *Evaluate quizzes* button in the student exams view solved the problem. Took me some time to figure that out :- D
