### ISSUE TITLE
[Bug]: Quiz page does not reload automatically when quiz starts

### ISSUE THREAD

**Issue by flhhndl** [ls1intum/Artemis#1894]
### Describe the bug
When waiting for a quiz to start, Artemis displays a message not to reload the page because it will automatically reload once the quiz hast started. When the timer is finished, and the page should reload automatically, nothing happens for at least one and a half minutes. When reloading the page manually, the quiz is displayed correctly.

#### To Reproduce
1. Get up in the morning for the weekly EiST good morning quiz
2. Open quiz and wait for the timer to finish
3. Wait and expect the page to reload 
4. Nothing happens
5. reload the page and try to finish the quiz in the time left

#### Expected behavior
The quiz should start automatically as it says

#### Screenshots
I rather spend the time left to finish the quiz.

### Environment
<details><pre>
 - OS: Linux 5.4.0-40-generic x86_64 Ubuntu 20.04 LTS
 - Browser: Google Chrome 
 - Version 83.0.4103.116 (Official Build) (64-bit)
</pre></details>

**Comment by krusche** [comment]
This can happen in case the client is shortly offline and the websocket message for the quiz start is not received. I guess we can only solve this, when there is a planned start.
In case the websocket does not arrive e.g. within 5s after the quiz start is planned, the client could automatically try to reload the quiz.

**Comment by krusche** [comment]
There should be an existing method in the component to reload the quiz
