### ISSUE TITLE
Modeling exercise assessment back button redirection not working for exams

### ISSUE THREAD

**Issue by FlorianGlombik** [ls1intum/Artemis#1905]
### Describe the bug

When using the _assess next_ button during the assessment of a modeling exercise in an exam, the redirection does not work properly.
When having pressed the _assess next_ button _n_ times you will have to press the back button _n_+1 times to be redirected to the tutor dashboard of the exercise.

#### To Reproduce

1. Create an exam with a modeling exercise, make sure there are multiple student submissions (at least 3) 
2. Assess these modeling exercises as a tutor (use the _assess next_ button to go to the next submission)
3. Try to go back to the tutor course dashboard, using the button in the upper left corner
4. See that you're redirected to the previously assessed submissions

#### Expected behavior

The tutor should directly be redirected to the tutor course dashboard.

#### Screenshots

![2020-07-16-8thTesterMeeting-assessmentBackButtonNotWorking](https://user-images.githubusercontent.com/63976129/87790965-bac31d00-c841-11ea-82e8-3c87b807a3e8.gif)

### Environment

<details><pre>
 - OS: Windows 10 Pro
 - Browser : Firefox
</pre></details>

**Comment by jpbernius** [comment]
I could not reproduce this issue. I refactored the logic for text, modeling, and file-upload exercise into one common logic in #2005. Can someone still reproduce this (with/withour the changes from #2005)?

**Comment by krusche** [comment]
this issue should not be relevant any more because we now use breadcrumbs
