### ISSUE TITLE
Change description of "Time left" in the end term acceptance screen

### ISSUE THREAD

**Issue by florian-glombik** [ls1intum/Artemis#1906]
### Is your feature request related to a problem?

The time during the exam and the time in the end screen are displayed as "time left"; this might confuse students when handing in early and seeing two different values for "Time left".

![2020-07-16-leftTimeMightBeConfusing](https://user-images.githubusercontent.com/63976129/87791955-720c6380-c843-11ea-8fe6-51176868ed1c.gif)

### Describe the solution you'd like

The description of "Time left" in the end term acceptance screen could be changed to something like "Time left to submit exam" to prevent confusion.

### Describe alternatives you've considered

Another alternative would be to leave it as it is or add a string/hint beside the timer to explain why there is a difference between the displayed _Time left_ counters.

**Comment by krusche** [comment]
Good finding! Should be easy to fix!
