### ISSUE TITLE
[Exam] Complaing is possible even though there are no scores shown 

### ISSUE THREAD

**Issue by anditurdiu** [ls1intum/Artemis#1907]
### Describe the bug
When the release date of the results is not set but the review period is, the student is allowed to complain, however, no scores are shown, which makes it misleading. We should make setting the release date mandatory and not allow the start student review date to be before the release date.

#### To Reproduce
1. Create an exam, with no result release date. Set the student review period 
2. Participate in the exam, evaluate your submissions. 
3. As a student again, go to the exam summary page.

#### Expected behavior
You should not see the complaint component or the scores should also be shown

### Environment

<details><pre>
 - OS: Windows
 - Browser chromium
</pre></details>

**Comment by krusche** [comment]
I consider this as a mistake of the instructor (setting the dates incorrectly), so this is low priority, but of course, it would be nice if it gets fixed
