### ISSUE TITLE
Clicking "Hand in early" and going back by clicking "Continue" displays a different exercise than initially selected and the bar at the top displays wrong information

### ISSUE THREAD

**Issue by alexmardale** [ls1intum/Artemis#1912]
### Describe the bug

In an exam if you have multiple exercises and click "Hand in early" and then go back to the exam by clicking "Continue", you will be shown a different exercises than the one you were on when you clicked "Hand in early"; the exercise you will be shown is the one after the one you were actually on.
Also, the bar at the top will have the first exercise highlighted and will say that you are on "Exercise 1 of X", no matter what exercise you are actually on.

#### To Reproduce

1. Create an exam with multiple exercises (at least 3)
2. Configure the exam normally and make it ready for students to start (add a student, generate participations, prepare exercises, etc.)
3. Start the exam as a student
4. Select an exercise then click "Hand in early"
5. Go back by clicking "Continue"
6. The exercise that will be displayed is the one to the right of the one you selected in step 4. The bar at the top will say "Exercise 1 of X" and will have the first exercise highlighted, regardless of the exercise that is actually displayed

#### Expected behavior

When returning back to the exam after clicking "Continue", the same exercise is displayed as before clicking "Hand in early".
The bar at the top highlights the correct exercises and the text refers to the correct exercise ("Exercise Y of X" refers to the correct Y)

#### Screenshots

![2020-07-17-15-56-57](https://user-images.githubusercontent.com/39967206/87795729-c36b2180-c848-11ea-930c-d41e9c082fb1.gif)

### Environment

<details><pre>
 - OS: Linux (Ubuntu)
 - Browser Chrome
 - Version 83.0.4103.116 (Official Build) (64-bit)
</pre></details>

**Comment by Varnika-Tyagi** [comment]
I can confirm this bug. Also, once you return to the 'n+1'th exercise (after clicking on 'Hand in Early'), the 'Save and Continue' button vanishes. If you scroll to the next/previous exercise, it appears again.
