### ISSUE TITLE
Activity diagram of my H09E03 submission cannot be seen entirely (can only be seen entirely at <=25% zoom out) (ge34liw)

### ISSUE THREAD

**Issue by ivymai** [ls1intum/Artemis#1921]
### Describe the bug

The Activity diagram of my H09E03 submission cannot be seen entirely if the zoom out level is larger than 25%, only a fraction of the right section of my diagram can be seen, even though I already scroll the furthest to the right. However, when I zoom out (using "Zoom out" function of my Chrome browser), I start to see more and more the right section of my diagram. And when the zoom out level is as small as at 25% (and below), the whole diagram can be seen. Yet at that zoom out level nobody can see clearly all elements of it anymore, and I don't want that I have score deduction (or even no score at all) just because the tutor cannot see clearly the entire model ONLY because of an UI bug. 
This is the first time I have encountered this bug. Other modeling exercises before, regardless of how big my model is, I am able to see my entire model (at every zoom level of Chrome browser) by scrolling left right 

#### To Reproduce

1. Go to Artemis
2. Click on exercise H09E03
3. Click on View submission
4. If the Zoom level of your Chrome browser is larger than 25%, the activity diagram cannot be seen entirely (a chunk of it on the right cannot be seen even though you scroll to the end to the right). However, starting at the Zoom out level as small as 25% (and below), the entire diagram can be seen. 

#### Expected behavior

I expect that at whatever Zoom level of Chrome browser, when I scroll the furthest to the left or to the right, I have to be able to view my entire model, in this case the activity model of H09E03.
[**SUGGESTED SOLUTION**]: The tutor should first adjust the Zoom out level of his/her Chrome browser to 25% (or below), so that the entire model can be seen. Then, zoom in using the touchpad of his/her laptop (by expanding the thumb finger & the middle finger away from each other); in that way you will be able to see not only the entire activity model but also each single element of it clearly.
 

#### Screenshots

Detailed screenshots of UI bugs as well as Suggested Solution
![Artemis bug H09E03 Right part of Activity model not seen entirely](https://user-images.githubusercontent.com/37301804/87837231-14a00300-c893-11ea-855a-677e3ce5dce0.PNG)
![Artemis bug H09E03 Right part of Activity model not seen entirely (at zoom out level bigger than 25%)](https://user-images.githubusercontent.com/37301804/87837261-3305fe80-c893-11ea-913b-2105890c4bf2.png)
![Artemis bug H09E03 Now the entire Activity model be seen (if at Chrome zoom out level 25%   below)](https://user-images.githubusercontent.com/37301804/87837271-37321c00-c893-11ea-8a97-8147fb9f6f38.png)
![Suggested solution for tutor to see the entire H09E03 model   each element well](https://user-images.githubusercontent.com/37301804/87837280-3d27fd00-c893-11ea-9724-c2cfe67ce851.png)

### Environment

<details><pre>
 - OS: Windows (newest version)
 - Browser: Google Chrome
 - Version: Version 84.0.4147.89 (Official Build) (64-bit)
</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by krusche** [comment]
Your diagram is simply too big. Modeling is about abstraction!
