### ISSUE TITLE
Exam mode - Tutor can get own assessment with complaint, but cannot update the assessment

### ISSUE THREAD

**Issue by TobiasPr** [ls1intum/Artemis#1922]
### Describe the bug

As a tutor I can see the complaints about my own assessment, can navigate into them, acquire the assessment lock, but cannot do the assessment

#### To Reproduce

1. Create an exam
2. participate and submit it as a student
2. Assess an exercise as a tutor
3. Make a complaint about the assessment as a student
4. As a tutor navigate back to tutor dashboard: you can see the exercise with the complaint
5. navigate into the exercise -> you have the assessment lock, but cannot submit a new assessment

#### Expected behavior

Tutors cannot see complaint requests about own assessments

#### Screenshots

![screenshot_14](https://user-images.githubusercontent.com/22955066/87837424-be7f8f80-c893-11ea-87a9-5516882b9f83.png)

### Environment

<details><pre>
</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by anditurdiu** [comment]
I am analysing this bug and the complaint feature seems to work as expected. 
I logged in with test user 7 and navigated to the exam you mentioned. Indeed the submission is not shown under complaints.
![image](https://user-images.githubusercontent.com/15110960/87871726-3c868800-c9b3-11ea-88a4-d9a395083501.png)
It is unclear to me however, why it is showing up under the student submissions section. I am looking into it
