### ISSUE TITLE
after closing problem statement, can't open it again (H9E3)

### ISSUE THREAD

**Issue by HardMax71** [ls1intum/Artemis#1931]
### Describe the bug

After closing "Problem statement" in H9E3 (in order to read the assesment grade), the "Problem statement" button becomes unclicable (but shouldn't).

#### To Reproduce

1. Open H9E3 with already made diagram
2. Close "Problem statement"
3. Try to click on (<-> open) "Problem statement" 1 more time
4. The button is unclicable, only retrying of the page helps.

#### Expected behavior

The "problem statement" button should be accessible even after closing the problem statement.

#### Screenshots

After step 1.
![image](https://user-images.githubusercontent.com/66359507/87873661-0b668180-c9cc-11ea-894b-107f837ceea9.png)
After step 3.
![image](https://user-images.githubusercontent.com/66359507/87873667-17eada00-c9cc-11ea-976c-3459641a1e16.png)

### Environment

<details><pre>
 - OS: Win10
 - Browser Chrome
 - Version 83
-  Skale : 100%

**Comment by krusche** [comment]
not reproducible
