### ISSUE TITLE
H10E03 not assessible

### ISSUE THREAD

**Issue by Alexanderkrp** [ls1intum/Artemis#1954]
#### To Reproduce

1. Go to 'Artemis'
2. https://artemis.ase.in.tum.de/#/course-management/48/exercises/1597/tutor-dashboard

#### Screenshots

![image](https://user-images.githubusercontent.com/52030186/88207022-75428d80-cc4f-11ea-8b99-f52474c95344.png)

### Environment

<details><pre>
 - Browser : chrome
 
</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by krusche** [comment]
@Alexanderkrp can you please provide more information, otherwise we won't be able to fix the problem.
Please keep in mind that the developers do not have access to this URL and can't find out the reason if you do not add more information!
