### ISSUE TITLE
[Exam] Commit hash is not visible/ is wrong last commit hash

### ISSUE THREAD

**Issue by fde312** [ls1intum/Artemis#1960]
### Describe the bug

The summary showed that I had made no commit and its hash only appeared upon refresh. (Maybe related: My commit caused a build failure).

We found also a issue that the wrong "last" commit hash was displayed (the one before the last was displayed), after reload the right last commit hash was displayed

#### Expected behavior

Always the last commit hash before the repo lock should be shown

**Comment by krusche** [comment]
One issue might be: if a user is offline, the user does not receive the latest submission over websocket. Then we cannot make sure that the last submission and commit hash is shown correctly. 

One way to solve this more reliably would be to load the latest submission when the user clicks on Finish for all programming exercises in the exam

**Comment by kloessst** [comment]
@krusche If I've seen this right, the client fetches the studentExam again on submit. We could attach the latest submission for programming exercises there. But this would bloat the submitExam() call even more.

**Comment by krusche** [comment]
We can check if the response for this REST Call already includes the latest programming submissions.
If yes, we might just need to show it correctly on the client. If not, we could fetch it at this point from the database, if this is not too much effort

**Comment by krusche** [comment]
I think we could do this at this place in the code in `StudentExamService`

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/744067/88381538-e3e62f00-cda6-11ea-97e4-2c450110ea8b.png">

**Comment by krusche** [comment]
We are working on it in the branch `feature/latest-programming-submission`
