### ISSUE TITLE
[Exam] [Investigation] Short answer and drag and drop quizzes not properly saved

### ISSUE THREAD

**Issue by kloessst** [ls1intum/Artemis#1963]
### Describe the bug
For one tester, the short answer and drag and drop quizzes were not properly saved.

#### To Reproduce
Need to investigate if this is reproducible or an user error

#### Expected behavior
All kinds of quizzes are saved properly

**Comment by julian-christl** [comment]
Tested with @tessaRuckstuhl, @fde312 and @anditurdiu. We couldn't reproduce this issue.

**Comment by krusche** [comment]
Not reproducible, so we close it
