### ISSUE TITLE
Text in text exercise assessment screen can overflow

### ISSUE THREAD

**Issue by kloessst** [ls1intum/Artemis#1964]
### Describe the bug
The submitted text of a text exercise can overflow in the assessment view.

#### To Reproduce

1. Submit a text exercise with a lot of tabs
2. Assess the text exercise
-> The text should overflow

#### Expected behavior
The text does not overflow

#### Screenshots
![image2020-7-24_10-41-15](https://user-images.githubusercontent.com/16407766/88381620-0710de80-cda7-11ea-9eab-adfee0585775.png)

**Comment by ge65cer** [comment]
Re-tested, the described bug does no longer occur. If you still experience it, feel free to open another issue.
