### ISSUE TITLE
Help screen of modeling exercises doesn't show in full screen mode

### ISSUE THREAD

**Issue by kloessst** [ls1intum/Artemis#1965]
### Describe the bug
Help functionality in modeling exercises in fullscreen mode does not show anything, but when you exit the full-screen mode, the help window is shown as often as you clicked on it.

#### To Reproduce

1. Enter fullscreen mode in a modeling exercise
2. Click on the help icon multiple times
--> No help is shown
4. Exit the fullscreen mode
--> Help windows is shown as often as clicked on it in fullscreen mode

#### Expected behavior
Help screen is displayed in fullscreen mode and can't be opened multiple times.

**Comment by krusche** [comment]
I think we should just remove the health button in the full screen mode

**Comment by krusche** [comment]
It takes space that can potentially be used for modeling and can still be used in the “normal mode”
—> it’s not necessary in full screen mode!
