### ISSUE TITLE
[Bug] Cannot expand problem statement after collapsing it and feedback is not readable.

### ISSUE THREAD

**Issue by Liqs-v2** [ls1intum/Artemis#1969]
I am dealing with the following [problem.](https://streamable.com/bfznzg) I already brought this problem regarding small screens up in slack and am now trying to use a TV screen, yet the same problem prevails - so I decided to open an issue.

This is on Google Chrome Version 84.0.4147.89 (Offizieller Build) (64-Bit).

When first opening a graded exercise, the feedback is completely hidden from view, with no indication where one might find it or if it did even load. Upon zooming out using the browser's zoom functionality the feedback window appears right of the modelling editor. At this point the font is way too small to be able to still read any of the feedback, the only way to find out what the feedback was is to copy it into some editor.

Upon collapsing the problem statement in the initial view, in order to have some more space in the modelling editor, the button for expanding it is hidden 'below' the modelling editor. It is impossible to interact with this button until one has zoomed out significantly.

My suggestion would be to move the problem statement as well as the feedback below or above the column of the modelling editor, this would also significantly increase usability for lower screen sizes.

**Comment by krusche** [comment]
problem statements can now be collapsed
