### ISSUE TITLE
[Bug] in all Artemis Diagram types Box-Snapping doen't behave as expected

### ISSUE THREAD

**Issue by maciello** [ls1intum/Artemis#1971]
### Describe the bug

The "Snapping Feature" of all Diagram-Boxes is bugged. They don't snap onto the background grid. It is sometimes impossible to align multiple boxes on the same grid-line, because there often is a misalignment by ~1-5 pixels. This is certainly a bug and it doesn't look right.
This Problem affects the Firefox Browser, the Chrome Brower and probably other Browsers as well.
This Problem affects Apollon-Diagrams. (See corresponding Bug report on Apollon)

#### To Reproduce

1. Open Apollon.
2. Put multiple Boxes on the grid next to each other, without using copy & paste.
3. Try to align them on a vertical or horizontal gridline (Background).
4. Some or all of them will be not aligned on the gridline. Their x/y values will differ by ~1-5 pixels. It will be impossible to align them properly, because the boxes can only jump ~10 pixels when moving them.

#### Expected behavior

When placing the boxes on the board, they should snap to the little boxes/gridlines in the background.

#### Screenshots

See Screenshots below.

### Environment

<details><pre>
 - OS: Windows
 - Browser: Firefox
 - Version 78.0.2 (64-bit)
</pre></details>
<details><pre>
 - OS: Windows
 - Browser: Chrome
 - Version 84.0.4147.89 (Offizieller Build) (64-Bit)
</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>
![Boxes_snapping](https://user-images.githubusercontent.com/9354898/88457186-a8219700-ce84-11ea-8b62-3396cbb62745.PNG)
![Boxes_snapping_edit](https://user-images.githubusercontent.com/9354898/88457188-abb51e00-ce84-11ea-9eaf-d9767e1c7333.png)

**Comment by krusche** [comment]
Thanks for the bug report. You already created it in Apollon which is the correct place. So I will close this one here.
Please do not create duplicated issues!
