### ISSUE TITLE
Feedback in modeling exercises covered by problem statement

### ISSUE THREAD

**Issue by mdomanitska** [ls1intum/Artemis#1972]
I use Artemis in Google Chrome  84.0.4147.89 (Official Build) (64-bit) on Mac.
In the submitted modeling exercises feedback from the tutor gets covered by problem statement and I have to chance to read it.
I attach a screen recording of how it looks. The problem persists in all types of modeling exercises (team, individual, lecture). 

[Screen Recording 2020-07-25 at 15.44.29.mov.zip](https://github.com/ls1intum/Artemis/files/4975663/Screen.Recording.2020-07-25.at.15.44.29.mov.zip)

**Comment by krusche** [comment]
the problem statement can now be collapsed
