### ISSUE TITLE
"Disconnected from the server" message in team exercises

### ISSUE THREAD

**Issue by mdomanitska** [ls1intum/Artemis#1973]
“You’re disconnected from the server” issues started happening to me on Artemis during modelling over the last week (when I click on “Submit” this always happens). I also know that some of my teammates had it and it indeed is very confusing:
I click on "Submit", get a red “Disconnected” status (which used to be "Connected" before I clicked on "Submit"), a red alert message “You are disconnected from the server, please check your Internet connection” but at the same time green success message “Your submission was successful”. If I try to submit again, the message persists.

**Comment by krusche** [comment]
we are not able to reproduce the issue any more
