### ISSUE TITLE
Tutor feedback is not displayed at team modelling exercise

### ISSUE THREAD

**Issue by flhhndl** [ls1intum/Artemis#1986]
### Describe the bug
The tutor feedback for our team exercise T04E02 is not displayed. We can only see the specific feedback for the nodes in the modeling exercise. See images attached

#### To Reproduce
1. Open graded team modelling exercise with feedback
2. See that no feedback is displayed
3. Cause confusing with your more feedback request 

#### Expected behavior
The feedback should be displayed in some way

#### Screenshots
![Screenshot from 2020-07-29 17-20-37](https://user-images.githubusercontent.com/29736922/88819941-f73b3500-d1c0-11ea-9670-d5ea85ce1d51.png)
![image](https://user-images.githubusercontent.com/29736922/88820178-408b8480-d1c1-11ea-9cf6-bc7258db61a2.png)

### Environment

<details><pre>
 - OS: Ubuntu 20.04 LTS
 - Browser: Chrome
 - Version: 84.0.4147.89
</pre></details>

**Comment by krusche** [comment]
not reproducible
