### ISSUE TITLE
Activate user registration with confirmation email

### ISSUE THREAD

**Issue by krusche** [ls1intum/Artemis#1987]
The Jhipster template provides the possibility for user registration with confirmation emails.

This should be activated  in Artemis based on a new setting in the yml configuration. Only if user registration is enabled in this setting, it will be shown to users at the start page (e.g. a link below the login screen)

It should be possible to define multiple regular expressions (in the yml configuration) for the email that the users have to use for the registration.

Ideally the email template for the confirmation email is configurable (either as a config file that can be changed on the server by super admins, e.g. as the privacy statement or even better as part of the Artemis GUI in the system administration settings) to include specific information (such as the university name, etc.)

**Comment by krusche** [comment]
I started to implement this feature in the branch https://github.com/ls1intum/Artemis/tree/feature/account-setup

**Comment by krusche** [comment]
User Registration can be activated with a new setting in the yml file now.
If the mail service is specified correctly, this should work.
Users can also change their passwords and update their names in corresponding jhipster template pages then.
They are also synchronized with external systems (such as Gitlab).

What is missing now:
- Testing on the test server
- Improved error messages
- Email pattern checking on the client

**Comment by snowball77** [comment]
This is great news. I will try to test it once I have my servers up and running again on new infrastructure for it

**Comment by snowball77** [comment]
I tested it and it worked - besides some strange internal server errors I got when sending the mail did not succeed but still in the DB the new registration was somehow persisted.
