### ISSUE TITLE
Overview Participations for a specific course

### ISSUE THREAD

**Issue by andreasseitz** [ls1intum/ArTEMiS#2]
As instructors, we want to have the possibility to see/analyze the data for students for a specific course. For example, I want to easily check the overall participations of student A for the course B which had in total 16 exercises so far. 
I want to know, in how many exercises the students participated (14 out of 16).

**Comment by josiasmontag** [comment]
Something like this?
![image](https://cloud.githubusercontent.com/assets/1945577/21859763/3e017b10-d82e-11e6-991c-062bd903925a.png)
More information in the table required?

**Comment by andreasseitz** [comment]
Looks good!

I would enrich the page with further information on top of the page if this is possible:
* name of the course
* number of total exercises for one course
