### ISSUE TITLE
Add support for second correction passes of exam exercises

### ISSUE THREAD

**Issue by jerhard** [ls1intum/Artemis#2015]
### Is your feature request related to a problem?
When grading exams, a second correction pass of each exercise is often required to alleviate possible issues in grading.
Currently, Artemis has no integrated UX for this process.

### Describe the solution you'd like
Tutors and instructors should be able to "grab" exercises that were already corrected once by another tutor/instructor in their view of the exercise correction dashboard. This could either be done by a) displaying a table of all exercises that have been corrected by other tutors or - preferably -  b) with a "correct next exercise" button forwarding the student to the exercise to correct. (If possible, a solution following the latter approach should support locking of assessments, to avoid extra work for tutors.)

### Describe alternatives you've considered
When we performed the correction of the first semester retakes exams for the introduction to informatics/the programming course, 
we manually distributed the exercises to perform a second correction on among the tutors in a way to ensure that exercises are not corrected twice by the same tutor. This process was not streamlined and thus cumbersome.

### Additional context
- The status of the second corrections (#performed second corrections / #all submissions) should be displayed in the course dashboard/the exam dashboard, as well. Similar how this is already the case for corrections and complaints/feedback requests.  
- One can debate for which exercises second corrections should be enabled, and whether it should only be possible to enable it for exercises in exams or also for regular course exercises. I guess it would make sense to make it configurable per exercise, even though we are only planning to use it for exams.

**Comment by jerhard** [comment]
#1838 is related.

**Comment by krusche** [comment]
We started to actively work on this issue and will have a working version until the end of the year

**Comment by anditurdiu** [comment]
This can be closed now? @krusche

**Comment by krusche** [comment]
Yes, the initial version of the second correction is implemented now.
We will further improve it in many small aspects, in particular in terms of usability and user experience, e.g. in the different pages in which you can find the information and access it.
