### ISSUE TITLE
Modeling Exercise Title not trimmed

### ISSUE THREAD

**Issue by Garfield96** [ls1intum/Artemis#2035]
### Describe the bug
If a user accidentally adds trailing whitespaces to the title of a modeling exercise, these whitespaces are stored by Artemis. This causes problems, e.g. if the user wants to delete the exercise and types in the name without the whitespace(s) at the end, Artemis will reject to delete the exercise although the name seems to match.

#### To Reproduce
1. Create modeling exercise with whitespaces at the end of the title
2. Try to delete it

**Comment by MaisiKoleni** [comment]
This also happens for programming exercises, I had that before accidentally.

We should also check on the server-side that the title has no whitespaces at the start or end (And I would prefer to use `String.strip()` for that).
