### ISSUE TITLE
[Feature] Manual Saving in Exercises

### ISSUE THREAD

**Issue by derLalla** [ls1intum/Artemis#2040]
The only way to save an exercise (e.g. in Modeling Editor UML) is via the automatic saving (which takes place in a fixed amount of time?).   

As I wanted to go back to the previous page and alert came up with unsaved changes.
It would be nice to offer a "Save" button, so the student can get assured that his work is saved, when he doesn't want to submit his exercise yet.

**Comment by krusche** [comment]
You can submit as often as you want until the deadline. "Submitting" also includes saving.
