### ISSUE TITLE
Don't show all tasks as successful for 100% or more manual result score

### ISSUE THREAD

**Issue by MaisiKoleni** [ls1intum/Artemis#2051]
### Describe the bug
Don't show all tasks in a programming exercise as green/successful when the result score is 100% or more. It could be the case, that one gets 100% even if some tests didn't pass. (e.g. bonus points or tests that didn't count)

The display for manual 100% results should be the same as the one for 98%.

**Comment by krusche** [comment]
I don't really understand this issue, but I think this has already been reworked and should be fixed now. 
Feel free to reopen it with a more detailed explanation.
