### ISSUE TITLE
Code Editor State in Exam not consistent

### ISSUE THREAD

**Issue by TobiasPr** [ls1intum/Artemis#2054]
### Describe the bug

In the screenshot you see an exam. In this exam multiple code-editor exercises are next to each other (exercise 1-3). Somehow I reached the state, that the exam-navigation-bar thinks the submission is submitted, but the editor says unsubmitted changes.

#### To Reproduce

1. I couldn't reproduce the bug

#### Expected behavior

Consistent state

#### Screenshots

![image](https://user-images.githubusercontent.com/22955066/91174632-d7276480-e6df-11ea-9973-d0d6c25e000a.png)

### Environment

<details><pre>
 - OS: Linux Mint
 - Browser chrome
 - Version Artemis 4.4.5
</pre></details>

#### Additional context

Happend when I tested https://github.com/ls1intum/Artemis/pull/2004. But also happened when reloading the exam page -> error in state not in change detection

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by TobiasPr** [comment]
Might be due to an empty commit, maybe one can revisit after the commit issue (file changes are not added to commit) is solved

**Comment by anditurdiu** [comment]
I remember we fixed this issue @krusche but I cannot find the specific PR. IMO this can be closed.
