### ISSUE TITLE
Show additional Bonus and Plagiarism information in the scores table

### ISSUE THREAD

**Issue by HanyaElhashemy** [ls1intum/Artemis#2055]
### Is your feature request related to a problem?

As an instructor it would be nice to have all information that influence the students exam score all present in one table, for example the table below:
![image](https://user-images.githubusercontent.com/50635005/91175498-30dc5e80-e6e1-11ea-9c7f-053d30220312.png)
This includes information about the bonus points they achieved or if the bonus was not calculated due to plagiarism or missing presentation points.

### Describe the solution you'd like

In the scores table add a column for the bonus: this could have 3 states:
1. the number of score achieved or
2. the word "plagiarism" or 
3. a state that shows that the student didn't fulfil the bonus requirements like for example did not get the required presentation points etc.

In addition, add the label plagiarism to the students statics view so that the student who received plagiarism is also informed about it.

**Comment by krusche** [comment]
instructors can configure a bonus for an exam, then it will be visible on the exam student score page
