### ISSUE TITLE
Running the server from docker-compose

### ISSUE THREAD

**Issue by axel1200** [ls1intum/Artemis#2057]
### Describe the bug
The build fails with the error:
```
...
artemis-server_1  | During the build, one or more dependencies that were declared without a version failed to resolve:
artemis-server_1  |     org.springframework.boot:spring-boot-devtools:
artemis-server_1  |
artemis-server_1  | Did you forget to apply the io.spring.dependency-management plugin to the Artemis project?
artemis-server_1  |
artemis-server_1  |
artemis-server_1  | Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
artemis-server_1  | Use '--warning-mode all' to show the individual deprecation warnings.
artemis-server_1  | See https://docs.gradle.org/6.6/userguide/command_line_interface.html#sec:command_line_warnings
artemis-server_1  |
artemis-server_1  | FAILURE: Build failed with an exception.
artemis-server_1  |
artemis-server_1  | * What went wrong:
artemis-server_1  | Execution failed for task ':bootJar'.
artemis-server_1  | > Could not resolve all files for configuration ':developmentOnly'.
artemis-server_1  |    > Could not find org.springframework.boot:spring-boot-devtools:.
artemis-server_1  |      Required by:
artemis-server_1  |          project :
...
```
#### To Reproduce
Setup development setup using docker-compose.

#### Expected behavior
Application launches

### Environment

<details><pre>
 - OS: Ubuntu 20.04
</pre></details>

#### Additional context
The error goes way when I add a version to the version to the `org.springframework.boot:spring-boot-devtools` dependency. in profile_dev.gradle

**Comment by MarvinKlemp** [comment]
I already opened an issue #2032
But looks like noone is responding.

artemis release 4.0.6 seems to work (But has a lot of other issues like missing icons etc)

**Comment by axel1200** [comment]
The issue is that there is no version specified in the dependency with is fine if you have a special gradle plugin that just uses the spring version for spring related dependencies but this project does not have this so either the version needs to be specified or such a plugin needs to be added. I think adding the version is the intended solution. I can make said change as a PR.

**Comment by axel1200** [comment]
@MarvinKlemp btw I got it running in a VM with docker-compose set up. Just some little things are broken like the generating of UML images, that cause the docker container set up probably misses some packages needed for that. And locally I get a ton of CORS errors which seem to not have much of an effect tho.
