### ISSUE TITLE
[database-change] Store build logs

### ISSUE THREAD

**Issue by sleiss** [ls1intum/Artemis#2067]
This issue tracks the required database changes to store build logs within Artemis.

## Motivation
Currently, Artemis has to fetch the build logs from the CI server (like Bamboo) every time the client requests these logs.
This is not optimal as on the one hand, it causes additional requests to the CI server. On the other hand, the build logs might be cleaned on the CI server and are thus not available anymore.

## Solution
We store the build logs of failed builds within Artemis. If the build plans are cleaned on the CI server, they are still persisted in Artemis.
We do not have to store logs of builds that did not fail as the feedback is then displayed directly within Artemis.

## Implementation
A list of `BuildLogEntry`s  is added to the `ProgrammingSubmission` that is persisted into the database using a `@ManyToOne`/`@OneToMany` relationship. The order of the `BuildLogEntry` is also stored as it is relevant when displaying the logs to the user.

Artemis will still include the current behavior (fetching the build logs) as existing submissions do not have build logs stored in the database and we currently only plan to implement this behavior for Bamboo, not for Jenkins.

**Comment by krusche** [comment]
The proposed changes sound good to me and are approved!

**Comment by sleiss** [comment]
Thanks, I'll close this issue now as the related PR is opened.
