### ISSUE TITLE
Improve test coverage for GitlabService and JenkinsService

### ISSUE THREAD

**Issue by krusche** [ls1intum/Artemis#2077]
Currently the test coverage for `GitlabService` and `JenkinsService` are rather low:

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/744067/91813943-b7d68d00-ec33-11ea-82c3-2465f6f856bf.png">

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/744067/91813980-c15ff500-ec33-11ea-9731-2da03e8b5b5f.png">

We should reach an instruction coverage of at least 80% for all classes and each method in `GitlabService` and `JenkinsService` should be invoked at least once.

The actual communication to both services should be mocked, by providing exemplary responses for the requests used in the tests.

Examples can be found in the tests and mocks for BambooService and BitbucketService

**Comment by krusche** [comment]
@anditurdiu started to implement the corresponding mocks here, but had issues with the used Jenkins library if I remember correctly.

@anditurdiu Can the code with your initial implementation still be found somewhere? Can you assist the developer who will work on this issue?

**Comment by anditurdiu** [comment]
> @anditurdiu started to implement the corresponding mocks here, but had issues with the used Jenkins library if I remember correctly.
> 
> @anditurdiu Can the code with your initial implementation still be found somewhere? Can you assist the developer who will work on this issue?

The changes I had started working on are here: 
https://github.com/ls1intum/Artemis/tree/enhancement/integration-tests/gitlab-jenkins
