### ISSUE TITLE
Inconsistent usage of "back" buttons

### ISSUE THREAD

**Issue by danielrainer** [ls1intum/Artemis#2083]
### Describe the bug

The Artemis frontend has some pages which have a "back" button and some which do not have a "back" button. Also, there are different "back" buttons in use.
#### To Reproduce

1. Go to Course Management -> Tutor Course Dashboard (for any course)
2. There is a white arrow at the top left which brings one back to the Course Management view.
3. Go to Course Management -> Instructor Dashboard (for any course)
4. This page has no "back" button, even though it is quite similar to the Tutor course Dashboard.
5. Go to Course Management -> View (for any course)
6. There is a colored button which reads "Back" and has an arrow in it at the bottom.
7. Go into the code editor
8. There is no "back" button.

#### Expected behavior

The frontend should be comfortably navigable without having to use the browser's "back" functionality. Currently, only some pages allow this, others force the user to make use of the browser's "back" feature or click on _Course Overview_ or _Course Management_ which means some unnecessary clicks in some cases.

#### Screenshots

Tutor Course Dashboard: "back" button at the top left
![Tutor_Course_Dashboard](https://user-images.githubusercontent.com/34983953/91886377-89839c80-ec89-11ea-88ad-497dfd5a354f.png)
Instructor Dashboard: no "back" button
![Instructor_Dashboard](https://user-images.githubusercontent.com/34983953/91886410-97d1b880-ec89-11ea-90fb-bf18f1b656ed.png)
Course Overview: "Back" button at the button
![Course_Overview](https://user-images.githubusercontent.com/34983953/91886906-4e359d80-ec8a-11ea-8dc8-d6c6c27e3c30.png)
Code Editor: no "back" button
![Code_Editor](https://user-images.githubusercontent.com/34983953/91886425-9b653f80-ec89-11ea-8cbf-89e0d5d042bb.png)

**Comment by krusche** [comment]
I would argue that it's not necessary to "reimplement" the back button of the browser. Why should we do this, if the browser offers this functionality and we don't need to write even one line of code?

I would rather suggest that we use bread crump navigation as part of the black navigation bar (at the top) by e.g. using https://getbootstrap.com/docs/4.0/components/breadcrumb/

Then we could remove all custom back buttons as they are not necessary any more!

**Comment by danielrainer** [comment]
> I would argue that it's not necessary to "reimplement" the back button of the browser. Why should we do this, if the browser offers this functionality and we don't need to write even one line of code?
> 
> I would rather suggest that we use bread crump navigation as part of the black navigation bar (at the top) by e.g. using https://getbootstrap.com/docs/4.0/components/breadcrumb/
> 
> Then we could remove all custom back buttons as they are not necessary any more!

I agree, this method of navigation gives more choice and information to the users and can be implemented consistently on all pages. It is a feature I would like to have. When proposing the use of a back button, I thought that it might make it easier for users to know how they can navigate Artemis, but bread crumb navigation also does a better job at this.

Should I adapt this issue or close it and create a new one for the bread crumb navigation feature?

**Comment by danielrainer** [comment]
This issus is no longer relevant since bread crumb navigation seems to be superior in every way.

A corresponding feature request can be found in #2097.
