### ISSUE TITLE
Inconsistent naming of buttons

### ISSUE THREAD

**Issue by danielrainer** [ls1intum/Artemis#2084]
### Describe the bug

On the _Course Management_ page, each course has a _Tutor Course Dashboard_ and an _Instructor Dashboard_ button. It is inconsistent to use the word "Course" for one of them but not the other. The pages which can be reached by clicking the buttons both have the word "Course" in the title.

#### To Reproduce

1. Go to Course Management.
2. Notice the inconsistent use of the word "Course in the buttons _Tutor Course Dashboard_ and  _Instructor Dashboard_.

#### Expected behavior

Make the usage of the word "Course" consistent. Either remove it from _Tutor Course Dashboard_ and the pages which can be reached by clicking the buttons, or rename the button _Instructor Dashboard_ to _Instructor Course Dashboard_.

#### Screenshots

Course Management: buttons described above can be seen on the right
![Course_Management](https://user-images.githubusercontent.com/34983953/91888784-272c9b00-ec8d-11ea-8868-70b020510b09.png)
Makes use of the word "Course".
![Tutor_Course_Dashboard](https://user-images.githubusercontent.com/34983953/91888823-33185d00-ec8d-11ea-9c13-e87a0433975a.png)
Also makes use of the word course, unlike the associated button.
![Instructor_Dashboard](https://user-images.githubusercontent.com/34983953/91888866-3d3a5b80-ec8d-11ea-8953-3f54524ebb0a.png)

**Comment by krusche** [comment]
I would suggest to rename Instructor Dashboard to Instructor Course Dashboard, because there is also an Instructor Exercise Dashboard
