### ISSUE TITLE
Include bread crumb navigation

### ISSUE THREAD

**Issue by danielrainer** [ls1intum/Artemis#2097]
### Is your feature request related to a problem?

Currently, navigation in Artemis is not as easy as it could be. Some pages have a back button, others do not.

### Describe the solution you'd like

Bread crumb navigation seems to be a good solution. It shows users where they are and enables easy navigation. If it is put into the top bar it can be present on all Artemis pages.

### Describe alternatives you've considered

Back buttons give less information, are harder to implement on all pages and mostly duplicate the built in browser _back_ feature.
Having no GUI elements for navigation makes it hard for users to know where they are and allows fewer navigation options.

### Additional context

This feature was already discussed in #2083.

**Comment by ge65cer** [comment]
Implemented. 🙂
