### ISSUE TITLE
Max Score field in Programming Exercise creation has strange behaviour

### ISSUE THREAD

**Issue by danielrainer** [ls1intum/Artemis#2098]
### Describe the bug

The Max Score input field in the Programming Exercise creation is weird in several ways:
- It only allows non-negative integers as input.
- If any value which can be parsed as a number is entered, but it is not a non-negative integer, the following message is displayed:
_The maximum score must be between 1 and 9999!_
This message does not match the input field's behaviour, since 0 is also allowed.
A message like this would also be useful if non-numeric input is given.
- When the input field is in focus an the cursor positioned on it, scrolling changes the Max Score value.

#### To Reproduce

1. Go to _Course Management_.
2. Click on the _Exercises_ button for any course.
3. Click on the _Generate new Programming Exercise_ button.
4. Click into the _Max Score_ input field.
5. Enter a number which is not a non-negative integer, e.g. 2.5
6. See the error message.
7. Enter 0.
8. No error message is present, which contradicts the error message.
9. Enter non-numeric input.
10. No error message is present.
11. Enter a number.
12. With the field selected and the cursor placed on it, scroll with the mouse wheel.
13. See the Max Score change instead of the page view. 

#### Expected behavior

- Scores which are not integers should be allowed.
- A correct error message should be displayed for all invalid input.
- Scrolling should not affect the Max Score but the page view. The current behaviour makes it easy to modify the Max Score by accident without realising it.

#### Screenshots

Numbers other than non-negative integers are not allowed.
![Non_integer_Max_Score](https://user-images.githubusercontent.com/34983953/92761933-70b66d80-f392-11ea-9ed0-0c9d9aded3aa.png)
Zero is allowed, contrary to the above error message
![Zero_Max_Score](https://user-images.githubusercontent.com/34983953/92761483-08678c00-f392-11ea-9cde-c3d4e7820a28.png)
No error message for non-numeric input
![Text_Max_Score](https://user-images.githubusercontent.com/34983953/92761516-0ef60380-f392-11ea-8ec3-194f6e32e733.png)

**Comment by krusche** [comment]
this issue was already fixed
