### ISSUE TITLE
Add Analytics

### ISSUE THREAD

**Issue by andreasseitz** [ls1intum/ArTEMiS#21]
To track the usage of ArTEMiS it would be great to add Analytics/Tracking tools

**Comment by jpbernius** [comment]
Analytics needs to be compliant with [TUM Data Protection policy](https://www.datenschutz.tum.de/en/unterstuetzung/web-presence/#c27).
I will get access to the TUM hosted [matomo-org/matomo](https://github.com/matomo-org/matomo) system for ArTEMiS.
Who needs access to the Analytics Data?
- @krusche 
- @jpbernius 
- Anyone else?

We need to check out [angulartics/angulartics-piwik](https://github.com/angulartics/angulartics-piwik) to see if this library is sufficient and can be integrated with ArTEMiS.

@Ceany is this something relevant to your contributions/thesis?

**Comment by Ceany** [comment]
I think this would be very useful for me. Because I would allow me to analyse which areas of the application and screensizes are used.

**Comment by krusche** [comment]
@jpbernius @maximilianmeier Can we add this into the next release?
