### ISSUE TITLE
Complaint count does not work on Tutor Exercise Dashboard

### ISSUE THREAD

**Issue by fde312** [ls1intum/Artemis#2128]
### Describe the bug

The counter for "Complaints about your assessments" is not calculated correctly. There should be 1 instead of 0.

<img width="1631" alt="image" src="https://user-images.githubusercontent.com/41108487/94374087-23fcc180-010a-11eb-973d-6001badcad3b.png">

After clicking on "Complaints about your assessments":
<img width="1640" alt="image" src="https://user-images.githubusercontent.com/41108487/94374097-3545ce00-010a-11eb-8c94-dca2c97efde0.png">

#### To Reproduce

1. Create exercise, participate and assess with one tutor
2. Complain about assessment
3. Check the count as the tutor who assessed all exercises

#### Expected behavior

Should display the right count 1 instead of 0

#### Screenshots

See above

**Comment by krusche** [comment]
I think this has been fixed already
