### ISSUE TITLE
Recreation of build plans and test repository on import/edit of programming exercises

### ISSUE THREAD

**Issue by kloessst** [ls1intum/Artemis#2138]
### Is your feature request related to a problem?
Build plans and test repository files might change slightly after an update for Artemis or its dependencies. On import/edit of programming exercises, the repositories and build plans are always cloned from the source exercise. Options such as static code analysis or sequential test runs can therefore not be altered on import/edit, as build plans and test repository must also be altered.

### Describe the solution you'd like
Add two new options for the import/edit of programming exercises:
- Recreate build plans
- Recreate test repository (tests of the original exercise should not be lost).

Enable to change the options sequential test runs and static code analysis when the options above have been selected.  

### Describe alternatives you've considered
Standalone recreate build plans/test repository button

**Comment by krusche** [comment]
Build plans can now be recreated #2330 
@kloessst is working on a solution to update test repositories with new content #2414

**Comment by kloessst** [comment]
#2414 does not fully solve the issue as it only updates dependencies and plugins for non-sequential and no static code analysis exercises. We should leave this open until it is fully solved.

**Comment by krusche** [comment]
I think the implementation is good enough now, so we can close the issue
