### ISSUE TITLE
Complaints for file upload exercise possible before result is shown

### ISSUE THREAD

**Issue by kloessst** [ls1intum/Artemis#2139]
### Describe the bug
Results for a file upload exercises are only shown to the student if the assessment due date has passed or no assessment due date was set. On the other hand a student is able to complain or request more feedback as soon as the exercise due date has passed.

#### To Reproduce

1. As a instructor, create a file upload exercise. Set due date and assessment due date
2. As a student, participate in the file upload exercise
3. As a tutor, assess the file upload exercise after the due date
4. As the student, check your the result before the exercise due date
--> No result is shown
5. You can complain or request more feedback

#### Expected behavior
You should only be able to complain, if the result is shown. Either make the results available as soon as an assessment is submitted or hide the complaint/more feedback button until the assessment due date.

**Comment by krusche** [comment]
referenced the wrong issue, this is not yet fixed
