### ISSUE TITLE
Jenkins plugin is deprecated

### ISSUE THREAD

**Issue by axel1200** [ls1intum/Artemis#2158]
### Describe the bug
Jenkins Plugin https://plugins.jenkins.io/multiple-scms/ is outdated and should be replaced.

**Comment by axel1200** [comment]
![Uploading Screenshot from 2020-10-05 12-04-13.png…]()

**Comment by axel1200** [comment]
![Screenshot from 2020-10-05 12-04-13](https://user-images.githubusercontent.com/19996713/95066667-ff54ab00-0702-11eb-8162-84b3e8a2a909.png)

**Comment by krusche** [comment]
I have seen this warning. However, this plugin is important to support multiple git repos. We first need to find a replacement, which probably takes some time, as this is an essential part of the Artemis setup

**Comment by axel1200** [comment]
https://plugins.jenkins.io/workflow-aggregator/ is suggested by the deprecation notice

**Comment by snowball77** [comment]
I have left a nice replacement using Jenkins pipelines in #2169 . We only need to create a pipeline job instead of the current classical job template.

**Comment by sleiss** [comment]
Closing this in favor of #2169. Once we switched to Pipelines, we do not need the Multiple-SCM plugin anymore.
