### ISSUE TITLE
Student self-registration to course not working

### ISSUE THREAD

**Issue by snowball77** [ls1intum/Artemis#2165]
@sleiss Thank you. I have noticed this check box before but was unable to make it work. I have activated it for my test course. When I create a new user in the USER_ROLE and log in using that user, the course overview of this user is empty. I did not find a way to self-register to the course. I am not sure, what mistake I made here when configuring it.

This is my current config:
![Screenshot_2020-07-02 Courses](https://user-images.githubusercontent.com/6409197/86306781-66028e00-bc15-11ea-8515-4e17c0b16d58.png)

This is what my new user sees:
![Screenshot_2020-07-02 Course overview](https://user-images.githubusercontent.com/6409197/86306786-6864e800-bc15-11ea-9ec6-6af93255e4c8.png)

_Originally posted by @snowball77 in https://github.com/ls1intum/Artemis/issues/1783#issuecomment-652729165_

**Comment by snowball77** [comment]
I moved the problem I have with registration of existing users in an open course into a new issue. The problem is that students do not see the open course and hence, cannot self-register. This is also related to #1987 which now, as it works, allows users to self-register to Artemis. The only missing puzzle piece now would be to also self-register in the course.

**Comment by snowball77** [comment]
An additional piece of information: I am using internal user management with GitLab and Jenkins in my setup.

**Comment by sleiss** [comment]
A quick fix would be to make the value of `TUM_USERNAME_REGEX` configurable.
https://github.com/ls1intum/Artemis/blob/be2bd00de534bc4f5d6aab2b821425e8f7951f78/src/main/webapp/app/app.constants.ts#L13

**Comment by snowball77** [comment]
In general it does not seem to be a good idea to have TUM specific variables/settings in the codebase :-) So is this Regex filtering for students which are allowed to self-register? If so, I could test setting it to a wildcard?

**Comment by sleiss** [comment]
@snowball77 You are absolutely right, I assume this was some kind of hotfix some time ago ;-). It should work if you set it to a wildcard and compile Artemis yourself. If you don't want to compile it yourself, you can verify that it's this setting by using a 'valid' TUM username, e.g. `ab12cde`. 
If you have verified that this is the correct option, a fix for this seems quite simple.

**Comment by krusche** [comment]
we will make this configurable in the next release following @sleiss's suggestion.
I guess a setting like `artemis.user-management.courses.allowed-username-pattern` would be helpful here.
If admins do not specify it, any user can register for a course.

**Comment by snowball77** [comment]
I tried it. I have a course "PSE" with student self registration set. I created a new user and logged in. The course still does not appear there.
I have modified the code like so: I put
```
export const TUM_USERNAME_REGEX = /^.*$/;
```
into the file and killed yarn and restarted it with `yarn run`

Is there something wrong in what I did there?

**Comment by snowball77** [comment]
Btw.: Can I debug the thing somehow? Like some log or debug statements in the course overview page which gives an insight why the course is not listed there?

**Comment by krusche** [comment]
You can debug using the Chrome developer tools

**Comment by krusche** [comment]
I added a first implementation of the customization options in the branch `feature/improve-registration`

**Comment by snowball77** [comment]
Thank you for the hint with the debugger. I found my issue at last. I have not had start and end date set by the query restricts to it. When I set it together with the changed config from above I can finally subscribe to my course.
Possible fix suggestions:
a) validate course form. If registration is allowed the dates have to be set too. Otherwise do not allow saving the form.
or
b) use a query with not date range in case the dates are unset

**Comment by krusche** [comment]
Courses need a start and end date at the moment, otherwise they won't be considered for the registration

**Comment by krusche** [comment]
I guess we can change the db query to include courses without start data and without end date as well

**Comment by krusche** [comment]
Should be working in the branch `feature/improve-registration` now.
I will create a PR soon. Let me know if you find any additional issues.
