### ISSUE TITLE
Customizing Jenkins Job Template with Pipelines

### ISSUE THREAD

**Issue by snowball77** [ls1intum/Artemis#2169]
### Is your feature request related to a problem?
Partially. I have a Jenkins in K8s. There it makes only really sense to use build jobs with Jenkins Workflow Scripts as in the script you need to configure the docker container with the build tools inside you need.

### Describe the solution you'd like
At the moment, when creating the Jenkins config, a Jenkins Job template XML is customized and copied. It would be great to allow users to provide their own templates. In doing so I could create, for example, a Pipeline job or a build based on a Jenkinsfile from the Test Repository. 

### Describe alternatives you've considered
None

**Comment by snowball77** [comment]
This feature would also solve #2158 . You could just provide a matching Jenkinsfile in the exercise generator which pulls both git repos (solution & tests) as needed and then calls whatever build tool is desired (e.g., maven).

**Comment by snowball77** [comment]
Related to #2158 : I created a pipeline job for testing purposes. I recreated the checkout and build behavior of the current classical job. It does not do post-build things yet, but that should be easy to achieve too. The Jenkinsfile in the Test repo looks so now:
`
pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps {
        dir('assignment') {
          git(url: 'https://gitlab.artemis.sqa.ddnss.org/PSESORT1/psesort1-solution.git', credentialsId: '095d406e-c208-4b97-81d1-dc14ecc434cb', branch: 'master', changelog: true)
        }
        git(url: 'https://gitlab.artemis.sqa.ddnss.org/PSESORT1/psesort1-tests.git', credentialsId: '095d406e-c208-4b97-81d1-dc14ecc434cb', branch: 'master', changelog: true)

      }
    }
    stage('build') {
      steps {
        withMaven {
          sh 'mvn clean test'
        } 
      }
    }

  }
}
`

**Comment by krusche** [comment]
@snowball77 looks good. we can definitely migrate to pipeline files. Where can we finde a good documentation for pipeline files?
Do you need additional plugins in Jenkins? Is there a REST API to post a pipeline file?

**Comment by snowball77** [comment]
Good documentation is available in a running Jenkins instance when editing a pipleline job via https://jenkins/job/test-pipe/pipeline-syntax/ or via google (as it is the de facto standard for CI/CD when the source should contain also the CI/CD steps). The pipeline file goes best as Jenkinsfile into the root of the Git repo which contains the project to be executed by Jenkins. 

To execute it, it still requires a Job (as far as I know at the moment at least, there is some magic available also that makes Jenkins look for all changes in all repos and all branches it knows and run accordingly. I think this is not the usecase needed in Artemis). The job can be created as the job you used before. Actually it can be the same almost. The only thing is those jobs do not have post processing steps. That means the steps of the postprocessor need to be migrated to the default script as well. For timestamp and the file operations there exist commands. For your custom plugin to sent reports back to Artemis there are two options. It either needs to be made pipeline aware by some handful of code changes. Or it could be replaced. There is a very customizable httpRequest command, which could maybe do the job already out of the box.

Plugins needed are not many. A regular installation of Jenkins now has pipeline installed as default (I used the kubernetes helm chart here - should be similar to the default docker image). The only plugin I had to install additionally was the "Maven Jenkins Pipeline Integration" which supplies the "withMaven" keyword. This keyword makes test reports, build results, stat, etc. available to the Jenkins UI.

**Comment by snowball77** [comment]
[PipelineJobConfig.txt](https://github.com/ls1intum/Artemis/files/5341184/PipelineJobConfig.txt)
Attached my example pipeline Job/config.xml which is equivalent to the existing classical one. It can be triggered by Gitlab Webhook and then it builds the description in the git's Jenkinsfile. That should be easy to convert into a template as it is with the classical template in Artemis' ressources

**Comment by sleiss** [comment]
@snowball77 I just started playing around with the Pipelines, it seems that a pipeline can also be specified directly when creating/configuring the job:
<details>
  <summary>Jenkins Config</summary>


```
<?xml version='1.1' encoding='UTF-8'?>
<flow-definition plugin="workflow-job@2.40">
  <description></description>
  <keepDependencies>false</keepDependencies>
  <properties>
    <com.dabsquared.gitlabjenkins.connection.GitLabConnectionProperty plugin="gitlab-plugin@1.5.13">
      <gitLabConnection>git.sleiss.me</gitLabConnection>
    </com.dabsquared.gitlabjenkins.connection.GitLabConnectionProperty>
  </properties>
  <definition class="org.jenkinsci.plugins.workflow.cps.CpsFlowDefinition" plugin="workflow-cps@2.83">
    <script>pipeline {
    agent any

    tools {
        // Install the Maven version configured as &quot;M3&quot; and add it to the path.
        maven &quot;M3&quot;
    }

    stages {
        stage(&apos;Build&apos;) {
            steps {
                // Get some code from a GitHub repository
                git &apos;https://github.com/jglick/simple-maven-project-with-tests.git&apos;

                // Run Maven on a Unix agent.
                sh &quot;mvn -Dmaven.test.failure.ignore=true clean package&quot;

                // To run Maven on a Windows agent, use
                // bat &quot;mvn -Dmaven.test.failure.ignore=true clean package&quot;
            }

            post {
                // If Maven was able to run the tests, even if some of the test
                // failed, record the test results and archive the jar file.
                success {
                    junit &apos;**/target/surefire-reports/TEST-*.xml&apos;
                    archiveArtifacts &apos;target/*.jar&apos;
                }
            }
        }
    }
}
</script>
    <sandbox>true</sandbox>
  </definition>
  <triggers/>
  <disabled>false</disabled>
</flow-definition>
```
</details>

This also has the advantage that the student can not access the configuration (which he could if there was a Jenkinsfile included in the repository).

**Comment by sleiss** [comment]
I also tested using Docker in the pipeline, this worked fine. Also remote agents are working (but as they are transparent to Artemis, we should not have to worry about this).
I'll have a look if we can update the jenkins plugin to support pipelines.

**Comment by sleiss** [comment]
@snowball77 As it turns out, the Jenkins plugin is already pipeline-compatible :tada: 

This is an example pipeline, that should match our criteria:

```
pipeline {
  agent {
      docker { image 'ls1tum/artemis-maven-template' }
  }
  stages {
    stage('Checkout') {
      steps {
        dir('assignment') {
          git(url: 'https://git.sleiss.me/sleiss/tmp-exercise.git', credentialsId: 'd3b3885a-fbf0-4dd0-8a2c-eef583ea5399', branch: 'master', changelog: true)
        }
        git(url: 'https://git.sleiss.me/sleiss/tmp-tests.git', credentialsId: 'd3b3885a-fbf0-4dd0-8a2c-eef583ea5399', branch: 'master', changelog: true)
      }
    }
    stage('build') {
      steps {
        withMaven {
          sh 'mvn clean test'
        } 
      }
    }
  }
    post {
        always {
            sh 'mkdir results'
            sh 'cp target/surefire-reports/*.xml $WORKSPACE/results/'
            step([$class: 'SendTestResultsNotificationPostBuildTask', credentialsId: '1aab4116-c6d7-4577-a6f2-f002fb493d81', notificationUrl: 'http://simon-leiss.de/payload.php'])
        }
    }
}
```

**Comment by sleiss** [comment]
I had to make some adjustments, but now it's working (some templates still have to be transformed).
I worked on it here: https://github.com/ls1intum/Artemis/tree/feature/jenkins-pipeline

Maybe you can also give it a try and see if it works (as this uses Docker, your agent has to support it).

**Comment by snowball77** [comment]
This sounds very promising. Thank you for working on it. When I find some spare time in the next days, I will give it a try. I can also try to adjust the template to test building in my kubernetes cluster natively. I will let you know on my progress.

**Comment by sleiss** [comment]
Great to hear! Just as a note, as of now, build logs are not working yet for pipeline builds.

**Comment by sleiss** [comment]
Build logs should now be parsed correctly.

**Comment by snowball77** [comment]
> @snowball77 I just started playing around with the Pipelines, it seems that a pipeline can also be specified directly when creating/configuring the job:
> Jenkins Config
> 
> This also has the advantage that the student can not access the configuration (which he could if there was a Jenkinsfile included in the repository).

Just a comment/question: I thought the students cannot access/write the test repository either (and only this one would have the Jenkinsfile in it)? If the students can alter the test repo in the GitLab, they simply can cheat by changing the tests, can't they?

I am asking because using the Jenkinsfile would still give more freedom in customization. At the moment, if I understand correctly, I still would need to hack the template file of my artemis if I need a slightly different pipeline (which I do for building on K8s)

**Comment by sleiss** [comment]
@snowball77
Students can not access the test repository. The problem I see with the Jenkinsfile in the test-repository is that it can't contain the whole configuration regarding the repositories: The Jenkinsfile has to be different for every student as the repository URL differs for every student.

If I understand you correctly, you propose that Jenkins should checkout the repositories nativly and then execute the Jenkinsfile that is stored in the tests-repository?

**Comment by snowball77** [comment]
> @snowball77
> Students can not access the test repository. The problem I see with the Jenkinsfile in the test-repository is that it can't contain the whole configuration regarding the repositories: The Jenkinsfile has to be different for every student as the repository URL differs for every student.
I see the issue. However, wouldn't it be possible to use variables in the Jenkinsfile or something like that? Just an initial idea. Then the variable parts can be configured per student, the static parts can be configured per exercise. I have to admit, I did not think it through completely, just brainstorming.

> If I understand you correctly, you propose that Jenkins should checkout the repositories natively and then executes the Jenkinsfile that is stored in the tests-repository for the actual build steps?
No. I just would like to only use the jenkins feature to only checkout the Jenkinsfile itself and then execute it. If you like, the regular mode when not putting the Jenkinsfile directly into the Job config.

> Also, out of curiosity as I'm not that familiar with K8s: What changes are needed?
For the k8s plugin, the Jenkinsfile needs to declare in the beginning the docker container image which is used to execute the commands specified in the Jenkinsfile. So instead of agent { docker ... } } there it will look somehow like this:
```podTemplate(containers: [
    containerTemplate(name: 'maven', image: 'maven:3.3.9-jdk-8-alpine', ttyEnabled: true, command: 'cat'),
  ]) {
```
Here all build commands would be executed in the maven docker image.

I think, the k8s pipeline config is just one of many possible configs, where a customization of the Jenkinsfile would be needed.

**Comment by krusche** [comment]
@snowball77 normally there are no changes needed in the Jenkinsfile. In the future we could provide customization options:

I see the following options:
1) As part of the server setup in one global file per programming language (e.g. in server administration)
2) On the course level (then an instructors needs knowledge about this)
3) When you setup the programming exercise (I imagine something like an Advanced area, in which the Jenkinsfile could be changed)

In our scenarios, build plans typically need no customization at all after the initial setup (there are only rare cases), which would still be possible when navigating to Jenkins.

Your scenario sounds like a global adaption per server would be necessary, right?
(You could achieve this in your setup already by changing the corresponding Jenkinsfile before building the application)

**Comment by snowball77** [comment]
Yes, correct, my current example would be an adaptation for all Java exercises globally. I can achieve it at the moment as workaround by changing the jenkins job template file in the artemis ressource. Then everytime the jenkins job is created by rendering the template it would render my version. So, at the moment, the discussion should not be a real show stopper for me :)

One could also say, that if I can test @sleiss feature branch successfully, we could close this issue and open new user stories to make this kind of customization "less hacky" - as you nicely sumarized in your list.

**Comment by sleiss** [comment]
The updated jenkins notification plugin can be found here: https://c.sleiss.me/index.php/s/aCTQMtg8qfY48pi
You can also build it yourself if you build this PR: https://github.com/ls1intum/jenkins-server-notification-plugin/pull/3

**Comment by axel1200** [comment]
I ran your thing on our server after rebasing it on develop. I get the following error in Jenkins.
``` 
Started by user Artemis User
Running in Durability level: MAX_SURVIVABILITY
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 4: Invalid agent type "docker" specified. Must be one of [any, label, none] @ line 4, column 13.
               docker { image 'ls1tum/artemis-maven-template:java15-2' }
               ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1085)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:142)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:127)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:571)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:523)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:337)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
Finished: FAILURE

```

**Comment by axel1200** [comment]
That's the pipline file it generated:
```

        pipeline {
        agent {
            docker { image 'ls1tum/artemis-maven-template:java15-2' }
        }
        stages {
            stage('Checkout') {
                steps {
                    checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '70fd2abc-80e8-4382-b225-448c845a2326', name: 'tests', url: 'https://gitlab.christiantiefenau.de/ALPRODEL/alprodel-tests.git']]])
                    dir('assignment') {
                        checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '70fd2abc-80e8-4382-b225-448c845a2326', name: 'assignment', url: 'https://gitlab.christiantiefenau.de/ALPRODEL/alprodel-solution.git']]])
                    }
                }
            }
            stage('Build') {
                steps {
                    timestamps {
                        withMaven {
                            sh 'mvn clean test'
                        }
                    }
                }
            }
        }
        post {
            always {
                sh 'rm -rf results'
                sh 'mkdir results'
                sh 'cp target/surefire-reports/*.xml $WORKSPACE/results/'
                sendTestResults credentialsId: 'bb3f22ea-c6a1-4e73-b910-816b828f6853', notificationUrl: 'https://alpro.besec.uni-bonn.de/api/programming-exercises/new-result'
                cleanWs()
            }
            success {
                sh '''
                mvn spotbugs:spotbugs checkstyle:checkstyle pmd:pmd
mkdir staticCodeAnalysisReports
cp target/spotbugsXml.xml staticCodeAnalysisReports
cp target/checkstyle-result.xml staticCodeAnalysisReports
cp target/pmd.xml staticCodeAnalysisReports
                '''
            }
        }
} 
```

**Comment by snowball77** [comment]
Did you install the plugin to use Docker as build agent in a pipeline?

**Comment by axel1200** [comment]
No I did not. But I am way past that... XD
I had to:
Install Docker plugin and Docker Pipiline
Add a volume that exposes /usr/bin/docker
Add jenkins user to docker group
... still get an error but I come back if I solved it or gave up

**Comment by axel1200** [comment]
I also need to Maven Pipeline Plugin it seems

**Comment by axel1200** [comment]
ok now I get this:
``` 
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (14 kB at 344 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.527 s
[INFO] Finished at: 2020-10-24T21:06:36Z
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'spotbugs' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/var/jenkins_home/workspace/ALPRODEL/ALPRODEL-SOLUTION/?/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException
Error when executing success post condition:
hudson.AbortException: script returned exit code 1
	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.handleExit(DurableTaskStep.java:659)
	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.check(DurableTaskStep.java:605)
	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.run(DurableTaskStep.java:549)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by axel1200** [comment]
![Screenshot from 2020-10-24 23-16-57](https://user-images.githubusercontent.com/19996713/97093756-0cecb900-164f-11eb-9c6e-1f4b6aafab52.png)

**Comment by axel1200** [comment]
BTW I tuned on static code analysis

**Comment by axel1200** [comment]
Plugin is configured as expected:
```
           <plugin>
                <groupId>com.github.spotbugs</groupId>
                <artifactId>spotbugs-maven-plugin</artifactId>
                <version>4.1.3</version>
                <configuration>
                    <xmlOutput>true</xmlOutput>
                    <includeTests>false</includeTests>
                </configuration>
            </plugin>

```

**Comment by snowball77** [comment]
This is not related to the pipeline any more as it comes from the maven run inside the pipeline. Did you add the spotbugs plugin to your maven configuration file?

**Comment by axel1200** [comment]
Well no but it got added automatically

**Comment by axel1200** [comment]
Maybe executed in the wrong directory

**Comment by sleiss** [comment]
@axel1200  Could you try setting up a new exercise without static code analysis? I also wrote to you in Slack in case you want to discuss it there.

**Comment by axel1200** [comment]
So I ran the spotbugs plugin locally and there it works

**Comment by axel1200** [comment]
And locally a get the same exception when I run the command in wrong working directory

**Comment by sleiss** [comment]
@axel1200 @snowball77 I fixed the SCA issue now. Would be great if you could test it aswell!

**Comment by axel1200** [comment]
Will do so soon. Remind me if I forget it

**Comment by snowball77** [comment]
I finally tested it. It works with the master notification plugin. I had to add 'JAVA_HOME=/usr/java/openjdk-15' in front of 'mvn clean install' as my build agent has JAVA_HOME set via enviromental variables and these get transfered into the docker image. Maybe it is more robust to add this in general?

**Comment by axel1200** [comment]
works... What about caching? Like the maven cache so it downloads the plugins less often? Is that possible in Jenkins .... Do you know?

**Comment by sleiss** [comment]
@snowball77 Thanks for testing! That issue regarding the environment variable is weird, maybe we can disable this setting as otherwise updating the docker image gets possibly more complicated.

@axel1200 We could use this setting to cache the `.m2` folder on the docker host:
https://www.jenkins.io/doc/book/pipeline/docker/#caching-data-for-containers
However, I have not tried it out yet. Can you maybe try this option manually?

**Comment by b-fein** [comment]
> @axel1200 We could use this setting to cache the .m2 folder on the docker host:
https://www.jenkins.io/doc/book/pipeline/docker/#caching-data-for-containers
However, I have not tried it out yet. Can you maybe try this option manually?

I tested that earlier today: It works, but you have to be careful as docker writes files as root user. Therefore, another non-docker job that tries to use the same cache fails. But with a separate cache like `args '-v $HOME/.m2_docker:/root/.m2'` there should be no problems.

**Comment by snowball77** [comment]
@b-fein You can also configure the user running the programs of your docker container. Root user docker containers are actually discouraged. It should be configured in the Dockerfile used to built the image. If you configure it to be the same as the user running builds on your agents you can freely mix docker and non-docker builds using the same cache. However, here it also gets individual per target config. Are you using on master node in Jenkins? Are you using Worker nodes? Are you using local/remote docker agents? Are you using kubernetes agent pipelines? And so on... That is why I also asked to have more options to configure the Jenkinsfile as you never will be able to capture all cases (also see my case of the worker node configured via environment variables). I suggest to provide a reasonable default config for a jenkins server which also acts as master itself. This config is the one you have when you are able to follow the Artemis Jenkins/GitLab how-to....

**Comment by b-fein** [comment]
@snowball77 Yes, more configurability in general of such things is definitely desirable.
My comment was not meant to give a full solution to this specific cache problem. It was just meant as a general hint where the linked solution might fail or that it might suddenly produce errors in other build jobs.

**Comment by snowball77** [comment]
@b-fein Yes, understood. I was also just trying to give more hints as the correct config and so on highly depends on the used Jenkins and Docker image setup.

**Comment by sleiss** [comment]
As already discussed earlier between @snowball77 and @krusche, I hope to implement a way to the whole `src/main/resources/templates` directory configurable. We would then include a sample config (which e.g. works on our setup at TUM), which can then be overriden by you. We will then provide variables (such as the `#dockerImageName` which already exists) that can be added to your templates and which can then also be used in other context, e.g. when running using Kubernetes.

I'd still propose that we do this in a follow-up and just try to build the basic config within this issue and once that's done, we can add a way to load templates from the file system.

**Comment by axel1200** [comment]
Pipline does not report results when compilation fails:
```
+ mkdir results
[Pipeline] sh
+ cp 'target/surefire-reports/*.xml' /var/jenkins_home/workspace/ALPROHELLOWORLD/ALPROHELLOWORLD-BASE/results/
cp: cannot stat 'target/surefire-reports/*.xml': No such file or directory
Error when executing cleanup post condition:
hudson.AbortException: script returned exit code 1
	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.handleExit(DurableTaskStep.java:659)
	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.check(DurableTaskStep.java:605)
	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.run(DurableTaskStep.java:549)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[Pipeline] }
[Pipeline] // stage
[Pipeline] }
$ docker stop --time=1 06644fe301864dba69a3f71fcc63be7ce108792b6cd042317e33ca4ca1911f01
$ docker rm -f 06644fe301864dba69a3f71fcc63be7ce108792b6cd042317e33ca4ca1911f01
[Pipeline] // withDockerContainer
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
```

**Comment by axel1200** [comment]
My fix 
![Screenshot from 2020-10-31 16-44-24](https://user-images.githubusercontent.com/19996713/97783484-647fad00-1b98-11eb-95d6-cde90854e517.png)

**Comment by sleiss** [comment]
@axel1200 I believe I already 'fixed' this in https://github.com/ls1intum/Artemis/commit/cf61bfdc297c7ec969b75f0fc6807764ab922dce, are you running an older version/using a pipeline that was created earlier?

**Comment by axel1200** [comment]
Well I guess i gotta merge the new changes in then

**Comment by sleiss** [comment]
I just fixed some issues related to old exercises (that do not yet use pipelines but should still be supported (e.g. so that exercises can be started and logs can be fetched)). I believe that it works quite well now, but I still have to test the 'import exercise' functionality.

@snowball77 Something that might be interesting for you: I've just added a way to load templates from the file system (so basically implemented variant 1 @krusche suggested). You can overwrite existing templates if you put files into the `templates` directory, which must be located next to the `artemis.war` file.
Files that are present in the file system will be used, if a file is not present in the file system, it is loaded from the classpath (e.g. the .war archive).

This is currently only supported for the templates Artemis created, this means all folders within the `src/main/resources/templates/` directory except the `mail` folder.

Would be great if you could test if this solves your issues related to the K8S setup, it should be sufficient to place a `Jenkinsfile` (`Jenkinsfile-staticCodeAnalysis`) in the `templates/jenkins/java` folder.
Note that these files *MUST* start with `pipeline` (e.g. there must not be a comment  before `pipeline`, but there can be one at any other position, if the Jenkinsfile-syntax allows it.

The variables `#dockerImage`, `#testRepository`, `#assignmentRepository`, `#jenkinsNotificationToken` and `#notificationsUrl` will automatically be replaced (for the normal `Jenkinsfile`, within the `Jenkinsfile-staticCodeAnalysis`, `#staticCodeAnalysisScript` is also replaced).
However, you should not need to touch any variables except `#dockerImage` (to adjust it to your K8S agent setup).

Would great if you could test it as I have no K8S setup to test this.

**Comment by snowball77** [comment]
This sound very nice! I will give it a try when I have some spare minutes and report back.

**Comment by sleiss** [comment]
I just fixed the exercise import (would be great if you could also test this).

I also added a label `docker` to the `Jenkinsfile`, which requires agents to also have this label.
This allows a setup where several agents exist, but only some can run docker builds.
@snowball77 @axel1200 @b-fein : You might need to add this label manually to your existing agents.

**Comment by sleiss** [comment]
I created a PR for this issue now (from the existing branch where the development happened): https://github.com/ls1intum/Artemis/pull/2306

Testing steps and some documentation can be found over there.

**Comment by axel1200** [comment]
> Well I guess i gotta merge the new changes in then

Did that an worked

**Comment by axel1200** [comment]
Just so you know, we run you changes on production and works fine till now :D

**Comment by axel1200** [comment]
> I just fixed the exercise import (would be great if you could also test this).
> 
> I also added a label `docker` to the `Jenkinsfile`, which requires agents to also have this label.
> This allows a setup where several agents exist, but only some can run docker builds.
> @snowball77 @axel1200 @b-fein : You might need to add this label manually to your existing agents.

I don't have any agents, I just run one instance :sweat_smile:

**Comment by axel1200** [comment]
![Screenshot from 2020-11-04 00-57-56](https://user-images.githubusercontent.com/19996713/98053444-dd049900-1e38-11eb-85f2-95b2b5a3141d.png)
I am warned about using a H2 DB for maven plugin. Did anybody encounter this ?Do you think I should act on that?

**Comment by axel1200** [comment]
> If you use the feature Trigger downstream pipeline when a snapshot is built it is critical to setup a real production database instead of the default embedded H2 instance. If you don’t do it, it might degrade your environment stability (The H2 database is running in your instance JVM and could request too many resources).

**Comment by axel1200** [comment]
![Screenshot from 2020-11-08 22-03-00](https://user-images.githubusercontent.com/19996713/98484229-41936f80-220e-11eb-8a18-d684f6bd5038.png)
With vs without caching

**Comment by snowball77** [comment]
@sleiss I finally tested a setup with k8s builder - at least manuallyand as a draft. Using the following static Jenkinsfile
```
podTemplate(containers: [
    containerTemplate(name: 'artemis-jdk', image: 'ls1tum/artemis-maven-template:java15-2', ttyEnabled: true, command: 'cat'),
  ], volumes: [
  persistentVolumeClaim(mountPath: '/root/.m2/repository', claimName: 'maven-cache-pvc', readOnly: false)
  ]) {
    node(POD_LABEL) {
            stage('Checkout') {
                    checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '095d406e-c208-4b97-81d1-dc14ecc434cb', name: 'tests', url: 'https://gitlab.artemis.sqa.ddnss.org/K8SPSEK8SSORT/k8spsek8ssort-tests.git']]])
                    dir('assignment') {
                        checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '095d406e-c208-4b97-81d1-dc14ecc434cb', name: 'assignment', url: 'https://gitlab.artemis.sqa.ddnss.org/K8SPSEK8SSORT/k8spsek8ssort-solution.git']]])
                    }
            }
            stage('Build') {
                    container('artemis-jdk') {
                        timestamps {
                                sh 'mvn clean test'
                        }
                    }
            }
       stage('Cleanup') {
            container('artemis-jdk') {
                sh 'mkdir results'
                sh 'cp target/surefire-reports/*.xml $WORKSPACE/results/ || true'
                sendTestResults credentialsId: 'e6c3b8ee-522e-439f-9321-3e51ddb60156', notificationUrl: 'https://artemis.k8s.sqa.ddnss.org/api/programming-exercises/new-result'
            }
       }
    }
}
```
This works fine and, even more important, scales elastic and dynamic in the k8s cluster. Open issue is that there is no post section available at the moment. I can try to put such a template into the filesystem as a template file as suggested by you - the changes to the current default is not so large. However, my current script does not start with `pipeline`. The LTS version of Jenkins does not support pipeline as first command when used in conjunction with k8s. This should be supported from Jenkins 2.266 onwards. Do you enforce at the moment having pipeline as first word?

**Comment by snowball77** [comment]
Btw. I am running now Artemis itself also inside the k8s cluster using slightly adapted versions of the JHipster K8s template files. So, I have all my applications inside a k8s cluster. @krusche Are you interested in a documentation how to achieve this setup?

**Comment by sleiss** [comment]
@snowball77 Were you able to start this exercise as a student? I believe it should not work, as we are using the `pipeline` keyword (which must occur as the first word) when starting an exercise to detect whether a new (pipeline) or old (pre-pipeline) configuration is used:
https://github.com/ls1intum/Artemis/blob/80edddb1244053d1230acdc0290999e9d49778da/src/main/java/de/tum/in/www1/artemis/service/connectors/jenkins/JenkinsService.java#L176

If this causes problems for your setup as you can not add `pipeline`/use a different structure, we might have to adjust this.

**Comment by snowball77** [comment]
@sleiss In order for the old K8s plugin to work we would need to add the `podTemplate` keyword here. But, maybe we should not. 

The new k8s pipeline plugin works with `pipeline` as root keyword too and eventually will become Jenkins LTS too. In this winter term I think it might be more stable to not run the experimental k8s setup but the more stable classical build agent setup. 

With your patch this is now highly configurable (wrt. Java, maven, etc. versions and environments) so we can run hamster programs in it, i.e., for the moment all is fine for us and we keep the k8s setup for later.

**Comment by snowball77** [comment]
@sleiss Btw.: No I did not start it as a student. I only tested that the script works, compiles and transmits the results back to Artemis successfully.
