### ISSUE TITLE
TUM username pattern is hard coded in front end

### ISSUE THREAD

**Issue by axel1200** [ls1intum/Artemis#2203]
### Is your feature request related to a problem?
If your user does not follow the TUM username pattern you are not shown the dialog for registration. This is pretty unintuitive and bad for external use cases. I suggest being able to configure the username pattern via a property in application-artemis.yml.

### Describe the solution you'd like
Make it configurable...

### Describe alternatives you've considered
None 

### Additional context
TUM_USERNAME_REGEX in app.contants.ts should be replaced.

**Comment by axel1200** [comment]
I might look into it even if by fix, for now, it just replacing the pattern with .*

**Comment by krusche** [comment]
will be fixed with #2174
