### ISSUE TITLE
‘Trigger All’ with Manual Assessments present results in inconsistent database state

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#2213]
### Describe the bug
Clicking ‘Trigger All’ in the ‘Configure Grading’ view after manual assessments are created results in them being neither editable nor a tutor being able to create new ones for that student.
The previous manual feedback is still considered partially present by Artemis.

#### To Reproduce
1. Create a Programming Exercise with a manual assessment.
2. Submit a solution as a student.
3. Wait until after the due date and submit a manual assessment as a tutor.
4. Click ‘Trigger All’ in the ‘Configure Grading’ view.
5. The manual submission is no longer available, but no new one can be created for that student.

#### Expected behaviour
The warning when clicking ‘Trigger All’ mentions that all manual assessments will be overwritten by the new automatic feedback. That should enable a tutor to create a new manual assessment even if one existed beforehand.

In my opinion a good improvement over fully removing the manual assessments would be to put all existing ones back into draft mode, so that the existing feedback is not fully lost, but a manual interaction by the tutor to review them is still necessary.

#### Screenshots
The tutor view shows inconsistent behaviour after reproduction steps. The status at the top mentions an existing manual assessment, but it can no longer be changed.
![Screenshot_20201015_220722](https://user-images.githubusercontent.com/64250573/96182758-33677180-0f36-11eb-8487-35eab0d95bd3.png)

### Environment

<details><pre>
 - Version: 4.6.1
 - Setup with Jenkins+Gitlab
</pre></details>

**Comment by krusche** [comment]
@schultek and @fde312 are currently working on a solution to this problem
