### ISSUE TITLE
Removing and adding user to group triggers password reset

### ISSUE THREAD

**Issue by axel1200** [ls1intum/Artemis#2233]
### Describe the bug
Removing and adding a user to the group triggers password reset even though this makes little sense. UserService:903

GitLab then issues an email to the user that his password was changed. This might look really strange to a user, why was his GitLab password changed.

#### Expected behavior
The user is updated without password reset unless Artemis password changed...

**Comment by krusche** [comment]
This is a well known issue in Gitlab. Updating a user (including the password) over the REST API automatically issues this and there seems no way to prevent this.
We could try to avoid that when the password has not changed, e.g. when the user is only added to or removed from a group, but this might not solve all issues (e.g. when the user changes the password in Artemis in case this is allowed)
Best would be, if we could deactivate that users change their password within Gitlab, but up to now, we did not find a way how to do that. Otherwise, it could also happen that the Artemis and Gitlab password diverge, which might be ok for most users, but which also might lead to issues for some (especially novice) users.

**Comment by axel1200** [comment]
Well, I think the email is fine if the user changes his password on Artemis, and then he receives a mail that his GitLab Password was changed. The user will probably understand what is going on.

But today I received an "admin changed your password email" after somebody added me to a course/group. I did not know about it and hence was really confused about who changed by password or why Artemis. When a ask my colleague he told me he added me to a course and I checked the code why Artemis would change my password.

I think at least not resetting the password after adding/removing of a group would be an improvement over the current situation. Also makes little sense to reset the password on that occasion right?

**Comment by axel1200** [comment]
I can provide the PR for this is wanted

**Comment by krusche** [comment]
Yes, I fully agree, in this case it does not make much sense, in particular if gitlab sends such emails (which it does not in our test instance).

The code in Artemis does not really reset the password, it actually updates the user object, which automatically triggers a password reset (even for unchanged passwords) in gitlab. The method which is responsible for this, already offers a boolean flag `shouldSynchronizePassword` in `GitLabUserManagementService:69`, so this should be easy to fix.
We would appreciate a PR. Thanks!

**Comment by krusche** [comment]
By the way: are you evaluating Artemis for the use in the University of Bonn? Or are you already using it in a real course? ;-)

**Comment by axel1200** [comment]
Kind of evaluated and we wanna use it though the course has not yet started (6. November). Creating exercises now. Of course, we might need to cancel if I discover major issues.

**Comment by sleiss** [comment]
> Yes, I fully agree, in this case it does not make much sense, in particular if gitlab sends such emails (which it does not in our test instance).
@krusche I'm actually not sure if we set up SMTP for our gitlab instance, so that might be why we don't receive these mails.

**Comment by krusche** [comment]
> > Yes, I fully agree, in this case it does not make much sense, in particular if gitlab sends such emails (which it does not in our test instance).
> 
> @krusche I'm actually not sure if we set up SMTP for our gitlab instance, so that might be why we don't receive these mails.

Yes, I think this is not mentioned in the docs. We should be able to prevent the mentioned issue with some small changes

**Comment by axel1200** [comment]
https://forum.gitlab.com/t/managing-git-lab-users-from-external-system/44202 asked on GitLab Forum

**Comment by krusche** [comment]
Solved in #2248
