### ISSUE TITLE
Code editor has white border when loaded the first time

### ISSUE THREAD

**Issue by MaisiKoleni** [ls1intum/Artemis#2235]
### Describe the bug

White margin around the code editor when loading it for the first time in the assessment view.

#### To Reproduce

1. New Java programming exercise without SCA with online editor
2. Participate
3. Over the tutor course dashboard, assess the submission, and view a .java file in the editor. You should see a white border/margin that disappears if you switch the files or reload.
4. _This might only work the first time / some time after, I cannot reproduce it every time but now came across it for the second time._

#### Screenshots

![image](https://user-images.githubusercontent.com/11130248/96507428-6fae1100-1259-11eb-9839-61a134e06975.png)

### Environment

<details><pre>
 - OS: Windows 10
 - Browser Vivaldi (Chromium)
</pre></details>

#### Output in Web Console

<pre>
[DOM] Found 2 elements with non-unique id #file-upload: (More info: https://goo.gl/9p2vKq) 
  <input id=​"file-upload" type=​"file" accept=​"image/​*" class=​"markdown-editor__file-input ng-star-inserted" multiple>​ 
  <input id=​"file-upload" type=​"file" accept=​"image/​*" class=​"markdown-editor__file-input ng-star-inserted" multiple>​
Failed to load resource: the server responded with a status of 400 (/api/programming-exercise/4273/static-code-analysis-categories:1)
</pre>

**Comment by krusche** [comment]
I cannot reproduce the issue any more
