### ISSUE TITLE
Back button on bookmarked exercise returns to about:blank

### ISSUE THREAD

**Issue by nutatuna** [ls1intum/Artemis#2251]
To reproduce:

1. Bookmark a random exercise: https://artemis.ase.in.tum.de/#/courses/39/exercises/710
2. Open a new tab. Go to the bookmark.
2. Click on the back button next to the exercise name (In this case Hello World Java).
3. About:blank page is opened. It should return to current course page.

I am using the latest Chrome (86.0) on Windows.

**Comment by krusche** [comment]
we will soon get rid of all back buttons to avoid such issues and instead use breadcrumbs
