### ISSUE TITLE
Complaint progress bar on exercise dashboard always full

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#2282]
### Describe the bug
On the general Assessment Dashboard the progress bar is shown correctly however if you enter the exercise specific dashboard it's always full.

#### To Reproduce
Prerequesites: Exercise with open complaints
1. Go to the Assessement dashboard
2. Check the complaint progress bar
3. Enter the exercise
4. See that the complaint progress bar is full

#### Expected behavior
The complaint progress bar matches the correct value

#### Screenshots
Shows the faulty bar at the top and the open complaints at the bottom
[![Screenshot from Gyazo](https://gyazo.com/77a5d3591f95ee31499adea9ff6d126b/raw)](https://gyazo.com/77a5d3591f95ee31499adea9ff6d126b)
Shows the correct one on the dashboard overview
[![Screenshot from Gyazo](https://gyazo.com/b152ed587e4e24da5ace80f279e15087/raw)](https://gyazo.com/b152ed587e4e24da5ace80f279e15087)

### Environment

<details><pre>
 - OS: Windows 10
 - Browser: Chrome v86.0.4240.111
</pre></details>

#### Additional context
Make sure that the issue doesn't occure on the original assessment as well.

**Comment by jpbernius** [comment]
We noticed this for the EIST repeat GOE.

**Comment by fde312** [comment]
Probably a duplicate of #2124?

**Comment by julian-christl** [comment]
Indeed, my bad
