### ISSUE TITLE
Automatically clear old repositories from repos folder.

### ISSUE THREAD

**Issue by sleiss** [ls1intum/Artemis#2286]
### Is your feature request related to a problem?
Copying the `repos` folder (e.g. when moving from one VM to another) takes very long because of all the small files within the `.git` folder.
This is quite frustrating (cc @Mtze).

### Describe the solution you'd like
Clear old repositories (e.g. when the exercise is over), we can always check the repository out from the VCS e.g. in case the students wants to practice.

### Describe alternatives you've considered
Add a button to clear all old repositories from all exercises.

**Comment by krusche** [comment]
I think this should be part of the `AutomaticBuildPlanCleanupService` which we should rename into `AutomaticCleanupService`
I would propose that we delete all student repos on the Artemis Server, **not in the VCS system**, (except template, solution and tests) 4 weeks (might be configurable in the yml file) after the last exercise date (`due_date` or `build_and_test_student_submissions_after_due_date` or `assessment_due_date`).

After 4 weeks, those should not be needed any more

`template`, `solution` and `tests` repos on the Artemis Server, **not in the VCS system**, should only be deleted 4 weeks after the corresponding course has ended. Then we assume that they are not needed any more.
