### ISSUE TITLE
Build plan links not redirecting correctly when opened in new tab

### ISSUE THREAD

**Issue by ndricimrr** [ls1intum/Artemis#2303]
### Describe the bug

The build plan anchors/links are not linking to bamboo correctly when opened in a new tab. Instead it redirects to the homepage: `https://artemis.ase.in.tum.de/`

#### To Reproduce

1. Go to **HomePage**
2. Click on **Course Management**
3. Click on **Exercises** 
4. At the shown table Hover on the _Build plan_ column over the **Template** or **Solution** links and look at the shown link at the bottom of the screen.
5. Alternatively right click & Open the link in new tab 

or 

1. Go to **HomePage**
2. Click on **Course Management**
3. Click on **Exercises** 
4. Open one exercise
5. Scroll down to the **Template Build Plan Id** and **Solution Build Plan Id**
6. Right Click & Open Link in New Tab (or middle mouse click) or Hover over the link to see the href link at the bottom of the screen

#### Expected behavior

It should redirect to bamboo instead when opened in a new tab.

#### Screenshots

![issue1](https://user-images.githubusercontent.com/18335489/97740481-a994d800-1ae1-11eb-9426-14c6843bf8ab.PNG)
![issue2](https://user-images.githubusercontent.com/18335489/97740483-aa2d6e80-1ae1-11eb-9e66-b67af88b0308.png)

### Environment

<details><pre>
 - OS: Windows 10
 - Browser A: Chrome
 - Version A : Version 86.0.4240.111 (Official Build) (64-bit)
 - Browser B: Firefox
 - Version B : Version 81.0  (64-bit)
</pre></details>

#### Additional context

-Persists even after logout-login, clearing cache or Force Refresh.

#### Output in Web Console

<details><pre>
  No output in Console
</pre></details>

**Comment by krusche** [comment]
For me, this is working correctly and I can't reproduce your behavior. Do you use any browser add-ons that could lead to such issues?

**Comment by ndricimrr** [comment]
@krusche  Direct clicking on the Links works without any issues for me as well, but it seems that there's no **href** attached to the anchor tag which should enable possibly copying the link or a right click. I tried on an Android phone and also asked another student to try it and got the same result. Same with Microsoft Edge and  Firefox where I'm not using any add-ons. 
![GIF-201101_230739](https://user-images.githubusercontent.com/18335489/97817110-a09b3680-1c9a-11eb-92e9-c117f98dc0f1.gif)

I would assume that the anchor tag has on **onClick** handler somewhere but no href defined.

**Comment by ndricimrr** [comment]
From what I could find out there seems to be proper **href**'s defined for the links in the other columns [here](https://github.com/ls1intum/Artemis/blob/develop/src/main/webapp/app/exercises/programming/manage/programming-exercise.component.html#L90), [here](https://github.com/ls1intum/Artemis/blob/develop/src/main/webapp/app/exercises/programming/manage/programming-exercise.component.html#L110) and [here](https://github.com/ls1intum/Artemis/blob/develop/src/main/webapp/app/exercises/programming/manage/programming-exercise.component.html#L130) but no **href** links defined for the buildPlan links [here](https://github.com/ls1intum/Artemis/blob/develop/src/main/webapp/app/exercises/programming/manage/programming-exercise.component.html#L149) and [here](https://github.com/ls1intum/Artemis/blob/develop/src/main/webapp/app/exercises/programming/manage/programming-exercise.component.html#L162) .


(I also would not consider this a major issue other then a small User Experience fix 😃. Usually clicking on links is a gamble since as a user you can only guess whether the link is going to be opened in a new tab upon click or replace the current tab, unless there is [an indication](https://ux.stackexchange.com/a/2502) of it being an external link. This may not be so relevant here but it's very much the case when you've written a very long text in a text field (potentially an online exam) and mistakenly click on a link which replaces the whole page and all the progress of many hours is lost 😅 )
