### ISSUE TITLE
No participations shown for programming exercise errors in console

### ISSUE THREAD

**Issue by axel1200** [ls1intum/Artemis#2318]
### Describe the bug
No participations shown for programming exercise

#### To Reproduce

Open participations 

#### Screenshots
![Screenshot from 2020-11-03 10-06-49](https://user-images.githubusercontent.com/19996713/97966593-5316ea80-1dbc-11eb-9adf-8cae19d9f33c.png)

### Environment

<details><pre>
 - OS: Linux
 - Browser Chrome und Firefox
 - Version neuste
</pre></details>

#### Additional context
We can grant access to our Artemis if needed.

#### Output in Web Console
[alpro.besec.uni-bonn.de-1604394712135.log](https://github.com/ls1intum/Artemis/files/5480261/alpro.besec.uni-bonn.de-1604394712135.log)

**Comment by axel1200** [comment]
Version based on commit 618309b7d16f9d765dfbf2d8767bcfb230b3b53b

**Comment by axel1200** [comment]
\begin{frame}{Ausgabe Reporting Modul}
\begin{figure}
    \centering
    \includegraphics[width=\linewidth]{cuckoo screenshots/STIX Beispiel.png}
    \caption{Ein Beispielhaftes STIX Objekt.}
    \label{fig:docker_cgroup_example}
\end{figure}
\end{frame}

**Comment by axel1200** [comment]
![Screenshot from 2020-11-03 10-44-42](https://user-images.githubusercontent.com/19996713/97970306-9fb0f480-1dc1-11eb-9d85-cb8d35ebb23c.png)

**Comment by axel1200** [comment]
33abf090667545c6eea07f586045710880af9b5a from @Waldhauser might have broken that changes this line on 20.10.2020

**Comment by axel1200** [comment]
![Screenshot from 2020-11-03 11-00-34](https://user-images.githubusercontent.com/19996713/97971770-d4be4680-1dc3-11eb-976f-85917ff994c1.png)
my guess ... not null safe

**Comment by axel1200** [comment]
I entered fake date for fun now and it does not solve the issue

**Comment by axel1200** [comment]
oh maybe because there are multiple nulls

**Comment by axel1200** [comment]
```
value?vlaue.format(...):''
```
That would probably do

**Comment by stefanwaldhauser** [comment]
@axel1200 Thank you for noticing this. I fixed it as you suggested in the PR https://github.com/ls1intum/Artemis/pull/2332
