### ISSUE TITLE
Option to navigate back after submitting a file

### ISSUE THREAD

**Issue by marvinbeckert** [ls1intum/Artemis#2320]
###  Problem
After uploading/submitting a file there is no "easy" way to navigate back or navigate to the next exercise which is break in the workflow when going through multiple exercises.

### Possible solution
A simple button on this screen would be nice

**Comment by krusche** [comment]
we intentionally do not provide back buttons and are currently in the process of removing all back buttons, because this functionality is already offered by the browser.
Instead we will implement breadcrumb navigation.
