### ISSUE TITLE
Bug: "Manage Hints" button doesn't work

### ISSUE THREAD

**Issue by airelawaleria** [ls1intum/Artemis#2337]
### Describe the bug

Logged as an instructor, the "Manage Hints" button in the programming exercise View does not perform any behavior. Therefore, hints cannot be created/managed.

#### To Reproduce

0. Pre-conditions: 
  0.0 Loggind in as instructor
  0.1 Programming exercise created with code editor
  0.2 Solution template succeded
1. Go to Course Management -> Exercises
2. Click on the programming exercise (View page should open)
3. Click on "Manage Hints" button
4. No behavior/no error messages/no changes

#### Expected behavior

A window should be opened with "Create a new hint" button.

#### Screenshots

![Screenshot 2020-11-04 155507](https://user-images.githubusercontent.com/64631786/98126682-28a95800-1eb6-11eb-8877-d93b06f06fef.png)

![ezgif com-gif-maker](https://user-images.githubusercontent.com/64631786/98127497-111e9f00-1eb7-11eb-94d5-37997d005a5c.gif)

### Environment

<details><pre>
 - OS: Windows 10 Pro
 - Browser: Chrome, Microsoft Edge
</pre></details>

#### Additional context

Link to TestQuality: https://ls1intum.testquality.com/project/10165/plan/17385/run/142723/result/2150214
Seemed to be an issue for the release 4.0.4

#### Output in Web Console

<details><pre>
 No output
</pre></details>

**Comment by nutatuna** [comment]
I am not able to reproduce the behavior, is this still a problem in the current version?

**Comment by airelawaleria** [comment]
Yes, it is still the issue, at least I still observe no behavior. When you clicked on "Manage Hints", was a new window with "Create a hint" functionality opened?

**Comment by nutatuna** [comment]
Yes, I'm also using Chrome. I will take a closer look at it tomorrow.

**Comment by krusche** [comment]
It works again

**Comment by krusche** [comment]
This issue was recently fixed.
