### ISSUE TITLE
Tutor Assessment Tutorial does not show up on test server

### ISSUE THREAD

**Issue by LudwigWeide** [ls1intum/Artemis#2338]
### Describe the bug
The Tutor Assessment Tutorial does not show up on test server does not show up on the test servers as intended by test case
https://ls1intum.testquality.com/project/10165/plan/17385/test/238284
The Precondition was set up correctly, but the option for the "Restart Tutorial" in the drop down menu was not there.

#### To Reproduce
1. Go to any test server (i.e.: https://vmbruegge60.in.tum.de/#/courses)
2. Log in with a instructor Profile.
3. Set up preconditions as intended in https://ls1intum.testquality.com/project/10165/plan/17385/test/238284
4. Log in as tutor
5. Click on "Course Management"
6. "Restart Tutorial" is missing

#### Expected behavior
There should be a "Restart Tutorial" button to start the Tutor Assessment Tutorial Guide.

#### Screenshots
![Bug_003](https://user-images.githubusercontent.com/52135815/98133225-a0c74c00-1ebd-11eb-98a6-05ccbf2fa536.PNG)

### Environment
<details><pre>
 - OS: Windows
 - Browser: Firefox, Opera
 - Version: 81.0.2 (Firefox), 72.0.3815.186 (Opera)
</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by krusche** [comment]
I guess, it's simply not configured on the test servers. Can you also test this on the production server?
