### ISSUE TITLE
Tutors can see the "set visible" and the "start now" button

### ISSUE THREAD

**Issue by marvinchimeka** [ls1intum/Artemis#2340]
### Describe the bug

Logged as a Tutor you could see the set visible button and the start now button of a quiz exercise.

#### To Reproduce

0. Preconditions: 
0.1 You created a quiz exercise according to TC207. This quiz should be "hidden"
0.2 You have 1 student, 1 tutor and 1 instructor account at hand
1. Go ' As instructor and tutor, navigate to the exercise section in course management of your respective test course

2. Under "Quiz Exercises", click "Set Visible" 

4. See error: 
Instructors as well as tutor could see the "set Visible" and the "start now" button. 

#### Expected behavior

 For instructor: The button should have changed to "Start Now" and the quiz is set visible.
For tutor: The "Set Visible" Button should not be present. 

#### Screenshots

Registered with the Artemis_test_user_7 = Tutor Tests Account

![instructor and tutor 5](https://user-images.githubusercontent.com/73886900/98171999-e94c2d00-1ef0-11eb-9dff-9581376176ad.jpg)

![instructor and tutor 6](https://user-images.githubusercontent.com/73886900/98172037-f49f5880-1ef0-11eb-8ce6-5769fd13897b.jpg)

### Environment

<details><pre>
</pre></details>

-IOS Safari

#### Additional context

Link to Testquality:
https://ls1intum.testquality.com/project/10165/plan/17385/run/142723/result/2150289

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by krusche** [comment]
That's ok, they should have this possibility!
