### ISSUE TITLE
Downloaded .zip with repositories from Scores is empty

### ISSUE THREAD

**Issue by airelawaleria** [ls1intum/Artemis#2342]
### Describe the bug

When downloading the repositories for Scores, the .zip file is empty and the contents cannot be extracted.

#### To Reproduce

Pre-Conditions:
  Existing programming exercises with at least 2 submissions.
1. Go to 'Scores'
2. Click on 'Download repos'
3. Open the downloaded file / Try to extract the contents

#### Expected behavior

The downloaded .zip file should contain multiple (in this case) 2 zipped repositories of the submissions.

#### Screenshots

![image](https://user-images.githubusercontent.com/64631786/98230525-8e035480-1f5b-11eb-8e58-54f9353b8ad0.png)

### Environment

<details><pre>
 - OS: Windows 10 Pro
 - Browser: Chrome, Microsoft Edge
</pre></details>

#### Additional context

Link to TestQuality: https://ls1intum.testquality.com/project/10165/plan/17385/run/142723/result/2150247
Was also an issue for Release 4.0.4

Possible solution: 7zip can handle this problem

**Comment by krusche** [comment]
Is this only an issue on Windows? Probably this is related to the way how the server creates the zip file (on a Unix based system). Not sure if we can even fix this easily.

Can you please research possible solutions to this problem?

**Comment by krusche** [comment]
might be related to https://stackoverflow.com/a/29871623
This means we could fix this rather easily by using relative file paths instead of absolute ones (which apparently cannot be handled by windows)

**Comment by airelawaleria** [comment]
I tested it on Mac os - and the files cannot be downloaded at all: Artemis shows Internal server error.
On Windows works fine with 7zip application.

**Comment by airelawaleria** [comment]
When I unzip the file with 7zip, I get the following path: "\\Downloads\il2021test-T00E01-1604479925630\**mnt\storage**\repos-download".  Probably the problem lies indeed in the way the file is created on unix.

**Comment by krusche** [comment]
I think this issue has been fixed. Feel free to reopen it if you still experience it
