### ISSUE TITLE
Add option to specify an end date to a lecture attachment

### ISSUE THREAD

**Issue by JohannesWeiss** [ls1intum/Artemis#2343]
### Is your feature request related to a problem?
There is currently no way to set an end date to an attachment for a lecture, just a release date. This feature may be useful for some scenarios, for example files that may only be downloaded for the duration of a lecture or copyrighted content, which needs to be removed at a given point in time.

### Describe the solution you'd like
Another input field during creation of a lecture attachment for an end date, after which the attachment becomes invisible (or optionally deleted). The exact behaviour may be specified with a checkbox (e.g. "Delete after the end date")

### Describe alternatives you've considered
Manually removing the attachments is possible at a given point in time, but may not be optimal with regards to the user experience for the instructor.

### Additional context
![image](https://user-images.githubusercontent.com/37304775/98233596-92ca0780-1f5f-11eb-931d-4f74ae347851.png)
Current situation could be extended with the end date.

**Comment by ge65cer** [comment]
I don't see a real use case here, once you release some material it is out there. If it would be copyrighted, one might consider not providing it as an attachment at all.
