### ISSUE TITLE
Bug: Programming Exercise Submission - Clone Repo (Late)

### ISSUE THREAD

**Issue by marvinchimeka** [ls1intum/Artemis#2347]
### Describe the bug

When you change a file (be sure that the code will compile) and push to the remote after the submission deadline is passed . It suppose to be updated to "x of n passed NOT GRADED" but the "No graded result" info is still there. The only thing that gets updated are the ticks in the exercise details.
#### To Reproduce

Preconditions:

0.1 Logged in as a student.
0.2 An exercise was created by an instructor. Submission due date is passed.
1. Go to Click on "Start Exercise".
2. You must see "No Graded Result" on top right.
3. Click on Clone Repository. Following should pop-up:
4. Change a file (be sure that the code will compile) and push to the remote. Wait until building and testing is completed.

#### Expected behavior

You should see the feedback in the form: "x of n passed NOT GRADED".
#### Screenshots

![Bildschirmfoto 2020-11-04 um 22 07 45](https://user-images.githubusercontent.com/73886900/98284969-2ae8e080-1fa2-11eb-9658-9ba425a0cb78.png)

### Environment

<details><pre>
</pre></details>

#### Additional context

https://ls1intum.testquality.com/project/10165/plan/17385/run/142723/result/2150410.

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by krusche** [comment]
The feedback is only shown in the result history at the bottom
