### ISSUE TITLE
[GitLab]Artemis fails to unprotect branch

### ISSUE THREAD

**Issue by axel1200** [ls1intum/Artemis#2349]
### Describe the bug
User can not push because branch is protected.
Log says:
```
Could not unprotectBranch branch (but will try to protect it) due to the following reason: Could not unprotect branch master for repository ALPROSTRINGCON/alprostringcon-xxx
``` 

#### To Reproduce
Unknown. I suspect happens on much Load.

- [x] Fix Exception with real reason is swallowed

**Comment by axel1200** [comment]
I have a pretty strong feeling that it is due to a race condition. 

Creating a fork is asynchronous https://docs.gitlab.com/ce/api/projects.html#fork-project and unprotecting the branch is the next rest call to Git lab after the creation of the fork. So that would kind of make sense. Also the Exception cluster around prime time. Which would make sense, because then fork creation probably take longer. To be 100% sure what the issue is a need to have it happen again after I deploy the change that make it actually log the Exception. Or I just implement the fix and find out it works that would probably also support my thesis.

**Comment by axel1200** [comment]
Seems suggestion is not working, today I got one new case:
```
artemis                    | 2020-11-10 09:13:18.031 ERROR 1 --- [ artemis-task-1] d.t.i.w.a.s.c.gitlab.GitLabService       : Could not protect branch (but will s
till continue) due to the following reason:                                                                                                                       
artemis                    |                                                                                                                                      
artemis                    | de.tum.in.www1.artemis.service.connectors.gitlab.GitLabException: Unable to protect branch master for repository https://s6vikaut@gi$
lab.christiantiefenau.de/ALPROTUTCALCULATOR/alprotutcalculator-xxx.git                                                                                       
artemis                    |    at de.tum.in.www1.artemis.service.connectors.gitlab.GitLabService.protectBranch(GitLabService.java:173)                           
artemis                    |    at de.tum.in.www1.artemis.service.connectors.gitlab.GitLabService.lambda$configureRepository$0(GitLabService.java:118)            
artemis                    |    at io.github.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.$
ava:78)                                                                                                                                                           
artemis                    |    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)                                      
artemis                    |    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)                                      
artemis                    |    at java.base/java.lang.Thread.run(Thread.java:832)                                                                                
artemis                    | Caused by: org.gitlab4j.api.GitLabApiException: Protected branch 'master' already exists                                             
artemis                    |    at org.gitlab4j.api.AbstractApi.validate(AbstractApi.java:633)                                                                    
artemis                    |    at org.gitlab4j.api.AbstractApi.post(AbstractApi.java:341)                                                                        
artemis                    |    at org.gitlab4j.api.ProtectedBranchesApi.protectBranch(ProtectedBranchesApi.java:165)                                             
artemis                    |    at org.gitlab4j.api.ProtectedBranchesApi.protectBranch(ProtectedBranchesApi.java:139)                                             
artemis                    |    at de.tum.in.www1.artemis.service.connectors.gitlab.GitLabService.protectBranch(GitLabService.java:170)                           
artemis                    |    ... 5 common frames omitted 
```

**Comment by axel1200** [comment]
Have you got any idea what could cause this?

**Comment by axel1200** [comment]
https://gitlab.com/gitlab-org/gitlab/-/issues/280805

**Comment by axel1200** [comment]
Well I am no trying to simply delay the protection thing by 10 seconds. So I just use a ThreadPoolTaskScheduler to do it and I coded in a second try if unprotecting or protecting fails. Let's see if that helps.

**Comment by axel1200** [comment]
> Well I am now trying to simply delay the protection thing by 10 seconds. So I just use a ThreadPoolTaskScheduler to do it and I coded in a second try if unprotecting or protecting fails. Let's see if that helps.

Gonna deploy this today and see if simply delaying the thing helps. Probably can tell if it does next week after I monitor if this Errors keep happening.

**Comment by axel1200** [comment]
Gitlab maintainer answered that the call the make is supposed to be DELETE instead of a PUT to unprotect a Branch

**Comment by axel1200** [comment]
Gotta check if we do call PUT instead of DELETE

**Comment by axel1200** [comment]
https://github.com/gitlab4j/gitlab4j-api/issues/634

**Comment by axel1200** [comment]
```
        scheduledExecutorService.schedule(() -> {
            //Async because https://github.com/ls1intum/Artemis/issues/2349
            try {
                protectBranch("master", repositoryUrl);
            }
            catch (Exception ex) {
                log.error("Could not protect branch due to the following reason: ", ex);
            }
        },20, TimeUnit.SECONDS);
``` 
I have something like that deployed and since then I get no more complaints

**Comment by axel1200** [comment]
> ```
>         scheduledExecutorService.schedule(() -> {
>             //Async because https://github.com/ls1intum/Artemis/issues/2349
>             try {
>                 protectBranch("master", repositoryUrl);
>             }
>             catch (Exception ex) {
>                 log.error("Could not protect branch due to the following reason: ", ex);
>             }
>         },20, TimeUnit.SECONDS);
> ```
> 
> I have something like that deployed and since then I get no more complaints
Somebody tried a similar thing on develop branch with 10 seconds and without trying again. I removed my hack and took the one from develop. And 1 hour after I deployed the thing from origin/develop and I got a report about it happening after 1 hour. The current hope fix from develop is not working.
Either10 seconds are not enough or the delay is unimportant but trying again in case of an Exception was what fixed it....

**Comment by snowball77** [comment]
Dear all,

we went online with our Artemis today. We have a lot of messages in our log like this:
[2m2020-12-14 11:22:17.789[0;39m [32m INFO[0;39m [35m1[0;39m [2m---[0;39m [2m[nio-8080-exec-8][0;39m [36md.t.i.w.artemis.service.CourseService   [0;39m [2m:[0;39m User permela00 has successfully registered for course PSE WS 20/21
[2m2020-12-14 11:22:17.861[0;39m [32m INFO[0;39m [35m1[0;39m [2m---[0;39m [2m[nio-8080-exec-5][0;39m [36md.t.i.w.artemis.web.rest.CourseResource [0;39m [2m:[0;39m /courses/for-dashboard.done in 9ms for 1 courses with 1 individual exercises and 0 team exercises for user permela00
[2m2020-12-14 11:22:46.939[0;39m [32m INFO[0;39m [35m1[0;39m [2m---[0;39m [2m[nio-8080-exec-2][0;39m [36md.t.i.w.a.s.c.gitlab.GitLabService      [0;39m [2m:[0;39m Try to fork PSEEX6%2Fpseex6-exercise into pseex6-permela00
[2m2020-12-14 11:22:47.583[0;39m [33m WARN[0;39m [35m1[0;39m [2m---[0;39m [2m[nio-8080-exec-2][0;39m [36md.t.i.w.a.s.c.gitlab.GitLabService      [0;39m [2m:[0;39m Could not unprotectBranch branch (but will try to protect it) due to the following reason: 

de.tum.in.www1.artemis.service.connectors.gitlab.GitLabException: Could not unprotect branch master for repository PSEEX6/pseex6-permela00
	at de.tum.in.www1.artemis.service.connectors.gitlab.GitLabService.unprotectBranch(GitLabService.java:168)
	at de.tum.in.www1.artemis.service.connectors.gitlab.GitLabService.protectBranch(GitLabService.java:149)
	at de.tum.in.www1.artemis.service.connectors.gitlab.GitLabService.configureRepository(GitLabService.java:106)
	at de.tum.in.www1.artemis.service.ParticipationService.configureRepository(ParticipationService.java:523)

In case it helps in debugging, I can provide the full log. At the moment, this issue floods the log and if we can help or test anything to resolve it, this would help.

**Comment by snowball77** [comment]
We are running Artemis 4.7.7. If I can move to a patched version to test it, let me know. We will see student registration over the whole of the current week for ~700 students

**Comment by axel1200** [comment]
Yes if the new release comes out, try that @snowball77 there is a delay for the protect call and it uses a different API. It is expected to fix this problem presented here.

**Comment by axel1200** [comment]
Since update no more complains

**Comment by snowball77** [comment]
Our students are all registered now, but I will still deploy it and observe it
