### ISSUE TITLE
Compiler warning compiling Angular locally

### ISSUE THREAD

**Issue by axel1200** [ls1intum/Artemis#2357]
```
ERROR in ./src/main/webapp/app/shared/util/utils.ts
Module Error (from ./node_modules/eslint-loader/dist/cjs.js):

/home/alexander/Idea Projects/Artemis/src/main/webapp/app/shared/util/utils.ts
  59:13  error  == should be === (tslint:triple-equals)  @typescript-eslint/tslint/config

✖ 1 problem (1 error, 0 warnings)
```
Still compiles and works. Did anybody else get this? Or only me

**Comment by FrankeLukas** [comment]
Fwiw, I don't get the same error.

**Comment by krusche** [comment]
We recently updated the settings of the linter as we would like to prefer `undefined` over `null` in the client code.
If you still have `== null` in your code, please change it to `== undefined` which is the logically the same and checks for both, null and undefined.
