### ISSUE TITLE
Test names missing in student view

### ISSUE THREAD

**Issue by kappelmann** [ls1intum/Artemis#2359]
### Describe the bug

When student's check their test results, they cannot see the name of the test case, which makes the feedback pretty much useless. See here 
![image](https://user-images.githubusercontent.com/7101032/98400268-05241000-2064-11eb-9bc8-84d917a75c5f.png)

If an instructor uses the "Scores" view, however, they can see the name. See here 
 
![image](https://user-images.githubusercontent.com/7101032/98400358-271d9280-2064-11eb-810b-82cf37248a87.png)

#### To Reproduce

Submit anything that causes a failing test and check both views.

#### Expected behavior

The test name should be visible for students. Otherwise, they cannot know what parameters made which test case fail.

#### Screenshots

See above

### Environment

<details><pre>
</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by kappelmann** [comment]
I hate pushing people, but as we plan to hand out our first homework today, we would very much appreciate this being prioritised to avoid confused and disappointed students :')

**Comment by FrankeLukas** [comment]
Apparently this was an intentional decision in #2177?
> Students do not see the test case names and have no distinction between automatic and manual Feedback. (All is labeled 'Feedback')

@schultek do you have an idea what can be done here?

**Comment by lukasstevens** [comment]
As a side note: the xml format for the test results also allows a hierarchical structure which looks as follows when printed:
```
Tests Homework 1
  H1.1
    myPair equals sample solution?:                   OK
      +++ OK, passed 250 tests.
    myFst returns first?:                             OK
      +++ OK, passed 250 tests.
    mySnd returns second?:                            OK
      +++ OK, passed 250 tests.
    H1.1d
      prop_myPair accepts correctly encoded pairs?:   OK
        +++ OK, passed 250 tests.
      prop_myPair rejects negative arguments?:        OK
        +++ OK, passed 250 tests.
      prop_myPair rejects incorrectly encoded pairs?: OK
        +++ OK, failed as expected. Falsified (after 1 test and 2 shrinks):
        (*)
        (*)
        (*)
        called: prop_myPair 0 0 1
  Tests H1.2
    equals sample solution for small numbers?:        OK (0.07s)
    equals sample solution for big numbers?:          OK
      +++ OK, passed 1000 tests.
    Testing for extra space characters:               OK
      +++ OK, passed 1000 tests.
    Testing for unknown words:                        OK
      +++ OK, passed 1000 tests.
```
It would be nice if the result view could reflect this hierarchical structure.

**Comment by krusche** [comment]
It was an intended decision to not show test case names to students. The feedback messages produced by the tests should be sufficient for students to understand why their solution is wrong. Please add more details to those messages in case important information is missing. 

Our experience is that test case names often contain technical details or include internal elements that should not be visible to students. We can further discuss whether it can make sense to show test case names in certain situations. An option would be to make this configurable for the instructor.

**Comment by kappelmann** [comment]
Okay I see. What's the motivation behind having technical details in test names that should not be shown to students?

Our test cases usually are called something like "Does x have property y?" and when a test case fails, it prints "x called with parameters a b c returns i but we expected j". I see two options in the current Artemis environment for us:
1. We could duplicate the string "Does x have property y?" in the output of the test case, but that seems very wrong to me (duplicated information).
2. We could change our attitude towards students: we do not tell them what the property is that we are testing and instead just show them the input/output behaviour. Is it pedagogically beneficial if students don't know the property that the tests try to verify and just see the mismatch of input/output? It is more difficult for them, of course, to see what is broken in their code that way, but it is also more realistic. In practice, a buggy program does not tell you what property is broken and you just see the calculations. What is your opinion @krusche and @lukasstevens ?

**Comment by lukasstevens** [comment]
I think the philosophy of not showing the test case names may work with other test frameworks but certainly does not make much sense with QuickCheck. Here, we already explicitly try to give the tests meaningful names. Why would we like to duplicate this information? The duplication gets even worse if you use hierarchical tests because you have to maintain the structure manually instead of letting the code handle it for you. I would definitely be in favor of having an option to show the test case names (this shouldn't be too difficult since it already works for instructors).

**Comment by kappelmann** [comment]
We also just received some complaints by students: they cannot see which test exactly times out:
![image](https://user-images.githubusercontent.com/7101032/98461229-cb115600-21aa-11eb-8872-0bd0985d70f4.png)

For other causes of failure, we (at least) managed to show which function caused a failure, but as for timeouts, I do not know if we can modify the feedback string as our used framework ([Tasty](https://hackage.haskell.org/package/tasty-1.4/docs/Test-Tasty.html#v:mkTimeout)) only allows passing a timeout and seems to ignore other feedback messages in case of killing a test thread.

So we can either 
1. write some code that traverses the produced XML, as Lukas mentioned, and copy the test names to each individual feedback or
2. add an option in Artemis to print test names.

I think 2. is the right thing to do (1. is duplication of information to me). Please let us know if you think this is something you'd support @krusche; for otherwise, Lukas and I need to start implementing option 1.

**Comment by krusche** [comment]
I think information duplication in tests is not that critical, but I can understand that you would like to avoid it.
Please use it as a quick fix until we have implemented a proper solution.

I guess we would need a new option for programming exercises to show the test case names to students. The default would be false, but instructors could activate it. We'll try to implement this as soon as possible.

@kappelmann every help in the implementation is appreciated
