### ISSUE TITLE
Renaming a folder which contains files in the code editor

### ISSUE THREAD

**Issue by sebastiantpeter** [ls1intum/Artemis#2360]
### Is your feature request related to a problem?

Renaming a folder which contains files is time consuming. Currently you would have to recreate all files and copy the file contents.

### Describe the solution you'd like

It should be possible to directly rename a folder which contains files. The files should be in the renamed folder afterwards.

**Comment by schultek** [comment]
Renaming folders is possible, but it is a bit hidden. You have to disable path-compression first, then renaming works normally for folders. 
![Bildschirmvideo-aufnehmen-2020-11-09-um-01 00 07](https://user-images.githubusercontent.com/13920539/98488049-3a2c9000-2227-11eb-9179-d1c9832f07d0.gif)

**Comment by schultek** [comment]
Since this might happen to other students, I created a PR which adds a tooltip to the rename icon when it is disabled. This will hopefully clear things up.
