### ISSUE TITLE
Allow default package when creating exercise

### ISSUE THREAD

**Issue by axel1200** [ls1intum/Artemis#2364]
### Is your feature request related to a problem?
Students do not know what a package is and this is only explained later. Artemis does not allow do use the default package/no package when creating an exercise.

### Describe the solution you'd like
Leaving the package input field empty results in classes being created in the default package.

### Describe alternatives you've considered
Moving them when editing the exercise

**Comment by krusche** [comment]
This would be difficult to implement with our current template generation approach.

Would it be so problematic to use a simple package name, tell them in one sentence that it is a "namespace that organizes a set of related classes and interfaces" and "more details will follow later"?

By the way, you can change the package how you like in the exercise, test and solution repos. It also does not have to correspond to the value used during the generation of the exercise

**Comment by axel1200** [comment]
I know that, I just thought it would save me the work to copy it over and I expected it to be a simple change
