### ISSUE TITLE
Show all lecture units in Lecture overview

### ISSUE THREAD

**Issue by max-ae** [ls1intum/Artemis#2372]
### Describe the solution you'd like
Currently, the lecture overview only shows the amount of attachments.
![Lecture overview](https://user-images.githubusercontent.com/4730112/98539995-814d6c00-228d-11eb-8a21-144f1c7def02.png)

However, with the introduction of lecture modularization, it would be helpful to also show all other lecture units. For example, as lecture slides are not attached as attachments anymore, but as lecture units, the attachment count is not as helpful as before.
Visualization:
![Bildschirmfoto 2020-11-09 um 13 13 39](https://user-images.githubusercontent.com/4730112/98540409-2f591600-228e-11eb-947f-856e93c4aeb7.png)

### Describe alternatives you've considered
Removing the attachment count as it is not helpful anymore for lectures with modularized lecture units.

**Comment by MerlinMehmed** [comment]
I am closing the PR, since the amount of attachment count has been removed in this [PR](https://github.com/ls1intum/Artemis/pull/2907) due to performance issues ([reference](https://github.com/ls1intum/Artemis/pull/2907#issuecomment-787487389)) and that is the alternative solution described.
