### ISSUE TITLE
Provide option to download all files attached to a lecture

### ISSUE THREAD

**Issue by max-ae** [ls1intum/Artemis#2373]
### Describe the solution you'd like
A button to download all attached files of a lecture (Slides, attachments) for example in the .zip format would be helpful to download all lecture material at once without having to go through all attached files.

### Describe alternatives you've considered
Providing an option to download a squashed PDF file of all lecture slide units.

**Comment by ge65cer** [comment]
Related #3385

**Comment by rstief** [comment]
Solved in #3571
