### ISSUE TITLE
Markdown editor code styling button adds additional word

### ISSUE THREAD

**Issue by JohannesWeiss** [ls1intum/Artemis#2390]
### Describe the bug
When editing code in the markdown editor (a modelling exercise in my case) and selecting some text to apply the `code` style the word _language_ gets added before the original text inside the new code part. 

#### To Reproduce

1. Open a markdown editor
2. Write some text
3. Select one or more words from the text
4. Press the _Code_ formatting symbol in the bar on top of the editor
5. Now your word is in a new code section and the word _language_ has been added before it

#### Expected behavior
Just the symbols for the code formatting should appear in this case, not the additional word.
Correct: `My written Text` 
Incorrect:`language My written Text`

#### Screenshots
![output](https://user-images.githubusercontent.com/37304775/99096669-da433a00-25d6-11eb-9cf4-0abc85a6c7c2.gif)

### Environment

<details><pre>
 - OS: macOS 10.15.6
 - Browser: Safari
 - Version: 14.0 (15610.1.28.1.9, 15610)
</pre></details>

#### Additional context
Error occurred with the editor in different exercises

**Comment by lukasstevens** [comment]
It works if you insert a line break after language. I suspect that this is the intended behavior for multiline code blocks.
