### ISSUE TITLE
File Upload Exercise for Exams

### ISSUE THREAD

**Issue by FlorianStang** [ls1intum/Artemis#2391]
### Is your feature request related to a problem?

TestQuality has two Tests ([TC474](https://ls1intum.testquality.com/project/10165/plan/17385/test/fullscreen/243822) and [TC480](https://ls1intum.testquality.com/project/10165/plan/17385/test/fullscreen/243828)) which describe the steps to add and edit File Upload Exercises to/of exams,
but at the moment File Exercises cannot be added to Exercise Groups 

### Describe the solution you'd like

Add the File Exercise Group as a possible exam exercise type 

### Describe alternatives you've considered
remove the TestQuality Tests (if present behavior is intended)

**Comment by krusche** [comment]
We currently do not support file upload exercises. We might support them in the future. Please simply remove the related test quality tests. Thank you
