### ISSUE TITLE
No build log shown on "Build Failed" 

### ISSUE THREAD

**Issue by kappelmann** [ls1intum/Artemis#2392]
### Describe the bug

When I click on `Build Failed` in the `Scores` view of an exercise, it does not show me the failed build log but just that there are no result details available.

#### To Reproduce
Click on `Build Failed` [here](https://artemis.ase.in.tum.de/#/course-management/87/exercises/2180/scores):
![image](https://user-images.githubusercontent.com/7101032/98919763-84379f00-24cf-11eb-933b-b1fd89687ea1.png)
and you will get this:
![image](https://user-images.githubusercontent.com/7101032/98919847-a2050400-24cf-11eb-8dff-cfce8dba52fd.png)

#### Expected behavior

When I click on `Build Failed`, I can see the failed build log data.

**Comment by kappelmann** [comment]
For reference, this came up in #2378

**Comment by sleiss** [comment]
I could reproduce the issue in another exercise now. The server sends build logs to the client but the client (for a yet unknown reason) does not display them.
