### ISSUE TITLE
Students are able to see Lecture before its release date

### ISSUE THREAD

**Issue by JohannesWeiss** [ls1intum/Artemis#2393]
### Describe the bug
Students are able to see lectures with a release date in the future and are able to access them. Relates to the following
[TestCase on TestQuality](https://ls1intum.testquality.com/project/10165/plan/17385/run/142723/result/fullscreen/2150446).

#### To Reproduce
1. Log in as a student
2. Go to a course with a lecture with a start date in the future
3. You can see the future lecture(s) in the lecture tab of that course
4. Accessing the lecture and content is also possible

#### Expected behaviour
A lecture becomes visible and accessible to students only after the start date if that date is in the future. 
Optimally a lecture preview would be shown, but greyed out and not accessible before its release.

#### Screenshots
<img width="948" alt="image" src="https://user-images.githubusercontent.com/37304775/99146835-0f559800-267c-11eb-9833-82593a54f595.png">

### Environment

<details><pre>
 - OS: MacOS
 - Browser: Safari
 - Version 14.0 (15610.1.28.1.9, 15610)
 - Logged in as student 
</pre></details>

**Comment by stefanwaldhauser** [comment]
I think the start date was never intended to be a release date. What is your opinion here @krusche?

**Comment by krusche** [comment]
I agree, start date != release date.
