### ISSUE TITLE
File Upload Exercises in Exams

### ISSUE THREAD

**Issue by philgabr** [ls1intum/Artemis#2404]
### Is your feature request related to a problem?

It is not possible to create **File upload Exercises** in exercise groups for exams.

### Describe the solution you'd like

According to the test [TCR1939](https://ls1intum.testquality.com/project/10165/plan/17385/run/142723/result/fullscreen/2150554) this option (of adding File Upload Exercises in exercise groups) should be available.

For normal course exercises this option is available: 
![image](https://user-images.githubusercontent.com/73602874/99247122-c9790b00-2806-11eb-8b13-653b47275226.png)

The option could just be added here:
![image](https://user-images.githubusercontent.com/73602874/99246726-13adbc80-2806-11eb-8b5a-7f075f9e4dbd.png)

### Describe alternatives you've considered

--

### Additional context

The test case [TCR1939](https://ls1intum.testquality.com/project/10165/plan/17385/run/142723/result/fullscreen/2150554) was deleted (not needed anymore).

**Comment by krusche** [comment]
This is currently not supported.
