### ISSUE TITLE
Copy button for the expected and the actual result

### ISSUE THREAD

**Issue by harcipulyka** [ls1intum/Artemis#2443]
### Is your feature request related to a problem?
Comparing the expected result with the actual result can become quite complicated when the result is long or when the difference is small. For this purpose I, and many others use text comparing software. It would help a lot, if there would be 2 buttons at these cases, with which you could copy the expected or the actual result.

### Describe the solution you'd like
When there is expected != actual error, I would like to have 2 button, one of which would copy the expected result into my clipboard, the other would copy the actual result into my clipboard

### Describe alternatives you've considered
The alternative I have to use, is scrolling through the expected result, finding the last character, copy it, then do the same with the actual result.

The alternative solution for this feature would be an in-built difference highlighter or a button that would open one of these online difference highlighters, and would pass the 2 strings to it. (That way we don't have to do anything)

**Comment by krusche** [comment]
I don't understand your feature request. Which exercise do you refer to? Can you add a screenshot with an example? Is this a student, tutor or instructor feature? We need more details. Feel free to reopen when you have added more details
