### ISSUE TITLE
Custom/No Programming Language option when creating a new programming exercise

### ISSUE THREAD

**Issue by egekorkan** [ls1intum/Artemis#2470]
### Is your feature request related to a problem?

When creating a new programming exercise, I am met with possible programming languages that also come with their own template repository. For a programming exercise with Node.js, I would need to choose Python and then remove everything from the repository for exercise, test and solution. After that, the students still see Python as the language of the exercise which is not correct. 

### Describe the solution you'd like

I would like having an option of no programming language which would create a totally empty repository. Similarly, as a next improvement, it would be nice to input a string for a custom language field that also creates an empty repository. 

### Describe alternatives you've considered

Creating a Node.js language option. However, this would not solve the problem for another language that someone else might want in the future.

**Comment by b-fein** [comment]
The option to select ‘Other’ as programming language exists now.

JavaScript and Typescript exercise templates exist now, too.
