### ISSUE TITLE
course statistics wrong details

### ISSUE THREAD

**Issue by ismail-404** [ls1intum/Artemis#2475]
### Describe the bug
hovering the mouse over the exercise shoes details of the next exercise tests instead of current one //in course statistics

#### To Reproduce

1. Go to course
2. Click on statistics
3. hover mouse an exercise 
4. see details of the following  exercise tests

#### Expected behavior
details of tests in the selected exercise

### Environment

 - OS: win10
 - Browser chrome
 - Version Version 87.0.4280.66
</pre></details>

[photo](https://drive.google.com/file/d/12XWxxLNzPifetlBCFjHhOr8LFZCS9U1e/view?usp=sharing)

**Comment by ge65cer** [comment]
We have re-implemented the graphs using another library, so this issue should be fixed. If you still experience it, feel free to open another issue.
