### ISSUE TITLE
Inconsistent views of programming exercise results

### ISSUE THREAD

**Issue by FrankeLukas** [ls1intum/Artemis#2486]
### Describe the bug
The scores differ between views

#### To Reproduce

1. Create and participate in a programming exercise
2. Add manual feedback
3. View the result from the student's perspective

#### Screenshots
The overview shows **110 of 100**:
![grafik](https://user-images.githubusercontent.com/72132281/100732922-bb61e780-33cd-11eb-9709-fe1cb32137e5.png)
Clicking on it shows **112 of 110** (and **0 of 1**):
![grafik](https://user-images.githubusercontent.com/72132281/100732943-c1f05f00-33cd-11eb-9b34-1f6fa864b420.png)
The manual grading results:
![grafik](https://user-images.githubusercontent.com/72132281/100733047-e64c3b80-33cd-11eb-9ac6-19bf0aebbad5.png)

**Comment by schultek** [comment]
Technically this is not a bug. In the score chart the 'of xxx' means just any points you would have gotten from summing up all the positive feedback (in this case 100 + 12). In the result string the 'of xxx' means of the maximum points of an exercise.

But I can see how this can be confusing. @krusche should I change this?
