### ISSUE TITLE
[Bug] GradingCriterion not saved correctly into the database when importing Programming Exercises

### ISSUE THREAD

**Issue by fde312** [ls1intum/Artemis#2491]
### Describe the bug

Import programming exercise with grading instructions

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/41108487/100894337-ad3ec480-34bc-11eb-9e09-ebd0484af67b.png">

#### Expected behavior

Should import without any error

**Comment by krusche** [comment]
This issue was already fixed!
