### ISSUE TITLE
Advanced Analytics for Instructors using SandDance and Data Query API

### ISSUE THREAD

**Issue by MaisiKoleni** [ls1intum/Artemis#2492]
### Is your feature request related to a problem?

Good exercise design can be developed and improved by analyzing how exercises are rated, corrected and how well test cases work, how exercises compare with each other and so on. This issue suggests using SandDance, which is also available as VS Code extension and a powerful visualization for plain CSVs. This is much more flexible and efficient than trying to implement all sorts of data visualizations manually into Artemis.

### Describe the solution you'd like
Allow instructors of a course to:
1. Select a dataset (that is generated by the server using the DB and sent to the client).
   Could be: 
    - row per exercise
    - row per result [for a set of exercises]
    - row by feedback / test case in case of programming exercises [for a set of ...]
    - SGI usage / distribution
    - ...
2. Select some additional properties; we could send all but that would always be expensive for Network and Client and DB.
   (like LOC, Submission count, automatic & manual result, difference, Model Elements (or count), ...)
3. Being able to explore the data in https://github.com/microsoft/SandDance
   Once the client has the data, no more ReST-calls are needed, unless the instructor wants to change the dataset.
4. Instructors can also download the generated CSV to process it further

### Notes
A very interesting approach would be to realize this with e.g. a GraphQL-API to retrieve the data. This GraphQL API could also be used by programmatic clients (but limited to retrieval first). This would allow instructors to select only needed attributes in a powerful way that also helps to reduce the load on the DB or server. I would then advise to make this an officially supported Artemis API. At least I could imagine this working great, as the Artemis Objects as well as the proposed analytics are very data-centric, and this would allow to be selective, minimalist and still provide the user with all they need. The schema would make it fairly user-friendly as well (as only instructors have access, this should be ok as an option). Some basic and quick calculations could be done on the server side to decide whether a request would be too expensive (or warn the user beforehand). This API could also be decoupled without too much effort from the internal representation of the classes in Artemis/DB, as far as I know. Having an API like that would also reduce the number of calls needed to get the desired data.

**As a side effect, this data export API could offer a file download of the results as well, effectively solving #1034.**

I am happy for more feedback and ideas on this, we had this idea when analyzing data in SandDance retrieved using the browser current client API in PGdP and believe this would be extremely helpful for many other courses as well (looking at the before mentioned issue and some conversations in Slack).

**Comment by MaisiKoleni** [comment]
This would also allow other chairs to build and research systems that don't need to be integrated into Artemis (directly). One could e.g. offer bachelor thesis topics on data mining on Artemis data, or static code analysis without requiring the solution to be an Artemis feature first, which would reduce the scope and the effort needed to supervise students and developers.

Once those systems have proven themselves, they could be integrated in a similar manner as the text clustering already is via a PR.

This lowers the barrier of entry into advanced Artemis work because no proficiency with Artemis code itself is needed.

Furthermore, such an integration could then be done by someone else as bachelor thesis, for example, decoupling Artemis development and feature development/research.

**Comment by krusche** [comment]
out of scope at the moment

**Comment by MaisiKoleni** [comment]
It might be interesting to note that more clients start to appear. Apart from our unmaintained, closed-source Java API I found this: https://github.com/kit-sdq/artemis_client.
