### ISSUE TITLE
[Bug] Empty text field in short answer questions causes an incorrect behavior in the submission review

### ISSUE THREAD

**Issue by airelawaleria** [ls1intum/Artemis#2493]
### Describe the bug

Leaving an empty text field in the exam quiz, causes an error. When reviewing the results as a student after assessment, the page is loaded incorrectly so that the next exercises (after the one containing an empty text field) are not displayed.

#### To Reproduce

1. Create an exam
2. Create a quiz with text input and other exercises comming after the quiz
3. Participate in the exam as a student, leave the text input field empty
4. Assess the student submission
5. As a student, go to your submission
6. Scroll down to the other exercises -> "]" is displayed instead of each exercise

#### Expected behavior
The empty field represented as `undefined` should be handled correctly by the client.
#### Screenshots

![image](https://user-images.githubusercontent.com/64631786/100934483-14756c80-34ef-11eb-93c2-5ee0318d88ea.png)
![image](https://user-images.githubusercontent.com/64631786/100934553-2eaf4a80-34ef-11eb-934f-4f169c2b1eb2.png)

### Environment

<details><pre>
 - Windows, OS
 - Chrome browser
</pre></details>

#### Output in Web Console

<details><pre>

</pre></details>

**Comment by anditurdiu** [comment]
This behavior is specific for short answer questions.
