### ISSUE TITLE
[Bug] Translation not found exception for the example submission for modeling exercise

### ISSUE THREAD

**Issue by marvinchimeka** [ls1intum/Artemis#2494]
### Describe the bug

During assessing the example submission there is an issue if you set one field to 0 Points and add feedback you cannot save your example submission. You get a translation not found exception. 

#### To Reproduce

1. Log in to Artemis.
2. Click on Course Administration 
3. Choose a course
4. Click on Edit on an existing modelling exercise or create one.
5. Click on Create Example Submission 
6. Create an example and save your example
7. Click on show assessment
8. Add 0 Points and a Feedback ( its does not matter in which field e.g attribute:type or method())

#### Expected behavior

You get a translation not found exception.

#### Screenshots

![Bildschirmfoto 2020-12-02 um 22 40 01](https://user-images.githubusercontent.com/73886900/100943553-bf8d2280-34fd-11eb-8d92-542732996123.png)

### Environment

<details><pre>
</pre></details>

-OS: Safari

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by anditurdiu** [comment]
Apart from just the translation issue, @MaisiKoleni mentioned that we want to allow tutors to rate elements with 0 points to just comment their approach, instead of adding and removing points. So, no `.invalidAssessment` error should be thrown in that case.
