### ISSUE TITLE
[Vulnerability] Add character limit for Text Exercises

### ISSUE THREAD

**Issue by SimonEntholzer** [ls1intum/Artemis#2496]
There is no character limit for text submissions, potentially very large submissions can be submitted.
-> Assessing the submission lags a lot.
Overriding the Assessment / processing its complaints potentially crashes the server.

**Comment by anditurdiu** [comment]
Related sentry issues: 

https://sentry.io/organizations/ls1intum/issues/2070246149/?environment=test&project=1440029&query=heap&statsPeriod=14d

https://sentry.io/organizations/ls1intum/issues/2070248544/?environment=test&project=1440029&query=heap&statsPeriod=14d
