### ISSUE TITLE
Wrong percent in Bonusexercise

### ISSUE THREAD

**Issue by JohannesStoehr** [ls1intum/Artemis#2538]
### Describe the bug
An exercise that only gives bonus points has a wrong percentscore.

#### To Reproduce

1. Create a programming exercise that only gives bonus points (in my case 5)
2. Change the weight of test cases. (In my case 20 tests with weight = 0.25, multiplier and bonus points set to 0 and 8 tests with all parameters set to zero)
3. Provide a student submission that passes all weighted tests but not every unweighted test

#### Screenshots
![Bildschirmfoto 2020-12-12 um 15 17 15](https://user-images.githubusercontent.com/38322605/101986238-20022980-3c8d-11eb-8473-1f5fc6f0d5a0.png)

**Comment by FrankeLukas** [comment]
Probably related: #2486

**Comment by schultek** [comment]
Does the result string (before opening the dialog) also say 5% or what does it say?

**Comment by schultek** [comment]
@fde312 and I found the error. There's a false statement in the points calculation on the server. The correct value would be 0% (so the graph is correct :-) )

**Comment by schultek** [comment]
> Probably related: #2486

This is unrelated.

**Comment by JohannesStoehr** [comment]
> Does the result string (before opening the dialog) also say 5% or what does it say?

![Bildschirmfoto 2020-12-12 um 19 20 34](https://user-images.githubusercontent.com/38322605/101991774-26090200-3caf-11eb-97a8-25c2d3e45738.png)
