### ISSUE TITLE
Make download repos for programming exercises more robust

### ISSUE THREAD

**Issue by krusche** [ls1intum/Artemis#2542]
When tutors or instructors download (multiple) repositories of programming exercises, this does not always work correctly.
In case of an exception, it can happen that the Artemis Server does not remove all artifacts making a second download impossible, because the folder and/or the git repository already exists, potentially in a state that cannot be recovered easily.

We should improve this:
1) When a repository is cloned into a subfolder of `repos-download`, we make sure the corresponding folder is empty by removing all entries before the `git clone` operation
2) In case of an exception during the clone operation and any other operation between clone and zip/download, we make sure that the corresponding sub folder is removed securely so that subsequent operations do not produce additional issues

Optional further improvements:
* We tell the user which repositories have been successfully downloaded and which not (e.g. as part of the server response)
* In case of an error, we try to use alternative approaches, e.g. download the zipped repo directly from the Version Control Service (e.g. Bitbucket) in case such an API exists

**Comment by derLalla** [comment]
I have opened a PR for this: #2550
