### ISSUE TITLE
Clicking 'show no exercises with full points' still shows exercises with more than 100 %

### ISSUE THREAD

**Issue by axel1200** [ls1intum/Artemis#2563]
### Describe the bug

![Screenshot from 2020-12-17 22-06-36](https://user-images.githubusercontent.com/19996713/102543836-2856cc00-40b4-11eb-8dc8-571cdb86202d.png)
Does not exclude exercises with more than 100%. Such exercises exist if there are bonus points.

#### To Reproduce
Trivial
Get an exercise you scored bonus points in and you have >100%, try excluding exercises with full points.

**Comment by krusche** [comment]
fixed by PR #2564
