### ISSUE TITLE
Show Spaces at Start of Lines in Quiz Exercises

### ISSUE THREAD

**Issue by ghagerer** [ls1intum/Artemis#2569]
### Describe the bug
When you create a Quiz Exercise of type Short Answer Question with spaces at the start of lines inside of the markdown editor, these spaces are removed in the exercise preview, see [example](https://artemis.ase.in.tum.de/course-management/84/quiz-exercises/2580/preview). This is a problem for fill-in-the-blank coding exercises, as the indentation is removed.

#### To Reproduce

1. Log in as instructor.
2. Click 'Course Management' at the top.
3. Click 'Exercises' of the respective course.
4. Under 'Quiz Exercises' click 'Create Quiz'.
5. Click 'Add Short-Answer Question'.
6. Add a code to the editor, such as the following: 

```
`public class Foo {`
`    public `[-spot 1]`() {}`
`}`
[-option 1] Foo
```
7. Click 'Save'.
8. Go back and click 'Preview Quiz'.

#### Expected behavior
The indentations and the respective spaces at the start of lines are shown in front of `public Foo() {}`.

#### Screenshots
Markdown:
![image](https://user-images.githubusercontent.com/875050/102629166-11af8400-414b-11eb-8136-4485ad26cf05.png)

Preview:
![image](https://user-images.githubusercontent.com/875050/102629103-fd6b8700-414a-11eb-9a85-820d7dd0f3a4.png)

**Comment by jerhard** [comment]
How is the behavior if you use three ticks to start and end a code segment?

**Comment by ghagerer** [comment]
Markdown:
![image](https://user-images.githubusercontent.com/875050/102632893-f72bd980-414f-11eb-8029-a3115ed2e48d.png)

Preview:
![image](https://user-images.githubusercontent.com/875050/102632859-e8ddbd80-414f-11eb-9e22-e12fa4fef5c8.png)

**Comment by jerhard** [comment]
So it seems like the three back ticks don't seem to work here. In other exercise types, they can be used to fomat the section enclosed in them into a monospace font where indentation is retained. 

The behavior that single back ticks do not retain all white spaces occurs in other exercises as well. I assume this is intentional?
So I'd say that the handling of segments within three back ticks in the "short answer quizzes" should be fixed.

**Comment by ghagerer** [comment]
A solution using code blocks with three ticks respectively would be much preferred of course, as it would be much easier to copy and paste your code then. I just thought that the proposed solution from the original post is easier to implement.
