### ISSUE TITLE
Short Answer Quiz: Assign a point for a text field *only* when all characters match

### ISSUE THREAD

**Issue by ghagerer** [ls1intum/Artemis#2570]
### Is your feature request related to a problem?
The feature request is related to fill-in-the-blank code exercises. See also [the blank spaces issue](https://github.com/ls1intum/Artemis/issues/2569).

For code fill-in-the-blank exercises it is at times crucial that all characters of a proposed solution inside of a text box match 100% the actual solution. Especially for variable names it can cause damage to the automatic corrections if you get points for stating wrong variable names, as these are sometimes very short and differ by only one character.

### Describe the solution you'd like
Above the markdown editor for the short answer quiz exercise, you can define the scoring type. Maybe here you can state another option "Exact Match", which yields the desired behaviour.

**Comment by jerhard** [comment]
Do you think that spaces (or even white space characters in general) at the start and end of input string should be trimmed?
A space at the end of an input should maybe not be considered a mistake. What do you think?

**Comment by ghagerer** [comment]
Yes, that makes absolutely sense to me! When only exact matches are accepted, whitespace at the beginning or end of text fields can cause irritations.
