### ISSUE TITLE
ich kann mich nicht registrieren

### ISSUE THREAD

**Issue by Xicheng-Uni-Stuttgart** [ls1intum/Artemis#2574]
### Describe the bug
<bei mir ist immer "Registrierung fehlgeschlagen! Bitte versuche es später nochmal." so ich kann mich nicht bei Artemis registrieren.>

### Environment

<details><pre>
</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by krusche** [comment]
Please talk to your system administrators. Such an issue, without any information about the error, is not helpful at all!
