### ISSUE TITLE
Triggering all participations fails with NPE

### ISSUE THREAD

**Issue by snowball77** [ls1intum/Artemis#2601]
### Describe the bug
After updating the test repo, we wanted to retrigger all submissions (some active, some inactive). However, it fails with lots of NPE.

#### To Reproduce
Go to an exervicse, list all participations, press "trigger all submissions".

#### Expected behavior
All submissions are triggered. Inactive ones become active again.

### Environment

<details><pre>
 - OS: Linux server
 - Browser [e.g. chrome, safari]: firefox
 - Artemis 4.8.4
 - Jenkins/Gitlab
</pre></details>

#### Additional context
I remote debugged the issue. The root cause is that configureBuildPlan in Jenkins Service calls "participation.getProgrammingExercise().getTemplateRepositoryUrl()"

However, in the fetched exercise object the template repository object is a Hibernate proxy. Hence, the getter return null instead of the expected object. I am just now trying to deploy a hotfix that eagerly fetches the template repository object instead of lazy. However, not sure if performance-wise this is the best solution.

**Comment by snowball77** [comment]
It indeed seems that the following patch helps:
diff --git a/src/main/java/de/tum/in/www1/artemis/domain/ProgrammingExercise.java b/src/main/java/de/tum/in/www1/artemis/domain/ProgrammingExercise.java
index 424db09d6..b573ea89d 100644
--- a/src/main/java/de/tum/in/www1/artemis/domain/ProgrammingExercise.java
+++ b/src/main/java/de/tum/in/www1/artemis/domain/ProgrammingExercise.java
@@ -80,12 +80,12 @@ public class ProgrammingExercise extends Exercise {
     @Column(name = "project_key", table = "programming_exercise_details", nullable = false)
     private String projectKey;

-    @OneToOne(cascade = CascadeType.REMOVE, orphanRemoval = true, fetch = FetchType.LAZY)
+    @OneToOne(cascade = CascadeType.REMOVE, orphanRemoval = true, fetch = FetchType.EAGER)
     @JoinColumn(unique = true, name = "template_participation_id")
     @JsonIgnoreProperties("programmingExercise")
     private TemplateProgrammingExerciseParticipation templateParticipation;

-    @OneToOne(cascade = CascadeType.REMOVE, orphanRemoval = true, fetch = FetchType.LAZY)
+    @OneToOne(cascade = CascadeType.REMOVE, orphanRemoval = true, fetch = FetchType.EAGER)
     @JoinColumn(unique = true, name = "solution_participation_id")
     @JsonIgnoreProperties("programmingExercise")
     private SolutionProgrammingExerciseParticipation solutionParticipation;

Also performance is not really different than before...

**Comment by krusche** [comment]
We would prefer a different solution. It should be enough to fetch those values in the corresponding repository methods that are used in the REST resources
