### ISSUE TITLE
Resuming an exercise only works after clicking a second time

### ISSUE THREAD

**Issue by axel1200** [ls1intum/Artemis#2615]
### Describe the bug
I want to resume an exercise.

#### To Reproduce

Happens on our instance for all exercises

#### Expected behavior

That it works :D

#### Screenshots

![Screenshot from 2020-12-30 17-05-29](https://user-images.githubusercontent.com/19996713/103365818-3bf53000-4ac1-11eb-9dcc-2ce125ef1645.png)

### Artemis response 
```
{"type":"https://www.jhipster.tech/problem/problem-with-message","title":"Internal Server Error","status":500,"path":"/api/courses/2/exercises/24/resume-programming-participation","message":"error.http.500"}
```
### Output Artemis log
```
artemis                    | 2020-12-30 16:00:54.676 ERROR 1 --- [io-8080-exec-49] o.z.problem.spring.common.AdviceTraits   : Internal Server Error
artemis                    | 
artemis                    | java.lang.NullPointerException: null
artemis                    | 

```

**Comment by axel1200** [comment]
Pretty bad is that the stacktrace of the Nullpointer is not logged no idea why that is. Ideas how to get the stack trace?

**Comment by axel1200** [comment]
Since we have deadline far in the future now this issue happens a lot, like almost to all users. And most don't try a second time and give up in disappointment

**Comment by axel1200** [comment]
Fixed in newest version

**Comment by krusche** [comment]
> Pretty bad is that the stacktrace of the Nullpointer is not logged no idea why that is. Ideas how to get the stack trace?

This is weird, in our setup the stack trace is shown and we even get some information which value is null.
Which JDK do you use? In JDK15, showing additional information about null values is supported as a new feature and activated by default.
