### ISSUE TITLE
Missing details in Instructor Course Dashboard

### ISSUE THREAD

**Issue by DenizShabani** [ls1intum/Artemis#2643]
### Is your feature request related to a problem?
In the _Information about this course_ box, Assessments shows the late submissions as not being assessed and waiting to be assessed.
In the Pie Chart the late submissions are under _Open Assessments_ which can also create the confusion that some submissions are yet to be reviewed.

### Describe the solution you'd like
For _Assessments_ in the _Information about this course_ box either write it next to the number of assessments as **(_x_ late submissions)** or maybe not mentioned at all.
For the Pie Chart create a new category called **Late Submissions**, so they dont count anymore in the **Open Assesment** category. Another solution could be to create two different Pie Charts, one for the on-time submissions and another for late submissions

![Screenshot 2021-01-05 131341](https://user-images.githubusercontent.com/44246548/103645302-143a1800-4f58-11eb-81a6-baa8698a2983.png)

**Comment by krusche** [comment]
The instructor course dashboard was recently merged into the course assessment dashboard (to avoid duplicated functionality). The course assessment dashboard should include the correct information.
