### ISSUE TITLE
The option "publish build plan" in programming exercises does not work any more

### ISSUE THREAD

**Issue by krusche** [ls1intum/Artemis#2648]
The main idea is, that the student can view the build plan in order to see the build results on the CI system.
If this is the case, students will get a link to their build plan in the exercise details.

This will only work if students have accounts in the CI system, so it is currently limited to the Bamboo setup.

The following changes are needed:
- [ ] Provide read access to the student when configuring the build plan in BambooService
- [ ] Rename the option in the programming exercise creation dialog ("publish" is a bit confusing here) --> "Let students see the build plan"
- [ ] Explain the option in the exercise in the programming exercise creation dialog with a (?)
- [ ] Do not show this option in the Jenkins setup

For now: this option cannot be edited after the programming exercise was created, because Artemis would need to change all existing build plans.

**Comment by Mtze** [comment]
Bitbucket and Bamboo are deprecated - Closing this issue
