### ISSUE TITLE
Unable to track student's build plan

### ISSUE THREAD

**Issue by SisterRiemannLee** [ls1intum/Artemis#2667]
Hello, I'm a tutor for a course and we create a exercise with the url:
https://artemis.ase.in.tum.de/course-management/85/programming-exercises/2710
But something very strange is that, for one student I can see his repo and score, but his status is inactivate, 
![image](https://user-images.githubusercontent.com/53027471/104205258-7a2e1000-542e-11eb-9cd7-c2c46ae7a77f.png)

His build plan should be somewhere:
![image](https://user-images.githubusercontent.com/53027471/104205537-cf6a2180-542e-11eb-86ec-00526bdb9c47.png)

But I don't have access to his build plan, why is this the case?
![image](https://user-images.githubusercontent.com/53027471/104205777-12c49000-542f-11eb-86cd-247f09e86a95.png)

**Comment by krusche** [comment]
Inactive means that the build plan was already cleaned up due to inactivity. You can simply trigger a single build for this student on the participations page, then the build plan will be recreated.
