### ISSUE TITLE
Statistics Feedback mismatch

### ISSUE THREAD

**Issue by SimonK4** [ls1intum/Artemis#2671]
### Describe the bug
When hovering over some programming exercises in the course statistics tab, not the corresponding feedback is shown, but the feedback of another exercise. The title however is shown correctly.
In my case the exercises 9-14 from the bottom (which I have participated in) show the feedback of the 5 exercises at the very bottom, all of which I have not participated in. (So instead of the number of failed and successful tests it shows "You have not participated in [title]".)

#### To Reproduce
1. Go to a Course (I do not know whether it happens on every one)
2. Click on Statistics
3. Hover over the green/red bar of some programming exercises.

#### Expected behavior
I expect to see the actual feedback of the exercise I'm hovering over and the title of which is displayed.

#### Screenshots
The exercise with the wrong feedback.
![1](https://user-images.githubusercontent.com/77293127/104219250-2b887200-543e-11eb-8217-f769819adb03.jpg)
The exercise the feedback actually belongs to.
![2](https://user-images.githubusercontent.com/77293127/104219258-2d523580-543e-11eb-9281-f898f763f532.jpg)
The feedback of the exercise if seen from the exercises and not the statistics tab.
![3](https://user-images.githubusercontent.com/77293127/104219267-2f1bf900-543e-11eb-8d5e-0014fcb5843a.jpg)

### Environment

<details><pre>
 - OS: Windows 10
 - Browser Chrome
 - Version 87.0.4280.141
</pre></details>

**Comment by krusche** [comment]
this issue was fixed
