### ISSUE TITLE
Students cannot push their solution to Gitlab any more

### ISSUE THREAD

**Issue by snowball77** [ls1intum/Artemis#2686]
### Describe the bug

After upgrading to Artemis 4.8.5 students cannot push any more to GitLab breaking the whole Artemis workflow. I digged a bit into it and compared it to the previous behavior. Before, students worked on a master branch in GitLab where both Maintainers and Developers had access to. Now, I see a default main branch which is only accessible by Maintainers which effectively excludes the students.

#### To Reproduce

Start an exercise on GitLab/Jenkins with a recent Artemis. Look into the configuration of the protected branches in GitLab.

#### Expected behavior
Either the old behavior, working with the master branch only. Or as new behavior working with main but then configure access for developers too.

### Environment

Artemis Server 4.8.5, client does not matter here I assume

**Comment by snowball77** [comment]
The additional problem I have now: how do I unprotect several hundereds of repositories in Gitlab? :(

**Comment by snowball77** [comment]
I have just tried to change the settings for the main branch manually for one student in gitlab and then it works.

**Comment by snowball77** [comment]
There might be another possible root cause: GitLab now uses main instead of master for new repositories and the exercise repositories itself use main instead of master

**Comment by krusche** [comment]
I think this is rather an issue with the use of Gitlab. In our (test) instance, the default master branch is still used

**Comment by krusche** [comment]
ist it possible that this is a new configuration setting in Gitlab?

**Comment by krusche** [comment]
We use `master` in several places in the code. What we could do is, make it configurable in the yml file which name for the main branch is used. Then administrator could change it...

**Comment by krusche** [comment]
In Bitbucket, you can specify the default branch
<img width="246" alt="image" src="https://user-images.githubusercontent.com/744067/104614629-b6f54380-5688-11eb-8d5e-0d55efc703db.png">

In our case this is still the one specified in git, which is `master`

**Comment by krusche** [comment]
https://stackoverflow.com/questions/30987216/change-default-branch-in-gitlab

**Comment by snowball77** [comment]
> We use `master` in several places in the code. What we could do is, make it configurable in the yml file which name for the main branch is used. Then administrator could change it...
This might be a good thing in any case. Our case shows that it might be good to have it configurable per exercise as it is hard to implement for a large team of tutors to enforce the name of the "master/main/..." branch. We even had a template repo to clone and it still went wrong...

**Comment by snowball77** [comment]
> In Bitbucket, you can specify the default branch
> <img alt="image" width="246" src="https://user-images.githubusercontent.com/744067/104614629-b6f54380-5688-11eb-8d5e-0d55efc703db.png">
> 
> In our case this is still the one specified in git, which is `master`

By the way: The default branch is not the issue in our case too. It is correctly configured to be the main branch, both for the exercise repo as well as for all the student repos. It is just the branch protection settings which are wrong. I assume this is why Artemis continues to work once we configured the protection correctly.

**Comment by snowball77** [comment]
We now worked around the issue via a script that uses the GitLab REST API to unprotect the main branch every 30min of all student repositories. That way the students are able to continue to work with Artemis without changing anything on their side.

**Comment by snowball77** [comment]
> https://stackoverflow.com/questions/30987216/change-default-branch-in-gitlab

Thank you for the link. I updated our Gitlab to the latest release (13.7.x, as the configuration option was introduced only in GitLab 13.6) and checked the configuration. Everywhere we have master as default branch name of the first branch. So my hypotheses is the tutors of the badly configured exercise used "main" as branch name because of their client or any other strange reason we may not be able to reproduce. I saw many discussions in gitlab issues about the name of the default branch of new projects and they all conclude "main" should be preferred by "master" is established. And the link posted by @krusche is what they ended up with: to have it configurable with master still being the system and group-wide default.

My proposal after investigating all this would be to change this issue from bug to feature request. As I wrote above my suggestion is to allow to configure the name of the default branch per exercise and then enforce/check that all three repos (base, solution, test) use that configured name as default branch. What do you think?

**Comment by krusche** [comment]
We can change it into a feature request yes, however theoretically this could be different between the 3 exercises (template, test, solution) in one exercise, so we might need to approach this completely dynamically. I think JGit can get the default branch of a local repository, then we could always use the local branch and would be completely independent of any configuration.

From my experience, you would actually have to manually change it. When you create a repository on Gitlab / Bitbucket, the default branch `master` (or recently `main`) is created automatically. When you simply clone the repo, add content, commit and push the changes, you won't accidentally change this.

We will investigate this in the future. For now, please tell all your tutors to stick with the current default ;-)

**Comment by krusche** [comment]
I opened #2699 to get this implemented
