### ISSUE TITLE
Use the same round method wherever it is needed

### ISSUE THREAD

**Issue by derLalla** [ls1intum/Artemis#2688]
### Is your feature request related to a problem?

Throughout the application we are using several round functions to calculate a score or points. Either it is `Math.round(x/10) * 10` or a separate function `roundToDecimals()`.

### Describe the solution you'd like

We should use one shared function (server and client) which is used every time when a rounded result is needed.

**Comment by ge65cer** [comment]
We now consistently use the helper class `RoundingUtil`.
