### ISSUE TITLE
Stay independent of a concrete default branch in git

### ISSUE THREAD

**Issue by krusche** [ls1intum/Artemis#2699]
Until now, Artemis assumed the default branch in git is master.
Since many different systems are in the process of renaming the default branch from master to main, Artemis should also get independent and rather read the default branch from the git configuration.

Needed changes: replace all places in which `master` is "hard coded" and try to retrieve the default branch from the git configuration.

**Comment by HardikAgrwl** [comment]
Hi I would like to work on this issue. Can you suggest me how should I get started?
