### ISSUE TITLE
Consistent handling of "no submission (to grade) left"

### ISSUE THREAD

**Issue by philgabr** [ls1intum/Artemis#2702]
### Is your feature request related to a problem?

When one submitted the assessment for an exercise there is the possibility to "assess (the) next submission". This is not possible when all other submissions have already been assessed or are currently locked by other tutors/instructors (reasonably). 
This case is handled differently for different types of exercises. For instance for text exercises you have the opportunity to go back to the assessment dashboard while for programming exercises only an error gets displayed.

### Describe the solution you'd like

A consistent handling of this case for all types of exercises would be great. Preferably, this would always be handled like e.g. for the text exercises (button to go back to assessment dashboard is displayed).

### Describe alternatives you've considered

/

### Additional context

_described case with text exercises:_
![image](https://user-images.githubusercontent.com/73602874/104821118-f4e59980-5839-11eb-9e2c-507807c9d839.png)

_described case with programming exercises:_
![image](https://user-images.githubusercontent.com/73602874/104821123-fdd66b00-5839-11eb-97c2-113da5a345c3.png)

**Comment by claujor** [comment]
👍 For Modelling exercises there is also only the warning popping up. Routing back to the Assessment Dashboard would be nice.
![image](https://user-images.githubusercontent.com/59499968/108367496-d1778b00-71f9-11eb-9ac2-b298081d4baa.png)
