### ISSUE TITLE
Students can't test the exercises afterwards

### ISSUE THREAD

**Issue by JohannesStoehr** [ls1intum/Artemis#2732]
### Describe the bug
As far as I'm aware, students should be able to push their changed code and still get feedback in some coding exercises.
The students in the PSE course still can push after the deadline in automatically graded exercises. This creates an empty submission in Artemis. Running the build plan manually on Bamboo also creates an empty assessments. So the student still sees the last automatic assessment before the deadline, even if now more or other tests pass on Bamboo.

Running the tests by triggering the build in Artemis in the submission overview creates a new assessment in Artemis. But this action uses the latest push, even if it was after the deadline. And the score of the student is changed as well by this. But at least the student can also see the new assessment.

![Bildschirmfoto 2021-01-23 um 17 02 30](https://user-images.githubusercontent.com/38322605/105607065-10eabd00-5d9d-11eb-9f43-c9fbb96250f6.png)

#### To Reproduce

1. Create a programming exercise
2. Push a wrong solution before the deadline
3. Push a better solution after the deadline
4. Rerun the tests
5. See error

#### Expected behavior
The student should be able to see results even if he pushes after the deadline or it shouldn't be possible at all.
If pushing after the deadline stays possible, the score of rerunning the tests should not be changed by using a push after the deadline.

### Environment

<details><pre>
 - Artemis: 4.9.1
</pre></details>

**Comment by krusche** [comment]
This issue should be fixed now.
