### ISSUE TITLE
/results-API ignores manual Testruns

### ISSUE THREAD

**Issue by Strohgelaender** [ls1intum/Artemis#2740]
### Describe the bug
Sometimes the automatic tests after the deadline fail at some particular students. In this case the instructors trigger a new manual run at theses students. But the /results-API ignores these new runs and stil shows the old automatic result (if there is no manual result).

#### To Reproduce
1. You need a programming exercise with at least one participation and the test must run automatically after the deadline. 
2. Update the tests and start a manual run of this participation.
3. The /results-API (e.g. used at the Scores-Page) still returns the old automatic result.

This can be best seen at the PGDP-Course, Exercise 2577, ID 2009677. This is also the score seen at the screenshot below.

During the assessment the code editor shows the new result. It seems like students also can't see this new result but this needs additional testing to be confirmed.

#### Expected behavior
A manual rerun of the test updates the returned score.

#### Screenshots
The participation mentioned above:
![grafik](https://user-images.githubusercontent.com/26540346/105640168-d2c4ca80-5e7c-11eb-8301-4b6ba85301de.png)

These 4 / 4 are only the public tests. I don't have a screenshot but I know for sure that the newest result differs from what is seen here.

<details>
<summary>API-Response</summary>

```JSON
"id": 2067317,
"resultString": "4 of 4 passed",
"completionDate": "2020-12-21T08:51:38+01:00",
"successful": true,
"score": 100,
"rated": true,
"hasFeedback": false,
"submission": {
	"submissionExerciseType": "programming",
	"id": 2009677,
	"submitted": true,
	"type": "INSTRUCTOR",
	"submissionDate": "2020-12-21T06:38:49+01:00",
	"commitHash": "b27b938136e6c2cc0b91f820e74b5babc1ec5a18",
	"buildFailed": false,
	"buildArtifact": false,
	"empty": false,
	"durationInMinutes": 4607
}, ...
```
</details>

### Environment
<details><pre>
 - Artemis 4.9.2
 - OS: Windows 10 19042
 - Browser Firefox 84.0.2
</pre></details>

**Comment by krusche** [comment]
Should be fixed with #2696
