### ISSUE TITLE
manual assesment follwed by test retrun leads to visible manual feedback before assesmente due date

### ISSUE THREAD

**Issue by Strohgelaender** [ls1intum/Artemis#2749]
### Describe the bug
Since #2482 manual and test feedback can be merged together. But this leads to visible tutor feedback for the students before the assessment due date if the manual correction is done in front of the test rerun. 

#### To Reproduce
This happened at the PGdP course an can be seen at exercise and 2842, resultID 2295291. This student can now already see his tutor feedback even though the assessment due date is not over yet.

<details>
<summary>API-Response</summary>

```JSON
{
"id": 2295291,
"resultString": "10 of 10 passed, 12 of 12 points",
"completionDate": "2021-01-26T10:17:41+01:00",
"successful": true,
"score": 100,
"rated": true,
"hasFeedback": true,
"submission": {
	"submissionExerciseType": "programming",
	"id": 2241066,
	"submitted": true,
	"type": "INSTRUCTOR",
	"submissionDate": "2021-01-26T04:13:03+01:00",
	"commitHash": "7648193600c7d8dcf9d4c778e2b785536a33d8d4",
	"buildFailed": false,
	"buildArtifact": false,
	"empty": false,
	"durationInMinutes": 9293
},
"participation": {
	"type": "programming",
	"id": 602922,
	"initializationState": "INITIALIZED",
	"initializationDate": "2021-01-19T17:19:57+01:00",
	"submissionCount": 4,
	"student": { ... },
	[...]
},
"assessor": { ... },
"assessmentType": "SEMI_AUTOMATIC"
},
```
</details>
Steps to reproduce:

1. Participate at a programming exercise
2. Evaluate this submission
3. Rerun the tests
4. The student can now see the manual feedback

#### Expected behavior
The student can only see the new test result, but not the manual feedback. This will be released after the assessment due date.

### Environment
<details><pre>
 - Artemis 4.9.2
</pre></details>

**Comment by krusche** [comment]
`SEMI_AUTOMATIC` results in programming exercises (with manual assessment) should only be visible after the `assessment_due_date` of the exercise is over (in case it is specified). In case the tutor has not yet saves the assessment, the completion_date is not set (it should be `null`). This should still be the case after merging in new feedback from new builds.

**Comment by derLalla** [comment]
Could you describe in more detail what you did?  I did exactly the mentioned steps but I couldn't see the manual feedback as long as the assessment due date was not over. 
My steps:
1. Participate at a programming exercise
2. Assess this submission
3. Changed the grading of the tests and saved
4. Clicked `Re-evaluate all`
5. Clicked `Trigger all`
6. The student could not see the manual feedback
7. The student could see it after the assessment due date or if the assessment due date was not set.
