### ISSUE TITLE
Bulk Editing of Release Dates of Programming Exercises Removes Categories 

### ISSUE THREAD

**Issue by jerhard** [ls1intum/Artemis#2752]
### Describe the bug
When using the "bulk editing" feature for programming exercises, which can be used to change release dates and deadlines, all categories of the selected programming exercises are lost. 

#### To Reproduce
1. In the instructor overview of all the exercises of one course, select one or several programming exercises via the check mark
2. Click on "Edit selected"
3. Change the dates and click on "Save"
4. If you go to the views of the individual exercises that you selected previously, you will see that the categories are now reset (i.e. there are none)

#### Expected behavior
The categories should not be affected by using the bulk edit feature.

**Comment by krusche** [comment]
@daniels98it can you please fix it? you might need to load the categories eagerly to avoid this issue

**Comment by daniels98it** [comment]
> @daniels98it can you please fix it? you might need to load the categories eagerly to avoid this issue

@krusche Yes, I opened a PR #2770 (which is still missing some client tests) but will be ready for review soon
