### ISSUE TITLE
Feedback for Compilation Error shows Docker Messages

### ISSUE THREAD

**Issue by MaisiKoleni** [ls1intum/Artemis#2758]
In case the docker image is not present on the build agent and needs to be pulled, and the student submission does not compile, we get all Docker messages first: (The actual error is at the very bottom)

![image](https://user-images.githubusercontent.com/11130248/106024010-9fc24700-60c7-11eb-84cb-de265c24f0fe.png)

**Comment by MaisiKoleni** [comment]
It seems that some Docker Logs or similar are always in the logs, however in this case, the feedback fits inside the browser window completely. The example above in the issue is more problematic since it has higher confusion potential. 
![image](https://user-images.githubusercontent.com/11130248/106026315-f7fa4880-60c9-11eb-814a-9c21971eff3e.png)

**Comment by krusche** [comment]
BuildLogEntryService was adapted and includes simple filter mechanisms to prevent such messages
