### ISSUE TITLE
Result before Build After Due Date is not visible

### ISSUE THREAD

**Issue by MaisiKoleni** [ls1intum/Artemis#2759]
The result before the Build After Due Date is not visible as instructor anymore, it only says Result Count 2. It is and was, however, in some cases critical for resolving discussions and issues to see the result that the students got displayed before the Build After Due Date. We need to be able to see all results, be it in the submissions list or a separate list.

Also, in regard to the multiple correction rounds for exams it would be dangerous if instructors cannot see the different assessments and all changes done to them.

![image](https://user-images.githubusercontent.com/11130248/106025049-b026f180-60c8-11eb-9909-7566249ac96c.png)

**Comment by krusche** [comment]
We already talked about showing all results of one submission in this list. In the example above this would look like this and should be easy to implement

![image](https://user-images.githubusercontent.com/744067/106032767-2f202800-60d1-11eb-8b9c-840cf09859f1.png)

Additionally it would be nice to highlight the result that actually counts for the students in the end in some way (could be done in a follow up)
