### ISSUE TITLE
More than 10 assessments can be started and the amount of locks is not correctly displayed

### ISSUE THREAD

**Issue by Stein-Adrian** [ls1intum/Artemis#2760]
### Describe the bug
Usually, a Tutor can only have 10 unfinished assessments per Exercise. This limit does not apply anymore, a Tutor can have more than 10 unfinished assessments right now. Furthermore, the locked assessments are not shown on the "Assessment Dashboard" and cannot be unlocked from there (Assessments can still be unlocked directly by the "Cancel" Option on the Assessment Screen).

#### To Reproduce
1. Start new Assessment (can be repeated more than 10 times)
2. Go to the Assessment Dashboard
3. The "Assessments locked by you:" field will show 0
4. Click on the "Assessments locked by you:" Link
5. Artemis will show "No assessments locked by you!"

#### Expected behavior
I expected that Artemis will prevent me from starting more than 10 (unfinished) assessments, as well as showing me the correct amount of currently locked assessments on the "Assessment Dashboard".

#### Screenshots
More than 10 Assessments:
![MoreThan10Assessments](https://user-images.githubusercontent.com/11130248/106028683-88d22380-60cc-11eb-9327-0f91e59a3c1d.png)

Assessment Dashboard showing 0 locked assessments:
![AssessmentLocks](https://user-images.githubusercontent.com/58308367/106025166-c6cd4880-60c8-11eb-8d4c-bfc5a1212c85.PNG)
![Locks](https://user-images.githubusercontent.com/58308367/106025180-c92fa280-60c8-11eb-82cf-f49e06c2d03c.PNG)

### Environment
<details><pre>
 - OS: Windows 10
 - Browser: Latest Firefox, Latest Google Chrome
 - Version: Artemis 4.9.2
</pre></details>

#### Additional context
Affected Course: 83 (PGdP - Praktikum Grundlagen der Programmierung)
Affected Exercise: 2849 (Funktionscache)

**Comment by MaisiKoleni** [comment]
I can confirm this:
![image](https://user-images.githubusercontent.com/11130248/106036385-9213be00-60d5-11eb-8ef9-2c9df52db733.png)

`TS1; artemis_test_user_7; Chris Test Course, Prog.Exercise PR 2738`
