### ISSUE TITLE
Cannot navigate anywhere when using certain breadcrumbs

### ISSUE THREAD

**Issue by MaisiKoleni** [ls1intum/Artemis#2764]
I cannot get out of `https://artemistest.ase.in.tum.de/course-management/266/programming-exercises/5977/code-editor/236901`
![image](https://user-images.githubusercontent.com/11130248/106033329-f03ea200-60d1-11eb-9134-2c1643a369dc.png)
Webconsole when clicking on any button or breadcrumb:
![image](https://user-images.githubusercontent.com/11130248/106034021-a99d7780-60d2-11eb-9394-32da5f6559ca.png)

How I got there: Continue a Programming Assessment and then click on the number breadcrumb before "assessment". Going back in the browser (here Firefox) does not work.

As instructor this is possible and the problem does not appear, as tutor I get the error.

**Comment by FrankeLukas** [comment]
I just tested the link with `/assessment` appended again, and as a tutor clicking on the number does not have an effect so this is no longer an issue.
