### ISSUE TITLE
cloning repo using ssh shows http url

### ISSUE THREAD

**Issue by RobinMarchart** [ls1intum/Artemis#2776]
When cloning an exercise repository, the `USE SSH` Button does not change the repo url

#### To Reproduce
1. navigate to either course or exercise page
2. click `Clone Repository`
3. click `USE SSH`

#### Expected behavior
A repository link using the ssh protocol is shown

### Environment
<details><pre>
 - OS: Linux
 - Browser Mozilla Firefox 86 & Chromium 88
</pre></details>

**Comment by krusche** [comment]
The bug was introduced by a refactoring of the clone button so that it can be used in other views #2729
I investigated the issue and will prepare a fix

**Comment by krusche** [comment]
fixed in 1cc87f0c
the bugfix will be included in the next release
