### ISSUE TITLE
[Bug] TutorLeaderboardService#getExerciseLeaderboard Internal Server Error

### ISSUE THREAD

**Issue by anditurdiu** [ls1intum/Artemis#2805]
### Describe the bug
When trying to access the exercise assessment dashboard for an exam exercise an Internal Server Error is thrown: 

```
2021-02-02 13:38:33.091 ERROR 20620 --- [nio-8081-exec-7] o.z.problem.spring.common.AdviceTraits   : Internal Server Error
org.springframework.orm.jpa.JpaSystemException: could not extract ResultSet; nested exception is org.hibernate.exception.GenericJDBCException: could not extract ResultSet
```

#### To Reproduce

1. Access an exam with submissions
2. Click on assessments
3. Select an exercise
5. The exercise status also does not load correctly as a result of the above error
![image](https://user-images.githubusercontent.com/15110960/106603497-a71da080-655e-11eb-83ff-1c1d2bee77b0.png)

#### Expected behavior
No console error should be thrown apart from the 404 no submissions without results found

### Environment
 - OS: [Windows 10]
 - Browser [Brave, Chromium: 88.0.4324.96 (Official Build) (64-bit)]
 - Version [1.19.88]
</pre></details>

#### Additional context
I expect this to also be the case for course exercises, but did not try it out.

#### Output in Web Console
![image](https://user-images.githubusercontent.com/15110960/106603318-70478a80-655e-11eb-9b15-af7cdfd97ad7.png)

**Comment by fde312** [comment]
@anditurdiu Yeah, this bug is a general bug right now. #2807 Should fix it :)
