### ISSUE TITLE
Make Jenkins Pipelines Templates more Flexible

### ISSUE THREAD

**Issue by Wallenstein61** [ls1intum/Artemis#2812]
### Is your feature request related to a problem?
In the CodeAbility project we have many instructors that propose specific requirements on Test executions. Currently the Jenkins pipeline definition template in src/main/resources/templates/jenkins/.../JenkinsFile is very unflexible. It only allows replacement of certain dedicated variables. 

However we need more flexible ways to define pipelines, e.g. if-then-else based on exercise variables.

E.g. in freemarker markup
```
pipeline {
        options {
            timeout(time: <#if exercise.difficulty=EASY>${jenkinsTimeout}<#else>${5*jenkinsTimeout}</#if>
        }
...
steps {
<#if exercise.categories.contain('requiresUI')>
            wrap([$class: 'Xvnc', takeScreenshot: false, useXauthority: true]) {
</#if>
                junit ...
<#if exercise.categories.contain('requiresUI')>
        }
</#if>
        }

```
### Describe the solution you'd like
1. We would propose to replace the current static textual variable replacements by more flexible ways of a template generator (e.g. [freemarker](https://freemarker.apache.org/)
2. Provide more flexible ways to provide (Jenkins) templates. I.e. do not freeze it in the source code, but e.g. load it from a configurable URL/Filesystem/... .

### Describe alternatives you've considered
There are not really good alternatives:
- restrict our instructor users to the definitions available
- manually make changes in Jenkins pipelines

### Additional context

We volunteer to provide a solution above.

The change can be done in a first implementation transparent to upgrades. The resulting files will be identical between old and new generation mechanisms. On the long run, we want to implement further exercise attributes to configure the pipeline configuration.

Also flexible template generation can be applied to other templates (e.g. example generation).

**Comment by sleiss** [comment]
@Wallenstein61 Regarding point 2: `Provide more flexible ways to provide (Jenkins) templates`:
This is already possible as of now, see https://artemis-platform.readthedocs.io/en/latest/dev/setup/programming-exercises/#templates.

You can override the Jenkins-templates that are included in the source code using a folder `Jenkins` in the root directory.

The other points, especially the more flexible templating engine, are not yet implemented, but maybe this already helps you a bit.

**Comment by b-fein** [comment]
We have a setup where the actual pipeline steps are defined by a `pipeline.groovy` script in the `tests`-Repository.

This is probably not a full solution to templating problems but might be enough to give you an usable workaround or at least a starting point.

`templates/jenkins/java/Jenkinsfile` in the filesystem next to the `Artemis.war` contains a skeleton that calls the actual script:
(`templates/jenkins/java/Jenkinsfile-staticCodeAnalysis` is a symlink to this file in our case)
*As long as this template is placed on the Artemis server all newly created Java exercises have to adhere to this format of split pipeline files. There is no way to select this template on a per exercise basis.*
```groovy
// ARTEMIS: JenkinsPipeline

node('docker') {
    ownStages = null
    try {
        stage('Checkout') {
            checkout([
                $class: 'GitSCM',
                branches: [[name: '*/master']],
                doGenerateSubmoduleConfigurations: false,
                extensions: [],
                submoduleCfg: [],
                userRemoteConfigs: [[
                    credentialsId: '#gitCredentials',
                    name: 'tests',
                    url: '#testRepository'
                ]]
            ])
            dir('#assignmentCheckoutPath') {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/master']],
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [],
                    submoduleCfg: [],
                    userRemoteConfigs: [[
                        credentialsId: '#gitCredentials',
                        name: 'assignment',
                        url: '#assignmentRepository'
                    ]]
                ])
            }
        }
        stage('Load') {
            timestamps {
                ownStages = load 'pipeline.groovy'
                ownStages.testRunner()
            }
        }
    } finally {
        if (ownStages != null) {
            ownStages.postBuildTasks()
        }
        sendTestResults credentialsId: '#jenkinsNotificationToken', notificationUrl: '#notificationsUrl'
        cleanWs()
    }
}
```

Then, inside the `tests`-Repository the task creator can add a `pipeline.groovy` file with the actual pipeline definition, written as a Scripted Pipeline https://www.jenkins.io/doc/book/pipeline/syntax/#scripted-pipeline (stripped down from our version, I hope it works)
```groovy
dockerImage = "INSERT_IMAGE_TAG_HERE"
dockerFlags = ""

/**
 * Main function called from jenkins
 * @return
 */
def testRunner() {
    setup()

    build()

    stage('Test') {
        // catchError: execute steps following this, even if this one fails
        catchError {
            unitTests()
        }
        staticCodeAnalysis()
    }
}

/**
 * For special tasks before the actual tests can begin
 *
 * E.g. building of docker images defined by Dockerfiles also stored in the tests repository,
 * setting docker flags specifically for student repos, …
 *
 * @return
 */
def setup() {
    if ("${env.JOB_NAME}" ==~ /.+-SOLUTION$/) {
        // special jobs to run only for the solution repository
        // …
    } else {
        // …
    }
}

/**
 * Build the student code
 * @return
 */
def build() {
    stage('Build') {
        docker.image(dockerImage).inside(dockerFlags) { c ->
            // unit tests currently in own stage, use second line below
            // and adapt stage-order defined in `testRunner` to run them in a
            // single one
            sh 'mvn -B clean compile'
            // sh 'mvn -B clean compile test'
        }
    }
}

/**
 * Run unit tests using maven
 * @return
 */
def unitTests() {
    stage('UnitTests') {
        docker.image(dockerImage).inside(dockerFlags) { c ->
            sh 'mvn -B test'
        }
    }
}

/**
 * Run the static code analysis
 * @return
 */
def staticCodeAnalysis() {
    stage("StaticCodeAnalysis") {
        docker.image(dockerImage).inside(dockerFlags) { c ->
            sh """
            mvn -B spotbugs:spotbugs checkstyle:checkstyle pmd:pmd pmd:cpd
            mkdir -p staticCodeAnalysisReports
            cp target/spotbugsXml.xml staticCodeAnalysisReports
            cp target/checkstyle-result.xml staticCodeAnalysisReports
            cp target/pmd.xml staticCodeAnalysisReports
            cp target/cpd.xml staticCodeAnalysisReports
            """
        }
    }
}

/**
 * Script of the post build tasks aggregating all JUnit files in $WORKSPACE/results
 * @return
 */
def postBuildTasks() {
    sh 'rm -rf results'
    sh 'mkdir results'
    sh 'cp target/surefire-reports/*.xml $WORKSPACE/results/ || true'
}

return this
```

**Comment by Wallenstein61** [comment]
Oh, looks quite interesting. 

Not an expert with groovy,  but if I understand it correctly, then the actual pipeline is generated on the fly for each run (potentially depending on actual repository content)?
This would even be better than our planned solution.

We will have a try with this.

Michael

**Comment by b-fein** [comment]
> Not an expert with groovy, but if I understand it correctly, then the actual pipeline is generated on the fly for each run (potentially depending on actual repository content)?

Yes, you can definitely do something like that.
We only use that functionality to execute some special tasks only for the `solution`-Repository (building the docker image used for this exercise and create some docker volumes with some additional files that get mounted into the containers when executing student code) but you have complete freedom to add conditional steps by using anything from the individual student’s repository content.

**Comment by Wallenstein61** [comment]
Hello, just as an intermediate feedback. I have played around with your proposal. Had a hard time to get it running (not being a groovy expert).

It seemed that there was a 
``` 
   return this;
``` 
missing at the end of "pipeline.groovy".
( see https://stackoverflow.com/questions/54838794/jenkinsfile-java-lang-nullpointerexception-cannot-invoke-method-printpn-on )

The next step will be, to make it run inside our projects.

**Comment by b-fein** [comment]
Closing this issue as there is now a more detailed issue (#5726) describing how the approach as proposed above could be implemented as part of a proper integration into Artemis.
