### ISSUE TITLE
SSH url not showing for  cloning a repository

### ISSUE THREAD

**Issue by FelberMartin** [ls1intum/Artemis#2816]
#### To Reproduce

1. Go to a programming exercise
2. Click on clone repository
3. Click on use SSH
4. The url is the same as the https url

#### Expected behavior

When I click 'USE SHH' I expect to get the ssh link to clone the project. 
This worked fine for me till now. 

### Environment

<details><pre>
 - OS: Windows 10
 - Browser: Firefox, Google Chrome (tried both of them)
 - Versions: 85.0 (Firefox), 88.0.4324.146 (Google Chrome)
</pre></details>

**Comment by krusche** [comment]
duplicate, this is already fixed on `develop` and will be part of the next release
