### ISSUE TITLE
Quiz exercises in exams cannot be edited

### ISSUE THREAD

**Issue by jerhard** [ls1intum/Artemis#2822]
### Describe the bug
After quiz exercises have been created in an exam, they cannot be edited, as the edit page does not load.
Only the top bar of Artemis is shown on the page. 

#### To Reproduce
1. Create a quiz exercise in an exam.
2. Add some MC questions and save the quiz
3. In the exam exercise overview, click on *Edit* for the just created quiz 
4. The Artemis page that loads contains no content.

#### Expected behavior
It should be possible to edit quiz exercises in exams. 

#### Screenshots
The page that is shown instead of the edit view for quizzes.
![empty_page](https://user-images.githubusercontent.com/5951582/106935231-6028da00-671b-11eb-9df7-69aa015dddb5.png)
[Example](https://artemis.ase.in.tum.de/course-management/109/exams/186/exercise-groups/643/quiz-exercises/3250/edit)
(might `404` in the future)
### Environment
Same issue on Firefox and Edge Beta.

#### Additional context
It is not clear how reproducible this problem is.

**Comment by krusche** [comment]
Thank for the error report. It should be fixed on `develop` now and in the next release. (need to verify it on a test server)

**Comment by FrankeLukas** [comment]
Confirmed that the edit button works again.

**Comment by krusche** [comment]
I can also confirm it
