### ISSUE TITLE
Restrict usernames to letters and digits only (Internal user managment)

### ISSUE THREAD

**Issue by 1-alex98** [ls1intum/Artemis#2824]
### Describe the bug
. Break the system because in a git repo name they cause funny errors when not escaped :D 
But the username on registration allows allows @ . and a lot more... just change the pattern in lin 25 of register.component.ts. The text in the html already say only digits and letters but the pattern in type script is wrong.

#### To Reproduce

Register a user see you can register a lot of stuff which ends funny.

**Comment by axel1200** [comment]
```
    userNamePatter = '[a-zA-Z0-9]{2, 10}';
    ...
            login: ['', [Validators.required, Validators.minLength(4), Validators.maxLength(10), Validators.pattern(this.userNamePatter)]],

``` 
line 25 register.component.ts

**Comment by axel1200** [comment]
Also min length for username is 4 but warning  text says it would be 1. Also max. 50 characters seems to much 10 would be more appropriate.

**Comment by krusche** [comment]
Min 4 should be the case. I think Max 10 is too less. If there is no reason to limit the max length, we should keep it at 50

**Comment by axel1200** [comment]
I mean the warning is: "name must at least have 1 character"

**Comment by axel1200** [comment]
in register.json in de and en

**Comment by axel1200** [comment]
Maybe would be good to test if a 50 character name works. Because I can imagine that gitlab might get angry if you create repos with 100 character name. Never tried.
