### ISSUE TITLE
Test runs are not compatible with Edit in Editor in Exams

### ISSUE THREAD

**Issue by krusche** [ls1intum/Artemis#2829]
If an instructor creates a test run, he cannot navigate into edit in editor any more, the server will return a 500 error due to the following exception:

<img width="1308" alt="image" src="https://user-images.githubusercontent.com/744067/107038093-4ee3da00-67bc-11eb-8a3f-9f532346758f.png">

We should also check what happens if there are multiple test runs.

**Comment by delsner** [comment]
This is related to #2806 and seems to work fine again after running
> Update result set assessment_type = 'MANUAL' where assessment_type = 'TEST_RUN'

on the database or re-creating the corrupt exercise.
