### ISSUE TITLE
Reachable points can be greated than overall points for quiz exercises after practicing

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#2840]
#### To Reproduce
1. Participate in a quiz
2. Make sure that statistics calculate as expected
3. Practice the same quiz
4. See that reachable points are greater than overall points

#### Expected behaviour
Nothing changes after practising

#### Screenshots
![](https://gyazo.com/61fba78b6b4a349292647eb5166fa08f/raw)

### Environment

<details><pre>
 - OS: Windows 10
 - Browser: Chrome v88.0.4324.150
</pre></details>

#### Additional context
On step 2 the initializationState of the participation is `FINISHED` but once you've practised the quiz it's `INITIALIZED`.
In line 56 of the [course-score-calculation.service.ts](https://github.com/ls1intum/Artemis/blob/develop/src/main/webapp/app/overview/course-score-calculation.service.ts) you can see that in this case the reachable points get added a second time (first in line 50).
The state shouldn't change when practising in my opinion

This was found by a student and reproduced by me.

**Comment by krusche** [comment]
In this case the result should be unrated and should be ignored for the score
