### ISSUE TITLE
Complains shouldn't be accepted/rejected instant

### ISSUE THREAD

**Issue by Kroko-fant** [ls1intum/Artemis#2847]
### Describe the bug

![grafik](https://user-images.githubusercontent.com/25010075/107370676-954e7700-6ae3-11eb-9255-b763b773910c.png)

In my opinion the reject button and the bigger message window should have more space in between. so the problem is that you can trigger the reject button very easy when you want to extend the window.
An other even better way would be to add an extra warning before accepting or rejecting a complain, like it is when you cancel the assessment of an exercise

I mean its an easy fix probably. There should be just an extra check

#### To Reproduce
1. Start a complain
2. click on reject

### Environment
ALL (tested with Firefox newest Version)

PS: please contact me if you need additional information

**Comment by MaisiKoleni** [comment]
@Kroko-fant please check if #2877 resolved your issue. (Will be released this Thursday)

**Comment by Kroko-fant** [comment]
works fine as a quick fix :)
