### ISSUE TITLE
Automatic and manual unlocking of repositories in Gitlab in exam-mode fails

### ISSUE THREAD

**Issue by tiefenau** [ls1intum/Artemis#2853]
### Describe the bug
We created an exam consisting of three blocks. Two of them contained text questions and one contained a programming exercise we imported from an existing one. 
Right before the exam began, we got the message: 
'When adding the write permissions for the student repositories, not all operations were successful. Number of failed operations: 2'
Unlocking all repositories manually (using course-management/2/exams/7/student-exams) then resulted in all prior successfully unlocked ones to be locked again and triggered another message 'When adding the write permissions for the student repositories, not all operations were successful. Number of failed operations: 462'. 
Using the button on 'course-management/2/programming-exercises/91', it shows the appended image.
Since then, we were not able to unlock them using the frontend. 

#### To Reproduce
see above.

#### Expected behavior
We wanted to have all repositories in Gitlab unlocked

#### Screenshots
![Bildschirmfoto 2021-02-10 um 15 22 45](https://user-images.githubusercontent.com/16190604/107522755-4de3eb80-6bb4-11eb-85f2-5545c87c0c70.png)

### Environment

<details><pre>
 - OS: MacOS. 
 - Server: Ubuntu 18.04. Artemis 4.9.4 runs using docker-compose
 - Source-Contol: Gitlab
 - Browser: Brave 
 - Artemis: alpro.besec.uni-bonn.de
 - Gitlab: gitlab.christiantiefenau.de
</pre></details>

#### Additional context
There are a lot of exceptions in the logs when triggering the button. They begin like this:

`
artemis                    | 2021-02-10 13:56:50.535 ERROR 1 --- [nio-8080-exec-5] a.s.s.ProgrammingExerciseScheduleService : 'add write permissions to all student repositories' failed for programming exercise with id 91 for student repository with participation id 12377
artemis                    | 
artemis                    | java.lang.NullPointerException: Cannot invoke "java.util.Map.containsKey(Object)" because the return value of "org.gitlab4j.api.GitLabApiException.getValidationErrors()" is null
artemis                    |    at de.tum.in.www1.artemis.service.connectors.gitlab.GitLabService.addMemberToRepository(GitLabService.java:107)
artemis                    |    at de.tum.in.www1.artemis.service.connectors.gitlab.GitLabService.configureRepository(GitLabService.java:91)
artemis                    |    at de.tum.in.www1.artemis.service.ProgrammingExerciseParticipationService.unlockStudentRepository(ProgrammingExerciseParticipationService.java:321)
artemis                    |    at de.tum.in.www1.artemis.service.scheduled.ProgrammingExerciseScheduleService.lambda$unlockAllStudentRepositoriesForExam$3(ProgrammingExerciseScheduleService.java:297)
artemis                    |    at de.tum.in.www1.artemis.service.scheduled.ProgrammingExerciseScheduleService.invokeOperationOnAllParticipationsThatSatisfy(ProgrammingExerciseScheduleService.java:452)
artemis                    |    at de.tum.in.www1.artemis.service.scheduled.ProgrammingExerciseScheduleService.lambda$unlockAllStudentRepositoriesForExam$5(ProgrammingExerciseScheduleService.java:299)
artemis                    |    at de.tum.in.www1.artemis.service.messaging.InstanceMessageReceiveService.processUnlockAllRepositories(InstanceMessageReceiveService.java:98)
artemis                    |    at de.tum.in.www1.artemis.service.messaging.InstanceMessageReceiveService$$FastClassBySpringCGLIB$$8cfdda8e.invoke(<generated>)
artemis                    |    at org.springframework`

**Comment by 1-alex98** [comment]
It could be that our nginx config just has pretty low timeout set. I already noticed on the plagiarism check. If that should be the issue a note in the documentation should be added.

**Comment by 1-alex98** [comment]
I will try having a higher timeout and then see if the next exam it is gone

**Comment by ivanchimeno** [comment]
I think that @1-alex98  is right, this error occurs when the timeout is too low. I had a similar issue on my local setup where I gave the Gitlab container too little memory. When the memory is full, Gitlab can't process the request and that exception is thrown.

 @1-alex98 wrote some documentation in PR #3016 on how to increase the timeout. Let me know if that helps and if  I can close this issue

**Comment by ivanchimeno** [comment]
I closed this issue for now but feel free to re-open it if it still occurs.
