### ISSUE TITLE
Team name with leading digits causes Internal Server Error

### ISSUE THREAD

**Issue by kappelmann** [ls1intum/Artemis#2854]
### Describe the bug

Team names with leading digits lead to internal server errors

#### To Reproduce

1. Create team name with leading digit, e.g. `1hallohallo`
2. Assign yourself to the team
3. Try to checkout the exercise
4. Result: Internal Server Error

**Comment by krusche** [comment]
I guess the issue is related to programming exercises, the team short name is used to create programming exercises on Bitbucket / Bamboo. I guess we should simply forbid team names / short names with leading digits

**Comment by derLalla** [comment]
When you created the teamname, what did you choose for the name? The shortname cannot start with a digit, so this should not be an issue: 

![image](https://user-images.githubusercontent.com/33484318/109640702-18964200-7b51-11eb-9c73-80ed1460493f.png)

**Comment by kappelmann** [comment]
We used the import from a file option to create the teams.
For example, save the following as `team.json` and replace the username by your LRZ ID
```json
[{"teamName": "1hallohallo","username": "gaXXXXX"}]
```
The check will then not be triggered.

**Comment by derLalla** [comment]
> We used the import from a file option to create the teams.
> For example, save the following as `team.json` and replace the username by your LRZ ID
> 
> ```json
> [{"teamName": "1hallohallo","username": "gaXXXXX"}]
> ```
> 
> The check will then not be triggered.

thanks! that helped me finding and fixing the bug. #2947
