### ISSUE TITLE
Properties popover auto closes when auto-save triggers

### ISSUE THREAD

**Issue by Khalphion** [ls1intum/ArTEMiS#286]
It seems that the auto-save closes the properties popover (when editing a class or association). 

### Environment
<details><pre>
 - OS: macOS Mojave 10.14.3
 - Browser: Chrome 73.0.3683.86
 - Version: Artemis 2.8.0
</pre></details>

**Comment by krusche** [comment]
Thanks for reporting. I think this issue was already fixed. In case this is still a problem, please feel free to reopen this issue. It would be great if you could then provide more details, ideally a screenshot.
