### ISSUE TITLE
Save attribute / method after dismissing with click outside

### ISSUE THREAD

**Issue by Khalphion** [ls1intum/ArTEMiS#287]
### Is your feature request related to a problem?
E.g. when I add an attribute to a class, I click outside the popover and expect the application to save. Currently the application just drops my input.

### Describe the solution you'd like
Clicking outside the popover should add the property.

### Describe alternatives you've considered
Add a button next to the input so I can click on it to save.

**Comment by jwilland-tum** [comment]
Thanks for the feedback! This is actually an issue with the integrated subsystem Apollon, therefore we move it over there. See https://github.com/ls1intum/Apollon/issues/28
