### ISSUE TITLE
Text exercise: Visual indication for feedback; colours are not optimal 

### ISSUE THREAD

**Issue by Khalphion** [ls1intum/ArTEMiS#288]
### Is your feature request related to a problem?
A red or yellow colour might confuse the student as it looks "wrong", but the colour is just used to indicate the relationship between the assessment and the student's answer. 

### Describe the solution you'd like
Display the feedback when clicking on the answer (similar to the "notes" of Moodle that are attached to the PDF / image).

### Describe alternatives you've considered
Use lines that show up on hovering and connects the answer with the tutor's feedback.

**Comment by rpadovani** [comment]
Thanks for the feedback, we are actually going to work on how we show the result of assessments to students

**Comment by rpadovani** [comment]
Fixed by #341
