### ISSUE TITLE
Sorting in student exams view not working as expected

### ISSUE THREAD

**Issue by delsner** [ls1intum/Artemis#2886]
Sorting by student name in the "student exams" view does not work as expected.
Clicking on "Student" will sort by the `user` object, leading to a misordering, as one would expect that the list is sorted by the full names of the students, that are displayed.

My first guess would be that the issue is in [this line](https://github.com/ls1intum/Artemis/blob/develop/src/main/webapp/app/exam/manage/student-exams/student-exams.component.html#L147), since it seems to sort by `user` rather than `user.name`.

This occurs in version 4.10.0.

**Comment by krusche** [comment]
Thanks, we also noticed this and are working on a fix
