### ISSUE TITLE
Exams: "Enable Second Correction" and "Delete Exam" Buttons are shown to tutors

### ISSUE THREAD

**Issue by jerhard** [ls1intum/Artemis#2892]
### Describe the bug
For exams, 
(a) tutors see "enable second correction"/"disable second correction" buttons for exercises. 
(b) They also see a "Delete" button for the exam, as well as a "Scores" button.

#### To Reproduce
1. Create and conduct exam
2. Add tutors
3. Tutors can see the aforementioned buttons in the assessment dashboard of the exam (a) and in the course management view of the exam (b), respectively.

It was not tested whether these buttons actually work for tutors.

#### Expected behavior
Tutors should not see the "enable second correction"/"disable second correction" buttons, and the "delete" button for the exam.
They probably also should not be able to see the button for the overall "scores" in the exam.

Additionally, it should be ensured that tutors are not able to perform these actions (via the API), if this is not the case already.

#### Screenshots
The enable/disable second correction buttons for the exam that tutors see:
![Enable_Disable_second_correction](https://user-images.githubusercontent.com/5951582/108510250-90957a00-72be-11eb-968e-f8ec481863df.png)

The "Delete" and "Scores" buttons that are shown to tutors for the exam:
![Delete](https://user-images.githubusercontent.com/5951582/108510242-8e332000-72be-11eb-8ead-09fc587b8a48.png)

**Comment by krusche** [comment]
The server prevents those actions, but you are absolutely right, those buttons should not be displayed for tutors. We will disable them for tutors asap
