### ISSUE TITLE
Re-evaluate might not work for exam quizzes

### ISSUE THREAD

**Issue by krusche** [ls1intum/Artemis#2908]
The following exception occurs:
```
Feb 22 08:57:57 node4 java[118960]: java.lang.NullPointerException: Cannot invoke "de.tum.in.www1.artemis.domain.quiz.QuizSubmission.getSubmittedAnswers()" because "quizSubmission" is null
Feb 22 08:57:57 node4 java[118960]:         at de.tum.in.www1.artemis.service.QuizExerciseService.updateResultsOnQuizChanges(QuizExerciseService.java:192)
Feb 22 08:57:57 node4 java[118960]:         at de.tum.in.www1.artemis.service.QuizExerciseService.reEvaluate(QuizExerciseService.java:366)
Feb 22 08:57:57 node4 java[118960]:         at de.tum.in.www1.artemis.web.rest.QuizExerciseResource.reEvaluateQuizExercise(QuizExerciseResource.java:460)
```

There are additional (duplicated) results in the database that are not connected to a submission any more (these results are only connected to the participation). This might be related to how the `Evaluate quizzes` button on the Student exams page creates the quiz results.

We should also check what is happening when instructors press the `Evaluate quizzes` button multiple times.

**Comment by izycheva** [comment]
Here are some details on how I've arrived to the error state:
1. Pressed "Evaluate quiz" and checked in student's view that some short answer submissions should be added as an additional correct option. Student view showed the evaluation results of the quiz.
2. Went to quiz exercise -> Re-evaluate -> Add Text Drag Item -> input the value and correct mapping -> Save. The message said that submissions were successfully re-evaluated. 
3. Go to student's view to check if the re-evaluation worked. The added option is still marked as "wrong".
4. Go back to "Re-evaluate" and see that the added options have disappeared.
5. Notice the "Make sure you evaluate the quiz first" message and go to "Student exams -> Evaluate quizzes" 
6. In the student view I could no longer see the quiz evaluation results.
7. Repeat steps 5 + 2 and get error message for re-evaluation. (done this several times, ~4)
 At the moment I still cannot see detailed evaluation results in the student's view (which answer is correct and how many points are given per answer), but can see the total number of points a student got for the quiz.

**Comment by krusche** [comment]
The button `Evaluate quizzes` in the Student Exams page should only be invoked once. It should not do anything if instructors press it the 2nd, 3rd, ... time

Re-evaluating quizzes should then be done individually per quiz exercise in the respective page.

We should also change the wording for short answer question in exercise -> Re-evaluate: Add Text Drag Item --> Add Short Answer Solution (I guess this is still an issue because short answers were copied from the drag and drop questions that existed before)

**Comment by izycheva** [comment]
> We should also change the wording for short answer question in exercise -> Re-evaluate: Add Text Drag Item --> Add Short Answer Solution (I guess this is still an issue because short answers were copied from the drag and drop questions that existed before)

I also suggest to enable text editing for the short-answer questions (as opposed to only visual editor right now in the re-evaluation). In my attempts dragging the answer to the correct "spot" didn't always work reliably. Sometimes I had to repeat the "dragging" 5-6 times before it indicated the correct mapping.

**Comment by krusche** [comment]
The problem with text editing is that Artemis would loose the information about the ids and could not automatically detect if you have changed an existing one, or deleted one and added a new entry...

**Comment by izycheva** [comment]
I see... How about text mode only for new options? or any other way of creating a mapping: drop-down list? (though maybe it's just me who can't drag to the correct position from the first try)

**Comment by krusche** [comment]
we'll think about making it easier to add new options
