### ISSUE TITLE
Atlassian Setup for local development no longer available

### ISSUE THREAD

**Issue by fde312** [ls1intum/Artemis#2922]
### Describe the bug

Due to policy change Atlassian will not support any more the Server services. We need to change our local testing setup to reflect the policy changes, as new developers will not be able to register for new Atlassian Server licenses. 

As @Mtze mentioned there is a pre-live instance hosted at the chair, that could be used for our testing purposes.

We need to evaluate this soon, as for the next developers the last server licenses will expire soon.

**Comment by krusche** [comment]
Developers should use the Gitlab / Jenkins setup and test programming exercises with Bitbucket / Bamboo on the test servers. In case there is a developer who wants to further develop the connectors to Bitbucket / Bamboo, we will find a solution
