### ISSUE TITLE
Number of programming exercises different for some students

### ISSUE THREAD

**Issue by tiffca** [ls1intum/Artemis#2927]
### Describe the bug
On the Student Statistics page: At least 2 students have reported that they are only able to see 41 programming exercises when there are 42. 
Affected students: Pellumb Baboci (ge96jur) , Ajayvir Singh (ge65lay), Merlin Mehmed [maybe there is a query being run that is based on the student identifier? ] 

The students are worried this will affect their score calculation. 

#### To Reproduce
1. In Prod, As a student who is affected, go to the student Statistics page of the PSE course (https://artemis.ase.in.tum.de/courses/88/statistics)
2. View the number of programming exercises 
3. Notice it says 41 instead of 42
4. (not yet sure how to reproduce the issue where it is not already present)

#### Expected behavior
Expected is that all students should see 42 programming exercises 

#### Screenshots
With issue 
![image](https://user-images.githubusercontent.com/63906424/108966853-06169700-767f-11eb-828b-3cdefbea4d0f.png)

Without the issue 
![image](https://user-images.githubusercontent.com/63906424/108966843-0151e300-767f-11eb-9921-fb7b152e03ea.png)

### Environment

Requested these details from the students 
<details><pre>
</pre></details>

#### Output in Web Console
Requested from the student 

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by krusche** [comment]
Might be related to https://en.wikipedia.org/wiki/42_(number)

**Comment by jpbernius** [comment]
This is expected as we have one exercise that is scheduled for 2023. There are 41 visible exercises and it is displayed correctly.
