### ISSUE TITLE
🍬 Overall points increase when clicking "Save" for the "Working Time"

### ISSUE THREAD

**Issue by claujor** [ls1intum/Artemis#2928]
### Describe the bug
When managing student exams, an instructor can adjust the Working Time manually. When the "Save" button is pressed, not only the "Working Time" is stored but also the "Overall Points" are recalculated. That results in displaying a false sum of points for the exam on the frontend.

See
https://github.com/ls1intum/Artemis/blob/e2b54b89fa93359a88f5fffc5f4969c576d98117/src/main/webapp/app/exam/manage/student-exams/student-exam-detail.component.ts#L108
Apparently, `maxTotalScore` is not reset to `0` before summing the points when called within `saveWorkingTime()`
https://github.com/ls1intum/Artemis/blob/e2b54b89fa93359a88f5fffc5f4969c576d98117/src/main/webapp/app/exam/manage/student-exams/student-exam-detail.component.ts#L88

#### To Reproduce
see description

#### Expected behavior
Overall points should stay the same.

**Comment by krusche** [comment]
Thanks for reporting the issue, we will fix it
