### ISSUE TITLE
Participating in programming exercise after deadline changes score

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#2955]
### Describe the bug
A student described that she started a programming exercise after the deadline of the exercise to practice it. She didn't participate in the exercise before.
This process increased her score in the statistics.

#### To Reproduce
1. Create an exercise with deadline X and Y points
2. Wait until deadline X passes
3. Make sure that you got 0/Y points in the statistics tab
4. Participate in the exercise
5. Check the statistics tab

#### Expected behaviour
This process shouldn't affect the score since it happened after the deadline.

#### Screenshots
-

### Environment
- Students system, let me know if you need details

#### Additional context
The participations are shown as not graded so that part is correct. I assume that there needs to be an additional conditional on the score calculation.

**Comment by krusche** [comment]
Can you please ask here to shared as screenshot and a few more details, e.g. which exercise? Ideally also the student name (you can send it on Slack) so that we can find the case in the database

**Comment by julian-christl** [comment]
I'll give you the information on Slack

**Comment by krusche** [comment]
We fixed the issue in #2980
Please double check if your issue has actually been fixed as soon as the new version 4.10.5 has been deployed.

**Comment by julian-christl** [comment]
The student retested this issue with another exercise and the percentage didn't change, so this should be fixed.
