### ISSUE TITLE
Allow instructors to open the result / assessment screen on the student exam detail page

### ISSUE THREAD

**Issue by krusche** [ls1intum/Artemis#2962]
Instructor can navigate to the student exam details of one student and can see the points.
However, they cannot navigate to the assessment screens directly in case something is wrong or they want to specifically check something. It should be relatively easy to display links on this page so that instructors can directly navigate to the result screen and potentially override the assessment in case it is wrong.

Additional information would also be helpful:
1) Show who has assessed the latest (and counting) result
2) Show if the student has complained about this exercise (and potentially allow the instructor to read the message, e.g. in a small popup) including information if the complaint has been addressed or not

**Comment by nicolasruscher** [comment]
Implemented.
