### ISSUE TITLE
Notifications in exam mode

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#2965]
### Is your feature request related to a problem?
When there is an error in one exercise variant which has to be fixed, it's not possible to notify all people in this variant.

### Describe the solution you'd like
Add a message system that sends the students of one exercise variant a message.
The student should see a popup-notification on top of the exam.

### Describe alternatives you've considered
Send it to all outside of Artemis but that isn't quite a good solution.

**Comment by Malyuk-A** [comment]
I am closing this issue, because it was resolved in https://github.com/ls1intum/Artemis/pull/3637 & https://github.com/ls1intum/Artemis/pull/3903.
