### ISSUE TITLE
Cover the "no-tests" or "tests after exercise end" case

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#2966]
### Describe the bug
If there are no tests executed during the exam/not shown to the student, the students get shown "0%, 0 out of 0".

#### To Reproduce
1. Create exam with programming exercise without tests / create a programming exercise
2. Participate
3. Click on the exercise
4. See issue

#### Expected behavior
Either show 100% or allow a switch to replace this with "Compiled" and "Not compiled"

**Comment by Strohgelaender** [comment]
Fixed via #3293
