### ISSUE TITLE
Show clearer indication of compilation status in Exams

### ISSUE THREAD

**Issue by joschahenningsen** [ls1intum/Artemis#2967]
### Is your feature request related to a problem?
Currently when participating in an exam there is a red message along the lines of `0% 0 of 0 passed` after pushing changes that compile successfully. This feels like there is a problem with the submitted code even though there isn't.

This confused quite a few students who participated in PSE 2020/2021.

### Describe the solution you'd like
A simple green status should be shown when the submission compiles along with a message like `submission compiled successfully`

**Comment by jpbernius** [comment]
Duplicates #2966
