### ISSUE TITLE
Manual Programming Assessment - Handle Repo Conflict State  

### ISSUE THREAD

**Issue by jpbernius** [ls1intum/Artemis#2990]
### Is your feature request related to a problem?
As a tutor, I want to assess a programming submission manually, but "the repository status could not be retrieved".
![image](https://user-images.githubusercontent.com/6382716/110474804-675b5300-80e0-11eb-9a8a-276efa80970d.png)
If the repository on Artemis is in a conflict state, I cannot resolve the conflict (e.g. `git origin reset master`).

As a student, I have a resolve conflict button, but not as a tutor for assessment.

### Describe the solution you'd like
Add a resolve conflict button for the assessor.

### Describe alternatives you've considered
New checkout for tutors? Not sure if that is a good idea.

### Additional context
In our instance, this was noticed as part of an exam!

**Comment by Strohgelaender** [comment]
Duplicate #2885
