### ISSUE TITLE
Processing complaints not possible for single course instructor

### ISSUE THREAD

**Issue by JonasSC** [ls1intum/Artemis#3033]
### Describe the bug
Being the only instructor for my course, I was not able to respond to the students' complaints in the exam review, because Artemis does not allow a complaint to be processed by the same person, who gave the original feedback.

#### Expected behavior
It is admirable, that Artemis has so many features, that ensure a fair evaluation, so the aforementioned behavior should remain the default, in my opinion. However, for courses with just one instructor, it should be possible to disable this lock.

#### Screenshots
![grafik](https://user-images.githubusercontent.com/2746810/111382552-6b224300-86a7-11eb-8d01-9280e7af79a3.png)

**Comment by krusche** [comment]
this was just fixed by merging #3019 
(we can read your mind)

**Comment by JonasSC** [comment]
Cool, thank you!
