### ISSUE TITLE
Structured grading instructions should not be immutable

### ISSUE THREAD

**Issue by JonasSC** [ls1intum/Artemis#3038]
### Is your feature request related to a problem?
It would be great, if it was possible to change the structured grading instructions later on. For example in the following situations:
- fixing a typo in the instructions
- adding a new instruction, that was forgotten in the beginning
- allowing for testing the instructions on a couple of submissions before refining them

It is unfortunate, that it looks like one can edit the structured grading instructions later on, but once the exercise is saved, the instructions are reverted back to the original instructions.

### Describe the solution you'd like
I am aware, that changing the structured grading instructions leads to inconsistencies, because the changed grading instructions cannot always be mapped to the grading instructions, that are already used in the assessments. I have the following ideas to avoid this issue:
- Unlock the structured grading instructions, when none of them are used in any assessment. This would make it possible to delete all the assessments and then edit the grading instructions.
- Ask, whether all assessments, that use the structured grading instructions, shall be deleted when editing the structured grading instructions. Or disable the editor and have a button to delete the assessments, which enables the editor.
- Ask, whether all previous structured grading instructions shall be converted to regular annotations when editing the structured grading instructions. Or disable the editor and have a button to convert the assessments, which enables the editor.
- Don't use a text editor, but a more structured user interface, that maintains the mapping between the applied grading instructions and the ones, that are being edited.
- Add some identifiers in the text editor, through which the mapping can be maintained.

**Comment by krusche** [comment]
We are aware that grading instructions cannot be edited after being used. We have this on the roadmap to improve this as soon as possible

**Comment by krusche** [comment]
In addition, we would like to realized some kind of automatic re-evaluation based on the points mapped to grading criteria

**Comment by krusche** [comment]
fixed by #3294
