### ISSUE TITLE
[Online Editor] Allow uploading files

### ISSUE THREAD

**Issue by LDAP** [ls1intum/Artemis#3047]
### Is your feature request related to a problem?
Students may not be familiar with Git (or access to GitLab may be denied) and copy-pasteing contents into the online editor does not provide a great user experience.

### Describe the solution you'd like
A button "Upload" allowing students to upload files into the editor.

**Comment by dfuchss** [comment]
An easy way could be an upload button that allows only files (not folders) and put the files in the selected directory.

**Comment by krusche** [comment]
I am not a big fan of this idea. The online Code Editor is quite complex anyway and each additional feature which is not 100% necessary would make it even more complex

**Comment by dfuchss** [comment]
In this case I think we can close this issue until this feature is mandatory for us (or anyone else :) ).
I'll close it for now.
