### ISSUE TITLE
Edit in Editor Mode is -1 in the Breadcrumbs

### ISSUE THREAD

**Issue by MaisiKoleni** [ls1intum/Artemis#3059]
### Describe the bug
See:
![image](https://user-images.githubusercontent.com/11130248/111862893-75b73380-8958-11eb-9bbb-1145460ceaac.png)

Situation:
- From Exam -> Exercise Groups
- Click on the Edit in Editor Button
- Look at the Breadcrumbs

If you reload the page, the problem is fixed and shows the participation id (?). Using the middle mouse button to open in a new tab will also not show the error.

Cycling through the button for
```
Template Repository
Solution Repository
Assignment Repository
Test Repository
```
fixes the breadcrumbs as well, and only for "Test", the code editor is referenced in the breadcrumbs.

### Environment

<details><pre>
 - OS: Win 10
 - Browser: Vivaldi/Chromium
 - Version: current
</pre></details>

#### Output in Web Console
None

**Comment by FrankeLukas** [comment]
That is because opening a new code editor tab has `-1` in the URL until it fetches the participation.

**Comment by krusche** [comment]
> That is because opening a new code editor tab has `-1` in the URL until it fetches the participation.

we should still try to fix this

**Comment by krusche** [comment]
This issue has been resolved
