### ISSUE TITLE
Selecting Haskell should automatically check "Checkout repository of sample solution"

### ISSUE THREAD

**Issue by lukasstevens** [ls1intum/Artemis#3094]
### Describe the bug
When using the Haskell template for generating a programming exercise, the option "Checkout repository of sample solution" should be checked automatically since the Haskell testing framework relies on it.

#### To Reproduce
1. Generate a new programming exercise
2. Select Haskell as a programming language
3. The option "Checkout repository of sample solution" is not checked.

#### Expected behavior
The option "Checkout repository of sample solution" should be checked.

**Comment by krusche** [comment]
You're welcome to provide a pull request for the change :-)
