### ISSUE TITLE
Tutors see 403 Forbidden Error when correcting exams

### ISSUE THREAD

**Issue by Strohgelaender** [ls1intum/Artemis#3107]
### Describe the bug
Every time you open an exam-related page (like the exam assessment dashboard, any exercise, or if you start assessing a new exercise) a 403 Forbidden error is displayed. Even though it seems to not cause any problems while working on the exam, errors like this should not be shown on a regular basis.

Looking at the stack trace this seems to be somewhat related to the breadcrumbs.
 
#### To Reproduce

1. You need to be a Tutor in any course with an exam (instructors don't get this error)
2. Go to any page e.g. the Exam Assessment Dashboard
3. See error

#### Expected behavior
no error.

#### Screenshots
![grafik](https://user-images.githubusercontent.com/26540346/113010473-269fa880-9179-11eb-9be1-5ff0a9660cca.png)
![grafik](https://user-images.githubusercontent.com/26540346/113010654-4cc54880-9179-11eb-8c77-d5d6220671b9.png)

**Comment by FrankeLukas** [comment]
Thank you for the report. This was already fixed for the upcoming version by #3070.
