### ISSUE TITLE
Password component: wrong error message 

### ISSUE THREAD

**Issue by LDAP** [ls1intum/Artemis#3110]
### Describe the bug
The error message in the password component on "current password" references the "new password"

#### To Reproduce

1. Enable Registration
2. Login
3. Open the Password component `/account/password`
4. Click on every field once

#### Expected behavior
Better error message

#### Screenshot
![grafik](https://user-images.githubusercontent.com/8215084/113108263-17663c80-9205-11eb-9763-ebd0db597594.png)

**Comment by rs-maker** [comment]
I have fixed this and will create a pull request.
![Screenshot from 2021-04-10 19-50-04](https://user-images.githubusercontent.com/56715566/114279676-1f5c8280-9a36-11eb-961a-9ff1403ae5ec.png)

**Comment by LDAP** [comment]
Closed with #3178
