### ISSUE TITLE
Only one system notification is shown

### ISSUE THREAD

**Issue by LDAP** [ls1intum/Artemis#3130]
### Describe the bug
Only one system notification is shown, even when multiple are set up.

#### To Reproduce
1. Create and activate two system notifications.
2. Refresh client

#### Expected behavior
2 boxes with system notifications

**Comment by krusche** [comment]
This is intended. There is not enough space to show multiple ones

**Comment by ge65cer** [comment]
Fixed in https://github.com/ls1intum/Artemis/pull/5462
