### ISSUE TITLE
Access old courses🚀 

### ISSUE THREAD

**Issue by rpadovani** [ls1intum/ArTEMiS#319]
During my structured evaluation interviews for the tutors related dashboards, I collected a feedback from a tutor who asked to be able to access old courses, as a student, also after a courses is ended. They say material shared during the course is useful, and would be cool to be able to go back and review what have been done after a course is ended

**Comment by krusche** [comment]
Thanks for reporting this. We hide old courses due to performance reasons, so this is not an option at the moment.
