### ISSUE TITLE
Assessment of modeling elements can be out of bounds

### ISSUE THREAD

**Issue by MaisiKoleni** [ls1intum/Artemis#3204]
### Describe the bug
The assessment popup escapes the modeling editor, some elements cannot be edited. This will be a significant impediment when we start assessing many modeling submissions again soon (EIST).

![image](https://user-images.githubusercontent.com/11130248/114570214-f0ccea80-9c75-11eb-87cd-809b76f19a1b.png)

#### Expected behavior
The assessment component stays in the editor and everything is visible.

#### Workaround
Zooming out a lot, but this is cumbersome and makes the diagram hard to read.

### Environment
- Artemis develop (~4.11.3)
- Win 10
- Chromium

**Comment by krusche** [comment]
@iozbeyli please try to fix this issue asap...
