### ISSUE TITLE
Collapsible list items in feedback view

### ISSUE THREAD

**Issue by gstuer** [ls1intum/Artemis#3217]
### Is your feature request related to a problem?

The feedback view gets crowded and confusing when the number and length of feedback items and consequently the length of the feedback view raises. This is especially a problem caused by **long texts in feedback items**. We want to provide our students with as many information as they need to understand and solve a problem on their own. Therefore, special behavior for long texts in feedback items is needed.

### Describe the solution you'd like

The items of the feedback list should collapse theirselves as soon as the text reaches a certain length. Therefore, some kind of mechanism has to be added in order to give the user the possibility to expand the item and see the whole text. In collapsed state the item could show the first few lines of the item's text and a little button for expanding/collapsing.

### Additional context

An example of such a collapsible item view solution is the changes view of the GitHub commit history.
Please do not hesitate to contact @dfuchss, @LDAP or me if you need any further information.

![image](https://user-images.githubusercontent.com/56889322/114859732-71612780-9deb-11eb-97e3-dbc6ced073c2.png)

**Comment by dfuchss** [comment]
Some points regarding a possible implementation/logic (@krusche and I have talked about that):

An easy way to provide this feature would be that each feedback longer than `x` tokens (maybe 200) will have two UI states:
* collapsed == show the first `x` tokens + "..." (I think that should be the default case)
* not collapsed == show the actual message

**Comment by rs-maker** [comment]
I would like to tackle this one. Cant assign myself so im saying it here.

**Comment by rs-maker** [comment]
This issue has been resolved with the above PR
