### ISSUE TITLE
Modeling Bug: Example Submission cannot be changed after the first assesment

### ISSUE THREAD

**Issue by cremertim** [ls1intum/Artemis#3222]
### Describe the bug

After having assesed an example submission of a modeling excercise, you cannot change the submission itself anylonger.  You can update the assesment, but you can't change the underlying submission. If you remove all of the assesments (atleast visually), you still cannot change the underlying part.

#### To Reproduce

1. Go to 'Course Management'
2. Click on 'Create Modeling Excercise'
3. Create an Modeling Excercise
4. Create an Example submission for the modeling excercise
5. Assess this submission and save the assesment
6. Remove the assesed parts and save the assesment again
7. Try to change the underlying submission
8. You will get following message displayed, but the assesment does not save:

 circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'results' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'Object'
    --- property 'submission' closes the circle

#### Expected behavior

You should be able to change the underlying example submission

#### Screenshots

![Assesment_Saved_1](https://user-images.githubusercontent.com/65229601/114996279-f8bba300-9e9e-11eb-8947-fc792bc54231.png)
![Assesment_Saved_2_Removed](https://user-images.githubusercontent.com/65229601/114996327-03763800-9e9f-11eb-9c0e-8f81bc98a505.png)
![Trying_To_Update_Assesment_1](https://user-images.githubusercontent.com/65229601/114996341-06712880-9e9f-11eb-9deb-e3b803a20c11.png)
![Trying_To_Update_Assesment_2](https://user-images.githubusercontent.com/65229601/114996355-08d38280-9e9f-11eb-9337-9c9f41e4bd53.png)

### Environment

<details><pre>
 - OS: [Windows]
 - Browser [Chrome]
 - Version [89.0.4389.114]
</pre></details>

#### Additional context

I tried the same procedure with text excercises, but there you can update the underlying submission, even when there is a assesment.

#### Output in Web Console

<details><pre>
  [No Output in the Web Console]
</pre></details>

**Comment by krusche** [comment]
@iozbeyli please have a look into this issue. Thanks
