### ISSUE TITLE
Importing Text Excercises does not work on the production server

### ISSUE THREAD

**Issue by cremertim** [ls1intum/Artemis#3261]
### Describe the bug

On production, i am currently not able to import text excercises

#### To Reproduce

1. Go to Course Management
2. Click on your excercises in a Course (used Test: Eist2021 in the screencast)
3. Scroll down to import text excercise
4. Configure all necessary parts (due dates)
5. Scroll down and try to import the excercise
6. See the error message:  Bad request

#### Expected behavior

The excercise should be imported succesfully

#### Screenshots

https://user-images.githubusercontent.com/65229601/115520586-9aba0180-a28a-11eb-8ac4-2601109ff548.mp4

### Environment

<details><pre>
 - OS:Windows 10
 - BrowserChrome
 - Version 90.0.4430.85
</pre></details>

#### Output in Web Console

<details><pre>
</pre></details>

**Comment by FrankeLukas** [comment]
The error is related to categories. Removing the categories before the import works around the issue for now.

**Comment by FrankeLukas** [comment]
Error message:
```
Bad Request: JSON parse error: Cannot deserialize value of type `java.util.HashSet<java.lang.Object>` from Object value (token `JsonToken.START_OBJECT`); nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.HashSet<java.lang.Object>` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (PushbackInputStream); line: 1, column: 998] (through reference chain: de.tum.in.www1.artemis.domain.TextExercise["categories"]->java.util.HashSet[0])
```
