### ISSUE TITLE
Lock on "List of complaints" side doesn't seem to work correctly 

### ISSUE THREAD

**Issue by WeissAugust** [ls1intum/Artemis#3271]
### Describe the bug

When working on complaints I noticed that Artemis seems to give away a new "lock" everytime you click on the "Show the complaint" button to the person who clicked it last. When someone is working already on it his feedback will get ignored.

#### To Reproduce

1. Go to 'List of complaints' page for an assessment
2. Click on 'Show the complaint' where a lock is already shown
3. When navigating out of the 'Complaint' view back to 'List of complaints' Artemis shows that you are the owner of the "Lock" currently
4. The second person working on the complaint will get ignored by the system since you own the "lock"

#### Expected behavior

You should be able to look at already locked complaints, but only the person who owns the lock should be able to edit it.
Also in the 'Complaint' side you are not able to remove your lock -> like in the 'Assessment'-view by clicking 'Cancel'

### Environment

<details><pre>
 - OS: Windows 10
 - Browser Chrome
</pre></details>

**Comment by Strohgelaender** [comment]
This is because you have instructor rights. When instructors open a locked complaint the lock will be overwritten by the instructor.

I think this behavior should be changed. Instructors should be able to remove complaint locks using an additional button. This should not be done by just opening the page.

**Comment by WeissAugust** [comment]
Okay if thats the case at least a warning for the instructor and the member working on it would be nice.

A button for removing the complaint lock would be even better.
