### ISSUE TITLE
Quiz Export File Name

### ISSUE THREAD

**Issue by NicolasUllmann** [ls1intum/Artemis#3311]
### Is your feature request related to a problem?

During the process of exporting quizzes, I noticed that the json files always get named "quiz" and as a result, it gets hard to keep an overview. After exporting like 15 quizzes I had 15 files which were named "quiz (1)", "quiz (2)", ... And it's a lot of extra effort if you have to rename every exported file to match the wanted keywords.

### Describe the solution you'd like

It would be awesome if there was a way to match the file name to the exercise name. I just tested it for quizzes, so f.e. a file would then not be just named "quiz" but rather "Quiz L01E01".

**Comment by AdrianMirica** [comment]
Hello, I am new to this project, but I want to help so I want to ask if this issue is still available?
