### ISSUE TITLE
Plagiarism detection for Text Exercises adds random ">" characters

### ISSUE THREAD

**Issue by AlEscher** [ls1intum/Artemis#3322]
### Describe the bug
When reviewing the results of a plagiarism detection, many submissions have random ">" characters inserted into the actual submission text

#### To Reproduce

1. Start a plagiarism test on a Text exercise
2. Review any matches
3. A lot of them will contain random ">" characters

#### Expected behavior

The submission texts don't contain any ">" characters

#### Screenshots

![image](https://user-images.githubusercontent.com/50444010/116604826-ed508900-a92e-11eb-97c4-0060c9b974d9.png)

### Environment

<details><pre>
 - OS: Windows 10
 - Browser: Chrome
 - Version: 90.0.4430.93
</pre></details>

#### Output in Web Console

<details><pre>
  No Warning / Error output
</pre></details>

**Comment by joschahenningsen** [comment]
If I'm not mistaken I fixed this in #3429
