### ISSUE TITLE
Downloading PDF file gives you f.txt file 🐛 

### ISSUE THREAD

**Issue by ibhh** [ls1intum/ArTEMiS#333]
### Describe the bug
Instead of a PDF file you will be offered by Google Chrome a txt file with the name "f"

#### To Reproduce
1. Go to Artemis POM Lectures
2. Click on Lecture 1 Attachment with the slides
3. Try to save file to disk

#### Expected behavior
A PDF file with the correct name and the .pdf file extension

### Environment
<details><pre>
 - OS: [Win10 Home]
 - Browser [chrome]
 - Version [73]
</pre></details>

**Comment by krusche** [comment]
Good catch, the browser displays f.txt instead of the correct file name. This also happens in other browsers, e.g. Safari and on macOS
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/744067/56641306-639dbf00-6675-11e9-9a9a-bf7a57ef5f0c.png">

**Comment by rpadovani** [comment]
This is due the header `Content-Disposition` set by the server, that has value `inline;filename=f.txt`. I think we can safely drop the `filename=f.txt`, it shouldn't be necessary: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition
