### ISSUE TITLE
Creating a programming exercise causes in ISE

### ISSUE THREAD

**Issue by FrankeLukas** [ls1intum/Artemis#3338]
### Describe the bug

I get an "Internal Server Error" when trying to create a programming exercise with `develop` on TS1. Sadly the error message does not contain more detailed information.

Message:
```
{
	"type": "https://www.jhipster.tech/problem/problem-with-message",
	"title": "Internal Server Error",
	"status": 500,
	"path": "/api/programming-exercises/setup",
	"message": "error.http.500"
}
```

#### To Reproduce

Create a programming exercise. I tried Java and Haskell with the default settings.

**Comment by FrankeLukas** [comment]
This isn't present on `release-775`, but on `release-776` which includes the EDITOR role changes (which also touch the programming exercise setup). @florian-glombik can you have a look at this?

**Comment by FrankeLukas** [comment]
Apparently this is caused by not having an EDITOR group in your course. After adding the group it works again, sorry for the false alarm.

**Comment by FrankeLukas** [comment]
We want to find a mechanism to prevent this, maybe by automatically setting an EDITOR group (the previous TA group?) for courses without one, so re-opening.

**Comment by krusche** [comment]
We cannot automatically migrate all courses to have an editor group, we have to find a different solution. The group should be optional. So when checking for access rights and the group is null, we should instead check if the user has tutor rights in the course

**Comment by FrankeLukas** [comment]
Closing as resolved by https://github.com/ls1intum/Artemis/commit/7cefc716c5beed0b772ffba12b8541fab63e592b. (See https://github.com/ls1intum/Artemis/pull/3339#issuecomment-830678541)
