### ISSUE TITLE
🚀 undo

### ISSUE THREAD

**Issue by Silasoa** [ls1intum/ArTEMiS#335]
### Is your feature request related to a problem?
 
I'm frustrated taht I cannot undo/redo my changes in the Modeling Editor

### Describe the solution you'd like

 An undo/redo function

**Comment by krusche** [comment]
There are options for und/redo. Did you check the help? You can use Ctrl+Z (on macOS it would be Cmd+Z). On Chrome, they work quite well. Other browser might have problems. Please let us know which browser you use and provide more details.

Feel free to reopen the issue, in case this is not resolve yet or you want to provide more details.
