### ISSUE TITLE
Improve client server communication on plagiarism checks

### ISSUE THREAD

**Issue by joschahenningsen** [ls1intum/Artemis#3354]
### Is your feature request related to a problem?

Plagiarism checks currently get triggered via a rest request (`api/programming-exercises/:id/check-plagiarism`). In very large courses this request takes so long that it eventually times out. 

### Describe the solution you'd like

The client should subscribe to a websocket that notifies them with the results when the plagiarism detection is finished. This websocket is already partly implemented.

### Additional context

![yikes!](https://user-images.githubusercontent.com/44805696/116986486-20e43800-acce-11eb-8d5f-b84d4c144796.png)

**Comment by krusche** [comment]
We improved the performance and let the instructor know about the progress using web sockets
