### ISSUE TITLE
Instructions panel can't be scrolled to the bottom

### ISSUE THREAD

**Issue by Khalphion** [ls1intum/ArTEMiS#339]
### Describe the bug
The instructions panel of an exercise can't be scrolled until the bottom. Some parts of the class diagram can't be seen. 

![image](https://user-images.githubusercontent.com/10117554/56648135-0a3c8c80-6683-11e9-8ad5-b992748f210b.png)

![image](https://user-images.githubusercontent.com/10117554/56648379-83d47a80-6683-11e9-9b2c-e2c627cde4f8.png)

### Environment

<details><pre>
 - OS: macOS Mojave 10.14.3
 - Browser: Chrome 73.0.3683.86
 - Version: Artemis 3.0.0
</pre></details>

**Comment by thilo-behnke** [comment]
This is an issue with the way the editor is styled:
The build output component can overlay the instructions if the user has a small screen or resizes the components. I'll look into it.

**Comment by thilo-behnke** [comment]
https://github.com/ls1intum/ArTEMiS/pull/344

**Comment by thilo-behnke** [comment]
Resolved. @Khalphion Thanks for the report!
