### ISSUE TITLE
Add continuous code quality monitoring

### ISSUE THREAD

**Issue by muenchdo** [ls1intum/ArTEMiS#34]
Hey, great to see how development continues on this project!

I recently stumbled upon [Codacy](https://www.codacy.com/product), a tool for analyzing and monitoring code quality. Besides highlighting code quality issues, it also gives explanations why certain things are an issue, so it is also a great chance for all contributors to improve their skills.

How about trying it out on ArTEMiS? It's free for open source projects.

Cheers,
Dominik

**Comment by krusche** [comment]
We added this some time ago
