### ISSUE TITLE
Possible Race Condition in "Next Assessment"

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#3411]
### Describe the bug
We've recently run into the bug that two teaching assistants had to assess the same solution which lead to issues regarding the grading. After talking to @krusche the idea is that this behavior might be caused by a not handled race condition in the "Assess next solution" functionality. As you can see in the picture, you can see less dates than assessments. 

As this state could only be resolved by manually editing the Database, I've marked this bug as "priority:high".

**EDIT: @krusche gave me the information that the lock mechanism for complaints has been reworked in the recent past; maybe this mechanism can be used for the assess next solution feature as well**

#### To Reproduce

As this might be caused by a race condition, it's quite hard to reproduce.

#### Expected behavior

A Submission shall be assessed by only one teaching assistant 

#### Screenshots

![image](https://user-images.githubusercontent.com/22198798/117980197-ff212b80-b333-11eb-8fae-3380883407df.png)

### Environment
Artemis 4.12.1 (Gitlab/Jenkins)

**Comment by dfuchss** [comment]
@joschahenningsen do you have any idea about the details of the race condition :) ?

**Comment by joschahenningsen** [comment]
Thanks for pinging me, I kind of forgot about this. :smile: 
I'll work on it and keep you updated. Is this happening regularly?

**Comment by dfuchss** [comment]
Actually, that occurs from time to time (luckily not that often) and as it's possible to delete the results for a submission, the race condition is currently not that critical :)

**Comment by krusche** [comment]
@dfuchss was the issue fixed in the mean time?

**Comment by dfuchss** [comment]
@krusche I think it might be fixed (I didn't encountered the behavior in the last corrections). If it occurs again, I'll reopen the issue.
