### ISSUE TITLE
Email Notifications

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#3424]
### Is your feature request related to a problem?

It would be nice if Artemis would send Emails on certain events to its users (based on their role).

Important for us would be mails for the following events ..
(Student (S), Teaching Assistant (T), Instructor (I))

* T/I 
   * New Complaints / New More Feedback Requests

* T
  * Assessment Start (with information on due date, and amount of students to assess each ?)

* S
  * New Exercises available for the registered course
  * received a complaint response
  * A (maybe signed) confirmation that an exam has been submitted ?

Maybe a general daily summary for the instructors would be nice (open complaints, open feedback requests, state of assessments)

### Describe the solution you'd like

It would be nice if you could activate in the global config (not UI but conf files .. I think thats easier) that mails shall be sent to users (maybe it should be possible to enable and disable the sending of mails based on the categories mentioned above: Complaints/Feedback, Assessment Events, New Exercises)

### Describe alternatives you've considered

We also thought about an RSS feed or something similar, because we (and the students) aren't logged in every time .. but we think emails would be better ..

**Comment by dfuchss** [comment]
JFIY @LDAP @gstuer

**Comment by FlorianGlombik** [comment]
It would be good to include notifications for students when they have received a complaint response, especially for exams.
