### ISSUE TITLE
🐛 Error in the final points score

### ISSUE THREAD

**Issue by giuseppevalle** [ls1intum/ArTEMiS#343]
### Describe the bug
After finishing my exercise I got the score of 100%, but I can see in the end of the page 0 of 5 pts. I think I got the points anyway, but the value of the label is not correct. 

#### To Reproduce
1. Go to the exercises mainpage 
2. Click on the one named 'Map a model to code'
3. Scroll down to the Recent results

#### Expected behavior
I should see 5 of 5 pts

#### Screenshots
![image](https://user-images.githubusercontent.com/30870349/56665269-02441300-66aa-11e9-9fef-2f600397b99a.png)

### Environment
<details><pre>
 - OS: macOS Mojave 
 - Browser: chrome
 - Version 73.0.3683.86 
</pre></details>

#### Output in Web Console

<details><pre>
Failed to load resource: the server responded with a status of 500 ()
</pre></details>

**Comment by maximilianmeier** [comment]
fixed in #346
