### ISSUE TITLE
[database-change] Reusable knowledge for assessment suggestions

### ISSUE THREAD

**Issue by argertboja** [ls1intum/Artemis#3441]
This issue tracks required database changes to store the link between the imported exercise and the knowledge captured within the old submissions of the parent exercise.

## Motivation
In order to improve the automatic assessment of text exercises, we need to establish a connection between the current exercise and the submissions of the one from which it was imported. This import relationship will help in using old assessments' feedback for the automatic assessment of text exercises.

## Solution
In order to be able to reuse the knowledge captured within exercises, we need to remove the `OneToOne` relationship between the text block and the cluster so that a text block can now be part of multiple clusters. In this way, even if the parent exercise is deleted, we can still make use of the knowledge captured within the submissions of the parent exercise. However, in case the instructors would like to break this connection to old submissions they will be able to do so through a button in the FE which will remove the connection between the exercise and the knowledge table. The UML below describes an overview of this solution where we show a conceptual model which will be used not only for text exercises but also for modeling exercises. However, at this stage, we will only concentrate on text exercises. This solution also enables us to use the knowledge created in multiple Artemis instances as we can export the knowledge for text exercises by serializing all text blocks and feedbacks related to a knowledge object into a JSON file and transfer it to another instance. However, this will be part of future work.
![UML class](https://user-images.githubusercontent.com/17032718/123009025-40d5d500-d3bc-11eb-8f36-469b03aac49c.png)

## Alternative Solution
An alternative solution would be to store only the parent exercise ID to the exercise table however, this solution would be limited as also denoted in the discussion below. The UML representation of this approach is described in the figure below:
![RecursiveUML](https://user-images.githubusercontent.com/17032718/116379648-825e5f80-a813-11eb-909f-9d3a8bdde341.PNG)

## Implementation
We will introduce a new table `assessment_knowledge` which will store only an `id` value. This value will be used to connect to each other the tables `exercise`, `text_block`, and `feedback` by storing this `knowledge_id` in each specific table. Furthermore, as a text block can now be part of multiple clusters, we will introduce a new table `cluster_to_block` which will have an `id`, `exercise_id`, `cluser_id`, and `block_id`columns  and hence enabling a `ManyToMany` relationship where each cluster can have multiple blocks and each block can belong to multiple clusters. The Database diagram below shows an overview of how these tables will look like. Please note that for simplicity, all columns not related to this issue are neglected in the diagram below:  
![db](https://user-images.githubusercontent.com/17032718/123009305-bf327700-d3bc-11eb-8f00-cabd89121733.PNG)

**Comment by jpbernius** [comment]
I am in favor of the `parent` relationship.

I would propose to implement the relationship as part of the `Exercise` class and also implement the relationship for all exercise types.

We need to be careful that deletion of exercises does not cause any trouble, e.g., when deleting an exercise it should not delete the parent exercise and when deleting the parent, it should not delete the imported exercise.

**Comment by krusche** [comment]
Is this approach not limited? What happens if multiple exercises share the same knowledge about which aspects of a solution are correct and which are wrong?
Also it would limit the implementation to just one Artemis instance, but in the future we would like to be able to share exercises and knowledge between multiple Artemis instances.

Would it not make more sense to find a way to store the knowledge exercise independently and then link or import the knowledge to the new exercise? Right now the knowledge is "hidden" in submissions and assessments, I suggest we think about storing it exercise independently (potentially in the file system) and anonymized

Also how would you support a deletion of the link in case the problem statement is changed and the link is not valid any more? (A wrong link could be problematic!)

I think we should come up with a better solution here!

**Comment by argertboja** [comment]
@krusche After discussing with @jpbernius your feedback, I have updated the issue described above. 

We have introduced two new tables which hopefully address all your comments. Also, we have added a better UML and Database diagram which will describe in more detail the approach to solve this issue. 

Please let us know in case there is any other problem so that I can start the implementation of this approach as soon as possible.

> Is this approach not limited? What happens if multiple exercises share the same knowledge about which aspects of a solution are correct and which are wrong?
> Also it would limit the implementation to just one Artemis instance, but in the future we would like to be able to share exercises and knowledge between multiple Artemis instances.
> 
> Would it not make more sense to find a way to store the knowledge exercise independently and then link or import the knowledge to the new exercise? Right now the knowledge is "hidden" in submissions and assessments, I suggest we think about storing it exercise independently (potentially in the file system) and anonymized
> 
> Also how would you support a deletion of the link in case the problem statement is changed and the link is not valid any more? (A wrong link could be problematic!)
> 
> I think we should come up with a better solution here!

**Comment by krusche** [comment]
This change was approved, so we can close the issue
