### ISSUE TITLE
Back to main course page button

### ISSUE THREAD

**Issue by J-MR-T** [ls1intum/Artemis#3447]
### Is your feature request related to a problem?
I'm very often working on a course and want to get back to the main *course* page quickly, but can't by simply pressing back multiple times, because sometimes it simply messes Artemis up, other times I'm 3 menu's deep and it's quite hard to get back to where I want to be.

### Describe the solution you'd like
My current 'workaround' for this is simply pressing the big Artemis logo to get back to the overview of all courses and then select the course I'm currently working on. That however is quite tedious, what I would like is a button, maybe below the main logo, which brings you back to the main page of the course that you are currently working on (so the course to which the current page/lecture/excercise belongs).
The placement below the main logo is probably not optimal, but I can't currently think of another good place to put said button.

### Describe alternatives you've considered
Well as it's not a huge problem it is arguable if this really needs to be fixed, so the alternative solution would be to do nothing, but because I personally (and I suspect others as well) do this so often it would really shave a lot of time of my Artemis browsing experience.

### Additional context
n/a

**Comment by FrankeLukas** [comment]
I'm currently working on enabling breadcrumbs for the students view, which should fix this.
