### ISSUE TITLE
Better Names for Weight / Bonus Multiplier / Bonus Points

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#3486]
### Is your feature request related to a problem?
We should find better names for the Weight / Bonus Multiplier / Bonus Points columns in the grading overview.

Maybe something like:
`Weight, Weight Multiplier, Summand Points` ?

Maybe that would make it easier to understand, what the different parts of the Grading are doing :)

As far as I understood, the Points of a test case are calculated by:

`PointsOfTest(weight, multiplier, additional_points) := PointsByWeightAndTask(task, weight) * multiplier + summand_points`

**Comment by dfuchss** [comment]
@krusche is the formula as stated above correct?

**Comment by dfuchss** [comment]
Maybe it could help to simply write the formula on the page (and of course replace the name "bonus" :) )

**Comment by ShivamTyagi12345** [comment]
hey can i take this isssue to work on as a part of 24 pull request

**Comment by dfuchss** [comment]
Sorry but I don't get the question. What would you like to ask ?

**Comment by krusche** [comment]
I guess @ShivamTyagi12345 refers to https://24pullrequests.com/

**Comment by dfuchss** [comment]
Ah, I did not know this event :) But feel free to create a proposal & PR

**Comment by dangcosta** [comment]
Hi @dfuchss , I would like to work on this issue if it hasn't be solved yet (which I assumed considering that the issue is still open). One thing isn't clear to me though. In which class is PointsOfTest method mentioned above? I have checked the grading resources classes and I could not find it.

**Comment by dfuchss** [comment]
The method does not exist. I've just used it to explain my current understanding of the parameters. The position of these names is the grading view of Artemis.
