### ISSUE TITLE
ESC-Characters are not correctly (re-)encoded when updating config.xml in Jenkins

### ISSUE THREAD

**Issue by Wallenstein61** [ls1intum/Artemis#3499]
Context is an Artemis-Installation with Jenkins (and GitLab).
### Describe the bug
The standard jenkins template for C-courses contains an encoded ESC-Character (`&#x1b`) in the snippet below:
```
  post {
            cleanup {
                sh '''
                   sed -i &apos;s/&#x1b;//g&apos; test-reports/tests-results.xml&#xd;
                   sed -i &apos;s/&lt;skipped/&lt;error/g&apos; test-reports/tests-results.xml&#xd;
                   sed -i &apos;s/&lt;\/skipped&gt;/&lt;\/error&gt;/g&apos; test-reports/tests-results.xml&#xd;
                   mv test-reports results
                   '''
                sendTestResults credentialsId: '#jenkinsNotificationToken', notificationUrl: '#notificationsUrl'
                cleanWs()
            }
        }
```
In `JenkinsJobPermissionsService.addInstructorAndEditorAndTAPermissionsToUsersForJob` the config.xml-template is loaded correctly from Jenkins and parsed into a  `org.jsoup.nodes.Document`.

After updateing it with permissions, it is written back to Jenkins as a String. This string however contains the ESC-character as unencoded character:
![image](https://user-images.githubusercontent.com/18215713/119682397-2521f200-be43-11eb-931a-8db296f09980.png)

This causes an exeption in Jenkins
```
Caught unhandled exception with ID a57c7285-d280-427c-8234-9454a32c903a
javax.xml.transform.TransformerException: org.xml.sax.SAXParseException; lineNumber: 135; columnNumber: 35; An invalid XML character (Unicode: 0x1b) was found in the element content of the document.
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:740)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:343)
	at jenkins.util.xml.XMLUtils._transform(XMLUtils.java:209)
	at jenkins.util.xml.XMLUtils.safeTransform(XMLUtils.java:81)
```

#### To Reproduce

Use an Artemis-Installation with Jenkins (and GitLab).

1. SetUp a new C-Programming Exercise
2. Click on 'Save'
3. See error
   - in User Interface
   - in Jenkins Logfiles

#### Expected behavior
The XML-String is decoded and re-encoded according to the XML-standard.

Our workaround is, to use a different template (without ESC-characters).

If you must work with the built-in template and C-Exercises this is a severe problem.
#### Screenshots
 
See above

### Environment
<details><pre>
 - OS: Artemis Windows, Jenkins Linux
 - Browser: Brave
 - Version: Artemis 4.12.0
</pre></details>

#### Additional context
Not relevant

#### Output in Web Console
Not relevant

**Comment by b-fein** [comment]
This looks like it is the same issue as in #3484 and is going to be resolved by #3491.

**Comment by Wallenstein61** [comment]
From #3491
> I looked into the issue and the reason the exception is happening is because the template Jenkinsfile contains the &#x1b; code on line 87 which cannot be read by Jenkins: sed -i 's/&#x1b;//g' test-reports/tests-results.xml. It looks like it's trying to replace ESC characters with an empty string. I'm not too sure why it's there and how we can encode the ESC so that it's readable in Jenkins but I would assume that we could just remove the line?

Just my two cents from the analysis of #3499:

The problem is not the XML-file. It contains valid XML. The Problem is in the source code that reads back the `config.xml` from jenkins in `JenkinsJobService.getJobConfig`. It reads it correctly into an `org.jsoup.nodes.Document`, however seems to set the output-Options incorrectly. Thus serializing it back with `doc.toString()` returns a faulty XML with an unencoded ESC-character.

Thus, just correcting the jenkins template will not guarantee that the problem is solved for any other templates.
Michael

**Comment by b-fein** [comment]
Reopening as the issue with escaping characters is not limited to ESC but could also be problematic in general as discussed in #3491,

**Comment by Wallenstein61** [comment]
As pointed out in #3491 the bug is not fixed. Only some imminent symptom is cured. It may come back, as soon as a user includes another specific entity in his specific JenkinsFile.

The problem is, that JSoup does not claim to be a correct XML-parser. It is mainly for HTML. Thus `org.jsoup.nodes.Document.toString()` does not generate valid XML-code. I dived deep into the implementation and finally down in `org.jsoup.nodes.Entities.escape` (line 162) does not escape all code points correctly as XML-entities (may be also not for HTML, but I did not check this).

I would recommend to step back to a classic `javax.xml.parsers.DocumentBuilder` and a `javax.xml.transform.TransformerFactory`.

I wrote a short test file to demonstrate the problem, and also the workaround:

```java
package at.ac.uibk.jsoup.tests;

import java.io.IOException;
import java.io.StringReader;
import java.io.StringWriter;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;

import org.jsoup.Jsoup;
import org.jsoup.parser.Parser;
import org.w3c.dom.Document;
import org.xml.sax.InputSource;
import org.xml.sax.SAXException;

public class JSoupTest {

	final static String originalXML = "<?xml version=\"1.1\" encoding=\"UTF-8\"?>\r\n"
			+ "<SomeText>This is an escaped escape-character: &#x1b;</SomeText>";

	public static void main(String[] args)
			throws SAXException, IOException, ParserConfigurationException, TransformerException {

		parseXMLWithJSoup();

		parseXMLInternal();

	}

	private static void parseXMLWithJSoup() {
		System.out.println();
		System.out.println("------------------- incorrect unparsing with JSOUP ------------------- ");
		System.out.println();
		System.out.println("original XML with escaped escape-character:\n  " + originalXML);
		org.jsoup.nodes.Document document = Jsoup.parse(originalXML, "", Parser.xmlParser());
		document.outputSettings().syntax(org.jsoup.nodes.Document.OutputSettings.Syntax.xml).indentAmount(2)
				.prettyPrint(true);

		String returnedXMLFromJSoupParser = document.toString();
		System.out.println();
		System.out.println("returned XMLFromJSoupParser No escaped escape character: \n  " + returnedXMLFromJSoupParser);

		org.jsoup.nodes.Document document2 = Jsoup.parse(returnedXMLFromJSoupParser, "", Parser.xmlParser());
		document2.outputSettings().syntax(org.jsoup.nodes.Document.OutputSettings.Syntax.xml).indentAmount(2)
				.prettyPrint(true);

		String returned2ndXMLFromJSoupParser = document.toString();
		System.out.println();
		System.out.println("returned reparsed result XMLFromJSoupParser: " + returned2ndXMLFromJSoupParser);
	}

	public static void parseXMLInternal()
			throws SAXException, IOException, ParserConfigurationException, TransformerException {
		System.out.println();
		System.out.println("----------------------- correct unparsing ---------------------- ");
		System.out.println();
		System.out.println("original XML with escaped escape-character:\n  " + originalXML);
		DocumentBuilder builder = DocumentBuilderFactory.newInstance().newDocumentBuilder();

		InputSource input = new InputSource(new StringReader(originalXML));
		Document doc = builder.parse(input);

		TransformerFactory tf = TransformerFactory.newInstance();
		Transformer trans = tf.newTransformer();
		StringWriter sw = new StringWriter();
		trans.transform(new DOMSource(doc), new StreamResult(sw));

		String returnedXMLFromSaxParser = sw.toString();

		System.out.println();
		System.out.println("returned XML From SAX Parser/Transformer: \n" + returnedXMLFromSaxParser);

	}

}

```

Best regards
Michael
