### ISSUE TITLE
Change "Submit" button text to something else for programming exercises 

### ISSUE THREAD

**Issue by Khalphion** [ls1intum/ArTEMiS#350]
### Is your feature request related to a problem?
Students are confused of the submit button's double semantic. In all exercises except programming, "submit" means "I can't change my submission after that".

### Describe the solution you'd like
Choose a different label for the button, e.g. "Compile and run".

**Comment by krusche** [comment]
We intentionally changed it to Submit a short time ago to make the UI consistent with other exercises. We will add tooltips to the submit buttons to make it more clear what they mean.
