### ISSUE TITLE
Grading instructions are only applied to the whole submission

### ISSUE THREAD

**Issue by tobias-lippert** [ls1intum/Artemis#3534]
### Describe the bug
When assessing a text exercise in the Assessment editor on Artemis by using grading instructions the whole text is automatically selected for one grading instruction instead of only one sentence.
#### To Reproduce

I was only able to reproduce this in the EIST 21 course not in the test course at the Artemis production server.
1. Go to the assessment dashboard of EIST 21 and try to assess a text exercise submission with grading instructions by dragging and dropping a  grading instruction to the submission. 
5. See that the whole submission is treated as one text block.
6. See that regardless of what you select the grading instruction is applied to the all parts of the submission without a grading instruction.

#### Expected behavior
The grading instruction should only be applied to one sentence as it was in previous versions.

### Environment

<details><pre>
 - OS: Windows 10
 - Browser : Chrome
 - Version: 91.0.4472.77 64 bit
</pre></details>

**Comment by julian-christl** [comment]
@jpbernius I expect this issue was related to Athene, wasn't it? Was this resolved?

**Comment by jpbernius** [comment]
When Athene is enabled, we employ a different strategy to identify segments (see [Bernius et al.](https://brn.is/ecsee20)) compared to the sentence strategy used otherwise.
This might result in the student answer being determined as one single segment (or block).

Generally speaking, this report sounds like intended behaviour.

**Comment by tobias-lippert** [comment]
So, the tutors cannot expect that this behavior changes in the near future?
Is there any workaround available besides manually selecting the desired text block? Manually selecting each sentence is not really beneficial for the grading workflow of the tutors.
