### ISSUE TITLE
Editors can click on course scores link but have no permission for the destination

### ISSUE THREAD

**Issue by MaisiKoleni** [ls1intum/Artemis#3537]
When I am an "Editor" of a course, I can view the course in the course management (`/course-management/<ID>`) and get some statistics. Among others, this includes the "Average Student Score":
![image](https://user-images.githubusercontent.com/11130248/120999266-37782600-c789-11eb-81d0-d6e8e15307dd.png)

The text links to the `/course-management/<ID>/scores` page, which I cannot access. I get an empty page and 403's.

This might be the case for the "Tutor" role as well.

**Comment by DanielKainz** [comment]
I logged in as a tutor and encountered the same issues you mentioned. 
Should editors and tutors get the permissions to view this page?
