### ISSUE TITLE
🚀 Enable HTTP2

### ISSUE THREAD

**Issue by rpadovani** [ls1intum/ArTEMiS#357]
HTTP2 is now a [widely adopted technology](https://caniuse.com/#feat=http2), it would be cool to enable it. It has some advantages:

- **Single Connection**. Only one connection to the server is used to load a website, and that connection remains open as long as the website is open. This reduces the number of round trips needed to set up multiple TCP connections.
- **Header Compression.** HTTP/2 uses HPACK compressions, which reduces overhead. Many headers were sent with the same values in every request in HTTP/1.1.
- **Multiplexing**. Multiple requests are allowed at the same time, on the same connection. Previously, with HTTP/1.1, each transfer would have to wait for other transfers to complete

There are two steps to enable it:

- in `application_prod.yml` and `application_dev.yml`, the parameter `jhipster.http.version` has to be changed to `V_2_0`
- the nginx configuration has to be updated to support http2. It should be as easy as adding `http2` to the SSL listener, something like `listen 443 ssl http2;`

**Comment by krusche** [comment]
We use it already :-) Have a look into the chrome console when connecting to test or production server, it is handled by nginx, therefore there is no configuration in the Artemis Server any more. I am not sure how internal communication between nginx and Artemis is handled and whether we use http2 here or not. Maybe @jpbernius can answer this...

**Comment by rpadovani** [comment]
Uh, it is true, I didn't double check, I just seen that in the config file of Jhipster is disabled :)

**Comment by jpbernius** [comment]
I will need to check if ArTEMiS <-> Nginx communication is using http 2. Thanks for pointing this out @rpadovani!

**Comment by krusche** [comment]
@jpbernius What is the status of this issue?

**Comment by jpbernius** [comment]
Both jhipster and nginx are configured to use http2.
