### ISSUE TITLE
Invisible text when grading text exercises

### ISSUE THREAD

**Issue by gereonelvers** [ls1intum/Artemis#3587]
### Bug Description
I'm a tutor grading a text exercise. During assessment, the submitted text for some submissions was partially hidden (not visible nor selectable) unless the tutor used the alt-button to select custom text.
After highlighting the previously hidden text and adding a grading, the text remains visible (even when revisiting the assessment later). If the tutor does not add a grading to the text, however, it disappears again after letting go of the alt-button.

#### To Reproduce
While the issue does not appear to be isolated to a single exercise (we observed it on both H06E03 as well as H06E04 in this semester's EIST course), it is not reproducible reliably and only seems to happen relatively rarely.
1. Select a text exercise in the assessment dashboard
2. Start assessment of a new submission by selecting "Start new assessment"

#### Expected behavior
All text from all text submissions should be visible/selectable at all times.

### Environment
<details><pre>
 - OS: Windows 10 64-Bit (Version 2004)
 - Browser: Chrome 91.0, Firefox 89.0.1
</pre></details>

#### Additional context
Screen resolution does not appear to be a factor, as the issue persisted on both a 1080p as well as 1440p screen. As the issue was reported by multiple tutors independently from each other, it does seem to be somewhat widespread (and especially not isolated to a single user).

**Comment by gereonelvers** [comment]
I've managed to reproduce the issue on video [here](https://www.youtube.com/watch?v=sj7Txs2p6Ks).
I apologize for the quick and dirty censoring of the problem statement - as this occured in this years EIST course, which is still in-progress, I did not want to publicly share grading instructions or the example solution.

**Comment by ge65cer** [comment]
There have been changes to the text assessment feature, can you check if this is still a problem?

**Comment by gereonelvers** [comment]
Unfortunately I no longer have access to the course as I am not working as a tutor anymore. As I don't have my own Artemis instance up and running, I'm also unable to test it myself. If the issue doesn't come up in this semesters courses, I'd assume it to be fixed though.
