### ISSUE TITLE
Check Plagiarism Similiarity Range [0-100]

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#3601]
### Is your feature request related to a problem?

In the past we encountered plagiarism with a score less then 50%.
Therefore, it would be good, if the range of the "Similarity Threshold in %" could be set to a value within [0, 100] instead of [50,100] for the Check Plagiarism View.

### Describe the solution you'd like

The value for "Similarity Threshold in %" should be configurable as [0, 100].

**Comment by krusche** [comment]
Yes, we can do that. We have limited the results to 500, so the previous performance bottleneck (that led to the decision to 50%) should not be problematic any more
