### ISSUE TITLE
Optimize assessment of model submissions for keyboard

### ISSUE THREAD

**Issue by Khalphion** [ls1intum/ArTEMiS#362]
### Is your feature request related to a problem?
Since I have many model submissions to assess, I'd like to be as efficient as possible. As a power keyboard user, I think all the clicking slows me down in my work and is kind of tedious.

### Describe the solution you'd like
When I double click a class to assess it...
- [ ] pre-focus the first input element, so I can use the tab key to navigate through the fields
- [ ] I'd like to have a "go to next element" button at the end of the popover, so I can use the tab key (+enter) to switch to the next class quickly

**Comment by krusche** [comment]
@jwilland-tum this is related to Apollon. Could we support something like this easily?

**Comment by jwilland-tum** [comment]
Thank you for your request. PR https://github.com/ls1intum/ArTEMiS/pull/442 includes the requested features.
When you open a popover to provide an assessment for an element, the first input field will be focused automatically. At the bottom of the popover, we added a button to assess the next element. With this button, you can iterate through root elements (not each individual child). Apparently, there seems to be a bug in the underlying technology if you use the `enter`-key to press the button. Then, in the next visible popover, the first input field is not focused correctly. For now, we suggest using the `space`-key to press the 'Next Assessment'-button until we find a workaround to make the `enter`-key work correctly.
