### ISSUE TITLE
Modelling editor: Always show icon next to elements with feedback

### ISSUE THREAD

**Issue by Khalphion** [ls1intum/ArTEMiS#363]
### Is your feature request related to a problem?
As a tutor, I sometimes think a certain property in a model should be different (e.g. naming, etc.) therefore I give some feedback. However, that might be just a hint and the student's answer isn't necessarily wrong, neither it is correct, therefore I don't give points. 

With 0 points, no tick nor cross icon is displayed, so the student might not see my feedback.

![image](https://user-images.githubusercontent.com/10117554/56829503-2fd4bc00-6864-11e9-87ab-e54eb3b76aad.png)

![image](https://user-images.githubusercontent.com/10117554/56829522-3ebb6e80-6864-11e9-9db4-edf6dd830b0a.png)

### Describe the solution you'd like
Display an "i" icon next to the property similar to the tick and cross for wrong answers. A dropdown selector where I could select an icon would be even better i.e. to attach contextual visual feedback (question mark for unclear, unsatisfying model properties, an "i" icon for general feedback, etc.)

![image](https://user-images.githubusercontent.com/10117554/56829755-e769ce00-6864-11e9-95b8-cbcdf28a3173.png)

**Comment by SiggZ** [comment]
Thanks for the feature request.
With https://github.com/ls1intum/ArTEMiS/pull/416 neutral feedback is highlighted by an exclamation mark symbol.
