### ISSUE TITLE
[Feature] Define mandatory tests for programming excersises

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#3641]
### Is your feature request related to a problem?

It would be nice if one could define mandatory tests for programming tasks that have to be fulfilled in order for a submission to be graded at all.
Assignments that do not pass such a test should automatically be graded with 0%.
This feature would make it possible to define minimum requirements.

The goal here is to make it clear to students that submissions usually have to meet minimum requirements.

### Describe the solution you'd like

Besides Always, After Due Date, and Never add a forth possible visibility to a test case : "Mandatory"

Tests marked as mandatory should always be visible to the students, but if they fail, no points shall be given by automatic assessment.

**Comment by b-fein** [comment]
We’ve thought about such a feature as well as that was possible in Praktomat.

I’m not sure if it should be implemented as an additional visibility value, however. I think it should be a separate attribute that therefore receives a dedicated checkbox per testcase on the ‘Configure Grading’ page. Of course only always visible tests should be possible to be mandatory, still.


For students it should be obvious which testcases are mandatory and what implications that has for them. That includes at least:
- In the task description tests which are mandatory should be highlighted in an obvious way (probably with some hover-over tooltip with an explanation).
- A submission that failed mandatory checks should include a message with some variation of ‘Your submission received 0% because a mandatory test was not successful.’

**Comment by dfuchss** [comment]
@b-fein actually, I would be also fine with a checkbox (I only thought that a further entry in the visibilities would be the easiest :) )

**Comment by JohannesStoehr** [comment]
We also had some problems with tests that would pass for an empty submission, but could fail when the student tries to implement the actual exercise (for example public variables, but for example also sorting an empty list and other similar edge cases).
Maybe it would be another solution to add tests that do not grant any points, when they pass, but rather deduct points when they are failing. This would also allow students to still get some points, when they only manage to solve a part of the exercise and not all minimal requirements

**Comment by dfuchss** [comment]
Typically, we define mandatory tests for existence of classes or basic checkstyle rules. If one of them breaks, you will not get any point.  I think your proposal would also be a solution for that case ("Maybe it would be another solution to add tests that do not grant any points, when they pass, but rather deduct points when they are failing") but I think Artemis provides only positive feedback (only points, no negative points) ?

**Comment by MaisiKoleni** [comment]
I think Artemis "sequential test runs" are pretty close to what you have in mind. As far as I know, whey were created for a similar reason. You could start there and then implement test cases for both stages as you like.

Negative points were theoretically possible, but didn't work. A test case would then deduct points if it succeeds, but you would see success in the UI and students could negative scores. So, I implemented checks that don't allow negative multipliers. I aggree that such deduction features would be useful, though.

**Comment by dfuchss** [comment]
Thanks a lot @MaisiKoleni ! We will have a look at the sequential test run feature .

**Comment by dfuchss** [comment]
@MaisiKoleni I think the sequential test runs are feasible for our problem.

Therefore, I think this feature request might be closed.

@b-fein do you think the sequential test runs are also feasible for you?

**Comment by b-fein** [comment]
We’ve structured our Jenkins pipeline in a way that it executes only some tests first and fails early without executing the rest (so it probably works similar to the sequential test runs). Therefore, there is no immediate need for us to integrate such a feature directly into Artemis.

It’s fine by me to close this issue, then.

**Comment by dfuchss** [comment]
Perfect. Then I'll close this issue for now. @ anyone feel free to re-open iff needed :)
