### ISSUE TITLE
🐛 Statistics: archived and missed points are switched

### ISSUE THREAD

**Issue by JoejoeSt** [ls1intum/ArTEMiS#365]
### Describe the bug
The overlay of the diagram in the statistics section shows the wrong points. The points for the archived and missed points are switched. 

#### To Reproduce
1. Go to statistics page
2. hover with the mouse over one of the bars in the diagram

#### Expected behavior
The points should be in the correct order

#### Screenshots
![IMG_0133](https://user-images.githubusercontent.com/38322605/56845934-ee2a2c80-68c8-11e9-8e1b-3ff2af0e825d.png)

### Environment
<details><pre>
 - OS: MacOS
 - Browser Safari
</pre></details>

**Comment by maximilianmeier** [comment]
#366

**Comment by BernhoferM** [comment]
This bug still seems to persist.
Though only for the programming exercises' bars, not the quizzes' bars.

OS: Windows 10
Browser: Firefox
