### ISSUE TITLE
New Artemis Logo not clearly recognizable in Light Mode

### ISSUE THREAD

**Issue by KiraNickel** [ls1intum/Artemis#3658]
### Describe the bug

In Chrome's light mode, the white part of the Artemis logo at the top blends completely into the background (as shown in the screenshot)

### To Reproduce

1. Open Artemis in Chrome (Light mode)
2. Select the Artemis tab at the top
3. See that the background color of the tab and the light color of the Artemis logo are the same

### Expected behavior

Maybe you could add a different color (like an Offwhite that is different from the browser white) for the light mode or set the logo against a darker background.

### Screenshots

![grafik](https://user-images.githubusercontent.com/69356806/123863833-57cf7680-d92a-11eb-9d77-4bc055d30ee3.png)

### What browsers are you seeing the problem on?

Chrome

**Comment by simon300000** [comment]
Same issue in Safari
<img width="106" alt="image" src="https://user-images.githubusercontent.com/12656264/124047824-88590280-da47-11eb-872e-20fd673ba8a5.png">

**Comment by MDK5** [comment]
And in Firefox (Only if the tab is selected):
![grafik](https://user-images.githubusercontent.com/61357727/124489999-e40ded80-ddb1-11eb-9460-5019f65aa12d.png)
