### ISSUE TITLE
Remove page scroll on save

### ISSUE THREAD

**Issue by N0W0RK** [ls1intum/Artemis#3680]
### Is your feature request related to a problem?

When working on modelling exercises, my progress gets periodically saved. The saving is indicated by a green bar on top of the modelling window. When the bar is shown, the page moves down by the width of the bar. This moves the modelling canvas and leads to frustration when connecting elements.

### Describe the solution you'd like

The saving could either be indicated by an element that does not increase page space above the modelling window or the space for the save bar is already allocated and the bar is just made visible.

### Additional context

![grafik](https://user-images.githubusercontent.com/22464684/124445156-96788d00-dd7f-11eb-9629-24298c10a53e.png)
![grafik](https://user-images.githubusercontent.com/22464684/124445257-af813e00-dd7f-11eb-95ee-81700ceb1302.png)

**Comment by ge65cer** [comment]
This issue has been addressed.

![Screenshot 2022-10-18 at 20-26-27 Modeling Exercises](https://user-images.githubusercontent.com/102237363/196513849-4b2072c5-98f9-4a31-b536-20521710a79d.png)
