### ISSUE TITLE
🚀 General assessment feedback textarea 

### ISSUE THREAD

**Issue by Khalphion** [ls1intum/ArTEMiS#369]
### Is your feature request related to a problem?
As a tutor, I sometimes like to give some general feedback that does not relate to a specific answer of a submission. (e.g. style notes, naming conventions, etc.)

### Describe the solution you'd like
I'd like to have a <textarea> below my assessment screen where I could enter some general feedback.

**Comment by SiggZ** [comment]
Thank you for your feature request. 
https://github.com/ls1intum/ArTEMiS/pull/432 introduces a "General Feedback" text field to the assessment of text and modeling submissions.
