### ISSUE TITLE
Students should be given read-only rights to their submission again for reviewing.

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#3690]
### Describe the bug

Students should be given read-only rights to their submission again for reviewing.
But access for students is not given

### To Reproduce

1. Create a exam with programming exercise.
2. Try to access your repo as student in the Review Phase
3. Repo in GitLab is accessible for student

### Expected behavior

During Review a Student shall have ro access to the repository or shall see the editor in Artemis for reviewing the Assessment.

### What browsers are you seeing the problem on?

Firefox

**Comment by JohannesStoehr** [comment]
I could not recreate the bug using our test server that uses GitLab.
Where some exercises created right before the release of the exam or did some students have problems accessing the repositories during the exam?

Or do you have any other information?

**Comment by dfuchss** [comment]
I'll check it again and try to get more information.

**Comment by dfuchss** [comment]
Ok, the students can't access the repository while the exam either:
![image](https://user-images.githubusercontent.com/22198798/124881379-8fe05480-dfcf-11eb-8e40-82b4915d6b1d.png)

In addition, the instructor (which I've added after creating the exam, because I'm also an admin) is not granted access to the repository either.

The task is configured that offline IDE should be accessible:
![image](https://user-images.githubusercontent.com/22198798/124881588-d0d86900-dfcf-11eb-83f1-18dd0df738a4.png)

**Comment by dfuchss** [comment]
I've tested the functionality with small time deltas .. this bug seems to be resolved in #3679

**Comment by dfuchss** [comment]
I'll link it to the PR as I encounter no bug on the feature branch :)

**Comment by krusche** [comment]
The problem is the scheduling. In a testing scenario: If you create the exercise and prepare the exercise start too shortly before the exam, it won't work. In reality, those actions are typically done way before the exam starts and therefore work correctly.
