### ISSUE TITLE
Breadcrumb Programming Exercises in Exams

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#3693]
### Describe the bug

In Exam Management, for Exercise groups and there Configure Grading the breadcrumb path is replaced by Exercise which is misleading.__

### To Reproduce

1. Create an exam with programming exercise 
2. Edit the grading of the exercise 
3. Look at the breadcrumbs (which point to exercises instead of exams)

### Expected behavior

The breadcrumbs shall include the exam not the exercises

### What browsers are you seeing the problem on?

Firefox

**Comment by krusche** [comment]
@FrankeLukas could you please have a look?
