### ISSUE TITLE
Participation Details broken

### ISSUE THREAD

**Issue by lukasalperowitz** [ls1intum/ArTEMiS#37]
<img width="360" alt="bildschirmfoto_2017-10-21_um_19 42 47_720" src="https://user-images.githubusercontent.com/1837922/31854472-37c46bd6-b69a-11e7-9876-dbdc9ad90b59.png">

Steps to reproduce:

* Select an Exercise
* Select the Participations

Expected: Timestamps etc. are shown
Actual: Only template placeholders are shown

**Comment by krusche** [comment]
This issue is already fixed. Thanks for reporting!
