### ISSUE TITLE
Back-button in the lecture components

### ISSUE THREAD

**Issue by DomiAb** [ls1intum/Artemis#3717]
### Is your feature request related to a problem?

When you're on a lecture, e.g. for downloading the slides, you can't easily get back to the overview of this course.

### Describe the solution you'd like

When you're on a programming exercise, then there's an arrow pointing to the left, which brings you back to the overview of the course. Just copy this idea (and the implementation lul) also for the lecture content.
Thanks

**Comment by krusche** [comment]
You can use the back button of the browser. We want to get rid of all Artemis back buttons in the future.
