### ISSUE TITLE
font-weight changes when going into text editor

### ISSUE THREAD

**Issue by SuspiciousActivity** [ls1intum/Artemis#3736]
### Describe the bug

In a text editor, when clicking the top left Artemis logo, the font-weight of everything course related on the main page changes. Take a look at the screenshots below.

### To Reproduce

1. Go to the Artemis main page
2. Navigate to a text assignment and open it
3. Click the Artemis logo on the top left
4. Text on the main page is now more bold

### Expected behavior

The font-weight should not change on the main page.

### Screenshots

Before and after. There is a lot more happening than the more bold percentage, make sure to open the images in seperate tabs and switch between them.
![Screenshot_1](https://user-images.githubusercontent.com/38253929/125341109-8bab9280-e353-11eb-8354-922a81922632.png)
![Screenshot_2](https://user-images.githubusercontent.com/38253929/125341111-8cdcbf80-e353-11eb-8ba2-7627bcba5dd5.png)

**_The following is in Firefox only!_** Before and after. The title also has weird formatting:
![Screenshot_3](https://user-images.githubusercontent.com/38253929/125341712-3a4fd300-e354-11eb-8da8-9ba03668789b.png)
![Screenshot_4](https://user-images.githubusercontent.com/38253929/125341719-3c199680-e354-11eb-9d42-5a2f040b6f85.png)

The latter probably has to do something with the fact that in Chrome the title and points text is more bold than in Firefox (which is probably another bug).

### What browsers are you seeing the problem on?

Chrome, Firefox

**Comment by FlorianGlombik** [comment]
Findings from @MDK5 and me when trying to fix the issue:
1. The issue does currently seem to arise from the import `@import 'src/main/webapp/content/scss/artemis-variables';`
   Within this file the following part seems to be problematic:
```
// Headings:
// Ensure that we use bootstrap font weight for components that import 'artemis-variables'
h6,
h5,
h4,
h3,
h2,
h1 {
    font-weight: 500;
}
```
2. When visiting components that use the import ``@import 'src/main/webapp/content/scss/artemis-variables';``, the font-weight is changed to `500` but not changed back to `300` _(e.g. go to the text exercise editor as student and return to the course overview, the described bug can be observed)_ <br>
**But this is not true for all components using the import ``@import 'src/main/webapp/content/scss/artemis-variables';``:**
navigating to the `user-settings-container` and going back to the _Course Overview_ does not lead to the bug 
<details>
<summary>User settings do not break font-weight</summary>

https://user-images.githubusercontent.com/63976129/140894270-ac135ecd-53f3-4a30-8c38-0c9b00eb4945.mp4

The import is contained: 
![image](https://user-images.githubusercontent.com/63976129/140894547-ebf5e26f-17b8-495a-ad6d-d0cb3deb1a29.png)

</details>

3. A fix that works for most components is the following: 
Remove the heading definitions from 'src/main/webapp/content/scss/artemis-variables'` and move it to a new file 'src/main/webapp/content/scss/artemis-headings'`. This file can now be imported where needed!<br>
**Worked for the plagiarism page:** affected components with the new import are `plagiarism-header-component`, `plagiarism-inspector.component`, `plagiarism-run-details.component`, `plagiarism-sidebar.component`, `plagiarism-split-view.component` _(Some components might not need the font changes)_ - the plagiarism page hat the correct font weights and the font weights have been changed back correctly when visiting the _Course Overview_<br>
**Did not work for the grading page:** adding the new import to `plagiarism-exercise-configure-grading` broke the font-weight when going back to the _Course Overview_ - therefore it seems that our fix can not be applied, as extracting the font-weights to another file removes the font-weights for the plagiarism page and when importing those heading styles it breaks aswell

**Comment by krusche** [comment]
I guess it's simply bad practice to do the following.

```
h1 {
    font-weight: 500;
}
```

Can we not apply a custom css class whenever we want to change the font-weight to 500?
