### ISSUE TITLE
Programming exercise results are sometimes not shown or outdated

### ISSUE THREAD

**Issue by MaisiKoleni** [ls1intum/Artemis#3756]
### Describe the bug

The template and solutions results of programming exercises in the exercise details page are sometimes not shown or outdated, as the screenshots show. 

### To Reproduce

A pattern is not known to me, just try to view different programming exercises and keep an eye on the results.

What I found is that compared to the previous problems before #3731:
- Both template and solution can be affected, previously it was only the solution
- No errors in the network tab
- Reload seems to worsen it

### Expected behavior

The latest results are always shown.

#### One Tab
![image](https://user-images.githubusercontent.com/11130248/125509506-0766f1db-3afc-4ea6-aa86-52c5b8ea54cc.png)

#### Another Tab
![image](https://user-images.githubusercontent.com/11130248/125510052-ed96435e-81be-4798-b126-e832805275e5.png)

### What browsers are you seeing the problem on?

Chrome

### Additional context

(A hard page refresh does not help.)

### Relevant log output

NO errors appear in the network tab, Artemis does NOT show an "internal server error" alert.

**Comment by krusche** [comment]
should be fixed in 089a6718d4975d3c7f585e42c85dec7182fe7fea after correctly sorting submissions
