### ISSUE TITLE
Text Team Exercises not Editable

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#3759]
### Describe the bug

It's not possible to open an already assessed text team exercise.
I can't say whether it's possible to grade a news one since currently there is no ongoing grading.

### To Reproduce

Precondition: An assessed text team exercise exists
1. Go to the team page
2. Click on "Open assessment" of the text team exercise
3. See that nothing happens
4. See error in console

### Expected behavior

I expect the assessment view to open.

### What browsers are you seeing the problem on?

Chrome

### Additional context

After Friday the assessment of team exercises starts containing one text exercise. So it's urgent that until then this is fixed.

### Relevant log output

```shell
Uncaught (in promise) Error: Cannot match any routes. URL Segment: 'course-management/121/text-exercises/4279/submissions/2636847/assessment'    router.js:2656
```

**Comment by julian-christl** [comment]
Seems similar to #3749 which was resolved.
Probably a similar fix could be done here 
@PatZintel since you did the fix, could this be done quickly? Due to the upcoming assessment, this would be quite important.
A tutor also mentioned that her students couldn't open the text exercises themselves so this might be worth testing as well.

**Comment by lschlesinger** [comment]
@julian-christl I already started to investigate, and I also contacted @PatZintel... I hope it can be fixed quickly as it seems to be related to some route refactorings.

**Comment by julian-christl** [comment]
Amazing, thank you. Also, a quick hotfix would be highly appreciated in case the refactoring takes longer.
