### ISSUE TITLE
Automatic Assessment of Empty Submissions (and enabled manual assessment)

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#3780]
### Is your feature request related to a problem?

Typically, we perform a manual assessment of programming tasks by our teaching assistants.
As students may start their task but do not commit any change, the teaching assistants have to assess these as well.

### Describe the solution you'd like

I would like the feature that manual assessment will only be performed if a student has at least one commit. Otherwise, the system should automatically rate the submission with 0 Points.

**Comment by krusche** [comment]
This is already available or exams and it should be easy to also make it available for course exercises.
@SimonEntholzer could you please have a look?

**Comment by krusche** [comment]
This issue has been resolved by #3678
