### ISSUE TITLE
Server State Dashboard

### ISSUE THREAD

**Issue by tilschuenemann** [ls1intum/Artemis#3790]
### Is your feature request related to a problem?

In the past there have been times where one of the Artemis services was down or took awfully long to respond.
It was also not clear if this was server-side or a problem of the user. An example would be starting an exercise and waiting for Artemis to generate a BitBucket repo.

### Describe the solution you'd like

I'd suggest adding a status site, displaying if servers are up or down and how big the current workload is. This would be useful so every user can see if it's Artemis fault or their own. 
This would also help to monitor the performance to some extent for the operators of the site. I guess that there already is some solution for monitoring, maybe parts of it can be made public.

**Comment by krusche** [comment]
We have such a page now: https://status.ase.in.tum.de/status
