### ISSUE TITLE
Make second correction rounds available for normal tasks

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#3792]
### Is your feature request related to a problem?

Adopted from a Slack discussion ...

### Describe the solution you'd like

It would be nice if the second correction round feature would also be accessible for normal course exercises.

**Comment by krusche** [comment]
@SimonEntholzer @nicolasruscher can you add some information what we would need to change in Artemis to make this exam feature available for course exercises?

**Comment by dfuchss** [comment]
Not needed for us anymore.
