### ISSUE TITLE
Register students to Course with Matriculation Numbers

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#3793]
### Is your feature request related to a problem?

Adopted from a Slack discussion ...

### Describe the solution you'd like

It would be nice if you could register students to a course the same way as you do for exams.
So simply add the import via CSV (Matriculation or Login) feature to courses as well.

**Comment by krusche** [comment]
This can already be achieved with a workaround

1. create an exam
2. import students with a csv file into the exam -> this automatically imports them into the course as well
3. delete the exam


So it should be relatively easy to add this functionality in the course details page for instructors.
