### ISSUE TITLE
Build läuft nicht durch 

### ISSUE THREAD

**Issue by philippstadler** [ls1intum/Artemis#3796]
### Describe the bug

Also wir (**JKU Linz**) sind gerade dabei den **WS Kurs für Software Entwicklung 1** einzupflegen. 
Das Problem besteht nun darin, dass die Builds scheinbar nicht durchlaufen. 
Ich hätte versucht eine neue Beispiel-Aufgabe anzulegen, die für die restlichen Einpfleger als Template dienen soll (https://git.codeability.uibk.ac.at/LINZ1WS21UE00A00TEMPLATE/linz1ws21ue00a00template-tests). 

Das große Problem ist, dass der Build scheinbar nicht durchläuft. Die Tests vom Anlage-Template (Bubble-Sort, usw...) scheinen immer noch auf und das Building und Testing hängt in Dauerschleife. Lokal funktioniert beispielsweise der Class-Test. 
Ein Problem meinerseits? Hätte es heute schon mehrmals probiert auch mit IO

### To Reproduce

Über Artemis das Beispiel 21WS UE00 A00 Template öffnen und Submit drücken. 

### Expected behavior

Der Build und die Tests sollten normalerweise erfolgreich sein, aus meiner Sicht

### Screenshots

![grafik](https://user-images.githubusercontent.com/15194329/126162737-a12515db-8d04-4b8e-89f1-bdc1c422d87f.png)

### What browsers are you seeing the problem on?

Firefox

### Additional context

Eventuell könnte das Problem wieder bei unseren verwendeten Libraries liegen 
In.java und Out.java

### Relevant log output

```shell
No build results are available 

ABER: 

The result for your last submission is not available. Please submit your code again.
```

**Comment by krusche** [comment]
Sounds like issue #3786
We are currently investigating the issue. Which Artemis version are you using?

**Comment by krusche** [comment]
What happens if you open the build plan on Jenkins?

**Comment by philippstadler** [comment]
version 4.12.0
i am currently in contact with our hoster to get jenkins access

**Comment by daniels98it** [comment]
I further investigated the issue and it seems to be related to the generation of test cases from feedbacks. 

As soon as `test.json` does not use one or more tests (*in this case no constructor **and** attribute tests*), the following **test case** is generated multiple times from ArTEMiS:

`ProgrammingExerciseTestCase{id=null, testName='generateTestsForAllClasses', weight=1.0, active=true, visibility=ALWAYS, bonusMultiplier=1.0, bonusPoints=0.0}`

with this kind of feedback from the Build Plan:

`No tests for constructors available in the structural oracle (test.json). Either provide constructor information or delete ConstructorTest.java!`

leading to an SQL error and subsequent internal server error:

`SQL Error - Duplicate entry 'generateTestsForAllClasses-1020' for key 'programming_exercise_test_case.exercise_test_case'`

`org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [programming_exercise_test_case.exercise_test_case]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement`

I'll try to come up with a fix for this and create a related PR.

@philippstadler As a workaround for now, `test.json` should contain at least one of each tests types (*attribute, class, method, constructor*)

**Comment by philippstadler** [comment]
Thanks a lot, I will check it out!
