### ISSUE TITLE
🚀 Corrected Quiz feedback

### ISSUE THREAD

**Issue by tosoikea** [ls1intum/Artemis#382]
### Is your feature request related to a problem?
Wrong feedback sentence after finishing a quiz.
(EIST - Quiz 01)
![image](https://user-images.githubusercontent.com/35578078/57058933-f9a79a00-6cb2-11e9-9f16-f27e9f07d725.png)

### Describe the solution you'd like
Remove "you have selected 2 answer options wrongly". (As this is not true)

**Comment by sebina** [comment]
@tosoikea could you please upload a screenshot of the question itself here? Also maybe a screenshot of the edit mode of the question.

**Comment by tosoikea** [comment]
![image](https://user-images.githubusercontent.com/35578078/57198478-7bc5e600-6f73-11e9-9e97-908ae0a51361.png)
(Scoring All or Nothing)

If you mean by edit mode if it was practice or graded, the message occured in both types.

**Comment by SteffenDE** [comment]
<img width="802" alt="Bildschirmfoto 2019-05-23 um 08 17 27" src="https://user-images.githubusercontent.com/4116351/58237889-7673e400-7d46-11e9-85b7-b4761a2e2c8b.png">
