### ISSUE TITLE
Tests don't get collected after due date

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#3821]
### Describe the bug

When setting tests and exercise to run after due date, the test results don't get displayed correctly.

### To Reproduce

1. Create and submit a programming exercise with tests (exam to be sure)
2. Set the tests in the grading section to "After due date"
3. Set "Run Tests after Due Date" to a due date in the past
4. Run all tests
5. The result should only show "Build Successful, no tests executed" for the participation

### Expected behavior

Instead of showing the generic response "Build Successful, no tests executed", the actual test results should be displayed.

### Screenshots

Example with the wrong response on top and the correct response at the bottom
![](https://gyazo.com/fda311679256be87c441800d1dcdfbd3/raw)

### What browsers are you seeing the problem on?

Chrome

### Additional context

Please make sure that it's also possible to have the visibility of the test "After due date" even if "Run Tests after Due Date" is unset.
At the moment it's unclear whether this is actually still possible or not.

**Comment by julian-christl** [comment]
cc @krusche

**Comment by MaisiKoleni** [comment]
@julian-christl regarding:
> Please make sure that it's also possible to have the visibility of the test "After due date" even if "Run Tests after Due Date" is unset.
At the moment it's unclear whether this is actually still possible or not.

`After due date` and `Run Tests after Due Date` are to my knowledge two distinct mechanisms now. The former controls visibility according to the due date. The latter allows to schedule an event that will cause all builds to run at the specified time. Of course, having tests becoming visible after the due date makes only sense if the tests are actually run after the due date, so you usually combine both.
I would have to look deeper into the code if there are still some connections between both features, but AFAIK, you can now select freely with the dropdown list. A longer time ago, there were only checkboxes and those were disabled if build after due was not set.

**Comment by julian-christl** [comment]
@MaisiKoleni This was my first intuition as well. The unclarity comes most probably from the bug itself anyway, so that's okay, I think.
