### ISSUE TITLE
🐛 Disabled login button in Google Chrome on iOS

### ISSUE THREAD

**Issue by lgerhardt45** [ls1intum/ArTEMiS#383]
### Describe the bug
Disabled login button in Google Chrome App on iPad (Pro 2018) and iPhone (6S)

#### To Reproduce

1. On iPad or iPhone open the Google Chrome browser app
2. Go to https://artemis.ase.in.tum.de/#/
3. Enter login credentials
4. See that „Sign-in“ button is disabled even though the credentials are right

#### Expected behavior
Enabled „Sign-in“ button

#### Screenshots
iPad: ![IMG_0057](https://user-images.githubusercontent.com/40395744/57058936-fd3b2100-6cb2-11e9-9426-6e4e1cf58c2a.jpeg)
iPhone: ![IMG_6487](https://user-images.githubusercontent.com/40395744/57058965-1ba11c80-6cb3-11e9-9fb5-03a8ee4e4411.jpeg)

### Environment
<details><pre>
 - OS: iPad iOS 12.2, iPhone 12.1.4
 - Browser: Chrome
 - Version (Chrome): 74.0.3729.121
</pre></details>

#### Additional context
Bug doesn‘t appear in Safari browser app

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by maximilianmeier** [comment]
@lgerhardt45 did you autofill the login information or typed them manually?

**Comment by maximilianmeier** [comment]
fixed in #390

**Comment by lgerhardt45** [comment]
It was happening with autofill only. Sorry for the late reply and thanks for fixing - it seems to work now (tested on Chrome for iPhone)
