### ISSUE TITLE
Exams: Add Participants after Exam start

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#3835]
### Is your feature request related to a problem?

Esp. for long-time exams (longer than just a few hours), It may be important to add students after the exam itself has been started.

### Describe the solution you'd like

Possibility to add students (that work already) and generate individual exams for them (that don't work after exam start)

### Additional context

Student added, but generation of exam not possible:
![image](https://user-images.githubusercontent.com/22198798/127003335-b5b388d7-b87a-41a4-89df-6a7558c9cb59.png)

Student's view that says he has to ask me (but I can't do anything)
![image](https://user-images.githubusercontent.com/22198798/127003455-936bc97b-358c-45d6-82c2-759b5b10c716.png)

**Comment by dfuchss** [comment]
Currently, not needed for us.

**Comment by krusche** [comment]
we still plan to implement this as part of @coolchock's thesis in the near future
