### ISSUE TITLE
🐛 Q&A doesn't change when clicking on a notification

### ISSUE THREAD

**Issue by JoejoeSt** [ls1intum/ArTEMiS#384]
### Describe the bug
Q&A doesn't change when clicking on a notification

#### To Reproduce
1. Open an exercise
2. Click on a notification that forwards you to an other exercise

#### Expected behavior
The Q&A of the other exercise should be loaded

#### Screenshots
<img width="1792" alt="Bildschirmfoto 2019-05-02 um 10 33 47" src="https://user-images.githubusercontent.com/38322605/57064336-42b51980-6cc6-11e9-825f-89e0a4e1bd04.png">

### Environment
<details><pre>
 - OS: MacOS
 - Browser Safari
</pre></details>

**Comment by maximilianmeier** [comment]
fixed in #397 and #389
