### ISSUE TITLE
Import exams

### ISSUE THREAD

**Issue by krusche** [ls1intum/Artemis#3848]
It would be nice, if instructors could import whole exams, including the whole exam configuration, all exercise groups and exercises.

We would basically create copies of the exam object, the exercise group objects and the exercise objects (including repositories and build plans, example submissions)

Registered students, student exams, participations, submissions and results would not be copied.

This would also make it easier to test certain exam configurations in test course.

We have a similar functionality for importing an exercise.

**Comment by ge65cer** [comment]
Feature is implemented.
