### ISSUE TITLE
🚀 iCal feed

### ISSUE THREAD

**Issue by JonasJJJJ** [ls1intum/ArTEMiS#385]
### Is your feature request related to a problem?
Definitely not a huge problem but it would be nice to have the possibility to add deadlines to the calendar.

### Describe the solution you'd like
Offering a iCal URL to add in the personal calendar. The events should be removed automatically, once a programming  exercise has 100% or an exercise that cannot be edited afterwards is submitted..

### Describe alternatives you've considered
Actually no idea.

**Comment by krusche** [comment]
Thanks for your suggestion, currently this is out of scope.
