### ISSUE TITLE
MultiLine Support for Feedback view of Students

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#3854]
### Is your feature request related to a problem?

Since we format our feedback using multiple lines, the feedback should be shown to the students in multiple lines as well ..

### Describe the solution you'd like

Format Feedback with multiple lines if written that way ..

Student View (**that shall show multiple lines as well**):
![image](https://user-images.githubusercontent.com/22198798/127503104-e7ecde91-6652-4c7b-abd0-b6799446c021.png)

Reviewer/Assessment View:

![image](https://user-images.githubusercontent.com/22198798/127503414-8f46f9ad-ca7f-46d7-a9a3-f5447af83cbf.png)

Detailed Feedback View (Student):
![image](https://user-images.githubusercontent.com/22198798/127503240-1508c1c4-1fc3-4001-9db0-335153dd9d21.png)

**Comment by krusche** [comment]
Ideally, we allow the use of the markdown editor here
(Github also uses it)

**Comment by dfuchss** [comment]
Is related to #3035 . @MDK5 @krusche in 3035 an initial solution was linked. Maybe that solution could be taken into accounf
