### ISSUE TITLE
Saving assessments broken (after navigating to "next" submission)

### ISSUE THREAD

**Issue by delsner** [ls1intum/Artemis#3866]
### Describe the bug

When assessing multiple submissions after each other (by clicking "Assess next submission" after finishing a submission), I run into the problem shown in the screenshot: Clicking the "save" button will lead to an infinite spinner next to the save button and the browser console shows the null pointer de-referencing error.
Reloading the browser window fixes the problem.

### To Reproduce

1. Go to Assessment view (e.g., `https://artemis.ase.in.tum.de/course-management/231/text-exercises/789/participations/456/submissions/123/assessment`)
2. Click on 'save' (after having created some feedback)
3. Click on 'submit'
4. Click on 'Assess next submission'
5. Click on 'save' (after having created some feedback)
6. See error

### Expected behavior

I would expect to be be able to assess more than one submission in a row, without having to reload the page. (This is a regression, it worked before.)

### Screenshots

Observable problem (infinite spinner after trying to save):
![image](https://user-images.githubusercontent.com/5920521/127782795-2a7d0679-1a70-47eb-96ab-afd613b55caf.png)

### What browsers are you seeing the problem on?

Chrome

### Additional context

Spotted on TUM Artemis Deployment (5.1.1)

### Relevant log output

Browser console error:
![image](https://user-images.githubusercontent.com/5920521/127782804-43552ca0-b48e-492f-9277-1a4cb8a591cc.png)

**Comment by krusche** [comment]
@jpbernius can you please have a look? Thanks

**Comment by delsner** [comment]
@jpbernius currently, the only way to work around this bug is to "submit" each assessment immediately (without saving, that breaks it as described).

**Comment by lschlesinger** [comment]
This might be solved by #4039 @Olimbia23?

**Comment by Olimbia23** [comment]
> This might be solved by #4039 @Olimbia23?

Yes it solves this issue.
