### ISSUE TITLE
Exam Mode does not show correct results for tests after due date

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#3899]
### Describe the bug

We conducted an exam with manual assessment (programming task) and tests with visibility after due date.
Furthermore, we set the execution of the tests after exam end date + grace period + buffer.

If you start the assessment, you won't see the updated points for all test cases. Only the test cases with visibility "Always" will be used for the point calculation

### To Reproduce

See Description

### Expected behavior

The assessment shall be based on all test cases (Always + After Due Date)

### What browsers are you seeing the problem on?

Firefox

**Comment by krusche** [comment]
Duplicate. Was already fixed in the Release 5.1.3 yesterday
