### ISSUE TITLE
Setting a start date for an existing lecture raises `cyclic object value` error.

### ISSUE THREAD

**Issue by martin-fink** [ls1intum/Artemis#3958]
### Describe the bug

Edit: I'm an instructor in this course. It seems that I do not have permission to change the start date for lectures. Another instructor was able to change the date.

When adding a start date to an existing lecture without a start date, I get the following error when saving (different errors on different browsers):

Chome:
```
Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'results' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'Object'
    --- property 'submission' closes the circle
```

Firefox:
```
cyclic object value
```

Safari:
```
JSON.stringify cannot serialize cyclic structures.
```

### To Reproduce

1. Go to lectures (in my particular case course 141, lecture 222, but happened with other lectures as well)
2. Click on 'edit'
3. Select a start date with the date picker
4. Click on save
5. See error
6. If page is reloaded, the date was not saved

### Expected behavior

I would expect the form to save the start date without showing an error.

### Screenshots

Chrome:
![Screenshot 2021-08-30 at 11 17 08](https://user-images.githubusercontent.com/17706737/131317409-1698f798-ae08-4c6a-8228-366084c94e14.png)
Firefox:
![Screenshot 2021-08-30 at 11 07 40](https://user-images.githubusercontent.com/17706737/131317964-e8934181-25bf-44bd-9895-08bb35238e19.png)

### What browsers are you seeing the problem on?

Chrome, Firefox

### Additional context

Chrome version:
Version 92.0.4515.159 (Official Build) (x86_64)

Firefox version:
91.0b9 (64-bit)

### Relevant log output

No output in console

**Comment by lschlesinger** [comment]
@martin-fink I will take care of it. I just reproduced the error I found out, that this is only possible for lectures that have exercises as lecture units which contain submissions. During serializing the lecture object for the request body, the cyclic dependency occurs within the nested this nested exercise student participations (`results` is part of it). I also found out, that the error is not related to setting the start date but rather to any PUT request, i.e. change on the lecture.

Can you confirm that:
1. The error occurs when editing _any_ property of the affected lecture, so title, description, start or end date? 
2. The affected lecture includes exercise as lecture units that have submissions?

I will work on the solution during the next days, I am confident that the issue will be fixed soon :)

**Comment by martin-fink** [comment]
@lschlesinger thanks! :)

1. Yes, the same error occurs when editing any property
2. Yes, the lecture includes exercises as lecture units that have submissions
