### ISSUE TITLE
🚀 Skip this assessment without evaluation

### ISSUE THREAD

**Issue by loomilahada** [ls1intum/ArTEMiS#401]
### Is your feature request related to a problem?
 I am exhausted when I get submissions in German and I have to translate the answers on Google translate to evaluate them (and the translations do not always work well)

### Describe the solution you'd like

A button that allows skipping the assessment without evaluation could help. There should be a field that takes the reason for why the assessment has to be skipped.

### Describe alternatives you've considered
 Maybe a language preference to the students while submitting the answers could help.

**Comment by krusche** [comment]
Thanks for your suggestion. @SiggZ implemented a cancel button in https://github.com/ls1intum/ArTEMiS/pull/406 which is already merged to develop and will be available in the next release.
