### ISSUE TITLE
Embedding TUM Live Videos as Lecture Unit not working

### ISSUE THREAD

**Issue by COM8** [ls1intum/Artemis#4028]
### Describe the bug

Embedding a video from TUM Live as a lecture unit does not work.
![image](https://user-images.githubusercontent.com/11741404/134331676-a13cafe7-7422-4fda-a8dc-92e9e7166024.png)

### To Reproduce

1. Go to `Lectures`
2. Select your lecture
3. Click on `Add a new Lecture Unit ` -> `Video`
3. Use any TUM Live video URL and append `?video_only=1`.

### Expected behavior

TUM Live videos should render.

### What browsers are you seeing the problem on?

Firefox

### Additional context

Might be related to: https://github.com/ls1intum/Artemis/blob/c115ad0a53a7217c75c0d0fc191748a3187dc1ea/src/main/webapp/app/lecture/lecture-unit/lecture-unit-management/video-unit-form/video-unit-form.component.ts

**Comment by joschahenningsen** [comment]
This was likely introduced in #3774.
@FrankeLukas any chance, TUM-Live could be excluded as described here? https://www.npmjs.com/package/js-video-url-parser#adding-a-provider
