### ISSUE TITLE
🚀 Text exercise status differentiation

### ISSUE THREAD

**Issue by jefryyy** [ls1intum/Artemis#403]
Please differentiate between
1) a not-submited text Exercise
2) a submited but not yet graded text Exercise
3) a a graded and failed text Exercise

Right now anything that is not graded but past its deadline is shown as "missed point" and it is really confusing and is harder to keep track of which exercises I submited and which one of them I just saved. And the overall grade goes down drastically and then comes back up as the exercises are graded. I know that in the end when it is all graded it will be the same grade, but the experience of using the service would be better I hope. Also this can also show which exercise I submited before the deadline, because right now to see which ones of them I completed I can only enter and manually check my submition one by one.

**Comment by krusche** [comment]
resolved by #657
