### ISSUE TITLE
VM Instance

### ISSUE THREAD

**Issue by white8086** [ls1intum/Artemis#4048]
### Describe the bug

hi
i have issue when installation Artemis
i can't install with docker, client, server
i have some error
please help me for installation
does anyone have *.iso or vmdk for artemis 
i need pre-installation instance
please help 
thanks

### To Reproduce

hi
i have issue when installation Artemis
i can't install with docker, client, server
i have some error
please help me for installation
does anyone have *.iso or vmdk for artemis 
i need pre-installation instance
please help 
thanks

### Expected behavior

hi
i have issue when installation Artemis
i can't install with docker, client, server
i have some error
please help me for installation
does anyone have *.iso or vmdk for artemis 
i need pre-installation instance
please help 
thanks

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

**Comment by krusche** [comment]
This is not the right place for asking about help with the installation of Artemis. Please follow the documentation
