### ISSUE TITLE
Users won't be added to Repositories for Exams

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#4081]
### Describe the bug

For the correction of our exams, we added new users as TA to our course.
Unfortunately, I had to add them manually to the exam groups in GitLab (since they were not added to the groups by artemis.)

### To Reproduce

1. Conduct an exam with programming tasks. 
2. Add a new user to the system and add the user to the TA group of the course.
3. Look into gitlab and see that there is no user added to the repository group of the exam task

### Expected behavior

TA should have access to the task.

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

Artemis 5.1.5

**Comment by dfuchss** [comment]
They have also no access to the jenkins group for the exam tasks

**Comment by krusche** [comment]
Just to clarify: Artemis wants to prevent access to repos and build plans before the exam takes place. So tutors should only get access when the exam is over.
(Instructors and editors should get the access independent of the exam date)

**Comment by dfuchss** [comment]
That's fine. But iff I add further tutors at the end of the exam they shall get access to it.

**Comment by krusche** [comment]
We have a quick fix now. We need to further tune the situation that before an exam, so that tutors will be added to the respective exercises with a scheduled tasks. This will be done in a follow-up
