### ISSUE TITLE
🚀 Calculation of the score percentage

### ISSUE THREAD

**Issue by JonasJJJJ** [ls1intum/Artemis#411]
### Is your feature request related to a problem?
The percentage shown in the overview, as well as the one in the statistics section count ungraded exercises with zero points. Therefore, it is not useful at all, because there are always exercises which are not graded yet.
<img width="221" alt="OverviewPNG" src="https://user-images.githubusercontent.com/24255548/57285601-d9f9e280-70b3-11e9-8994-1c9d27456757.PNG">
<img width="837" alt="statistics" src="https://user-images.githubusercontent.com/24255548/57289290-5d6b0200-70bb-11e9-97aa-a19f4fa37747.PNG">

### Describe the solution you'd like
Not counting text and modeling exercises which are not graded yet for the maximum amount of points. So the user can estimate how good he performed until now instead of just getting a rather useless number.
### Describe alternatives you've considered
At least in the statistics section, the pie chart could alternatively include points of ungraded exercises but differentiate them from points of graded exercises, that the user did not receive instead of ust mixing up both of them like it is done currently in the grey section.

**Comment by maximilianmeier** [comment]
In #590 we changed how the score is calculated and only include exercises where the due date is in the past
