### ISSUE TITLE
🚀  Abstract methods (UML class diagram)

### ISSUE THREAD

**Issue by tosoikea** [ls1intum/ArTEMiS#412]
### Is your feature request related to a problem?
Trying to differentiate between abstract and non abstract methods inside an abstract class.
This differentation problem occures in the UML class diagram editor.

### Describe the solution you'd like
Allow for the uml specific options of marking methods as abstract (italic).
Additionally the display of static (underline) class members or methods is desirable.

This could me introduced in the same way, abstract classes are marked.

**Comment by krusche** [comment]
Thanks for your suggestion. Could you please add this into the GitHub repository of the Apollon editor:  https://github.com/ls1intum/Apollon

Closing this issue here because Artemis does not implement the modeling editor, it is an external component.
