### ISSUE TITLE
Lecture Attachments: Full authentication is required to access this resource

### ISSUE THREAD

**Issue by COM8** [ls1intum/Artemis#4120]
### Describe the bug

We added attachments to our [lecture](https://artemis.ase.in.tum.de/courses/152/lectures/231) and one looks to be broken.
When we try to download the file, the following error occurs:
```json
{
  "type": "https://www.jhipster.tech/problem/problem-with-message",
  "title": "Unauthorized",
  "status": 401,
  "detail": "Full authentication is required to access this resource",
  "path": "/api/files/temp/Fib_Solution.zip",
  "message": "error.http.401"
}
```

### To Reproduce

1. Go to 'Lectures'
2. Click on 'Add Attachments'
3. Once done, try downloading it.

### Expected behavior

The file should download.

### What browsers are you seeing the problem on?

Chrome, Firefox

### Additional context

We are unable to reproduce it.
We kept the broken attachment in case it helps you debugging it.
The broken attachment can be found in our `Speicher und Pointer` lecture for the `C-Vorkurs`.
It's called `Diesen Link bitte ignorieren...`.

Link to the lecture: https://artemis.ase.in.tum.de/courses/152/lectures/231

**Comment by ge65cer** [comment]
Closed, as I can not reproduce the issue.
