### ISSUE TITLE
🐛 Downloading materials changes all buttons to "Is downloading..."

### ISSUE THREAD

**Issue by Khalphion** [ls1intum/ArTEMiS#413]
### Describe the bug
When I click on a lecture attachment to download, all attachments change to "Is downloading"

#### To Reproduce
1. Go to a lecture
2. Click one of multiple files

#### Expected behavior
Only one button should show "Is downloading".

#### Screenshots

![image](https://user-images.githubusercontent.com/10117554/57300694-a335c380-70d7-11e9-8289-46b3fc2302b7.png)

### Environment

<details><pre>
- OS: Windows 10
 - Browser: Chrome 74.0.3729.108
 - Version: Artemis 3.0.4
</pre></details>

**Comment by sleiss** [comment]
This should be fixed by https://github.com/ls1intum/ArTEMiS/pull/408.
