### ISSUE TITLE
🐛 Drag&Drop quiz scales badly on 13 inch, Full HD Laptop resolution (Win 10)

### ISSUE THREAD

**Issue by lukasHoel** [ls1intum/Artemis#417]
### Describe the bug
When doing a drag&drop quiz the whole quiz might not be displayed completely on my monitor. I need to scroll down to get to some answer possibilities and might need to scroll up again to put the answers in their right spot. But scrolling upwards on a touchpad does NOT work when I am still dragging the answer. Putting the answer at the top of the screen does also not scroll the page back up. Thus, it is not possible to put the answer at its right spot without manually decreasing the zoom level of my browser (which leads to very small text boxes, etc.)

#### Expected behavior
Either the quiz scales correctly to show the quiz and all possible answers in one screen or I must be able to scroll while dragging an activity (for example by dragging the answer at the top of the screen which does a scroll).

#### Screenshots
This is the part of the quiz that gets displayed by default. As you can see I need to scroll down to see the answers.
![image](https://user-images.githubusercontent.com/36296213/57354966-3c62e980-716d-11e9-9a45-e8959b159a7b.png)

I need to zoom out to 50% zoom level to see all possible answers. This appears pretty small on my monitor
![image](https://user-images.githubusercontent.com/36296213/57355067-7b913a80-716d-11e9-9e5d-7beb48b66631.png)

### Environment

<details><pre>
 - OS: Win10, FullHD 1080p 13-inch monitor
 - Browser Chrome (newest)
 - Version Artemis 3.1.0
</pre></details>

**Comment by krusche** [comment]
We improved this in the next release 3.2.0
Let us know what you think about it and if it works better on your monitor.

**Comment by lukasHoel** [comment]
The issue is fixed for me on my monitor. While I still could not fit everything on one page, it allowed me to scroll up by placing the issue at the top of the page while still dragging it. Thanks for your support!
