### ISSUE TITLE
🚀 Make the scaling of the text field fit better to bigger screens

### ISSUE THREAD

**Issue by rjrj98** [ls1intum/ArTEMiS#419]
### Is your feature request related to a problem?
Not a very important problem

### Describe the solution you'd like

I would like to have an option to make the text field in the text exercise not as wide because it extends width wise over the hole screen which is very weird for reading it:
![Screenshot 2019-05-08 11 57 16](https://user-images.githubusercontent.com/50199155/57373676-3be04800-7199-11e9-9e9d-3cd6c6362782.png)

Normally a text Field does not extend that far to the sides:
![Screenshot 2019-05-08 11 58 59](https://user-images.githubusercontent.com/50199155/57373777-7813a880-7199-11e9-813f-050dd7cfa6ea.png)

 

### Describe alternatives you've considered
The possibility to Upload files

**Comment by krusche** [comment]
I think you can just resize your browser, can't you?
