### ISSUE TITLE
RFC: Individual Extended Working Time for Exercises

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#4196]
# Is your feature request related to a problem?

In some lectures the points of multiple exercises performed during the semester is combined into the final grade (‘Portfolioprüfung’). As in those cases the exercise directly influences the grade, sick days the student can prove via a doctor’s notice have to be compensated by individually extending that student’s final submission date for the current exercise.

Extensions of working time is currently only possible for exams, but not not for regular exercises within Artemis.

# Describe the solution you'd like

## User Facing Changes
- As an instructor to the exercise
    - When accessing the ‘Participation’ page in the exercise management, I would like to see in the list of students that participate for which ones an individual due date has been set.
    - I would like to be able to add an individual due date to any participation of the exercise. The due date should only be allowed to be later than the regular exercise due date.
- As a tutor
    - After the regular due date not yet finished submissions should not show up when assessing other submissions of the same exercise.
- As a student
    - I would like to see my individual due date in the Artemis client.
    - I would like to be able to submit to the exercise until my individual due date.

## Changes to the data model
The individual working times for exams are stored in the `StudentExam`. Similarly for exercises, this can be done in `Participation` by adding a `ZonedDateTime individualDueDate` attribute.
As this is part of the `Participation`, the student is at least required to click on ‘Start Exercise’ before the regular due date to make sure such a `Participation` for the student exists. This is a reasonable and acceptable limitation.

## Effects that have to be considered
- The uniform due date for an exercise is assumed at many places throughout most of Artemis’s functionality.
- All exercises: Assessment on other submissions should be able to start before the last student has finished their exercise. The not yet finished participation should not yet be possible to be assessed by tutors.
- Programming exercises: When receiving build results, the test cases and feedbacks for tests marked with `AFTER_DUE_DATE` have to be filtered according to the individual due date.
- Programming exercises: The scheduling for the after due date tasks has to be updated:
   - The run tests after due date CI-runs have to be scheduled according to either the specified date, or after the individual due date depending on which one exists.
   - The repository locking mechanism after the due date has to exclude those repositories that belong to students that are still allowed to work on the exercise.
   - The repository locking mechanism has to lock the repository on the individual due date.
- Possible effects on the notification system? → I’ve not looked into it, but that is not a core functionality and necessary changes could be implemented in a follow-up PR.
- Individual due dates should only be possible for exercises that actually have a due date themself.
- Moving the due date for the exercise itself to a later point in time should remove all individual due dates that are before the general due date.
    - Invariant: ∀ i ∈ individual due dates: i = `null` ∨ i > exercise due date

### Server
Similarly to the existing `ExamDateService` a new `ExerciseDateService` should be introduced. Then all server-side checks if the due date has passed can be directed to a central location.
The check needs the student participation. If no individual due date is set for that participation, then the due date of the exercise is used. If the exercise is an exam exercise the due date check from the `ExamDateService` should be used.

Apply a filter to the submissions when tutors request one for assessment. Not yet finished ones should not be able to be sent to the client for assessment.

Scheduling changes (only relevant for programming exercises):
- For all students in the exercise for which no individual due date is set the regular scheduling as implemented now should still be used.
    - Spawning a lot of individual tasks that concurrently perform basically the same actions produces unnecessary load on the system, especially for very big courses with many students.
    - Instead, when locking repositories, and when updating scores a filter has to be applied to only perform those actions on submissions that do not have an individual due date (can be done in the query fetching them from the database).
- Only for students which have got an individual due date, individual tasks for locking the repository and updating the score are scheduled.
    - This should only affect very few students, no extraordinary load is to be expected.
    - The `ScheduleService` should be extended to also allow for scheduling based on the `Participation`.
    - A new small `ParticipationLifecycleService` to handle those scheduled tasks will be introduced.

### Client
- Where a due date is shown to the student, this should now be the individual due date if one exists. If not, the regular exercise due date should be shown.
    - A similar check as in the server that uses the exercise and participation to determine the due date should be introduced.
- The ability to choose an individual due date for a student as instructor has to be added to the participation list.
- `AFTER_DUE_DATE`-feedbacks are filtered server-side. Requesting a result with feedbacks therefore works as before without changes to the client.
- When tutors request the next submission to assess, a request is made to the server anyway. The server can filter the submissions without assessments accordingly to not return a non-finished one. ⇒ No change needed.

# Describe alternatives you've considered

Manually unlocking a single repository and allowing the student to push further commits would be possible. Artemis at the moment does not handle the exclusion from manual assessments. In programming exercises with tests marked with `AFTER_DUE_DATE`, those would be visible to the student while still working on the exercise.
⇒ Not a real alternative.

# Additional context

I’ve marked this PR as RFC, as I want to change a core idea/assumption in the exercise model. Therefore, I want to make sure that possible effects have been considered not only be myself to make sure I did not miss potentially important ones before I start implementing the feature.

WIP on branch `feature/exercises/individual-due-dates`: https://github.com/ls1intum/Artemis/tree/feature/exercises/individual-due-dates, PR #4416

**Comment by krusche** [comment]
Thanks for this detailed proposal, great work! I like the solution that you describe. From my side, you can start with the implementation. I know that @dfuchss is also waiting for this feature.

After the implementation is done, we have to test this very carefully to make sure no functionality is affected.
