### ISSUE TITLE
🐛Can't log in to Artemis on both of my Android smartphones

### ISSUE THREAD

**Issue by ivymai** [ls1intum/ArTEMiS#421]
### Describe the bug

For illustration take a look at my screenshot in the link below:
https://drive.google.com/open?id=1k6DPT8VzOrlF2-bRuRjDXlU-m7K1Ebhs

**Comment by jpbernius** [comment]
Hello @ivymai, can you please provide all the information requested in the [bug report template](https://github.com/ls1intum/ArTEMiS/blob/develop/.github/ISSUE_TEMPLATE/bug-report.md)?

It is hard to relate to your problem as I am missing information on your browser etc. 
Please try to clear your browser cache, check your internet connection and try again.

---
ℹ️ Note: You can attach files to GitHub issues directly.
