### ISSUE TITLE
🐛 Statistics: Wrong order of on-hover popups

### ISSUE THREAD

**Issue by max-OS1** [ls1intum/ArTEMiS#424]
### Describe the bug
On-hover popover on statistics page is unreadable (→ Screenshot)

#### To Reproduce
1. Log in to Artemis
2. Enter a course page and go to the statistics tab
3. Hover over the Total Points pie diagram pieces

#### Expected behavior
On-hover popover should be in front of the pie chart

#### Screenshots
<img width="457" alt="Bildschirmfoto 2019-05-09 um 09 20 45" src="https://user-images.githubusercontent.com/4730112/57434771-09d3f200-723c-11e9-8190-7004250e0cf3.png">

### Environment

<details><pre>
 - OS: macOS 10.14.4
 - Browser: Safari
 - Version 12.1
</pre></details>

**Comment by maximilianmeier** [comment]
thank you for reporting this issue. i'm working on a fix

**Comment by maximilianmeier** [comment]
Fixed in #463
