### ISSUE TITLE
🐛 Text assessment highlighting randomly not showing

### ISSUE THREAD

**Issue by Khalphion** [ls1intum/Artemis#425]
### Describe the bug
Assessment highlight sometimes fails (dark green):

![image](https://user-images.githubusercontent.com/10117554/57439076-8ae3b700-7245-11e9-8268-13ff9e27a53e.png)

#### To Reproduce
Randomly occurs, first I thought it was due to colons or line breaks, but I also had cases where this just happened for no visible reason.

### Environment

<details><pre>
- OS: macOS Mojave 10.14.3
 - Browser: Chrome 74.0.3729.108
 - Version: Artemis 3.1.0
</pre></details>

**Comment by Khalphion** [comment]
Another recent example:

![image](https://user-images.githubusercontent.com/10117554/57455119-b75dfa00-726a-11e9-8f7c-d27945c94ce0.png)

**Comment by krusche** [comment]
@jpbernius you are working on this screen for the general feedback anyway. Could you please have a look and see if you could fix this issue easily? Thanks!

**Comment by krusche** [comment]
@jpbernius What is the status of this issue? Can we fix it?

**Comment by jpbernius** [comment]
The idea is to replace this view with something more consistent with the look and feel of #341.
However, there is no timeline. The problem occurs when matching a selection to HTML containing some `<tags>` which to not match the plain text representation, obviously.

**Comment by jpbernius** [comment]
This issue should be addressed as part of #1208 also, as this is caused by the same / a similar problem as #1147.

**Comment by jpbernius** [comment]
We will not address this as part of #1208, as this is related to some weird behavior in the text selection API.
In this case, the submission contains multiple space characters `  `. The text selection API does return this only as one space ` ` which makes it hard to match.
We will try to address this / work around this limitation when reworking the assessment UI as part of #1251.
