### ISSUE TITLE
🚀 Modeling: Customize keyboard shortcuts

### ISSUE THREAD

**Issue by AlEscher** [ls1intum/Artemis#426]
### Is your feature request related to a problem?

While in the modeling editor, Ctrl + D is the shortcut in Chrome to add a bookmark instead of duplicating an object.

### Describe the solution you'd like

An option to customize the shortcuts for the modeling editor, especially for the duplicate shortcut as that is one of the most useful.

### Describe alternatives you've considered

To be able to duplicate by right clicking on an object in the modeling editor, or add a duplicate button on each object.

**Comment by jwilland-tum** [comment]
Thank you for your detailed description! In our current release, we changed the shortcut to duplicate elements to `ctrl-c` and `ctrl-v`. If you are using a Windows device, please be patient for the next release including https://github.com/ls1intum/Apollon/pull/69
