### ISSUE TITLE
🐛 Layout for submission of modeling exercises broken

### ISSUE THREAD

**Issue by oberrich** [ls1intum/ArTEMiS#428]
### Describe the bug

The layout on modeling exercises is broken -- for long problem statements at least. I suspect that this is due to `height: calc(100vh - 173px);` in `.assessment-result-container`. Removing this seems to fix the layout (see [2])

#### To Reproduce

1. Submit a model exercise
2. Go to said model exercise
3. Click on 'View submission'
4. See broken layout (Reproducible on EIST H02E01 and H02E02)

#### Screenshots

[1] Live view

![image](https://user-images.githubusercontent.com/6305520/57449034-27648400-725b-11e9-92c3-a5d08957d2a4.png)

[2] Withought `height: ...` in `.assessment-result-container`

![image](https://user-images.githubusercontent.com/6305520/57449151-83c7a380-725b-11e9-9bc7-4d1ff594933c.png)

### Environment

<details><pre>
 - OS: Windows
 - Browser Chromium
 - Version 72
</pre></details>

**Comment by SiggZ** [comment]
Thank you for reporting the bug.
It should be fixed with https://github.com/ls1intum/ArTEMiS/pull/430.

**Comment by marcklingen** [comment]
It is still is impossible to view the submissions on mobile. Not sure if this is out of scope though.
