### ISSUE TITLE
`Teams`: It is impossible for tutors to handle complaints in team mode.

### ISSUE THREAD

**Issue by bottbenj** [ls1intum/Artemis#4294]
### Describe the bug

When attempting to handle a complaint on an text or file upload exercise in team mode, the assessing tutor sees the message `There is a complaint for this assessment. Another tutor must respond.`, the feedback items are read only and the complaint response box is missing. However the assessment lock will be correctly acquired.

When attempting to handle the complaint as another tutor that didn't do the original assessment, no message will be shown, the feedback items will be editable and the complaint response box will be shown. Acquiring the assessment lock will fail with 403 error and pressing the accept or reject complaint buttons will do nothing.

Behavior of modeling and programming exercises was not tested but is almost certainly also broken in some way.

### To Reproduce

1. Create a Team Mode exercise
2. Submit a solution
3. Assess the solution as a TA (must not be instructor)
4. Create a complaint on the assessment
5. Attempt to handle the complaint

### Expected behavior

It is possible to handle the complaint as the assessing tutor.
It should not appear to be possible to handle the complaint as an other tutor.

### What browsers are you seeing the problem on?

Firefox

### Additional context

#4274 Does not fix this issue

This bug has at least 2 independent causes.

1. in `complaints-for-tutor.component.ts` `isAllowedToRespond` fails to work correctly after the first call, because of this line 
https://github.com/ls1intum/Artemis/blob/490c680a82c72c27e497266750c5fd379baa6068/src/main/webapp/app/complaints/complaints-for-tutor/complaints-for-tutor.component.ts#L214
because after the first call either `createLock` or `refreshLock` will re-set the complaint property to the complaint object from the response of their web request, which does *not* contain the team property, even if the exercise is a team exercise.
the easiest fix is to use `this.exercise?.teamMode` instead to check if team mode is active

   this then shows the complaint response box correctly and the complaint can be handled, but the assessment itself can sill not be changed as the feedback is still read only

2. the rest of the assessment for seems to not know about team mode whatsoever.
and since i have no idea where the problem starts and ends here this is an issue and not a PR

   Edit: changing the `readonly` property in the text and file upload assessment components makes the feedback editable, but that needs to basically replicate the `isAllowedToRespond` 4 times; and then the `assessment-header.component` is still wrong, but that doesnt really matter
   
   no idea about how programming and modeling work

**Comment by michael-schwarz** [comment]
This is an important issue for us. We are currently using group submissions for FPV ("Info2"), and our workaround is having TAs sending instructors the answers to the complaints which they can then enter on Artemis. It works, but involves more busywork than one would like.

Would be of great help to us if this can be fixed :blush:

**Comment by krusche** [comment]
We try to fix it as soon as possible
