### ISSUE TITLE
Discussions: Show usernames when hovering over reactions

### ISSUE THREAD

**Issue by fh314** [ls1intum/Artemis#4306]
### Is your feature request related to a problem?

When using reactions on posts or answers in the discussion tab, there seems to be no way for other users to tell who the author of these reactions is. 

### Describe the solution you'd like

Show the names of the users who used the reaction when hovering over it. 
Example: Zulip
![image](https://user-images.githubusercontent.com/29736922/141803556-fdfabc71-07a8-41e7-881c-6a0e55e56ed9.png)

**Comment by lschlesinger** [comment]
I am working on a solution :) thanks for the input!
