### ISSUE TITLE
Students cannot complaint about assessments for file upload exercises since 4.3.2

### ISSUE THREAD

**Issue by bottbenj** [ls1intum/Artemis#4317]
### Describe the bug

Students cannot create complaints on file upload exercise since the update to 4.3.2.
The Complaint and More Feedback buttons will be grayed out and not work.

Reverting the client to 4.3.1 fixes the issue, so #4301 likely is responsible for this regression.

### To Reproduce

1. Create a file upload exercise
2. Create a submission for it
3. Asess it
4. Attempt to complain about it
5. Notice that the complain and more feedback buttons are grayed out and cannot be clicked

### Expected behavior

Complaints should be possibe since the assessment happened wilthin the last 7 days. (or what ever was configured for the course)

### Screenshots

![grafik](https://user-images.githubusercontent.com/44437514/142070929-c5fca664-7a28-4a3a-a3e8-f2d1d2b3a871.png)

### What browsers are you seeing the problem on?

Firefox

### Additional context

semi-related: the tooltip informing students about why the cant submit complaits boesnt work either, even tho it would be wrong in this case

As a workaround students can just remove the disabled attibute from the buttons and everything will work fine afterwards.

### Cause

https://github.com/ls1intum/Artemis/blob/77e8435d715100cfe44aba585ba2cb13160bd955/src/main/webapp/app/complaints/complaints-for-students/complaints-student-view.component.ts#L136-L143

file upload exercises do not have an assessment type and trigger this case incorrectly

**Comment by krusche** [comment]
Is this related to #4294?

**Comment by bottbenj** [comment]
this is that since the latest update some students cant even place complaints in the first place. (complaints-for-students)
that one was an older issue and on the tutor side of things (complaints-for-tutors)

they are certainly unrelated and this one is most likely not limited to teams (it just happened with teams as most of our exercises in th first weeks are team ones)

**Comment by julian-christl** [comment]
It actually is most probably only related to teams since it was tested for individual exercises in #4301 and worked. I will try to reproduce it.

**Comment by bottbenj** [comment]
@julian-christl see cause in the issue description it is related to file upload exercises
