### ISSUE TITLE
Make test server DNS names consistent

### ISSUE THREAD

**Issue by FlorianGlombik** [ls1intum/Artemis#4318]
### Is your feature request related to a problem?

The naming of the test server is not consistent with ts3 as https://vmbruegge60.in.tum.de/ and ts1 + ts2 as https://artemistest.ase.in.tum.de/ and https://artemistest2.ase.in.tum.de/. 

### Describe the solution you'd like

Ts3 could get a similar name: https://artemistest3.ase.in.tum.de/

### Describe alternatives you've considered

Ignore the inconsistency.

**Comment by krusche** [comment]
I don’t think this should be a GitHub issue because it’s not related to code. Could you instead use the ls1admin JIRA project for issues related to the TUM infrastructure?

**Comment by FlorianGlombik** [comment]
This makes sense, I was not aware of the separation _(which I should have thought off as this does only affect our instances)_. I have created an issue within the JIRA Artemis project instead
