### ISSUE TITLE
Accepting a complaint turns postive test cases with 0 weight into negative ones

### ISSUE THREAD

**Issue by Strohgelaender** [ls1intum/Artemis#4334]
### Describe the bug

When accepting a complaint for a programming exercise, successful test cases which don't award points (weight 0) get changed into negative ones. As a consequence, the student sees reed empty feedback elements.

### To Reproduce

1. You need a programming exercise with test cases that don't award points (weight 0)
2. A student needs to submit a complaint.
3. A tutor accepts the complaint
4. The test cases get negative and are shown red.

### Expected behavior

positive test cases stay positive.

### Screenshots

result before the complaint (tutor view):
![grafik](https://user-images.githubusercontent.com/26540346/142620161-b806d710-3413-49fb-8426-34db16edbfcb.png)

result after the accepted complaint (tutor view):
![grafik](https://user-images.githubusercontent.com/26540346/142619894-4df47b03-c496-4a53-a7b0-271ca68bf684.png)

result after the accepted complaint (student view):
![grafik](https://user-images.githubusercontent.com/26540346/142619930-bbd6c6c7-8a45-404f-95b4-a17c7c1966ac.png)

### What browsers are you seeing the problem on?

Firefox

### Additional context

Looking at the data from the API, I found out that the `positive`-attribute gets changed when accepting the complaint, from `true` to `false`.

**Comment by dfuchss** [comment]
We've also seen this behavior.
