### ISSUE TITLE
🚀 Comment for update notices

### ISSUE THREAD

**Issue by max-OS1** [ls1intum/Artemis#434]
### Is your feature request related to a problem?
When an instructor updates an exercise, there is no way to see what changed or if there is no visible change to the student. Sometimes, this is confusing.

### Describe the solution you'd like
When instructors update an exercise, let them specify a short comment what exactly was updated, to be shown in the notifications tab.

### Describe alternatives you've considered
A change log with all comments in the exercise view could also be established instead of showing the comment in the notification.

**Comment by maximilianmeier** [comment]
Thanks for the input. We added this functionality in #592
