### ISSUE TITLE
Exercise list sorting not working

### ISSUE THREAD

**Issue by N0W0RK** [ls1intum/Artemis#4346]
### Describe the bug

After opening the exercise list from course management, the exercises cannot be sorted. Changing the table sorting option does not change the order in any way.

### To Reproduce

1. Open course management as editor or instructor.
2. Select exercises
3. Try to change the display order via the arrows next to the table headers.

### Expected behavior

Changing the sorting should affect the order of the exercises.

### Screenshots

Screenshots have been limited to one column. The course I checked was PGDP2122
![grafik](https://user-images.githubusercontent.com/22464684/142779202-1536329e-875b-49aa-8ac7-58ff31464abb.png)
![grafik](https://user-images.githubusercontent.com/22464684/142779205-d9f03ef8-afb8-410d-9566-5011deb74bfd.png)

### What browsers are you seeing the problem on?

Firefox

**Comment by julian-christl** [comment]
@Hialus Could this be related to #4205?

**Comment by Hialus** [comment]
> @Hialus Could this be related to #4205?

Indeed it is. #4375 fixes this.
