### ISSUE TITLE
Create Documentation for Artemis Docker Deployments

### ISSUE THREAD

**Issue by Mtze** [ls1intum/Artemis#4349]
### Is your feature request related to a problem?

In #3670 we introduced a workflow that automatically builds Artemis Docker images. 
Up until now we don't have documentation on how to use the docker image to deploy Artemis in a production environment. 

### Describe the solution you'd like

An entry in the documentation that describes how to deploy Artemis using a docker image.

**Comment by 4ludwig4** [comment]
@Mtze Not sure if the current documentation about Docker and Docker Compose fulfills this?

**Comment by Mtze** [comment]
It does :)
