### ISSUE TITLE
🐛 Deleting name of Classes in UML model editor

### ISSUE THREAD

**Issue by ga62suz** [ls1intum/ArTEMiS#436]
### Describe the bug
In the model editor (object model mode), after you delete the name of an existing class (or abstract class / interface / enum), the class disappears, but the editor window is still open. If you then try to add an attribute or a method to that class, the editor is bugged out.

#### To Reproduce
1. Go to model editor (object model mode)
2. Add a class
3. Double click on this class
4. Click the delete button next to the class' name
5. Click on the now-empty field below "Attributes" or "Method"
6. Type in a name to add an attribute or method
7. Press enter
8. The editor is now bugged, you cannot move, add, or edit classes.

#### Expected behavior
You can still move, add, and edit classes after doing that.

#### Screenshots
![image](https://user-images.githubusercontent.com/50523655/57571637-f332c400-7410-11e9-9d33-0a597f144b71.png)
![image](https://user-images.githubusercontent.com/50523655/57571679-5886b500-7411-11e9-8142-2904b837f214.png)

### Environment

<details><pre>
 - OS: Windows 10
 - Browser: Firefox, Chrome
 - Version: Firefox 66.0.5 (64-bit), Chrome Version 74.0.3729.131 (Official Build) (64-bit)
</pre></details>

#### Additional context
When bugged, added classes does not show up but will be there when you press save -> F5 refresh

**Comment by krusche** [comment]
This is related to Apollon. @jwilland-tum could you have a look into this bug please?

**Comment by jwilland-tum** [comment]
Thank you for your detailed request! PR https://github.com/ls1intum/ArTEMiS/pull/442 fixes this issue by dismissing open popovers if an element is deleted.
