### ISSUE TITLE
🐛 Duplicating: non-working keyboard shortcut

### ISSUE THREAD

**Issue by Extender** [ls1intum/ArTEMiS#438]
### Describe the bug
Duplicating in the modeling editor does not work for me because CTRL+D is the shortcut to create a bookmark.
Please choose another shortcut, CTRL+D always creates a bookmark when pressed!

Chrome Version: 74.0.3729.131 (64 bit; Windows 10)

**Comment by jpbernius** [comment]
Closing this in favor of #426.
