### ISSUE TITLE
🐛 Use Cases disappear in UML use case editor 

### ISSUE THREAD

**Issue by goldst** [ls1intum/ArTEMiS#439]
### Describe the bug
A Use Case disappeared while creating a UML use case diagram (Eist 2019 H02E01). It reappeared after closing and reopening the editor. Connection lines didn't disappear.

#### To Reproduce
I can't reproduce the behavior because I already submitted my solution. To me, it happened after adding many use cases. It might have to do with resizing the object behind the disappeared one, I'm not sure though.

#### Expected behavior
Use cases that I add should stay visible unless I delete them.

#### Screenshots
Sorry, wasn't able to take any because I wasn't sure this is a bug when it happened to me.

### Environment
<details><pre>
 - OS: Linux Arch (Xorg, Gnome)
 - Browser Firefox
 - Version 66.0.3 (64-bit)
</pre></details>

#### Additional context
Another student in my class (Eist 2019) had a similar problem (See Q&A section of H02E01 at 10.05.19 17:19). He only saw the reappeared use case after submitting. That's where I found out this might be a bug.

#### Output in Web Console
Sorry, too late for this.

**Comment by goldst** [comment]
Possibly the same problem as #479 (duplicate?)

**Comment by krusche** [comment]
I think this issue was solved in a previous release. @goldst Can you confirm this please?
If it still occurs, please reopen the issue.

**Comment by goldst** [comment]
It looks like it should be fixed now.
