### ISSUE TITLE
Page Title of Discussion Overview is "[Object object]"

### ISSUE THREAD

**Issue by Strohgelaender** [ls1intum/Artemis#4421]
### Describe the bug

The title of the discussion overview is not displayed correctly (see screenshot).

### To Reproduce

1. Open a Course and go on the Discussion-Tab
2. See wrong page title

### Expected behavior

Correct title (e.g. "Discussions")

### Screenshots

![grafik](https://user-images.githubusercontent.com/26540346/144263177-2736c7b2-266c-4294-9ec3-ad7b666d210b.png)

### What browsers are you seeing the problem on?

Firefox

**Comment by fh314** [comment]
I think @lschlesinger already fixed this in #4367

**Comment by lschlesinger** [comment]
@Strohgelaender wants to close the issue as soon as the version including the fixing PR #4306 is released.

**Comment by krusche** [comment]
It was already merged to `develop`, so I think we can close it 👍
