### ISSUE TITLE
🐛 Multiple bugs in text assessment view

### ISSUE THREAD

**Issue by max-ae** [ls1intum/Artemis#444]
### Describe the bug
Multiple bugs, see screenshot

1. Yellow: HTML tags showing up in submitted text
2. Blue: Text getting cut off by checkmark
3. Red: Submitted text gets duplicated after assessment

These bugs happen on all my assessed submissions in different browsers and on different devices.

#### To Reproduce

1. Go to 'Exercises'
2. Click on any assessed exercise and view assessed submission
3. See error

#### Expected behavior
1. No HTML tags appearing
2. Correct alignment of checkmarks, not cutting off text
3. Text only shows up once, with correct highlighting without getting duplicated after assessment

#### Screenshots
<img width="1345" alt="Bildschirmfoto 2019-05-13 um 23 07 15" src="https://user-images.githubusercontent.com/4730112/57654837-70a73180-75d5-11e9-9728-03250fc97d83.png">

### Environment

<details><pre>
 - OS: macOS 10.14.2 & iOS 12.2 / 12.3
 - Browser: Safari 12.1 & Chrome 74.0.3729.131
</pre></details>

**Comment by krusche** [comment]
@jpbernius I think you implemented this screen. Could you please review this issue and fix it?

**Comment by jpbernius** [comment]
This problem is related to matching text selections and actual student text during assessment. This no longer occurs when using the new text assessment (v2) #1286.
