### ISSUE TITLE
Error messages excplicitly recommend *only* Chrome

### ISSUE THREAD

**Issue by I-Al-Istannen** [ls1intum/Artemis#4447]
### Describe the bug

The error message in https://github.com/ls1intum/Artemis/blob/c3b98db7645f45e3164e2d194b47ab624b8ef3d8/src/main/webapp/index.html#L36 only mentions Chrome and I am not sure that is warranted. If you for whatever reason don't think Firefox works (which is a real shame), Edge should at least have the same underlying engine.

I haven't found any API or structure that doesn't work on FF in my web projects, I sometimes had to adjust a property name here and there to make it work on Chrome (I mainly develop using FF). Maybe you are using bleeding edge APIs that Chrome or Edge are driving forward, or other things I am not aware of though.

In my experience such messages are mostly added because people just do not bother (or find the time!) to test on another browser than they use for developing the application, which might happen to be Chrome in your team.

This issue isn't meant as an accusation or attack, I just wanted to bring it to your attention. Not having the time to test it if all developers use a single browser, relying on APIs FF doesn't implement or running into layout differences is unfortunate - I just don't know if that is the case.

### To Reproduce

1. ???
2. See error message recommending chrome

### Expected behavior

See an error message recommending
- Updating your browser
- Using chrome or Edge or, if there wasn't a hard reason initially, another browser like FF or Safari

### Screenshots

![image](https://user-images.githubusercontent.com/20284688/144704419-eb12d06c-f9b9-4983-8df1-94c7ace393fb.png)

### What browsers are you seeing the problem on?

Firefox

**Comment by krusche** [comment]
Artemis support all major modern browsers such as Google Chrome, Firefox, Safari and Edge. However, we already experienced cases when Firefox behaved differently. I changed the description now to be a bit more open for other browsers as well.

**Comment by krusche** [comment]
Some information about happy browsing: http://browsehappy.com

**Comment by krusche** [comment]
Browser distribution: https://en.wikipedia.org/wiki/Usage_share_of_web_browsers
