### ISSUE TITLE
Plagiarism checks: Internal server error when parsing empty submission

### ISSUE THREAD

**Issue by fh314** [ls1intum/Artemis#4448]
### Describe the bug

When running JPlag for a given exercise (H06E01) in our course (INHN0002), an Error 500 is returned which seemingly is caused by a submission that is empty (apart from a .gitkeep file)

### To Reproduce

1. Go to Exercise "H06E01" in the "Fundamentals of Programming (INHN0002)" course
2. Click on "Check plagiarism"
3. Open the Network tab of the Chrome Developer tools
4. Start the plagiarism checks
5. See error 
![image](https://user-images.githubusercontent.com/29736922/144705389-221565a1-2cc0-43d5-837f-9cb77ec10841.png)

### Expected behavior

Plagiarism checks are run and the results are returned. Empty or just template repositories without student submissions could just be excluded (by choice) from the plagiarism checks.

### What browsers are you seeing the problem on?

Chrome

### Additional context

For the given submission that is mentioned in the error message, the student didn't commit or push anything. The repository is just the empty template provided by the exercise.
Exercise _H06E01_ (ID: 5663) in the course _Fundamentals of Programming (INHN0002)_ (ID: 161)

**Comment by fh314** [comment]
May be related to https://github.com/jplag/JPlag/issues/161 and https://github.com/ls1intum/Artemis/issues/3603

**Comment by dfuchss** [comment]
@fh314 I've added a PR (#4453) to update JPlag to its current version. AFAIK the version of JPlag used by Artemis is some custom version. Maybe that resolves some of the issues.
