### ISSUE TITLE
🐛 Modelling editor: Icons floating around / hard to see

### ISSUE THREAD

**Issue by Khalphion** [ls1intum/Artemis#445]
### Describe the bug
The icons belonging to feedback are floating around making it very hard to associate them with the correct item. They should be placed at the center of each object, and for arrows and lines in the middle of the line.

![image](https://user-images.githubusercontent.com/10117554/57657119-aac70200-75da-11e9-8381-6d61c5bb1d06.png)

Maybe consider to add them _onto the items_ (even if they overlay the element) and add a semi-transparent background (circle) around them. They could then act as button to open the feedback.

![image](https://user-images.githubusercontent.com/10117554/57657389-83bd0000-75db-11e9-8bf2-c320d29d77f8.png)

**Comment by jwilland-tum** [comment]
Thank you for your detailed description! We moved this issue to the corresponding Apollon repository (https://github.com/ls1intum/Artemis/issues/445) and tackle this issue with the next release!
