### ISSUE TITLE
Show missed points in failed test feedback

### ISSUE THREAD

**Issue by JohannesStoehr** [ls1intum/Artemis#4452]
### Is your feature request related to a problem?

More and more programming exercises are only graded automatically on Artemis.
To make the grading a bit more fair, students can complain on these exercises if the instructor allows it. One common reason for complaints is a small bug that leads to a big deduction in points. But if the student can't see on how many points they missed out in a certain test they failed, they cannot judge whether a complaint for a small mistake is reasonable, since they might also just loos a small amount of points for certain tests.

### Describe the solution you'd like

Similar to the points granted by passed tests, Artemis should display the missed points for failed tests.

### Additional context

![Bildschirmfoto 2021-12-04 um 17 03 27](https://user-images.githubusercontent.com/38322605/144716300-84e5e7ba-4651-4b2f-b106-0abb1fef2339.png)

**Comment by dfuchss** [comment]
This would be a very interesting feature for our student 👍

**Comment by JohannesStoehr** [comment]
Duplicate of #4393
