### ISSUE TITLE
Artemis Dark Mode

### ISSUE THREAD

**Issue by ge95quz** [ls1intum/Artemis#4456]
### Is your feature request related to a problem?

Immer, wenn ich meine PGdP Aufgaben um 2 Uhr nachts mache, brennt es mir vom 2. Bildschirm aus weiß meine Augen aus.
Ein Dark Mode würde das Arbeiten viel angenehmer machen.

### Describe the solution you'd like

Ein Dark Mode, damit die Augen nicht so schmerzen.

**Comment by Strohgelaender** [comment]
Duplicate of #4404
