### ISSUE TITLE
Instructors cannot override text assessment

### ISSUE THREAD

**Issue by JohannesStoehr** [ls1intum/Artemis#4464]
### Describe the bug

Instructors cannot override a text assessment after a tutor has assessed the submission.
While other exercise types like programming and file upload exercises work just fine, text exercises don't.

This might be linked to #4428

### To Reproduce

1. Create a text exercise
2. Submit as a student
3. Assess the submission as a tutor
4. Try to override the assessment as an instructor and fail to do so.

### Expected behavior

The instructor should be able to override the text assessment.

### Screenshots

Textassessment header:
![Bildschirmfoto 2021-12-07 um 14 34 35](https://user-images.githubusercontent.com/38322605/145038752-ba12ced1-1eaa-4773-9944-229c9c4dfb18.png)

Programmingassessment header:
![Bildschirmfoto 2021-12-07 um 14 35 28](https://user-images.githubusercontent.com/38322605/145038756-8938edec-60f7-4d9e-b271-3a98a1f46f7c.png)

### What browsers are you seeing the problem on?

Safari

### Additional context

I did not verify the modeling exercises. They might or might not work.

**Comment by FlorianGlombik** [comment]
I have just checked modeling exercises on ts1 with release 5.3.5 and for modeling and file-upload exercises the buttons are available but they appear to be broken for text exercises.
