### ISSUE TITLE
`Download PDF` button not working

### ISSUE THREAD

**Issue by taiki-okano** [ls1intum/Artemis#4504]
### Describe the bug

On `Lectures`, when I try to download the merged PDF file by clicking `Download PDF`, it does not work.
Getting individual PDF files works, but getting a merged PDF file does not work.
Considering it started happens recently, it might be related to the recent releases.

### To Reproduce

1. Go to a random lecture.
2. Click on `Download PDF` on the top.

### Expected behavior

It should show up a merged PDF.

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge, Firefox

### Relevant log output

```shell
ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'api/files/attachments/lecture/281/merge-pdf'
```

**Comment by dfuchss** [comment]
@MerlinMehmed see also https://github.com/ls1intum/Artemis/pull/4506#issuecomment-994752714
