### ISSUE TITLE
Add confirmation to "Use SSH"/"Use HTTPS"

### ISSUE THREAD

**Issue by JohannesStoehr** [ls1intum/Artemis#4507]
### Is your feature request related to a problem?

A lot of students interacting with Artemis are still quite new to git and different methods for interacting with a repository. So they don't know the difference between HTTPS and SSH.
Even more the students also have to learn the usage of Artemis itself at the start of their studies and might click some buttons by accident without knowing what they do.

This leads to the problem that a handful of students switches to SSH without knowing and then not being able to find the problem on their own.

### Describe the solution you'd like

Artemis should warn the user when switching the mode between SSH and HTTPS. A short message explaining what the student is currently doing and a confirm button to check if the students know what they are doing should be enough.
And you don't switch between these modes too often, so additional step for the confirmation should not matter too much.

**Comment by krusche** [comment]
There is already a warning when switching on SSH

**Comment by krusche** [comment]
![image](https://user-images.githubusercontent.com/744067/146070378-13ace243-2bca-4bc1-877e-a186bedca682.jpeg)

**Comment by krusche** [comment]
I don't really understand how you can miss that. We can add a yellow triangle to this warning message to make it more obvious. Also rephrasing might help "You can **only** use ssh, if you have set up an ssh key in your account and on your local computer". (account should link to Bitbucket/Gitlab).

But I don't think we should decrease the usability for all users with an additional confirmation. One possibility could be to change the button to a dropdown menu like Bitbucket is doing it.

<img width="345" alt="image" src="https://user-images.githubusercontent.com/744067/146149918-ffc3cf5f-b83c-4615-ab33-f55a8759237a.png">

Then students can at least not click it accidentally.

What does "a lot of students" mean here? Are we talking about 5 or 10 users or more? (keep in mind that thousands of students use Artemis every day)

**Comment by JohannesStoehr** [comment]
It‘s a bit more than 10 students per semester that require active support on Slack/Zulip and probably some more that can figure it out on their own or find the resolved post by their fellow student. 

But the dropdown might be a good compromise that I didn’t thought of 👍
