### ISSUE TITLE
Cannot Change Score of Feedback When Using Assessment Instruction

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#4515]
### Describe the bug

When using structured grading criteria/assessment instructions the score value for the comment cannot be changed.

I’m not sure if the expected behaviour has changed, or if it is a bug.

### To Reproduce

1. Start the manual assessment of a programming exercise (other exercise types with structured grading criteria might work as well.)
2. Add feedback.
3. Before dragging an assessment instruction into the feedback, its score can be changed.
4. Drag an assessment instruction into the feedback. The score can no longer be changed.

### Expected behavior

There exists a scale option when creating the grading criterion in the exercise options. I assumed this to be there to give tutors additionally to the default value the freedom to change the score a bit if they think it is fairer that way. Therefore, I’d expect tutors to be able to edit the score value.

### Screenshots

Inline comment without assessment instruction:
![Screenshot 2021-12-16 at 09-15-54 Programming Exercises](https://user-images.githubusercontent.com/64250573/146333666-63ee8426-4763-4ddc-a1c1-42a7a28011b1.png)
After dragging an assessment instruction into the inline comment box the points value can no longer be edited:
![Screenshot 2021-12-16 at 09-16-09 Programming Exercises](https://user-images.githubusercontent.com/64250573/146333669-690031d4-1890-4659-8871-caa0b47ee582.png)

### What browsers are you seeing the problem on?

Firefox

**Comment by krusche** [comment]
I think this was intended, because grading instructions actually define how many points the feedback should provide.
In such cases, we would like to avoid inconsistencies. However, I am not sure if this was fully realized for all exercise types.

@imstreetspirit can you provide more details?

**Comment by imstreetspirit** [comment]
To avoid potential inconsistencies, we disabled the score after applying the grading instructions with this [PR](https://github.com/ls1intum/Artemis/pull/4104). We should not change this behavior. If the tutors do not think the credit of instruction is not fair, the instructor should adjust the credits and re-evaluate the existing assessment, or not. This functionality is integrated for all feedback editors in Artemis (text-block, code-editor inline comment, general feedback, modeling).

**Comment by b-fein** [comment]
Thanks, then the behaviour makes sense.
In that case the grading scale option when creating the instruction should no longer be needed. At least it is confusing in the current form, as it suggests that the given points when using the instruction can be varied.

**Comment by krusche** [comment]
> Thanks, then the behaviour makes sense.
> In that case the grading scale option when creating the instruction should no longer be needed. At least it is confusing in the current form, as it suggests that the given points when using the instruction can be varied.

What exactly do you mean with grading scale option? Can you provide an example screenshot?

**Comment by b-fein** [comment]
It’s just named Scale now, the tooltip calls it grading scale:
![Screenshot 2021-12-20 at 10-07-47 Programming Exercises](https://user-images.githubusercontent.com/64250573/146741668-b96c9577-6b5c-4ce5-9c82-5e06c45523c4.png)

Tooltip: The grading scale defines the lower and upper limit for assessing student performance levels with this grading instruction.

This sounds like it is/was intended to give tutors information about the range of points they are allowed to give for this grading criterion.

**Comment by krusche** [comment]
Scale is meant to be a string that describes the quality of the submission to help the tutors identify if the instruction fits

It can eg be very good, good, satisfying, bad, etc.

@imstreetspirit We should definitely improve the tooltip

**Comment by imstreetspirit** [comment]
Okay, to keep short and clear the titles, we just named it as Scale, but it is actually a grading scale. I was not aware that it could cause confusion. I'll update the tooltip msg for the grading scale.
