### ISSUE TITLE
🐛 The exercise is not shown when I want to view my submission, so I cannot compare my answers to the solutions.

### ISSUE THREAD

**Issue by LeniRohe** [ls1intum/Artemis#452]
### Environment

<details><pre>
</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by jpbernius** [comment]
Hello @LeniRohe, thanks for reaching out to us. Can you please clarify the problem you are facing.
It would be especially useful if you would describe the steps you took and add a screenshot.

**Comment by Khalphion** [comment]
I know this issue from other students. The submission is only visible after zooming out (it is squeezed at the bottom of the page).

**Comment by oberrich** [comment]
@Khalphion The bug where you weren't able to view your submission on certain devices/displays should be fixed with version 3.1.1 (with #430 I think). I haven't encountered any further issues on mobile other than the modeling exercises scaling horribly (desktop mode helps a lot).

**Comment by SiggZ** [comment]
Thank you @Khalphion and @oberrich. So are there still any issues regarding viewing your submission that you are aware of except for the scaling on mobile devices?
