### ISSUE TITLE
Client Alert Styling Partially Broken

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#4524]
### Describe the bug

The styling of the close button of the alert now has a button around it. Before, the button was not visible and just the black x was shown without a special background.

### To Reproduce

1. Trigger any kind of alert in the client, e.g. by changing a programming exercise.

### Expected behavior

The close icon is usually to the right without the special button-box around it.

### Screenshots

![Screenshot 2021-12-18 at 13-14-35 Exercise Assessment Dashboard](https://user-images.githubusercontent.com/64250573/146642366-6b265cd8-c029-4ac8-9770-bec3f9790830.png)

### What browsers are you seeing the problem on?

Firefox 95.0.1

### Additional context

On current `develop` branch.

**Comment by krusche** [comment]
does this appear for all alerts or only some?

**Comment by b-fein** [comment]
For all, both positive and negative alerts.
