### ISSUE TITLE
Play elevator music while waiting for build to finish

### ISSUE THREAD

**Issue by julKali** [ls1intum/Artemis#4558]
### Is your feature request related to a problem?

I'm always frustrated when I have to wait minutes for my build to complete.

### Describe the solution you'd like

To ease the waiting, I would like to vibe to soft tunes, e.g. https://www.youtube.com/watch?v=VBlFHuCzPgY

**Comment by krusche** [comment]
A build should normally complete within 10-20s for simple exercises. I know that some courses may have more complex exercises and that some of the build agents at TUM have issues with some C exercises. 

We already investigate why some build agents are slow and are working on a fix.

In the meantime, I suggest that you play the music on your own 😉 because this is out of scope for the  Artemis platform

**Comment by just-max** [comment]
if ArTEMiS is lacking :x: this feature :bulb: , i'm afraid we will have to ask for money back :thinking:

<div>
<img src="https://c.tenor.com/lZChuv1gHAcAAAAC/pingu-angry.gif" height="105em" />
<img src="https://c.tenor.com/lZChuv1gHAcAAAAC/pingu-angry.gif" height="102em" />
<img src="https://c.tenor.com/lZChuv1gHAcAAAAC/pingu-angry.gif" height="109em" />
</div>

###### to ease your pain, i offer you

0. :zero::star_struck: install userscript manager: :fist_left::hear_no_evil::fist_right: violentmonkey (or compatible :hammer_and_wrench:) for [firefox :fox_face:](https://addons.mozilla.org/firefox/addon/violentmonkey/) or [chrome :large_blue_circle:](https://chrome.google.com/webstore/detail/violentmonkey/jinjaccalgkegednnccohejagnlnfdag)
1. install userscript: [elevator :elevator: :notes: music :notes: for ArTEMiS :bow_and_arrow:](https://greasyfork.org/en/scripts/437727-elevator-music-for-artemis) from greasyfork :fork_and_knife: :rofl:
2. read :open_book: at least the first two :two_men_holding_hands: lines about permissions :magnet: and :gear::gear::gear: settings
3. shown :syringe::microscope::pill: to relieve frustration for build durations of up to 299 seconds :alarm_clock:. for more information about risks :warning: and side effects :left_right_arrow: read the documentation and consult with your doctor :switzerland: or pharmacist :nerd_face::nerd_face::nerd_face:

absolutely :no_pedestrians: no (0) responsibility for bugs :cockroach:
