### ISSUE TITLE
Missing back button on lecture details page

### ISSUE THREAD

**Issue by tobias-lippert** [ls1intum/Artemis#4560]
### Describe the bug

The lecture details page doesn't contain a back button to go the previous page. This leads to an inconsistent user experience since the exercise details page contains a back button to go back to the previous page.

### To Reproduce

1. Go to  a course that contains lectures.
2. Click on a lecture to open the lecture details page.
3. See that the back button is missing and there's no other possibility to go back, besides using the navigation elements of the web browser.

### Expected behavior

A back button is visible and clickable on the lecture details page that behaves in the same way as the one on the exercise details page.

### Screenshots

![image](https://user-images.githubusercontent.com/84102468/147483269-e15e336d-43ba-4714-9d2d-f686d44c9d91.png)

### What browsers are you seeing the problem on?

Chrome, Firefox

**Comment by krusche** [comment]
The browser contains a back button, so there is no need for Artemis to offer one.

We previously implemented breadcrumbs for a much improved user experience regarding navigation and added it to course administration. We have not been able yet to roll it out to all pages under the section course overview.

We will do that in the coming months and then remove all back button within the Artemis app.

**Comment by julian-christl** [comment]
@krusche Do we need to keep this open then?

**Comment by krusche** [comment]
We can close it
