### ISSUE TITLE
open repository link

### ISSUE THREAD

**Issue by quarz12** [ls1intum/Artemis#4582]
### Describe the solution you'd like

I would love to have a button to open the repository of an exercise instead of always copy pasting its link.

**Comment by julian-christl** [comment]
Please specify the problem you have now so we can better understand what you are trying to solve with this suggestion.

**Comment by quarz12** [comment]
I think this is best explained with an image
![Unbenannt-1](https://user-images.githubusercontent.com/64491670/150991318-e0da72b4-9c7c-4cb2-9d0f-6ece7b1c44c1.png)
this would make it a lot more convenient if you are not on your main pc and want to quickly check in on the repository

**Comment by julian-christl** [comment]
Alright, then I understood correctly. Thanks for the clarification.
