### ISSUE TITLE
Loading animation after submitting code does not work

### ISSUE THREAD

**Issue by FarisBenSaad1** [ls1intum/Artemis#4591]
### Describe the bug

If I push Code to Artemis the Code is tested but I cannot see that Artemis is processing/testing. I can only see that Artemis is doing anything after the tests are done. 

### To Reproduce

1. Clone a Repo
2. Make a change
3. Push to Artemis

### Expected behavior

Artemis should show the loading or processing after pushing and should stop with that if the tests are done

### What browsers are you seeing the problem on?

Chrome

### Additional context

Started on sunday, 09.01.22

**Comment by krusche** [comment]
Can you provide more details and a screenshot. I do not really understand the issue

**Comment by FarisBenSaad1** [comment]
![Screenshot 2022-01-11 at 21 07 22](https://user-images.githubusercontent.com/61881976/149013546-fa6dc59d-9e99-4e7a-a06d-253a9e5da366.png)
Ach hallo Prof. Krusche, 

When I would push code changes in the past, Artemis used to load and show this loading process in the area of the screenshot. Now it doesn't show the loading process anymore. I can only see that Artemis has processed the code if the test results change.

**Comment by Garfield96** [comment]
@krusche We can confirm this issue. It was reported multiple times for exercises in GBS.

**Comment by krusche** [comment]
thanks, we will fix it asap

**Comment by krusche** [comment]
I just tried it out and can confirm, it does **not** work:
1. on the exercise details page 
2. on the exercise overview

It does however work correctly in the online code editor (also for instructors), also when I push code locally using git.

This means, it should probably be relatively easy to fix the issue.
