### ISSUE TITLE
Disable Override Assessment button when the assessment was not changed

### ISSUE THREAD

**Issue by florian-glombik** [ls1intum/Artemis#4592]
### Is your feature request related to a problem?

Within text exercises, the `Override Assessment` button is disabled if no changes were made to the assessment. When changes have been made to the assessment the button is no longer disabled.

This is not the same behavior for the other exercise types `programming exercises`, `modeling exercises` and `file upload exercises`, which is inconsistent. 

<details>
<summary>Button greyed out in text exercises</summary>

https://user-images.githubusercontent.com/63976129/149014145-9b134574-2080-4113-8ace-c6287239a4a1.mp4
</details>

<details>
<summary>Button not greyed out, even though nothing was changed</summary>

![image](https://user-images.githubusercontent.com/63976129/149013815-227e445d-7731-4a76-ba77-c9e31651757b.png)
</details>

### Describe the solution you'd like

I think that the solution for the `text exercises` is quite nice and increases the user experience.

In the best case the logic, or at least parts of the logic that have already been used for the `text exercises` can be reused.

**Comment by canberkanar** [comment]
https://github.com/ls1intum/Artemis/pull/4631

https://user-images.githubusercontent.com/67344158/150694804-16361f85-6b6f-4ebf-a988-0789586cdf42.mp4


https://user-images.githubusercontent.com/67344158/150694820-96425687-765e-435c-a143-acf923a3f4e7.mp4

**Comment by canberkanar** [comment]
@FlorianGlombik can you help me replicate the issue for the programming tasks?
![image](https://user-images.githubusercontent.com/67344158/150694919-091dafd7-993e-491c-ab2f-7d9b93213791.png)

**Comment by canberkanar** [comment]
Override Assessment button is disabled on programming exercise manual assessment page, until the assessment is updated

https://user-images.githubusercontent.com/67344158/150812361-b7bb44f3-c23f-4175-b733-a43af3b8274f.mp4

.
