### ISSUE TITLE
docker-compose failed

### ISSUE THREAD

**Issue by TUTUtu234** [ls1intum/Artemis#4616]
### Describe the bug

I just do as the [link](https://docs.artemis.ase.in.tum.de/dev/setup/jenkins-gitlab/#automated-jenkins-server-setup) at docs. When I came to step 7, I got the outputs as bellow:
![image](https://user-images.githubusercontent.com/44726267/149796498-1d7ab2a7-7760-4eb5-92dc-77e3d2ffa28d.png)
It said that `configure: error: C compiler cannot create executables`, but I don't know how to get the `config.log`. I also tried to solve this througn Google but failed :(.

### To Reproduce

1. Clone the repository：`git@github.com:TUTUtu234/Artemis.git` (forked from this repository two months ago);
2. Gradle Sync...
3. Finished the prerequisites and do as  the [docs](https://docs.artemis.ase.in.tum.de/dev/setup/jenkins-gitlab/#setup-for-programming-exercises-with-jenkins-and-gitlab)，and to the 7th step of [this](https://docs.artemis.ase.in.tum.de/dev/setup/jenkins-gitlab/#automated-jenkins-server-setup);
4. Got the error.

### Expected behavior

Solving the error and then go ahead. If any information needed, please let me know. Thank you~

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

1. OS: Windows 11
2. Docker version 20.10.8, build 3967b7d
3. Dockerfile in `src/main/docker/jenkins`
```dockerfile
FROM jenkins/jenkins:lts

LABEL description="Jenkins with maven, python3.6 and gcc libraries pre-installed for Artemis"

USER root

# I use this to speed up apt install
RUN echo "Asia/Shanghai" > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata && \
    echo "deb http://ftp.cn.debian.org/debian buster main" > /etc/apt/sources.list

RUN apt update

RUN apt install -y wget

# Install Java and Maven dependencies
RUN apt-get install -y maven
RUN cd /usr/lib/jvm && \
    wget https://github.91chi.fun//https://github.com/AdoptOpenJDK/openjdk16-binaries/releases/download/jdk-16%2B36/OpenJDK16-jdk_x64_linux_hotspot_16_36.tar.gz && \
    tar -zxf OpenJDK16-jdk_x64_linux_hotspot_16_36.tar.gz \
    && mv jdk-16+36 java-16-openjdk-amd64 \
    && rm OpenJDK16-jdk_x64_linux_hotspot_16_36.tar.gz
RUN chown -R root:root /usr/lib/jvm/java-16-openjdk-amd64
RUN JAVA_HOME="/usr/lib/jvm/java-16-openjdk-amd64" && export JAVA_HOME
ENV JAVA_HOME /usr/lib/jvm/java-16-openjdk-amd64

# Install C dependencies
RUN apt install -y gcc gdb make libubsan0 liblsan0 libtsan0

# Some packages need to be installed to avoid some known problems for python3.6, see: https://github.com/pyenv/pyenv/wiki/Common-build-problems
# There are some errors before and I used the aptitude to solve them, but I don't know if this will have any side effects. See https://askubuntu.com/a/1056378. 
RUN apt install -y aptitude && aptitude install -y -f make build-essential libssl-dev zlib1g-dev libbz2-dev \
    libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev

# Install Python3.8 
# I just replaced https://www.python.org/ftp/python/3.8.6/Python-3.8.6.tgz with ftp://me@172.18.96.1/Python-3.8.6.tgz
RUN wget ftp://me@172.18.96.1/Python-3.8.6.tgz && \
    tar xvf Python-3.8.6.tgz \
    && cd Python-3.8.6 \
    && ./configure --enable-shared \
    && make -j8 \
    && make altinstall \
    && cat ./config.log
RUN apt install -y python3 python3-pip
RUN cd ..
RUN rm -r -f Python3.8.6/ && rm -f Python-3.8.6.tgz

# Install pytest for python exercises
RUN pip3 install -U pytest

# Install third-party plugins required by Artemis
COPY plugins.yml /usr/share/jenkins/ref/plugins.yml
RUN jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.yml

# Install docker client (if you want a local build agent)
# (Uncomment this line if you want to use a local docker build agent e.g for development purposes)
RUN curl https://download.docker.com/linux/static/stable/x86_64/docker-19.03.8.tgz | tar xvz --directory /tmp && mv -v /tmp/docker/docker /usr/local/bin/docker && chmod +x /usr/local/bin/docker && rm -rf /tmp/docker

# Disables the first-time setup wizard of Jenkins
# (Uncomment this line if you're using jenknis-casc-config.yml for auto-configuration)
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false

USER jenkins
```

**Comment by TUTUtu234** [comment]
I uncommented install python3.8 and just apt instasll python3 so that skiped the error... Abandoned Soldier and Protected Commander.

**Comment by dfuchss** [comment]
May be related https://github.com/ls1intum/Artemis/pull/4407 ?
Also see comment: https://github.com/ls1intum/Artemis/pull/4407#discussion_r783911848

**Comment by TUTUtu234** [comment]
> 可能与#4407有关吗？ 另见评论：[#4407（评论）](https://github.com/ls1intum/Artemis/pull/4407#discussion_r783911848)

Thank you, It provides an idea. I've successfully built by commenting out the erroring code, hope this helps someone else.
