### ISSUE TITLE
Exam Mode: Evaluating quizzes an assessing unsubmitted exams triggers loading animation for both buttons

### ISSUE THREAD

**Issue by fh314** [ls1intum/Artemis#4620]
### Describe the bug

When, as an instructor, you either trigger the evaluation of quizzes or the assessment of resubmitted exams on the exam assessment dashboard, the loading animation is shown for both buttons

### To Reproduce

Prerequisites:
Instructor
Exam

1. Go to the assessment dashboard of an exam
2. Click on either "Evaluate Quizzes" or "Assess unsubmitted Exams"
3. See that loading animation is shown for both buttons

### Expected behavior

Only the loading animation for the given button is shown

### Screenshots

![image](https://user-images.githubusercontent.com/29736922/150108506-6480dd96-0949-4578-9a44-9b8f0d1e2b77.png)

### What browsers are you seeing the problem on?

Chrome

### Additional context

Chrome Version 97.0.4692.71 (Offizieller Build) (64-Bit)
Windows 10 Pro 64Bit

**Comment by Strohgelaender** [comment]
The same error happens when pressing on "Enable second correction: 
![grafik](https://user-images.githubusercontent.com/26540346/151570014-6d99a442-2979-494c-9cbf-be9f3628dfa1.png)
