### ISSUE TITLE
InvalidPasswords Exception is ambiguous

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#4628]
Not my exception, the naming is a bit ambiguous: This exception gets thrown if the provided password doesn't match the requirements (registration, etc.)

_Originally posted by @julian-christl in https://github.com/ls1intum/Artemis/pull/4508#discussion_r787867568_

As this is not a 401, a better name should be chosen and implemented. E.g. "InvalidFormPasswordException" or something along the lines

**Comment by apollofps** [comment]
hi i would like to work on this issue

**Comment by julian-christl** [comment]
@apollofps Sure, we appreciate it. Feel free to take a look at our [docs](https://docs.artemis.ase.in.tum.de/) and if you have questions, let us know. You can fork the repository and create a PR from your fork into our repository.
If you'd like to join our Slack Server, follow the instruction in the Readme.

**Comment by dangcosta** [comment]
Hi @julian-christl , I tried to propose a refactored name for the exception on this PR #4842 (https://github.com/ls1intum/Artemis/pull/4842). See what you think and if you have any feedback, so I would change it.
