### ISSUE TITLE
🐛  Entering the tab key in the text editor does not indent the line but tries to go out to the next field on firefox

### ISSUE THREAD

**Issue by jefryyy** [ls1intum/Artemis#467]
Entering the tab key in the text editor does not indent the line but tries to go out to the next field on Firefox

**Comment by AlEscher** [comment]
Also happens on Chrome (Version 74.0.3729.157 (Offizieller Build) (64-Bit))

**Comment by jpbernius** [comment]
Switching to the next input is the browsers default behavior. We need to implement a custom handler for Tab Key events. An example on how to do that can be found here: https://jsfiddle.net/2wAzx/13/

**Comment by krusche** [comment]
This was fixed in #578 and will be part of the release 3.2.0 which will be available shortly
