### ISSUE TITLE
Modeling Editor: Add "Fullscreen Mode" to enhance student presentations

### ISSUE THREAD

**Issue by QDidThis** [ls1intum/Artemis#470]
### Is your feature request related to a problem?

Im always frustrated when the modeling editor doesnt show the full diagramm.
### Describe the solution you'd like

Add functionality to download the diagram as a pdf/png
### Describe alternatives you've considered

make the modeling editor/grading editor zoomable

**Comment by jpbernius** [comment]
Hello @mahman1234, can you provide a bit more context to the problem your are facing.
Can you provide a link to a submission which is affected. Also, can you share information on your system such as browser and your screen resolution.

**Comment by mahman1234** [comment]
One of my students had the problem using the editor and trying to present in class and one I struggled with is https://artemis.ase.in.tum.de/#/modeling-exercise/462/submissions/122074/assessment?showBackButton=true this one. Its just harder if you cant get an general overview. I'm on Chrome
Version 74.0.3729.131 (Offizieller Build) (64-Bit) with a 13" display and 1280 x 800 resolution

**Comment by mahman1234** [comment]
The download as pdf option would mainly make it more comfortable to present for students

**Comment by mahman1234** [comment]
![artemis](https://user-images.githubusercontent.com/33229711/58096008-6cca6f00-7bd4-11e9-8b60-7d7560a14416.png)

**Comment by jpbernius** [comment]
**💡 Idea:** Lets use Apollon SVG export API to show the entire modle fullscreen.

**Comment by krusche** [comment]
We have a fullscreen toggle available for the markdown editor. Maybe this one can be easily used here as well?

We could add this to the submission page so that students could show their solution.

@filip-gregurevic @TobiasPr 
Can you check if this could be done easily with a similar approach as the full screen button in the markdown editor?

**Comment by jpbernius** [comment]
I may be wrong here, but I think Fullscreen in the Markdown editor is a function of ACE. (So be underlying text editor library.)

**Comment by krusche** [comment]
I don't think so. Have a look at `fullscreen.command.ts`

It simply invokes `requestFullscreen()` (or a browser specific version) on a specific dom element. I guess we could also invoked this on the Apollon canvas (or a surrounding div element)

https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen

This is supported on all browsers

**Comment by TobiasPr** [comment]
Would that be an acceptable solution?

![fullscreen_modelling_editor](https://user-images.githubusercontent.com/22955066/80073855-acb67680-8548-11ea-8680-fce31ca95e21.gif)
