### ISSUE TITLE
Exams: Exercises not included in score do not work

### ISSUE THREAD

**Issue by jpbernius** [ls1intum/Artemis#4704]
### Describe the bug

When crating/editing an exercise, you can select if it counts towards the score:
<img width="524" alt="image" src="https://user-images.githubusercontent.com/6382716/153888729-b7700136-0975-4aa4-a2e8-591cef4e2809.png">

Exam exercises that are not part of the score do not really make sense. Bonus exercises are debatable.

### Expected behavior

Suggestion: Do not allow Exam exercises that are not part of the score

**Comment by mallgaier** [comment]
Closed with #4745
