### ISSUE TITLE
Width of Problem Statement on Text Exercises Limited to 750px

### ISSUE THREAD

**Issue by just-max** [ls1intum/Artemis#4705]
### Describe the bug

When working on a text exercise, the problem statement pane is limited to 750px, even on large monitors. See screenshots. Problem statements may be cut off if they contain non-reflowable elements (images, LaTeX via ` ```latex`). The scrollbar is at the very bottom of the pane. Most of the page is wasted space on large monitors.

### To Reproduce

Create a new text exercise and then go to the page where it can be filled out from the student's perspective. Try to drag the width of the problem statement wider than 750px. Use Responsive Design Mode (in Firefox: Ctrl+Shift+M) to see what the page looks like on e.g. a 4K monitor.

### Expected behavior

The problem statement should be able to take up as much or as little of the page as desired, or the maximum width should depend on available space.

### Screenshots

![ultrawide](https://user-images.githubusercontent.com/17551908/153940436-684ab9ae-b777-4802-a4d0-b6c1c5df0972.png)

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

All browsers.

**Comment by krusche** [comment]
Is it really not possible to make it larger by moving the mouse pointer to the border on the left to the Problem Statement (near ||) and dragging the Problem Statement window larger?

**Comment by just-max** [comment]
Yes, the screenshots show it as wide as it goes. Of course the effect is exaggerated since the screenshot is from a (virtual Firefox) 4K view port, but the limit is there on smaller screens too (and the amount of content cut off is the same).

Dragging to the right to make the pane smaller works, but it doesn't go any further left than shown in the screenshots.

The 750px value was read out from DOM inspector and is apparently set via JavaScript. Setting it manually to a larger value works temporarily, until the drag handle (||) is nudged, at which point the width snaps back to 750px. So I suspect there is some hard-coded limit.

**Comment by krusche** [comment]
thanks for the additional information. I think we can increase the max size to a higher value

**Comment by Strohgelaender** [comment]
The limit is hardcoded in https://github.com/ls1intum/Artemis/blob/develop/src/main/webapp/app/shared/resizeable-container/resizeable-container.component.ts#L43.

**Comment by krusche** [comment]
Can you try to increase it? For example 1500?

**Comment by just-max** [comment]
Is there any reason for having a hard limit? Wouldn't it make more sense to have the maximum width depend on the size of the device?

Of course, setting it to 1500px would be enough to fix our problem.
