### ISSUE TITLE
🚀 Search Box for Student Names

### ISSUE THREAD

**Issue by QDidThis** [ls1intum/Artemis#472]
### Is your feature request related to a problem?

Im frustrated when I search for a student participation to add a presentation and they are unaware their second name is in artemis as well. It makes it hard to find via my browser search
### Describe the solution you'd like

A search box to filter for student names that searches for words independently
### Describe alternatives you've considered

Don't show middle names.

**Comment by krusche** [comment]
I think we are getting the student names directly from TUM Online so removing middle names is not possible. We will consider to add a search box in the future. Thanks for this idea

**Comment by krusche** [comment]
This has been implemented now and users can search for student names and logins. In case of middle names, they can use `*` and `?`. It is available in the scores and participation pages.
