### ISSUE TITLE
CSV Export "Export Results" broken

### ISSUE THREAD

**Issue by Garfield96** [ls1intum/Artemis#4767]
### Describe the bug

The functionality "Export Results" in the "Scores" view of programming exercises produces incorrect results. Some student names contain a comma which is interpreted as an additional column in the exported CSV file.

### To Reproduce

Try to export a programming exercise with a participant who has a comma in its name.

### Expected behavior

Quoted strings in CSV files.

### What browsers are you seeing the problem on?

Firefox

**Comment by krusche** [comment]
I don't think we have usernames with commas

**Comment by krusche** [comment]
ok, I just looked it up and apparently we have two users who have a `,` in the first name. I did not know that this is possible.
As team names could potentially have a comma as well, it's best to use quoted strings as proposed in #4769
