### ISSUE TITLE
Plagiarism Detection Shows Incorrect Data

### ISSUE THREAD

**Issue by Garfield96** [ls1intum/Artemis#4770]
### Describe the bug

During the review of plagiarism cases in Artemis, we saw many identical submissions. While it sometimes happens that students upload identical solutions, the high number of these cases was suspicious. Hence we double-checked the repositories and discovered that Artemis sometimes shows the submission of a single student twice. This can lead to a false reason of suspicion with potentially severe consequences for students. 

### To Reproduce

Since personal identifiers are involved, we can not post a screenshot on Github. We will send a screenshot to @krusche using Slack.

### Expected behavior

The shown submission should belong to the shown student id.

### Screenshots

Sent via Slack

### What browsers are you seeing the problem on?

Firefox

**Comment by krusche** [comment]
This issue was recently fixed
