### ISSUE TITLE
The Discussion tab leaks student e-mail adresses

### ISSUE THREAD

**Issue by Haspamelodica** [ls1intum/Artemis#4786]
### Describe the bug

When visiting an exercise, the Artemis website loads discussion posts from an API endpoint. The response contains e-mail addresses of all students participating in the discussion.

### To Reproduce

1. Open the DevTools of the browser you're using.
2. Navigate to any exercise with some discussion posts. Example in the Tutorial course in the TUM instance: https://artemis.ase.in.tum.de/courses/39/exercises/710
3. In DevTools, find the request to https://artemis.ase.in.tum.de/api/courses/COURSEID/posts?exerciseId=EXERCISEID and look at its response section.
4. Each post object and each answer object contains an author object, which contains details about the author of that post/answer. These details include the e-mail address of the author.

### Expected behavior

Artemis should not leak e-mail addresses of students.

### Screenshots

![grafik](https://user-images.githubusercontent.com/46954095/157069986-afccc4d8-f7bb-4038-a819-4c024ac9e992.png)

### What browsers are you seeing the problem on?

Firefox

**Comment by krusche** [comment]
Resolved in 1b9e096260426f505c0c873b31d258f1ccb9d69c
