### ISSUE TITLE
Activities overlap and are impossible to correct

### ISSUE THREAD

**Issue by ehertel-tum** [ls1intum/ArTEMiS#479]
### Describe the bug
A student created a giant activity and has smaller activities underneath that are now invisible and impossible to correct

#### To Reproduce
1. Create small activities
2. Create a gaint one that overlaps them

#### Expected behavior
Make the smallest activities always on top, or warn the student before submitting that there are overlaps. Or make it possible to drag activities in the submission

#### Screenshots
![image](https://user-images.githubusercontent.com/50831173/58169915-5387f800-7c92-11e9-9487-36142218d24b.png)

**Comment by julianfel** [comment]
![Screenshot from 2019-05-21 10-38-52](https://user-images.githubusercontent.com/50919322/58184628-c2287e00-7cb1-11e9-9da9-07c71479b992.png)

**Comment by jwilland-tum** [comment]
Thanks for reaching out to us! We identified a bug regarding the ordering of elements. The provided pull request should solve this issue so that you can see the diagram as expected.
