### ISSUE TITLE
Feedbacks are cropped

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#4796]
### Describe the bug

Some of our test cases provide a very detailed feedback to the students on what they are doing wrongly.

Since https://github.com/ls1intum/Artemis/blob/develop/src/main/java/de/tum/in/www1/artemis/config/Constants.java#L119 defines a max character limit of 5000 chars per feedback, the feedback of some tests gets cropped without warning.

E.g., a test that lists all Checkstyle errors (currently I cannot show other tests, because the exam is running until the end of march)
In general we have interactions (text user interface) that will be simulated via unit tests. 
If a response is wrong, the student gets details about the input/output of the TUI until the error occurs.
Therefore, this output should not be truncated.
![image](https://user-images.githubusercontent.com/22198798/157637067-939aebd6-d0c1-411c-b233-e337fce61a44.png)

### To Reproduce

Create a test case with detailed output (more that 5000 Chars) and let it fail.

### Expected behavior

Students should always see the whole feedback.

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

Any browser

**Comment by krusche** [comment]
The limit is on purpose. I don't think Feedback with more than 5000 characters is really needed and would add value to the learning experience.
