### ISSUE TITLE
Double clicking on connecting Lines

### ISSUE THREAD

**Issue by jfly609** [ls1intum/Artemis#480]
Problem:
when double clicking on a line connecting two Objects in the modeling editor, it may not opens the line editor window if the two objects are to close together(I think the system wants to rearrange the line when clicking the line)

suggestion: 
lower the distance which decides if you are in "rearrange mode" and therefore increase the space in which a double click opens the line editor window 

other suggestions:
open line editor with right-click (tbh I have not checked whether there is a button which you can press during a click to open the line editor window)

(sorry I pressed Enter to early so I had to Edit the Request message)

**Comment by jwilland-tum** [comment]
Thanks for your suggestion! We will look into this issue. Our suggestion would be to start the "rearrange mode" only after the user has dragged the relationship end at least 5 pixels. If this is not the case, the "rearrange mode" then should not interfere with the double click to open the update pane.
We will also consider using the context menu (right click), yet only as a support for a functioning solution. We try to prevent the usage of feature which behave differently in different environments (e.g. desktop vs. mobile).

**Comment by jwilland-tum** [comment]
This issue is now solved in the current release (https://github.com/ls1intum/Apollon/pull/64).
