### ISSUE TITLE
Auto correction of modeling exercises

### ISSUE THREAD

**Issue by DeRealMorgan** [ls1intum/ArTEMiS#481]
Each modeling exercise has a sample solution. 
My idea is to automatically compare the solution of students to the sample solution. 

1. If it is identical the student can get the points right away and the exercise does not have to be marked by the tutors
- this will happen (as there are 2000 students) and especially in-class exercises are identical (as they are copied from the slides anyway).
2. If the solution differs the exercise still has to be marked by the tutors as usual.

I think this "idea" will decrease the amount of exercises that need to be marked (leaving more time for the tutors)!

**Comment by jmaximilian2** [comment]
Artemis already contains a semi automated grading system for modeling exercises named Compass that basicly uses manually assessed submissions of tutors to automatically grade similar submissions. Currently Compass is disabled in production while it is being reviewed and improved.
