### ISSUE TITLE
Individual selection of text block for assessment takes first matching pattern instead of marked text part

### ISSUE THREAD

**Issue by willergeorg** [ls1intum/Artemis#4819]
### Describe the bug

Given a text that contains reoccurring text blocks, e.g. the word "trigger". If a tutor now marks any other occurrence of this block except the first one, the assessment gets attached to the first occurrence of the block. I added a screencast showing the problem below.

### To Reproduce

1. Go to an unassessed text submissions with reoccurring text blocks
2. Press ALT (for Windows, don't know which button it is for Mac) and mark any occurrence of this block except the first one
3. Keep ALT pressed and click 'Assess'
4. The selection should jump to the first occurrence and the input field for the assessment is attached to it.

### Expected behavior

The selection should stay to the text block the tutor actually marked.

### Screenshots

https://user-images.githubusercontent.com/80622272/158579578-c16ff70b-05bd-4bb1-a963-0349761f07fa.mp4

### What browsers are you seeing the problem on?

Chrome

**Comment by Strohgelaender** [comment]
Duplicate of #3407?

**Comment by willergeorg** [comment]
> Duplicate of #3407?
Indeed, thanks for mentioning!
