### ISSUE TITLE
Invisible Interface behind the component by editing 

### ISSUE THREAD

**Issue by yongzeCheu** [ls1intum/Artemis#483]
### Environment

<details><pre>
</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by krusche** [comment]
Can you please provide more details and a screenshot?

**Comment by jwilland-tum** [comment]
@yongzeCheu Is this related to https://github.com/ls1intum/ArTEMiS/issues/479?

**Comment by yongzeCheu** [comment]
![WeChat Image_20190524131554](https://user-images.githubusercontent.com/46302924/58324085-1e141380-7e26-11e9-8068-69fab7c18dc8.png)
I am not sure if it is the same problem. But this interface only comes up when I have submitted the task. Before submission, I cannot see this interface at all
