### ISSUE TITLE
Add "locked" quizes that tutors can unlock to allow student participation

### ISSUE THREAD

**Issue by jerhard** [ls1intum/Artemis#4834]
### Is your feature request related to a problem?

We want to motivate students to participate in tutorials and keep up-to-date with the contents of the lecture. Our idea is to provide quizzes  for the course for which participation is only unlocked for a student when they visit a tutorial. 

Then, students could be awarded bonus points for successful participation in the in-tutorial quizzes.

### Describe the solution you'd like

One possibility to implement quizzes that can be unlocked would be to require a passphrase for quiz-participation. This could work as follows:

- Students  are requested to enter a passphrase when they want to participate in the given quiz. 
- Tutors are able to generate a passphrase for a quiz exercise that is currently within the participation period. 
- Tutors can share the passphrase to students in their tutorial. This step need not be implemented in Artemis; sharing of the pass phrase could simply happen over e.g. a black board.
- Students can access and participate in the quiz exercise with the pass phrase. The passphrase allows unlocking the quiz only for a limited time period, e.g. 15 minutes. If a student enters the passphrase to late, the quiz won't be unlocked.

As usual, students can only participate once in a quiz to gain points. 

### Describe alternatives you've considered

We considered using the quiz-feature as is, but this would not conveniently allow to enforce that the quiz is worked on during a tutorial.

**Comment by julian-christl** [comment]
Not related to whether to implement it or not in the end but just to extend one point:

The passphrase should be kept simple in case students are not able to copy it digitally. For example, it could be a four-digit pin. It shouldn't be a Base64 String.
