### ISSUE TITLE
Feature: JPlag 4.0

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#4861]
### Is your feature request related to a problem?

JPlag will release a Version 4.0 in the future.
They especially ..
* created a new [UI](https://jplag.github.io/JPlag/) that shows a good comparison of code [1]. E.g., https://github.com/jplag/JPlag/issues/192#issuecomment-997798228
* re-added clustering mechanisms [2]

Some features of them could be used in Artemis as well.

[1] https://github.com/jplag/JPlag/pull/287
[2] https://github.com/jplag/JPlag/pull/281

### Describe the solution you'd like

Include important features of JPlag to Artemis if JPlag 4.0 will be released. I'll mention that in this Issue as well :)

**Comment by ge65cer** [comment]
JPlag 4.0 is not released yet, so I'll mark this as blocked. Feel free to ping once it's available.

**Comment by dfuchss** [comment]
JPlag 4 is released now

**Comment by krusche** [comment]
Are there any breaking changes or can we simply adopt the new version immediately?

**Comment by dfuchss** [comment]
There are some breaking changes. I can help here within the next weeks.

**Comment by ge65cer** [comment]
Implemented in https://github.com/ls1intum/Artemis/commit/c166b4cba7bffc34d3b8834aff9779c956cabb4e
