### ISSUE TITLE
Copying Lectures from one Course to another

### ISSUE THREAD

**Issue by philippzagar** [ls1intum/Artemis#4880]
### Is your feature request related to a problem?

As of the last winter semester, the iPraktikum is using the Artemis platform in order to conduct the intro course which teaches about 60-80 students the fundamentals of Swift and iOS development. 
This intro course is also held this semester, again via the Artemis platform, therefore requiring a new course. As the content of the course stayed mostly the same, we copied over the Exercises (which automatically also creates the required repositories etc.). However, the same isn't possible for the Lecture material. The tutors had to manually copy over all Lectures together with each individual lecture unit to this semester's Artemis intro course, consuming multiple work hours.

### Describe the solution you'd like

A simple copy-and-paste functionality from one course to another, similar to the copying of the Exercises (which is already possible), should resolve the need for manual copy-and-pasting, which can take hours for larger courses. 
The solution I'm envisioning is basically the same as the Exercise-copying (see image below), enabling the course instructor to click "Import Lecture" and then select the respective lectures out of all to him/her accessible lectures. 
This feature will drastically reduce the time to set up new Artemis courses which are very similar to old ones.

<img width="1697" alt="Screenshot 2022-03-30 at 15 05 26" src="https://user-images.githubusercontent.com/25406915/160841309-85af7ff1-bfd4-4baa-a4cd-0a0d577353f5.png">

<img width="793" alt="Screenshot 2022-03-30 at 15 07 08" src="https://user-images.githubusercontent.com/25406915/160841636-63de8752-3e88-49cf-92c2-36746c7120d2.png">

### Describe alternatives you've considered

No real alternative, except for manual copy-and-pasting ;)

**Comment by ge65cer** [comment]
Hello @philippzagar, thank you for documenting this issue. I agree that manual copy-pasting is not a satisfying solution here.

As you might know, each `lecture` has multiple `lecture units` which in turn are connected to `learning goals`. By only copying the lectures these valuable mappings would be lost. 
The question is if there exists a use case where one would only copy selected lecture content and not wish to clone the whole course (e.g., all lectures with units  and learning goals). I'd argue that mostly the second use case is more applicable.  Do you agree?

**Comment by ge65cer** [comment]
I've decided with @krusche that for a first version, we will add the feature to import one or multiple lectures (thereby duplicating all lecture units and attachments to the new course) just like with exercises.
Later, we might revisit this in regard to also copying the learning goals while simultaneously keeping the mappings between the objects.

**Comment by philippzagar** [comment]
Perfect, thanks for quickly resolving the issue :)

**Comment by ge65cer** [comment]
Hey @philippzagar! Good news: Development is complete, and you can expect this feature to be included in the next Artemis version.
