### ISSUE TITLE
Add Prerequisites to Courses

### ISSUE THREAD

**Issue by ge65cer** [ls1intum/Artemis#4894]
### Is your feature request related to a problem?

Artemis now allows adding learning goals, lectures, and lecture units to a course. Thereby, it is able to represent the content of a course.
However, currently there is no way of showing students the prerequisites required to attend the course.
As of right now, these must be listed on an external site, such as [here](https://ase.in.tum.de/lehrstuhl_1/teaching/1175-eist-2022) for EIST in the summer term.

### Describe the solution you'd like

Artemis should be able to, similar to the implemented learning goals, manage a list of prerequisites for a course.
These should be displayed to students even before the official start of the course, so that they can refresh their knowledge and make a self-assessment if they have the knowledge to successfully participate.
Additionally, they could include links to external resources for students to repeat the topic.

In a future version, a quiz or exercises could be added to the prerequisites to encourage students towards an objective assessment of their skills.

### Describe alternatives you've considered

The current alternative is that the prerequisites must either be listed on an external website or be added to the general course description.

Another solution could be mark lecture content as a prerequisite (e.g., using a tick box), without introduction an additional class to the data structure.

### Additional context

Issue filed on behalf of @krusche

**Comment by ge65cer** [comment]
**Specification:**
I think it would make the most sense to create a separate class for prerequisites that are each linked to one course (1-n relationship). They consist of a _title_ and an optional _description_, where links to external material may be added (Markdown support).

**Outlook:**
Later, exercises (such as quizzes) can be created and linked to one prerequisite, similar to how this is currently possible with learning goals. Completion of such exercises could eventually be made mandatory to sign up for the course or the achieved scores could be incorporated in the student's adaptive learning path during the course. For that purpose, prerequisites could potentially be mapped to individual learning goals.

**Comment by krusche** [comment]
Could we simply add a new relationship between `Course` and `LearningGoal` called `prerequisites`?
In fact, a prerequisite includes a **competence** which is expressed with a **learning goal**. So in some sense, learning goal and competence are similar. We could even rename learning goal to competence in the future.

Then, it could be possible to link the learning goal of one course as a prerequisite to another course. This would in fact help to check if students have already gained specific prerequisites for a course or not.

**Comment by ge65cer** [comment]
As discusses privately, we'll move on with a minimal approach and only add a new n-n relation for prerequisites between courses and learning goals.
