### ISSUE TITLE
Filter future lectures

### ISSUE THREAD

**Issue by jpbernius** [ls1intum/Artemis#4930]
### Is your feature request related to a problem?

The **Lectures* tab shows all lectures to students, regardless of the associated date.
If I create a bunch of lectures at the beginning of the semester, the lecture tab is already messy.

Example:
<img width="1702" alt="image" src="https://user-images.githubusercontent.com/6382716/163211895-deb73e40-a63c-4658-9803-67dcf9f5a8c8.png">

### Describe the solution you'd like

Add a filter, similar to the one in the exercises tab, to easily allow hiding future lectures. (I'd even hide them by default.)

**Comment by jgrant12345** [comment]
Is this issue free for anyone to work on?

**Comment by jgrant12345** [comment]
Can anyone work on this issue?

**Comment by yassinsws** [comment]
@nikirovast  are you currently working on this ?

**Comment by yassinsws** [comment]
@jpbernius can you mark this as solved? I don't know who solved this but the upcoming lectures are no longer shown as described.
