### ISSUE TITLE
Two Submissions are Created for Commits in Programming Exercises

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#4973]
### Describe the bug

For many commits two submissions are created:
- one without build result, and
- one with a build result.

In our case it not problematic except for the unnecessary database entries and resulting UI clutter. However, in exercises that use submission policies based on the number of submissions students might get a points deduction even if they shouldn’t.

### To Reproduce

I can see this for submissions from different students. The students in this case used the online code editor to submit.
I was not able to reproduce this issue on artemis-test2 but in our instance the issue is present for many submissions for different students.

### Expected behavior

Only one submission is created per commit.

### Screenshots

![Screenshot 2022-04-26 at 14-37-52 Participation](https://user-images.githubusercontent.com/64250573/165302670-befd8c1b-d072-4acd-b912-c9eb5a50b4b7.png)

In this example the bug happens only to builds where the build fails. In other places it also occurs when some tests pass.

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

- Artemis 5.7.4
- Gitlab/Jenkins setup
- The method around the log message in `ProgrammingExerciseGradingService` (`createAndSaveFallbackSubmission`) has been introduced in #4830
    - This method also seems to create the second submission that is not really needed.

### Relevant log output

```shell
2022-04-25 14:41:22.623  INFO 26810 --- [.1-8080-exec-31] t.i.w.a.s.p.ProgrammingSubmissionService : NotifyPush invoked due to the commit <HASH01> by <STUDENT> in 
2022-04-25 14:41:29.825  INFO 26810 --- [.1-8080-exec-31] t.i.w.a.s.p.ProgrammingSubmissionService : Create new programmingSubmission with commitHash: <HASH01> for participation <000000>
2022-04-25 14:41:34.314  INFO 26810 --- [.1-8080-exec-41] d.t.i.w.artemis.web.rest.ResultResource  : Artemis received a new result for build plan <BUILD_PLAN>-<USER_ID_STUDENT>
2022-04-25 14:41:34.339  WARN 26810 --- [.1-8080-exec-41] .a.s.p.ProgrammingExerciseGradingService : Could not find pending ProgrammingSubmission for Commit Hash Optional[<HASH01>] (Participation <000000>) Will create a new one subsequently...
2022-04-25 14:41:37.350  INFO 26810 --- [.1-8080-exec-41] d.t.i.www1.artemis.service.ScoreService  : Updated an existing participant score. Was: StudentScore{…}
2022-04-25 14:41:37.382  INFO 26810 --- [.1-8080-exec-41] d.t.i.w.artemis.web.rest.ResultResource  : The new result for <BUILD_PLAN>-<USER_ID_STUDENT> was saved successfully
```

**Comment by b-fein** [comment]
Thanks for looking into it.

We did not make any changes to our CI system. By the logs the first submission is created in Artemis at 14:41:29.825, then for some reason can’t be found at 14:41:34.339. That is why I think that there is some issue within Artemis.

I now found a case where the submissions without and the one with a result are in different order. There seems to a race-condition when the system is under load which is why it isn’t really reproducible on the test systems.
Could it be that querying the commit/push date from Gitlab in `ProgrammingSubmissionService#notifyPush` sometimes takes too much time so that the first submission is not actually fully created by the time the result arrives? Therefore, it cannot be found, but will still be created afterwards.

![Screenshot 2022-04-27 at 08-03-17 Participation](https://user-images.githubusercontent.com/64250573/165451754-34695175-f6c7-470f-a4cc-269712f8804e.png)

**Comment by dfuchss** [comment]
As far as I can see, we also have such cases on our systems.

**Comment by julian-christl** [comment]
So I have seen this too. While usually, it's only about milliseconds, especially in exams it could be relevant. If they pushed before according to the VCS but the report takes just a bit longer it could be discarded.
=> While usually this can be neglected, I think as it's about exams, we shouldn't.

So I'd suggest immediately saving the submission with the current date and after that retrieving the precise submission date from VCS to make sure we handle the edge case.
=> We shouldn't get a race condition whilst still getting the most accurate date.

**Comment by krusche** [comment]
@julian-christl I disagree. For exams this will not be an issue. I can tell you more details personally. I removed the corresponding code block in the commit c29811257a392b36520b0a988b100fb1606fcb7b

**Comment by krusche** [comment]
In 941c92596e16a2cfbe8247cc90576aca778883ed I moved the submission date creation to the top of the method, so this will improve the accuracy for a couple of milliseconds
Before, I also added a TODO that we should store the default branch of a participation in the database to avoid that we retrieve this all the time. It cannot change after the repository was created, so it is much more efficient to store it once instead of retrieving it in several places
