### ISSUE TITLE
Warning when leaving text-editor and text isn't saved

### ISSUE THREAD

**Issue by DatMoser** [ls1intum/Artemis#498]
### Is your feature request related to a problem?
I'm usually working on my laptop which has swiping gestures and it sometimes happens, that I'm working on one of the exercises and then try to have a look at my notes on another virtual desktop and try to swipe to the left, but somehow Mac detects a two finger slide, which means going back to the last website and I leave the text editor and my already written text is gone.

### Describe the solution you'd like
This could be prevented by listening if changes were applied to the textarea. When the user then tries to go back, he gets warned with an alert if he/she really wants to leave the site without saving the text.

### Describe alternatives you've considered
An alternative would be that the program automatically saves changes made to textarea.

### Additional context
. / .

**Comment by krusche** [comment]
@rpadovani could you have a look? Should be easy to implement, we already use such a feature in the quiz creation dialog. As you are most experienced with the text editor, could you please add this? Should not be a big effort.

Thanks!
