### ISSUE TITLE
Creating an attachment unit spawns two notifications

### ISSUE THREAD

**Issue by ge65cer** [ls1intum/Artemis#4986]
### Describe the Issue

When an instructor creates an attachment unit for a lecture, Artemis will show two notifications.

### To Reproduce

1. Login to Artemis as Instructor
2. Go to Units in the Lecture Overview
3. Create a new Attachment Unit
4. See two notifications

### Expected behavior

One notification banner would be enough. 😉 

### Screenshots

<img width="600" alt="Screenshot 2022-04-28 at 08 48 34" src="https://user-images.githubusercontent.com/102237363/165694120-b81e91f5-f9cf-4f25-8c0a-ff991e550fbd.png">

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge, Firefox

### Additional context

Because there are two requests (first the attachment unit is created, then the file is uploaded), Artemis shows two notifications.

**Comment by ge65cer** [comment]
@julian-christl Fixed in #5427 ?

**Comment by julian-christl** [comment]
I think so, please check on the current develop to be sure before closing.
