### ISSUE TITLE
Adblocker extension blocks text assessment API endpoint

### ISSUE THREAD

**Issue by ge65cer** [ls1intum/Artemis#4989]
### Describe the Issue

Almost everyone is using an adblocker nowadays.
When assessing a text exercise, the adblocker extension blocks our client request to `/api/analytics`.
However, the error message is rather not descriptive, and you have to look into the console to see that the request was blocked (and the server is actually reachable just fine).

### To Reproduce

1. Login to Artemis as Instructor with Adblocker extension
2. Go to the Assessment of a Text Exercise
3. Try to assess the text exercise
4. See the error

### Expected behavior

The request should not be blocked, we could rename the API endpoint for better user experience.

### Screenshots

<img width="800" alt="Screenshot 2022-04-28 at 21 58 32" src="https://user-images.githubusercontent.com/102237363/165835566-38369b97-276a-43db-9929-106bb5fb062c.png">

### What browsers are you seeing the problem on?

Firefox with uBlock Origin extension

### Additional context

_Originally posted by @ge65cer in https://github.com/ls1intum/Artemis/issues/4987#issuecomment-1112602817_

**Comment by Dominik-Weinzierl** [comment]
https://user-images.githubusercontent.com/60005702/165836260-8cac472b-7161-47a9-bccd-98eeee34fd93.mp4
