### ISSUE TITLE
Changing sort order of assignments incorrectly changes course information

### ISSUE THREAD

**Issue by jneubrand** [ls1intum/ArTEMiS#499]
### Describe the bug
When the sort order of some assignments is updated, the course information box changes to display inaccurate information even though no change is needed.

#### To Reproduce
Go to the assignment list. Change the sort order (or “change” it to the same value). Note that the number of assignments in the separate groups changes while the total remains constant.

#### Expected behavior
Number of assignments is unchanged.

#### Screenshots
<img width="424" src="https://user-images.githubusercontent.com/15683245/58403199-5f910280-8062-11e9-8998-78c8c4c7c00b.png">

_“2 + 2 = 5”_

### Environment
irrelevant

**Comment by krusche** [comment]
Rhanks for reporting. Will be fixed in the next release.
