### ISSUE TITLE
</span>-elements vissible in plagiarism check matches

### ISSUE THREAD

**Issue by rhubinger** [ls1intum/Artemis#5015]
### Describe the bug

After clicking through some plagiarism matches, \</span>-elements start to appear in the submissions as seen in the picture.
 

### To Reproduce

1. Go to an exercise and run the plagiarism check
2. Click through some matches and then suddenly the </span> elements start to appear
I couldn't figure out how to trigger it exactly, but it seems that the bug occurs more likely at matches with a higher index (>50) 

### Expected behavior

The text should be shown without the </span> Elements

### Screenshots

![Bug_plagiarismcheck](https://user-images.githubusercontent.com/62466619/166521695-58871e99-a283-4170-89f3-8e518980f14d.png)

### What browsers are you seeing the problem on?

Firefox

**Comment by ge65cer** [comment]
Pinging @filip-gregurevic
