### ISSUE TITLE
`Exam Mode`: Not all annoations are shown in the editor (programming tasks)

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#5030]
### Describe the bug

After our exams of the last term, we have recognized some missing annotations that are present in the REST Response and also visible in the List of all Annotations. Nevertheless, inline the annotation is not visible.

I'll mark it as prio high (feel free to change that) as it effects the assessment of tasks directly.

### To Reproduce

Unknown. I can provide further details in Slack. But no error is shown in the logs of the client.

### Expected behavior

Annotations shall appear inline.

### Screenshots

REST Response
![image](https://user-images.githubusercontent.com/22198798/167077115-f8da6dc5-f1cc-473c-b125-310cfbdaae74.png)

Editor Excerpt:
![image](https://user-images.githubusercontent.com/22198798/167077170-2cf1c45a-1fbc-4a2f-ab35-ea0bfd4bbca0.png)

### What browsers are you seeing the problem on?

Firefox

**Comment by Shirkanesi** [comment]
I've inspected the actual submission you've used as example even more.
Seems like the editor only shows inline-annotations from the first correction-round but not the second one :)

**Comment by Shirkanesi** [comment]
I would suggest this is caused by [this line](https://github.com/ls1intum/Artemis/blob/ca4cde922bb3f6afa7db24197bd5053a2f8d4fd8/src/main/webapp/app/exercises/programming/shared/code-editor/container/code-editor-container.component.html#L42):
```ts
 [feedbacks]="(participation?.results && participation.results!.length > 0 && participation.results!.first()!.feedbacks) || []"
```
as it will always use the first result. However, I think, the **newest** (is this the last?) result should be used.

**Comment by dfuchss** [comment]
I would agree on @Shirkanesi the current feedbacks were in the second entry f the results

**Comment by Dominik-Weinzierl** [comment]
Yes - i agree :+1: was also able to reproduce this behavior locally. I create a pull request to solve that issue
