### ISSUE TITLE
Dark mode: Classes names in UML Diagrams are not visible in dark mode.

### ISSUE THREAD

**Issue by Johnypier** [ls1intum/Artemis#5038]
### Describe the bug

When opening any exercise which has UML diagrams in it, you can notice that class names are not visible.

![Снимок экрана 2022-05-07 142144](https://user-images.githubusercontent.com/98538725/167254233-784e7fbe-1294-49f5-9f78-7b5654fc2f49.png)

### To Reproduce

1. Go to any exercise with UML diagram.

### Expected behavior

Make class names visible and maybe all diagrams also have dark mode.
Browser extension used for this screenshot - Dark Reader.

![233](https://user-images.githubusercontent.com/98538725/167254267-a78e7ade-dbb1-457e-95c9-1381f3735e91.png)

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by krusche** [comment]
This is related to PlantUML. I noticed that the diagrams also do not reload when users switch between dark and light mode.
This might also be related to a migration of existing problem statements.

In our previous tests, the diagrams rather looked like this

![image](https://user-images.githubusercontent.com/744067/167262254-138cb934-0b1c-4eff-a6be-eab7e18ecca1.png)

**Comment by krusche** [comment]
Seems to be a migration issue. We will manually remove the skins in the problem statements of the exercises in which the skins remain
