### ISSUE TITLE
Dark Mode: Associations in UML Diagrams

### ISSUE THREAD

**Issue by Johnypier** [ls1intum/Artemis#5040]
### Describe the bug

Composition Association is not displayed correctly. It looks similar to aggregation.

![1](https://user-images.githubusercontent.com/98538725/167257811-cc0c50f2-6b4f-41e3-9cb3-a91005ec0071.png)

### To Reproduce

1. Go to any exercise with UML editor
2. Make a composition association
3. See error

### Expected behavior

"Diamond" in composition should be black.

![2](https://user-images.githubusercontent.com/98538725/167258860-119b7825-af50-4b0d-9438-ea227a05d6b5.png)

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by krusche** [comment]
This is an issue that needs to be fixed in https://github.com/ls1intum/Apollon
Can you please open it there?

**Comment by Johnypier** [comment]
> "Diamond" in composition should be black.

Done, thank you.
