### ISSUE TITLE
Discussion tab: Introducing a "search topic" button/textfield

### ISSUE THREAD

**Issue by Trackti** [ls1intum/Artemis#5041]
### Is your feature request related to a problem?

Hey, sometimes it can feel annoying to scroll through a large amount of posts in the discussion tab of exercises/assignments. Determining, if a question that you have, has already been posted and asked can feel tedious at times.

### Describe the solution you'd like

Introduce a "search topic" button/textfield, with which you could filter certain topics with keywords. There is space for it next to the "Discussion" headline(see photo).
![Screenshot Artemis](https://user-images.githubusercontent.com/92391589/167260599-bbf5be5b-19a0-4540-96e3-2e285a9965ef.png)

**Comment by krusche** [comment]
You can search in the Discussion tab and filter the shown posts to one specific exercise or lecture

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/744067/167261948-7ea7807c-7185-4faf-bf17-484949651c8b.png">
