### ISSUE TITLE
Dark Mode: Code block's background is white.

### ISSUE THREAD

**Issue by Johnypier** [ls1intum/Artemis#5043]
### Describe the bug

Code block's background is white in exercise description.

![222](https://user-images.githubusercontent.com/98538725/167263878-aff4cdd1-06f3-4d97-b0da-ef638adebc36.png)

### To Reproduce

1. Go to any exercise which has code block in description.
2. See error.

### Expected behavior

Code block's background should be gray or another dark color.

![111](https://user-images.githubusercontent.com/98538725/167263936-c17b44fd-02d4-4598-916b-2d8c79f9dd2c.png)

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by bassner** [comment]
This issue is not introduced by dark mode.

The background color of these blocks has been explicitly set by the instructors of the course while writing the problem statement using some custom CSS overrides.

Please contact your course instructors and ask for a fix if required.
