### ISSUE TITLE
Dark Mode: White font on (yellow | light green) hard to read

### ISSUE THREAD

**Issue by Shirkanesi** [ls1intum/Artemis#5045]
### Describe the bug

When using the dark-mode the white text on (yellow | light green)background is quite hard to read.
(see screenshots below)

### To Reproduce

Navigate through the UI and look for (yellow | light green) elements (e.g. buttons, progress-bars, file-names in the editor)

### Expected behavior

The colors should be adjusted so text is still readable.

### Screenshots

In the assessment-dashboard:
![grafik](https://user-images.githubusercontent.com/30196411/167273045-6a98b751-048d-4413-bcfe-4839894cff6b.png)

In the code-editor:
![grafik](https://user-images.githubusercontent.com/30196411/167273064-ecd5075b-5340-4c26-96c3-4f2a08bce4f7.png)

In the code-editor for assessment:
![grafik](https://user-images.githubusercontent.com/30196411/167273112-f5e91e9f-d7b0-4239-a60d-4edb927e2e20.png)

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

**Comment by bassner** [comment]
That looks rather like an opinion than a bug.

The colors are mostly taken from https://bootswatch.com/darkly/, a widely accepted dark theme for Bootstrap. To me, the example you showed look fine to be honest.

Unless we get more similar feedback, I'd keep the colors for now.

**Comment by Shirkanesi** [comment]
> That looks rather like an opinion than a bug.

Of course. Colors are always opinions.

> The colors are mostly taken from https://bootswatch.com/darkly/, a widely accepted dark theme for Bootstrap. To me, the example you showed look fine to be honest.

I totaly agree. The text on their example is quite readable. It might be a combination of the font(-size and -weight) used in Artemis and my screen. I've looked at it on a completely different screen, there it looked good.

I think we should totaly wait whether more people have problems with it on their system or if this is just a "me-problem".

**Comment by ge65cer** [comment]
Closed in favor of #5091
