### ISSUE TITLE
"Assess" button for text exercises isn't where it should be

### ISSUE THREAD

**Issue by TheTrueVester** [ls1intum/Artemis#5047]
### Describe the bug

When selecting text to assess by holding alt, the "assess" button is always significantly lower than it should be.

### To Reproduce

1. Go to the course management
2. Click on Assessment Dashboard
3. Pick the exercise dashboard of a text exercise
4. Click start new assessment
5. Select a portion of text by holding alt

### Expected behavior

The assess button should be directly above the highlighted text.

### Screenshots

![image](https://user-images.githubusercontent.com/47668936/167293524-4ba53fd8-1397-403c-85e3-4d0daf32d07f.png)
![image](https://user-images.githubusercontent.com/47668936/167293541-f0e4edb0-0675-4d2f-add2-838e87bee77a.png)

### What browsers are you seeing the problem on?

Chrome

**Comment by krusche** [comment]
I think @valeriebucher is already working on this as part of her current PR #5035, right?

**Comment by TheTrueVester** [comment]
> I think @valeriebucher is already working on this as part of her current PR #5035, right?

Oh thanks, I overlooked her post.
