### ISSUE TITLE
`Discussion`: Add search bar and filters to the exercise detail page

### ISSUE THREAD

**Issue by Strohgelaender** [ls1intum/Artemis#5050]
### Is your feature request related to a problem?

Especially in large courses, students will ask many questions using the discussions section of an exercises. In this case, it can be quite hard for other students to find anwers for their specifc problems.

### Describe the solution you'd like

The discussions page already contains a search bar and some filters. This functionallity should also made accessable on the exercise, to allow the students a more direct access to this feature.

During this we should also consider moving the "add post" button to the top of the side.

### Additional context

Example of a very long discussion page:
![grafik](https://user-images.githubusercontent.com/26540346/167315882-850b2f0b-daa2-4537-a5a6-eac5cbeac922.png)

**Comment by Dominik-Weinzierl** [comment]
Similar to https://github.com/ls1intum/Artemis/issues/5041

**Comment by krusche** [comment]
I talked to @canberkanar 
He will add two elements from the main discussion page

<img width="732" alt="image" src="https://user-images.githubusercontent.com/744067/168777725-fc480476-8d81-42fd-8a2c-19b2028dbe50.png">

<img width="394" alt="image" src="https://user-images.githubusercontent.com/744067/168777805-29fcd246-3514-4e67-912d-0b849adbd380.png">
