### ISSUE TITLE
Quiz exercises: The check box for start time does not validate if certsanly you insert a start time

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#5052]
### Describe the bug

If you create a quiz exercise and you click the check box "start-time" you can save the quiz without a problem. start-time

### To Reproduce

1. Go to Course Management
2. Click on any course
3. Click on exercises 
4. Create a new quiz exercise 
5. Add at least one question, and the title for the quiz 
6. click on start time, and check that you can save the quiz even if you did not establish the start time. 

### Expected behavior

If you click on the check box "start ", you definitely must provide the start time otherwise, a message error should be deployed. 

### Screenshots

<img width="583" alt="image" src="https://user-images.githubusercontent.com/88991954/167351191-76886774-0d84-46e3-992f-26f24f03eeda.png">

### What browsers are you seeing the problem on?

Chrome

**Comment by ge65cer** [comment]
@Santia-go Can you please re-test this with the changes from https://github.com/ls1intum/Artemis/pull/5055.

**Comment by Santia-go** [comment]
The button is still clickable without inputting a start time. However, when I click it, the quiz is not saved until I input the start time. But the error messages are not related. Check the screencast. Additionally, it would be good if a message at the bottom says that the start time has not been inserted. 

https://user-images.githubusercontent.com/88991954/172318690-6cea814d-e68c-48dc-b8c7-cd45a29c0a3f.mov

**Comment by Santia-go** [comment]
Closed by: https://github.com/ls1intum/Artemis/pull/5055
