### ISSUE TITLE
Gitea as GIT Service

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#5059]
### Is your feature request related to a problem?

I just thought about [gitea](https://docs.gitea.io/en-us/) as GIT server in Artemis.
Would there be interest for such a support? I would be happy to get some opinions on that.

There are some benefits of gitea (https://docs.gitea.io/en-us/comparison/) especially the memory usage

### Describe the solution you'd like

Maybe we could support gitea as git backend in Artemis.

**Comment by Shirkanesi** [comment]
Sound like an interesting idea. Do you have any quantitative statistics about the memory-usage of both systems?

However, implementing this feature might be quite a pain, as the JavaAPI for gitea seems to be directly generated from swagger-docs and therefore feels quite counter-intuitive to use for some operations.

Also I'm wondering how to properly implement the concept of projects (or as GitLab calls them: Groups), as this is a feature not supported by gitea at all. 
This might not really be a problem; I don't know if Artemis just uses them for a cleaner structure in the VCS or if this is required.
