### ISSUE TITLE
UML Diagram: Communication Diagram

### ISSUE THREAD

**Issue by Johnypier** [ls1intum/Artemis#5062]
### Describe the bug

In this case, self-messages point to the left and they overlap with current class diagram, which makes them less visible.

![image](https://user-images.githubusercontent.com/98538725/167612301-dbfa7ccd-5dbe-41e0-8576-9cd8052c70b7.png)

### To Reproduce

1. Go to exercise with Communication Diagram edditor.
2. Create self-messages.
3. See error

### Expected behavior

Suggestion: let the messages be displayed above with arrow pointing to opposite direction.

![image](https://user-images.githubusercontent.com/98538725/167612378-bf7a2283-2cc7-451b-8955-61351a3ec1b6.png)

### Screenshots

None

### What browsers are you seeing the problem on?

Microsoft Edge

### Additional context

None

### Relevant log output

```shell
None
```

**Comment by bassner** [comment]
Bugs in the UML editor must be fixed in our UML editor, Apollon.
Please open an issue here: https://github.com/ls1intum/Apollon/issues/new?assignees=minrows&labels=bug&template=bug-report.md
