### ISSUE TITLE
Artemis Dark Theme: comments are barely visible

### ISSUE THREAD

**Issue by Marvin-Vitcu** [ls1intum/Artemis#5071]
### Describe the bug

When you assess a student exercise in the new Artemis Dark Theme and you try to read a comment in a code section that is green (because the student changed something here). Then the comment is barely visible
![image](https://user-images.githubusercontent.com/36523308/167725843-2f7a719f-83d8-4a66-bd56-1e492f675462.png)

### To Reproduce

1. Enable Artemis Dark Theme
2. Go to any Assessment Dashboard
3. Assess an exercise
4. Look for a green code section with a comment

### Expected behavior

The font color of the comment should be different (with more contrast to the background color green)

### What browsers are you seeing the problem on?

Chrome

**Comment by Shirkanesi** [comment]
I actually think everything show on your screenshot is way to hard to read.
We also had a discussion yesterday while we were correcting and all agreed on correcting being impossible in the dark-mode.

**Comment by bassner** [comment]
Yeah, most likely the color of the green line color is not changed in the dark mode. I'll have a look at that later 👍

**Comment by bassner** [comment]
A fix is ready for review in #5077.
