### ISSUE TITLE
Login via Token or OAuth2

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#5075]
### Is your feature request related to a problem?

Since we are developing applications for Artemis like [eclipse-artemis](https://github.com/kit-sdq/programming-lecture-eclipse-artemis), we would like to have an authentication workflow that is independent from the used login mechanism.
E.g., we at KIT are currently using the SAML2/Shibboleth workflow for registering users & the internal user management of Artemis.

Since our Eclipse Plugin directly talks to the REST API of Artemis, we currently rely on the ability to login via username and password to get an JWT Token. Nevertheless, we want to disable the ability to change the password of users in Artemis and want to enable #4749 to clone repositories. This would make our Grading Plugin not usable, since it could not communicate with the API anymore.

### Describe the solution you'd like

After talking to @krusche @jpbernius @b-fein we considered to options (which have to be decided):

1. OAuth2 Workflow
2. Personal Access Tokens

### OAuth2
OAuth2 Login in Artemis (Artemis is also Authorization Server)
* (+) Library Support from Spring Boot https://www.baeldung.com/rest-api-spring-oauth2-angular & https://docs.spring.io/spring-security-oauth2-boot/docs/2.2.x-SNAPSHOT/reference/html/boot-features-security-oauth2-authorization-server.html
* (+) Standard Workflow
* (-) Polling might be needed (since we do not assume native apps)

### Personal Access Tokens
Allow generation of a personal access token in the User Page of a Logged-In User

* (+) Easy to implement
    * (?) Integration into Spring authentication flow
* (+) Compatible with any software (it's only a token/string)
    * (+) especially important when implementing command line applications accessing the API
* (-/0) How to store the token / if we do not store it, how to revoke it? (e.g., JWT Tokens have no need to save; but they cannot be revoked)
    * Storage as separate DB-table with link to user, token-hash, token-name, and (optional) end of life date
        * (+) User can generate multiple access tokens for different applications with different lifetimes
        * (+) Easy: Special sub-page in the profile settings to create/remove tokens
* (-) user has to manually copy token into other application

**Feel free to add more +/-**

**Comment by sleiss** [comment]
Just a question: How would you authorize against the Version Control System?
Would you first (somehow) authorize against Artemis and then load a personal access token for the VCS from Artemis or do you have other plans?

**Comment by dfuchss** [comment]
That would be the plan (also simply storing the PAT from GitLab #4749 would be possible for us) We are mainly interested in accessing the API

**Comment by krusche** [comment]
One idea: can you not simply use the existing gitlab personal access token to authorize against Artemis?

This is already stored in the database anyway, right? @sleiss

**Comment by b-fein** [comment]
That would probably work, but has two major problems:
- The functionality of using token auth for the Artemis API would be tied to using Gitlab setups and also using the option of using Gitlab access tokens.
- The token seems to be stored in plaintext in the database. That should definitely not be the case for a token that gives Artemis API permissions.

**Comment by krusche** [comment]
I think it could be generalized to other setups as well, but the storing part sounds problematic

**Comment by dfuchss** [comment]
We (at KA) think that we could focus on the following approach for now:

* Use "JWT token" as Personal Access Token to Artemis:
    * life time should be configurable to the admin
    * No need for new authentication mechanisms (Artemis already uses JWT Tokens)
    * No need for DB changes (JWT Token contains all information, so there is no need to store it)
    * JWT Tokens can only shown once (simply generate it and that's it)

Open Questions:

* How to invalidate a token? -> that's maybe a general problem ? What does currently happen if you disable a user and he/she has a valid token (is logged in)?

**Comment by jpbernius** [comment]
> How to invalidate a token? -> that's maybe a general problem ?

I see two strategies to invalidate tokens:
1. short lifetime and use renew token to frequently issue a new token and use this renewal process to update permissions or revoke access altogether.
2. Store some form of ID in the token and check that with every request. (However, at this stage we could also replace JWT with random tokens.)

**Comment by dfuchss** [comment]
Maybe a simple endpoint /getNewToken can simply provide a new token for a valid token (could also be used for the initial token in the UI)

**Comment by krusche** [comment]
Admins can already configure the lifetime of JWT tokens. 

JWT tokens are used to authenticate and to partly authorize the user (based on the global role)

A second authorization is done based on the groups of the user which determine the specific role within a course.

Deactivating a user was not a real use case until now for us. We probably would need to integrate this into the second authorization check if we want to fully support this in all configurations and make sure that users cannot access Artemis any more.

**Comment by dfuchss** [comment]
> Admins can already configure the lifetime of JWT tokens

Thats nice; simply forgot that option .. then I would suggest to create a possibility to create JWT Tokens as logged-in user and show that option in the user preferences tab.
Nevertheless, in the future we could think about having another lifetime for such generated tokens.

Would that be an option for you @krusche . If so, we would start implementing it.

**Comment by dfuchss** [comment]
Closing for now. We are using browser-based login now.
