### ISSUE TITLE
Generally enhance display of buttons/choices

### ISSUE THREAD

**Issue by ge65cer** [ls1intum/Artemis#5089]
### Is your feature request related to a problem?

We are constantly adding features to Artemis, and thereby the amount of buttons (or choices in general) in the user interface increases all the time.

User experience research tells us that too many choices are exhausting for users (paradox of choice). As a rule of thump, a user should only be shown at most 7 options at a time (on one hierarchy level).

_Example:_ **Programming Management**

Desktop: More than 20 buttons/choices for the user!

<img width="1009" alt="Screenshot 2022-05-14 at 11 51 30" src="https://user-images.githubusercontent.com/102237363/168420778-9957ac86-5d12-4f5b-8f4e-743f5152248c.png">

Mobile: Equally many choices. While the labels are omitted to save space, this reduces context for the button action at the same time.

<img width="405" alt="Screenshot 2022-05-14 at 11 51 14" src="https://user-images.githubusercontent.com/102237363/168420819-6a3abe5e-94de-4080-8ef9-05b9261e7180.png">

### Describe the solution you'd like

We should consider limiting the amount of options displayed to the user at any point in time. Using other UI elements could help here.
One solution could be to create hierarchy using [Tabs](https://getbootstrap.com/docs/5.2/components/navs-tabs/#tabs) or [Accordions](https://getbootstrap.com/docs/5.2/components/accordion/).
Similarly, a popular approach would be to display some primary actions with a [dropdown](https://getbootstrap.com/docs/5.2/components/button-group/#nesting) to show the rest.

### Additional context

> As the number of choices increases, so does the effort required to collect information and make good decisions. Featuritis can be an exhausting disease for users.
> From: https://www.nngroup.com/articles/simplicity-vs-choice/

https://www.usertesting.com/blog/how-to-use-the-paradox-of-choice-in-ux-design

https://www.keepitusable.com/blog/the-psychology-of-choice-why-less-is-more/

**Comment by julian-christl** [comment]
I made a suggestion on how these buttons could be categorised. We can discuss this thoroughly before the implementation or implement it first and then wait for feedback.

Either way, if you have suggestions on how to improve it, feel free to participate in the discussion.

- Creation
  - Edit
  - Edit in editor
  - Manage Hints
  - Get Extracted Tasks
  - Delete Tasks
- Repository Actions
  - Combine Template Commits
  - Update Structure Test Oracle
  - Create structural solution entries
  - Show difference between the template and solution repositories
- Grading & Participation
  - Submissions
  - Participations
  - Scores
  - Grading
  - Add External Submission
  - Check Plagiarism
- Statistics
  - Scores
  - Statistics
- Maintenance
  - Unlock all Repositories
  - Lock all Repositories
  - Check Consistency
  - Build Plan Reset
  - Cleanup
  - Delete
- Export
  - Download Exercises
  - Download Repos
