### ISSUE TITLE
Point deduction not visible for students

### ISSUE THREAD

**Issue by JohannesStoehr** [ls1intum/Artemis#5114]
### Describe the bug

The amount of points deducted in an inline feedback of the assessment of a text exercise is not visible to the student.

### To Reproduce

1. Submit a text as a student
2. Assess the submission and use a negative inline feedback
3. See no amount of points deducted as a student

### Expected behavior

The student should also see the amount of points being deducted

### Screenshots

Student view (No amount of points in inline feedback):
![grafik](https://user-images.githubusercontent.com/38322605/168790741-29f9b996-e7f9-4c79-80a4-aa57c2bc9b74.png)
Instructor view:
<img width="1144" alt="Bildschirmfoto 2022-05-17 um 12 27 22" src="https://user-images.githubusercontent.com/38322605/168790892-623c11c8-6847-4e31-baa0-8b1de1f6ef56.png">

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge, Firefox

**Comment by Strohgelaender** [comment]
The amout of deducted points should be visible by hovering over the check / cross-icon. But I agree, this should be more noticable for both positive and negative feedback.
