### ISSUE TITLE
Complaints open the wrong correction round

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#5122]
### Describe the bug

If I use the overview for complaints in an exam with two correction rounds (see picture), it opens the first correction round instead of the second one. (URL contains `/submissions/XYZ/assessment?correction-round=0`)

![image](https://user-images.githubusercontent.com/22198798/168996646-beb362d3-7317-458d-bcde-efae0169166d.png)
![image](https://user-images.githubusercontent.com/22198798/168996887-ff7f6a6d-6551-4202-9c8b-458df66f7414.png)

### To Reproduce

1. Conduct exam with two correction rounds.
2. Create complaints.
3. Go to the complaint (using the steps in decsription)

### Expected behavior

It shall open the second correction round.

### What browsers are you seeing the problem on?

Firefox

**Comment by dfuchss** [comment]
Since our gradings will start soon, I'll mark it as high prio now :) Feel free to change that

**Comment by manuelmanso** [comment]
Was this fixed? Can't seem to reproduce it anymore

**Comment by dfuchss** [comment]
I'll check it again next week

**Comment by dfuchss** [comment]
@manuelmanso we encountered the issue again :)

**Comment by dfuchss** [comment]
(In Artemis 5.10.2)

**Comment by dfuchss** [comment]
@manuelmanso not sure why, but it again was a problem during exam reviews :( .. what information could we provide in addition?

**Comment by dfuchss** [comment]
Closing now. If the issue occurs again; I'll reopen it.
