### ISSUE TITLE
Online editor: Problem statement out of view

### ISSUE THREAD

**Issue by Dominik-Weinzierl** [ls1intum/Artemis#5144]
### Describe the bug

It is possible to force the right side of the problem statement out of the view.  

### To Reproduce

1. Go to the online editor
2. Drag the resize button to the left
3. See how the right side of the problem statement gets out of the view

### Expected behavior

The problem statement component should remain in the view and should not exceed the limits.

### Screenshots

https://user-images.githubusercontent.com/60005702/169837334-93677de6-a006-4245-83f7-bd97c75b07c0.mp4

### What browsers are you seeing the problem on?

Firefox

**Comment by krusche** [comment]
This is most likely a duplicate of an existing issue

**Comment by Dominik-Weinzierl** [comment]
Oh, yes seems like there are similar issues with the online editor: e.g. https://github.com/ls1intum/Artemis/issues/1851

**Comment by ge65cer** [comment]
Potentially related Sentry issue: https://sentry.ase.in.tum.de/organizations/artemis/issues/22069/

**Comment by ge65cer** [comment]
Tracked in: https://github.com/ls1intum/Artemis/issues/1460
