### ISSUE TITLE
Text input not visible for text fields on the exercise creation pages in dark mode

### ISSUE THREAD

**Issue by ole-ve** [ls1intum/Artemis#5174]
### Describe the bug

In dark mode, the text input for text input fields on the creation/update page for every exercise type is not visible because the text color is the same as the background color.

### To Reproduce

1. Go to Course Administration
2. Click on "(Create|Import) new (Programming|Quiz|Modeling|Text) Exercise"
3. Input any text in one of the text boxes
4. See that the text is not visible

### Expected behavior

The text color should be different from the background color.

### Screenshots

https://user-images.githubusercontent.com/73833780/170867334-dbecb371-4908-4a74-8ced-2798e877d62c.mov

### What browsers are you seeing the problem on?

Chrome

**Comment by bassner** [comment]
This work in the current production system
![grafik](https://user-images.githubusercontent.com/23171488/170877423-b8cbc604-fdb3-4635-bbd4-a44a96ca324b.png)

**Comment by ole-ve** [comment]
Originally experienced on TS1, this was probably just related to the test server configuration. Clearing the cache resolved that issue.
