### ISSUE TITLE
Remove leading and trailing spaces of the pasted URL in a video lecture unit 

### ISSUE THREAD

**Issue by evgeny1984** [ls1intum/Artemis#5185]
### Describe the bug

When the user wants to create a new lecture unit of type video and paste the url containing leading or trailing spaces, they are not recognized and therefore not removed from the source. That leads to the failed video loading.
To resolve the issue, the leading and trailing spaces need to be removed before the value is inserted into the text field.

### To Reproduce

1. Go to some existing course → Lectures → Units
2. Click on 'Add a new Lecture Unit' of type video
3. Give some name
4. Enter the URL containing spaces and save
5. The video cannot be watched if the user opens the unit

### Expected behavior

The system checks the inserted URL before assigning it to the text field and removes the spaces. The result URL is already cleaned by the system.

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge, Firefox

**Comment by Dominik-Weinzierl** [comment]
@evgeny1984 I added multiple whitespaces at the beginning and the end and wasn't able to reproduce this issue - could you please provide an example :thinking: Thank you!
![image](https://user-images.githubusercontent.com/60005702/171418121-7a2f784a-793a-4eca-aed1-3988ec23727c.png)

**Comment by Dominik-Weinzierl** [comment]
@evgeny1984 I added multiple whitespaces at the beginning and the end and wasn't able to reproduce this issue - could you please provide an example :thinking: Thank you!
![image](https://user-images.githubusercontent.com/60005702/171418121-7a2f784a-793a-4eca-aed1-3988ec23727c.png)

**Comment by evgeny1984** [comment]
> @evgeny1984 I added multiple whitespaces at the beginning and the end and wasn't able to reproduce this issue - could you please provide an example 🤔 Thank you! ![image](https://user-images.githubusercontent.com/60005702/171418121-7a2f784a-793a-4eca-aed1-3988ec23727c.png)
Try this one ' https://live.rbg.tum.de/w/ExPhys2/12088/PRES?video_only=1'

**Comment by Dominik-Weinzierl** [comment]
Interesting, thank you :+1:
