### ISSUE TITLE
Deleting failed attachements for lectures do not work

### ISSUE THREAD

**Issue by ehertel-tum** [ls1intum/Artemis#519]
### Describe the bug
Uploading PDF slides as attachements for lectueres does not work (the uploaded files can't be opened) if the file is to big. The file however will still be showen as a link afterwards and there is no error message. The files then can not be deleted or edited afterwards.

**Comment by ehertel-tum** [comment]
![image](https://user-images.githubusercontent.com/50831173/58537305-ea086c00-81f2-11e9-8b9e-9d1a3d2957c4.png)
This is how it looks when one tries to open the attachement

**Comment by maximilianmeier** [comment]
thanks for reporting.
fixed in #582
