### ISSUE TITLE
Number of "Unassessed submissions" > 0, but correcting submissions not possible

### ISSUE THREAD

**Issue by ehertel-tum** [ls1intum/ArTEMiS#520]
### Describe the bug
The number of unassessed submissino is bigger than 0, but there are no student submission to assess (they are also not locked by someone)

#### To Reproduce
Open e.g. https://artemis.ase.in.tum.de/#/course/30/exercise/489/tutor-dashboard

#### Expected behavior
The number should be 0 or we should be able to correct.
We suspect the late submissions to be the problem. They are marked as "No result" after the assessment, and therefore seem to count towards the "unassessed submissions" count. We tried this out with submitting late and grading the submission (and receiving "no results") and the "unassessed submissions" count went up.

#### Screenshots
![image](https://user-images.githubusercontent.com/50831173/58552912-dd484000-8213-11e9-8e31-a7f6f19f9c75.png)
![image](https://user-images.githubusercontent.com/50831173/58552953-f05b1000-8213-11e9-9f9a-e1b0c2ebb334.png)

**Comment by rpadovani** [comment]
Thanks for reporting this issue, and especially for tracking down the cause of the issue! I will work on it
