### ISSUE TITLE
Widened Artemis Logo in Safari

### ISSUE THREAD

**Issue by JohannesStoehr** [ls1intum/Artemis#5223]
### Describe the bug

The Artemis logo is currently displayed in a really wide version on Safari.

### To Reproduce

1. Go to Artemis
2. See error on top left

### Expected behavior

The logo should be displayed correctly.

### Screenshots

![Bildschirmfoto 2022-06-09 um 09 31 47](https://user-images.githubusercontent.com/38322605/172800365-5bc374b5-e76f-4146-8faa-0c55223d25fa.png)

### What browsers are you seeing the problem on?

Safari

### Additional context

@Haspamelodica also mentioned that Firefox displays a more narrow than usual version of the logo.

**Comment by Haspamelodica** [comment]
Firefox on Windows seems to have a similar issue; the logo seems to be squished a bit.
![grafik](https://user-images.githubusercontent.com/46954095/172802212-5616ba8c-1667-41da-86b6-43f21faa18dc.png)

**Comment by stefanwaldhauser** [comment]
Fixed in https://github.com/ls1intum/Artemis/pull/5225
