### ISSUE TITLE
Add Team Change Management Features 

### ISSUE THREAD

**Issue by evgeny1984** [ls1intum/Artemis#5224]
### Is your feature request related to a problem?

In Team Exercises, a team consists of several students. Many changes occur so that the team adds new students or loses students. In addition, the team can also decide to stop completely. These different actions cannot be fully logged, so it is not possible to create statistics on how the behavior of the teams is and how it can be influenced in the future.

### Describe the solution you'd like

Here is an extension of the functionality: Team Change Management would be helpful, where a team can be in different states, which can be mapped as an Enum: Pending/Approved/Cancelled. This status is then mapped to an entity TeamHistory and linked with a 1 to n association with the Team, so that per change a logging of date and time as well as the reason for the change can be made.

For example, an evaluation can be run at the end of the semester to check how many teams of those originally enrolled have made the changes: Changes to team Members, Team Cancellation, etc. This evaluation can help to improve the quality of the process.

**Comment by krusche** [comment]
I think this is out of scope at the moment
