### ISSUE TITLE
`Plagiarism Detection`: Results are not shown in artemis if "Generate JPlag Report" is enabled

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#5242]
### Describe the bug

The results of the plagiarism check is not shown if "Generate JPlag Report" is activated

### To Reproduce

1. Execute a plagiarism check with "Generate JPlag Report" enabled.

### Expected behavior

Results should also be shown in artemis (otherwise I have to run the plagiarism check twice)

### What browsers are you seeing the problem on?

Firefox

**Comment by krusche** [comment]
The main idea of this check was that you can still create the JPlag report outside of Artemis, so this is actually intended behavior. We could change this in the future, but I would not consider this as a bug
