### ISSUE TITLE
The "Save" button stays disabled after copy and paste into the "new post" Content text field

### ISSUE THREAD

**Issue by evgeny1984** [ls1intum/Artemis#5244]
### Describe the bug

When the user copies and pastes the text into the content field of the new post dialog, the system does not recognize the text and the state of the save button does not change.

### To Reproduce

1. Go to some course, e.g. EIST 22
2. Click on Discussion Tab → + New Post
3. Fill in the title and paste the text from the clipboard into the Content text field
4. See the state of the Safe button does not change.

### Expected behavior

When the user filled in the title and pasted or written the text into the content field, the system should recognize the change and the Safe button state must be changed to enabled.

### Screenshots

![image](https://user-images.githubusercontent.com/10652693/173672478-8ca25b57-51f8-40e5-a1a5-23b5b5810bb2.png)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge, Firefox

**Comment by krusche** [comment]
@canberkanar can you please have a look?

**Comment by canberkanar** [comment]
> @canberkanar can you please have a look?

For sure 😊

**Comment by canberkanar** [comment]
> @canberkanar can you please have a look?

Here is the fix: #5283 😊
