### ISSUE TITLE
Add support for new file formats for the lecture file units

### ISSUE THREAD

**Issue by evgeny1984** [ls1intum/Artemis#5249]
### Is your feature request related to a problem?

Currently, it is only  possible to upload the attachments units in following format: ".png", ".jpg", ".jpeg", ".svg", ".pdf", ".zip"
Uploading e.g. of .docx files is not possible.

### Describe the solution you'd like

We should support additionally following formats: Word, Excel, PowerPoint, Pages, Numbers and Keynote.

**Comment by JohannesStoehr** [comment]
The OpenDocumentFormats (.odt, .ods, .odp, .odg, .odf) would also be a good idea. Especially since all students should be able to open these documents, regardless of their operating system and preferred office suite.

**Comment by ge65cer** [comment]
We absolutely could support more file types, the current list is [here](https://github.com/ls1intum/Artemis/blob/develop/src/main/java/de/tum/in/www1/artemis/web/rest/FileResource.java#L76).
