### ISSUE TITLE
Horizantal scrollbar visible despite no need to 

### ISSUE THREAD

**Issue by rhubinger** [ls1intum/Artemis#5263]
### Describe the bug

On the assessment dashboard there is a horizontal scrollbar for the Assessment information which is visible even when the full assessment information fits on the page.

### To Reproduce

1. Go to the assessment dashboard of a course
2. Look at the assessment information box in the upper right corner
3. There is a horizontal scrollbar below it although the box is fully visible

### Expected behavior

The scrollbar should only be visible when the box can't be fitted on the page.

### Screenshots

![Screenshot (18)](https://user-images.githubusercontent.com/62466619/174811829-907423e3-2e05-4514-b9c2-6e7076f3ed00.png)

### What browsers are you seeing the problem on?

Firefox

**Comment by Dominik-Weinzierl** [comment]
Safari :thinking: (noticed while testing another PR)
![image](https://user-images.githubusercontent.com/60005702/174875485-20763749-5502-4e80-9d07-bb08c932699f.png)

**Comment by rhubinger** [comment]
I use Firefox 101.0.1 (64-Bit) on Windows 11 and a normal Full HD monitor.
