### ISSUE TITLE
Add semi-automatic assessment functionality for modelling exercises

### ISSUE THREAD

**Issue by rhubinger** [ls1intum/Artemis#5277]
### Is your feature request related to a problem?

When assessing modelling exercises especially the ones from the lecture you always have to assess a lot of submissions which just copied the lecturers example solution. This means you have to assess a lot of submission (~70%) which are nearly the same as they just submitted the example solution presented to them. By being able to automatically assess such submissions one could ease the workload on the tutors and eliminate the repetitive task of always assessing the same solution.

### Describe the solution you'd like

While creating an exercise the creator can enable semi-automatic assessment. The creator must then provide the example solution which will be presented in the lecture. The creatuor must furthermore provide an example assessment. After that he can publish the exercise normally. After the due date Artemis would compare all student submissions with the provided example submission. If the student submission matches the example submission, Artemis would apply the provided example grading to it.

**Comment by krusche** [comment]
This is already possible.
