### ISSUE TITLE
`Plagiarism checks`: Error when generating JPlag report in plagiarism detection

### ISSUE THREAD

**Issue by ge65cer** [ls1intum/Artemis#5293]
### Describe the bug

When an instructor ticks the checkbox `Generate JPlag Report` before running a check on the plagiarism detection page, the server responds with an _Internal Server Error_.

### To Reproduce

1. Go to Plagiarism Detection page as Instructor
2. Expand the settings and tick the `Generate JPlag Report` checkbox
3. Click on the `Rerun plagiarism detection` button
4. See the error

### Expected behavior

The instructor expects the feature to work without errors.

### Screenshots

<img width="1507" alt="Screenshot 2022-06-26 at 20 39 32" src="https://user-images.githubusercontent.com/102237363/175829441-0103eaed-3765-47d2-a6df-0b18ad554ceb.png">

### What browsers are you seeing the problem on?

Chrome, Firefox

### Additional context

Tested on TS1.

**Comment by ge65cer** [comment]
Maybe related to #5242? However, there is no mention of a server error in that issue.

**Comment by dfuchss** [comment]
@ge65cer shouldn't be releated. What was the internal server error in your case?

**Comment by ge65cer** [comment]
Didn't test it locally, yet. The HTTP response was empty.

**Comment by dfuchss** [comment]
@ge65cer still an issue?
