### ISSUE TITLE
Show number of unassessed submissions in tutor dashboard

### ISSUE THREAD

**Issue by Khalphion** [ls1intum/ArTEMiS#530]
### Is your feature request related to a problem?
On the tutor dashboard, I can't see if an exercise still has unassessed submissions immediately. I have to click through all exercises.

For example, H02E01 has 18 unassessed submissions, but I can't see that in the dashboard.

![Screenshot from 2019-05-30 23-21-32](https://user-images.githubusercontent.com/10117554/58665688-baac4900-8331-11e9-9c1b-16337fbc56de.png)

![Screenshot from 2019-05-30 23-21-45](https://user-images.githubusercontent.com/10117554/58665690-baac4900-8331-11e9-945e-5fd8c6d84304.png)

### Describe the solution you'd like
Show something similar what instructors have (progressbar, etc) in the table of the tutor dashboard.

**Comment by rpadovani** [comment]
Thanks for reporting, I am already working on this but there were other changes to do before :)

**Comment by krusche** [comment]
This feature was implemented and will be deployed in the next release 3.1.5 that will be available soon.
