### ISSUE TITLE
Discussion: are not filtered correctly when filtering too early

### ISSUE THREAD

**Issue by JohannesStoehr** [ls1intum/Artemis#5313]
### Describe the bug

When the discussion tab has many posts and therefore loads a longer time, pressing the filter buttons does not actually work as expected.

### To Reproduce

1. Go to the discussion tab
2. Filter the posts before they have been loaded
3. See unfiltered posts
4. Deselect and reselect the filter
5. Still see all posts

### Expected behavior

The posts should get correctly filtered

### Screenshots

https://user-images.githubusercontent.com/38322605/176661729-a0c4fd0e-b442-4314-9480-90a840a006e6.mov

### What browsers are you seeing the problem on?

Safari

**Comment by PaRangger** [comment]
Closing this due to being stale issue and not reproducible in the current communication module.
