### ISSUE TITLE
Additional unnecessary horizontal scrollbar

### ISSUE THREAD

**Issue by Dominik-Weinzierl** [ls1intum/Artemis#5360]
### Describe the bug

![image](https://user-images.githubusercontent.com/60005702/178159558-660ab3b5-8593-4186-a742-b10317542eb8.png)

### To Reproduce

1. Go to `/course-management/xxx/assessment-dashboard`
2. View the assessment info table

### Expected behavior

This scrollbar should not be visible.

### What browsers are you seeing the problem on?

Firefox

**Comment by Dominik-Weinzierl** [comment]
Seems like this is fixed in the current version.

**Comment by ge65cer** [comment]
Duplicate of https://github.com/ls1intum/Artemis/issues/5263
