### ISSUE TITLE
Assessment Dashboard responsiveness

### ISSUE THREAD

**Issue by Dominik-Weinzierl** [ls1intum/Artemis#5362]
### Describe the bug

It seems that something is wrong with the responsiveness.
I noticed that this problem is already present in 5.8.7 in production.

### To Reproduce

1. Go to `course-management/xxx/assessment-dashboard/xxx`
2. Resize the window
3. See overlapping elements

### Expected behavior

I would expect a good responsive design.

### Screenshots

![image](https://user-images.githubusercontent.com/60005702/178160352-ddfd375b-8682-417d-81d3-ef7a7750f979.png)

https://user-images.githubusercontent.com/60005702/178160435-a7d20b03-0d9e-4954-a49d-3a33a077d5de.mp4

### What browsers are you seeing the problem on?

Firefox

**Comment by ge65cer** [comment]
Thanks for reporting, the layout looks normal on desktop and doesn't seem to shrink correctly.
I took a look in the [git history](https://github.com/ls1intum/Artemis/commits/develop/src/main/webapp/app/exercises/shared/dashboards/tutor/exercise-assessment-dashboard.component.html) but couldn't make out an exact time when this was introduced. It has likely just gone unnoticed for quite some time.
