### ISSUE TITLE
`Exam mode` It is not posible to import quiz exercises from another exam if there is a test run in the original one. 

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#5379]
### Describe the bug

I cannot import a quiz exercise from an exam that has a test run into a new one (even if the exam is in another course). I get an error that says that I need to delete the test run. 

### To Reproduce

1. Create an exam with some exercises
2. Make a test run on that exam
3. Create a new exam (could be in another course)
4. Import the exercises from the first exam
5. Check that you get the error that says "need to delete the test run"
6. Check that you cannot save the exercise due to this error. 

### Expected behavior

Should be possible to import the quiz exercise from one exam to another one even if the first exam has a test run. 

### What browsers are you seeing the problem on?

Chrome

**Comment by krusche** [comment]
Does it only happen for quiz exercises? Or does it also happen for other exercise types?
