### ISSUE TITLE
Course plagiarism cases don't work and show internal server error

### ISSUE THREAD

**Issue by evgeny1984** [ls1intum/Artemis#5388]
### Describe the bug

The instructor cannot access the plagiarism cases of the particular course. By trying to do so, the Internal server error appears.

### To Reproduce

1. Go to a course which contains the plagiarism cases
2. Click on 'Plagiarism Cases' button
3. See error

### Expected behavior

The instructor can access the overview of the plagiarism cases without getting an error.

### Screenshots

![image](https://user-images.githubusercontent.com/10652693/178932204-d12a07c4-d0e0-415a-b356-e7a7869f16d4.png)

### What browsers are you seeing the problem on?

Chrome, Safari, Firefox

**Comment by krusche** [comment]
This issue was recently fixed
