### ISSUE TITLE
`Plagiarism Checks` The tutor view and the instructor view of a plagiarism check differs. 

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#5399]
### Describe the bug

The view of the plagiarism check in a text exercise shows the comparison. That is correct. See screenshot 1. 

However, when you will notify the students, you cannot see the comparison. See screenshot 2. 

### To Reproduce

1. Go to the Course manager 
2. Click on a course
3. Click on a text exercise which have already a plagiarism check with some cases 
4. You will see those cases and the submissions comparison between the students. 
5. In another window go to course manager 
6. Click on a course 
7. Click on Plagiarism Checks 
8. Scroll until the plagiarism results in the exercise that you select in the step 3. 
9. Open the case of the specific students
10. Check that you cannot see the submission of the second student in the comparison. 
has

### Expected behavior

Both views should show a comparison with both submissions. 

### Screenshots

Screenshot 1. Tutor view where the plagiarism check was deployed. 
![Screenshot 2022-07-15 at 13 26 35](https://user-images.githubusercontent.com/88991954/179224259-09537faf-8921-4fc0-a776-c004e6a66b4c.png)

Screenshot 2. Instructor view to notify the students
![Screenshot 2022-07-15 at 13 26 25](https://user-images.githubusercontent.com/88991954/179224257-8a06c7ab-3966-4008-9431-266de352f984.png)

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by krusche** [comment]
This issue has already been fixed
