### ISSUE TITLE
`Plagiarism checks`: Scroll-down in the comparison of modelling exercises is working in some cases and other no. 

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#5402]
### Describe the bug

Scroll-down action the modelling exercises in the comparison of plagiarism checks is not working properly. 
Sometimes it works in both submissions like the first case in the video
Sometimes it does not work in both  submissions
And in the 4th case, just works in the right submission. 

### To Reproduce

1. Go to the Course manager
2. Click on a course
3. Click on a modeling exercise that has already a plagiarism check with some cases
4. You will see those cases and the submissions comparison between the students.
5. In a window with no zoom try to scroll down in those submissions. 
6. Check if the behavior is the same as the screencast below. scroll down

### Expected behavior

Should be possible to scroll down just like the first case in the screencast below. 

### Screenshots

https://user-images.githubusercontent.com/88991954/179237679-7e85c252-8e12-4777-badc-0d7f5ad4ea9f.mov

### What browsers are you seeing the problem on?

Chrome

**Comment by ge65cer** [comment]
This might be somewhat related to the Apollon editor? CC @minrows
