### ISSUE TITLE
`Exam mode`: Unintentional log out during exam is not prevented correctly

### ISSUE THREAD

**Issue by maximiliansoelch** [ls1intum/Artemis#5440]
### Describe the bug

When I (unintentional) click on sign out as a student during an exam, I get an alert that all unsaved changes will be lost.
If I then click on cancel, I nevertheless get logged out and receive authentication errors.

### To Reproduce

1. Conduct an exam as a student
2. Click on sign out
3. A warning is shown (see screenshots)
4. If you click cancel, you will be logged out anyways and then get errors that you are not authenticated

### Expected behavior

If I click cancel in the alert box, then I should still remain logged in.

### Screenshots

<img width="1512" alt="Bildschirmfoto 2022-07-20 um 12 55 53" src="https://user-images.githubusercontent.com/9954674/179966923-a7d1974d-ca4c-4d37-bb7b-d2792f467ca1.png">
<img width="1512" alt="Bildschirmfoto 2022-07-20 um 12 56 04" src="https://user-images.githubusercontent.com/9954674/179966930-f4eb18b8-cf28-4027-8934-04aea0288dce.png">
<img width="1511" alt="Bildschirmfoto 2022-07-20 um 12 56 16" src="https://user-images.githubusercontent.com/9954674/179966939-72f14229-94d1-4859-8b7b-6bf3fd59c782.png">

### What browsers are you seeing the problem on?

Chrome

**Comment by Pellumbengineer** [comment]
Hi, 

This bug does not only occur on exam mode but everywhere when there is unsaved changes. One of the cases that i have tested is during modeling exercise and when i tried to signed out the same bug occurs. 

![errorArtemis](https://user-images.githubusercontent.com/26312757/194655918-504d4d86-9b85-4dce-9e00-58db6ca5e478.png)

I am currently working on this issue at this #5727 PR
