### ISSUE TITLE
`Plagiarism checks` : 403 when trying to run plagiarism checks while being tutor and editor

### ISSUE THREAD

**Issue by fh314** [ls1intum/Artemis#5467]
### Describe the bug

When trying to run plagiarism checks in a course I'm both tutor and editor in, I get the following error. This doesn't happen when you're additionally assigned instructor rights. 
![image](https://user-images.githubusercontent.com/29736922/180668651-2cbf1868-c7fe-4c10-a627-e6d0c051f37b.png)

### To Reproduce

1. Open exercises details page
2. Click "Check Plagiarism"
3. Open Dev Tools
4. Click "Detect Plagiarism"

### Expected behavior

Plagiarism checks run sucessfully

### What browsers are you seeing the problem on?

Chrome

### Additional context

user ge75pub in course id 169

**Comment by fh314** [comment]
Logging in and out seems to fix this issue

**Comment by krusche** [comment]
If users get additional roles, they need to logout and login again to synchronize the rights in the JWT token.
Probably, this was missed here. I double checked the code and don't see a reason why it should work for some, but not all editors.
