### ISSUE TITLE
Internal Server Error when retrieving hints for a programming exercise with a problem statement with wrong test case names

### ISSUE THREAD

**Issue by byaylymov** [ls1intum/Artemis#5475]
### Describe the bug

I receive an internal server error when I try to update the page after pushing to the exercise repo (FPV homework exercise).
Exercise link: https://artemis.ase.in.tum.de/courses/189/exercises/7426
This page throws a status 500: https://artemis.ase.in.tum.de/api/programming-exercises/7426/exercise-hints/available
See also: https://zulip.in.tum.de/#narrow/stream/1157-FPV-Sheet13/topic/W13.20H02.20-.20Tests.20Server.20failure

### To Reproduce

1. Go to Course 189
2. Push some changes
3. Update the Artemis exercise page
4. Internal server error

### Expected behavior

The program should build and show hints for each one of the subtasks.

### Screenshots

![image](https://user-images.githubusercontent.com/22872206/180995207-42ce3372-8ffe-4d13-becd-6be021dfad68.png)
![image](https://user-images.githubusercontent.com/22872206/180995282-fd2ac209-d72e-441d-a9ff-5213acfc660d.png)
![image](https://user-images.githubusercontent.com/22872206/180995429-3d408616-f642-495d-822f-f05510bc531a.png)

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

Used browser: Brave Browser

**Comment by ole-ve** [comment]
Thanks for reporting, @byaylymov.

We would need some more information for investigation:
- Which programming language/project type has the exercise?
- Has the exercise been imported (e.g. from another test course) or created directly in the specific course?
- Why does the feedback for one task state that "No result details available."? Do you skip any tests? Also, double-check that the test case names are defined correctly in the problem statement.

I assume that the issue is somehow related to missing test feedback. The missing feedback, however, is not related to the functionality of retrieving/displaying hints.

**Comment by byaylymov** [comment]
Hi Ole,
after I pushed all my code and fixed my code issues, Artemis shows 100% but the internal server error is still there. See the screenshot: 
![image](https://user-images.githubusercontent.com/22872206/181019095-ae52581b-3d70-4506-841d-b6d73c837d7b.png)

- The programming language is OCaml and I don't know the project type of the exercise since I'm a student and not a tutor.
- The exercise instructors provided this exercise and I just cloned it from there. (Internal server error pops up just for this exercise and not others)
- "No result details available" feedback is shown for all subtasks: https://user-images.githubusercontent.com/22872206/181020733-c165254c-3452-4acd-a84d-1cf1de582d63.mp4

**Comment by ole-ve** [comment]
Thanks for the detailed report. In this case, I am pretty sure that the problem statement markdown content is wrong. To be more precise, the referenced test case names (in the PS) may be wrong. If the test case names were correct, each subtask would contain the feedback of the test cases (related to this subtask) as can be seen at the overall score.

Therefore, reach out to your instructors and ask them to double-check that the referenced test case names in the problem statement are correct.

This error should still not occur, but can simply be solved by correcting the problem statement markdown content. Therefore, I will categorize the issue as low-prio.

**Comment by Hialus** [comment]
I've implemented a fix for this.
However, Ole is still correct: The tasks in the problem statement of the exercise have issues. So the instructors of your course should probably fix this.

**Comment by byaylymov** [comment]
Thank you for your explanations and solutions. I've informed the instructors and they are working on it. I will update you as soon as they find a solution.

**Comment by byaylymov** [comment]
They fixed the bug and now it shows all hints :)
Thank you guys for your support and time!
