### ISSUE TITLE
`Quiz exercises` : Do not return to exercise overview after saving quiz exercise

### ISSUE THREAD

**Issue by fh314** [ls1intum/Artemis#5487]
### Is your feature request related to a problem?

When editing quiz exercises and saving changes, you're always returned to the exercise overview page and have to navigate back to your exercise to continue editing. Most of the time I'm saving an exercise only to save the current progress I made and not actually to finish editing the exercise.

### Describe the solution you'd like

Just save the exercises without returning to the exercise overview page or add a second button to only save the exercise and not return to the exercise overview page.

**Comment by krusche** [comment]
@bassner in the case of quiz exercise we might need to revert the latest change, because it makes more sense to stay on the page and being able to continue editing
