### ISSUE TITLE
Exam mode: Notification for file upload exercise

### ISSUE THREAD

**Issue by ge65cer** [ls1intum/Artemis#5497]
### Describe the bug

When uploading a file for a file upload task in an exam, Artemis creates a user notification for it.

### To Reproduce

1. Create exam with file upload task
2. Participate in the exam and upload a file
3. Finish the exam
4. Open the notification sidebar
5. See the notification for the file upload task

### Expected behavior

For exam exercises, no notifications should spawn.

### Screenshots

<img width="306" alt="Screenshot 2022-07-28 at 13 59 01" src="https://user-images.githubusercontent.com/102237363/181500205-8f3a8383-83aa-4aa8-9fd0-098571b326c9.png">

### What browsers are you seeing the problem on?

Chrome, Safari, Firefox

**Comment by manuelmanso** [comment]
Fixed in https://github.com/ls1intum/Artemis/pull/5501
