### ISSUE TITLE
Results of text exercises are shown weirdly

### ISSUE THREAD

**Issue by JonasJJJJ** [ls1intum/ArTEMiS#551]
### Describe the bug
The results of text exercises are shown weirdly.  

#### To Reproduce
Just view the result of a text exercise.

#### Screenshots
![image](https://user-images.githubusercontent.com/24255548/58865254-8a103a80-86b6-11e9-97e2-ff84d9e5e228.png)

### Environment

<details><pre>
 - OS: Windows 10
 - Browser: chrome
 - Version: Google Chrome Version 74.0.3729.169 (Offizieller Build) (64-Bit)
</pre></details>

**Comment by max-OS1** [comment]
Duplicate of #444 ?

**Comment by JonasJJJJ** [comment]
True @max-OS1
