### ISSUE TITLE
Remove course icon

### ISSUE THREAD

**Issue by Dominik-Weinzierl** [ls1intum/Artemis#5526]
### Is your feature request related to a problem?

As far as i can see it is not possible to remove the course icon.

### Describe the solution you'd like

It should be possible to remove the course icon.

### Additional context

![image](https://user-images.githubusercontent.com/60005702/182140591-c44d4af3-c73d-4ab4-91f0-c95022059129.png)

**Comment by rriyaldhi** [comment]
Hi @Dominik-Weinzierl, I'll assign the issue to myself if you don't mind. Thanks!

**Comment by Dominik-Weinzierl** [comment]
Sure, thanks for implementing this issue 👍
