### ISSUE TITLE
The scroll bar in the course management page seems to be positioned incorrectly

### ISSUE THREAD

**Issue by Dominik-Weinzierl** [ls1intum/Artemis#5529]
### Describe the bug

The scroll bar is not after the elements, but overlaps them.

### To Reproduce

1. Go to Course Management page
2. View a course with multiple exercises
3. Scroll down within the course preview
4. See the wrong scroll bar

### Expected behavior

The scroll bar should not overlap the elements.

### Screenshots

![image](https://user-images.githubusercontent.com/60005702/182142136-0135a442-6ea4-4a07-9d3a-1f73c7426a42.png)

### What browsers are you seeing the problem on?

Firefox

**Comment by ge65cer** [comment]
Fixed, moved the padding to the child element that owns the scrollbar.
