### ISSUE TITLE
`Programming exercises`: Inline feedback box semi-transparent

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#5536]
### Describe the bug

See screenshot below: The inline feedback box is semi-transparent.

### To Reproduce

1. Go to the manual assessment for a programming exercise.
2. Add an inline feedback by clicking on the `+` in the gutter of the code editor.

### Expected behavior

The feedback box is not transparent, as before.

### Screenshots

![Screenshot 2022-08-02 at 08-06-05 Programming Exercises](https://user-images.githubusercontent.com/64250573/182303683-cec02b45-09db-416c-8b89-7e19e906e672.png)

![Screenshot 2022-08-02 at 08-08-50 Programming Exercises](https://user-images.githubusercontent.com/64250573/182303975-5df5adbd-245a-40f6-b19d-f94ef66378db.png)

### What browsers are you seeing the problem on?

Firefox 102

### Additional context

- Artemis 5.9.6

**Comment by ge65cer** [comment]
Fixed, caused by updating Bootstrap.
