### ISSUE TITLE
`Plagiarism Checks`: The warning message is shown in a wrong position 

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#5537]
### Describe the bug

The warning message "You must notify the student before determining the verdict" is shown in a wrong position when I approach the mouse cursor. 

### To Reproduce

1. Go to Plagiarism check in a course 
2. Open a case from any student without notification
3. Approach the cursor over the button in the Verdict section. 
4. Verify that the warning message for the Plagiarism button is shown in the wrong position. See the screencast

### Expected behavior

Should shown the warning message over the Plagiarism button. 

### Screenshots

https://user-images.githubusercontent.com/88991954/182304551-babebc3e-ff10-4e48-a71a-c226f67b5d9e.mov

### What browsers are you seeing the problem on?

Chrome

**Comment by ge65cer** [comment]
I have re-done the instructor interface, so this will soon be no longer an issue.
