### ISSUE TITLE
`Dark mode`: Comparison title not readable 

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#5538]
### Describe the bug

The font color is not adapted for dark mode. 

### To Reproduce

1. Go to Plagiarism check in a course
2. Open a case from any student with/without notification
3. Verify that the comparison title is not readable. See screenshot 

### Expected behavior

The font color should be addapted.

### Screenshots

![image](https://user-images.githubusercontent.com/88991954/182304981-4b6e0a19-44a3-4436-949e-30378defc88e.png)

### What browsers are you seeing the problem on?

Chrome

**Comment by bassner** [comment]
This has already been fixed in #5544
