### ISSUE TITLE
Information for auxiliary repositories when editing a programming exercise not clear

### ISSUE THREAD

**Issue by julian-christl** [ls1intum/Artemis#5551]
### Describe the bug

When creating an auxiliary repository for a programming exercise after the exercise has been created, everything gets created on Artemis without an error, but the linked repository doesn't exist.
The hint that changes don't get propagated only refers to editing and deleting repos.

It's definitely not created. It's not in the corresponding project, even with full privileges.
Current workaround: Create the auxiliary repository in Artemis and then create it manually in Bitbucket and add the required settings to the build plan.

### To Reproduce

1. Create a programming exercise
2. Add a new auxiliary repository to the exercise
3. See the success message
4. Look at the detail page of the exercise
5. Open the link to the repository
6. Get a 404

### Expected behavior

1. At least the hint should be extended to include creation
2. If possible, Bitbucket should be included (adding, editing, deleting)
3. Bamboo currently can't tackle it so that's okay

### What browsers are you seeing the problem on?

Chrome

**Comment by Mtze** [comment]
Bitbucket and Bamboo are deprecated - Closing this issue
