### ISSUE TITLE
Searching after exercise within a course

### ISSUE THREAD

**Issue by LadnerJonas** [ls1intum/Artemis#5573]
### Is your feature request related to a problem?

When preparing for an upcoming exam, I always want to search after specific topics (e.g. "docker") and see all the relevant exercises.

### Describe the solution you'd like

A search bar inside the exercise overview of a course

### Describe alternatives you've considered

Tagging of exercises (e.g. "docker", "testing")

**Comment by b-fein** [comment]
Implemented in #5717 as of Artemis 5.12.3
