### ISSUE TITLE
`Programming Exercises`: Submissions for commits on all branches are created

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#5575]
### Describe the bug

Artemis does not only create submissions for commits on the main/default branch, but also for commits on other branches.

This is a high priority bug, as students that commit to other branches than the default see a positive result in Artemis. However, when a tutor manually assesses the exercise, they only see the default branch in the online editor where nothing has been changed.
This could also happen in exams where students are allowed to use the local IDE to solve the task.

### To Reproduce

1. Create a programming exercise.
2. As student, commit to a non-default branch in the student repo.
3. Artemis creates a submission for this commit.

### Expected behavior

Artemis only creates new submissions for commits on the default branch and ignores all other ones.

### What browsers are you seeing the problem on?

Firefox

### Additional context

- Artemis 5.9.8 (while investigating the bug I noticed that it seems to have occurred at least once, a month before as well, so all versions at least since 5.9.0 probably have the same issue)
- Gitlab/Jenkins setup

### Relevant log output

```shell
08:00:36.303 INFO t.i.w.a.s.p.ProgrammingSubmissionService : NotifyPush invoked due to the commit 457652989a86cfee17eb3ee8d306ded00dfa3d8b by Benedikt Fein with <...> in branch testbranch
08:00:36.304 WARN .i.w.a.w.r.ProgrammingSubmissionResource : Processing submission for participation 1469 failed: Submission for participation id 1469 in branch testbranch will be ignored! Only the default branch is considered
08:00:57.547 INFO d.t.i.w.artemis.web.rest.ResultResource  : Artemis received a new result for build plan TEST01GGTJAVA17-FEIN02
08:01:05.093 WARN .a.s.p.ProgrammingExerciseGradingService : Could not find pending ProgrammingSubmission for Commit Hash Optional[457652989a86cfee17eb3ee8d306ded00dfa3d8b] (Participation 1469, Build Plan TEST01GGTJAVA17-FEIN02). Will create a new one subsequently...
08:01:06.338 INFO d.t.i.w.artemis.web.rest.ResultResource  : The new result for TEST01GGTJAVA17-FEIN02 was saved successfully
```

**Comment by dfuchss** [comment]
Related to https://github.com/ls1intum/Artemis/issues/5273 ?

**Comment by krusche** [comment]
I looked into this issue. The submission for commits on branches other than default will not be created initially (in the logs it says other branches will be ignored), but when the result is received, a fallback submission will be created. At the moment, we do not have any information for which branch the build result was created.

There are different options how to fix the issue:
1. We make sure that Bamboo and Jenkins only start a build for the default branch and ignore all other branches. I think this is already the case for build plans on Bamboo.
2. When creating the fallback submission in `createFallbackSubmission`, we would need to ask the version control system for the commit details to retrieve the branch for the related commit (we have to check how well this works, in particular as commits could reside on multiple branches)
3. We try to add the branch information to the build result sent with the plugins developed in https://github.com/ls1intum/bamboo-server-notification-plugin and https://github.com/ls1intum/jenkins-server-notification-plugin

Option 1 might be the easiest solution and it would also save computing power on the CI system

**Comment by krusche** [comment]
I think the issue is the following statement in basically all template `Jenkinsfile`s:

`branches: [[name: '**']]`

I would suggest we change this to something like

`branches: [[name: '#defaultBranch']]`

and then add a replacement in `JenkinsBuildPlanCreator` which replaces `#defaultBranch` with the actually used default branch as configures in Artemis

**Comment by krusche** [comment]
Regarding Bamboo: in the default configuration, Bamboo will only build on the default branch, all other so called "Plan branches" would need to be created manually, except other options are specified

**Comment by krusche** [comment]
I started to implement this on the branch `bugfix/limit-jenkins-build-to-default-branch`

@b-fein @dfuchss would be awesome if you can have a look if this makes sense to you

**Comment by sleiss** [comment]
I check the Bamboo plugin and it is possible to extract the used branch of the used repositories so we could send this information to Artemis.

I will check whether/how that is possible for Jenkins as well.

**Comment by b-fein** [comment]
> `branches: [[name: '#defaultBranch']]`

> I started to implement this on the branch `bugfix/limit-jenkins-build-to-default-branch`

The webhook from Gitlab still triggers the build for all branches but now Jenkins just always (unnecessarily) builds for the `main` branch even on pushes on other branches.

**Comment by sleiss** [comment]
> I check the Bamboo plugin and it is possible to extract the used branch of the used repositories so we could send this information to Artemis.
> 
> I will check whether/how that is possible for Jenkins as well.

I just checked and it is possible to include the branch name in the payload sent from Jenkins to Artemis, too.

We could thus also implement this change within Artemis, so that the builds are still executed but Artemis not grade them (although I believe preventing the build in the first place might be the better approach as the build is then not performed and it will not use any resources).

**Comment by krusche** [comment]
@b-fein I implemented the `push_events_branch_filter` in the latest commit on the referenced PR. Can you check in your setup if this prevents Jenkins from building on other branches?
