### ISSUE TITLE
Ungraded and Unstarted Exercises in the Statistics View

### ISSUE THREAD

**Issue by metacookie** [ls1intum/Artemis#560]
### Is your feature request related to a problem?
When viewing the personal statistics, exercises that haven't been graded yet appear as failed exercises, instead of simply not counting toward the statistic. This makes it very difficult for me to evaluate my own performance on the tasks. Additionally, unstarted exercises count towards the Total Max Score value, but are not reflected in the Bar Charts, which can be confusing.

### Describe the solution you'd like
Display ungraded exercises as grey bars that don't count toward the statistics, and add unstarted exercises as white bars. Add mouse-hover descriptions for the statistics values to explain them.

### Additional context
The information relevant to the user is his or her performance on the exercises that they have worked on. Seeing ungraded exercises as failures makes it very difficult to assess personal performance.

**Comment by maximilianmeier** [comment]
We improved the statistics in #590
