### ISSUE TITLE
Test Exam: Repositories are not locked after deadline

### ISSUE THREAD

**Issue by just-max** [ls1intum/Artemis#5601]
### Describe the bug

In the new test exam feature, student repositories are not locked after the deadline. On the one hand, this is not a big deal since it's a mock exam, but it's certainly not intended behaviour and still sends the "Illegal submission" notification.

### To Reproduce

1. Create a new exam in "test exam" mode
2. Set the end of working window to 5 minutes in the future and the working time to 5 minutes.
3. Create a programming exercise, language does not matter
4. Start the exam (as a student would)
5. Start the programming exercise
6. (Clone, commit some change and push: this works as expected)
7. Wait until the working time is done
8. Commit some change and push again (I)
9. Wait until the individual working time is over
10. Commit some change and push again (II)

### Expected behavior

Being able to push during (I) is probably OK, but maybe it should be clear that students can work until the end of the working period plus the individual working time. Repositories should definitely be locked on (II).

**Comment by krusche** [comment]
@mallgaier could you please have a look into this issue?

**Comment by mallgaier** [comment]
Thank you for reporting the issue.
The programming exercise repositories for test exams are currently only locked once the student submits the student exam.
If the student just lets the working time pass, the repository is not locked. However, once the working time is over, the student exam and hence the assignment is no longer accessible in the client. 
We will have a look at the issue. There is a scheduler missing, which performs the locking of the repository after the working time.
However, the functionality of the real exams is not affected by this issue. There, the repositories are scheduled to be locked after the (individual) working time.

**Comment by just-max** [comment]
Yep, it's not a critical issue since it's just the test exam.

While reproducing the issue, I just let the working time run out (and then went through with the regular confirmation), so your description makes sense.
