### ISSUE TITLE
Dependabot/Renovate Integration

### ISSUE THREAD

**Issue by Dominik-Weinzierl** [ls1intum/Artemis#5636]
### Is your feature request related to a problem?

Its important to update dependencies regularly. In order to minimize the manual effort, applications like Github provide the possibility to use bot applications like Dependabot or Renovate to update those.

Dependabot: https://github.com/dependabot
Renovate: https://docs.renovatebot.com/

I personally prefer renovate (e.g.: https://meabed.medium.com/software-dependency-management-from-dependabot-to-renovate-5b4e749b5b1c)

### Describe the solution you'd like

I think it would be good to integrate such applications into this repository in order to keep the dependencies up to date and avoid any issue (e.g. security issues).

**Comment by JohannesStoehr** [comment]
We use dependabot, see e.g. #5775
