### ISSUE TITLE
`Development`: Log level for QuizScheduleService

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#5643]
### Is your feature request related to a problem?

The following line generates a log line nearly every 5 seconds: 
https://github.com/ls1intum/Artemis/blob/83f1d11d5b37832482f01bab4eba6aae9cc480a8/src/main/java/de/tum/in/www1/artemis/service/scheduled/cache/quiz/QuizScheduleService.java#L409

### Describe the solution you'd like

I would suggest to set the logging of this line to debug.

### Describe alternatives you've considered

You can set the log level for QuizScheduleService to warn.

**Comment by b-fein** [comment]
Quick (temporary?) fix without code changes:

Take https://github.com/ls1intum/Artemis/blob/develop/src/main/resources/logback-spring.xml and add

```xml
<logger name="de.tum.in.www1.artemis.service.scheduled.cache.quiz.QuizScheduleService" level="WARN"/>
```
somewhere, then in your `application.yaml` or ENV set the config key `logging.config: <PATH_TO_CUSTOM_LOGBACK.XML>`.

**Comment by krusche** [comment]
We are still investigating an edge case issue which only occurs sometimes, so I would like to keep those logs for a while

**Comment by krusche** [comment]
We want to increase the number of info logs in general in the future because this makes it easier to identify certain issues

**Comment by b-fein** [comment]
Setting the config value
```yaml
logging:
   level:
       de.tum.in.www1.artemis.service.scheduled.cache.quiz.QuizScheduleService: WARN
```
directly seems to work, too.
