### ISSUE TITLE
Some assessed Exercises do not show points

### ISSUE THREAD

**Issue by DeRealMorgan** [ls1intum/Artemis#567]
### Describe the bug

In der Übersicht werden teilweise Aufgaben als Status "no result" angezeigt, obwohl sie schon bewertet wurden. 
Klickt man auf die Detailansicht der Aufgabe, werden die erhaltenen Punkte angezeigt.

Wenn der Bug gefixt wird: Sind die Aufgaben trotzdem in die Berechnung des Gesamt-Scores eingeflossen?

(Hab dann wohl die Überschrift auf Englisch geschrieben.)

**Comment by DeRealMorgan** [comment]
![Unbenannt](https://user-images.githubusercontent.com/34401569/59563844-61d1f580-903f-11e9-9248-70a8eba14c89.PNG)

**Comment by diana0905** [comment]
have the same problem 
![Screenshot 2019-07-01 at 17 29 47](https://user-images.githubusercontent.com/52419065/60667318-8a445700-9e69-11e9-812d-9c6b82ab41d6.png)
