### ISSUE TITLE
Tooltip clipping in `programming-exercise-lifecycle.component.ts`

### ISSUE THREAD

**Issue by simon-hng** [ls1intum/Artemis#5679]
### Describe the bug

As the class `.timeline-box` in `programming-exercise-test-schedule-picler.scss` has the attribute `overflow-x: scroll;`, [overflow in y direction is also hidden](https://stackoverflow.com/questions/12931680/overflow-x-and-y)

### To Reproduce

1. Create a programming exercise
2. Hover over any due date. At time of writing this the following tooltips overflow
- Release Date, Automatic Tests, Due Date, Run Test after Due Date, ...

### Expected behavior

The overflow shouldn't clip and be shown

### Screenshots

![Screenshot_20220924_221510](https://user-images.githubusercontent.com/25489463/192120069-1c6af3f3-c8a0-4934-8be2-f2168fc65123.png)

### What browsers are you seeing the problem on?

Firefox

**Comment by ge65cer** [comment]
See #5677 and #5562

**Comment by ge65cer** [comment]
Duplicate of #5125
