### ISSUE TITLE
Displaying wrong results on code exercises on main screen (EIST).

### ISSUE THREAD

**Issue by Cosmin2106** [ls1intum/ArTEMiS#568]
![Screenshot from 2019-06-07 16-25-52](https://user-images.githubusercontent.com/35492896/59111306-0ddd5780-8941-11e9-98e1-7613cffca0ce.png)
![Screenshot from 2019-06-07 16-26-20](https://user-images.githubusercontent.com/35492896/59111308-0e75ee00-8941-11e9-9ac9-cebbc6871f9c.png)
![Screenshot from 2019-06-07 16-26-37](https://user-images.githubusercontent.com/35492896/59111309-0e75ee00-8941-11e9-9ada-7dc836bf6f63.png)

### Describe the bug
At the EIST exercise L06E02 I have three submissions: 67%, 92%, 100%. When you first open the page, the biggest is shown (as it should), but if you click on the problem, scroll to all the results, click on the errors from the 67% result, close the popup window then go to the previous page (main page), the 67% result is now shown until you refresh the page.

#### To Reproduce
1. Go to a coding exercise with multiple submissions.
2. Scroll to the bottom and click on "show all results'.
3. Click on the errors of the first result (e.g.: 4 of 13 failed)
4. Close the pop-up window with the errors.
5. Press the back button of the browser.
6. On the exercise it is now displayed the wrong score, namely the one we clicked on.

#### Expected behavior
The last result should always remain displayed.

**Comment by krusche** [comment]
Thanks for reporting. This bug should be fixed in the next release 3.1.5 the will be deployed soon.
