### ISSUE TITLE
SAML2 Login Not Possible

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#5710]
### Describe the bug

The redirection to the SAML2 provider no longer works. Therefore, users cannot login.

### To Reproduce

Artemis with SAML2 enabled required.

1. Log out of Artemis.
2. Click the Login via SAML2/Shibboleth/… button on the right half of the login screen.
3. You are not redirected to the SAML2 provider, instead a blank page is shown.
4. The error as shown below is in the browser console log.

### Expected behaviour

The user is forwarded to the SAML2 provider for the authentication

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge, Firefox

### Additional context

* Artemis Version: 5.11.0
* Confirmed working on 5.10.2
* Using `curl` to query the `/saml2/authenticate` endpoint correctly returns the 302 redirect in 5.10.2, but the same call is intercepted in the newer version and returns a HTML ‘please activate Javascript’ response.

The redirection to the `/saml2/authenticate` page is initiated at https://github.com/ls1intum/Artemis/blob/723ddcc017006bf6c4874fa44c9cf1a8a078bf38/src/main/webapp/app/home/saml2-login/saml2-login.component.ts#L46

### Relevant log output

```shell
Error: NG04002: Cannot match any routes. URL Segment: 'saml2/authenticate'
```

**Comment by b-fein** [comment]
CC @dfuchss
Can you reproduce that on a test system?

**Comment by dfuchss** [comment]
I'll check it later.

**Comment by dfuchss** [comment]
Yes, Version 5.11.0 is critical for us as well. Verified on test-systems.

**Comment by bassner** [comment]
Hmh. I guess the problem is not related to Angular at all. The really important point seems to be your third bullet point in the additional context. The servers seems to deliver the webapp bundle instead of the correct redirect response. I see that there have been a few changes to the security configuration in https://github.com/ls1intum/Artemis/pull/5604. Could that be related?

**Comment by b-fein** [comment]
The change to the security config was already part of 5.10.2. That version definitely still works, though.

**Comment by bassner** [comment]
All that changed between those two version are the dependencies, though ...
What if you try to roll back [this upgrade](https://github.com/ls1intum/Artemis/commit/7c3c0847a576128c8761f667a8f657520691b381#diff-3d103fc7c312a3e136f88e81cef592424b8af2464c468116545c4d22d6edcf19R10) and check if the resulting build works? Then we'd at least know that this is the change that caused it

**Comment by b-fein** [comment]
Good catch, I not notice/consider this dependency update. It looks like reverting this change indeed fixes the issue. :+1:

Thank you!

**Comment by dfuchss** [comment]
I've updated our local test repository to 5.10.2: https://github.com/kit-sdq/Artemis-SAML2-Test-Docker

You can simply change version of `.env` for testing and use preconfigred `data.tgz` if you want to test the changes of this PR (e.g. using the version tag `pr-5710`)
