### ISSUE TITLE
`Exam live statistics`: Chrome issue (Error: <path> attribute d: Expected number)

### ISSUE THREAD

**Issue by Dominik-Weinzierl** [ls1intum/Artemis#5716]
### Describe the bug

The Exam Live Statistics system causes errors when using the Chrome browser (these errors do not occur with Firefox).

![image (4)](https://user-images.githubusercontent.com/60005702/194049151-9349e807-5a35-4dff-8e64-9d9a20274da6.png)

Possible reasons:
- Decimals with multiple decimal places (precision)
- Updating data during re-rendering
- Malformed data: https://stackoverflow.com/questions/62245818/error-path-attribute-d-expected-number-521739130434781-nanl60-739130434
- ...

### To Reproduce

1. Go to Exam Live Statistics Page with the Chrome browser
2. Participate with multiple students
3. Open the console
4. See errors

### Expected behavior

Similar to other browsers, the exam live statistics system should not produce any issues or errors in Chrome.

### What browsers are you seeing the problem on?

Chrome

**Comment by ge65cer** [comment]
Finding no. 22 in [exam mode testing](https://confluence.ase.in.tum.de/pages/viewpage.action?pageId=138610767).
