### ISSUE TITLE
Move course score calculation to the server

### ISSUE THREAD

**Issue by TimOrtel** [ls1intum/Artemis#5741]
### Is your feature request related to a problem?

The course score is currently calculated on the client [here](https://github.com/ls1intum/Artemis/blob/develop/src/main/webapp/app/overview/course-score-calculation.service.ts). However, for the creation of the native clients of Artemis, this calculation has to be copied to the Android/iOS app and always kept in sync with the code of the web version. 

Are there any reasons, why the score should instead be calculated on the client?

### Describe the solution you'd like

The relevant scores should instead be calculated on the server and be sent to the client as attributes in the JSON-object for each course.

### Describe alternatives you've considered

The code could also be duplicated on the native clients.

**Comment by ge65cer** [comment]
When re-implementing this, the scores should also be fetched using the _Participant Scores_ to make it more performant.
