### ISSUE TITLE
Missing course statistics depending on the previous section

### ISSUE THREAD

**Issue by Dominik-Weinzierl** [ls1intum/Artemis#5742]
### Describe the bug

https://user-images.githubusercontent.com/60005702/196202304-1d78dc31-4001-45f6-be8c-8983e2a9feda.mp4

### To Reproduce

1. Go to the Exercises
2. Switch directly to the Statistics
3. See missing Statistics
4. Reload the page
5. Statistics should be visible

### Expected behavior

---

### What browsers are you seeing the problem on?

Firefox

**Comment by ge65cer** [comment]
Re-tested on TS1 with v6.0.0. - can not reproduce.
