### ISSUE TITLE
Automatically refresh the deployment page

### ISSUE THREAD

**Issue by ge65cer** [ls1intum/Artemis#5743]
### Is your feature request related to a problem?

When deploying to a test server to review a PR, the "maintenance mode" page does not automatically refresh.

### Describe the solution you'd like

I'd be great if the page would automatically reload every 3-5 seconds so that I can immediately see in the browser tab title when the deployment is completed.

### Describe alternatives you've considered

Manually refreshing the page multiple times until the deployment is complete.

### Additional context

https://www.w3schools.com/tags/att_meta_http_equiv.asp

<img width="300" alt="Screenshot 2022-10-17 at 20 09 33" src="https://user-images.githubusercontent.com/102237363/196251851-077ce3cf-a0ad-40d7-986d-83dd1de1b7f9.png">

**Comment by sleiss** [comment]
@ge65cer We have already merged the corresponding PR two weeks ago, but I forgot to deploy the change: https://github.com/ls1intum/artemis-ansible-collection/pull/26

I have deployed it on TS0, TS1 and TS2 now.
