### ISSUE TITLE
Adding of users

### ISSUE THREAD

**Issue by kpdin** [ls1intum/Artemis#5746]
### Describe the solution you'd like

Creation of new users (Student) with help of CSV file.
Creation of new users (Tutor,Editor,TA) with help of CSV file.
Creation of Course with CSV file (it may be useful while same course as been offered with more than one faculty in a semester)

**Comment by ge65cer** [comment]
You can already import users from a CSV file. 🙂 

![Screenshot 2022-10-18 at 19-50-01 Groups](https://user-images.githubusercontent.com/102237363/196506961-cdd1f486-cc51-4af5-a481-f0ce582dd5be.png)

For the course feature, we track this issue in #3765
