### ISSUE TITLE
Student not able to resume exercise

### ISSUE THREAD

**Issue by chaimaghaddab** [ls1intum/Artemis#5747]
### Describe the bug

The bug happens as follows: 
1. Student requests feedback
2. Student does not get feedback yet, probably queued in the requests list
3. Student wants to resume exercise (presses resumes exercise)
4. Artemis displays resume exercise 
5. Student receives the errors on the attached image
![IMG_20221017_131239](https://user-images.githubusercontent.com/74461116/196399269-89a03af3-4b5f-4881-b038-6b3156bbf86c.jpg)

Suspected problem: the build is being cleaned up for the exercise

### To Reproduce

1. Request feedback for 100% submission
2. Do not give feedback for the submission (pending)
3. Try to resume exercise
4. The error should occur then

### Expected behavior

The Student should be able to resume the exercise

### Screenshots

![IMG_20221017_131239](https://user-images.githubusercontent.com/74461116/196399951-cf68d399-f111-4a0a-a552-df6b3de80777.jpg)

### What browsers are you seeing the problem on?

Chrome

**Comment by simon-hng** [comment]
Does the `Resume Exercise` button appear instantly after submitting feedback?

**Comment by chaimaghaddab** [comment]
They said after a while they see the resume exercise button but no exact time or reason for it
