### ISSUE TITLE
Allow users to get Mails for certain Artemis Events

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#5748]
### Is your feature request related to a problem?

Currently, Artemis only allow users to get mail notifications for certain posts (discussion feature)

![image](https://user-images.githubusercontent.com/22198798/196431756-6ee53a84-8d79-4364-9409-374a34fbb00a.png)

### Describe the solution you'd like

Allow users to get mails for any discussion post (similar to ILIAS mail notifications) by composing mails with many "bcc" recipients to keep load as low as possible

**Comment by ge65cer** [comment]
Duplicate of https://github.com/ls1intum/Artemis/issues/3424?

**Comment by dfuchss** [comment]
Possibly. There's also https://github.com/ls1intum/Artemis/issues/5164 .
Maybe they should be merged to one issue.

**Comment by dfuchss** [comment]
Currently, not needed anymore by us :)
