### ISSUE TITLE
`Quiz exercises`: It is not possible to save a quiz exercise when I change the visible date

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#5772]
### Describe the bug

It is not possible to save a quiz exercise when I change the visible date to a date after the actual one. 

### To Reproduce

1. Go to Quiz exercises and create or import a quiz exercise and save it. 
2. Click on edit 
3. Scroll down to change the visible date to a different date than the actual date
4. check if the "save" button is deactivated (see the screen cast)
screencast

### Expected behavior

As long as the visible date is before the start date, the quiz should be able to be saved. 

### Screenshots

https://user-images.githubusercontent.com/88991954/197578028-ca269ce3-d96c-4b10-8df7-f9ca3aa85c6a.mov

### What browsers are you seeing the problem on?

Chrome

**Comment by JohannesStoehr** [comment]
Might have been introduced in #5455
