### ISSUE TITLE
Refactoring: `FileService` should use paths instead of strings

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#5793]
### Is your feature request related to a problem?

The [`FileService`](https://github.com/ls1intum/Artemis/blob/develop/src/main/java/de/tum/in/www1/artemis/service/FileService.java) uses `String`s instead of proper `Path`s as parameters for most public methods.

### Describe the solution you'd like

Using proper paths would make the usage less error-prone. E.g., cases

- using the correct path separator,
- possibly forgetting the path separator when building paths manually

would then be definitely handled correctly.

Quite a few users of the public methods of this service already use `Path`s but then convert them to `String`s just for passing them to the file service.

### Additional context

The file service is used in a lot of places, so the changes to the public methods here might affect a lot of code. In case a pull request would get too big, it would also make sense to gradually transition the public interface of the service:
- add a new implementation using proper paths for an existing public method,
- call the new implementation from the old one,
- add a `@Deprecated(forRemoval=true)` annotation to the old public method if removing it directly would cause too many changes for one PR, or remove it directly.

*good first issue*: Every partial transition already improves the code quality, so smaller refactorings parts of the `FileService` as described above are very welcome.

**Comment by Strohgelaender** [comment]
Related:
The `FilePathService` is currently full of methods like this:
```
    public static String getLectureAttachmentFilePath() {
        return Path.of(fileUploadPath, "attachments", "lecture").toString();
    }
```

this should be refactored to directly return a Path:
```
    public static Path getLectureAttachmentFilePath() {
        return Path.of(fileUploadPath, "attachments", "lecture");
    }
```
