### ISSUE TITLE
Feedback points field does not change color when value changes

### ISSUE THREAD

**Issue by tobias-lippert** [ls1intum/Artemis#5818]
### Describe the bug

When you assess a submission as a tutor and create a new feedback block and you change the points to a negative number, the field color stays green (see screenshot) instead of becoming red.

### To Reproduce

1. Go to a course with an exercise that requires manual assessment
2. Go to the assessment dashboard, select the exercise and start a new assessment
3. Add a new feedback
4. Enter some feedback and a negative number of points
5. See that the color does not change

### Expected behavior

The field color should change to red to color code whether feedback gives points or deducts points

### Screenshots

![image](https://user-images.githubusercontent.com/84102468/200193085-5d6c2d3c-4341-4dc5-a924-f60a0c4c607a.png)

### What browsers are you seeing the problem on?

Chrome

**Comment by Strohgelaender** [comment]
I think the green and red here are used to validate your inputs. It will turn red if the text is missing or if you type in non-numerical values.
