### ISSUE TITLE
`Programming Exercises`: Re-add test score to result

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#5824]
### Is your feature request related to a problem?

In #5715 the result score has been shortened.
Since, we do not provide all tests during the task (we use "after due date" as visibility), students get confused by results that show only "30% (vorläufig)" without any mention of successful tests. 
![image](https://user-images.githubusercontent.com/22198798/200320662-269f07aa-48ce-46ad-8d3c-4bc3988ba1c8.png)

### Describe the solution you'd like

I would suggest to re-add at least the information about the amount of successful test cases to the editor. 
We already got questions like "Why do I only have 30% of the points?" by students that had all visible tests green.

**Comment by krusche** [comment]
We intentionally kept it short and ask students to open the details view to find our more about how the score is calculated.

The score should always be clickable to open the result details.

If this is not the case in your example, we should fix it.

If you have an idea how we can better indicate that students can click on the result, feel free to propose it here

**Comment by krusche** [comment]
@JohannesStoehr can you double check that the result details can always be opened? I think we should even activate this for cases where all tests pass.

@Strohgelaender and @simon-hng also have in mind to provide additional details in the result details screen in the future

**Comment by Strohgelaender** [comment]
The score is only clickable if `hasFeedback` is set to true. It could be that this is not the case here, since all publicly available tests were successful (no feedback message) and therefore no details are available.

See also this discussion: https://github.com/ls1intum/Artemis/pull/5758#discussion_r1014620793

**Comment by dfuchss** [comment]
The biggest problem I see is that the students have no insights about their success before opening the details. So they always need to open the details in order to see how many tests passed.

**Comment by krusche** [comment]
As I said before: in the future, it should be possible to always open the details, independent of "hasFeedback" which we potentially could remove and independent of certain logic
