### ISSUE TITLE
`Communication`: Ordering of posts shows wrong order

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#5840]
### Describe the bug

Our TAs said:

The posts in communication are ordered by date. Nevertheless, they are not ordered by their latest response. That makes it hard to identify whether there are new posts or not.

### To Reproduce

1. Open two threads in communication (A and B).
2. Write a comment in A, then in B, and afterwards in A.

### Expected behavior

The threads should be ordered by their latest change, not by their creation date.

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

**Comment by dfuchss** [comment]
@stefanwaldhauser @egekurt123 Is this resolved be the new communication / messaging module?

**Comment by krusche** [comment]
the new messaging module works like a chat, which shows the latest message at the bottom, no matter when the last reply in a thread has been
