### ISSUE TITLE
Show open complaints in tutor dashboard

### ISSUE THREAD

**Issue by Khalphion** [ls1intum/Artemis#586]
### Is your feature request related to a problem?

I really like the new tutor dashboard that includes the #530 features.
However, I think there's still some space where you could display the amount of open complaints as well. 

**Also, you should introduce another filter "Unevaluated complaints", because unticking "Show finished exercises" will hide exercises with complaints.**

### Describe the solution you'd like

Something like this for example?
![image](https://user-images.githubusercontent.com/10117554/59617961-97520e00-9127-11e9-8325-e987b9aca5a3.png)

### Describe alternatives you've considered

A simple number in a separate column is also nice.

**Comment by Khalphion** [comment]
Would help to get all complaints evaluated at the end of the semester :)

**Comment by krusche** [comment]
@HanyaElhashemy this would really be a useful feature. It should be fairly simple to implement. Could you have a look?

**Comment by jerhard** [comment]
Is there a timeline when this change is going into production?

**Comment by krusche** [comment]
It was already deployed as part of the 3.10.1 release

**Comment by jerhard** [comment]
Interesting. I don't see where the number of open complaints is displayed, though?

The numbers below show Feedback Requests + Complaints.

![Tutor Course Dashboard](https://user-images.githubusercontent.com/5951582/75034064-a48c7d00-54ac-11ea-875c-90b04419e8c0.png)

**Comment by krusche** [comment]
We combined this. The yellow progress bar shows you that there are 7 open requests (including complaints)
