### ISSUE TITLE
Reduce Metis queries and reduce waiting times for users.

### ISSUE THREAD

**Issue by TimOrtel** [ls1intum/Artemis#5881]
### Is your feature request related to a problem?

In order to support proper storing of metis posts on Android and iOS metis needs the following features:

- **Paging with post offset**: Currently, you can specify a page size and the number of page you would like to query. However, you should also be able to query n posts starting from a post id. E.g: The client currently knows of 23 posts. The client now wants to load 20 additional posts. Therefore, the client sends a query with the id of the last post it knows of and the server sends the next 20 posts.
- **Replay the last changes that happened since a specified time**: The server already supports to send updates about new/removed or updated posts using STOMP. However, it should be possible to query for the changes that happened since a specified time. For example, a smartphone could lose internet connection for 3 minutes. Because it missed the updates for this time, it has to reload all courses. Instead it should be possible to query a list of all events that happened starting off a specified time.
The json could look something like this:
```json
[
  {
    "type": "deleted",
    "postIds": [412, 541, 212]
  },
  {
    "type": "newOrUpdated",
    "posts": [
      {... post1},
      {... post2},
    ]
  }
]
```
New or updated should send all posts so that the client can add/replace them accordingly.
If more events happened than a specified threshold, the server could instruct the client to instead wipe its cache and reload everything. For example, if more than 20% of all posts are affected by changes (but at least 30 posts) the server could send a "RESET" response.

### Describe the solution you'd like

Create a rest endpoint e.g. `/getChangedPostsFrom` with an additional query parameter `from: timestamp` and return a json similar to the example above.

To do that we need to 
1. Add a field `lastUpdated: timestamp` to `Posting.java`
2. Mark deleted postings. see below

#### Problems
Currently there is no way to know if a post was deleted, as they are just deleted from the database. There are two possible solutions:
1. Create a new boolean flag in the Postings model `isDeleted`
3. Create a log of deleted

#### Concerns
Going through all posts and checking their `lastUpdated` timestamp arguably might lead to a higher database work load but is necessary to limit the size of json, that we send to our mobile client. It may even be possible to create an index for the lastUpdated timestamp, so that the search goes a lot faster. We still want to limit the time frame in which those requests are possible as well as the amount of them. Tim suggested a size of `deletions < 30`  and `updates < 30`   

### Describe alternatives you've considered

The client could also request all data from scratch every time they may have missed an update.

### Additional context

Will be implemented in pair programming
@simon-hng 
@TimOrtel

**Comment by krusche** [comment]
I don't think such an implementation is needed. I think we should keep it simple!
