### ISSUE TITLE
`Plagiarism checks`: The graphic is not sorting correctly the results 

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#5884]
### Describe the bug

The graphic for the result of the plagiarism check is showing wrong the ranges of plagiarism. 

### To Reproduce

1. Go to course management
2. Click on any programming exercise
3. Click on Plagiarism checks
4. Run the plagiarism check
5. Verify that the X-axis is incorrect. Showing in the opposite site the ranges (Look the screenshot).

### Expected behavior

It should have the correct ranges in the graphic. 

### Screenshots

![Screenshot 2022-11-25 at 18 18 05](https://user-images.githubusercontent.com/88991954/204032957-539dc1b9-dea0-4f13-afee-dfa8a473df83.png)

### What browsers are you seeing the problem on?

Chrome

**Comment by jakubriegel** [comment]
I've checked on ts2 and prod - in both cases the issue does not occur. 

You can check my video from different issue as a reference: https://www.loom.com/share/f636c4a9449d451b98fd6a5e5630cfb1
