### ISSUE TITLE
Communication container does not expand to full page

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#5906]
### Describe the bug

The UI container for communication does not expand to screen size if more posts should be shown.
It's about the bottom space. The container that contains the discussions does not expand vertically.

![image](https://user-images.githubusercontent.com/22198798/204542777-78b7da1a-8ac8-49ed-b658-e0e77ff0fc24.png)

### To Reproduce

1. Go to Communication
2. Create multiple posts that you fill the communication view

### Expected behavior

The container should be expanded to the full page

### What browsers are you seeing the problem on?

Firefox

**Comment by pellumbbaboci** [comment]
I think this happened after virtual scrolling was introduced. And also this depends on screen size as when i zoom out to 80% it looks like the following picture
![Percent_80](https://user-images.githubusercontent.com/26312757/205967799-f9069913-a57c-4bf1-ae4a-5e3137447249.png)


And when its 100% looks like the following:
![Percent_100](https://user-images.githubusercontent.com/26312757/205968076-5410d632-f50c-4de7-8c8f-080803e6bc3c.png)


@dfuchss Do you think that even if users zoom out it should fill the below space?

**Comment by dfuchss** [comment]
I'll have a look at it. (I'll send a full screenshot when I'm at home)

**Comment by pellumbbaboci** [comment]
> I guess it should expand at any zoom level?

I am not quite sure, i think that if you zoom out it is normal to have the space below.  But maybe someone else could also comment on this. 

I tested on different screen sizes (24 inch, 27 inch and 15 inch) and on different browsers (firefox, chrome), if zoom level is 100% there is no space below. And also if someone has a bigger screen could test in 100% zoom level and give a feedback.

**Comment by dfuchss** [comment]
Maybe it's about the resolution? I've two monitors (3840x2160 and 2560x1440) 

If I'm on the monitor with the smaller resolution, the height is constantly at 769.733px 
![image](https://user-images.githubusercontent.com/22198798/206313694-30a8223d-c73a-4b7d-8039-45d11795a229.png)
On my 4K monitor that changes to 769.067px

Maybe it's about the scaling Windows does (e.g., for the 4K monitor it's set to 150% in the windows display settings)
