### ISSUE TITLE
Counter for participations counts TA's participations as well

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#5924]
### Describe the bug

The counter for the participation does not only consider students:
E.g., 
![image](https://user-images.githubusercontent.com/22198798/205679914-bbce7039-a34b-42e9-b5ab-2c63cd439d01.png)
Here, only 2 TAs participated in the tasks so far. (Normal students are locked)

### To Reproduce

Create a participation as Tutor and check counters at several sites in the artemis UI

### Expected behavior

The participation of people that are not in the "student" group of the course should be excluded from any calculation.

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

**Comment by pal03377** [comment]
probably related: #5418

**Comment by dfuchss** [comment]
@laadvo since you assigned yourself: Is this issue still present or resolved?

**Comment by krusche** [comment]
The question is if this is really a problem. If TAs act as students, it might be good to include them here as well. Otherwise, the TAs would need to be filtered out in all places

**Comment by dfuchss** [comment]
That's also true . I'll reopen in the future if needed .
