### ISSUE TITLE
Refactor Submissions lists for the various exercise types

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#5941]
### Is your feature request related to a problem?

The list view for submissions of the various exercise types are implemented in different components, even though they share a lot of the same code.

### Describe the solution you'd like

The existing duplication should be reduced by creating a template that can be shared for all exercise types and just the different parts can be plugged into it where necessary.

The components are:
- `programming-exercise-submissions.component`
- `file-upload-assessment-dashboard.component`
- `text-assessment-dashboard.component`
- `modeling-assessment-dashboard.component`

### Additional context

The ‘Scores’ tables seem to contain a very similar content. Maybe the submissions view can even be merged with them?

**Comment by JohannesStoehr** [comment]
This table will probably merged with the scores view soon, since it does not provide any additional information
