### ISSUE TITLE
`Quiz exercise`: Error when trying to edit a Quiz with an added Batch

### ISSUE THREAD

**Issue by laadvo** [ls1intum/Artemis#5958]
### Describe the bug

When there is a quiz in batched mode and a new batch has already been added, an internal server error occurs after editing the quiz (e.g changing the duration, changing batched mode to synchronized) and trying to save the changes. Cancel then has to be clicked to leave the page and all changes are lost.

### To Reproduce

1. Go to Course Management and select a course as instructor
2. Click on Exercises
3. Click on Create Quiz under Quiz Exercises
4. Give a title to the quiz and add a question
5. For Batch Mode select **Batched**
6. Save the quiz and click Back
7. Click the Add Batch button
8. Edit the quiz by for example decrease the duration
9. Error occurs

### Expected behavior

Since a batch has already been created it might not make sense to be able to edit the quiz. The instructor / tutor should be informed of this instead of getting an exception.

### Screenshots

![image](https://user-images.githubusercontent.com/73339358/207100091-679a81a5-9091-46e2-b397-c825e2c28549.png)

### Which version of Artemis are you seeing the problem on?

6.0.0

### What browsers are you seeing the problem on?

Chrome

### Additional context

I observed this bug while testing a PR related to batch mode on ts1 and ts2.

**Comment by krusche** [comment]
@rriyaldhi could you please take a look?

**Comment by rriyaldhi** [comment]
> @rriyaldhi could you please take a look?

yes, I'll fix it

**Comment by rriyaldhi** [comment]
The issue was fixed by this PR [#5968](https://github.com/ls1intum/Artemis/pull/5968).
