### ISSUE TITLE
`Exercises`: Import UI broken

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#5960]
### Describe the bug

See screenshot. The UI to import exercises does not work.

It is probably related to the Category chips.

### To Reproduce

1. As instructor, try to import an exercise (tested with a programming exercise).

### Expected behavior

The import UI works.

### Screenshots

![Screenshot 2022-12-13 at 13-07-10 Import Programming Exercise](https://user-images.githubusercontent.com/64250573/207313820-1ce797ae-9b16-45b0-ba77-7fc48e135d83.png)

### Which version of Artemis are you seeing the problem on?

`develop`

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
ERROR TypeError: this._chipInput is undefined
    Angular 27
        get focused
        MatFormField_HostBindings
        processHostBindingOpCodes
        refreshView
        refreshComponent
        refreshChildComponents
        refreshView
        refreshEmbeddedViews
        refreshView
        refreshComponent
        refreshChildComponents
        refreshView
        refreshEmbeddedViews
        refreshView
        refreshComponent
        refreshChildComponents
        refreshView
        detectChangesInternal
        detectChanges
        tick
        next
        invoke
        onInvoke
        invoke
        run
        run
        next
    RxJS 6
    Angular 20
    RxJS 31
    ArtemisVersionInterceptor artemis-version.interceptor.ts:40
    ArtemisVersionInterceptor_Factory main.js:2505
    Angular 22
    RxJS 20
instrument.js:108:32
    instrumentConsole instrument.js:108
    handleError Angular
    handleError sentry.error-handler.ts:73
    Angular 12
    RxJS 6
    Angular 20
    RxJS 31
    ArtemisVersionInterceptor artemis-version.interceptor.ts:40
    ArtemisVersionInterceptor_Factory main.js:2505
    Angular 22
    RxJS 50
    getTranslation ngx-translate-core.mjs:430
    retrieveTranslations ngx-translate-core.mjs:416
    setDefaultLang ngx-translate-core.mjs:363
    ArtemisCoreModule core.module.ts:108
    ArtemisCoreModule_Factory main.js:2345
    Angular 31
    73249 app.main.ts:19
    Webpack 7
```

**Comment by krusche** [comment]
I think this affects the current version in `develop` (6.0), right?

**Comment by b-fein** [comment]
Yes, I assume the upgrades to Angular 15 broke something there.

**Comment by heddendorp** [comment]
The issue is most likely this line
https://github.com/ls1intum/Artemis/blob/89f1c5b18e9af345168e5f6557e76c708c820b01/src/main/webapp/app/shared/category-selector/category-selector.component.html#L15
It leads to the input not existing if there are not categories => the chips grid not being able to bind to it. I'm not sure about the intended behavior so I can't guess what would be the proper way to hide or not hide parts of this ui
