### ISSUE TITLE
`Development`: Default Push Notifications GitLab → Jenkins not working

### ISSUE THREAD

**Issue by 4ludwig4** [ls1intum/Artemis#5973]
### Describe the bug

During testing the following PR:

- #5915

I experienced that the default values for the [GitLab to Jenkins push notification token](https://docs.artemis.cit.tum.de/dev/setup/#gitlab-to-jenkins-push-notification-token) provided [in the docs for the GitLab Quickstart Guide](https://docs.artemis.cit.tum.de/dev/setup/#gitlab-server-quickstart) are not working.
They aren't even working if I use the provided ``master.key`` so maybe sth changed in how they calculate those tokens? According to @sleiss this once worked when he wrote the guide, but it seems like something changed behind the scenes.

In general, it's weird that a project-specific token is being used for this instead of a global token for all projects.
[See the Jenkins GitLab plugin documentation](https://plugins.jenkins.io/gitlab-plugin/#plugin-content-global-plugin-configuration).

As a workaround, I will either modify the docs in the PR where I found the bug or create a new PR 

### To Reproduce

1. set up a new GitLab Jenkins Test setup according to the [GitLab Quickstart Guide](https://docs.artemis.cit.tum.de/dev/setup/#gitlab-server-quickstart)
2. create a programming exercise and submit an exercise

### Expected behavior

No manual labor should be needed for developers, as it once worked with the quick-start guide.

### Workaround

Updated docs in the following PR which states that you have to create this token manually:

- #5982 

### Which version of Artemis are you seeing the problem on?

develop

### What browsers are you seeing the problem on?

Firefox

**Comment by b-fein** [comment]
GitLab no longer uses the webhook to communicate with Jenkins, instead Artemis does that directly now.
