### ISSUE TITLE
Behavior when saving a quiz is different from other exercise types

### ISSUE THREAD

**Issue by tobias-lippert** [ls1intum/Artemis#5985]
### Describe the bug

When creating a quiz and clicking the save button, I am not redirected to any other page.
For all other exercise types I'm redirected to the exercise details page.

This is confusing for users who do not know this behavior.

Since for quizzes no exercise details page exists, maybe redirecting to the preview quiz page is a suitable option.

### To Reproduce

1. Go to a course and create a quiz
2. Click save and see that you stay on the page even after the quiz is saved.

### Expected behavior

I'm redirected to another page.

### Which version of Artemis are you seeing the problem on?

5.12.7

### What browsers are you seeing the problem on?

Chrome

**Comment by krusche** [comment]
This behavior is intended so that quiz creators can save while editing. Quizzes are more than a simple "form" that you fill out and after adding 2-3 questions you might want to save your current work to prevent loosing it.

This is typically not necessary for other exercise types.
