### ISSUE TITLE
Unangemeldeter Kurs

### ISSUE THREAD

**Issue by s1081253** [ls1intum/Artemis#5989]
### Describe the bug

Hallo,

bei mir erscheint ein Kurs, an dem ich nicht teilnehme 

### To Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Hallo,

bei mir erscheint ein Kurs, an dem ich nicht teilnehme: Einführung (die nicht Python ist)

### Screenshots

<img width="1636" alt="Bildschirmfoto 2022-12-21 um 16 22 22" src="https://user-images.githubusercontent.com/115487557/208947067-bb90c1af-1403-40bb-9633-c08c142fe2f4.png">

### Which version of Artemis are you seeing the problem on?

5.9.6

### What browsers are you seeing the problem on?

Safari

**Comment by krusche** [comment]
Please contact your system admin first. If this is really a big, then please specify more details, otherwise we cannot resolve the issue.
