### ISSUE TITLE
Artemis client requires additional packages installation to run

### ISSUE THREAD

**Issue by evgeny1984** [ls1intum/Artemis#5993]
### Describe the bug

When the developer tries to run the Artemis Client locally, the client cannot be compiled because it misses the 2 additional packages to be installed:
- @popperjs/core
- @sentry/types
After the manual installation, the client could be built as expected.
Node version on the local pc: 18.12.1

### To Reproduce

1. Check out the Artemis repostitory
2. Select the Angular Client build configuration
3. Build and debug the project
4. Inspect the error in the console

### Expected behavior

The client should start without manual installation of the additional packages.

### Which version of Artemis are you seeing the problem on?

6.0.0

### What browsers are you seeing the problem on?

Chrome

**Comment by krusche** [comment]
All CI systems run reliably without those packages
