### ISSUE TITLE
`Plagiarism checks`: The submissions of Tutors/Instructors shouldn't be considered in the plagiarism checks

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#6023]
### Describe the bug

Tutors/Instructors sometimes test the code of students to replicate possible issues with the test cases. Their submissions shouldn't be considered in the plagiarism checks. Otherwise, we will have cases with high similarity, which would confuse when instructors deny them. 

### To Reproduce

1. Solve any exercise as a student. 
2. As instructor/tutor, use the submitted code of the student and submit it. 
3. Check that both submissions are presented in the plagiarism checks. 

### Expected behavior

The submissions of Tutors/Instructors shouldn't be considered in the plagiarism checks. 
**_In case this is on purpose should be a way to differentiate the tutor's/instructor's submissions. Maybe a * next to the login (ge##aaa *). In this way, we can deny immediately plagiarism without checking who belongs to that login first._** 
**_Another option would be to mark in another color in the table the case._** 

### Which version of Artemis are you seeing the problem on?

5.12.9

### What browsers are you seeing the problem on?

Chrome

**Comment by Strohgelaender** [comment]
I think this is actually expected. Instructors can submit code they found online (e.g. on StackOverflow) and automatically integrate this code into the plagiarism checks.

This should be better highlighted, however. Also, this case needs to be handled when determining verdicts for plagiarism cases.

**Comment by jakubriegel** [comment]
I vote for simple highlight. 

@MarkusPaulsen is the `*` next to the submission enough?

**Comment by MarkusPaulsen** [comment]
I see two completely different use cases here:

1. The first use case is identifying similarities between two student submissions. These should in an optimal world never happen, as we disallow students to copy from each other (even if cited). Here the tutors/instructors code should not be considered.
2. The second use case is identifying similarities between a student submission and an outside source. These should in an optimal world never happen in an uncited manner, as we should only allow students to use other sources if they cite correctly. Here the tutors/instructors may be considered. But here I think it makes more sense to use an automatic system for scanning the code from sources like StackOverflow and displaxy it in a separate window.

Therefore I think it makes sense to not consider the submissions of tutors/instructors in the current plagiarism check

**Comment by krusche** [comment]
I agree, we should filter them out during the process. Everything else is confusing

**Comment by jakubriegel** [comment]
Ok, I will implement a fix to filter them out
