### ISSUE TITLE
`Plagiarism checks`: It is needed to refresh the page to get the results

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#6025]
### Describe the bug

When a new plagiarism check with a new threshold is run, the icon of loading continues it animation until you force the refresh of the page to show the new results. 

### To Reproduce

1. Go to a programming exercise with submissions 
2. Run a plagiarism check with the threshold by default (50%)
3. Change the threshold (e.g. to 70)
4. Check that the chart is presented but the loading icon in the left-up part continues with its animation. 
5. Check that the table still shows the cases with a threshold of 50% 
6. Wait several minutes and then refresh the page to get the new cases with the new threshold. 
See the screencast.
I re-run the plagiarism check with 70% (it was before 50%), but the chart and table didn't refresh until I force it. 

### Expected behavior

1. The loading icon should stop its animation when the results are presented. 
2. The presentation of the results when you re-run a plagiarism check should be without forcing a refreshing of the page. 

### Screenshots

https://user-images.githubusercontent.com/88991954/210233755-457173e5-f613-4759-8170-4697743fa016.mov

### Which version of Artemis are you seeing the problem on?

5.12.9

### What browsers are you seeing the problem on?

Chrome

**Comment by jakubriegel** [comment]
@Santia-go this looks like already fixed. Here is a video:
https://www.loom.com/share/f636c4a9449d451b98fd6a5e5630cfb1

Could you confirm?

**Comment by Santia-go** [comment]
Confirm! 
This issue is fixed
