### ISSUE TITLE
`Exam`: artemis crashes if submitting unsupported file type for first time

### ISSUE THREAD

**Issue by simon-hng** [ls1intum/Artemis#6028]
### Describe the bug

Submit a file with unallowed ending, leading to a crash.

### To Reproduce

Submit a unallowed file type in a file upload submission with a file size over the limit

Example using `jpg` in a exercise allowing `png, pdf` 

### Expected behavior

Shouldn't crash

### Screenshots

![image](https://user-images.githubusercontent.com/25489463/210550289-84d58536-8d9c-43a4-8590-787159d75605.png)

### Which version of Artemis are you seeing the problem on?

6.0.0

### What browsers are you seeing the problem on?

Chrome

### Additional context
uploaded this image in size 5,803 × 3,918; 5.56mb
https://commons.wikimedia.org/wiki/File:Katsushika_Hokusai_-_Fine_Wind,_Clear_Morning_(Gaif%C5%AB_kaisei)_-_Google_Art_Project.jpg

**Comment by krusche** [comment]
What do you exactly mean with crash? Can you please provide more details?

**Comment by easy-lisi** [comment]
Tested with Artemis 7.5.6 without any issues.
