### ISSUE TITLE
`Tutorial Groups`: General configuration, date picker opens in wrong location

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#6035]
### Describe the bug

The date picker in the tutorial group general settings opens in the wrong location.

### To Reproduce

1. Go to ‘Tutorial Groups’ for a course.
2. Edit the configuration.
3. Select the from/to dates for the groups.
4. C.f. screenshot.

### Expected behavior

The date picker does not open in the top-right corner of the browser window.

### Screenshots

![Screenshot 2023-01-04 at 11-05-46 Create global Tutorial Groups Configuration](https://user-images.githubusercontent.com/64250573/210531599-c73cdfa8-3ad3-4510-a0ad-c9da6ab7bcc2.png)

### Which version of Artemis are you seeing the problem on?

develop, commit b6f6ae519f6f039bd5791a7efccd0382827e70c2

### What browsers are you seeing the problem on?

Firefox

**Comment by stefanwaldhauser** [comment]
Thanks for catching this! I will fix it
