### ISSUE TITLE
`Tutorial Group`: From/To date picker unintuitive behaviour

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#6038]
### Describe the bug

The date picker contains the options to set a From and a To date. It highlights the next date that will be set on the bottom.

However, when editing an existing selection and manually clicking on the ‘To’ row at the bottom
- the ‘To’ row gets highlighted as active, and
- when clicking on a date, the ‘From’ date gets set and the ‘To‘ date removed.

### To Reproduce

I only know the tutorial group global settings where this picker is used at the moment, maybe there exist more locations.

1. Go to the tutorial group settings for a course.
2. Top-right: More > Edit Global configuration.
3. Try to edit the from/to dates as described above.

### Expected behavior

- The currently highlighted date gets set.
- The other date does not get removed when changing one date.

### Which version of Artemis are you seeing the problem on?

develop, commit b6f6ae519f6f039bd5791a7efccd0382827e70c2

### What browsers are you seeing the problem on?

Firefox

**Comment by stefanwaldhauser** [comment]
I will look into it, if this can be easily changed

**Comment by stefanwaldhauser** [comment]
I agree this can be considered maybe unintuitive but I think this is currently not a bug as it is a standard component with standard behavior. Also the global configuration is changed maybe once during a whole course.
