### ISSUE TITLE
`Tutorial Groups`: Language setting can only be German/English

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#6039]
### Describe the bug

When creating a tutorial group the language can only be German or English.

### To Reproduce

Create or edit a tutorial group. The language setting is a choice between the two options.

### Expected behavior

The language can be input in a free-form text. This allows Artemis to be independent of the language choice of instruction.

### Which version of Artemis are you seeing the problem on?

develop, commit b6f6ae519f6f039bd5791a7efccd0382827e70c2

### What browsers are you seeing the problem on?

Firefox

**Comment by stefanwaldhauser** [comment]
Hi @b-fein. Thanks for the suggestion. Will implement it :)
