### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by leukschrauber** [ls1intum/Artemis#6055]
### Describe the bug

When using Firefox 108.0.2 (64-bit), I was unable to mark the "Accept terms" checkbox to login, which ultimately prevents me from logging in.

### To Reproduce

1. Go to the starting page
2. Click on "Bedingungen akzeptieren"
3. Box does not tick => Login is prevented

### Expected behavior

Box "Bedingungen akzeptieren" is ticked and login is made possible.

### Which version of Artemis are you seeing the problem on?

5.9.8

### What browsers are you seeing the problem on?

Firefox

### Additional context

Firefox 108.0.2 (64-bit)

**Comment by krusche** [comment]
At which university are you using Artemis?

**Comment by leukschrauber** [comment]
University of Innsbruck @krusche. I've attached a screenshot. Seems to be as well related to the resolution of the screen as it works on my external monitor, but not on my laptop screen.
![grafik](https://user-images.githubusercontent.com/122229139/211368640-e2b5bd3e-b2e0-4eac-865e-1d04f106cb21.png)

**Comment by krusche** [comment]
@daniels98it could you have a look into this issue? Might be related to custom adaptions in the Innsbruck Artemis version

**Comment by daniels98it** [comment]
The issue has now been fixed 👍 @leukschrauber Could you please test it and let me know?

Additionally, the pop-up message responsible for the bug will be completely removed by next week.

**Comment by leukschrauber** [comment]
Works @daniels98it. Mille grazie. :)
