### ISSUE TITLE
Model assessment impossible after cancelling the submission dialogue box

### ISSUE THREAD

**Issue by Khalphion** [ls1intum/Artemis#609]
# Describe the bug

The assessment popover closes immediately after a keypress.

#### To Reproduce

1. Model assessment
2. Assess one element
3. Click on Submit
4. "Cancel" in dialogue
5. Unassessed elements are highlighted
6. Assess another element, try to enter feedback / change points, etc: See error, the popup closes immediately as soon as a key is pressed.

![ezgif-2-32020b8bee28](https://user-images.githubusercontent.com/10117554/60439045-4f94b180-9c12-11e9-8344-85a18841edd3.gif)

The bug disappears after a complete page reload.

### Environment

<details><pre>
 - OS: Linux (Ubuntu Disco Dingo)
 - Browser: Chromium Version 75.0.3770.100 (Official Build) snap (64-bit)
 - Version Artemis 3.22
</pre></details>

**Comment by SiggZ** [comment]
Hi @Khalphion, thank you for the meaningful bug report. We fixed the issue in https://github.com/ls1intum/Artemis/pull/548 which will be released very soon.

**Comment by SiggZ** [comment]
I close this issue as this is fixed by now.
