### ISSUE TITLE
Statistics of a Course not displayed correctly

### ISSUE THREAD

**Issue by philippzagar** [ls1intum/Artemis#6103]
### Describe the bug

The statistics functionality for a course (as a student) is not working as expected.
Before clicking the 'Refresh' button on the Statistics page of a course, the displayed data differs from the data after clicking the 'Refresh' button.
Only the "after-refresh" data is actually correct.

### To Reproduce

1. Go to 'Course Overview'
2. Click on a specific course
3. Go to 'Statistics' in the selected course
4. Note down the displayed points (and percentage etc.)
5. Click on 'Refresh'
6. Note that the displayed points etc. changed upon refreshing

### Expected behavior

See the correct statistics, even without manually clicking the 'Refresh' button on the Statistics page of a Course.

### Screenshots

**Screenshot 1: Before clicking the 'Refresh' button**

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/25406915/213443368-d14dfe11-37eb-476b-a27b-f3c73c1e90e3.png">

**Screenshot 2: After clicking the 'Refresh' button**

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/25406915/213443402-b0c60d7d-4510-4558-830b-c47eb848e5ef.png">

### Which version of Artemis are you seeing the problem on?

5.12.9

### What browsers are you seeing the problem on?

Chrome

**Comment by ge65cer** [comment]
Related/duplicate: https://github.com/ls1intum/Artemis/issues/5742
