### ISSUE TITLE
Allow "Open in new Tab" (CTRL / CMD click or middle mouse button)

### ISSUE THREAD

**Issue by Khalphion** [ls1intum/Artemis#611]
### Is your feature request related to a problem?

I sometimes want to compare some submissions/assessments or just quicky open multiple exercise dashboards (for example just before a tutor group session). 

But it's a very tedious task, for each page I'd like, I need to open a new Artemis instance manually in a new tab because right click > "open in new tab" or control-clicking the link doesn't work on any link of Artemis.

### Describe the solution you'd like
When I hold CMD (mac) or CTRL and click on a button or link, I'd like to have it to open in a new tab rather than in the current tab.

**Comment by plainerman** [comment]
When implementing this feature, please evaluate if it is possible to support middle-mouse-click (same behavior as CMD / CTRL click).

**Comment by thilo-behnke** [comment]
The issue is that we define our [routerLink] buttons as a button, while they should be a `<a>`. They can still look the same if properly styled.

**Comment by jpbernius** [comment]
This is more a long-term Vision here, but maybe we should style those links differently (e.g. outline button) to visualize if the user performs navigation or actually any action.
