### ISSUE TITLE
Lecture Units: Mark as completed not saved.

### ISSUE THREAD

**Issue by TimOrtel** [ls1intum/Artemis#6118]
### Describe the bug

When you mark lecture units as completed and you reload the page they are no longer marked as completed.
This must be a server-side bug as the Android app faces the same issue. 

### To Reproduce

Look above. 

### Expected behavior

Should be saved instead of forgotten. 

### Which version of Artemis are you seeing the problem on?

5.12.9

### What browsers are you seeing the problem on?

Chrome

**Comment by krusche** [comment]
this is working in 6.0
