### ISSUE TITLE
`Programming exercises`: Online Editor code completion text not readable in dark mode

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#6130]
### Describe the bug

See screenshot. The code completion suggestion in the online code editor are not really readable in dark mode.

### To Reproduce

1. Switch to dark mode.
2. Go to the online code editor and type something so that the code completion comes up.

### Expected behavior

The text in the pop-up is readable.

### Screenshots

![image](https://user-images.githubusercontent.com/64250573/213989409-db9da72d-59ef-426f-89db-22637848e5d2.png)

### Which version of Artemis are you seeing the problem on?

6.0.0

### What browsers are you seeing the problem on?

Firefox

**Comment by krusche** [comment]
@bassner could you please try to fix that? Thanks!

**Comment by BaumiCoder** [comment]
With the new Monaco editor it looks seems to be resolved.
![Monaco](https://github.com/ls1intum/Artemis/assets/73783062/6687559b-4f12-4b67-b7dd-01d4d257defc)

@b-fein So we can close this issue, right?

**Comment by b-fein** [comment]
:+1:
