### ISSUE TITLE
`Communication`: Detailed configuration option

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#6136]
### Describe the solution you'd like

Version 6.0.0 introduces an enhanced experience for `Communication` features.
![image](https://user-images.githubusercontent.com/22198798/214143024-54b842c3-1024-4fb6-81d8-c9e097f19a90.png)

We would like to configure the availability of possible options (e.g., via checkboxes) 

* Communication Tab
* Channels
* Group Chats
* Direct Messages

We are especially not sure how to deal with not-moderated (Group/DM) in general therefore, we want to disable that for now until we know more about possible consequences.

**Comment by dfuchss** [comment]
I've marked it as high priority, since we are not sure about law/privacy w.r.t. DMs/Group chats. 
Feel free to change the prioritization.

**Comment by dfuchss** [comment]
Related to https://github.com/ls1intum/Artemis/pull/4825

**Comment by krusche** [comment]
We already have an option in the course to activate / deactivate the whole communication module. While we can add additional customization options, we should not make it too complex to avoid code complexity.
