### ISSUE TITLE
`Plagiarism checks`: The duration time is correct? make sense to have it?

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#6143]
### Is your feature request related to a problem?

When you run the plagiarism check in any exercise, at the end you can see that took 00:00:00.### that means milliseconds. 
But actually no, It takes several seconds even minutes (when we have a lot of submissions) to show the results. 
So, what exactly is this duration in milliseconds? 
Does it make sense to show this time? 

<img width="700" alt="image" src="https://user-images.githubusercontent.com/88991954/214538312-4d711d22-405d-4ca5-9e99-eb5a2513b813.png">

### Describe the solution you'd like

A solution would be to show the real time that takes to show the results of the plagiarism checks. Other wise remove this.

**Comment by dfuchss** [comment]
JPlag is normally really fast. Depending on the set of people you can encounter that low time spans. Nevertheless, Artemis downloads all repositories; I assume that this time is not taken into account.

**Comment by krusche** [comment]
Yes, this it he time that JPlag needs. It does not include aspects like downloading everything, storing the results in the database, etc

But I agree, it does not add much value at the moment

**Comment by jakubriegel** [comment]
@Santia-go @MarkusPaulsen maybe just remove this timer? Anyway for the continuous plagiarism control this will be irrelevant. Other option is to fix this clock to show the full time, but I don't think this is a value worth the effort
