### ISSUE TITLE
Exercises showing up as assessed in course statistics but no feedback/assessment visible

### ISSUE THREAD

**Issue by jaspzz** [ls1intum/Artemis#617]
### Describe the bug
Already assessed exercises only show up as assessed on the "course statistics"-page, but on the exercise's detail page, it still shows up as "not assessed".

Contrary to #567 I can also not see the assessment on the detail page of the exercise or any feedback.

I noticed this bug as the total course percentage went up, but no additional exercises showed up as assessed.

#### Screenshots
![Screen Shot on 2019-07-03 at 14_03_51](https://user-images.githubusercontent.com/50105070/60594835-1d1bbd80-9da6-11e9-85bd-382172071a9c.png)
![Screen Shot on 2019-07-03 at 14_04_21](https://user-images.githubusercontent.com/50105070/60594846-23119e80-9da6-11e9-84b4-46ef42d9414a.png)
![Screen Shot on 2019-07-03 at 14_04_29](https://user-images.githubusercontent.com/50105070/60594867-2d339d00-9da6-11e9-9e00-3655ba51e8eb.png)

### Environment

<details><pre>
 - OS: MacOS
 - Browser Chrome, Safari, Safari for iOS
</pre></details>

#### Additional context
I already deleted the browser cache, refreshed the page and tried different browser.

**Comment by SiggZ** [comment]
In the screenshot it says that the assessment due date is in the future. Since the assessment is only visible to students after the assessment due date, it is the intended behavior that you do not see the result or any feedback earlier.
I think the only bug here is that you see information regarding the assessment on the course statistics page before the assessment due date.

**Comment by tosoikea** [comment]
@SiggZ This behavior is reproducable btw. 
Normal behavior (assesment not yet visible, statistics page after fresh reload) :
![image](https://user-images.githubusercontent.com/35578078/62007809-4be14580-b152-11e9-931a-66fa3637cdba.png)
If I then click on the exercise and return to the statistics page I am able to the the current assesments result. This works for every exercise type.
![image](https://user-images.githubusercontent.com/35578078/62007823-759a6c80-b152-11e9-82f1-feb30d0030ec.png)

(Sometimes you need to click any another exercise before assesment is shown. The statistics reset after another page reload.)
