### ISSUE TITLE
`Settings`: Align the top position of both columns

### ISSUE THREAD

**Issue by sebastiannikles** [ls1intum/Artemis#6183]
### Describe the bug

When opening the settings, the left column with your name and the right column with the different settings are not aligned at their tops but start at different positions.

### To Reproduce

1. Log into Artemis
2. Go to settings
3. See the misaligned columns

### Expected behavior

Both columns should start at the same vertical position.

### Screenshots

<img width="1739" alt="diverse_unubersichtlichkeiten_notifications_settings" src="https://user-images.githubusercontent.com/16115423/216498416-1a3dc854-fb10-4480-9ae0-30a03aca6979.png">

### Which version of Artemis are you seeing the problem on?

6.0.2

### What browsers are you seeing the problem on?

Safari

**Comment by tunargs** [comment]
@krusche @sebastiannikles, is this how it is intended? I removed unnecessary horizontal lines and fixed column alignments.

<img width="1399" alt="image" src="https://user-images.githubusercontent.com/81355607/232545020-e416952d-976c-474f-a778-b6de6a3aa478.png">
