### ISSUE TITLE
`Edit Course`: Always Open DatePicker

### ISSUE THREAD

**Issue by sebastiannikles** [ls1intum/Artemis#6189]
### Is your feature request related to a problem?

When editing a course and clicking into the date fields, I can see the cursor and can just start typing. It's not clear that I can only enter a date.

### Describe the solution you'd like

As soon as I click into the field, the date picker should pop up so I can select the date.

**Comment by krusche** [comment]
It is intended that users can also type in the date or copy and paste dates
