### ISSUE TITLE
`Participant Scores`: Table too long for screen and not scrollable

### ISSUE THREAD

**Issue by sebastiannikles** [ls1intum/Artemis#6193]
### Describe the bug

The table that is shown for participant scores is too long to be shown on one view but it's also not scrollable horizontally and thus, hiding some of the content.

### To Reproduce

1. Go to participant scores
2. Play around with the width of the screen
3. See columns appear and disappear
4. Try scrolling horizontally

### Expected behavior

The table should either fit on one screen (make columns smaller) or at least be scrollable horizontally and it should be apparent that it's possible to scroll horizontally.

### Screenshots

![Bildschirm­foto 2023-02-03 um 03 59 24](https://user-images.githubusercontent.com/16115423/216502435-aa578fa4-a237-480d-87be-a33c15a74de8.png)

### Which version of Artemis are you seeing the problem on?

6.0.2

### What browsers are you seeing the problem on?

Safari

**Comment by ge65cer** [comment]
Fixed within https://github.com/ls1intum/Artemis/issues/6230
