### ISSUE TITLE
`Course`: Navigate to Management Directly

### ISSUE THREAD

**Issue by sebastiannikles** [ls1intum/Artemis#6197]
### Is your feature request related to a problem?

When I am an instructor and currently in the "normal" detail view of a course, I have no option to directly go to the management of that course. I have to go back to management and find the course first.

### Describe the solution you'd like

It would be nice if there was a button in the course menu that sends me directly to the management page of a course if I am an instructor for that course.

**Comment by jakubriegel** [comment]
Hi! I'd like to work on this
