### ISSUE TITLE
`Communications`: Archived Posts

### ISSUE THREAD

**Issue by sebastiannikles** [ls1intum/Artemis#6200]
### Is your feature request related to a problem?

When archiving a post, it is not really visually clear that it's archived except for that tiny border around the button. Also, I have no way of hiding archived posts.

### Describe the solution you'd like

The design for archived posts should be updated to make it clearer (grayed out maybe?) and there should be a filer option/toggle to hide/show archived posts in the list.

**Comment by PaRangger** [comment]
Closing due to being stale and the archive button is not available anymore.
