### ISSUE TITLE
Remove Participant Scores page for instructors

### ISSUE THREAD

**Issue by ge65cer** [ls1intum/Artemis#6230]
### Describe the bug

The 'Participant Scores' button/page on Course Management does not offer any real uses cases or benefits for instructors.

### To Reproduce

1. Go to 'Course Management'
2. Click on the 'Participant Scores' button

### Expected behavior

In my opinion, it could be removed entirely or should only be visible to administrators (if we decide to keep it for debugging).

### Screenshots

<img width="400" alt="Screenshot 2023-02-10 at 09 46 23" src="https://user-images.githubusercontent.com/102237363/218045560-8fde74e3-0afa-446d-9498-59754f7c7e31.png">

<img width="400" alt="Screenshot 2023-02-10 at 09 50 58" src="https://user-images.githubusercontent.com/102237363/218046517-fe013fae-0a04-4941-b7ac-516cd4a7457d.png">

### Which version of Artemis are you seeing the problem on?

6.0.0

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge, Firefox

**Comment by ge65cer** [comment]
What's your take on this, @krusche?

**Comment by Strohgelaender** [comment]
I just opened the page and it took over a minute to load: 
![grafik](https://user-images.githubusercontent.com/26540346/218114604-f0397cda-e2ca-4fd8-9882-968aa1434a5a.png)

If we decide to keep it, we should do the paging on the server and increase the performance.

**Comment by krusche** [comment]
I agree, let's remove it together with the corresponding Server rest call
