### ISSUE TITLE
Statistics view shows incorrect points on first load

### ISSUE THREAD

**Issue by maximiliansoelch** [ls1intum/Artemis#6254]
### Describe the bug

Besides having already one exercise completed, the statistics view still indicates that I received 0 points.
After reloading the page, the score is updated to the correct value.

### To Reproduce

See Screenrecording

### Expected behavior

The statistics view should display the correct values already on the first load.

### Screenshots

https://user-images.githubusercontent.com/9954674/219050983-b4f1f622-e428-464d-b13f-d2f717fd578f.mov

### Which version of Artemis are you seeing the problem on?

6.0.5

### What browsers are you seeing the problem on?

Safari

**Comment by Strohgelaender** [comment]
Related to #5742?

Do you have a reproducible example for this issue? Neither @ge65cer nor I were able to recreate this locally.

**Comment by maximiliansoelch** [comment]
@Strohgelaender Yes, the issue seems to be related to #5742.
I have a reproducible example on production. The exercise was imported from a previous course, maybe that has something to do with it.

**Comment by maximiliansoelch** [comment]
I could once again reproduce the issue on Safari with a test user. I will send you the details over Slack.
