### ISSUE TITLE
Incorrect visualization of the current exercise's status

### ISSUE THREAD

**Issue by maximiliansoelch** [ls1intum/Artemis#6263]
### Describe the bug

On the student's exercise dashboard, the visualization of the current exercise's status differs from the status shown in the exercise's normal visualization.
This behavior occurs on the first load as well as on a reload. Switching the ribbon (for example to Lectures) fixes the visualization.

### To Reproduce

See screen recording

### Expected behavior

The exercise state should be consistent on the whole dashboard.

### Screenshots

https://user-images.githubusercontent.com/9954674/219441842-12c897ef-29ba-4c62-a3a4-4132039e9275.mov

### Which version of Artemis are you seeing the problem on?

6.0.5

### What browsers are you seeing the problem on?

Chrome

**Comment by ge65cer** [comment]
Probably because the for-dashboard request does not contain some specific data needed for rendering the dates.
