### ISSUE TITLE
No links to the quiz exercises on the title on the exercise overview page

### ISSUE THREAD

**Issue by nikirovast** [ls1intum/Artemis#6295]
### Describe the bug

If you open 'Exercises' page of the course overview, the quiz exercises titles are presented as text, without links to them.

### To Reproduce

1. Go to 'Course Management'
2. Click on 'Exercises'
3. See that the titles of the quizzes are not links, but just text

### Expected behavior

Quizzes titles are also links to them

### Screenshots

Programming exercises:

<img width="1410" alt="Screenshot 2023-02-24 at 14 36 38" src="https://user-images.githubusercontent.com/44327027/221193263-50601607-e7f6-453c-8ba9-3757743aaae7.png">

Quizzes:

<img width="1413" alt="Screenshot 2023-02-24 at 14 36 58" src="https://user-images.githubusercontent.com/44327027/221193429-cf9331a3-7c3a-4e9a-a7e5-bccc1f95a4ba.png">

### Which version of Artemis are you seeing the problem on?

6.0.7

### What browsers are you seeing the problem on?

Chrome

**Comment by Strohgelaender** [comment]
This is correct since there is no details page for quizzes. You can only edit them or use the preview functionality.

**Comment by ge65cer** [comment]
Simply duplication the link of 'id' column should fix this.
