### ISSUE TITLE
Long Feedback Texts

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#6296]
### Is your feature request related to a problem?

Similar to #4796, we have some exercises that test programs via CLI interactions. Therefore, more text output is generated which sometimes is longer than 5.000 characters.

## Data Model

A new database table `long_feedback` is created (pseudo-SQL):
```sql
create table long_feedback (
   id serial primary key,
   feedback_text longtext, -- liquibase type gets mapped to longtext in MySQL , text in PostgreSQL
   feedback serial foreign key references feedback.id
)
```

The existing `feedback` gets extended with a `bool` flag `long_feedback_exists` that indicates whether this feedback was truncated and a separate long feedback is stored.
Therefore, each long feedback is linked to exactly one regular feedback and cannot exist without one. The `feedback` only contains information if some optional long feedback exists.

### Server 

New feedback creation: Check if feedback is longer than the current limit:
- if not, no special action is needed
- otherwise:
  - truncate the regular feedback text to either the first line, or to the first 200 (?) characters similar to how it is displayed in the client currently and set the long feedback flag
  - save the full feedback text separately into the long feedback table and connect it to the regular feedback it belongs to

Endpoint to fetch feedback:
- When delivering results/feedbacks to the client, the long feedbacks are not transmitted. The client can determine later due to the flag if additional long feedback should be fetched separately.
- A new REST endpoint `api/participations/{participationId}/results/{resultId}/feedback/{feedbackId}/long-feedback` is introduced.
  - This delivers the `feedback_text` of the `LongFeedback` connected to the regular feedback with `feedbackId` to the client as plain text.

### Client

When feedback is displayed, only the flag if long feedback exists is known.
Based on this, the information that the feedback has been truncated can be displayed. Additionally, a link should be present that opens a new tab where the long feedback text is shown as plain text information.
Showing the feedback inside the Artemis UI would have little benefit, since there is no way to syntax-highlight relevant parts, so it would have to be displayed there as a text blob anyway.

## Security

Even the feedback will still be truncated at some reasonable limit that should realistically never be exceeded, e.g. a few MiBs (that would still allow feedback with a few million text characters). This prevents denial-of-service attacks where arbitrarily large feedback has to be processed and stored. E.g. students might be able to craft long logs/assertion message content in their programs that would then be stored as feedback in Artemis.

### Additional context

In case the full feature is not ready for the maintenance window at TUM (March 6th to 10th), a minimal database migration could be applied to the large `feedback` table to make use of the downtime there and avoid separate Artemis service interruptions:
The `feedback` table gets extended with the `bool` flag `long_feedback_exists` which then would remain unused until the full implementation is ready.

**Comment by dfuchss** [comment]
Does https://github.com/ls1intum/Artemis/pull/6306 resolves the issue?

**Comment by b-fein** [comment]
No, not yet. The linked PR only performs the necessary database migrations to make use of the maintenance at TUM and avoid separate downtime to apply a long-running migration to the large `feedback` table there.

The actual implementation that makes use of the new table still has to be done.

**Comment by b-fein** [comment]
Implementation of long feedbacks is now ready for review in #6386.

**Comment by krusche** [comment]
I had a look in the Artemis Production DB at TUM, how the last approx. 18 million feedback entries are divided regarding `detail_text` (without distinguishing the feedback type)
96.1% are less than 300 characters, 3.9% are greater than or equal to 300 characters
97.5% are under 500 characters long, 2.5% are 500 characters or longer
98.7% are under 1000 characters long, 1.3% greater than or equal to 1000 characters
99.3% are under 2000 characters long, 1.3% greater than or equal to 2000 characters

=> so we could do long feedback much earlier than 5000 characters without having a big impact
