### ISSUE TITLE
`Communication`: Allow definition of Contexts

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#6316]
### Is your feature request related to a problem?

We would like to define contexts for our exams (as they are long running exams, where students are allowed to ask questions).
Nevertheless, we can't create a suitable context for this purpose.

Therefore, we would like to add custom contexts.

### Describe the solution you'd like

see above

**Comment by dfuchss** [comment]
For now, we are using "Dummy"-Tasks in order to define contexts.

**Comment by dfuchss** [comment]
@egekurt123 can that be closed with the new messaging/communication module. I guess it's possible now to create channels.

**Comment by krusche** [comment]
yes, if the new communication module is enabled, there should be a channel for each exam in which students can ask corresponding questions
