### ISSUE TITLE
An error has occurred while loading and displaying the Artemis website :-(

### ISSUE THREAD

**Issue by RuiRioPina** [ls1intum/Artemis#6317]
### Describe the bug

When cloning the repo for the first time and running ```docker compose up``` on the root folder it shows a white troubleshooting page, after it's done doing its thing. 
- The troubleshooting page isn't loaded immediately, there's some kind of timeout in place, it seems like it is trying to fetch something unsuccessfully. 
- No logs are sent to the console.

I expect a login page to appear.

### To Reproduce

1. git clone the repo
2. cd into Artemis root folder
3. docker-compose up
4. wait until it succeeds
5. Go to localhost:8080

### Expected behavior

When we visit the page, / should redirect to the login page.

### Screenshots

![image](https://user-images.githubusercontent.com/75616461/222794962-d60cc9c7-e806-45e3-b4c6-26d9e7267ef1.png)
![image](https://user-images.githubusercontent.com/75616461/222795825-12bc13fa-860e-4592-bded-157b093cf5c2.png)

### Which version of Artemis are you seeing the problem on?

Most recent dev branch

### What browsers are you seeing the problem on?

Chrome, Firefox

### Additional context

This error was replicated in three different machines (2 Mac Os, 1 Ubuntu 22.04), all on updated browsers. All of these were first time installs.

**Comment by ge65cer** [comment]
Did you take a peek at our setup guide? https://docs.artemis.cit.tum.de/dev/setup/
Regarding the Docker issue, @4ludwig4 can probably help you out.

**Comment by RuiRioPina** [comment]
I have looked at it indeed. One thing that I want to add is that I have run and used the web app before, using docker-compose, without any errors or hiccups.

I ran it again this morning, and it gave me these errors.

```
artemis-server_1  | 2023-03-04 10:07:47.204 ERROR 1311 --- [           main] d.t.i.w.a.s.c.b.BitbucketService         : Could not update Bitbucket user artemis_admin
artemis-server_1  | 
artemis-server_1  | org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 : [no body]
artemis-server_1  | 	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:105)
artemis-server_1  | 	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168)
artemis-server_1  | 	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)
artemis-server_1  | 	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
artemis-server_1  | 	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:825)


artemis-server_1  | 2023-03-04 10:07:47.224 ERROR 1311 --- [           main] d.t.i.w.a.aop.logging.LoggingAspect      : Exception in de.tum.in.www1.artemis.service.connectors.bitbucket.BitbucketService.updateUserDetails() with cause = 'org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 : [no body]' and exception = 'Error while updating user'
artemis-server_1  | 
artemis-server_1  | de.tum.in.www1.artemis.exception.BitbucketException: Error while updating user
artemis-server_1  | 	at de.tum.in.www1.artemis.service.connectors.bitbucket.BitbucketService.updateUserDetails(BitbucketService.java:280)
artemis-server_1  | 	at de.tum.in.www1.artemis.service.connectors.bitbucket.BitbucketService$$FastClassBySpringCGLIB$$47a7311.invoke(<generated>)
artemis-server_1  | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)


artemis-server_1  | 2023-03-04 10:07:47.226 ERROR 1311 --- [           main] d.t.i.w.a.aop.logging.LoggingAspect      : Exception in de.tum.in.www1.artemis.service.connectors.BitbucketUserManagementService.updateVcsUser() with cause = 'org.springframework.web.client.HttpClientErrorException$Unauthorized: 401 : [no body]' and exception = 'Error while updating user'
artemis-server_1  | 
artemis-server_1  | de.tum.in.www1.artemis.exception.BitbucketException: Error while updating user
artemis-server_1  | 	at de.tum.in.www1.artemis.service.connectors.bitbucket.BitbucketService.updateUserDetails(BitbucketService.java:280)
artemis-server_1  | 	at de.tum.in.www1.artemis.service.connectors.bitbucket.BitbucketService$$FastClassBySpringCGLIB$$47a7311.invoke(<generated>)


artemis-server_1  | 2023-03-04 10:07:47.228 ERROR 1311 --- [           main] d.t.i.w.a.service.user.UserService       : An error occurred after application startup when creating or updating the admin user or in the LDAP search
artemis-server_1  | 
artemis-server_1  | de.tum.in.www1.artemis.exception.BitbucketException: Error while updating user
artemis-server_1  | 	at de.tum.in.www1.artemis.service.connectors.bitbucket.BitbucketService.updateUserDetails(BitbucketService.java:280)
artemis-server_1  | 	at de.tum.in.www1.artemis.service.connectors.bitbucket.BitbucketService$$FastClassBySpringCGLIB$$47a7311.invoke(<generated>)
artemis-server_1  | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
```

**Comment by 4ludwig4** [comment]
The current docker compose setup is afaik not maintained anymore, therefore you probably get these errors.

There is a [PR](https://github.com/ls1intum/Artemis/pull/5915) which restructures the docker compose files. Documentation for the PR can be found [here](https://artemis-platform--5915.org.readthedocs.build/en/5915/dev/setup/#alternative-docker-compose-setup). Currently, this PR doesn't include a complete docker compose development suite, as most developers work locally on the code. What it does include is a very basic runnable instance of Artemis.

**Comment by RuiRioPina** [comment]
Thanks, Ludwig. I'll look into it.
I'll just do the local setup for now. :)
