### ISSUE TITLE
Not usable button in Exam View

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#6325]
### Describe the bug

Missing translation in Exam View; the button is also not clickable (leads to nowhere):
![image](https://user-images.githubusercontent.com/22198798/223274254-90f12116-3cb5-41a5-99c2-e9fed84117ed.png)

### To Reproduce

Enter a Exam Detail View for an exam

### Expected behavior

Don't show missing translation

### Which version of Artemis are you seeing the problem on?

6.1.0

### What browsers are you seeing the problem on?

Firefox

**Comment by b-fein** [comment]
cc @ge65cer

→ #6239

**Comment by krusche** [comment]
I think this button is only visible for administrators. With my non-admin account, I could not see it
