### ISSUE TITLE
`UI`: There is not anymore the Plagiarism button in the Course management view neither in the course view. 

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#6330]
### Describe the bug

There is not anymore the Plagiarism button in the Course management view neither in the course view. 

### To Reproduce

First verification
1. Go to Course management
2. Check there is no plagiarism button there

Second verification 
3. Open a course and verify there is no plagiarism button there

### Expected behavior

should be the button in both sites 

### Screenshots

Course management view: 

![image](https://user-images.githubusercontent.com/88991954/223780235-40ad6e6e-7a17-4404-8fec-7fe966a50e5c.png)

Course view: 
![image](https://user-images.githubusercontent.com/88991954/223779867-55a4ce68-05c5-4cf7-9c26-5e0f6781bdf8.png)

### Which version of Artemis are you seeing the problem on?

6.1.0

### What browsers are you seeing the problem on?

Chrome

**Comment by ge65cer** [comment]
Click on the dropdown arrow or go to the assessment dashboard. 😉
