### ISSUE TITLE
`Programming exercises`, `Assessment`: Unnecessary empty space below tutor comments

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#6367]
### Describe the bug

There is quite a bit of empty space below inline code editor comments. The actual amount of space seems to differ based on some browser/font settings per user.

### To Reproduce

1. Assess a programming exercise submission and add inline comments.

### Expected behavior

There is less empty space below inline comments.

### Screenshots

The actual amount of empty lines seems to be minimum one, but up to three depending on the system font settings. The space without line number could be reduced/removed.

![Screenshot 2023-03-21 at 15-25-36 Programming Exercises](https://user-images.githubusercontent.com/64250573/226639561-89f136a0-68db-4f83-9e0a-1f9f2cc85813.png)
![rect3148](https://user-images.githubusercontent.com/64250573/226639565-acfc5ecf-232d-4816-a075-508074966f28.png)

### Which version of Artemis are you seeing the problem on?

6.1.1

### What browsers are you seeing the problem on?

Microsoft Edge, Firefox

**Comment by pal03377** [comment]
- ACE determines the height of the `LineWidget` using `offsetHeight`: https://github.com/ajaxorg/ace/blob/eb1340ea26ddefada62d62b68c821fac4c8713aa/src/line_widgets.js#L205
- This includes the default `margin-bottom: 1em` of the `.alert` class.
- #7099 will probably fix this:
![screenshot-2023-08-27_001845](https://github.com/ls1intum/Artemis/assets/9006596/5a07cea4-460d-4144-9e47-873b95e22138)

**Comment by pal03377** [comment]
- There also is (still) an issue where when you have the instructions / the file browser open initially and then close it, the height of the feedback card is changed, but the reserved space within the editor is not.
