### ISSUE TITLE
Edit page for programming exercise shows "Java" after creating a Kotlin exercise in a Jenkins setup

### ISSUE THREAD

**Issue by frederik-kt** [ls1intum/Artemis#6392]
### Describe the bug

After creating a Kotlin exercise on test server 2 (set up with Jenkins as the continuous integration system), the edit page still shows "Java" as the chosen programming language.

### To Reproduce

1. Create a Kotlin exercise on TS2.
2. Click on "Edit".
3. Scroll down to the chosen programming language (greyed out, cannot be changed after the exercise was created)

### Expected behavior

"Kotlin" should be displayed as the chosen programming language.

### Screenshots

![Screenshot (149)](https://user-images.githubusercontent.com/64478731/228244946-af00afb0-f9f6-431b-8106-d91c18439e08.png)
![Screenshot (151)](https://user-images.githubusercontent.com/64478731/228245813-eaf59f6e-e744-443b-87ad-3a988a08d2fb.png)

### Which version of Artemis are you seeing the problem on?

6.1.2

### What browsers are you seeing the problem on?

Chrome

**Comment by b-fein** [comment]
Tested, no longer happens. Properly shown as Kotlin.
