### ISSUE TITLE
Creating an instructor assignment repository after the due date has passed results in an error.

### ISSUE THREAD

**Issue by frederik-kt** [ls1intum/Artemis#6430]
### Describe the bug

When trying to create an assignment repository for an instructor after the due date of the exercise has passed, an error is thrown.

### To Reproduce

1. Go to the Course Management and look for the exercise with the due date in the past as an instructor.
2. Click on 'Edit in editor'
3. Click on 'Create assignment repository'

### Expected behavior

Instructors should be able to create an assignment repository for an exercise even after the exercise due date has passed.

### Screenshots

![Screenshot (157)](https://user-images.githubusercontent.com/64478731/230911238-6de5498b-2da6-42b6-9ed7-8430991fc5ac.png)

### Which version of Artemis are you seeing the problem on?

6.1.3

### What browsers are you seeing the problem on?

Chrome

**Comment by ramzesmosiej** [comment]
Hi! I would be happy to work on this :)
