### ISSUE TITLE
`Programming Exercise`: Importing of Swift programming exercises is not possible

### ISSUE THREAD

**Issue by maximiliansoelch** [ls1intum/Artemis#6440]
### Describe the bug

Importing Swift programming exercise (maybe this also occurs to other languages) currently does not work as intended. When clicking on the import button, no error message is shown. However, in the web console a 500 error is shown (see screenshot below). 
The exercise is created in the database and the template repository is set up. But the creation of the solution and test repository as well as both build plans fails.

### To Reproduce

1. Try to import an exercise (I tried to import a Swift exercise)
2. Click on 'Import'
3. No success or error message is shown
4. This error is shown in the web console:
<img width="1508" alt="Screenshot 2023-04-11 at 22 16 38" src="https://user-images.githubusercontent.com/9954674/231279160-7dca6280-45c0-4240-85c1-033c09261d4b.png">
5. The exercise is created in the database and the template repository is set up
6. However, the solution and test repository as well as both build plans are not created.

### Expected behavior

The exercise should be imported successfully, all repositories and build plans should be set up and configured.

### Which version of Artemis are you seeing the problem on?

6.1.2

### What browsers are you seeing the problem on?

Safari

### Additional context

Java exercises are not affected.

**Comment by krusche** [comment]
I just tried it out for a Java programming exercise in 6.1.2 on https://artemis.in.tum.de (Atlassian setup) and the programming exercise import worked like a charm, however I also heard from another person that the import did not work once.

@maximiliansoelch is this a persistent issue with a specific configuration or does this happen always in your case?

We should probably also look into [Sentry](https://sentry.ase.in.tum.de/organizations/artemis/issues/) if we can find a corresponding issue.

**Comment by b-fein** [comment]
Also just imported a Java exercise on our system (Artemis 6.1.1, Jenkins). Maybe it is specific to Swift exercises? Then a possible cause/related issue could be #6436.

**Comment by maximiliansoelch** [comment]
Yes, apparently the issue is only related to Swift exercises (6.1.2, Atlassian setup). For them, the import fails consistently.

**Comment by maximiliansoelch** [comment]
The issue occurs when a binary file is present in the template/solution repo. It's the same error in jgit as described in #6890.
