### ISSUE TITLE
Not registered in course despite following all instructions

### ISSUE THREAD

**Issue by Kiwyexe** [ls1intum/Artemis#6467]
### Describe the bug

I (ge87ris) have been registered for the course IN0006 since wednesday, but I was not registered for the course on artemis. I accidentally registered myself for the artemis Heilbronn course instead, but it does not contain the same contents as the Garching course does.
I have looked in the registration courses, but the option to register for the Garching course doesn't exist.
Attempting to reach the course by using a link sent by a friend does not work and gives me the notification that I am not authorized for the course.

### To Reproduce

1. Go to "Course Registration".
2. The option for "IN0006 Garching" does not exist. 

### Expected behavior

Normally I should've been automatically registered for the course since I registered myself on TUMonline on wednesday, but I cannot find the course.

### Which version of Artemis are you seeing the problem on?

6.1.3

### What browsers are you seeing the problem on?

Chrome, Safari

### Additional context

It is possible that I registered too late. An email including the link to artemis was sent by Evgeny Volynsky on wednesday around 2 PM, instructing the students to register for the course on artemis before the first lecture starts. I did not receive the email because I registered in the evening.

**Comment by krusche** [comment]
This is not a bug on Artemis. The enrollment does not happen automatically. Please consult the instructor of the respective course
