### ISSUE TITLE
`Messages:` Unexpected behaviour editing a message

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#6484]
### Describe the bug

When I edit a message in a channel or a direct chat, I get at the end of the message `(edited by <author> on <date> <hour> [UTC])`

In the normal communication you don't see this when you edit a message. 

### To Reproduce

1. Go to messages 
2. Send a message 
3. Edit it 
4. Verify that the message is shown

### Expected behavior

Shouldn't show the message `(edited by <author> on <date> <hour> [UTC])`

Just should show edited or nothing

### Screenshots

![image](https://user-images.githubusercontent.com/88991954/234549684-8e8dd106-303c-4b66-9f2c-8f539600c34c.png)

### Which version of Artemis are you seeing the problem on?

6.1.4

### What browsers are you seeing the problem on?

Chrome

**Comment by krusche** [comment]
I think this is fine. Slack e.g. also shows you that someone has edited a message. However, I would suggest to show this shorter and smaller and in grey so it's not too much in the focus

**Comment by Strohgelaender** [comment]
Fixed by #6704
