### ISSUE TITLE
`Conversation`/`Notifications`: Start page shows internal server error / Course deletion does not clean up connected conversations

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#6516]
### Describe the bug

On the start page Artemis tries to load conversations for a course that does not exist. This results in an internal server error.

### To Reproduce

Not sure how to reproduce. Possibly:

1. Create some course with the conversation feature enabled.
2. Register in that course.
3. Delete the course.

### Expected behaviour

It does not try to fetch information for a course that does not exist.

### Which version of Artemis are you seeing the problem on?

6.1.5

### What browsers are you seeing the problem on?

Firefox

### Additional context

Relevant query seems to be https://github.com/ls1intum/Artemis/blob/2b2fe957297b85b979b3278dc63c5c758a593937/src/main/java/de/tum/in/www1/artemis/repository/metis/conversation/ConversationRepository.java#L52 through `ConversionResource::getAllConversionsForNotifications` and `ConversionService::findaAllConversationsForNotifications`.

So it is probably caused by course deletion not properly cleaning up connected conversions.

### Relevant log output

```shell
{
    "type":"https://www.jhipster.tech/problem/problem-with-message",
    "title":"Internal Server Error","status":500,
    "detail":"Unable to find de.tum.in.www1.artemis.domain.Course with id 4; nested exception is javax.persistence.EntityNotFoundException: Unable to find de.tum.in.www1.artemis.domain.Course with id 4",
    "path":"/api/courses/conversations-for-notifications",
    "message":"error.http.500"
}
```

Conversations exist but no course with `course_id = 4`:
| id | course\_id | creation\_date | last\_message\_date | discriminator | name | description | is\_public | topic | creator\_id | is\_archived | is\_announcement |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 2 | 4 | 2023-03-13 13:22:02.421 | null | O | null | null | false | null | 3 | false | false |
| 3 | 4 | 2023-03-13 13:30:55.940 | null | C | testchannel | null | true | null | 3 | false | false |
| 4 | 4 | 2023-03-13 13:31:36.912 | null | G | null | null | false | null | 3 | false | false |

**Comment by krusche** [comment]
We also found this bug yesterday evening and are working on a fast fix

**Comment by krusche** [comment]
I added some first implementation in #6504 because the e2e tests failed for this PR.

Apparently, the foreign key is also missing
