### ISSUE TITLE
`Manual Assessment: ` Errors while drag and drop the points.

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#6517]
### Describe the bug

In some submissions, the assessment works as expected but in others the points are not being updated when I drag and drop the points. 

### To Reproduce

1. Go to exercise dashboard of a modeling exercise
2. Drag and drop the grades 
3. Verify you get the same errors in the console and the points are not being updated. (see the screenshot)

### Expected behavior

The assessment should work as usual. 

### Screenshots

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/88991954/235619094-9b7b68a6-f99b-4a4e-8fb9-ea03ef23430e.png">

### Which version of Artemis are you seeing the problem on?

6.1.5

### What browsers are you seeing the problem on?

Chrome

**Comment by Santia-go** [comment]
https://user-images.githubusercontent.com/88991954/236146815-bc947d7b-d888-4597-a39a-c102af1a2d02.mov

**Comment by LordMuetze** [comment]
I don't have this problem anymore, works like a charm :) 
@Santia-go if it's also working for you, you might consider closing this issue.
