### ISSUE TITLE
Jenkins and Bamboo do not assign results to correct submissions

### ISSUE THREAD

**Issue by frederik-kt** [ls1intum/Artemis#6524]
### Describe the bug

When submitting to programming exercise repositories multiple times in rapid succession, the CI systems do not handle the results correctly. For Jenkins, sometimes all results are assigned to the latest submission (see screenshot 1 below), sometimes there is not even one result per submission returned (see screenshot 2 below). Similarly for Bamboo (see screenshot 3 below).

### To Reproduce

1. Use a Jenkins setup (e.g. TS2) or a Bamboo setup (e.g. TS1)
2. Go to the online editor for a programming exercise (e.g. go to "Edit in editor" and change the template repository there)
3. Submit multiple times in rapid succession, adding one letter to the source code in between submissions.
4. Go to the exercise overview page -> "Show Template Submissions"

### Expected behavior

It is expected, that the CI systems do not run a build for every submission. Jenkins, e.g. uses "Coalescing" to save on resources.
In that case, we should however only send one build result back to Artemis.
There seems to be no way to tell the CI system to run a build for a specific (older) commit.
For local CI, we were able to implement this by handing the commit hash to the CI system which then checks out that commit hash explicitly, so the problem does not exist for local CI.

### Screenshots

![Screenshot (171)](https://user-images.githubusercontent.com/64478731/235897751-c5a839f8-f599-4a0e-8861-f520ce57ee99.png)
Screenshot 1

![Screenshot (172)](https://user-images.githubusercontent.com/64478731/235897794-845d5413-db2e-4eb5-be50-57a50cb0f51d.png)
Screenshot 2

![Screenshot (170)](https://user-images.githubusercontent.com/64478731/235893703-bbf06a77-b945-4da9-9175-1c67ddd72c03.png)
Screenshot 3

### Which version of Artemis are you seeing the problem on?

6.1.6

### What browsers are you seeing the problem on?

Chrome

**Comment by dearjasmina** [comment]
One way to deal with burst commits is to increase the quiet period in jenkins. 
Disadvantage: By doing this, the students' experience will be worse as they would have to wait more to get the result.
Advantage: https://www.jenkins.io/blog/2010/08/11/quiet-period-feature/

After discussing with Stephan, the disadvantage wins in this case.

**Comment by krusche** [comment]
CI systems are not designed to handle such cases in a way that would be ideal for Artemis.


If there are many pushes in a short time, they typically queue the builds. When a queued build for the 3rd commit will start with the clone operation, the commits 4 and 5 are already pushed in the repo and therefore will be part of the 3rd build.

One way to deal with this in Artemis would be to checkout the commit assigned to a submission during the build. This is done by the local CI system.
