### ISSUE TITLE
`Plagiarism cases`: The cases in the instructor plagiarism view are not being updated.

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#6529]
### Describe the bug

When a tutor `confirm` a case, this case is shown in the `course management>course> Plagiarism cases` as a list. 
However, when a tutor deny the case, the list is not updated (remove the previous case). 

### To Reproduce

1. Run the plagiarism check of one exercise and confirm some cases. 
2. As an instructor check the list of cases 
3. As tutor, deny the previous confirmed cases 
4. Check if the list is updated. 
5. check if the columns are sorted correctly (see the screenshot)

### Expected behavior

Confirm or deny some cases, should update the list that the instructor have. 

### Screenshots

<img width="1905" alt="image" src="https://user-images.githubusercontent.com/88991954/236168843-aa12918b-36c8-463f-a7f9-13b70c17eb43.png">

### Which version of Artemis are you seeing the problem on?

6.1.5

### What browsers are you seeing the problem on?

Chrome

**Comment by jakubriegel** [comment]
I'll work on that

**Comment by jakubriegel** [comment]
@Santia-go I'm not able to reproduce that.

Steps I did on TS2:
1. Run plagiarism checks.
2. As an editor (tutor didn't have access to plagiarism classes) I confirmed a case
3. As an instructor I checked the lists: the case was there
4. As an editor I denied that case.
5. As an instructor I checked the lists: the case was not there

Could you verify that this issue still occurs?

**Comment by jakubriegel** [comment]
Most likely the cause here is the same as in #6528

**Comment by jakubriegel** [comment]
Note from @krusche:

> Sounds good, it might be possible to add a database unique constraint for a combination of objects. It might also be possible to add a loading state to the respective button in the client (if not yet done) to avoid that users accidentally click multiple times. I don’t think that multiple users have worked on this in parallel (this is quite unlikely as there is typically only one instructor working on this)

**Comment by jakubriegel** [comment]
After discussion with @MarkusPaulsen we agreed to:
- apply the quick fix on the db
- implement lock/atomic on approving/denying plagiarism submission and creation/deletion of plagiarism case

**Comment by krusche** [comment]
Can you explain in more detail what you plan? In an environment with multiple servers, a lock can be difficult to implement. We should be careful here

**Comment by jakubriegel** [comment]
Fo the quick fix:
- @bassner will remove both cases from the db
- then I will click `Deny` on the client to fix the state (changing the status wil end with exception, but all will be fine since no the status will change and no cases will be present)

**Comment by jakubriegel** [comment]
@krusche I will let you know

**Comment by jakubriegel** [comment]
For the concrete solution:
- `@Transactional` did the trick
- PR: #6613 
- In the PR description there is list of steps to reproduce the issue and test the fix

**Comment by jakubriegel** [comment]
Second PR with the second frontend only variant of the solution: #6614 

Those can be merge together or we can stick to one of them. Waiting for decision of @krusche and @MarkusPaulsen

**Comment by jakubriegel** [comment]
We are going ahead with client side solution only
