### ISSUE TITLE
Images not exported for Programming Exercises

### ISSUE THREAD

**Issue by chrisknedl** [ls1intum/Artemis#6535]
### Describe the bug

When exporting a programming exercise, the images are not exported. If the exercise is then imported on the same system it has been exported from, the images are there, because the image URLs are the same. For a different system, the images can't be displayed, as they are not present on that system.

### To Reproduce

1. Go to the details page of a programming exercise with images in its description
2. Click on `Download Exercise` 
3. Import exercise on another system (e.g. local setup) by navigating to the exercise section of a course and clicking `Import Programming Exercise`
4. There should be no images in the description of the imported exercise

### Expected behavior

The export should also include images, so that they can be automatically transferred between systems.

### Which version of Artemis are you seeing the problem on?

6.1.5

### What browsers are you seeing the problem on?

Chrome

**Comment by krusche** [comment]
@tobias-lippert can you please have a look?

**Comment by tobias-lippert** [comment]
gonna look into it
