### ISSUE TITLE
[Programming Exercise] Not able to set weight for test cases in Grading view

### ISSUE THREAD

**Issue by LordMuetze** [ls1intum/Artemis#6560]
### Describe the bug

As mentioned in the title: I am not able to set weights for different test cases anymore. This used to work and for my Exercises it's a very important feature.

### To Reproduce

1. Create new Java programming exercise with Maven
2. From the details page of the exercise go to 'Grading'
3. If not already selected go to the tab 'Test cases'
4. Here you see the problem (or more precisely: you do not see the expected behavior)

### Expected behavior

I expect to see a list of all test cases with input boxes for normal weight, bonus weight etc. and some diagrams to visualize the content of the input boxes.
Instead I see jsut empty space (Screenshot below)

### Screenshots

![image](https://github.com/ls1intum/Artemis/assets/30774791/1791e582-5bea-47c9-987a-cb468ca5255e)

### Which version of Artemis are you seeing the problem on?

6.1.6

### What browsers are you seeing the problem on?

Chrome, Firefox

**Comment by krusche** [comment]
We already fixed this issue and will release a new version until tomorrow morning
