### ISSUE TITLE
`Plagiarism`: Confirm button should ask for confirmation

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#6592]
### Is your feature request related to a problem?

The plagiarism view shows the two buttons ‘Confirm’ and ‘Deny‘ to the instructor. Neither button asks for confirmation when pressed.

### Describe the solution you'd like

Since plagiarism is quite a severe accusation, especially the ‘Confirm’ button should ask for explicit confirmation first.

This avoids sending out the notification directly to students when pressing the button accidentally.

### Describe alternatives you've considered

-/-

**Comment by krusche** [comment]
At this point no notification is sent. This happens on a different page on which you can customize the actual message sent to the respective student. You can also easily revert the decision.

I don't think we need a confirmation here

**Comment by krusche** [comment]
The main reason is that students could be involved in multiple plagiarism comparisons. You might then confirm multiple times for the same student. However, on the plagiarism cases page, you would then send one notification to the student, which would be the desired behavior in my opinion.

**Comment by b-fein** [comment]
In that case I agree that no confirmation is necessary.
