### ISSUE TITLE
Dont show "To use ssh, you need to add an ssh-key to your account here." every time

### ISSUE THREAD

**Issue by MariusAlbrecht** [ls1intum/Artemis#6650]
### Is your feature request related to a problem?

When using ssh to clone the repositories artemis always shows a warning:
![image](https://github.com/ls1intum/Artemis/assets/64852250/4a80e8a9-4350-4dea-95e0-5ec449be0562) 
I am very aware of how ssh works and things work perfectly fine for me so this warning is both unnecessary and annoying

### Describe the solution you'd like

A way to disable this warning. Could be 
- a "x" + popup with "dont show again" option 
- a toggle in the settings
- an automatic disable after the warning has been shown a few times. This is probably not a good idea overall, though it'd work for me

### Describe alternatives you've considered

Locally editing the css of the site to just not render the warning. Easily possible but
- not very accessible for most people
- Requires some wonky hacking or an extension to the browser
- relies on the fact that internal css selectors dont change which could mean it'd have to be redone regularly

**Comment by krusche** [comment]
We could allow users to click on a X and store this information in the local browser storage. This would be an easy implementation and would only require client side changes. Small disadvantage: users would need to do it again if they switch the browser, however, I think this should be ok. In case we don't do it yet, the client should also remember whether SSH or HTTPS was chosen by the user so that users don't need to switch every time

**Comment by MariusAlbrecht** [comment]
Perfectly fine solution for me! Clicking x once after switching browsers is absolutely no problem imo.
However I'd like to add, that most useres would _probably_ (just an assumption  I'd certainly fo it) click away ghe warning either way. Just out of "instinct" even though they haven't made sure it doesn't apply to them (and then potentially wouldn't see the warning of they could actually use it)

**Comment by krusche** [comment]
But what would then be a good solution to circumvent such behavior?

**Comment by MariusAlbrecht** [comment]
maybe something like this?
![JGfW0.png](https://github.com/ls1intum/Artemis/assets/64852250/6eea99bd-6506-49d1-97ed-a875522c062e)
https://ux.stackexchange.com/a/89179

**Comment by Friedjof** [comment]
Hi, I miss this function in the new version of Artmenis. Is there currently an issue with the implementation of SSH key authorisation? Or is this in planning?

**Comment by Strohgelaender** [comment]
For LocalVC, the warning now disapears if there is a SSH key available. Therefore I'm closing this issue now.
