### ISSUE TITLE
Course Registration: Students don't see available courses in registration overview and therefore cannot enrol/register

### ISSUE THREAD

**Issue by andreasdomanowski** [ls1intum/Artemis#6668]
### Describe the bug

In Artemis versions 6.2.0 and 6.2.1 (_haven't tested < 6.2.0 yet, although no students complained until updating to 6.2.0_) students don't see the available courses in the course registration (_/courses/register_) and therefore cannot register and participate in the course.

Student course registration is enabled in the course configuration. Start and end date of the courses are either not set or specified to enable student registration at the current point in time.

### To Reproduce

1. Set up a new course and enable student registration
2. Try to register as a student

### Expected behavior

Course registration should be possible

### Which version of Artemis are you seeing the problem on?

6.2.0 and 6.2.1

### What browsers are you seeing the problem on?

Firefox

**Comment by Strohgelaender** [comment]
On my local instance the course registration worked, I can also see available courses on the TUM production instance (6.2.2)

Can you check the `course-enrollment.allowed-username-pattern` configuration property? This options allows to limit the users wh can potentially register to courses. A studentent cannot self-register if the username does not match this pattern. Maybe the current server configuration has a wrong value here?

**Comment by andreasdomanowski** [comment]
Thank you very much, @Strohgelaender. This was indeed the issue - we only set the value for `course-enrollment.allowed-username-pattern`.

**Comment by martinmo** [comment]
> Thank you very much, @Strohgelaender. This was indeed the issue - we only set the value for `course-enrollment.allowed-username-pattern`.

That's a typo, Andreas meant to say that we used the old key `course-registration.allowed-username-pattern`. It seems like all this was renamed in 6.2.0 via #6565, but without mentioning it in the release notes :(
