### ISSUE TITLE
Auto-submission: warning when attempting to submit exercise after deadline expiration

### ISSUE THREAD

**Issue by Extender** [ls1intum/Artemis#670]
Hello,
could you please add a warning next to the save/submit buttons that is displayed after the deadline has expired (saving/submitting will make you lose the possibility of getting bonus points)? There is a "deadline missed" message, but it is not really clear that pressing the buttons will make you lose points.
Thank you!

**Comment by jpbernius** [comment]
We updated the submission procedure for text (#976), modelling (#977) and file upload (#1017) exercises. Thereby we changed the behavior of the submit button.

Based on this progress, I am closing this issue.
