### ISSUE TITLE
copy ssh url is missing ':' divider

### ISSUE THREAD

**Issue by benborga** [ls1intum/Artemis#6724]
### Describe the bug

the url provided for ssh dosn't work

### To Reproduce

1. Go to 'Any Programming Exercise'
2. Click on 'Clone Repository'
3. Change from HTTPS to SSH
4. Error: the url is missing a : between domain and repository

### Expected behavior

git@domain-example:path/to/repository.git

### Which version of Artemis are you seeing the problem on?

6.2..0

### What browsers are you seeing the problem on?

Firefox

**Comment by JohannesStoehr** [comment]
I compared the clone url of Artemis and Bitbucket and apart from the capitalization they are identical for me:
Bitbucket: ssh://git@bitbucket.ase.in.tum.de:7999/gad23e06/gad23e06-exercise.git
Artemis: ssh://git@bitbucket.ase.in.tum.de:7999/GAD23E06/gad23e06-exercise.git

So the URL in Artemis looks fine to me.

**Comment by b-fein** [comment]
That may be a configuration error in our instance at Uni Passau, then. I’ll check.

We don’t have a specific port as part of the URL, that’s why it might look/work different and the colon needs to be added.

**Comment by b-fein** [comment]
Fixed in our instance.
