### ISSUE TITLE
Homepage not loading

### ISSUE THREAD

**Issue by ch-schindi** [ls1intum/Artemis#6728]
### Describe the bug

The homepage is not working and you cannot sign in

### To Reproduce

1. Go to artemis.ase.in.tum.de
2. log out
3. try to log back in -> does not work

### Expected behavior

should work

### Screenshots

<img width="960" alt="image" src="https://github.com/ls1intum/Artemis/assets/131975063/a8ddfdd2-1f63-4e89-9b66-66f158fb8e68">

### Which version of Artemis are you seeing the problem on?

6.3.0

### What browsers are you seeing the problem on?

Microsoft Edge, Other (specify in "Additional context")

### Additional context

Opera

**Comment by krusche** [comment]
There was a config error in the TUM Artemis system which we have resolved. Sorry for the inconvenience! It should work again. Let us know if you still experience issues.
