### ISSUE TITLE
Improved uml modelling editor

### ISSUE THREAD

**Issue by theblobinthesky** [ls1intum/Artemis#6737]
### Is your feature request related to a problem?

We've been using the uml modelling tools internal to Artemis at uni in passau, e.g. the apollon editor to complete homework assignments. The editor obviously has many flaws that could be addressed, for example the lack of zoom in/out, no rectangular selections and Actor stickfigures in UseCase Diagrams don't respond to clicks in their entire bounding box. And the list goes on.

### Describe the solution you'd like

I'd like to use a thought through editor that supports the most common kinds of uml diagrams well and is reasonably usable.
Is there an ongoing effort to get the editor to be good and if there is none: Can people like me contribute by coding up a new editor from scratch that actually works well and integrates with Artemis? And will that pull-request be accepted?

**Comment by krusche** [comment]
We keep Apollon intentionally simple to use to avoid a completely crowded experience as in other UML editors, however zoom options and rectangular selection are definitely features we want to implement in the future. Additional usability improvements are welcome as well.

There is a separate Apollon repository and I would suggest that you create concrete issues with improvement suggestions there and consider contributing a pull request there. Such contributions are highly welcome

However, please keep in mind that implementing such features in a good quality can be quite challenging. So don't underestimate the effort.

**Comment by theblobinthesky** [comment]
Thank you for the quick answer.

**Comment by b-fein** [comment]
Relevant issues have been/will be created in https://github.com/ls1intum/Apollon.
Therefore closing this issue here.
