### ISSUE TITLE
seeing "translation-not-found"

### ISSUE THREAD

**Issue by Anatoly03** [ls1intum/Artemis#6766]
### Describe the bug

seeing placeholder text:

```
translation-not-found[artemisApp.courseOverview.exerciseList.details.upcomingDueDate]
```

### To Reproduce

1. Go to 'https://artemis.in.tum.de/courses/256/exercises'
2. Scroll down to due list on the side bar 
3. See error

### Expected behavior

don't see placeholder text

### Screenshots

<img width="472" alt="Screenshot 2023-06-25 at 20 37 40" src="https://github.com/ls1intum/Artemis/assets/44678124/69e015ec-406a-4536-a8e1-918d735328c0">

### Which version of Artemis are you seeing the problem on?

university latest

### What browsers are you seeing the problem on?

Chrome

### Additional context

There is no further context.

**Comment by krusche** [comment]
Thanks for reporting, we will fix it asap
