### ISSUE TITLE
`Modelling`, `Assessment`: Feedback for model elements not possible in use case diagrams

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#6788]
### Describe the bug

For UML use case diagrams the assessments on model elements are not saved.

### To Reproduce

Requirements:
- Use case diagram modelling exercise, at least one submission with elements in the diagram

1. As tutor/instructor go to the assessment of the submission.
2. Add a feedback element to an element in the diagram.
   - The save button stays disabled.
3. Add a new general feedback below the diagram.
   - The save button becomes active.
4. Save the assessment.
5. Issue: the model element feedbacks are gone.

### Expected behavior

The model element feedback items are still present and saved.

### Which version of Artemis are you seeing the problem on?

6.3.1

### What browsers are you seeing the problem on?

Firefox

**Comment by krusche** [comment]
I think this issue was fixed with #6893 and with recent updates in Apollon.
If the error still occurs, please reopen the issue
