### ISSUE TITLE
UseCase model will not connect Actions

### ISSUE THREAD

**Issue by DeRealMorgan** [ls1intum/Artemis#681]
### Describe the bug

I just tried to do the in class use case diagram exercise. When trying to connect actions with lines the line just did not get connected. 

You drag the line from one action to another action (the action gets highlighted in a blue rectangle) if you release the line then the line was not connected as expected (it worked maybe 1/10 times). 

Thats 4 lost points sadly.

### Environment

<details><pre>
 - Browser: Chrome
</pre></details>

**Comment by krusche** [comment]
This is an issue that should be opened in https://github.com/ls1intum/Apollon
