### ISSUE TITLE
Text search in online code editor and markdown editor

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#6811]
### Is your feature request related to a problem?

I would like to be able to search in the online code editor. The usual browser shortcut of Ctrl+F does not work in that frame.

### Describe the solution you'd like

The ACE editor has a built-in feature for search which can be easily enabled.

In #6665 the implementation was already done. The only remaining question is how the search box can be styled properly in both light and dark mode.

Therefore, only (S)CSS knowledge needed to fully implement this.

**Comment by BaumiCoder** [comment]
Resolved with Pull Request #8130 as @b-fein commented [here](https://github.com/ls1intum/Artemis/pull/8130#pullrequestreview-1973503139):
> Also nice to see that the new editor will have a search/search-and-replace functionality (https://github.com/ls1intum/Artemis/issues/6811) 🎉.
