### ISSUE TITLE
Background for Drag-And-Drop-Questions is not saved correctly

### ISSUE THREAD

**Issue by FloezeTv** [ls1intum/Artemis#6825]
### Describe the bug

When I create a Drag-And-Drop Question in a Quiz, I can select a background for the question and insert positions for Drag Items.
During the creation of the exercise, the background is shown, except in the preview.

However, when saving the exercise, the background can not be retrieved form the server, therefore leading to an alt-text being displayed.

The image is uploaded to the server in the request for the exercise creation, but the image link in the returned response always returns HTTP `200 - OK` with 0 bytes of data.

### To Reproduce

1. Create a new Quiz exercise in any course or exam (I used the [TUM instance](https://artemis.ase.in.tum.de/))
2. Enter a name for the Quiz
3. Click on `Add Drag-And-Drop Question`
4. Enter a title for the question
5. Click on `Select Background` and select an image to be used as background
7. Create a new drop-zone on the background-image
6. Click on `Add Text Drag Item`
8. Drag the text drag item onto the drop-zone
9. Click on `Save` to save the exercise
10. Notice the image is not displayed here (and when taking the quiz)

Alternatively, one can click on `Preview` in Step 9 to see the broken preview.

### Expected behavior

I expected to correctly see my uploaded image when taking the Quiz.

##### The image is displayed during creation of the exercise:
![Image is displayed during creation](https://github.com/ls1intum/Artemis/assets/32437469/eeb4b6f5-6dac-4c02-a01c-5a9de7257f56)

##### The preview is unable to load the image during creation:
![Broken preview during exercise creation](https://github.com/ls1intum/Artemis/assets/32437469/f9883113-6b80-48a6-a8e5-1316a76b54ad)

##### After saving the exercise, the image is gone:
![Image is gone after saving](https://github.com/ls1intum/Artemis/assets/32437469/00ae121e-7399-4fda-8cd6-7e543fb70449)

##### When taking the quiz (here using the preview mode), an alt-text is shown instead of the image:
![Alt-text instead of image when taking quiz](https://github.com/ls1intum/Artemis/assets/32437469/395670c9-4933-4d7e-a247-5ad366702d95)

##### The image is sent to the server when creating the exercise:
![Request to the server](https://github.com/ls1intum/Artemis/assets/32437469/eb1a7e4f-38fa-40d0-9b98-dada35a5ebb1)

##### The server responds with a [link](https://artemis.ase.in.tum.de/api/files/drag-and-drop/backgrounds/5790/DragAndDropBackground_2023-07-05T10-51-38-776_8bc31f89.png) to the image:
![Response of the server](https://github.com/ls1intum/Artemis/assets/32437469/8b57dacc-bea7-4262-8fcf-b5d1e81a9298)

##### When accessing the returned link, the server responds with `200 - OK` but returns 0 byte:
![Response 200 but no data returned](https://github.com/ls1intum/Artemis/assets/32437469/67015a72-0d43-4193-aaab-09c6c404e9c0)

### Which version of Artemis are you seeing the problem on?

6.3.2

### What browsers are you seeing the problem on?

Firefox

### Additional context

Images uploaded in the question description load fine.

**Comment by michael-schwarz** [comment]
Don't mean to be pushy since we just opened the issue, but just so you're aware: We want to use this feature for an exam which we'll conduct on Artemis on 07/31, and want to give the students the opportunity to test it before the actual date. We'd highly appreciate it if this could be fixed and ideally land on the TUM instance within the next week or so - or if that is not possible a timeline of when you'll get around to it.

Thank you (from one floor up ;))

**Comment by krusche** [comment]
Thanks for reporting the issue, we will fix it asap

**Comment by krusche** [comment]
@FloezeTv how large is your background image?

**Comment by FloezeTv** [comment]
The test-image I used for writing this issue (as to not leak any exam questions) was the following `512x512` png, which takes up 8.2 KB:
![512x512](https://github.com/ls1intum/Artemis/assets/32437469/29495b03-75eb-43e2-8bbb-dda7eeb28b29)

I have just tried to create a Drag-And-Drop quiz using this 82 Byte `32x32` png, which also does not load:
![32x32](https://github.com/ls1intum/Artemis/assets/32437469/2c049abc-20e9-44da-a70e-6d77c907b67f)
