### ISSUE TITLE
`Exam mode`: The working time in minutes is not calculated automatically in Test mode

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#6870]
### Describe the bug

When you create or import an exam, the working time in minutes is not calculated automatically in Test mode. 

### To Reproduce

1. Go to any course
2. Click on `exam` 
3. Click on `create` or `import` exam 
4. Select `Test exam` in the mode section. 
5. Adaprt the dates and verify that the `working time remains in zero`. See the screencast.  

### Expected behavior

The working time should be calculated just like in the normal `Exam` mode. 

### Screenshots

https://github.com/ls1intum/Artemis/assets/88991954/b0bf926e-343a-4132-851a-8951c0df1d92

### Which version of Artemis are you seeing the problem on?

6.3.3

### What browsers are you seeing the problem on?

Chrome

**Comment by krusche** [comment]
This is intended. In the test exam students can start the exam in a window (eg 1 week) and instructors need to specify the working time (eg 90min)
