### ISSUE TITLE
Artemis internal timer 

### ISSUE THREAD

**Issue by DaliGaoudi** [ls1intum/Artemis#6883]
### Describe the bug

My Artemis internal clock is always one hour ahead of the real clock, exercises expire 1 hour before they should, The problem seems to be happening only to me.

### To Reproduce

i don't know how

### Expected behavior

clock should be like the real world clock 

### Which version of Artemis are you seeing the problem on?

6.3.3

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

i'm using vivaldi as a browser, i was using opera GX before and i had the same problem

**Comment by Strohgelaender** [comment]
Can you explain a bit more how you are seeing this issue? I assume you are talking about the due date of exercises, right?

Is the problem that Artemis shows that the working time is already over, even though you and other students can still submitt solutions (in case of programming exercises, does that mean that you can stil push something?)

In which time zone are you living? What is your compters clock set to?

**Comment by DaliGaoudi** [comment]
yes i am talking about the due dates of exercises and i am afraid that during the exam i won't have the same time as everyone.

The problem is exactly what you said except that i can't push anything anymore, it says that the date is due.

i live in germany and my computer's clock is  automatically set to London timezone (UTC+00:00)
