### ISSUE TITLE
Practicing quizzes reduces score in statsistic

### ISSUE THREAD

**Issue by AlexanderTreml** [ls1intum/Artemis#690]
### Describe the bug

When practicing a quiz, the percentage of the total score in the statistics view is reduced.

#### To Reproduce

1. Go to 'Exercises'
2. Enter any quiz in practice mode
3. Complete the practice
4. Navigate to statistics
5. The percentage of points has reduced

#### Expected behavior
Practicing quizzes should not change this percentage

### Environment

<details><pre>
 - OS: Windows 10
 - Browser: Edge
 - Version: 42.17134.1.0
</pre></details>

#### Additional context
The percentage in the project overview does not change. Only the one in the statistics view is affected.

**Comment by krusche** [comment]
@maximilianmeier could you please have a look?

**Comment by maximilianmeier** [comment]
@krusche i can not confirm the behaviour. I tried to reproduce it on the test server

@AlexanderTreml could you check if the statistics for the specific exercise has changed?

**Comment by blub-munich** [comment]
I (Jonathan Vogel) have the same issue after practicing quiz 4b. The points for the quiz are sometimes shown in the statistics and sometimes they are not. The quiz 4b page itself says constantly that i have no graded results and only shows the practice results.

![error2](https://user-images.githubusercontent.com/51967227/62384631-28077080-b553-11e9-840e-ec508c668142.JPG)
![error1](https://user-images.githubusercontent.com/51967227/62384632-28a00700-b553-11e9-887b-431e94bbc35a.JPG)

**Comment by blub-munich** [comment]
Same for quiz 7. I for sure won't practice any more quizzes. Statistics now down to 87.3%
![sicherheitshalber3](https://user-images.githubusercontent.com/51967227/62386542-82ef9680-b558-11e9-9324-89f85f2cb88a.JPG)
![error6](https://user-images.githubusercontent.com/51967227/62386575-8d119500-b558-11e9-95a2-aca7cdf7eaa2.JPG)
![error5](https://user-images.githubusercontent.com/51967227/62386577-8d119500-b558-11e9-9d53-98a6ba15e170.JPG)

**Comment by krusche** [comment]
This has been fixed some time ago
