### ISSUE TITLE
Unable to practice programming exercise

### ISSUE THREAD

**Issue by ole-ve** [ls1intum/Artemis#6943]
### Describe the bug

I would like to participate in [this programming exercise](https://artemis.ase.in.tum.de/courses/258/exercises/10205). I did not participate yet, thus, I would start the exercise in "Practice mode". However, when clicking on "Practice", I get an internal server error (500 - "message": "error.http.500") and cannot start the exercise.

The failing endpoint:

POST /api/exercises/10205/participations/practice?useGradedParticipation=false

### To Reproduce

1. Open [the exercise](https://artemis.ase.in.tum.de/courses/258/exercises/10205)
2. Click "Practice" and confirm

### Expected behavior

The exercise should be started.

### Which version of Artemis are you seeing the problem on?

6.3.4

### What browsers are you seeing the problem on?

Chrome

**Comment by Strohgelaender** [comment]
Seems like the base build plan is missing for this exercise. Please contact your instructor.
