### ISSUE TITLE
Automatically generated channel name can contain invalid characters

### ISSUE THREAD

**Issue by tobias-lippert** [ls1intum/Artemis#6957]
### Describe the bug

I experienced it while creating an exam but should be reproducible with lectures and exercises as well.
Give the entity a name containing periods/hashtags any other invalid character. 
See that the channel name contains the invalid character as well.
Try to save the entity. 
Saving fails because of an invalid channel name.

### To Reproduce

see above.

### Expected behavior

invalid characters should be replaced with - 

### Which version of Artemis are you seeing the problem on?

6.3.5

### What browsers are you seeing the problem on?

Chrome

**Comment by pal03377** [comment]
Additional info: When you fail to create an exam because of this bug, a "ghost exam" is still created, which can confuse.

![screenshot-2023-07-23_001662](https://github.com/ls1intum/Artemis/assets/9006596/cf42dddf-e921-48b6-9ece-85e138ce0032)

**Comment by Strohgelaender** [comment]
The automatic name can also be too long.

**Comment by krusche** [comment]
@lennart-keller could you have a look into this issue? Should be easy to fix. The channel name should never break the creation of exercises / lectures / exams. Ideally, the client validates the correctness already and the server does not create automatic names which could be wrong
