### ISSUE TITLE
```Assessment```: < and > incorrectly interpreted in tutor comments

### ISSUE THREAD

**Issue by chrisknedl** [ls1intum/Artemis#6965]
### Describe the bug

When using the `<` and `>` symbols in the tutor feedback comments, they aren't shown properly. Only using < with nothing coming after it, or using <> with nothing in between is displayed correctly. However, when there is text after the opening bracket <, that whole piece of text (including the bracket) is gone, until there is a closing bracket >, which is also not displayed after saving the comment.

Possible explanation:
The brackets might be interpreted as html tags.

### To Reproduce

1. Create a programming exercise with manual feedback enabled.
2. Create an assignment for this exercise and wait till the submission deadline has passed.
3. Create a tutor comment and test out the cases outlined above.
4. After saving, you should be able to see the error (i.e. not see some of the text).

### Expected behavior

Expected behavior would be WYSIWYG, so entering a < or > in any combination should display exactly that after saving.

### Screenshots

Error can be observed in the middle comment.
![Bildschirmfoto 2023-07-23 um 17 19 29](https://github.com/ls1intum/Artemis/assets/53149143/d41a87fc-dee3-4eb6-b157-075978e92851)
![Bildschirmfoto 2023-07-23 um 17 19 37](https://github.com/ls1intum/Artemis/assets/53149143/6a6fbeee-3ff6-46fb-b8ec-7b5f55f6ad03)

### Which version of Artemis are you seeing the problem on?

6.3.5

### What browsers are you seeing the problem on?

Chrome

**Comment by b-fein** [comment]
Additional context: It is only wrong in the inline feedback, in the feedback details dialogue the full comment is shown.
![image](https://github.com/ls1intum/Artemis/assets/64250573/851a19d4-6e6a-40d2-a6f9-f99355341f98)
![image](https://github.com/ls1intum/Artemis/assets/64250573/46a80d8f-0544-42ed-8439-ebbecf916eb4)
