### ISSUE TITLE
Plagiarism check for Java exercises shouldn't fill logs with parser stacktraces in case of syntax errors

### ISSUE THREAD

**Issue by martinmo** [ls1intum/Artemis#7013]
### Is your feature request related to a problem?

When performing a plagiarism check and some of the checked submissions contain syntax errors, the server logs will contain several huge stacktraces. As an admin, I then think there is an unhandled error or a server misconfiguration. However, the plagiarism checks proceeds successfully and ignores the corresponding submission (as expected).

### Describe the solution you'd like

The full parser stack trace should only be shown at `DEBUG` level. Otherwise, the logs should include an `INFO` message that submission X was removed from the check because of a syntax error.

**Comment by krusche** [comment]
@jakubriegel could you please take a look in this issue and try to fix it?

**Comment by jakubriegel** [comment]
I'll handle this

@b-fein are you able to post here example of such log?

**Comment by martinmo** [comment]
I can also provide an excerpt:

[artemis_log_excerpt.log](https://github.com/ls1intum/Artemis/files/12333473/artemis_log_excerpt.log)

**Comment by jakubriegel** [comment]
This log comes directly for jplag: https://github.com/jplag/JPlag/blob/main/core/src/main/java/de/jplag/Submission.java#L251
 I'll check if it is possible to change this class' logger to `error` since all other logs here are `error`, so that this log will be silenced and others will remain active

**Comment by jakubriegel** [comment]
@b-fein please check #7078
