### ISSUE TITLE
Drag & Drop: answer menu too small

### ISSUE THREAD

**Issue by Friendly-Banana** [ls1intum/Artemis#7020]
### Describe the bug

The possible answers list for Drag & Drop exercises does not span the entire height of the screen. Instead there is a scrollbar. The exercise itself is bigger than the screen.

### To Reproduce

1. Go to a Drag & Drop exercise with a big answers list
2. see the answers list

### Expected behavior

The answers field uses the entire height of the screen (or at least most of it) and only if that is not enough uses a scrollbar.

### Which version of Artemis are you seeing the problem on?

6.3.8

### What browsers are you seeing the problem on?

Firefox

### Additional context

See e.g. FPV exam, https://artemis.in.tum.de/courses/271, Exercise 6
encountered while in exam/editable mode

**Comment by krusche** [comment]
Can you provide a screenshot what you mean?

**Comment by Friendly-Banana** [comment]
@michael-schwarz could you please also provide the fpv exercise for this issue?

**Comment by just-max** [comment]
@Friendly-Banana could you provide a screenshot based on the exercise I linked in https://github.com/ls1intum/Artemis/issues/7019#issuecomment-1679613337?
