### ISSUE TITLE
`Grading`: Duplicate name for grade steps in default Grading Key

### ISSUE THREAD

**Issue by DominikRemo** [ls1intum/Artemis#7023]
### Describe the bug

When creating a default grading key, there are two grade steps with name "1.0"

The default grading key cannot be save and an error is displayed:
`All grade steps must have unique names!`

### To Reproduce

1. Go to Course Management > _Your Course_ > Assessment > Grading Key
2. Generate a default grading key
3. Note how the default grading key cannot be saved

### Expected behavior

There shouldn't be duplicated names for the grade steps in a default grading key.
The user should be able to save the default grading key.

### Screenshots

<img width="1200" alt="Bildschirmfoto 2023-08-01 um 22 18 59" src="https://github.com/ls1intum/Artemis/assets/47261058/a3797825-9f45-4f2e-b435-d23985dcb9e3">

### Which version of Artemis are you seeing the problem on?

6.3.8

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge, Firefox

**Comment by krusche** [comment]
Can we remove the unique constraint? Before it used to have 1.0+ but this cannot be parsed into a number and would fail at a later point

**Comment by DominikRemo** [comment]
Removing the unique constraint might not be the right approach.

I would have suggested to remove the last grade step like this:
<img width="1200" alt="Bildschirmfoto 2023-08-02 um 10 58 12" src="https://github.com/ls1intum/Artemis/assets/47261058/6885f6f4-2650-40c3-a172-3d2b157d15a3">

The grading key would then also be more consistent with the default grading key that is created in "Detailed" mode:
<img width="1200" alt="Bildschirmfoto 2023-08-02 um 10 58 24" src="https://github.com/ls1intum/Artemis/assets/47261058/5984b7b1-d729-4e03-9a3d-fc3d1664873f">

There is also another inconsistency between "detailed" and "interval" mode: When saving the default grading key from "Detailed" mode and switching back to "interval", the bounds of the grade step before the sticky grade step is different { [90-95) instead of [90-95] }
<img width="600" alt="Bildschirmfoto 2023-08-02 um 11 01 03" src="https://github.com/ls1intum/Artemis/assets/47261058/f45710a8-987b-4fa4-be3f-223231c79861">

**Comment by krusche** [comment]
would also be a good solution for me 👍 
could you please change this and fix the inconsistency? Thanks

**Comment by DominikRemo** [comment]
Sure, I'll work on this 👍
