### ISSUE TITLE
`Plagiarism`, `Programming Exercises`: Side-by-side view incorrectly handles HTTP 409 responses from `/api/repository/*/files`

### ISSUE THREAD

**Issue by martinmo** [ls1intum/Artemis#7026]
### Describe the bug

(I've seen #6579, but my issue seems to be unrelated.)

During a review of plagiarism matches ("check plagiarism" in an exercise), I noticed that sometimes one of the source code views (left or right) again contains the source of the corresponding side of a previously selected (and unrelated) match when switching to another match. In the browser network console, `409 CONFLICT` responses are shown from the `/api/repository/*/files` endpoint. I guess this response (and maybe others, this should be checked) isn't handled properly and the previous contents are rendered again.

In the meantime, I could work around this by git-stashing all changes of all affected repos under the `artemis.repo-clone-path` on our server.

### To Reproduce

1. Find an exercise that has enough and very similiar submissions for a plagiarism check.
2. Provoke the conflict: for example, as another user `U` that participates in the exercise, edit code via the online editor, without submitting. Afterwards, commit something directly via git.
3. Go to `/course-management/COURSE_ID/programming-exercises/EXERCISE_ID/plagiarism` and run the plagiarism check with an appropriatly low threshold and wait for it to finish.
4. Open the browser's Javascript console.
5. Select a match that doesn't involve user `U`, afterwards, select a match that involves user `U`.
6. See the error in the console and also see that either the left or right side, which should contain code by user `U`, actually contains unrelated code.

### Expected behavior

Display a message that there was an error when loading the files. Maybe add a hint what can be done about it (e.g., stashing the online editor changes on the server or some other cleanup operation that Artemis might offer).

### Which version of Artemis are you seeing the problem on?

6.3.8

### What browsers are you seeing the problem on?

Firefox

**Comment by jakubriegel** [comment]
I've implemented the solution in #7848. @martinmo
