### ISSUE TITLE
Feedback details list: points for feedback not rounded as expected 

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#7032]
### Describe the bug

The points for a result are rounded not according to the course settings.
This results in two different total scores being shown in the feedback details dialogue (see screenshot) which is confusing to students.

### To Reproduce

1. In the course settings, set the rounding to 2 decimal places.
2. Set up a new programming exercise that has 10 points, and 6 test cases.
3. For the solution repo, all tests pass and each test should result in $\frac{10}{6} \approxeq 1.67$ points. However, each test is shown to give 2 points instead.

### Expected behavior

The rounding is applied to the feedback items.

### Screenshots

Course settings:
![image](https://github.com/ls1intum/Artemis/assets/64250573/905885fb-e4b7-4387-b0f5-8073f6c323c3)

Result: 
![image](https://github.com/ls1intum/Artemis/assets/64250573/c89ac403-e001-42fe-8bb1-56e54425e219)

Feedback list:
![image](https://github.com/ls1intum/Artemis/assets/64250573/bcd52204-ebd1-458c-94a9-838501a8c6d1)

### Which version of Artemis are you seeing the problem on?

6.3.6, 6.3.8

### What browsers are you seeing the problem on?

Firefox

**Comment by krusche** [comment]
@simon-hng could you please have a look why the rounding is incorrect here and provide a fix?
Thank you

**Comment by simon-hng** [comment]
![image](https://github.com/ls1intum/Artemis/assets/25489463/e7e90b07-7fa7-46a4-962e-f6f5e0a190e6)

Couldn't reproduce. I messaged Benedikt on Slack to schedule a call and have a look at the problem with him

**Comment by Strohgelaender** [comment]
Was there a change to the score rounding value? The feedback points get calculated and rounded on receiving the result on the server. A change to the rounding accuracy does not get applied immediately, but requires a new result.

**Comment by b-fein** [comment]
Triggered a new build to make sure the rounding was not influenced by changes to the course settings: Same result.

The grading page shows the points for the test cases as 1.67, the feedback dialogue as 2 points.

**Comment by b-fein** [comment]
Example test case from that response:

```json
  {
    "id": 00000000,
    "text": "...",
    "hasLongFeedbackText": false,
    "credits": 2,
    "positive": true,
    "type": "AUTOMATIC",
    "visibility": "ALWAYS"
  },
```

**Comment by krusche** [comment]
@simon-hng any progress on this issue?

**Comment by simon-hng** [comment]
@b-fein and @Strohgelaender managed to narrow the issue to the server. Benedikt wanted to reproduce the issue in a test environment but it appears the issue is only in Production.

I offered him help if anything comes up but otherwise I don't have any further progress to report. @b-fein, maybe you could further elaborate?

**Comment by b-fein** [comment]
Did not happen again. No idea what was the issue. ¯\\\_(ツ)\_/¯
