### ISSUE TITLE
Coverage script falsely displays `deleted` in line coverage column

### ISSUE THREAD

**Issue by MaximilianAnzinger** [ls1intum/Artemis#7035]
### Describe the bug

Currently, our support script to generate the coverage table falsely reports `deleted` when the coverage could not be retrieved.

### To Reproduce

Generate a code coverage table for a branch that contains a file for which no coverage can be retrieved.

### Expected behavior

If the coverage can't be retrieved it should display a dedicated flag (e.g. `not found`)

### Screenshots

Line of coverage table:
<img width="629" alt="Screenshot 2023-08-03 at 13 30 30" src="https://github.com/ls1intum/Artemis/assets/44003963/29ae41c4-d719-43f7-b438-fc0f06f6296f">

Proof that file was not deleted:
<img width="1367" alt="Screenshot 2023-08-03 at 13 31 07" src="https://github.com/ls1intum/Artemis/assets/44003963/f90a26af-b122-485c-82fb-f8330a3da434">

### Which version of Artemis are you seeing the problem on?

6.3.9

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

Not related to browser.

**Comment by MaximilianAnzinger** [comment]
@FelixTJDietrich I already contacted you about this. I added this issue so other developers are informed.

**Comment by FelixTJDietrich** [comment]
Okay I looked into it. The quick fix is just to rename `deleted` to `not found`. I was not really satisfied with this and tried to match the test file with the SUT file (?) but I think this can not be done reliably for all cases.

Ideally, it would like something like this, IMO:
|SUT File|Test File|Tests Status|
|--------|---------|------|
| x.ext       | x_test.ext | Adjusted ✅|
| x.ext       | x_test.ext | Not adjusted ❌|
| x.ext       | x_test.ext | Added ✅ |
| x.ext       | - | Deleted |
| x.ext       | - | Missing ❌ |
