### ISSUE TITLE
Offer to instructors a text box next to the option of removing the slides

### ISSUE THREAD

**Issue by pellumbbaboci** [ls1intum/Artemis#7039]
### Is your feature request related to a problem?

When instructors create a lecture and then choose to process the units automatically they can also remove "Break" or "Example solution" slides from the PDF file. But if the slides have different pattern or are in different language the removal process will not work as it does search the words  "Break" or "Example solution". 

### Describe the solution you'd like

In this #6895 PR it was suggested to offer to instructors a text box next to the option of removing the slides by @JohannesStoehr. So when instructors choose to remove slides they should see a text box alongside the option to remove slides, allowing users to input their desired text. If instructors fill the text box the slide to be removed will be compared with the entered string, otherwise it should be compared with default values: "Break" for break slides and "Example solution" for solution slides.

### Additional context

Possible solution is to get as request body 2 new fields (breakString and solutionString) and then pass to the split service that will be compared when removing slides.

**Comment by nityanandaz** [comment]
Support a comma-separated list of key phrases
