### ISSUE TITLE
UX- Excercise Overview keep dropdowns of sections open

### ISSUE THREAD

**Issue by JNB-80335** [ls1intum/Artemis#704]
### Is your feature request related to a problem?
 Most of the time, when I go back to the Excercise Overview, after having entered an excercise, all sections (also the one recently opened by me) are closed and the page is shown at the top of the list. Then, I have to search through the sections to find where I entered last. But this takes time and is annoying.

### Describe the solution you'd like
When I go back into the Excercise Overview, the dropdown should stay opened as when I chose the specific excercise. Moreover, it should redirect to the right height on the page where I click on an excercise last, if for example the excercise dropdown block was at the end of the page.

![image](https://user-images.githubusercontent.com/51079607/62308917-afd37900-b486-11e9-9650-7b0fb3c37036.png)

**Comment by krusche** [comment]
We will rework the exercise overview soon
