### ISSUE TITLE
Show git clone link only after repo has been unlocked

### ISSUE THREAD

**Issue by pogobanane** [ls1intum/Artemis#7044]
### Is your feature request related to a problem?

On an exam with 6 programming exercises, we ran into the problem of long repository (un)locking times. We ran into the problem of unlocking taking longer than 10 minutes in our exam test run and in main exam, when we wanted to unlock repos again after submissions closed. This is confusing for students since they dont get useful error messages when their clone fails due to unlocking no being complete. It is also confusing for students, because they dont know what an "illegal submission" is. 

### Describe the solution you'd like

- Add hover text explanation for "illegal submission"
- Only show git clone link, once the repo has been unlocked. In the meantime display a loading symbol or so. 

### Describe alternatives you've considered

An alternative is to have either less students or less programming exercises per exam. 

### Additional context

related https://github.com/ls1intum/Artemis/issues/6971

**Comment by krusche** [comment]
Adding a better explanation for illegal is definitely a good idea. But showing a loading icon until the repo is unlocked would be more difficult. We will evaluate whether we could implement this in a reasonable effort and user experience

**Comment by krusche** [comment]
After discussing this issue again, we cannot sync the state of the button with the state of the repo easily and reliably without adding too much additional load on the system.

In the longtime we want to use a local VCS solution within Artemis, where locking and unlocking operations are not necessary any more. The permission whether students can clone/push is then directly checked during the respective git operations based in the settings of the exam / student exam.
