### ISSUE TITLE
UX Toolbar - Add Sort features + Un-/Fold all Button

### ISSUE THREAD

**Issue by JNB-80335** [ls1intum/Artemis#705]
### Is your feature request related to a problem?
During my exam preparation, at first I wanted to go through all quizzes. I had to open each dropdown to get into each quiz. This took long. Moreover, when I was looking for an overview of all Modeling excercises, I had to go through the same as aforementioned.

### Describe the solution you'd like
The Sort Excercise button, which offers sort for newest/oldest first, could have additional features like only show quizzes, only show modelling/programming/text excercises. 

Moreover, in order to not have to open every dropdown manually or if not needed anymore, close all dropdowns manually, a button called "Fold/Unfold Sections" could be shown beside of the sorting excercises button. This would increase the usability of the Excercise Overview. Same could be done for the lectures overview.

Additionally, the filtered should stay active as long as I am in my session, e.g. when I am switching between different quizzes the user of course does not want to set the filter over and over again.

![image](https://user-images.githubusercontent.com/51079607/62309859-903d5000-b488-11e9-9198-7ae35cb066a4.png)

**Comment by jpbernius** [comment]
Somewhat related to #386 and #599

**Comment by krusche** [comment]
The most important aspect was fixed by #599 which is already merged.
For the other aspects, we decided in the development team that too many filter options would lead to problems in the user interface. Therefore, I will close this issue
