### ISSUE TITLE
Exam Mode: Improve review page

### ISSUE THREAD

**Issue by florian-glombik** [ls1intum/Artemis#7203]
### Problem  
The current version of the review page for exams is inconsistent and therefore unclear in many places. Reviewing solutions and assessments often leads to navigating to other pages, which impairs the User Experience.

### Motivation 
Make the _Exam Results_ page easier to understand by reducing duplicated information and reducing the need of navigating away from the Exam Results page to improve the user experience.
Ensure a uniform design to improve understandability.

This issue is addressing the _General Information_ and _Exercise Overview_ of the _Exam Results_ page.

---
### Existing (Problematic) Solution / System 
1. Duplicated information in the header which makes it hard to retrieve the relevant information
2. Unclear connection between overview and exercises
3. Must navigate to another page to view the grading key

![image](https://github.com/ls1intum/Artemis/assets/63976129/28a1cab2-31af-46f4-a99b-3ebfa1021b37)

![image](https://github.com/ls1intum/Artemis/assets/63976129/e035ea26-7c7e-4032-a5ae-21c0cb0489a8)

### Proposed System 
1. Remove duplicated information
2. Improve UX
    a) Make columns clickable and scroll to the associated exercise
    b) Unify exercise names and usage of related icons
    c) Do not display the _Included in Score_ column if all exercises are included in the score
3. Make _View Grading Key_ collapsable, to ensure that the page must not be left

## UI / UX 
[See Design](https://www.figma.com/file/poo7wrcoGWmNavqBOlGkhh/Florian-Glombik---Exam-mode%3A-improve-review-page-design?type=design&node-id=0-1&mode=design&t=pp13zvYKwGBi3r9K-0)

![image](https://github.com/ls1intum/Artemis/assets/63976129/48e64041-d5fa-43c0-96f1-87a7e33258c4)

**Comment by Strohgelaender** [comment]
Two additional ideas:

- Maybe you can make the achived points / percentage clickable to directly open the feedback detail modal.
- In case all exercises are included into the exam score (which should be the case for most exams), the 'included' column can be hidden.

What do you think of this?

**Comment by florian-glombik** [comment]
Regarding https://github.com/ls1intum/Artemis/issues/7203#issuecomment-1720911011

I think that making the feedback viewable in the overview will not be needed with the new design described in the second milestone [Exam mode: Usability and readability of exercise results and assessment #7278](https://github.com/ls1intum/Artemis/issues/7278)

The second point is incorporated 🙌
