### ISSUE TITLE
Drag and Drop Model Quiz Exercise "Generate Quiz Exercise" button not working

### ISSUE THREAD

**Issue by basak-akan** [ls1intum/Artemis#7211]
### Describe the bug

When using the drag-and-drop model quiz, the 'generate quiz exercise' button doesn't appear to function. I expect it to create a quiz exercise and redirect to the course management exercises page. The [documentation](https://ls1intum.github.io/Artemis/user/exercises/quiz/#create-drag-and-drop-model-quiz-exercise) lacks clear instructions on this.

### To Reproduce

1. Go to Course Management of an Artemis course
2. Click on Exercises
3. Scroll down to Quiz Exercises
4. Click on Create Drag and Drop Model Quiz
5. Click on Create a new Apollon Diagram
6. Fill title and select any Diagram Type
7. Drag-drop some modeling
8. Click on Generate a Quiz Exercise
9. No actions happen

### Expected behavior

The expectation would be the generation of an drag and drop model quiz exercise

### Screenshots
![Drag_Drop_Quiz_Issue](https://github.com/ls1intum/Artemis/assets/11020241/e3ede797-a817-4754-9997-e520abe61fd9)

### Which version of Artemis are you seeing the problem on?

6.5.0

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
No errors appear on the console
```

**Comment by milljoniaer** [comment]
I was just investigating for this issue #7020 when I also realized the problem with the "Generate Quiz Exercise" button. But as far as I could see the button is just not working as long as no interactive parts are inserted/selected in the model (what in general makes sense for a dnd quiz).
But we should disable the button as long no interactive parts are there and display some kind of validation error.
