### ISSUE TITLE
Programming Exercises: Result Generation for Existing Programming Exercises Is Broken

### ISSUE THREAD

**Issue by just-max** [ls1intum/Artemis#7227]
Since the maintenance work over night (update to 6.5.0, presumably), existing programming exercises variously generate incorrect and/or duplicate results. I'll try to describe the issue as best I can, but as I don't have reproduction, I would appreciate some pointers for investigating this issue further.

For a given programming exercise, here's what I've been able to observe:
- The build in the underlying CI system (Bamboo) completes successfully, and all JUnit test cases are recognized properly.
- In Artemis, the student sees two results. The first result properly contains the test results, while the second shows a "Build Failed"
  ![image](https://github.com/ls1intum/Artemis/assets/17551908/633ec909-05e5-426a-b811-4758e7a33e48)
    - The first result always shows 0% when I've reproduced this (even though all tests passed), but students have sent screenshots with a score of e.g. 85%. The result contains the build log, and properly shows the test results:
      ![image](https://github.com/ls1intum/Artemis/assets/17551908/519bd604-e288-4f7f-a5c1-a449591bf7d0)
    - The second result shows the typical build failure message, but since the build succeeds, there is just some log information:
  ![image](https://github.com/ls1intum/Artemis/assets/17551908/8e5c408d-08b9-48e8-a9b0-4ef22305f97d)
- From the instructor view (e.g. for the template and sample solution), only the latest result, i.e. the build failure is shown.

### To Reproduce

None, unfortunately. Newly created exercises have no apparent issues.

### Expected Behaviour

A single result, properly showing passed/failed tests, the score, and no build failure message.

### Which version of Artemis are you seeing the problem on?

6.5.0

### What browsers are you seeing the problem on?

Firefox, not browser-specific

### Additional context

All this has been observed only in OCaml exercises. Note that we have modified the configuration of our exercises in Bamboo: the Docker image is a custom one. I can't think of any other modifications. Unfortunately, we have no existing exercises with an unmodified Bamboo configuration to check this issue against.

Additionally, our exercises use the "Sample Solution Checkout" feature, but I can't imagine that being the issue here.

From looking over recent commits, the most relevant I've seen is the one of #6682. That one seems to be live, despite being committed after 6.5.0, but I'm anyway not sure how that would cause this issue.

**Comment by krusche** [comment]
I already found something out in the database. Apparently, Artemis currently generates two results for the same submission and same participation, both with the same result_order 0, which definitely should not be the case.

I found this in the practice mode of an OCaml programming exercise. I will check if this also happens for other exercise types.

**Comment by just-max** [comment]
That sounds promising. Here are a couple more exercises where I've been able to observe this behaviour:

https://artemis.ase.in.tum.de/course-management/253/programming-exercises/9820
https://artemis.ase.in.tum.de/course-management/253/programming-exercises/10001
https://artemis.ase.in.tum.de/course-management/253/programming-exercises/10059

Obviously these are exercises from our course (but they're not too sensitive because they are only tutorial exercises). If you need any other information or more examples let me know.

**Comment by krusche** [comment]
I also cannot reproduce this for an existing (migrated) programming exercise in Java using the practice mode

**Comment by krusche** [comment]
> That sounds promising. Here are a couple more exercises where I've been able to observe this behaviour:
> 
> https://artemis.ase.in.tum.de/course-management/253/programming-exercises/9820 https://artemis.ase.in.tum.de/course-management/253/programming-exercises/10001 https://artemis.ase.in.tum.de/course-management/253/programming-exercises/10059
> 
> Obviously these are exercises from our course (but they're not too sensitive because they are only tutorial exercises). If you need any other information or more examples let me know.

I imported one of your exercises into a test course and could reproduce the issue in the solution build

**Comment by just-max** [comment]
Interesting. As mentioned, this problem also does not occur on newly created OCaml exercises. I had also observed up until now that importing the exercise made the problem go away, but it looks like that's not always the case. I can try resetting the build plan on one of the problematic exercises and recreating our CI system changes to see if the issue goes away.

**Comment by krusche** [comment]
I was also able to reproduce this issue in the imported exercise for a student in the graded mode

<img width="1381" alt="image" src="https://github.com/ls1intum/Artemis/assets/744067/6c4f0a3d-05c2-471e-b189-9a8192924873">

Two results are created shortly after each other, even if there should be only one.
As fas as I can tell, this is independent of the migration and happens only for Ocaml exercises (maybe exercises which use the solution repo for the build plan)

**Comment by krusche** [comment]
Interestingly it does not occur for a newly generated Ocaml programming exercise

**Comment by krusche** [comment]
I think I found the issue. One step in the migration failed (i.e. deleting the old notification URL) @julian-christl 
Therefore, some migrated build plans now have 2 notification recipients

**Comment by krusche** [comment]
Therefore, this does not happen for new exercises

**Comment by julian-christl** [comment]
How often does this occur? Should we clean this up or is this so rare that this can be resolved manually?

**Comment by just-max** [comment]
From checking a random sample, it occurs on any of our programming exercises, of which there are about 40. So we would be grateful for an automated fix. Unless you mean, of course, manually running a script admin-side to fix these issues.

**Comment by krusche** [comment]
<img width="1256" alt="image" src="https://github.com/ls1intum/Artemis/assets/744067/b5590aed-5331-4335-8f2a-c21f6b616d38">

**Comment by krusche** [comment]
I don't really know how many programming exercises are affected. We try to implement an automatic script to resolve this.

**Comment by b-fein** [comment]
Similar issue will probably happen for GitLab/Jenkins setups → #7233

**Comment by krusche** [comment]
> Similar issue will probably happen for GitLab/Jenkins setups → #7233

It only happens if you change the base URL of Artemis in the yml configuration, which we have done once at TUM from artemis.ase.in.tum.de to artemis.in.tum.de

If you never did that, you are not affected by the problem.
