### ISSUE TITLE
`Tutorial`: Usability issues in the creation of tutorial. The search text fields does not work as expected. 

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#7292]
### Describe the bug

Some fields in the creation of Tutorials are not working properly. 

When you add a tutor, definitely  "You can search by typing into the field."

This is not applicable to Campus and Language. If this is on purpose, then the instruction bellow the field should be different. 

<img width="723" alt="image" src="https://github.com/ls1intum/Artemis/assets/88991954/f6226c51-4072-4e99-a5b2-202abb9d30be">

### To Reproduce

1. Go to a course
2. Create a Tutorial
3. In the tutor field verify that you type something and suggest some tutors. 
4. In the language and Campus, verify that you have to write completely the name of the Campus and Language. Even if the instructions say that you can search for languages and Campuses. 

### Expected behavior

These 2 fields show work as the searcher for tutors. Otherwise, the instructions should be adapted. 

### Which version of Artemis are you seeing the problem on?

6.5.3

### What browsers are you seeing the problem on?

Chrome

**Comment by milljoniaer** [comment]
I tried to reproduce this issue, but as far as I can see everything worked. 
Have you added other tutorial groups? Since the search function only works with the Campuses and languages with have already been used in other tutorial groups.
<video src="https://github.com/ls1intum/Artemis/assets/78978542/0de8b325-5d98-4ee9-bb9f-016bab53a277">

**Comment by Strohgelaender** [comment]
Can we maybe seach for campus and language options in other courses where the creating user is instructor? Since courses are usually hold in regular intervalls these values can just be shown again in the following years.
