### ISSUE TITLE
`Iris`: Label is linked to wrong switch

### ISSUE THREAD

**Issue by JohannesStoehr** [ls1intum/Artemis#7343]
### Describe the bug

In the Iris settings clicking on the label to enable/disable Hestia, toggles the switch for the Iris settings.

### To Reproduce

1. Go to Course Management
2. Click on Iris settings
3. Click on 'Enabled/Disabled' under the Hestia settings
4. See error where Iris is instead enabled/disabled

### Expected behavior

Hestia should be enabled/disabled

### Screenshots

https://github.com/ls1intum/Artemis/assets/38322605/13479135-fbd2-4480-8020-5fd564ef8045

### Which version of Artemis are you seeing the problem on?

6.5.4

### What browsers are you seeing the problem on?

Safari

**Comment by mohanadkandil** [comment]
Hey, if no one is working on this I can take this as my 1st contrib @ Artemis
