### ISSUE TITLE
🧪 Add (Unit|Integraiton) Tests for Jira (+LDAP) Authentication Flow

### ISSUE THREAD

**Issue by jpbernius** [ls1intum/Artemis#737]
The Authentication Flow depends on two external systems:
  - Jira
  - LDAP #716

We should add test coverage for this. Cases to consider include:
  - Artemis only Accounts
  - Jira only Accounts
  - Jira + LDAP Accounts
  - Updating Name/Email on external system

**Comment by ungaralex** [comment]
Currently covered:
* Artemis only Accounts
* Jira only Accounts

**Comment by krusche** [comment]
I think most of the mentioned tests are covered now
