### ISSUE TITLE
`Exam mode`: Misleading notification when updating exam details

### ISSUE THREAD

**Issue by florian-glombik** [ls1intum/Artemis#7380]
### Describe the bug

When updating the Title of an exam a notification for updated working time is sent to the students.

### To Reproduce

1. Configure an exam 
2. Make sure the exam is visible to students _(exams have been prepared & exercise start aswell)_
3. Change the title of the exam
4. See that the registered students receive a message that the working time would have been updated

### Expected behavior

No notification should be sent

### Screenshots

![image](https://github.com/ls1intum/Artemis/assets/63976129/969fa201-7c16-4cda-9572-452379b3f937)

### Which version of Artemis are you seeing the problem on?

6.6.0

### What browsers are you seeing the problem on?

Chrome

**Comment by aplr** [comment]
Hm, I think it's a server issue, and I already have an Idea what causes it. I'll have a look!

**Comment by aplr** [comment]
Ok fixed it, thanks for reporting, fix is here: https://github.com/ls1intum/Artemis/pull/7382
