### ISSUE TITLE
Practice Mode of Artemis

### ISSUE THREAD

**Issue by ebrukadi** [ls1intum/Artemis#7403]
### Describe the bug

There is an internal server error when I want to use the practice mode of Artemis and this issue happened in multiple different exercises I have tried. The issue causes the practice mode to not work, as the clone repository button only has white blanks. 

### To Reproduce

1. Go to 'any excercise'
2. Click on 'practice'
3. Click on 'Practice with template repository' or 'Practice with graded participation'

### Expected behavior

After a minute of trying to come up with a repository to clone, artemis comes up with an error namely "internal server error".

### Which version of Artemis are you seeing the problem on?

6.6.0

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by Strohgelaender** [comment]
In which course are you encountering the issue? I'm unable to reproduce this locally.

**Comment by krusche** [comment]
please reopen this issue when you can provide more details and the error still occurs
