### ISSUE TITLE
Mention in Messages doesn't notify the user and there is no notification selection in settings for mentions.

### ISSUE THREAD

**Issue by sarpsahinalp** [ls1intum/Artemis#7410]
### Is your feature request related to a problem?

If it is planned to use the messages/communication for courses it might be nice to get a notification when there is a mention. Just like in other platforms: Slack/Discord etc.

### Describe the solution you'd like

A potential solution could be to implement a notification system for mentions. Users should have the ability to customize their notification preferences, including the option to receive alerts when they are mentioned in messages.

### Describe alternatives you've considered

Maybe a notification profile away, online like in other professional messaging apps that makes it possible to recieve notifications of mentions etc.

### Additional context

I have discovered this while testing PR #7405. Here some screenshots where there is no notification: 
![Screenshot from 2023-10-17 18-22-20](https://github.com/ls1intum/Artemis/assets/92453703/81b4589a-962c-4f50-a52a-579748912419)

**Comment by krusche** [comment]
@lennart-keller recently implemented notifications when a user is mentioned. Did you double check the notifications in the upper right corner? Maybe, something is not working correctly or you ran into an edge case.

In any case, we should allow a user to customize this in the notification settings
