### ISSUE TITLE
Leave a course

### ISSUE THREAD

**Issue by JustDaniel7** [ls1intum/Artemis#7416]
### Describe the bug

I cannot leave a course and I don't find a button for it. I might be stupid but I searched for a while, if there is one it should be more visible more easily. 

### To Reproduce

There is no button, so there is no reproduction of the issue.

### Expected behavior

A button to leave a given course I enrolled in.

### Which version of Artemis are you seeing the problem on?

6.6.1

### What browsers are you seeing the problem on?

Chrome

**Comment by Strohgelaender** [comment]
Leaving a course is only possible if the instructor defines an unenrollment period for this course (See PR #6577 for details). Please contact your responsible instructor about this.
