### ISSUE TITLE
Missing Build plans of imported exercise

### ISSUE THREAD

**Issue by sarpsahinalp** [ls1intum/Artemis#7439]
### Describe the bug

It seems that an imported exercise doesn't have build plans.
![image](https://github.com/ls1intum/Artemis/assets/92453703/4083052a-268f-4837-8364-b127e1fbe26f)

Here are the inconsistencies:
![image](https://github.com/ls1intum/Artemis/assets/92453703/3a74cae8-6a6f-441b-bbb7-2635221263aa)

### To Reproduce

The same behavior is not deterministic.

1. Go to course management
2. Import an exercise
3. See the incostency error

### Expected behavior

Build plans from imported exercise work expectedly/ are not missing.

### Screenshots

![image](https://github.com/ls1intum/Artemis/assets/92453703/12e6526f-6c4d-47bc-9ab5-6ed8e5041013)

### Which version of Artemis are you seeing the problem on?

6.6.2

### What browsers are you seeing the problem on?

Chrome

### Additional context

I am a tutor in ITP course. I had to refurbish an exercise from last year, but it gave me this error and there was no build plan connected to exercise and solution build. I also couldn't just edit the build plans had to create a new exercise with new name and shortname.

### Relevant log output

```shell
Ge {headers: O, status: 0, statusText: 'Unknown Error', url: 'api/notification-settings', ok: false, …}
```

**Comment by Strohgelaender** [comment]
Can you (or someone else @MarkusPaulsen) double check that the original exercsie actually has a build plan?

**Comment by Mtze** [comment]
Bamboo and Bitbucket are deprecated - Closing this issue
