### ISSUE TITLE
`Exam mode`: Improve attendance check with websocket based Id information

### ISSUE THREAD

**Issue by max-bergmann** [ls1intum/Artemis#7454]
### Is your feature request related to a problem?

The on site exam mode requires the check of the matriculation number, the name of the student and the artemis username. This information are used to savely identify the student and the open artemis session on the student device. 
Currently the student has to open a new tab and show his credentials. This should be improved and implemented more interactively. 

### Describe the solution you'd like

The instructor should be able to initiate a pop up from the instructors iPad that opens on the students enddevice in the ongoing exam mode. 
This pop up should contain the matriculation number, the name of the student and the artemis username. 
This information is needed to identify the student and his open exam session.

**Comment by krusche** [comment]
cc @bassner
