### ISSUE TITLE
bug in the class JackOlatern

### ISSUE THREAD

**Issue by MWahajKhalil** [ls1intum/Artemis#7512]
### Describe the bug

The de.tum.cit.ase.JackOLantern class has no constructor with the parameter types: [class de.tum.cit.ase.Pumpkin, class de.tum.cit.ase.Candle, class de.tum.cit.ase.Ghost]

this program is showing error even if i switch the postion of parmaters (Candle, Ghost)  in the program which is nothing to do with the program in real life.  i spend hours figuring out this error. Kindly resolve this bug.

### To Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

I wanted program to give no error even if i  switch positions of paramaters in JackOLantern class

### Screenshots

![image](https://github.com/ls1intum/Artemis/assets/96848221/57821e76-5385-4693-b4a3-1490ce2061d4)

### Which version of Artemis are you seeing the problem on?

6.6.3

### What browsers are you seeing the problem on?

Chrome

**Comment by Strohgelaender** [comment]
You are refering to a specific exercise on Artemis, please contact your instructor in this case.

This repository contains the code for the Artemis plattform, and is not about specific exercises.
