### ISSUE TITLE
`Text exercises`: Do not display number of words

### ISSUE THREAD

**Issue by florian-glombik** [ls1intum/Artemis#7522]
### Is your feature request related to a problem?

In the grading view the number of words and number of characters is not relevant for the assessment (as far as I know) - and is rather an indicator for students while working on exercises.

![image](https://github.com/ls1intum/Artemis/assets/63976129/d0eacd05-2023-4212-a592-83da1abd4897)

### Describe the solution you'd like

Do not display `Number of words` and `Number of characters` when in the assessment view for text exercises. 

@milljoniaer @rabeatwork @florian-glombik

**Comment by Strohgelaender** [comment]
The number of words might be relevant depending on the assessment instructions of the course / exercise.

For example, there could be a rule in the problem statement of "write at most 50 words" and an assessment instruction that says that "if more than 80 words a written, deduct one point". Having the word count directly available allows to easily apply that instruction.

Also, I don't think that the assessment view is particularly cluttered and small indicators like this can just stay here.
