### ISSUE TITLE
When hovering over IRIS, page gets scrolled to the top

### ISSUE THREAD

**Issue by FiasKr** [ls1intum/Artemis#7526]
### Describe the bug

If you have the chat with IRIS open and scroll down in the task, the page jumps back to the top as soon as you hover the mouse over the chat window.

### To Reproduce

1. Go to course 'Introduction to Programming (CIT5230000) WS 23/24'
2. Click on any assignment
3. Scroll down a bit and click on the IRIS Chat on the bottom right
4. Hover over the chat window
5. See error

### Expected behavior

The page should remain at the scrolled position.

### Screenshots

![image](https://github.com/ls1intum/Artemis/assets/148067980/88f7b4e7-5273-4b45-8ed8-0db4826d7583)

### Which version of Artemis are you seeing the problem on?

6.6.4

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge

**Comment by yassinsws** [comment]
If no one is working on this I can take it as my first issue
