### ISSUE TITLE
`Exam mode`: Navbar exercise icons not displaying correct state

### ISSUE THREAD

**Issue by florian-glombik** [ls1intum/Artemis#7560]
### Describe the bug

Navbaricon for working on programming exercises not updated properly

### To Reproduce

DISCLAIMER: If the behaviour from the screencast does not occur for you, force reload the page and clear the cache (`Empty cache and hard reload`) - this seemed to be a reliable way for me to reproduce the issue.

1. Create an exam with a programming exercise, activate the online code editor
2. Join the Exam as student before it begins
3. Already input your username and accept the code of conduct _(so you should see a countdown now)_
4. Edit the code in the code editor and see that the build is triggered
5. See the icon is still the pencil and not a checkmark for having something submitted
6. Reload the page and see that now the navbar displays the correct exercise state

The same issue occurs for cloned exercises

### Expected behavior

The state of the exercise should contain a checkmark if submitted, and turn yellow after changes that were not submitted.

Edit file content (navbar pencil icon turns yellow) -> submit (navbar icon turns blue with save icon)

This should be the case without having to reload the page.

### Screenshots

The state after reloading the page would be the expected state. (Checksmarks for exercises where something was submitted)

https://github.com/ls1intum/Artemis/assets/63976129/e2206277-e576-4346-8f60-5fe143605903

<details>
  <summary>Initial Screencast</summary>

https://github.com/ls1intum/Artemis/assets/63976129/c40a667a-371f-4d6b-b380-0ccb5e439252
</details>

### Which version of Artemis are you seeing the problem on?

6.6.4

### What browsers are you seeing the problem on?

Chrome

**Comment by MichaelOwenDyer** [comment]
Cannot exactly reproduce the issue. The icon turns yellow for me, and then back to the pencil upon submitting. Appears as a check mark after reloading the page.

https://github.com/ls1intum/Artemis/assets/59163924/1fdb24e8-1e53-4234-99f4-4cc9c0129b43

What do you think of this? Is this still unexpected behavior? @florian-glombik

**Comment by florian-glombik** [comment]
> Cannot exactly reproduce the issue. The icon turns yellow for me, and then back to the pencil upon submitting. Appears as a check mark after reloading the page.

I will have another look if I can reproduce the issue with the yellow pencil - from my expectation after submitting the state in the navbar should be a checkmark - which was not the case in the screencast. 

So this is still an issue from my point of view.

It also appears to be intended like that when looking at the [documentation ](https://artemis-platform.readthedocs.io/en/latest/user/exams/students_guide.html#participating-in-programming-exercises)

**Comment by krusche** [comment]
I do not fully understand the issue based on the screencast, but I would not consider this as a high priority issue

**Comment by florian-glombik** [comment]
I have exchanged the screencast. The correct state of the navbar is only shown after reloading the page, but when working on the exercises again the states are broken again - does this make the issue clearer?

https://github.com/ls1intum/Artemis/assets/63976129/4732ccad-9e18-47c5-a839-1829ef5fe08d

While reproducing the issue, it worked in some cases - I could not find out the underlying cause to trigger the bug.

The reason why I ranked it as priority high is due to the upcoming exams and students who might be unhappy with losing the overview of which exercises they finished/worked on.
Since the exercises are ordered and the issue does not seem to arise always, it might not be as severe as I thought.

**Comment by krusche** [comment]
I don't think it is related to login/logout and to websockets.

We do not plan to use the online code editor in exams, therefore the priority is not super high, but we should still fix the issue asap.

What I wonder: it seems that the navbar does not highlight the current exercise anymore. Could this be the case?

**Comment by krusche** [comment]
There seems to be another issue: after pushing source code into the git repository, the animation for the build starts and this seems to break some UI elements including the clone dialog
