### ISSUE TITLE
`Exam mode`: Grade bonus is not applied properly

### ISSUE THREAD

**Issue by florian-glombik** [ls1intum/Artemis#7569]
### Describe the bug

The 0.3 bonus is not applied to the grade _(should be 3.7 instead)_

### To Reproduce

- 1 instructor
- 1 student who participated in the course which is used for applying a bonus _(the course needs to have a grading key with type bonus)_
- graded exam with participation and released exam results (student review date in the past)

### Expected behavior

The bonus should be applied properly (grade 3.7)

### Screenshots

![image](https://github.com/ls1intum/Artemis/assets/63976129/68308b23-285d-4120-9817-e329df202744)

### Which version of Artemis are you seeing the problem on?

6.6.4

### What browsers are you seeing the problem on?

Chrome

**Comment by florian-glombik** [comment]
@Jan-Thurner Do you have more insights on the exact bonus configuration that lead to this behaviour?
You can also directly link the test course and user that was used as we want to fix it in the upcoming week

**Comment by Jan-Thurner** [comment]
It was [this exam](https://artemis.in.tum.de/course-management/275/exams/667) . The User was test user 1.

**Comment by florian-glombik** [comment]
It does not seem to be an issue for me.

![image](https://github.com/ls1intum/Artemis/assets/63976129/7153fe72-36a0-4c0b-98ae-83d2292b34e6)

5,3 points are still the grade `4.0` - however, I am wondering if it is intended that the points are not displayed that are associated. I will investigate this but close this issue for now as it seems to work fine for me.
