### ISSUE TITLE
`Exam mode`: Importing a user with incorrespond registration number and login account failed without error report to user

### ISSUE THREAD

**Issue by RY997** [ls1intum/Artemis#7570]
### Describe the bug

When importing users whose registration numbers and login accounts belong to different users, the import is displayed successfully, but it is not displayed on the main page. An error such as "User information does not correspond" should be reported.

### To Reproduce

* 1 instructor
* 1 csv file, the content like this
![image](https://github.com/ls1intum/Artemis/assets/60965100/72421148-79e8-44e1-9464-9d44a5b0a7b1)

1. Go to an existing exam or create a new one
2. Click on "Students" and then "Import students"
4. Upload a CSV file and import it

### Expected behavior

When the registration number and login account are inconsistent but valid, we should have an error report.

### Screenshots

<img width="599" alt="image-2023-11-10_10-54-55" src="https://github.com/ls1intum/Artemis/assets/60965100/3ba99d1d-3435-451f-b01c-05a3101fd6c3">

![image-2023-11-10_10-55-16](https://github.com/ls1intum/Artemis/assets/60965100/98b7ac75-c615-499b-8d55-6f08c46325f0)

### Which version of Artemis are you seeing the problem on?

6.6.4

### What browsers are you seeing the problem on?

Chrome

**Comment by sarpsahinalp** [comment]
Could not reproduce the issue. It seems that this happens only when the login belongs to an instructor in the course.

**Comment by florian-glombik** [comment]
I think that @sarpsahinalp is right and it is only related to instructors: [Exam mode: Missing instructor validation on csv user import #8879](https://github.com/ls1intum/Artemis/issues/8879)
