### ISSUE TITLE
add link to "student course view" to "course management view"

### ISSUE THREAD

**Issue by pogobanane** [ls1intum/Artemis#7596]
### Is your feature request related to a problem?

While drafting a course, the course is only available in "course management", but not in "course overview". 
However testing exercises from a student perspective is best done from the students view of an exercise (particularly for programming exercises). 

### Describe the solution you'd like

Place a link to the student view of the course (https://artemis.ase.in.tum.de/courses/276/exercises) on the course management page of the course. 

### Describe alternatives you've considered

A good workaround is guessing under which URL the student view is hidden.

**Comment by MaximilianAnzinger** [comment]
I've opened a PR since I myself would love this simple QOL improvement. 👍 
I'd use this multiple times per day. 

@krusche was it intentional to leave this out or can we add this?
