### ISSUE TITLE
Frontend Responsive Nav Bar not showing Course Management

### ISSUE THREAD

**Issue by MaximilianJG** [ls1intum/Artemis#7601]
### Describe the bug

When I am zoomed in too much and logged in as Admin the course management (and server administration) tabs disappear. 

### To Reproduce

1. Use test server 2
2. Log in as admin user
3. Zoom in (or use a small device) 
4. Buttons should disappear

### Expected behavior

It would be better, if you could smaller icons for smaller screens (or a dropdown) 

### Screenshots

<img width="1226" alt="Screenshot 2023-11-15 at 17 48 56" src="https://github.com/ls1intum/Artemis/assets/64839680/8d11c445-c626-4a25-ad72-942a04eacac9">

<img width="744" alt="Screenshot 2023-11-15 at 17 49 01" src="https://github.com/ls1intum/Artemis/assets/64839680/8f33411f-a06d-44d1-8b8b-98ef5dfe2617">

### Which version of Artemis are you seeing the problem on?

6.6.5

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge, Firefox, Other (specify in "Additional context")

**Comment by krusche** [comment]
There should be a dropdown menu (with the three lines) in the upper right corner 
<img width="1910" alt="image" src="https://github.com/ls1intum/Artemis/assets/744067/8e43b79e-969d-4d8e-a1ab-794d93f738c1">
In your screenshot, it might be hidden by the zoom level
