### ISSUE TITLE
`Plagiarism checks`: Option for check after due date is toggled by default

### ISSUE THREAD

**Issue by JohannesStoehr** [ls1intum/Artemis#7611]
### Describe the bug

Currently the option for checking plagiarism after the due date is toggled by default and cannot be changed unless CPC is enabled.

### To Reproduce

1. Create a programming exercise
2. Try to toggle the plagiarism detection after the due date
3. Scroll down to '...'

### Expected behavior

It should not be enabled by default and it should be possible to deactivate it, even if CPC is not enabled

### Screenshots

![Bildschirmfoto 2023-11-17 um 11 38 57](https://github.com/ls1intum/Artemis/assets/38322605/2dc4adef-58e2-4271-a2ea-2d7dccbf9a1b)

### Which version of Artemis are you seeing the problem on?

6.6.6

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge, Firefox

**Comment by Strohgelaender** [comment]
Should it even be possible to active this without CPC? Or are these two independent features?

**Comment by jakubriegel** [comment]
This is an intended behavior of this component. We want the post due date checks to be enabled by default when CPC is enabled. 

When CPC is not enabled then no checks are triggered (including the post due date ones). That's why the UI checkbox is disabled when CPC is unchecked.

**Comment by Strohgelaender** [comment]
I think this is still an issue. Even if the checkbox being active has no impact, this behavior is unexpected and not explained by the UI. This checkbox should be inactive by default and only get set to true once CPC gets enabled.
