### ISSUE TITLE
`Exam mode`: Students not displayed after exam conduction

### ISSUE THREAD

**Issue by MaximilianAnzinger** [ls1intum/Artemis#7614]
### Describe the bug

When viewing the students registered for an exam after the conduction, there are 0 students displayed.

However, the students are requested from the server (see screenshot). Moreover, the student exams should not be loaded when requesting registered students (see screenshot).

![chrome_ucA1ggegwl](https://github.com/ls1intum/Artemis/assets/44003963/6fced840-ac7d-4167-89db-fb265c186974)
![chrome_Jqvq9poqwd](https://github.com/ls1intum/Artemis/assets/44003963/98bde3b0-c807-4f08-9151-93b05387045e)

### To Reproduce

1. Go to Exam management after conduction
2. View students (*not student exams*)
3. no students

### Expected behavior

List of students should be displayed correctly.

### Screenshots

![chrome_8nmBLHXbQw](https://github.com/ls1intum/Artemis/assets/44003963/be497a17-493f-4c3a-88ea-9187e9f5ae5b)

### Which version of Artemis are you seeing the problem on?

6.6.6

### What browsers are you seeing the problem on?

Chrome

**Comment by krusche** [comment]
It might be that additional data is loaded to show potential issues with attendance checks, eg a student who participated from
home. We should fix the issue asap!

**Comment by JohannesStoehr** [comment]
I get this error in the console. Might be the cause for that...
<img width="392" alt="Bildschirmfoto 2023-11-17 um 19 36 18" src="https://github.com/ls1intum/Artemis/assets/38322605/1aa0bef7-bf74-43a3-aa0e-fd207b35ba60">

**Comment by maximiliansoelch** [comment]
@MaximilianAnzinger Did you create a student exam for each registered student?

**Comment by MaximilianAnzinger** [comment]
@maximiliansoelch Yes, I know what you're referring to but that's something that should not be discussed on GH.
