### ISSUE TITLE
Praktikum: Grundlagen der Programmierung WS23/24; W04H01 - Rekursive Pinguologie, test case flawed

### ISSUE THREAD

**Issue by paul-linked** [ls1intum/Artemis#7628]
### Describe the bug

nicht ein bug aber der test case ist halt kapput oder zumindestens macht kein sinn. es steht " Test Case · Task 1 - Test negative failed
Der 2. Wert der pinguSequenceRec für p=(2,9,0) ist falsch. Erwartet: 18; aber war: 9" aber das kann nicht sein weil der zweite wert ist der parameter 9. okay vieleicht ist es 0- indexed aber immernoch dann waere es 0, und nicht 18. oder vieleicht hab ich etwas verpasst und es ist meine schuld, ich hab shon sehr viele stunden PGdP gemacht :')

### To Reproduce

1. Go to Courses > Praktikum: Grundlagen der Programmierung WS23/24 > Exercises > W04H01 - Rekursive Pinguologie
2. Aufgabe 1 - Rekursive Pinguin Reihe
3. der test der auf bitbucket ist sieht so aus: @HiddenTest
	@DisplayName(value = "Task 1 - Test negative")
	public void t1TestNegative() {
		long[] results = new long[] { 2L, 18L, 0L, -10L, 26L, 36L, -10L, 6L, 88L, 62L, -14L, 100L, 238L, 110L, 72L,
				438L };
		for (int i = 0; i < 16; i++) {
			long studentValue = RecursivePingulogy.pinguSequenceRec(-i, 2, 9, 0);
			if (results[i] != studentValue) {
				TestUtils.privilegedFail(
						"Der " + (i + 1) + ". Wert der pinguSequenceRec für p=(2,9,0) ist falsch. Erwartet: "
								+ results[i] + "; aber war: " + studentValue);

### Expected behavior

volle points, fuer mich sogar extra weil ich so nett bin und das reporte :smile:

### Which version of Artemis are you seeing the problem on?

6.6.7

### What browsers are you seeing the problem on?

Chrome

**Comment by krusche** [comment]
This is not a bug of the Artemis learning platform and therefore this is the wrong place to report this issue. So while we really appreciate that you get in touch with us, we would kindly ask to notify the instructor or a tutor of the respective course.

If you find other issues related to Artemis itself, feel free to create feature requests or bug reports here on Github.
