### ISSUE TITLE
Create a lazy angular module that includes the markdown editor

### ISSUE THREAD

**Issue by krusche** [ls1intum/Artemis#764]
The markdown editor is only used in the course administration by a few users who want to create exercises. It contains quite some dependencies, e.g. the ace editor and showdown.

It would be great if we could create a lazy angular module that integrates the markdown editor. If this is problematic because the markdown editor is used in multiple routes, we should think about an alternative, e.g. a `course-admin` module that includes everything that is only needed in the course administration. Example: In EIST, we have around 1500 users who accessed Artemis. Only around 50 (i.e. around 3%) of them - the tutors and instructors - actually need access to the course administration page, so this is a case where lazy loading definitely makes a lot of sense!

In addition, we need to make sure that the new module does not duplicate code that is also used in the code-editor module which can also be used by students.

**Comment by krusche** [comment]
https://developers.google.com/web/fundamentals/performance/optimizing-javascript/code-splitting/
https://developers.google.com/web/tools/lighthouse/audits/first-contentful-paint
https://developers.google.com/web/fundamentals/performance/optimizing-javascript/tree-shaking/

**Comment by thilo-behnke** [comment]
:+1:
