### ISSUE TITLE
Wrongly displayed grading table when a test case is linked in two different tasks

### ISSUE THREAD

**Issue by JanaNF** [ls1intum/Artemis#7670]
### Describe the bug

You can include the test cases in the individual subtasks of programming assignments so that students can click directly on the feedback for the subtask.
The grading page also shows it sorted according to the subtasks.

Problem: If you accidentally link a test in two subtasks, it also shows the grading table in both subtasks, and then, for example, the "Resulting Points" are no longer correct.

Suggestion to solve this problem: Either warn about this in the task editor and/or, if the tests have been linked twice, display all tests individually in the grading table and don't sort by subtasks.

### To Reproduce

1. Create a programming exercise
2. Include different test cases to the subtasks
3. Link a test case to two different subtasks
4. Go to the grading table
5. The grading table displays that test case twice and shows wrong information, e.g. the Resulting points are off

### Expected behavior

To not see both subtasks in the grading table and correct "Resulting Points".

### Screenshots

![image](https://github.com/ls1intum/Artemis/assets/41042413/f221bf8b-e562-49fa-b3dc-11aaab058fd8)

### Which version of Artemis are you seeing the problem on?

6.6.8

### What browsers are you seeing the problem on?

Chrome

**Comment by krusche** [comment]
@simon-hng can you have a look please?

**Comment by JanaNF** [comment]
> @JanaNF @krusche. Does this work for you? #7674

Yes, looks good. Tested and approved from my side.
