### ISSUE TITLE
Markdown Editor: Katex formulars with included markdown characters not working

### ISSUE THREAD

**Issue by thilo-behnke** [ls1intum/Artemis#768]
### Describe the bug

Formulas that contain markdown reserved characters (e.g. '_' for italic) are not rendered correctly in the markdown editor.
The problem seems to be that the markdown characters are parsed BEFORE our katex extension parses formulas (https://github.com/obedm503/showdown-katex), as this extension is of type output: https://github.com/showdownjs/showdown/wiki/extensions#type-propertyrequired.

#### To Reproduce

1. Go to Course Administration > Programming Exercises
2. Click on Edit
3. Scroll down to Markdown Editor for problem statement
4. Insert formular `$ a_0 + a_1 $`

#### Expected behavior

It should render as:
![image](https://user-images.githubusercontent.com/28230611/64005726-3d9b9600-cb11-11e9-9213-e5283d1344eb.png)

But renders for us as:
![image](https://user-images.githubusercontent.com/28230611/64005797-53a95680-cb11-11e9-9fac-33e6765b4e9d.png)

### Environment

Environment independent.

**Comment by thilo-behnke** [comment]
Even though it's not ideal, a workaround is to use the centered latex formulars (can't be embedded inline):

``` latex
$ a_0 + a_1 $
```

**Comment by cod-eric** [comment]
You can, however, escape the markdown special characters with a backtick - but this makes it annoying to copy-paste between other editors where LaTeX is rendered before markdown.

**Comment by b-fein** [comment]
Fixed with #9354
