### ISSUE TITLE
Label exercises with categories

### ISSUE THREAD

**Issue by krusche** [ls1intum/ArTEMiS#77]
For the calculation of bonus scores with different kind of exercises, it would be helpful to allow instructors to tag exercises with keywords.
These keywords are then used to filter for certain exercises when calculating the score of students

**Comment by krusche** [comment]
Categories are available in the database, but we need to allow instructors to use them

**Comment by maximilianmeier** [comment]
Fixed in https://github.com/ls1intum/ArTEMiS/pull/201
