### ISSUE TITLE
Programming Exercises: Option to run scheduler when due date passes to grade the submissions

### ISSUE THREAD

**Issue by thilo-behnke** [ls1intum/Artemis#770]
### Is your feature request related to a problem?

Some courses prefer to run a scheduler when the due date passes to grade all submissions.
This would especially be useful with test cases that are only run after the due dates passes ("secret test cases").

### Describe the solution you'd like

We need to use a scheduler that runs when the due date passes and triggers a build in the build plans of the individual repositories.

### Describe alternatives you've considered

n/a

### Additional context

Might be related to https://github.com/ls1intum/Artemis/issues/769 as this will also require a scheduler on due date.

**Comment by jpbernius** [comment]
Maybe you can use the API provided by #621?

**Comment by thilo-behnke** [comment]
This is done :tada:
