### ISSUE TITLE
Tutorial Free Periods longer than one day

### ISSUE THREAD

**Issue by Jan-Thurner** [ls1intum/Artemis#7701]
> Feature Template Spec Version 0.1

### Problem  
> Currently there is no way of setting a tutorial free period (longer than one day) on Artemis

### Motivation 
> In case of semester Holidays like christmas, it happens that there is a lecture / tutorial free period longer than one day. So far, this cannot be represented efficierntly via Artemis.

---
### Existing (Problematic) Solution / System 
Currently, tutorial free periods can only be exactly one day long.

### Proposed System 
The solution should allow for Tutorial free periods in longer intervals.

### Requirements 
1. FR: Tutorial Free Period: In the Tutorial management, an exercise instructor should be able to set Timeframes longer than one day as a lecture free period.

### Dynamic Behavior 
> Include dynamic models (Activity Diagram, State Chart Diagram, Communication Diagram) here to outline the dynamic nature of the PROBLEM 

---
### Subsystem Decomposition
These Subsystems are used: 
![SubsystemDecomposition](https://github.com/ls1intum/Artemis/assets/107639007/f94a81bc-6a0e-4841-b06a-b537936ba606)

No APIs are changed.
In the TutorialGroupFreePeriodDTO and other classes, the red elements are removed, green ones are added and yellow ones modified.
![TutorialGroupFreePeriodDTO](https://github.com/ls1intum/Artemis/assets/107639007/24b88ce8-7071-4894-b512-73ffb98c2aea)
CreateTutorialFreePeriodComponent
![CreateTutorialGroupFreePeriodComponent](https://github.com/ls1intum/Artemis/assets/107639007/8306803b-19bb-4f75-9f32-8bf2eace287a)
![EditTutorialGroupFreePeriodComponent](https://github.com/ls1intum/Artemis/assets/107639007/a815539c-0a6e-424a-8b26-6b74457181bf)
![image](https://github.com/ls1intum/Artemis/assets/107639007/20baeedb-5491-455a-b950-bf45b36be886)
![image](https://github.com/ls1intum/Artemis/assets/107639007/2e49bb3f-3a91-4495-926e-251f9d3c5e65)

### Persistent Data Management
No Database Changes are made.
No new config options are added.
No other data persistency mechanisms are used.

### Access Control / Security Aspects 
The acces control is already in place.

---
## UI / UX 
![image](https://github.com/ls1intum/Artemis/assets/107639007/6fa6a476-128d-4cb5-9e96-5f97c0dd572d)
![image](https://github.com/ls1intum/Artemis/assets/107639007/a052ee2d-8e41-4ee9-a251-fd32072237f9)

**Comment by Strohgelaender** [comment]
See also #7372
