### ISSUE TITLE
Getting a "Not Authorized" Notification when accessing the Course Management Page as a Tutor

### ISSUE THREAD

**Issue by MaximilianJG** [ls1intum/Artemis#7739]
### Describe the bug

When I access the Course Management Page as a Tutor I get a Notification saying: "You are not authorized to access this page". I can still access the content though. 

### To Reproduce

1. Go to Artemis and login as a Tutor
2. Click on Course Management of the Introduction to Programming (CIT5230000) WS 23/24 Course
4. See notification in the top right 

### Expected behavior

The notification should not appear. 

### Screenshots

![Screenshot 2023-12-06 at 14 12 38](https://github.com/ls1intum/Artemis/assets/64839680/d67e45b3-4b96-4feb-82a1-613f5aa5650b)

### Which version of Artemis are you seeing the problem on?

6.7.1

### What browsers are you seeing the problem on?

Chrome, Other (specify in "Additional context")

### Additional context

Arc (runs on Chromium)

**Comment by tobias-lippert** [comment]
Could you please check the network tab in the Chrome Dev Tools for any requests that return a 403.

**Comment by b-fein** [comment]
Closing as duplicate. Further discussion in #7797.
