### ISSUE TITLE
Consistency: Client and server routes for Modelling and Text exercises

### ISSUE THREAD

**Issue by maxr96** [ls1intum/Artemis#778]
### Is your feature request related to a problem?

Both modeling and text exercises have similar routes. However, the naming is usually different and sometimes it doesn't fit our Route Naming Convention. 

### Describe the solution you'd like

We should implement consistent routes for these types of exercises and have it as an example for any future exercise types that will be added.

**Comment by jpbernius** [comment]
We unified client routes when we refactored the angular app structure. Server routes were also unified. This is why I am closing this>
