### ISSUE TITLE
UI Confusion in Iris Button Configuration on Exercise/Iris Settings Page

### ISSUE THREAD

**Issue by egekurt123** [ls1intum/Artemis#7781]
### Problem: 

Currently, on the Exercise / Iris Settings page, the configuration of the iris button appears confusing with "enable/disable." At first glance, I mistakenly perceived that having it positioned on the right indicated it was disabled.

### Proposal: 
Change the labeling to enabled/disabled -> enabled

### Screenshot:
![IrisEnableButton](https://github.com/ls1intum/Artemis/assets/69898283/d2f97129-b997-4753-937b-7ddf32547fd3)

### Which version of Artemis are you seeing the problem on?

6.7.3

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge, Firefox

**Comment by krusche** [comment]
I think we should use a completely different button with different modes and not a simple switch. It could be like the choice of easy, medium, hard for the difficulty of exercises, but just with two states: enabled (green) and disabled (red)

The selected one should then be highlighted

**Comment by egekurt123** [comment]
The same issue is also present in "Hestia Settings" and "Code Editor Settings" buttons.  I am going to handle this in the next couple days.
