### ISSUE TITLE
`Programming exercises`: Manual assessment detaches long feedback from feedback

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#7788]
### Describe the bug

When manually assessing a submission that has some feedbacks with long feedback text, the long feedback text is gone after saving/submitting the manual assessment.

### To Reproduce

- Programming assessment with manual assessment and at least one submission that has a long feedback text (you can create a test case that just contains `fail("abc".repeat(5_0000));`)

1. Wait until after the due date.
2. Start the manual assessment process.
3. When first opening the submission:
     - Open the result details.
     - The test case with the long feedback should still show the full feedback text when opening the feedback details.
4. Add a manual feedback comment.
5. Save the assessment.
6. Open the result details again. Now when opening the feedback with the long text again, the text remains short. The browser devtools network tab shows a 404 error.

### Expected behavior

The long feedback remains attached to the feedback.

### Which version of Artemis are you seeing the problem on?

6.7.2

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

Responsible server endpoint: https://github.com/ls1intum/Artemis/blob/3b14e24870172038f04ec5e40aced7d109a7ea3f/src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingAssessmentResource.java#L133

I suspect the re-fetching of the result with feedbacks might be the issue since I’m confident it was working as originally implemented and the loading again was changed later in #7552:
https://github.com/ls1intum/Artemis/blob/3b14e24870172038f04ec5e40aced7d109a7ea3f/src/main/java/de/tum/in/www1/artemis/web/rest/ProgrammingAssessmentResource.java#L199

After loading in all feedbacks the `longFeedbackText: Set<LongFeedbackText>` is empty. After saving again, the feedback is therefore detached from an existing long feedback text.

**Comment by kaancayli** [comment]
I'm working on this. I just couldn't reproduce the error. Is there any mistakes that I for reproducing this:

1. I create a programming exercise.
2. I do a submission to that exercise.
3. I wait until exercise due date passes, and afterwards I start with the manuel assessment.
4.  I submit a long form feedback. ("abc" repeated 5000 times)
5. Then I add another manuel feedback to the submission, and override the first feedback.
6. When I open the result details I see both feedback without 404 (see image below).

<img width="1131" alt="Screenshot 2023-12-13 at 11 01 34" src="https://github.com/ls1intum/Artemis/assets/38523756/a97ee922-02ef-4768-96ae-12b215ace273">



Am I missing something? Thanks for your response in advance

**Comment by b-fein** [comment]
Step 4: Did you add a test case to the exercise before the student submitted? Then the feedback with the long text is generated from the test case rather than being a reviewer feedback.
```
@Test
void longFeedbackTest() {
    fail("abc".repeat(5_000));
}

**Comment by kaancayli** [comment]
Ok, my bad. I have mistaken it with the instructor feedback. I will check that again.

**Comment by b-fein** [comment]
Thanks for looking into the issue!

Can you open the reviewer feedback by clicking on the ‘See more’? The 404 only might occur then since the long text is only loaded when really needed.
It would be interesting to know if the long feedback works for manually created ones but not for test-case-feedbacks.

**Comment by kaancayli** [comment]
When I click on the `see more` I get 404 also in manuel assessment case. I guess the issue exists for both cases.
<img width="1656" alt="Screenshot 2023-12-13 at 11 29 15" src="https://github.com/ls1intum/Artemis/assets/38523756/9c378c0e-76fb-4c73-805f-1a8ad3a7255b">
