### ISSUE TITLE
`Exam mode`: The diff for problem statement changes is broken if inside Markdown structures

### ISSUE THREAD

**Issue by Hialus** [ls1intum/Artemis#7793]
### Describe the bug

During an exam we had some smaller issues in the problem statement of an exercise, which we adjusted. This then leads to a diff in the student view showing the changes.
However, if the changes are in certain Markdown structure like `code blocks` or task declarations the diff view breaks in two ways:
1. If inside `code blocks` or the name of a task declaration the HTML for the rendering is shown. This confuses the students and requires a page reload to fix
2. If inside certain parts of a task declaration (i.e. the test cases part) the entire task declaration breaks and is not rendered correctly anymore
3. Additionally if the diff concerns a task in a way that overlaps the task name with the test case names, the entire task is shown as a diff with test cases ids replacing test case names. This is caused by the relatively new feature that replaces test case names with test case ids before being sent to the client. This is not correctly done for the diff view, which then results in the diff showing these changes.

### To Reproduce

1. Create an exam with an exercis
2. Start the exam
3. Participate in it
4. In a separate Browser instance as an Instructor make changes to the problem statement as described.
5. See the broken diffs

### Expected behavior

The diffs should always be rendered correctly no matter where they happen

### Screenshots

If the diff is in a task name (same goes for code blocks):
<img width="1092" alt="image" src="https://github.com/ls1intum/Artemis/assets/18218285/f3e859f1-7d27-4fce-9dec-22a5cf44ed97">
If the diff is in a task name and overlaps with the test case names:
<img width="1158" alt="image" src="https://github.com/ls1intum/Artemis/assets/18218285/24316dcb-181a-4619-9eac-c5f00cf3e6e2">

### Which version of Artemis are you seeing the problem on?

develop

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge, Firefox, Other (specify in "Additional context")

### Additional context

Browser independent

**Comment by krusche** [comment]
Some additional aspects:

1. The toggle button between the latest version and the diff should be shown outside the problem statement, so it will always be visible and cannot be hidden when scrolling down
2. We should use some existing html diff libraries (e.g. https://www.npmjs.com/package/htmldiff-js) and not diff the markdown
3. The change notification should use the new subsystem that creates a persisted notification which can be dismissed and re-viewed after some time (similar to exam announcements and time extensions)

**Comment by Strohgelaender** [comment]
Can we close this now that #8461 got merged @coolchock? Or did the PR only fix some of the problems mentioned above?

**Comment by coolchock** [comment]
Yes, all 3 points were resolved.
