### ISSUE TITLE
Deletion of Users only blocks user in GitLab

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#7804]
### Describe the bug

If I delete a user in artemis, this user does't gets deleted in gitlab. The user will only be blocked. If I try to recreate the user afterwards, you will get a silent error (only backend) that the user cannot be created. (e.g., because mail address is already taken).

### To Reproduce

1. Create a user with mail
2. Delete user
3. Verify that the user is Blocked in GitLab Admin Area
4. Try to re-create the user
5. See in the logs.

### Expected behavior

Deletion should delete users from GitLab. Addtionally, the old blocked accounts should be deleted as well (in order to repair the old behavior)

### Which version of Artemis are you seeing the problem on?

6.7.2

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

**Comment by b-fein** [comment]
I guess this issue has two parts that can be implemented separately:

- Users in GitLab should be deleted instead of blocked when deleting them in Artemis.
- When trying to create a new user and one already exists in GitLab with matching username/email combination, reactivate/unblock it and use it again instead of failing.

**Comment by dfuchss** [comment]
If we always delete users, the second should never happen :) But yes, some recovery of failing actions during account creation would be good.

**Comment by b-fein** [comment]
> If we always delete users, the second should never happen

True, but it might still happen for users that are currently blocked but have not been deleted until the change is implemented.

I’m not sure if Artemis should delete all GitLab-blocked users in a migration. It would not be a problem for our instance but depending on how the GitLab is used, the migration might remove data that should have remained: GitLab exclusive for Artemis, vs. one that is also accessed directly. As far as I know, the documentation does not specify that the GitLab has to be exclusive to Artemis, so setups like that could be possible somewhere else.

**Comment by b-fein** [comment]
Maybe the documentation should be extended to clarify that, since after the change a proper user deletion without automatic recovery is going to happen.

**Comment by dfuchss** [comment]
This issue might be releated to #6442 . Anonymization in Artemis is ok, but the users should be deleted in the external services.

**Comment by dfuchss** [comment]
This will not be an Issue with LocalVC anymore :)
