### ISSUE TITLE
`General`: Route to not found page

### ISSUE THREAD

**Issue by florian-glombik** [ls1intum/Artemis#7830]
### Is your feature request related to a problem?

When a route cannot be found there is currently no clear error message but instead just re-routing to the base Url, which requires the user to notice the change of the Url to understand that the route cannot be found.

If the Url change is not noticed it seems like Artemis would not work properly.

Current redirect to base url:
<img width="549" alt="image" src="https://github.com/ls1intum/Artemis/assets/63976129/b1b75873-823f-4ccd-bea9-03f9da97d3bb">

### Describe the solution you'd like

A not found page which
* contains the requested route
* a redirect button to the course overview

**Comment by Strohgelaender** [comment]
Duplicate of #6689
