### ISSUE TITLE
`Programming exercises`: Allow online editor in read-only mode

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#7886]
### Is your feature request related to a problem?

Currently, programming exercises allow the activation of the online editor and/or the offline IDE. This sometimes leads to a conflict in case inexperienced students make submissions in both and then have to solve the merge conflicts.

### Describe the solution you'd like

I would like to be able to activate the online editor in read-only mode if the offline IDE mode is enabled.

This would prevent such conflicts. Additionally,
- this would enable students see the location for static code analysis issues inline,
- students would be able to browse the repository in cases where they don’t have direct access to the version control system (e.g., GitLab using access tokens, local-VCS).

### Additional context

The online editor already supports a read-only mode for the manual assessment and review after the deadline.

**Comment by b-fein** [comment]
Discussion on Slack about an alternative solution:

- LocalVCS supports a read-only view of the repository (#7957):
  ![image (1)](https://github.com/ls1intum/Artemis/assets/64250573/9a31c215-6a3a-4a16-b5c6-f2a0c07a1c2f)
- This feature should be visible for GitLab setups as well.
- The feature may be gated behind a config flag in the server settings so that it can be enabled or disabled by an admin.

**Comment by dfuchss** [comment]
Related to https://github.com/ls1intum/Artemis/issues/5025 . A Read-Only mode would be nice for exam reviews as well :)

**Comment by dfuchss** [comment]
@b-fein Am I right, that LocalVC will also support some reviewing like proposed in #5025 ? (I'm currently cleaning up my issues :) )

**Comment by b-fein** [comment]
I know that LocalVC has some repository viewer built into Artemis. I’d hope this is also enabled for exam exercises. Since I have not used LocalVC so far and especially not in Exam mode, I don’t know. Someone else working in that area might know more.

**Comment by krusche** [comment]
Yes, it's enabled for exams as well. Students can see their own repo and instructors (+ potentially tutors) can see the repo of students similar to how Gitlab and Bitbucket show it.

It also offers a commit history, but currently lacks branch and pull request support. 

Branches (when configured in the respective exercise) will be added soon.

If you miss any other (cool new) features, please let us know

**Comment by dfuchss** [comment]
@krusche Do you plan (or does it already support) https://github.com/ls1intum/Artemis/issues/5025#issuecomment-1118408196 ? This would help the reviewing of exams a lot I guess :)

**Comment by pzdr7** [comment]
Yes, this would be possible. We could check if any feedback items apply to specific lines (like a tutor comment or GenAI feedback) and, if that is the case, offer the option to toggle the in-editor feedback on or off. I'll try a few things and draft up a PR. 👍
