### ISSUE TITLE
Introduce @DiscriminatorOptions for all abstract Entities

### ISSUE THREAD

**Issue by jpbernius** [ls1intum/Artemis#791]
This Annotation results in child entity repositories to not find an entity by id of a different child.
e.g. find a modeling exercise with id of a text exercise.
This case should return 404 instead of trying to cast it.

_Originally posted by @jpbernius in https://github.com/ls1intum/Artemis/pull/762_

**Comment by krusche** [comment]
@DiscriminatorOptions(force = true)

**Comment by krusche** [comment]
I added this to all abstract entities
@madwau please also consider this for your changes for Team Exercise Models

**Comment by madwau** [comment]
@krusche Yes, I will add that annotation to the new models where applicable.
