### ISSUE TITLE
Code-Editor: Height of ace editor is 0 on Safari

### ISSUE THREAD

**Issue by thilo-behnke** [ls1intum/Artemis#797]
### Describe the bug

The ace editor is not visible in the code-editor when a file is selected.
This must be due to the css rendering in Safari (Chrome is working).

#### To Reproduce

1. Go to Overview > Programming Exercise > Open Code Editor
2. Select a file in the file browser
3. Editor doesn't show up in the central panel

#### Expected behavior

Editor should show up, similar to Chrome.

#### Screenshots

![image](https://user-images.githubusercontent.com/28230611/64248548-acae2b80-cf11-11e9-92eb-9bd6e04e68f9.png)

### Environment

<details><pre>
 - OS: Mac OS
 - Browser: Safari
</pre></details>

#### Additional context

n/a

#### Output in Web Console

n/a

**Comment by thilo-behnke** [comment]
I have done some investigation on this issue yesterday with @lovaiible:
After the file content is added to the ace-editor we do a resize on it to make sure the ace-editor adapts to the line number of the file. This does not seem to work for the code-editor in Safari, also when the height is set manually on the `ace-editor` tag, it only resizes to 2 lines (see screenshot in description).

I assume the issue is that we don't remove the ace-editor in the code-editor in case of loading or no file being selected, but **hide it** (https://github.com/ls1intum/Artemis/blob/develop/src/main/webapp/app/code-editor/ace/code-editor-ace.component.html#L16). There could be a timing issue with the resize that is hard to pin down, too (https://github.com/ls1intum/Artemis/blob/develop/src/main/webapp/app/code-editor/ace/code-editor-ace.component.ts).

It would be good if somebody with a Mac could look further into this issue.

**Comment by krusche** [comment]
Resolved with #835
