### ISSUE TITLE
Student score list can't be sorted by last result column

### ISSUE THREAD

**Issue by MaximilianAnzinger** [ls1intum/Artemis#7983]
### Describe the bug

When viewing the score list of an exercise, instructors can't sort by the latest result column.

### To Reproduce

Requires Exercise with multiple participants and results.
1. Log in as an Instructor
2. Navigate to the editing view of the exercise
3. click the `Scores` button to view the list of scores
4. Try to sort the list by the `Last Result` column -> broken

### Expected behavior

The list should be sorted by the latest results, e.g. first build failed, then by increasing percentage (or reversed).

### Screenshots

![Screenshot 2024-02-01 at 10 38 39](https://github.com/ls1intum/Artemis/assets/44003963/7ae66722-1a30-4402-99d4-c99df6b2e57a)

### Which version of Artemis are you seeing the problem on?

6.7.6

### What browsers are you seeing the problem on?

Chrome

**Comment by pzdr7** [comment]
When sorting by the last result, where should the submissions without a score be?
