### ISSUE TITLE
Programming exercise: UI unintuitive / not self-explanatory

### ISSUE THREAD

**Issue by Garfield96** [ls1intum/Artemis#801]
### Is your feature request related to a problem?
I recently started using Artemis and had some problems during exercise creation/editing, because multiple input fields have no clear description:
* Create new Programming Exercise:
  * What is the difference between "Title" and "Short Name"? Obviously "Short Name" should be a short representation of "Title" but why is this necessary and there is this "Short Name" used instead of the "Title"?
  * There is no warning that some fields can not be edited after creation, e.g. "Short Name" is not changeable.
  * Can a programming exercise belong to more than one category? Is it possible to enter a comma-separated list of categories?
  * What happens if the user clicks on "Save"? After using it for the first time I figured out Artemis creates all necessary repositories automatically, but a small note above "Save" would be great.
* Edit Programming Exercise:
  * What does "Optional: Notification about changes" mean? Is this notification send to all people registered in the course or is it only displayed when the user opens Artemis? What happens if this field is empty?

All these questions can be solved by trial and error, but this is not optimal.

### Describe the solution you'd like
Add descriptions in the form of paragraphs and use "question-circle" for more input fields.

### Describe alternatives you've considered
Add a link to documentation which contains all information.

**Comment by krusche** [comment]
Thanks for pointing out these issues. Until now, only a few people have used this dialog, so we did not put too much effort in making it perfectly understandable for new users. 

We will try to clarify all these questions directly in the user interface in an intuitive way in the future. I have some ideas in mind:
- Change the `Save` button to `Create` and add some information when hovering over it.
- Show a preview of the 3 repo name and 2 build plan names that are generated using the course short name + exercise short name. When leaving the text field of the short name, we can also check if this name is still available on the version control and continuous integration server
- Add some additional info boxes to communicate what certain options mean.

Regarding your questions: 
* The title can be changed. It is displayed in Artemis to the students
* The short name is used to create a unique name for the build plan and git repos. Therefore it is not changeable after the creation any more.
* You can use multiple categories in an exercise (e.g. homework), they will be visible to students. You are free in defining them. It might be a good idea to use them consistently.
* During edit you can notify students about changes (e.g. deadline extensions, change in the problem statement, etc.). They will then see a notification in the upper right corner. This only makes sense after an exercise has started. It is optional. If you leave it empty, no notification will be triggered, e.g. if you only fix a typo in the problem statement, you might not want to notify all students in your course.

**Comment by Garfield96** [comment]
Thank you for the clarification.

> During edit you can notify students about changes (e.g. deadline extensions, change in the problem statement, etc.). They will then see a notification in the upper right corner. This only makes sense after an exercise has started. It is optional. If you leave it empty, no notification will be triggered, e.g. if you only fix a typo in the problem statement, you might not want to notify all students in your course.

This is problematic because not all students will look into Artemis after the change and some students might not recognize that the exercise changed before the deadline. It would be reasonable to add an option to send an additional email notification.

**Comment by krusche** [comment]
I agree, an email notification would be good in certain cases. However, at the moment, Artemis does not support email notifications, but we will implement this in the future. So for now, if there is a really important change after the exercise release and you fear that students do not look into Artemis, you need to send the email manually.

**Comment by ungaralex** [comment]
The UI should now be much more intuitive. @Garfield96 have you had the chance to use the latest deployed release? There should now be a lot more tooltips and the whole lifecycle/timeline of an exercise should be much more self-explanatory

**Comment by Garfield96** [comment]
@ungaralex Thank you very much. The UI is now much easier to understand. 

The only additional change I would like to see is a tool-tip for the notification field (see issue text).

Unfortunately, the new UI introduced a little bug. The blue line of the timeline is misaligned for small window sizes:
![image](https://user-images.githubusercontent.com/15248220/67045847-60205780-f12f-11e9-83d7-c4900526cbe1.png)

**Comment by krusche** [comment]
@ungaralex please have a look at the last comment if you have time

**Comment by krusche** [comment]
@ungaralex could you have a look here so that we can close this issue soon? Thanks
