### ISSUE TITLE
Clone repository button on exercise detail view does not work

### ISSUE THREAD

**Issue by Strohgelaender** [ls1intum/Artemis#8024]
### Describe the bug

When viewing the programming exercise details as an instructor, the clone repository button has no content:
![grafik](https://github.com/ls1intum/Artemis/assets/26540346/eb43e93e-bef6-4ae3-9263-6a736a785844)

### To Reproduce

1. Navigate to Course Management -> Exercises -> Exercise Details
2. Click on "Clone Repository" (next to one of the 3 repositories)
3. See that the content is empty

### Expected behavior

The repository link should be displayed.

### Which version of Artemis are you seeing the problem on?

6.8.0

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
ERROR TypeError: null has no properties
    Do detail-overview-list.component.html:9
```

**Comment by milljoniaer** [comment]
This issue is caused by a type error within programming detail pages, it will be closed with the above linked PR
