### ISSUE TITLE
`Exam mode`: Allow students to see if their attendance was checked

### ISSUE THREAD

**Issue by MaximilianAnzinger** [ls1intum/Artemis#8036]
### Is your feature request related to a problem?

Our students cannot verify if their attendance during an exam has been recorded properly. This leads to confusion during the examination and possible arguments after the conduction.

### Describe the solution you'd like

The exam view should include a checkmark or even a warning at the end of the exam, to signal whether their attendance was checked or not.

A very nice addition would be a warning when submitting the exam although the attendance has not been checked.

**Comment by PTheocharis** [comment]
Hello! I am a beginner in coding and I think I would like to contribute to the project. I am more focused on good first issues of course, do you think I can handle this one or you have any other recommendations in terms of programming?
