### ISSUE TITLE
JPlag Version 5.0.0 Release

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#8062]
### Describe the solution you'd like

JPlag 5.0.0 has been released yesterday. Since JPlag has some breaking changes, this update might need manual actions :)

**Comment by Strohgelaender** [comment]
JPlag v5 uses Java 21, Artemis is still on Java 17. We need to first finish the Upgrade to Spring 3 (which is then compatible with Java 21) before we can use version 5.

```
 bad class file: /de/jplag/Submission.class
    class file has wrong version 65.0, should be 61.0
```
