### ISSUE TITLE
Programming Exercises: Show build output even for successfull builds

### ISSUE THREAD

**Issue by pogobanane** [ls1intum/Artemis#8138]
### Is your feature request related to a problem?

If builds/tests succeed accidentally, there seems to be no way to show any build output.

### Describe the solution you'd like

The code editor should really show "Build Output" not only on failed CI runs. 

We used to be able to access build output without the code editor by accessing the bamboo plan. It would be nice to have similar button in the "Course Management > Exercises > My Execise" view near the  template and solution result.

**Comment by julian-christl** [comment]
Fixed in #8170, according to PR description.
