### ISSUE TITLE
Clone-Link broken

### ISSUE THREAD

**Issue by JosefSchoenberger** [ls1intum/Artemis#8162]
### Describe the bug

The link you get for cloning a repository seems to be broken (at least for already-existing repos – I cannot speak for new repos). Instead of a hostname, they contain `undefined`, e.g. `undefinedgit/GBS2324BASH/gbs2324bash-go42tum.git`

Edit: Apparently, this only occurs on `artemis.ase.in.tum.de`, not `artemis.ase.cit.tum.de`.

### To Reproduce

1. Go anywhere where a “Clone Repository” button exists (e.g., a student's view of an exercise or the instructor's exercises overview)
2. Click on “Clone Repository”
3. Notice that the URL is malformed, starting with an “undefined”.

### Expected behavior

The clone URL should be valid.

### Screenshots

![grafik](https://github.com/ls1intum/Artemis/assets/82521952/83236648-ab80-471d-a2a5-4846514fc73a)

### Which version of Artemis are you seeing the problem on?

6.9.0

### What browsers are you seeing the problem on?

Firefox

### Additional context

There is no relevant log output. The only error I can see is pertains to a cross-origin request violation for sentry.ase.in.tum, which I see on all Artemis pages.

**Comment by JosefSchoenberger** [comment]
Ok, removing the entire brower state seems to resolve the issue. A bit weird, but I guess a viable workaround.

**Comment by krusche** [comment]
You should use artemis.cit.tum.de
