### ISSUE TITLE
Create generic button client component with optional icon, loading & disabled state

### ISSUE THREAD

**Issue by thilo-behnke** [ls1intum/Artemis#817]
### Describe the solution you'd like

Create a simple, reusable button component. Should behave similar to: https://ant.design/components/button/

- loading state
- disabled state
- optional icon left to the text
- output for button click
- styled with bootstrap CSS by providing a type (e.g. Error or Success)

**Comment by jpbernius** [comment]
Not quite sure if it is possible to somehow also address #611?

**Comment by krusche** [comment]
> Not quite sure if it is possible to somehow also address #611?

This is a long standing issue in Artemis and it would be great if we could resolve it.

**Comment by thilo-behnke** [comment]
> Not quite sure if it is possible to somehow also address #611?

I'll look into it.

**Comment by thilo-behnke** [comment]
From my point of view the issue with the links is an html/css issue: https://github.com/ls1intum/Artemis/issues/611#issuecomment-530435846

It would just be a bit of work to wrap the buttons into `<a>`s and style them properly. It makes more sense to me then implementing complicated logic to dynamically create a button or a tag.
