### ISSUE TITLE
Changed programming exercise deadline not applied to repositories

### ISSUE THREAD

**Issue by LordMuetze** [ls1intum/Artemis#8176]
### Describe the bug

I extended the deadline of a programming exercise (before the transfer to integrated code lifecycle) und it seems like the change wasn't applied to the student repositories as most of student repositories were locked (after the transfer, after the original deadline).

I'm not sure if this was caused by the transfer to the new integrated code lifecycle or if it is a general problem with it.

### To Reproduce

1. Create programming exercise with a deadline.
2. Create a student assignment.
3. Extend the exercise deadline.
4. Try to push to a student repository after the orginial deadline. / Open it using the online editor.
5. See bug: Error 500 (using Git)  /  in online editor: 'Repository locked' 

### Expected behavior

Students can work regularly at exercises before the new and after the original deadline.

### Which version of Artemis are you seeing the problem on?

6.9.1

### What browsers are you seeing the problem on?

Chrome

**Comment by krusche** [comment]
We do not lock and unlock repositories any more, but it could be the that the participation status in this case is not correct any more. Thanks for reporting the issue, we will investigate it
