### ISSUE TITLE
Feature toggle integration for client

### ISSUE THREAD

**Issue by thilo-behnke** [ls1intum/Artemis#818]
### Is your feature request related to a problem?

Sometimes our PRs get very large, because we can't merge a client feature without the complete server implementation.
In some cases we can merge the server side first, but that's also not always ideal.

Good example: https://github.com/ls1intum/Artemis/pulls
Here the client interface is visible, even though the server implementation is not done completely.

### Describe the solution you'd like

It would be great if we would have a way we can merge unfinished features, but hide/remove them from our users.
This could be done with a feature toggle service in the client: https://devblogs.microsoft.com/premier-developer/angular-how-to-implement-feature-flags/

We could limit the hiding/removing of features to certain roles, so that Admins still see all features that are currently deployed.

**Comment by krusche** [comment]
We have added this recently for programming exercises and it can be easily extended to other cases
