### ISSUE TITLE
`Programming Exercises`: The personal clone URL starts with undefined

### ISSUE THREAD

**Issue by maximiliansoelch** [ls1intum/Artemis#8300]
### Describe the bug

After the student started the exercise, cloning was not possible as the clone URL started with undefined: `undefinedgit/IOS24INTROS6E1/ios24intros6e1-xx11xxx.git`

Reloading the page did not help. Only after opening the exercise in another browser, the correct URL for cloning was displayed.

### To Reproduce

Occurred for multiple students during the intro course, not sure how to exactly reproduce this.

### Expected behavior

The client should show a valid clone URL for all students.

### Which version of Artemis are you seeing the problem on?

6.9.5

### What browsers are you seeing the problem on?

Chrome

**Comment by Strohgelaender** [comment]
See #8162, seems like a browser cache issue.

**Comment by krusche** [comment]
It's still unclear how the issue can happen due to browser caches. I think we should still try to fix it
