### ISSUE TITLE
Maven exercise template has build error

### ISSUE THREAD

**Issue by LordMuetze** [ls1intum/Artemis#8308]
### Describe the bug

When creating a programming exercise with maven the exercise template leads to a build error in template and solution: net.bytebuddy:byte-buddy:jar:1.12.21 could not be resolved

I tried to find any bytebuddy dependency in the pom files however couldn't find any. 

### To Reproduce

1. Go to 'Create programming exercise'
2. Setup the exercise with these options: 
- Maven
- No aux. repo
- No exemplary dependencies
- No seq. test runs
- No submission policy
- Show test names to students
- No SCA
- No adjusted build plan
3. Save
4. See the identical errors on solution and template

### Expected behavior

No errors/exceptions in exercise template.

### Screenshots

![image](https://github.com/ls1intum/Artemis/assets/30774791/4d4276da-58b3-43d2-bec9-6ac0c9437ccd)

### Which version of Artemis are you seeing the problem on?

6.9.5

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

(this is the full output, which is also ssems cut off in reality)

```shell
[ERROR] Failed to execute goal on project Gestaffelte-Tests-Tests: Could not resolve dependencies for project test1000:Gestaffelte-Tests-Tests:jar:1.0: The following artifacts could not be resolved: net.bytebuddy:byte-buddy:jar:1.12.21 (absent): Could not
```

**Comment by Strohgelaender** [comment]
Could the be a network error? Maybe the maven repository was down for a moment? Version 1.21.21 definitely exists: https://mvnrepository.com/artifact/net.bytebuddy/byte-buddy/1.12.21
