### ISSUE TITLE
Delete dialogs allow incorrect titles

### ISSUE THREAD

**Issue by rstief** [ls1intum/Artemis#8313]
### Describe the bug

The "Confirm delete operation" dialog allows to delete objects for certain names (e.g. "a+", ".*", ...), even when the entered string does not match the name.

This seems to be caused by comparing the entered names as a regex (e.g. "a+" allows the input of arbitrarily many "a"s while ".*" allows the input of anything)

### To Reproduce

This works for any delete dialog. One example are competencies
1. Go to *Course Management* -> *Competencies*
2. Create a new competency with the name (title) ".*"
3. Click on delete -> See that you can enter any string and the delete button does not disable

### Expected behavior

The delete button in the delete dialog should only enable when entering the exact names of the object that should be deleted.

### Screenshots

![image](https://github.com/ls1intum/Artemis/assets/118574504/c05f376f-127f-4754-b6a3-67b184de40d8)

### Which version of Artemis are you seeing the problem on?

7.0.0

### What browsers are you seeing the problem on?

Chrome

**Comment by zhngharry** [comment]
Anyone tackling this issue yet? I'm trying to start contributing to Artemis and think this Issue might be a nice place to start.

**Comment by zhngharry** [comment]
How would I go about requesting a Review for my PR? In the guidelines it says to actively look for a review, but directly tagging a person seems a bit too much for me... whats the usual process here?

**Comment by zhngharry** [comment]
Also maybe we can discuss here, which item names allow what pattern. As mentioned in the PR, to fix this issue I have implemented a validation on the title itself so that no items with strings like ".*" can be created in the first place. 

For now, it is the same rule/regex for every item: Only alphanumeric, spaces and dashes

Should some items allow other special characters too?

**Comment by rstief** [comment]
Hey @zhngharry, thanks for your interest! Most of the communication happens on slack, but I think it is invite-only. There you can DM people you know, post your PR into channels like artemis-test and participate in testing sessions (scheduled by you or other devs).
I've also asked there how you could best get in contact (as I'm not sure how communication works if you are not writing your thesis at the ls1 like I am). I'll get back to you as soon as I know more :)

**Comment by rstief** [comment]
I've also taken a quick look at your PR, I have two things to add here:
To get access to the test servers you would also need to get in contact with the dev team 😅 Again - I'll let you know when they get back to me.

For how you solved the problem, I think this is not the way to go. Restricting the titles for all objects where we want to use the delete dialog is prone to errors in the future (as developers using the delete-button-directive) and causes problems with simple titles such as "Topic X (optional)"
I think you should rather take a look at if it is possible to fix how the delete-dialog (or whichever of its child components causes this error) :)

**Comment by rstief** [comment]
Ok, so just send an E-Mail to Prof. Dr. Stephan Krusche (krusche@tum.de) and he will add you to the slack space. You can then also just DM me if you need help 😄 I'll probably react faster to messages there

**Comment by zhngharry** [comment]
@rstief Thanks for reaching out and even contacting the team for me! Regarding the PR, I will change it up to fix like requested. Sorry for the confusion/troubles and thanks again 😄

**Comment by rstief** [comment]
No worries! Feel free to reach out anytime 😁
