### ISSUE TITLE
Superfluous whitespace in Code Editor for Student's submission

### ISSUE THREAD

**Issue by mallgaier** [ls1intum/Artemis#8375]
### Describe the bug

When viewing a student's submissions in the online editor, there is a superfluous whitespace in the heading within the Point's brackets. 
Note: This problem is not present in the online editor when editing the exercise in the code editor. It seems to be limited to the situation, when the student's submission is viewed in the online editor. 

### To Reproduce

1. Go to an Programming Exercise with an student's submission
2. Click on Scores
3. Open the student's submission in the Online editor

### Expected behavior

The whitespace should be removed

### Screenshots

![Screenshot 2024-04-11 154413](https://github.com/ls1intum/Artemis/assets/94070506/70590be5-54db-43f2-bede-a1152acbfa8d)

### Which version of Artemis are you seeing the problem on?

6.9.6.

### What browsers are you seeing the problem on?

Microsoft Edge

### Additional context

Thanks for @Hialus and @MarkusPaulsen for suggesting to report the bug :)

**Comment by mallgaier** [comment]
Hallo @JanaNF :)

**Comment by varungole** [comment]
Can I work on this?
