### ISSUE TITLE
Programming Exercise: Package Name for non-Java exercises

### ISSUE THREAD

**Issue by pstoeckle** [ls1intum/Artemis#8419]
### Describe the bug

One cannot create anymore a programming exercise with a non-Java programming language. The validation shows a error that the package name is missing

### To Reproduce

1. Course Management View
2. Exercises 
3. Create Exercises
4. FIll out the data fields
5. Select non-java programming language, e.g., python.
6. Try to create the exercise

### Expected behavior

Just create the exercise

### Screenshots

<img width="888" alt="Screenshot 2024-04-17 at 10 54 25" src="https://github.com/ls1intum/Artemis/assets/5854768/c671c073-ea80-4e30-a477-f86bc4ed5430">

<img width="276" alt="Screenshot 2024-04-17 at 10 54 36" src="https://github.com/ls1intum/Artemis/assets/5854768/6d1df963-86a7-4a3a-a8a5-ca90b5ec4d00">

### Which version of Artemis are you seeing the problem on?

7.0.0

### What browsers are you seeing the problem on?

Chrome

**Comment by b3n3d17** [comment]
I can confirm, I have the same issue.

**Comment by pzdr7** [comment]
See #8394

**Comment by Strohgelaender** [comment]
Thanks for reporting the issue. We already fixed the problem and you will be able to create Python exercises again with version 7.0.1 at the end of the week.
