### ISSUE TITLE
Allow force pushes to template, solution, auxiliary and test repos for instructors

### ISSUE THREAD

**Issue by maximiliansoelch** [ls1intum/Artemis#8469]
### Is your feature request related to a problem?

As an instructor, it is currently not possible to force push to template, solution, auxiliary and test repos. 

### Describe the solution you'd like

Allow force pushing for instructors to template, solution, auxiliary and test repos.

**Comment by krusche** [comment]
We discussed this in the programming team and do not want to allow this
