### ISSUE TITLE
Lock student respositories after the due date passes 

### ISSUE THREAD

**Issue by thilo-behnke** [ls1intum/Artemis#847]
### Is your feature request related to a problem?

It should be possible to lock the student repositories after the due date passes.
The reason is that in some cases students should not be able to add new commits after the deadline as tutors will download the repo to rate the student's submission locally. 

### Describe the solution you'd like

A quick approach would be to schedule this locking process if the dueDate and buildAfterDueDate dates are set. The scheduler would run with the expiration of the dueDate and send REST requests to Bitbucket to remove the write permissions of the student.

**Comment by krusche** [comment]
This issue was solved by #867
