### ISSUE TITLE
Remove the old course navigation from the client (/courses)

### ISSUE THREAD

**Issue by thilo-behnke** [ls1intum/Artemis#851]
### Describe the bug

We have switched from the old /courses area to the new /overview course structure.
We should now remove the old routes as they are not used anymore and increase the bundle size unnecessarily.

The old /courses area is now also broken, when you switch between it and e.g. course administration, console errors appear and the app breaks:

```
main.f663bb909c8fb3c0260f.bundle.js:2 ERROR TypeError: Cannot read property '0' of undefined
    at Object.updateDirectives (main.f663bb909c8fb3c0260f.bundle.js:2)
    at Object.updateDirectives (main.f663bb909c8fb3c0260f.bundle.js:2)
    at Gv (main.f663bb909c8fb3c0260f.bundle.js:2)
    at l_ (main.f663bb909c8fb3c0260f.bundle.js:2)
```

#### To Reproduce

1. Go to /courses

**Comment by krusche** [comment]
We still use this as landing page for online courses which open Artemis over LTI. We first need to migrate this to the new overview page before we can remove the old /courses page

**Comment by thilo-behnke** [comment]
The bug with the page was resolved in the linked PR.
