### ISSUE TITLE
'Plagiarism checks': UI bug

### ISSUE THREAD

**Issue by kerstinandree** [ls1intum/Artemis#8528]
### Describe the bug

The clean-up button on plagiarism checks results in a bug in the UI (see the screenshot)

### To Reproduce

1. Run a plagiarism check
2. Clean up 
3. Verify you get the same box as in the screenshot 

### Expected behavior

Should not have this error in the UI

### Screenshots

![image](https://github.com/ls1intum/Artemis/assets/29281795/f2b52714-8f6c-4e6f-8fdf-75b6abfc77e7)

### Which version of Artemis are you seeing the problem on?

7,0,2

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by zhngharry** [comment]
Could someone assign this issue to me?

**Comment by zhngharry** [comment]
Ive tried to debug the issue, but it seems like it is deeply rooted somewhere else, possibly not even in the Client Side. It seems like the doesnt appear on Modeling Plagiarism Results. I'm not familiar with the backend at all, could someone from the backend double check this?
