### ISSUE TITLE
Issues with the notification system (course notifications)

### ISSUE THREAD

**Issue by thilo-behnke** [ls1intum/Artemis#854]
### Describe the bug

When working with the notification system in https://github.com/ls1intum/Artemis/pull/850, I noticed 2 severe bugs with the course notifications:

1) The subscription is only setup in the course-service.findAll and .query methods ((https://github.com/ls1intum/Artemis/blob/develop/src/main/webapp/app/entities/course/course.service.ts#L70)). This means if you load any other page than the course-administration or course-overview, you won't see any notifications in the popover at the top. The problem seems to be that the client is not aware of existing course ids before this call is executed.
2) The subscription sometimes is set up twice. I can't find the concrete issue, but made a hotfix in the mentioned PR: https://github.com/ls1intum/Artemis/pull/850/commits/d3e4249d3c41b55bbf65ad066977f71ace03e6c4. Maybe this is the case if you have visited both the course-administration and course-overview pages.

#### Screenshots

![image](https://user-images.githubusercontent.com/28230611/65624421-25ad1a00-dfca-11e9-8efe-d86233ef9f9f.png)

**Comment by tiffca** [comment]
I don't think this is reproducible in Test env. 
1. I received the "exercise updated" notifications even in a course exercises view as a student. However maybe I am not understanding the issue clearly 
2. I was not able to reproduce duplicate exercise updated notifications
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/63906424/82058928-adfd3e00-96c5-11ea-8738-60b8083f68dc.png">
