### ISSUE TITLE
Can't scroll down on the page of tutorials in GAD (IN0007)

### ISSUE THREAD

**Issue by OBrook** [ls1intum/Artemis#8549]
### Describe the bug

I can't scroll down in the page of tutorials and check what and when will be. I tried to do it from several browsers- from Google Chrome, Microsoft Edge and Safari on my phone.

### To Reproduce

1. [Go to this page of tutorials in GAD](https://artemis.cit.tum.de/courses/346/tutorial-groups?filter=all)
2. Try to scroll down
3. See error

### Expected behavior

Normal scroll down

### Which version of Artemis are you seeing the problem on?

7.0.3

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge

**Comment by noahlokocz** [comment]
Same here on MacOS (14.4.1), tested on Firefox (125.0.3) and Safari (17.4.1).
