### ISSUE TITLE
Replacement of the old translation feature

### ISSUE THREAD

**Issue by eceeeren** [ls1intum/Artemis#8561]
### Is your feature request related to a problem?

As a new developer in Artemis, when I need to change a translation, I always get confused whether to use artemisTranslate or jhiTranslate as the translation feature until I was warned. This naming should be changed completely to end the confusion.

### Describe the solution you'd like

I suggest that all of the string with format

`<span>{{ 'artemisApp.xxx...' | artemisTranslate }}</span>`

to be changed to 

`<span jhiTranslate="artemisApp.xxx..."></span>`
 
 And to get each of them tested individually.

**Comment by rstief** [comment]
Just a note: We can't replace all occurrences of `artemisTranslate` see the example in the [documentation](https://docs.artemis.cit.tum.de/dev/guidelines/client.html#localization).

If we want to replace the translations, I think we should:
- **Make sure to only replace cases where there is ONLY {{ 'artemisApp.xxx...' | artemisTranslate }} BETWEEN THE TAGS!!! jhiTranslate removes everything else between the tags where it is used!!!**
- use a well-tested regex expression (and not do it by hand!!!)
- thoroughly code review it, as changes of this scale are not really testable, see #8139

**Comment by schastlivcev** [comment]
Hi, just thought about the solution, possible regex expressions may be: `(<.+)> ?\{\{ '(artemisApp\.[\w\d.-]*)' \| artemisTranslate \}\} ?(<\/.+>)` to find such cases, `$1 jhiTranslate="$2">$3` to replace to follow new guidelines. There are about 900 occurrences. Maybe it will help someone or I'll do it by myself later (I'll write about it in that case)
