### ISSUE TITLE
Quiz results are not saved 

### ISSUE THREAD

**Issue by mhunter02** [ls1intum/Artemis#8567]
### Describe the bug

# We conducted a quiz, but after the quiz, the results were not loaded, and it shows:

### The quiz settings are the following:
![image](https://github.com/ls1intum/Artemis/assets/61734972/7bc24063-1d19-4baf-a06f-f5584384d3d2)

### To Reproduce

1. Go to https://artemis.ase.in.tum.de/course-management/335/quiz-exercises/13733
3. Click on **Statistics** 
4. Scroll down to **Grading**
5. See error **No results are present**

### Expected behavior

See statistics, students get results

### Student point of view:
- Missed due date
![image](https://github.com/ls1intum/Artemis/assets/61734972/fbfb9df1-9006-4e91-9d0b-1f2d7fcddccf)

### Instructor point of view:
- Here, you will see no statistics are loaded:
![image](https://github.com/ls1intum/Artemis/assets/61734972/5ba562a9-6771-40e9-8abc-2c00a2663a57)
- Here is the Participation
![image](https://github.com/ls1intum/Artemis/assets/61734972/f65370f3-2795-4797-a98c-573aede001e9)

Although overall statistics view show that the students have participated:
![image](https://github.com/ls1intum/Artemis/assets/61734972/4420bf04-a1e4-476d-98d1-cfef3af3c90e)

Even more weird is that after **Release of practice**
The practice participations seem to be counted (not shown in the Participations view), but statistics get updated:
![image](https://github.com/ls1intum/Artemis/assets/61734972/153ae54f-c60e-471e-8ab1-99de59a0f784)

### Which version of Artemis are you seeing the problem on?

7.0.4

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge, Firefox, Other (specify in "Additional context")

### Additional context

Artemis application

**Comment by mhunter02** [comment]
I saw that even though I did not participate in the official conduction time (I did it as practice), I can see the "View result" button. Which I should not
After clicking, I see an empty page:
![image](https://github.com/ls1intum/Artemis/assets/61734972/414f34bb-3910-479a-a159-993cd8ad59c3)

**Comment by krusche** [comment]
We are working on a quick fix for the issue. We restarted the production system and it seems that for now the quizzes work again. We will investigate why they did not work and update the code to make it more reliable

**Comment by jerhard** [comment]
Is there a chance to recover failed participation from the data base? E.g. for [this exercise](https://artemis.ase.in.tum.de/course-management/351/quiz-exercises/13683) where no participations were registered for the 9th and 10th of May.
If there is no way to recover the participations, we will find another solution for our course.

**Comment by FelixTJDietrich** [comment]
Was this issue related to/fixed by #8703?

**Comment by krusche** [comment]
this was recently fixed
