### ISSUE TITLE
Make Direct Messages Optional in "Messages" Module and Delete "Communications" Module

### ISSUE THREAD

**Issue by egekurt123** [ls1intum/Artemis#8585]
### Context

We are currently maintaining two separate modules: "communications" and "messages". The "communications" module is our legacy system, which we intend to delete. However, the "messages" module includes a direct messages / group chats feature that not all users wish to utilize.

### Solution

In the future, we want to provide three options:

1. **No Communication:** Disable all communication features.

2. **Announcements + Exercise / Lecture Channels:** Enable only announcements and exercise/lecture channels (previously part of the "communications" module).

3. **All Channels and Chats:** Enable all features, including direct messages and group chats (previously part of the "messages" module)

With third Option **All Channels and Chats**  being the default setting

Once the new modes are implemented and thoroughly tested, remove the legacy "communications" module.

**Comment by dfuchss** [comment]
Sounds good. It's important for us to be able to disable DMs and custom Group Chats. We want to be able to moderate the channels. Thus, Option (2) is what we need :)

**Comment by dfuchss** [comment]
Additionally, we need a migration for existing courses. We don't want to loose any chat in the existing courses :)

**Comment by egekurt123** [comment]
> Additionally, we need a migration for existing courses. We don't want to loose any chat in the existing courses :)

We already have a common database for the communication and messaging modules, so this shouldn't be a problem. 👍

**Comment by PaRangger** [comment]
This issue was addressed, since the course management page allows you now to specify whether you want to enable/disable the communication module, wheter or not private messages are allowed.

<img width="317" alt="Bildschirmfoto 2024-11-29 um 22 14 53" src="https://github.com/user-attachments/assets/167d9a95-1e35-4307-8f78-ce3e0b301b96">
