### ISSUE TITLE
`Communications`: New UI Design for Messages and Threads

### ISSUE THREAD

**Issue by egekurt123** [ls1intum/Artemis#8591]
## Context
This issue is to propose the implementation of a new UI design created by  @JohannesWt, aimed at modernizing our current user interface to enhance the user experience and keep our platform visually and functionally competitive.

### Problem  
The current UI design, while operational, lacks modern design elements and could greatly benefit from a refresh to meet current user expectations and design trends.

The new design:
- A clean, minimalist layout that emphasizes usability and aesthetic appeal
- Modern typography that improves readability and user engagement
- A vibrant, updated color palette that is both inviting and professional

### New Design for Messages
![Screenshot 2024-05-14 at 15 48 27](https://github.com/ls1intum/Artemis/assets/69898283/1f7a7842-92a5-4424-af6d-f504ee7a64f2)

#### Option 1: Threads Covering the Whole Chat Area
![Screenshot 2024-05-14 at 15 47 44](https://github.com/ls1intum/Artemis/assets/69898283/f1f446d3-38d3-4998-95ac-4f323b8d6143)

#### Option 2: Threads on the Side
![Screenshot 2024-05-14 at 15 50 39](https://github.com/ls1intum/Artemis/assets/69898283/32d73aca-8d18-47ce-8e17-97421d600b5d)

**Comment by PaRangger** [comment]
This has been partially implemented, but I think since there were various new changes to the visual design of the module I will close this for now.
