### ISSUE TITLE
`Programming exercises`: Download Repository button broken for auxiliary repository on localCI 

### ISSUE THREAD

**Issue by florian-glombik** [ls1intum/Artemis#8605]
### Describe the bug

When creating a new programming exercise with an auxiliary repository, the download repository functionality does not work (the repository does not seem to be created by default by localCI)

### To Reproduce

* 1 instructor

1. Create a new programming exercise
2. Edit the programming exercise, create an auxiliary repository
3. Try to download the auxiliary repository
4. See that you will receive an error message in the network tab but not an alert in the client
5. See that no auxiliary repository was created

### Expected behavior

1. An alert should be displayed for the error in the network tab

(2. The download should work for localCI - maybe it would be possible to create / delete the auxiliary repository according to the changes in the UI?)

### Screenshots

![auxRepoDownloadButtonDoesNotWork](https://github.com/ls1intum/Artemis/assets/63976129/bb56fc18-0c82-456d-baee-abe23c8e2836)

### Which version of Artemis are you seeing the problem on?

7.1.0

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
{
    "headers": {
        "normalizedNames": {},
        "lazyUpdate": null
    },
    "status": 500,
    "statusText": "Internal Server Error",
    "url": "http://localhost:9000/api/programming-exercises/153/export-instructor-auxiliary-repository/19",
    "ok": false,
    "name": "HttpErrorResponse",
    "message": "Http failure response for http://localhost:9000/api/programming-exercises/153/export-instructor-auxiliary-repository/19: 500 Internal Server Error",
    "error": {}
}
```

**Comment by iyannsch** [comment]
@florian-glombik I tested out the auxiliary repo download for both an admin and an instructor and could **not** verify your issue. It worked in both times. 

My `application-local.yml` does contain the following, which might help you fix the problem locally.

> version-control:
>         local-vcs-repo-path: ./../local-vcs-repos
>         url: http://localhost:8080
>         ssh-template-clone-url: ssh://git@localhost:7921/

Let me know if I can investigate and help solve this problem any further :)

**Comment by florian-glombik** [comment]
@iyannsch I refined the steps to reproduce, this only seems to occur when editing a programming exercise and adding an auxiliary repository there.
