### ISSUE TITLE
`Teams`: Change the deadline for one team is not working

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#8610]
### Describe the bug

We extended the deadline to one team in a text exercise. However, the student could not see the button to start the exercise. 

### To Reproduce

1. Create a text exercise for teams
2. In the participation tab, extend the individual deadline to one team
3. As a team member, verify that you cannot see any button to start the exercise or open the text editor (see the screenshot)

### Expected behavior

The student member of the team who was extended the deadline should be able to do the exercise. 

### Screenshots

![image](https://github.com/ls1intum/Artemis/assets/88991954/6cf1823c-e653-49b2-b95a-3ab4b03e86b7)

### Which version of Artemis are you seeing the problem on?

7.0.5

### What browsers are you seeing the problem on?

Chrome

**Comment by EneaGore** [comment]
This seems to be a problem for individual excersies too. It only happens if the student/team has not participated before the due date but tries to start the exercise after, then the individual deadline is changed.
