### ISSUE TITLE
Running exercise is shown as ‘Future’

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#8618]
### Describe the bug

An already active exercise is shown as ‘Future’. This is confusing students since they can already participate.

### To Reproduce

Not sure, does not seem to affect all exercises. See the screenshots for the example configuration where this happen.

### Expected behavior

The exercise is shown in the ‘Current’ section.

### Screenshots

Student view:
The ‘Participate in Exercise’ button at the top of the page (not shown) works, though.
![Screenshot](https://github.com/ls1intum/Artemis/assets/64250573/1a482b41-6058-49fe-8a2a-7c6e6ef93b01)
Also not shown on start dashboard page:
![image](https://github.com/ls1intum/Artemis/assets/64250573/a6d1088a-ec1d-4c2e-8bf5-9e1b938791c1)
Timeline: 
![image](https://github.com/ls1intum/Artemis/assets/64250573/77850fd5-6bef-4e38-8b2f-534bf619cd60)

---

Timeline for another exercise in another course that is working as expected:
![image](https://github.com/ls1intum/Artemis/assets/64250573/7a4c8cf1-cdc3-408b-bbbe-e40ab7489de1)

### Which version of Artemis are you seeing the problem on?

7.0.5

### What browsers are you seeing the problem on?

Chrome, Firefox

### Additional context

We observed the problem already in Artemis version 6.9.6 before the upgrade.

**Comment by JohannesStoehr** [comment]
Currently all exercises with a due date that is further away than 7 days is considered "future". E.g. when a course uses learning paths and already releases all exercises at the start of the course.
I also talked to @rabeatwork about that, but we did not yet find a good solution. Do you have suggestions?

**Comment by b-fein** [comment]
For me ‘Future’ means that the student cannot do anything with the exercise right now. Especially combined with the ‘No exercise planned’ it looks to a student like there is nothing available in the course at the moment.
I guess I’m not alone being confused since at least two students and a colleague also asked about it.

I personally would mark *all* exercises that students can work on as ‘Currently Running’ or ‘Available’ to indicate that students can work on them. If I remember correctly, there also is a special marker for ‘Due Soon’ which would highlight important ones to work on in any use case (with and without learning paths).
