### ISSUE TITLE
`Programming exercises`: Ocaml template solution does not fulfill all requirements

### ISSUE THREAD

**Issue by florian-glombik** [ls1intum/Artemis#8632]
### Describe the bug

When creating a new Ocaml programming exercise, the solution result is not 100%; as far as I am aware, this should always be the case for the template solution.

### To Reproduce

1. Create a new programming exercise with the programming language `Ocaml`
2. Wait for the template and solution build to complete
3. See that the solution build will not be 100%

### Expected behavior

The solution result should be 100% when creating a new exercise.

#### Programming exercise details page
![image](https://github.com/ls1intum/Artemis/assets/63976129/4fa04aa0-e089-431c-9ce0-a9e97a482fd0)

##### Failing Details
![image](https://github.com/ls1intum/Artemis/assets/63976129/8121dc70-1856-47bd-b074-5237bda22f21)

### Which version of Artemis are you seeing the problem on?

7.1.0

### What browsers are you seeing the problem on?

Chrome

**Comment by Strohgelaender** [comment]
These tests are there as an example on how hidden tests can be created.

I would not consider this a bug. While the solution for finished exercises should fulfill all tests cases, this must not really be the case for the template since real exercise will never be an unchanged template.

**Comment by florian-glombik** [comment]
Thank you for the clarification; I was not aware that this is intentional behavior, and I agree that it is not a bug then!

If I start creating exercises, I would prefer and expect the template to represent the state of an exercise as if I had configured it properly. For me, this seems like a rather unintuitive way to introduce the feature of hidden tests, as I would expect a finished exercise to pass the hidden tests as well.

However, I agree that this is probably the most effective way to make sure instructors get to know hidden tests.
