### ISSUE TITLE
Fix Problem Statements not getting displayed on mobile Phones

### ISSUE THREAD

**Issue by janthoXO** [ls1intum/Artemis#8674]
### Describe the bug

When opening a programming exercise view on a mobile device with a small screen width, the problem statement itself can not be seen but only the sidebar with the different exercises. 
The website is not scrollable to the side in mobile View neither in desktop view on the phone. Therefore the user can not scroll to the side to see the problem statement

### To Reproduce

1. Go to a course with programming exercises on your mobile phone
2. Click on a programming exercise
3. Try to scroll to the side to see the problem statement

### Expected behavior

As a user I either want to be able to minimize the sidebar on my mobile phone
Or be able to scroll to the side to see the problem statement

### Screenshots

https://github.com/ls1intum/Artemis/assets/95364200/4252803b-c7e8-4feb-b052-9d7a6726cd1a

### Which version of Artemis are you seeing the problem on?

7.1.0

### What browsers are you seeing the problem on?

Safari

**Comment by JohannesStoehr** [comment]
You can minimise the side bar with the button on the left of `Exercises` on the top of the page.
Does this fix the issue for you?

**Comment by zhngharry** [comment]
Tried it out on my phone, result is that the exercise is still not able to be shown fully. I think making the exercise container scrollable should fix it, what do you think? @JohannesStoehr https://github.com/ls1intum/Artemis/assets/98264403/98ef3e14-8664-4776-a779-3f307eb4b554
