### ISSUE TITLE
Change `value` of CompetencyJol to int

### ISSUE THREAD

**Issue by JohannesStoehr** [ls1intum/Artemis#8676]
### Is your feature request related to a problem?

#8598 introduced the CompetencyJol with `Integer` as data type for the stored value. But the value should always exist, if we only create the CompetencyJol when actually needed. 

### Describe the solution you'd like

Change the data type to `int` and only create the objects when they are actually needed.

### Describe alternatives you've considered

Don't change it and accept all the null checks...

**Comment by krusche** [comment]
Can we simply do it in the corresponding branch?

**Comment by MaximilianAnzinger** [comment]
We changed it to short in #8689
