### ISSUE TITLE
Add Export functionality for tutorial Details 

### ISSUE THREAD

**Issue by az108** [ls1intum/Artemis#8681]
# Feature Proposal
> Spec Version 0.2.0

### Problem  
> It is currently not possible for Instructors to export tutor group data, such as group names, tutor names, starting time, end time and student lists, from the Tutorials Section in Artemis.

### Motivation 
> This feature would allow exercise instructors to easily reuse tutorial data every year, saving time and effort in manually creating these. It would be easy to forward data to groups requiring it, also saving time and effort.

### Existing (Problematic) Solution / System 
> Currently, exercise instructors have to manually look up the tutorial data from previous years and enter it into a file, which requires a lot of effort.

### Proposed System 
> The exercise instructor can press an export button and receive a CSV containing all the data they need without having to create it manually. When an instructor presses on a button, this should display a modular view where the instructor can choose the fields he/she wants to export. After selecting the checkboxes, these fields should be exported to a CSV. This is planned to be done server-side by adding the CSV parsing logic there and handling the export request. When the client sends the information about which fields to export, the server should parse this information and create the CSV based on the client’s request and send the information back. Additionally, the exported data should be importable again with the existing import feature.

### Requirements 
> FR: Export Functionality: Create a CSV with all the information needed about tutorial groups in the current course.
>
> NFR: Reliability: Functioning Button: The button should work when pressed.

### Access Control / Security Aspects 
> Only exercise instructors of a course should be able to use this functionality to maintain data privacy.
> The server should only accept requests with predefined tutorial information fields, as selected via the checkbox options. To enforce this, a switch statement will be implemented to validate and process only the permitted field values, ensuring no custom or unauthorized data can be sent.

## UI/UX Design
![image](https://github.com/ls1intum/Artemis/assets/92953467/1d20dd04-1ff7-4c7a-a9f3-13c9d5d50496)
![image](https://github.com/ls1intum/Artemis/assets/92953467/7a3a04d3-6678-47f6-9414-c934aec1d4bf)

**Comment by JohannesStoehr** [comment]
The import functionality is currently very limited (only group name and registered students). So you would probably have to allow the import of other information like rooms and campus, language or the login for the tutor. 
Additionally we use the import to create the tutorials in Artemis that already exist in TumOnline, so the import should not focus on other Artemis tutorials alone.

**Comment by MarkusPaulsen** [comment]
> The import functionality is currently very limited (only group name and registered students). So you would probably have to allow the import of other information like rooms and campus, language or the login for the tutor. Additionally we use the import to create the tutorials in Artemis that already exist in TumOnline, so the import should not focus on other Artemis tutorials alone.

True, but improving the import function is definitely a different feature and should be dealt with in a second feature proposal.

**Comment by MarkusPaulsen** [comment]
- Regarding "It is currently not possible for Instructors to export tutor group data from the Tutorials Section in Artemis.": Please provide examples of possible "tutor group data".
- Please do not mention the student council explicitly (as this is an internal TUM matter)
- I would mention in "Proposed System" that the exported data can also be imported again and that importing previously exported data should not alter anything when imported
- Please remove the sentence "Describe the Functional and Non-Functional Requirements of the feature. Stick to the INVEST methodology!"
- Regarding "Persistent Data Management": Is the file temporarily stored somewhere during its the creation?
- Regarding "UI/UX Design": I would remove the part "to CSV", as this is also not present in the tutorial groups

- Are you planning to also make it possible to export the students registered in the tutor group or the appointments of the tutor group. If yes, how would you save it in a CSV structure?
