### ISSUE TITLE
Difficult to understand Import Button

### ISSUE THREAD

**Issue by az108** [ls1intum/Artemis#8695]
### Describe the issue

The import button does not provide clear information on what kind of CSV file should be uploaded to import information on a Tutor Group.  For example the line: "For tutorial group title: gruppe, titel, group, title" confuses one person more rather than helping. And this seems to be a translating error in the code.

### To Reproduce

1. Go to 'Course Management in a Course where you are Instructor'
2. Click on 'Tutorials'
3. Click on 'More'
4. Click on 'Import Tutorial Groups'

### Expected behavior

It should be clear which headers and rows are expected in the CSV file which will be imported. This saves a new Instructor time and effort in understanding the system.

### Screenshots

<img width="1028" alt="image" src="https://github.com/ls1intum/Artemis/assets/92953467/2a7a63a4-5b35-47e5-894d-a6c76481ae06">

### Which version of Artemis are you seeing the problem on?

7.1.1

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge, Firefox

**Comment by MarkusPaulsen** [comment]
Please describe more what you mean with "It should be clear what should be included in the CSV file which will be imported.".
