### ISSUE TITLE
`Programming exercises`: Warnings in the assessment editor trigger flickering

### ISSUE THREAD

**Issue by BaumiCoder** [ls1intum/Artemis#8731]
### Describe the bug

If there are warnings in the assessment editor from static code analyses (e.g. Checkstyle), you get some kind of flickering. It occurs when you move your mouse of the code lines, and you hit some lines with warnings.

One possible solution could be to make the column weight enough to contain both icons, if there are warnings in at least one line, independent of the actual line of the mouse course.

### To Reproduce

1. Create a programming exercise with static code analysis (e.g. Java Maven Project)
2. Make a submission for this exercise with changes that add warning (e.g. Rename the constants in the `Client.java` see Screenshots)
3. Set the Due Date of the exercise to now and add a manual assessment
4. Open your submission in the assessment editor
5. Went through the code with your mouse courser

### Expected behavior

There are no visual distractions when going through the code with the mouse courser.

### Screenshots

![example](https://github.com/ls1intum/Artemis/assets/73783062/1b1a5a58-2524-480c-ad2a-acf71361c4c3)
Gif convertation had added some color bugs, so here also the video file: https://github.com/ls1intum/Artemis/assets/73783062/63fe0676-5d80-4184-8b29-0f1c79d540f9

### Which version of Artemis are you seeing the problem on?

7.1.2

### What browsers are you seeing the problem on?

Firefox

**Comment by pzdr7** [comment]
This was the workaround we implemented to prevent the button being hidden under the build annotations. We might be able to move the button to the right of the line numbers.

I quickly typed something up in the Monaco Editor playground: [example](https://microsoft.github.io/monaco-editor/playground.html?source=v0.49.0#XQAAAAJwBQAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscw417fQEChknxTyhsOtw_oZuoS-bntDRvUjkOwcRtcHNwKoOpD9hqF1FLGw7nCYILel2Pa8v_zJ3fSGF5dVzmbj45xm9DS0quUH1uxuaQU24y-oAP3oetW9Wp89BrEhKnd1gNXAtfPKu-nP_1tpHxbqaEZ6_FSRTSWt596XS_xYSVf_z2eSkZ7WjL_Aka2D1-kF0_ouGwL-nUnJcH77JFMUsCXtANhJ1R7xHFAeH2xHJtgdVKgxJuD6LcdP7F99XPZvLQAuDGPW9wZbNaHyIe2kVfUSbMPqGvNBnQgpz0Jg9jHn_rgawMdT8wbSFl-YAHyTmAvLlc5QDV-H7RM5CR1JN5pfGYH1pTp71CDaDva2BCgqtj_QA60lgnt7ukRaU8P2_9aYgYpGAgL51ibPQ-N8icecmnBgQb6dgc4RyYLHzMf-PBGvIHYenApz_rLwW6uX3bCLj-hHBqZhSYrXF40AJgfn2Ud7s-C7A8tAtXy3_s7bPyGujgRPNEcs7yEPeR4p-U2b4ZjmcTw9Vqx_PKWYxXjYF1TZDeKp4AlcH3A0b2tyO7-kKQ2JHM0mHoVkmdYGBhFZQFHmJzHI9Oc4G1pgg4YgTly_eghpCN-2C6jCXXh-OU5lG7hPEuFoGUQY8IRJx1MXXLzD21ajlrxvx8TfDnbneEDGQ4pxxFzMpJYd--xNFNHf56ANP0GLNfAB8vMp51sD17WmmK2c6jLF4MmWfzrIc6ubvbgLTjl4lMOQZCkxzq52tHjV6jfoaN6vzNMUCJlDN-4JpqpNukR7jmvkpgDl08j9Vz3uMWFT6_iYMjc0_QeSgLILvseAkDVjoL5fU5NXL--ZMbtGzWYSDuzSxtno4w9vrfbE7gL7iTuwCwXt-iS50qqGY9SzkQQuYH0Jbz_72tniQ) - move your mouse around in the preview editor

Would you prefer it if this was what it looked like?

**Comment by BaumiCoder** [comment]
Yes, that approach seems suitable for me if nobody misses the arrows to collapse code blocks like methods.

When changing already something here, a more discreet icon would be nice e.g., a lighter color. If you read the code with your mouse cursor as a pointer, you can be easily got distracted from the moving icon on the left.
