### ISSUE TITLE
Local Repository remains after programming exercise is deleted

### ISSUE THREAD

**Issue by hornflip** [ls1intum/Artemis#8786]
### Describe the bug

We use localvc and localci and a docker-setup. The repositories are bound by mounted volumes and are therefore visible on the host machine.
But the project with name 'PROGTEMP' inside the 'local-vcs-repo' folder still exists after I delete the programming exercise in the web-app.
After manually deleting the 'PROGTEMP' folder I am able to create a programming exercise with the same name.

### To Reproduce

1. Go to CourseManagement > Create new Course
2. fill out all necessary fields (Title & short Title) and Create Course
3. Navigate to Course > Exercises > create Programming Exercise
4. fill out all necessary fields (Title, short Name, packagename and points to 1)
5. klick Generate
6. klick Delete > Type in the Exercise Name > klick Delete > See Confirmation ("Prog Exec deleted")
7. Generate Course with exact same name > See Error ("Project already exists on the Version Control Server: TKurs Template3. Please choose a different title and short name!")

### Expected behavior

With deleting the exercise out of the database I expect the corresponding repositories (template, solution, test) from the version control server to be deleted.

### Which version of Artemis are you seeing the problem on?

7.2.0, 7.1.1

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
2024-06-12T15:13:47.482Z  INFO 1 --- [Artemis] [io-8080-exec-28] d.t.i.w.a.web.rest.QuizExerciseResource  : REST request to get all quiz exercises for the course with id : 3
2024-06-12T15:14:06.982Z ERROR 1 --- [Artemis] [nio-8080-exec-4] tech.jhipster.web.util.HeaderUtil        : Entity processing failed, Project already exists on the Version Control Server: TKurs Template3. Please choose a different title and short name!
2024-06-12T15:14:06.986Z  WARN 1 --- [Artemis] [nio-8080-exec-4] o.z.problem.spring.common.AdviceTraits   : Bad Request: Project already exists on the Version Control Server: TKurs Template3. Please choose a different title and short name!
```

**Comment by sarpsahinalp** [comment]
![image](https://github.com/ls1intum/Artemis/assets/92453703/c0c6d689-fc63-4eb4-b7f6-3a5a8340ac0a)
The following is always passed in as false:

- `@RequestParam(defaultValue = "false") boolean deleteStudentReposBuildPlans`

There for the following is never executed:
```java
if (deleteBaseReposBuildPlans) {
        deleteBuildPlans(programmingExercise);
        programmingExerciseRepositoryService.deleteRepositories(programmingExercise);
}
```

That is why the LocalVC repos are not deleted a possible option could be checkbox to ask for the local repos to be deleted.

**Comment by krusche** [comment]
For LocalVC/LocalCI this option should have a default value of true

**Comment by krusche** [comment]
I implemented a fix on `develop`. Please try it again and let me know if it does not work correctly for you.

**Comment by sarpsahinalp** [comment]
Tested again works as expected.
