### ISSUE TITLE
Please give a support for a jupyter notebook file with file upload

### ISSUE THREAD

**Issue by weiyuandu** [ls1intum/Artemis#8810]
### Is your feature request related to a problem?

Currently, the file upload does not support a jupyter notebook file. 

### Describe the solution you'd like

Please add file end with .ipynb for file upload. which will be very helpful for our python exercises. :)

**Comment by Strohgelaender** [comment]
This seems to be related to one specific exercise. Please contact your course instructors for such requests and questions.

Artemis allows instructors to specify any set of allowed extensions and your instructors can add the .jpynb extension there.
