### ISSUE TITLE
Bamboo Playwright E2E Tests with Multinode Configuration Running on Wrong Branch

### ISSUE THREAD

**Issue by egekurt123** [ls1intum/Artemis#8831]
### Describe the bug

We have identified an issue where the Bamboo Playwright E2E tests configured for Multinode execution are running on HEAD instead of pushed branch. 

### To Reproduce

1. Turn the video recording on for a branch for debugging reasons
2. Trigger the Bamboo build for the Playwright E2E tests with the multinode configuration.
3. Observe the branch on which the tests are executed.

### Expected behavior

The tests should get executed on the pushed branch

### Screenshots

Example Build with playwright video artifacts: https://bamboo.ase.in.tum.de/browse/ARTEMIS-AEPAEPTMLM11-DA-28/artifact

<img width="573" alt="Screenshot 2024-06-20 at 15 13 43" src="https://github.com/ls1intum/Artemis/assets/69898283/89e65156-ad9e-41b5-a9f5-74ec7666fd45">

### Which version of Artemis are you seeing the problem on?

7.2.3

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge, Firefox

**Comment by krusche** [comment]
We should fix this issue asap!
