### ISSUE TITLE
`Exam mode`: Repository of an Programming Exercise can not be opened

### ISSUE THREAD

**Issue by JohannesWt** [ls1intum/Artemis#8878]
### Describe the bug

When taking part in an exam as a student and doing a Programming Exercise the repository cannot be opened. When clicking on "Open repository" the exam page is loaded and not the repository in the online editor

### To Reproduce

1. Start exam with student (having a Programming Exercise)
2. Select Programming Exercise
3. Click "Open repository"
4. you will be directed to Exam page and **not** the repository in the online editor

### Expected behavior

The click should lead to the repository

### Which version of Artemis are you seeing the problem on?

7.3.1

### What browsers are you seeing the problem on?

Chrome

**Comment by EneaGore** [comment]
Same problem on exam summary as well.

**Comment by pzdr7** [comment]
I was working on moving this button anyway. I'll discuss this with Stephan
