### ISSUE TITLE
`Modeling exercises`: Problem statement panel closes if text is clicked

### ISSUE THREAD

**Issue by magaupp** [ls1intum/Artemis#8883]
### Describe the bug

Clicking on the text of the problem statement also collapses the panel. This prevents selecting and copying parts of the problem statement.

### To Reproduce

1. Go to a modeling exercise
2. Click on the text of the problem statement (not the button)
3. The problem statement is collapsed

### Expected behavior

The problem statement should not collapse if the text is clicked. The problem statement should only collapse if the arrow button is clicked.

### Which version of Artemis are you seeing the problem on?

Branch: feature/exam-mode/new-design Commit Hash: 9e56059

### What browsers are you seeing the problem on?

Chrome, Firefox

**Comment by edkaya** [comment]
I think this issue does not happen only in modeling exercises, but also in text exercises (or other exercises types that use collapsible problem statement box)

**Comment by florian-glombik** [comment]
@edkaya Yeah, it seems to occur for multiple exercise types 

https://github.com/ls1intum/Artemis/issues/8899

**Comment by edkaya** [comment]
I will fix them together today 👍
