### ISSUE TITLE
`Integrate code lifecycle`: Provide Instructors with more control over build configuration of programming exercises

### ISSUE THREAD

**Issue by BBesrour** [ls1intum/Artemis#8887]
# Feature Proposal
> Spec Version 0.2.0

### Problem  
Currently, the Artemis platform provides limited control over programming exercise configurations for instructors. This lack of customization hampers the ability to tailor the exercise environment to specific needs, resulting in inefficiencies and challenges in managing exercises effectively.

### Motivation 
Enhancing control over programming exercises is crucial for improving both the instructor and student experience. This feature will allow for precise environment configurations, making the Integrated Code Lifecycle (ICL) feature-wise on par with external solutions like GitLab and GitLabCI. This advancement will help improve exercise management and overall platform efficiency.

### Existing (Problematic) Solution / System 
Currently, the checkout path, build job limit, and Docker flags are set through environment variables. This setup means neither administrators nor instructors can change these settings within the Artemis platform. Additionally, the system only allows pushing to the default branch (main), limiting flexibility for handling multiple branches in programming exercises.

### Proposed System 
Create a build config entity connected to the programming exercise. This entity will be loaded lazily, joined only when necessary, and will store the new configuration data. This data, including the checkout path, build job limit, and Docker flags, will be passed to the build agent when a build is triggered. Additionally, other relevant fields currently in the programming exercise entity will be moved to this new build config entity.

### Requirements 
FRs:
- Allow instructors to specify the checkout path for the code within the container.
- Enable instructors to set a build job time limit between 1 and max limit set by admins.
- Allow administrators to configure the system-wide maximum build job limit.
- Allow instructors to specify the Docker flags for running the container for each programming exercise. These docker flags should be restricted for security and performances reasons.
- Provide instructors with the ability to specify allowed branch regex.
- Allow students to push to branches other than main.

NFRs:
- Ensure the build config entity is loaded lazily to optimize performance.
- The UI for setting these configurations should be intuitive and easy to use for both instructors and administrators.

### Analysis Object Model 
![build_config_entity drawio](https://github.com/user-attachments/assets/13ba9693-ab2d-4cc7-9cd5-81a95e1ed35a)

### Subsystem Decomposition
This would require changing `VersionControlService` to provide a way to get latest commit for branch (`getLatestCommitForBranch(String branch)`). Previously, the service only provided a method to get the latest commit for the default branch. The programming exercises DTOs will also be adjusted to reflect the new changes.
We would also need to change the `BuildConfig` DTO so that it holds the new configuration data. The buildagent interfaces shouldn't change since they use commit hashes. 

### Persistent Data Management

- table `BuildJobConfig` (NEW)
  - fields: testRepositoryUri, staticCodeAnalysisEnabled, sequentialTestRuns, branch, buildPlanConfiguration, buildScript, checkoutSolutionRepository, checkoutPath, timeoutSeconds, dockerFlags
- table `SystemBuildJobConfig` (NEW)
  - fields: maxTimeoutSeconds
- table `ProgrammingExercise` (EDITED)
  - removed fields: testRepositoryUri, staticCodeAnalysisEnabled, sequentialTestRuns, branch, buildPlanConfiguration, buildScript, checkoutSolutionRepository

### Access Control / Security Aspects 
**POST/PUT** `api/admin/programming-exercises/build-timeout`
- Updates the max timeout time allowed for build jobs
- Access right: Admin

**GET** `api/programming-exercises/build-timeout`
- Reads the max timeout time allowed for build jobs
- Access rights: Instructor+

## UI/UX Design
![image](https://github.com/ls1intum/Artemis/assets/58034472/789419cd-4a60-4015-86bf-71f5f778fa82)[wireframe](https://wireframe.cc/llouQT)

The build queue view would also be slightly changed to add a configure button that will show a modal. We can configure the max build timeout in that modal (and possibly new other configuration in the future)

**Comment by b-fein** [comment]
> Enable instructors to set a build job time limit between 1 and 10 minutes.

I would propose to let admins define the upper limit instead via the already existing config option `artemis.continuous-integration.build-timeout`.

> Provide instructors with the ability to specify allowed branch regex.
> Allow students to push to branches other than main.

Related issue: #8753

**Comment by BBesrour** [comment]
> I would propose to let admins define the upper limit instead via the already existing config option artemis.continuous-integration.build-timeout.

Thanks for the feedback @b-fein! That sentence was badly phrased. The plan is to allow admins to change the limit at runtime

**Comment by krusche** [comment]
@b-fein I think we will have a hybrid approach. Admins can define the maximum system wide build timeout, e.g. 10minutes. Instructors could then define this on an exercise basis between 1s and <max-build-time-out>.
The default stays at 2min (120s)

**Comment by dfuchss** [comment]
Is it really important that the checkout directory can be changed. I would see that more like an advanced feature and I'd also say that if you want to modify the checkout directory it might be more easy to adapt the build script to deal with the default location  :) or are there certain use cases to modify the checkout directory (I mean you could easily just add `mv assignment /my-custom-dir` to the script. I'm unsure whether a UI option is really needed :)

**Comment by krusche** [comment]
This is definitely an advanced option that will be hidden by default and only be accessible in the expert mode (when customizing the default build structure However checkout paths are currently hard coded and cannot really be changed in LocalCI which was possible with bamboo and is possible with Jenkins. Making this available during exercise creation for advanced instructors does not hurt and makes the whole process more flexible, also for different programming languages which so far might use different settings for checkout paths

**Comment by BaumiCoder** [comment]
Strongly related to the need for docker flag configuration, is the need for multiple container. If you set docker flags they maybe have to be different for different part of the tests. For example for secret tests you want to limit the network access (as described [here](https://docs.artemis.cit.tum.de/admin/setup/programming-exercises.html#security-considerations)), but need full network access for some public tests.
