### ISSUE TITLE
`Exam Mode`: Text Exercise Problem Statement collapses when clicking on any part of the element

### ISSUE THREAD

**Issue by BBesrour** [ls1intum/Artemis#8899]
### Describe the bug

In a text exercise in exam mode, the problem statement section collapses when clicking on any part of the element (even when selecting text)

### To Reproduce

1. Create exam with text exercise
2. Participate as student
3. Click on the text of the problem statement

### Expected behavior

Problem statement is only collapsable when clicking on the arrow or the element header (the blue section)

### Which version of Artemis are you seeing the problem on?

7.3.1 - Commit Hash: 4168203

### What browsers are you seeing the problem on?

Microsoft Edge

### Additional context

This is not present in a non-exam graded text exercise.
Also not present in exam programming exercise

**Comment by edkaya** [comment]
This issue is fixed together with other issue #8883 in PR #8915
