### ISSUE TITLE
`Exam Mode`: Error when viewing test run summary 

### ISSUE THREAD

**Issue by laadvo** [ls1intum/Artemis#8900]
### Describe the bug

Clicking on the "Summary" button of a finished Exam Test Run when there is a newly created Test Run causes an Internal Server Error.

### To Reproduce

1. Create an exam
2. Start a Test Run and participate in it. Make sure to submit it.
3. Go to the Test Run page
4. Create a new Test Run
5. Click on the Summary page of the first Test Run
6. Get an Internal server error

### Expected behavior

The Summary should open normaly, without an error

### Screenshots

![image](https://github.com/ls1intum/Artemis/assets/73339358/dcdafba7-8a71-426d-be5e-0d4c6cc93264)

### Which version of Artemis are you seeing the problem on?

7.3.1

### What browsers are you seeing the problem on?

Chrome

### Additional context

Found during the exam mode testing session

### Relevant log output

```shell
error:
- detail: "Query did not return a unique result: 2 results were returned"
- message: "error.http.500"
- path: "/api/courses/90/exams/163/student-exams/grade-summary"
- status: 500
- title: "Internal Server Error"
- type: "https://www.jhipster.tech/problem/problem-with-message"
```

**Comment by coolchock** [comment]
resolved in #8974
