### ISSUE TITLE
`Exam Mode`:  Error when uploading a pdf in file upload exercises when multiple upload options available

### ISSUE THREAD

**Issue by marlon-luca-bu** [ls1intum/Artemis#8902]
### Describe the bug

If png, pdf, zip, jpg are specified as upload options in a file upload exercise in an exam, the pdf upload does not work.

### To Reproduce

1. Create an exam
2. Create an file upload exercise with the possibility to upload pdf, jpeg, png and zip
3. Try to upload a pdf

### Expected behavior

One should always be able to upload a pdf file 

### Screenshots

![image](https://github.com/ls1intum/Artemis/assets/65083942/f9f547e6-d600-4027-9841-8f76d2c45696)

### Which version of Artemis are you seeing the problem on?

7.3.1

### What browsers are you seeing the problem on?

Chrome

**Comment by coolchock** [comment]
I and @marlon-luca-bu were not able to reproduce this issue, neither locally nor on test servers.
