### ISSUE TITLE
`Exam mode:` Export of the exam wastes a lot of space

### ISSUE THREAD

**Issue by undernagruzez** [ls1intum/Artemis#8906]
### Describe the bug

When I submitted an exam and printed the overview as a student, the resulting document contained a large portion of Artemis UI.

### To Reproduce

1. As a student participate in an exam.
2. As an instructor, grade the submissions and release the results.
3. As a student, go back and export the exam.

### Expected behavior

The page could hide the navigation area, to keep the document more informative.

* The course sidebar should be collapsed on export
* The exam sidebar should not be displayed on export

### Screenshots

![image](https://github.com/ls1intum/Artemis/assets/63976129/39df09b7-c879-48a2-bb05-767e51ddc3c6)

### Which version of Artemis are you seeing the problem on?

7.3.1

### What browsers are you seeing the problem on?

Chrome

### Additional context

[examExportWastingSomeSpace.pdf](https://github.com/user-attachments/files/16036880/examExportWastingSomeSpace.pdf)

**Comment by florian-glombik** [comment]
I added an example, a screenshot and made the expected behaviour more concrete.

Previous expected behavior: 
> The page could hide the navigation area, to keep the document more informative.
