### ISSUE TITLE
`Exam mode`: The model exercises are not saved automatically.

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#8928]
### Describe the bug

The model exercises are not saved automatically.

### To Reproduce

1. Create an exam with model exercises 
2. solve them as a student but don't press save just change the question 
3. Finish the exam 
4. verify that in the summary, your models were not saved them but another kind of questions yes (text for example)

### Expected behavior

The model should be saved only by changing the question because it shows a green-check in each question when there is a change. 

### Screenshots

<img width="1047" alt="Screenshot 2024-06-28 at 14 28 56" src="https://github.com/ls1intum/Artemis/assets/88991954/bfb66e64-6602-4da5-b1a3-9400a08513b0">
<img width="1055" alt="Screenshot 2024-06-28 at 14 29 13" src="https://github.com/ls1intum/Artemis/assets/88991954/992c8201-41d3-4177-aaad-e23e8e67047d">

### Which version of Artemis are you seeing the problem on?

7.3.0

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by florian-glombik** [comment]
When testing with `7.3.1` this issue did not occur for me. Could you please double check that it works for you aswell as this would otherwise be a critical issue? @Santia-go

**Comment by edkaya** [comment]
This is not the case for me too in the current version `7.4.2`. The modeling exercise is being saved after 30 seconds automatically. If I change the exercise, it is saved too.

**Comment by krusche** [comment]
the issue was not reproducible any more
