### ISSUE TITLE
Courses cannot be deleted if competency relations exist

### ISSUE THREAD

**Issue by MaximilianAnzinger** [ls1intum/Artemis#8954]
### Describe the bug

Courses cannot be deleted if competency relations exist.

### To Reproduce

1. Create course with competencies and relations
2. Try to delete course

### Expected behavior

Course should be deleted.

### Which version of Artemis are you seeing the problem on?

7.4.0

### What browsers are you seeing the problem on?

Chrome

**Comment by krusche** [comment]
Would be great if we can fix this issue asap!
