### ISSUE TITLE
`Exam mode`: Allow changing (or disabling) hard-coded welcome page texts

### ISSUE THREAD

**Issue by FloezeTv** [ls1intum/Artemis#8970]
### Is your feature request related to a problem?

When conducting an exam using Artemis, the students are greeted with a welcome page.
This page contains some texts that are hard-coded in the [respective component](https://github.com/ls1intum/Artemis/blob/a6eade2a875cae1080a86344b5c294af894a4b7b/src/main/webapp/app/exam/participate/exam-start-information/exam-start-information.component.html#L20-L32):
https://github.com/ls1intum/Artemis/blob/a6eade2a875cae1080a86344b5c294af894a4b7b/src/main/webapp/i18n/en/exam.json#L152-L164

While some (parts) of these texts (e.g., `readCarefully`, `submissionPeriod`, `workingInstruction`) may be general enough, having all of these texts hard-coded seems tailored to a specific exam mode, making it impossible to use Artemis for exams with different modalities.

In particular, we plan to conduct an exam in August which will **not** be open-book, therefore the hard-coded texts are not fitting.
Some examples include:
- `workOnYourOwn`: `This is an open book exam (including using the Internet)`
This will not be the case for our exam
- `checkForPlagiarism`: `If you happen to copy code, for example, from a book or a website`
This will not be allowed in our exam
- `programmingSubmission`: `No actual tests will be run against your submission.`
This will also not be the case for us as we plan to provide some small sanity-check tests

### Describe the solution you'd like

Some possibilities I could think of are:
- Allow showing/hiding these texts in the exam settings
- Make these texts editable in the `Exam texts` section on the exam edit page
- Use these texts as a default-value for the `Exam start text`-field on the exam edit page

### Describe alternatives you've considered

The only alternative I could think of would be to tell students to ignore this part of the start page, though apart from being hard to understand (i.e., which parts are to be ignored and which contain the correct information) this may also lead to legal consequences due to contradictory statements.

##### The hard-coded texts at the exam start page:
![Screenshot of the exam start screen (of a test run) containing the mentioned messages](https://github.com/ls1intum/Artemis/assets/32437469/ce24e70b-6bd8-429e-a721-24b2f2ee3a29)

**Comment by krusche** [comment]
It's not intended that those values are hard-coded. This was an implementation mistake that slipped through. The whole page should be customizable by the instructor with those values when creating / editing an exam in the course management area:
* Exam start text
* Exam start confirmation text

Also the end page should be fully configured by the instructor using:
* Exam end text
* Exam end confirmation text
