### ISSUE TITLE
`Programming exercises`: Build script customization does not work on the first attempt

### ISSUE THREAD

**Issue by pzdr7** [ls1intum/Artemis#8980]
### Describe the bug

When customizing the build script of a programming exercise for the first time, the build script is not saved. For any subsequent attempts, the build script is saved correctly.

### To Reproduce

As an instructor (tested locally and on TS1)

1. Create a new programming exercise, but do not customize the build script .
2. Edit the programming exercise, tick the "Customize build script" box, and change the build script.
3. Save the exercise.
4. See that the build script is not the one you just entered. (Expected: Should be the one you just entered.)
5. Repeat steps 2 and 3.
6. See that the build script now updates correctly (as expected)

### Expected behavior

It should work on the first attempt as well.

### Screenshots

**Request with updated build script**: `PUT /api/programming-exercises`

![image](https://github.com/ls1intum/Artemis/assets/38403547/b3df45a0-6a09-427f-97cb-c9836d3636c9)

**Response with old/default? build script**:

![image](https://github.com/ls1intum/Artemis/assets/38403547/d62ca586-01b7-4f73-91fa-898c9cdddb0a)

### Which version of Artemis are you seeing the problem on?

7.4.1

### What browsers are you seeing the problem on?

Chrome

**Comment by just-max** [comment]
I've found that if the custom docker image is changed, changes to the build script are ignored. Is that happening here, or is the docker image unchanged?

**Comment by pzdr7** [comment]
@just-max I think that might be the root cause. I'll investigate it 👍

**Comment by just-max** [comment]
Thanks for investigating. Upon closer inspection I noticed that what actually happens is:
- if only the build script is changed, it works
- if the docker image is changed, the build script is ignored **and replaced with the default build script**

That one might have gone under the radar since I'm not sure how many people are using the custom build scripts.
