### ISSUE TITLE
`Communication`: Unnecessary gray area in empty dropdown

### ISSUE THREAD

**Issue by asliayk** [ls1intum/Artemis#9002]
### Describe the bug

When there are no options available in the collapsible/dropdown menu of the communication section of a course, an unnecessary and unappealing empty grey area is displayed. This behavior is not ideal for user experience and is less common in user interfaces.

### To Reproduce

1. Go to Course Management page
2. Click Communications button of a course
3. Click an empty option in the collapsible menu
4. Notice the unnecessary gray empty area

### Expected behavior

- The collapsible menu should not expand when there are no options available.
- Alternatively, a message such as "No options available" should be displayed instead of an unnecessary gray area.

### Screenshots

![image](https://github.com/ls1intum/Artemis/assets/56061820/df5aab5b-09bb-4aa4-9c92-23fdcf48fb60)

### Which version of Artemis are you seeing the problem on?

7.4.2

### What browsers are you seeing the problem on?

Chrome

**Comment by egekurt123** [comment]
Normally, as like other modules on sidebar, we do not intend to display empty accordions. However, we cannot remove this one due to an impediment caused by private messages and group chats, which require the plus button on the accordion to create chats. This should change in upcoming versions.
