### ISSUE TITLE
`Exam mode`: Problem statement not updated if exercise not previously loaded

### ISSUE THREAD

**Issue by BBesrour** [ls1intum/Artemis#9009]
### Describe the bug

When the exercise was not previously loaded, the problem statement is not updated even though we received a notification and we acknowledged it

### To Reproduce

Prerequisites:
- Exam containing an exercise with a problem statement
- 1 Instructor
- 1 Student

1. As a student, start the exam. Stay on the overview page (don't navigate to any exercise)
2. As Instructor, update the problem statement of one of the exercises
3. As a student, you should've received a notification. Click on Acknowledge
4. As a student, navigate to changed exercise. The problem statement was not updated. 

### Expected behavior

Problem statement should be updated even when exercise was not previously loaded.

### Which version of Artemis are you seeing the problem on?

7.4.1 (4c5382b)

### What browsers are you seeing the problem on?

Microsoft Edge

### Additional context

The socket is probably only being initiated when we load the exercise component.

**Comment by pzdr7** [comment]
I think the PR #8739 addresses this
