### ISSUE TITLE
`Adding new people`: Weird behavior of the icons

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#9022]
### Describe the bug

The icons replicate when I try to add a tutor, instructor, editor, or student 

### To Reproduce

1. Go to any course 
2. Try to add a person as a tutor, instructor, editor, or student
3. Verify that as long as you type or delete characters, the icon on the side of the name is duplicating 

### Expected behavior

The icon should not be duplicated or showing multiple times. 

### Screenshots

https://github.com/ls1intum/Artemis/assets/88991954/9199958b-1de4-4cd6-a581-5d97d39eff8c

### Which version of Artemis are you seeing the problem on?

7.4.1

### What browsers are you seeing the problem on?

Chrome

**Comment by edkaya** [comment]
I think this issue is already mentioned here #8938
