### ISSUE TITLE
Programming Exercise Descriptions: Underscores in Both Task Name and in Test Names Break Display by Adding Italics

### ISSUE THREAD

**Issue by just-max** [ls1intum/Artemis#9035]
### Describe the bug

I'm guessing since https://github.com/ls1intum/Artemis/pull/8461: tasks (i.e. the `[task][...](test1,test2,...)` syntax) will render underscores incorrectly:

- If an underscore is present in the task name and in the test name, part of the task name will render in italics. This occurs consistently on the instructor's exercise description view, but only in some cases in the student view (I have not been able to figure out what causes it to occur/not occur). Example: `[task][task_name](test_name)`  will render as **task<i>name</i>**.
- If an even number of underscores are present in the task name, they will render whatever is between them in italics [1]. Example: `[task][long_task_name](test)`  will render as **long<i>task</i>name**.

In both cases, it is impossible to escape the italics by adding a backslash: the backslashes are simply added directly to the output (in the instructor's preview) or dropped entirely (in the student view).

[1] This in and of itself is regular markdown behaviour, so perhaps not a bug. It is however different from the previous behaviour, and affected by being inescapable.

### To Reproduce

Create a new programming exercise with the following description:

```md

1. [task][task_name](test_name)
  Underscores combine across task and test name (BUG).

2. [task][long_task_name](name)
  Underscores create italics in task name (OK, but new behaviour).

---

3. [task][task\_name](test_name)
  Italics cannot be escaped with a backslash (BUG).

4. [task][long\_task\_name](name)
  Even where the "normal" markdown behaviour of underscores is present (BUG).

5. [task][task\_name](test\_name)
  This is doubly wrong, and doesn't work.

---

6. [task][task&#95;name](test_name)
  Using an HTML entity circumvents the issue.
```

### Expected behavior

1. Underscores in *test* names never affect formatting.
2. If underscores in *task* names affect formatting, those effects can be escaped with backslashes.

### Screenshots

Screenshot of the above exercise description, in the instructor view:

![image](https://github.com/user-attachments/assets/f5f926c4-71b8-450a-8d98-959acc37a306)

The same in the student view:

![image](https://github.com/user-attachments/assets/23245109-1ea9-4536-a86e-a71e8d3003bd)

*Note: In same cases, (1.) would render fine in the student view (see the bug description), but I don't have a MWE.*

### Which version of Artemis are you seeing the problem on?

7.4.1

### What browsers are you seeing the problem on?

Chrome, Firefox

### Additional context

Workaround (as above):

```md
1. [task][task&#95;name](test_name)
  Using an HTML entity circumvents the issue.
```

**Comment by krusche** [comment]
@pzdr7 could you please have a look?

**Comment by pzdr7** [comment]
Having checked out the corresponding commits locally, I can confirm that this seems to happen since #8461. I was unable to reproduce the missing backslashes in the student view in any version.

I suspect that the order in which we generate markdown / process the tasks has changed slightly, which causes the markdown formatting to be applied to the tasks (I remember there being some issues with the task diff when I was testing that PR. Could be related)
