### ISSUE TITLE
"Error while forking repository" when trying to start programming exercise

### ISSUE THREAD

**Issue by sascha11110** [ls1intum/Artemis#905]
### Describe the bug
Programming task could not be started after button *Start exercise* was clicked (see console output below).

#### To Reproduce
1. Go to [https://artemis.ase.in.tum.de/#/overview/10/exercises/688](https://artemis.ase.in.tum.de/#/overview/10/exercises/688)
2. Click *Start exercise*

#### Expected behavior
Task has been started and repository link is available

#### Screenshots

![Screenshot_20191011_162015](https://user-images.githubusercontent.com/15168372/66659102-18876080-ec43-11e9-9390-ac3ac92fd778.png)

### Environment

<details><pre>
 - OS: Linux (Fedora 30)
 - Browser: Chromium
 - Version: 77.0.3865.90 (Entwickler-Build) Fedora Project (64-Bit)
</pre></details>

#### Output in Web Console

```
{
  "type": "https://www.jhipster.tech/problem/problem-with-message",
  "title": "Unauthorized",
  "status": 401,
  "detail": "Vollständige Authentifikation wird benötigt um auf diese Resource zuzugreifen",
  "path": "/api/courses/10/exercises/688/participations",
  "message": "error.http.401"
}
```

Error state found using debugger:
```
error: {type: "https://www.jhipster.tech/problem/problem-with-message", title: "Internal Server Error", status: 500, detail: "Error while forking repository", path: "/api/courses/10/exercises/688/participations", …}
headers: p {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}
message: "Http failure response for https://artemis.ase.in.tum.de/api/courses/10/exercises/688/participations: 500 OK"
name: "HttpErrorResponse"
ok: false
status: 500
statusText: "OK"
url: "https://artemis.ase.in.tum.de/api/courses/10/exercises/688/participations"
```

**Comment by krusche** [comment]
@sascha11110 What happens if you click again on start exercise? Does it work then?

Since the last Bitbucket update, we have this issue randomly, but cannot identify when and why it actually happens.

**Comment by sascha11110** [comment]
No, even if I click it 10 times, it won't work.

**Comment by krusche** [comment]
I think the problem was that the exercises did not really exist any more on Bitbucket and Bamboo (probably because I deleted it in another Artemis instance).
I just created another exercise, can you try it again?
https://artemis.ase.in.tum.de/#/overview/10/exercises/715

**Comment by sascha11110** [comment]
Yes, everything works as expected.
