### ISSUE TITLE
Download of PDF lecture units not possible of imported lectures

### ISSUE THREAD

**Issue by FelixTJDietrich** [ls1intum/Artemis#9059]
### Describe the bug

PDF file is not downloadable from a lecture that has been imported.

This happened with the iPraktikum Intro Kurs lectures were we imported old lectures from previous courses.

### To Reproduce

1. Go to Course -> Manage -> Lectures
2. Click 'Create Lecture' to create some lecture
3. Click 'Units'
4. Click 'File' to add a new file lecture unit
5. Create File Unit using some PDF
6. Navigate to Lectures
7. Click 'Import Lecture'
8. Import the lecture you just created
9. Try downloading the PDF file of the unit
10. Does not work

### Expected behavior

File should have been downloaded 

### Screenshots

Pressing download here:
<img width="1083" alt="image" src="https://github.com/user-attachments/assets/5f1ce32e-41ea-4f35-a297-5cc174abd50e">

Yields:
```
{
    "type": "https://www.jhipster.tech/problem/problem-with-message",
    "status": 404,
    "detail": "No static resource api/files/temp/AttachmentUnit_2024-07-15T11-45-19-768_The_JHipster_Mini_Book_5.0.pdf.",
    "path": "[/api/files/temp/AttachmentUnit_2024-07-15T11-45-19-768_The_JHipster_Mini_Book_5.0.pdf](https://artemis-test3.artemis.cit.tum.de/api/files/temp/AttachmentUnit_2024-07-15T11-45-19-768_The_JHipster_Mini_Book_5.0.pdf)",
    "message": "error.http.404"
}
```

### Which version of Artemis are you seeing the problem on?

7.4.2

### What browsers are you seeing the problem on?

Chrome

**Comment by krusche** [comment]
Would be great to fix this
