### ISSUE TITLE
Unauthorized error in console for pending assessment

### ISSUE THREAD

**Issue by sascha11110** [ls1intum/Artemis#907]
### Describe the bug
If you start an assessment but don't finish it and then go back to the exercise's overview in the tutor dashboard, there is an "Unauthorized" error on console (see console output below). The error occurs with modeling, text and file upload exercises.

I could not detect any effect to the expected functionality caused by that error.

#### To Reproduce
1) Participate (submit) in e.g. https://artemis.ase.in.tum.de/#/overview/10/exercises/626 (the error also occurs with file upload exercises)
2) Go to the tutor dashboard for that exercise
3) Start the assessment for that submission (do not finish it)
4) Go back to the tutor dashboard (overview) for that exercise
5) Have a look at the console

#### Expected behavior
No error in console.

### Environment
<details><pre>
 - OS: Linux (Fedora 30)
 - Browser: Chromium
 - Version: 77.0.3865.90 (Entwickler-Build) Fedora Project (64-Bit)
</pre></details>

#### Output in Web Console
<details><pre>
{
  "type": "https://www.jhipster.tech/problem/problem-with-message",
  "title": "Unauthorized",
  "status": 401,
  "detail": "Vollständige Authentifikation wird benötigt um auf diese Resource zuzugreifen",
  "path": "/api/exercises/626/text-submission-without-assessment",
  "message": "error.http.401"
}
</pre></details>

**Comment by krusche** [comment]
As this is quite an old issue, I think we have already fixed it
