### ISSUE TITLE
Artemis is not working on Google chrome

### ISSUE THREAD

**Issue by Onstum17** [ls1intum/Artemis#9082]
### Describe the bug

Hi, 
I tried to open the Artemis page on google chrome but this error shows up (it used to work normally before but I don't know what happened) I tried to update my google chrome but nothing has changed. It works normally on Microsoft edge though, only on google chrome. Does anyone know how to fix this? I really appreciate any help you can provide. 

### To Reproduce

2. Click on '...'
3. Scroll down to '...'

### Expected behavior

It is supposed to open up on the google chrome but it didn't

### Screenshots

<img width="959" alt="Error Artemis" src="https://github.com/user-attachments/assets/dc612fe4-44e9-456e-96e3-7ef7d360efe7">

### Which version of Artemis are you seeing the problem on?

7.4.3

### What browsers are you seeing the problem on?

Chrome

**Comment by edkaya** [comment]
If you are trying to access Artemis locally and this page shows up, I suggest you to restart your server.

**Comment by krusche** [comment]
In case you are an end user, it might help to clear all data and cookies. To verify that Chrome works, you could try the Incognito mode. If this one also does not work, please reopen the issue and provide more details, e.g. which operating system, which Chrome version you use, etc. it would also be nice to see the console. Open the Developer Tools in Chrome and copy paste error messages and/or screenshots
