### ISSUE TITLE
Cannot create a new programming exercise

### ISSUE THREAD

**Issue by jeanDanh** [ls1intum/Artemis#9088]
### Describe the bug

I've set up Artemis locally. What I mean is I git cloned the project, setup via "Alternative: Docker Compose Setup" way. I've created a course successfully but there will be an error message saying "internal server error" when I attempt to create a new programming exercise.

### To Reproduce

1. Clone the Artemis repos
2. Open Powershell as the admin
3. Go to `Artemis/docker`
4. Input `docker compose -f artemis-dev-postgres.yml up` and press enter
5. Go to "localhost:8080" on your local machine's browser. 
6. Login Artemis as admin (Sorry, I can't leave the username and password here. I might get into trouble)
7. Header bar > "Course Management"
8. "Create new course"
9. Input info to create a new course
10. Go to your newly create course, click "Exercise"
11. Under the heading of "X Programming Exercises" (X is a natural number), click "Create Programming Exercise"
12. Input info to create a programming exercise
13. Click "Generate"
14. The error message shows up

### Expected behavior

1. Clone the Artemis repos
2. Open Powershell as the admin
3. Go to `Artemis/docker`
4. Input `docker compose -f artemis-dev-postgres.yml up` and press enter
5. Go to "localhost:8080" on your local machine's browser. 
6. Login Artemis as admin (Sorry, I can't leave the username and password here. I might get into trouble)
7. Header bar > "Course Management"
8. "Create new course"
9. Input info to create a new course
10. Go to your newly create course, click "Exercise"
11. Under the heading of "X Programming Exercises" (X is a natural number), click "Create Programming Exercise"
12. Input info to create a programming exercise
13. Click "Generate"
=> A new programming exercise is successfully created

### Screenshots

![Screenshot 2024-07-19 170411](https://github.com/user-attachments/assets/12387388-dd67-47a9-8328-8d7b73292038)

### Which version of Artemis are you seeing the problem on?

7.4.3

### What browsers are you seeing the problem on?

Microsoft Edge

### Additional context

Run on laptop, Windows 10 Pro

**Comment by Strohgelaender** [comment]
Make sure to follow the documentation on how to setup the integrated code lifecycle. https://docs.artemis.cit.tum.de/dev/setup/integrated-code-lifecycle.html 
Please also check that you are using the correct spring profiles.
