### ISSUE TITLE
Automatic quiz question loading while waiting for it to start fails

### ISSUE THREAD

**Issue by ungaralex** [ls1intum/Artemis#909]
### Describe the bug

When trying to start a quiz exercise as a student, before it is actually release, but only visible: On the page, where students can wait for the quiz to start (automatic refresh of the page as soon as the quiz starts), after the quiz actually gets started by an instructor, the students' page can't load the quiz questions (see output below).
You can however open the quiz again after it has been started and it will display all questions correctly. Only waiting for it doesn't work

#### To Reproduce

1. Create a new quiz exercise
2. Set the quiz visible
3. Click on "Open Quiz" as a student
4. Start the quiz for all students
5. On the students page, the loading should fail

#### Expected behavior

The page should correctly load all quiz questions after the quiz has been started.

### Environment

<details><pre>
 - OS: Ubuntu
 - Browser: Firefox
 - Version 3.8.1
</pre></details>

#### Output in Web Console

![quiz_start_bug](https://user-images.githubusercontent.com/27979674/66702127-7af46580-ed04-11e9-98f2-c77257e061ba.png)

**Comment by krusche** [comment]
Thanks for findings this issue! I fixed it!
