### ISSUE TITLE
`Programming Exercises` Customizability of "Open in Button"

### ISSUE THREAD

**Issue by janthoXO** [ls1intum/Artemis#9091]
### Is your feature request related to a problem?

Some people dont use the widely used IDEs like IntelliJ or VSCode but IDEs like VSCodium or other Jetbrain Products. Most of these IDEs still support deep links to clone.

### Describe the solution you'd like

The IDE to clone the exercise in, should be customizable by the User. The user can select the standard IDEs for certain Languages but also provide own deep links if they don't use "mainstream" IDEs.
The `clone in ...` buttons can then be reduced to only one button, making the UI more minimalistic 

#### Client side
<img width="1068" alt="image" src="https://github.com/user-attachments/assets/121d2d72-9d70-4ce4-9a9c-833353822885">

#### Server side
<img width="717" alt="image" src="https://github.com/user-attachments/assets/2f37bd77-70c8-4c79-9559-789a6e1314d5">

**Comment by krusche** [comment]
I like the idea, we can definitely do that. Please also talk to @rabeatwork who designed the new "Code" dialog in a really nice way. 

@rabeatwork 
With the configuration, we could only display one `Open in "..."` based on the configuration and could add a link to change this configuration. This would make the whole dialog easier and users would still be in full control

We could potentially ask the user what their preferred IDE is when they start an exercise for a specific programming language for the first time.

**Comment by janthoXO** [comment]
If the implementation of that is not too difficult then we can do that.
Otherwise we can just set VSCode as the default one for all languages and just write in the tool tip that it can be configured in the settings
