### ISSUE TITLE
Instructions text exceeds the limits of the text box

### ISSUE THREAD

**Issue by maxr96** [ls1intum/Artemis#910]
### Describe the bug

In the Code Editor Instructions text takes more space than set by text box. The text box boder overlaps the instructions text.

#### To Reproduce

1. Go to 'Overview'
2. Select programming exercise
3. Start exercise
4. Open code editor
5. See the text on the right under Instructions

#### Expected behavior

Text is only shown inside the text block

#### Screenshots

![Screenshot_2019-10-12 Code Editor](https://user-images.githubusercontent.com/17262376/66702415-c0666200-ed07-11e9-838c-921fe99d81f5.png)

### Environment

<details><pre>
 - OS: [Linux and Windows]
 - Browser [Firefox]
 - Version [69]
</pre></details>

**Comment by ungaralex** [comment]
If I remember correctly we've had this bug for quite some time now.
This should only be the case for Firefox, though.

**Comment by maxr96** [comment]
> 
> 
> If I remember correctly we've had this bug for quite some time now.
> This should only be the case for Firefox, though.

I didn't find it here in the Issues, so I added a new one. It is also reproducible in Microsoft Edge. 
![Снимок экрана (1)](https://user-images.githubusercontent.com/17262376/66702674-729f2900-ed0a-11e9-93df-ecf6b3c77aeb.png)

**Comment by madwau** [comment]
I wrote a fix in #1102.
