### ISSUE TITLE
Import / Export programming exercises

### ISSUE THREAD

**Issue by Garfield96** [ls1intum/Artemis#911]
### Is your feature request related to a problem?
Currently, it is not possible to import/export programming exercises. Therefore, if exercises should be reused in another semester they must be created from scratch.

### Describe the solution you'd like
Implement import/export functionalities for programming exercises.

### Describe alternatives you've considered
Since programming exercises are mostly characterized by their description an import/export function for the Markdown description would be a great addition (or alternative).

**Comment by krusche** [comment]
We have this already implemented, but not yet made available, because of some recent changes in the setup of the repositories and the build plans. As soon as we can make sure that the import of old programming exercises migrates the structure, we will make it available

**Comment by krusche** [comment]
This is possible since some time
