### ISSUE TITLE
Bonus (programming) exercises

### ISSUE THREAD

**Issue by Garfield96** [ls1intum/Artemis#912]
### Is your feature request related to a problem?
Many courses offer bonus exercises, either in the form of subtasks or complete exercises, but this functionality is not supported yet.

### Describe the solution you'd like
Add option (checkbox) in "Manage Test Cases" to mark a test case as a bonus.

### Describe alternatives you've considered
Add the option to specify a test case as a bonus in the MD description of the exercise.

### Additional information
There should be an additional option to select whether the max. score can be exceeded by bonus points or whether bonus points only help to compensate for failing test cases (max. score is not exceeded).

**Comment by krusche** [comment]
Good idea. You can actually set the weight of a test case to 0, which should have a similar effect. If you then mark the task in the problem statement as optional and you make sure that all tests associated to this task have a weight of 0, then you should have the desired behavior.

Of course, a checkbox optional could make this behavior more obvious and we should implement such a checkbox in the future.

**Comment by 13XxM1CHA3lxX37** [comment]
> Good idea. You can actually set the weight of a test case to 0, which should have a similar effect. If you then mark the task in the problem statement as optional and you make sure that all tests associated to this task have a weight of 0, then you should have the desired behavior.

I think that's not an adequate solution to this issue (if I understand the issue correctly). You refer to a similar solution like in the Strategy Pattern example where there is not really a bonus, but one can extend the solution "for fun" ungraded/untested.
I think the request refers to have let's say 100 points in total you can reach for all exercises, but we want to add let's say 20 bonus points, so one can theoretically reach 120 points with doing the bonus exercises or 100 if one skips the bonus exercises. With the bonus points one could compensate losses in other exercises, but my understanding is that one should get a 100% with [100;120] points.

**Comment by krusche** [comment]
Ok I understand, this would be a bit more difficult to implement then. We will think about how to integrated this in the future

**Comment by Garfield96** [comment]
> I think that's not an adequate solution to this issue (if I understand the issue correctly). You refer to a similar solution like in the Strategy Pattern example where there is not really a bonus, but one can extend the solution "for fun" ungraded/untested.
> I think the request refers to have let's say 100 points in total you can reach for all exercises, but we want to add let's say 20 bonus points, so one can theoretically reach 120 points with doing the bonus exercises or 100 if one skips the bonus exercises. With the bonus points one could compensate losses in other exercises, but my understanding is that one should get a 100% with [100;120] points.

Exactly. This was the main objective.

**Comment by krusche** [comment]
We will work on this soon 👍

**Comment by krusche** [comment]
Bonus exercises are now possible 👍
