### ISSUE TITLE
Students show be able to see completed / inactive course

### ISSUE THREAD

**Issue by Mtze** [ls1intum/Artemis#9129]
### Is your feature request related to a problem?

Students often ask to get access to old/completed courses on artemis. Students can actually access these coureses if they remember the link to the course. 

### Describe the solution you'd like

We need an option to browse all the courses a student has been part of. 

I think it would be best to select a semester and show all the courses in that specific semester. Alternatively a list with all the courses and a search bar to quickly get to the respective course. 

### Describe alternatives you've considered

There are none

**Comment by Strohgelaender** [comment]
See also the discussion in #2075.

**Comment by krusche** [comment]
We can add a page "old courses" (or similar) where we simply display a list of accessible courses for the user (e.g. grouped by semester, sorted from newest semester on top to the oldest semester) without adding any additional details (no statistics, no exercise data, etc.). Students could then navigate into the course by clicking on the course title.
