### ISSUE TITLE
'Go to build plan' button opens code editor

### ISSUE THREAD

**Issue by maxr96** [ls1intum/Artemis#913]
### Describe the bug

When I click on `Go to build plan` on the exercise that has `Publish Build Plan` set to true, I see code editor. It does the same as `Open code editor` button.

#### To Reproduce

1. Create a programming exercise with `Publish Build Plan` option set to true. 
2. Go to Overview
3. Select the course this exercise is in
3. Click `Go to build plan` on the exercise
4. Code editor is shown

#### Expected behavior

I want to see my own build plan

#### Additional context

There is an error in the console and also visible in the network tab. However this error seems to be related to code editor itself.

#### Output in Web Console

<details><pre>
  GET https://artemistest.ase.in.tum.de/mode-undefined.js net::ERR_ABORTED 404
</pre></details>

**Comment by krusche** [comment]
this was already fixed
