### ISSUE TITLE
Instructions frame not hidden if there are no instructions for programming exercise

### ISSUE THREAD

**Issue by maxr96** [ls1intum/Artemis#914]
### Describe the bug

Instructions frame not hidden if there are no instructions for programming exercise. Instead empty space is shown, which can be resized and behaves like an instruction frame.

#### To Reproduce

1. Go to 'Overview'
2. Click on course that has programming exercise without instructions
3. Select 'Open code editor' on the programming exercise
4. See empty space on the right 

#### Expected behavior

Instruction frame should be minimized and not use extra space of the code editor.

#### Screenshots

![Screenshot_2019-10-12 Code Editor(1)](https://user-images.githubusercontent.com/17262376/66703873-68cff280-ed17-11e9-84de-7875fa6b4163.png)

**Comment by ungaralex** [comment]
It's also not possible to change the instructions to an empty String --> The PATCH request returns a 400
