### ISSUE TITLE
Editing an exam quiz after the exam throws a 500 error

### ISSUE THREAD

**Issue by nilsreichardt** [ls1intum/Artemis#9156]
### Describe the bug

I'm trying to edit a quiz (adding explanations) for an exam. The exam already took place on Saturday. However, adding explanations to the quiz and then saving the quiz, throws an internal error.

### To Reproduce

1. Go to https://artemis.in.tum.de/course-management/276/exams/763/exercise-groups/3160/quiz-exercises/14240/edit
2. Click the edit button
3. Change any explanation (just add a character)
4. Click the save button
5. See error

### Expected behavior

I would expect to be able to edit the quiz.

### Screenshots

![image](https://github.com/user-attachments/assets/9a2f9e15-965b-4ca9-9522-8bc61cdfe04b)

### Which version of Artemis are you seeing the problem on?

7.4.5

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
In Chrome DevTools, it shows the following error details for the request:


{
    "type": "https://www.jhipster.tech/problem/problem-with-message",
    "title": "Internal Server Error",
    "status": 500,
    "detail": "could not execute batch [Cannot delete or update a parent row: a foreign key constraint fails (`Artemis`.`multiple_choice_submitted_answer_selected_options`, CONSTRAINT `SOME_ID` FOREIGN KEY (`selected_options_id`) REFERENCES `answer_option` (`id`) ON DELETE RESTRICT)] [delete from answer_option where id=?]; SQL [delete from answer_option where id=?]; constraint [null]",
    "path": "/api/quiz-exercises/14240",
    "message": "error.http.500"
}
```

Note: `SOME_ID` is a placeholder.

**Comment by krusche** [comment]
After a quiz is over, instructors should use the re-evaluate functionality to make sure that nothing in the quiz breaks.
The edit button / functionality should actually not be available.
Can you try out if it works with re-evaluate?

**Comment by nilsreichardt** [comment]
Thanks for the super quick support! ❤️ 

Using the "re-evaluate" button worked! 👍

> The edit button / functionality should actually not be available.

I created a new ticket for this (https://github.com/ls1intum/Artemis/issues/9157). Therefore, I'm closing this ticket.
