### ISSUE TITLE
Support multiple ssh keys

### ISSUE THREAD

**Issue by Per-severance** [ls1intum/Artemis#9166]
### Is your feature request related to a problem?

I find it rather tedious that I always have to change the ssh key in Artemis if I switch between different devices.

### Describe the solution you'd like

Add option to store multiple ssh keys

### Describe alternatives you've considered

only use one ssh key for all my devices -> bad for security reasons

**Comment by SimonEntholzer** [comment]
Closed by  https://github.com/ls1intum/Artemis/pull/9478
