### ISSUE TITLE
`Programming exercises`: Import from file doesn't import buildscript and docker image

### ISSUE THREAD

**Issue by BBesrour** [ls1intum/Artemis#9183]
### Describe the bug

Importing an exercise from a file does not correctly import the build script and the docker image from the original exercise. Default values will be used

### To Reproduce

1. When creating an exercise, change the build script and the docker image
2. Create the exercise and export it (Download exercise button)
3. Import exercise from file
4. Build script and docker image not imported

### Expected behavior

These values should imported from the original exercise

### Which version of Artemis are you seeing the problem on?

7.5.0

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by krusche** [comment]
We should export and import those. Can you have a look and fix it?

**Comment by Strohgelaender** [comment]
The information is present in the export, but the import ignores it currently.

**Comment by krusche** [comment]
Ok, then the import should take it into account. Sounds like an easy bugfix 😉

**Comment by krusche** [comment]
@BBesrour please make sure the new build config object is put into the export and taken into account during import
