### ISSUE TITLE
Make Cleanup of local repositories configurable

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#9197]
### Is your feature request related to a problem?

Currently, the cleanup of local repositories are configured here: https://github.com/ls1intum/Artemis/blob/eb5b9bd4321d953217e902868ac9f38de6dd6c6f/src/main/java/de/tum/in/www1/artemis/service/scheduled/AutomaticProgrammingExerciseCleanupService.java#L96

### Describe the solution you'd like

It would be nice, to be able to configure the time spans to consider for cleanup. Additionally, I'm currently not sure what happens after cleanup and if a student opens the task once again ; will the local repository be cleaned up again?

**Comment by krusche** [comment]
This is only done for old repositories that are **checked out** when the online code editor is active.
This makes sense to avoid polluting disk space and is only done for programming exercises which end date is at least 8 weeks in the past.

The LocalVC repositories (the "bare repositories" of the "git server") are not deleted at all, except if you delete the corresponding participation or programming exercises.

We could make the 8 weeks configurable, but I am not sure if this really is required. If you are interested in that, please reopen the issue.
