### ISSUE TITLE
`README.md` not shown in online code editor

### ISSUE THREAD

**Issue by Joshy-R** [ls1intum/Artemis#9214]
### Describe the bug

If a student repository includes a `README.md` file, it is filtered out in the file tree of the online code editor. 
This appears to be some compatibility layer to a legacy type of programming exercises. (See [here](https://github.com/ls1intum/Artemis/blob/1a6169f070398ce4145e232f2a8e935ab4704e06/src/main/webapp/app/exercises/programming/shared/code-editor/file-browser/code-editor-file-browser.component.ts#L518)). 
New exercises that actually intend for some readme are hindered this filtering. 

### To Reproduce

1. Create an exercise.
2. Start exercise and commit a file called `README.md`.
3. Open either the online code editor or viewer.
4. The file will not be visible

### Expected behavior

The file is visible.

### Which version of Artemis are you seeing the problem on?

7.5.0

### What browsers are you seeing the problem on?

Firefox

**Comment by krusche** [comment]
@pzdr7 could you have a look please?
