### ISSUE TITLE
Communication is not easily usable on small screens (e.g. Smartphones)

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#9225]
### Describe the bug

Unfortunately, the Communication UI is not that easily usable on mobile devices like smartphones. Especially, the need for opening of the thread view to answer makes it hard to quickly answer student questions.

### To Reproduce

Open Communication on your smartphone

### Expected behavior

Smartphone layout should be different than Desktop View :)

### Screenshots

![image](https://github.com/user-attachments/assets/e8149a07-afb8-4131-8f6f-d8f90cf532ad)

### Which version of Artemis are you seeing the problem on?

7.5.0

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

FF on iPhone

**Comment by GunniBusch** [comment]
It's not only the communication page but the course page as well. 
The old one was far better!

**Comment by krusche** [comment]
We will optimize it soon for smaller screens (again). There are also mobile apps that can be used. The iOS app is already available in the AppStore. The android version will be available soon.

**Comment by PaRangger** [comment]
The mobile layout of the communication module was improved in #9460
