### ISSUE TITLE
Order in Audit Log is wrong

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#9234]
### Describe the bug

The default ordering of Audit Logs is descending. Nevertheless, the ordering is descending based on pages, but the ordering of a page is ascending. If ordering is descending, the page itself should also be ordered in this manner.

### To Reproduce

Go to Audits and look at the dates

### Expected behavior

Ordering should be correct

### Which version of Artemis are you seeing the problem on?

7.5.0

### What browsers are you seeing the problem on?

Firefox

**Comment by b-fein** [comment]
For me it is newest event first:

![image](https://github.com/user-attachments/assets/ef5aa4f2-07bd-4600-ab48-74ade2a497e3)
