### ISSUE TITLE
Programming Exercsies/Exam Review: Named Tasks are Displayed in Wrong Exercise

### ISSUE THREAD

**Issue by just-max** [ls1intum/Artemis#9253]
### Describe the bug

When reviewing exam results, students can see tasks written into the exercise (`[task][Task Name](test1,test2,...)`). However, instead of displaying the correct task, Artemis is displaying tasks from other exercises. This means that the name, number of passed tests, and the result details when opening the detailed view are all taken from that other task.

### To Reproduce

~~I have not reproduced the issue myself, but presumably creating an exam with at least two programming exercises containing `[task]`s, participating in the exam as a student, and reviewing one's results.~~

1. Create an exam
2. Create two exercise groups, each with a programming exercise (OCaml, not sure if relevant)
3. Set the exercise description of the first to:
  ```
  1. [task][Task in First Exercise]()
  ```
  and the second to
  ```
  1. [task][Task in Second Exercise]()
  ```
4. Create and participate in a test run, then view the summary page

### Expected behavior

Show correct task

### Screenshots

Result of reproduction above:

![image](https://github.com/user-attachments/assets/401be86b-05f6-4e6b-9d5b-ac436d8e7316)

---

Screenshots provided to us by students:

---
This task is actually named "map_acc_tr", whereas "IntPartialOrder" is from a different exercise
![image](https://github.com/user-attachments/assets/bbbd9b1b-f095-44e1-a27e-172fa9f71c63)

---
This tasks here are actually named "top : 'a stack -> 'a option" and "pop : 'a stack -> 'a option * 'a stack", whereas "IntPartialOrder" and "CoordinatePartialOrder" are once again from a different exercise:

![image](https://github.com/user-attachments/assets/26f24f58-c6c4-4c4b-82d5-83de886ae943)

---
The task here is actually called "Grading", the task "push : ..." is from a different exercise.

![image](https://github.com/user-attachments/assets/d3d19591-f362-499f-83c9-34cf7978c8ea)

### Which version of Artemis are you seeing the problem on?

7.5.0

### What browsers are you seeing the problem on?

Other (specify in "Additional context")

### Additional context

Sometimes, reloading helps.

**Comment by jerhard** [comment]
@krusche As the exam review is currently running, and we would ideally finish it within the next days, it would be great if this issue could get assigned a high priority.
