### ISSUE TITLE
`Iris`: Allow enabling for courses only by admin

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#9301]
### Describe the solution you'd like

The use of Iris can lead to high costs. Especially, it's a global configuration. Since multiple chairs are using our Artemis instance, we want to ensure that nobody accidentally enables the Iris feature for their course.
We suggest, to make the configuration option for Iris in a course only available to administrators.

### Describe alternatives you've considered

Allow the configuration of OpenAI tokens in a course. I.e., do not share them :)

**Comment by Hialus** [comment]
This should already be the case. The global Iris settings are solely available to admins. The course settings are partially available to instructors. Admins can set the enabled state and the available variants (part of a current PR), and instructors can select the used variant (part of a current PR). The exercise level settings are fully available to instructors.

**Comment by dfuchss** [comment]
Thanks for the information ; probably I haven't seen it because I'm admin and instructor. The global settings are clearly only for admins . The course wide setting I'll check one more :) Probably closing the Issue tomorrow :)

**Comment by dfuchss** [comment]
Works as expected :)
