### ISSUE TITLE
Programming Exercise/Simplify local setup

### ISSUE THREAD

**Issue by thilo-behnke** [ls1intum/Artemis#933]
### Is your feature request related to a problem?

We have a private setup document for the local programming exercise setup with docker containers for jira, bamboo and bitbucket.
The first time setup process is time consuming and error-prone, because users, app-links, etc. have to be setup.

### Describe the solution you'd like

We could preconfigure the 3 containers with users, app-links, etc., push the pre-configured images to a docker repository provided by the chair and use docker-compose to easily boot up the containers locally.

### Describe alternatives you've considered

Another alternative would be to host the containers on a remote, but this would probably not be easily available to contributors outside of the main Artemis team (?).

**Comment by krusche** [comment]
This was simplified by #1292 and will also be simpler due to #1290.
So I'm closing this issue for now.
