### ISSUE TITLE
Deletion of inactive users does not work if too many users are inactive

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#9364]
### Describe the bug

In #9224 we got the nice feature of deleting inactive users. Nevertheless, this request fails if you want to delete many users (e.g. > 1000).

Http failure response for https://artemis/api/admin/users?login=xyz&login=.....: 400 OK

It's probably because the request is encoded as parameters in the url.

### To Reproduce

See above

### Expected behavior

Inactive users shall be deleted

### Which version of Artemis are you seeing the problem on?

7.5.3

### What browsers are you seeing the problem on?

Firefox

**Comment by b-fein** [comment]
/cc @BaumiCoder 

If the cause is the parameter list, I think a simple fix would then be to create a small DTO like
```java
record InactiveUserLogins(logins: List<String>) {}
```
and send that as POST body rather than via parameters.

**Comment by dfuchss** [comment]
It's not super urgent because I've now used a script for that. But maybe it's important for others as well :)

**Comment by BaumiCoder** [comment]
I can reproduce the bug. I get an even clearer error message:
```
Http failure response for http://localhost:9000/api/admin/users?login=dummy_user1000&login=dummy_user1001&... : 431 Request Header Fields Too Large
```
