### ISSUE TITLE
Opening course dashboard causes error message to appear

### ISSUE THREAD

**Issue by Kooper16** [ls1intum/Artemis#9365]
### Describe the bug

Opening the dashboard of a course in Student View (or as a Student) generates an error message that reads
> Unknown lecture unit type: de.tum.cit.aet.artemis.lecture.domain.ExerciseUnit

### To Reproduce

1. Go to 'Course Overview'
2. Click on a course with a dashboard
3. Red error message in the top right

### Expected behavior

No error message.

### Which version of Artemis are you seeing the problem on?

7.5.3

### What browsers are you seeing the problem on?

Firefox

### Additional context

This error appeared after upgrading from Artemis 7.5.2 to 7.5.3.

**Comment by Strohgelaender** [comment]
@ole-ve Probally related to #9313?

**Comment by krusche** [comment]
This is already fixed. The bugfix will be deployed soon
