### ISSUE TITLE
Programming exercises: Repo access token not used in clone dialogue when in the repository view

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#9380]
### Describe the bug

When on the main page for an exercise in the student view, the `</> Code` button shows the token option:
![image](https://github.com/user-attachments/assets/3156e950-0915-462a-902d-d272c025bbe6)

When in the repository view for the same exercise, the button shows a warning that an account-token should be created:
![image](https://github.com/user-attachments/assets/fea8c632-803b-43be-aaa8-ea94c710855f)

### To Reproduce

Artemis system with token-based VCS cloning enabled.

As student:

1. Use the clone dialogue on the dashboard page. The token is part of the URL.
2. Use the arrow in the clone dialogue to open the repo viewer.
3. Then use the clone dialogue on this page. The token is not part of the URL.

### Expected behavior

The clone button on the repository view page has the same behaviour as the one on the exercise page and uses the participation-specific token.

### Screenshots

See above.

### Which version of Artemis are you seeing the problem on?

7.5.1

### What browsers are you seeing the problem on?

Firefox

**Comment by SimonEntholzer** [comment]
Looking into it :+1:
