### ISSUE TITLE
Programming Exercise/Enable tutor dashboard for programming exercises

### ISSUE THREAD

**Issue by thilo-behnke** [ls1intum/Artemis#940]
### Is your feature request related to a problem?

The tutor course and tutor exercise dashboards can't be used atm for programming exercises.

### Describe the solution you'd like

Enable the tutor dashboards for programming exercises.
Related to https://github.com/ls1intum/Artemis/issues/932.

**Acceptance criteria:**
- Show programming exercises in dashboards with setting semi automatic enabled
- Tutor exercise dashboard: Get random submission for assessment (compare modeling / text submission)

**Out of scope for first iteration:**
- more feedback, complaints
- tutor leaderboard
- Your Status column
- Assessment Due Date column

**Comment by thilo-behnke** [comment]
Dependent of https://github.com/ls1intum/Artemis/pull/930.

**Comment by jerhard** [comment]
> Out of scope for first iteration:
> 
>     more feedback, complaints

Can you give an estimate on when the complaint feature for programming exercises will be implemented and eventually available in the working instance of Artemis? 
This has an impact on whether we need to provide some other means for the students to complain about  their tutor assessments. 

Related to this, will it be possible for students to complain about those exercise assessments that were done before the feature release?

**Comment by krusche** [comment]
Complaints by students are implemented. @maxr96 is currently working on the implementation that tutors can respond to these complaints
