### ISSUE TITLE
Invalid login message when using a valid login

### ISSUE THREAD

**Issue by Kooper16** [ls1intum/Artemis#9402]
### Describe the bug

When typing in a username in the login page, a message saying "Invalid login" appears under the textbox. I noticed it happening when the username is less than 4 characters long or has a capital letter that is not at the start (eg. "tesT" is invalid but "test" isn't). It is still possible to login but the message may confuse users.

### To Reproduce

1. Go to login page
2. Click on the "Login or Email" textbox.
3. Type "tesT"

### Expected behavior

No "Invalid login" message until I click on "Sign in" and the username/email is actually invalid.

### Which version of Artemis are you seeing the problem on?

7.5.5

### What browsers are you seeing the problem on?

Firefox

**Comment by Kooper16** [comment]
https://ls14-artemis.cs.tu-dortmund.de/
![image](https://github.com/user-attachments/assets/a6fae8a4-f990-487a-ae33-081c1235faed)

**Comment by krusche** [comment]
I found the issue. The default regex is wrong. Will fix it

**Comment by krusche** [comment]
Fixed in 0aa3aaf4632f4c694d40f8a72552e2ffdefbd0c6
