### ISSUE TITLE
Chrome on MacOS: Misplaced tutorial video view when bookmark bar is showing

### ISSUE THREAD

**Issue by lgerhardt45** [ls1intum/Artemis#943]
### Describe the bug
Using Chrome on MacOS I found the tutorial view being misplaced (some of the top area is cut off) when a video is embedded. When I hid my bookmarks bar, it was placed correctly again. See screenshots attached below.

#### To Reproduce
1. Open Artemis in Chrome on MacOS 
2. Unhide your bookmark bar
3. Click through tutorial until a step with a video appears

#### Expected behavior
The tutorial view should be placed centered as when the bookmark bar is hidden

#### Screenshots
![Artemis Tutorial Video with Bookmark Bar](https://user-images.githubusercontent.com/40395744/66841488-0a4e8280-ef6a-11e9-861d-f5a1f3394a9f.png)
![Artemis Tutorial Video without Bookmark Bar](https://user-images.githubusercontent.com/40395744/66841501-120e2700-ef6a-11e9-8e64-64ac50bc656e.png)
![Artemis Tutorial Non-Video with Bookmark Bar](https://user-images.githubusercontent.com/40395744/66841518-189c9e80-ef6a-11e9-9151-cddf01e00fc0.png)

### Environment
<details><pre>
 - OS: MacOS Catalina
 - Browser: Chrome
</pre></details>

**Comment by lovaiible** [comment]
Hi @lgerhardt45,
thanks for reporting the bug. I will have a look at it and fix it.

**Comment by lovaiible** [comment]
Hi @lgerhardt45,
we have deployed the bugfix to the production system. Can you verify that this issue is now fixed for you?

**Comment by lgerhardt45** [comment]
The issue is fixed, thanks a lot!
