### ISSUE TITLE
New Exercises not visible for students

### ISSUE THREAD

**Issue by ValentinHerrmann** [ls1intum/Artemis#9433]
### Describe the bug

New exercises are not visible in the course overview for the students but for instructors (in student view). The direct link to the exercises is working properly. Whether or not you have a release time does not make a difference.

### To Reproduce

1. Create quiz exercise
2. Make sure the release time is in the past or no release time exists
3. Go to an account which is registered as student in the course an see the bug: Quiz exercise not visible

### Expected behavior

The Quiz exercise is expected to be visible for students in the exercise overview.

### Which version of Artemis are you seeing the problem on?

7.5.6

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge, Firefox

**Comment by Strohgelaender** [comment]
Are you using an "online course" (Moodle / Mebis integration)? If yes, here the exercises are expected to be hidden and should only be accessed via the external tool.

**Comment by ValentinHerrmann** [comment]
Thanks, that solved the problem.
