### ISSUE TITLE
General manual feedback not fully shown in feedback view

### ISSUE THREAD

**Issue by flaferty** [ls1intum/Artemis#9434]
### Describe the bug

After professor uploaded feedback to exercise, while trying to extend it, it's still not being shown properly, ending by [...].
Photo is attached.
The issue is same for tablet and phone version, even while using "Desktop site" functionality

### To Reproduce

1. Go to 'exercise
2. Click on last review and then on 'feedback'
3. Scroll down to 'end of feedback'
4. Not be able to extend feedback any more even though it has some more text
5. See error

### Expected behavior

After expanding feedback I expected to see the whole text in phone version

### Screenshots

![Screenshot_20241007_150610_Chrome](https://github.com/user-attachments/assets/37be756e-870d-4b0a-83f5-7eb5a7c8b867)

### Which version of Artemis are you seeing the problem on?

7.5.6

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by krusche** [comment]
This might not be limited to smartphones and might be a general issue

**Comment by upsj** [comment]
For additional context, I saw the same issue inside the text input element when looking at the previously saved description. This might be an issue of the long feedback never making it to the database, or potentially also the textview only showing the shortened version, and the client overwriting the long feedback by a shortened version when clicking "Save".

**Comment by kaancayli** [comment]
I had worked on an [issue](https://github.com/ls1intum/Artemis/pull/7792) with long feedbacks a while ago. Might it be related?

**Comment by b-fein** [comment]
Something to test to debug this: The long feedback is only loaded from the server in the client when unfolding the feedback in the list. You can open the browser devtools before doing that and check if there is a network request that fetches the long feedback. That should should if the feedback is successfully returned to the client (and its just a visual issue of not displaying it in the client), or if there is another problem as well where the feedback is missing and the network request fails.
