### ISSUE TITLE
`Adaptive learning`: Add weight to links between learning objects and competencies

### ISSUE THREAD

**Issue by JohannesStoehr** [ls1intum/Artemis#9446]
# Feature Proposal
> Spec Version 0.2.0

### Problem  
The current system links learning objects directly to competencies without any way of quantifying how much a learning object contributes to or is related to a specific competency. This lacks the ability to fine-tune so Artemis cannot determine the importance of a learning object for a competency. Some might only cover parts of a competency while others cover the core principles and should therefore be more important for the competency.

### Motivation 
The introduction a weight for these links is necessary to enhance the adaptive learning experience. By assigning these weights, instructors can quantify the relevance of each learning object for specific competencies. This will allow for more precise learning paths and guidance for students in areas where they need improvement. Affected users include instructors, who will be able to configure these links, and students, who will benefit from more accurate learning recommendations.

### Existing (Problematic) Solution / System 
Currently the learning objects and competencies directly store their linked counterparts.
<img width="623" alt="Bildschirmfoto 2024-10-09 um 15 16 11" src="https://github.com/user-attachments/assets/ead77865-ca05-4e75-bb7b-67b3dcf6da6d">

### Proposed System 
To also store the weight, we need an additional class between the two to store the weight.

### Requirements 
1. FR: Manage Competency Links: Artemis must allow the input of a weight when learning objects and competencies are linked.
2. FR: Use weight for learning path: Artemis should use the new weight to determine important exercises and priorities them when selecting exercises for the learning path.
3. FR: Use weight for mastery calculation: Artemis should use the weight to determine the mastery of a student by lowering the confidence if the student is worse in more important learning objects and vice versa.

### Analysis Object Model 
<img width="958" alt="Bildschirmfoto 2024-10-09 um 15 17 07" src="https://github.com/user-attachments/assets/edffa893-2959-4a5c-80f4-689619c5efd8">

### Subsystem Decomposition
The endpoints to link competencies to learning objects must now also take the weight as a parameter.

### Persistent Data Management
Adapt the existing `competency_exercise` and `competency_lecture_unit` table to also include a weight with a default value of 1 for existing links.

## UI/UX Design
Add a dropdown with 3-5 choices (weak-strong) after each selected competency so the instructor can choose a weight for each connection.
<img width="510" alt="Bildschirmfoto 2024-10-09 um 15 24 55" src="https://github.com/user-attachments/assets/3292b99b-c627-45c8-9adb-d783360571db">

**Comment by MaximilianAnzinger** [comment]
Rather than an input field I'd like to use some simplification, e.g., weak, medium, strong. With default value `medium`. In the backend we can still map it to a double for future ML plans.  👍
