### ISSUE TITLE
UI bug related to Guided tour

### ISSUE THREAD

**Issue by Garfield96** [ls1intum/Artemis#946]
### Describe the bug
A warning related to the guided tour is shown although the guided tour is not active.

#### To Reproduce
1. Make sure browser window is maximized (full screen or close to full screen)
2. Go to the main page there all courses are listed
3. The guided tour should not pop up (it should be done in the past already)
4. Decrease the width of the browser window to tablet or even smartphone size
5. Although the tour was not open before resizing the window, a warning for the guided tour shows up (see screenshot). This only happens once. Afterwards, resizing the window has no effect until the page is reloaded.

#### Expected behavior
No warning, since the tour was not open.

#### Screenshots
![image](https://user-images.githubusercontent.com/15248220/66857672-0cbfd500-ef88-11e9-97a3-c0372fa6e1ce.png)

### Environment
<details><pre>
 - OS: Debian Buster
 - Browser: Mozilla Firefox
 - Version: 60.9.0esr (64-bit)
</pre></details>

**Comment by lovaiible** [comment]
Hi @Garfield96,
thanks for reporting the issue. We have deployed the bugfix to the production system. Can you verify that this issue is now fixed for you?

**Comment by Garfield96** [comment]
@lovaiible Thank you. The issue is fixed.
