### ISSUE TITLE
UI content too small when creating / editing programming exercises

### ISSUE THREAD

**Issue by Garfield96** [ls1intum/Artemis#947]
### Describe the bug
The width of the content in the creation dialog for programming exercises is not adapted to smaller screen sizes. This makes working with multiple windows problematic since huge parts of the description are cut away.

#### To Reproduce
1. Go to 'Generate new Programming Exercise'
2. Adjust window width

#### Screenshots
![image](https://user-images.githubusercontent.com/15248220/66859610-e69c3400-ef8b-11e9-9fe2-e382f77a084e.png)

#### Expected behavior
Content should take up full width for smaller window sizes:

![image](https://user-images.githubusercontent.com/15248220/66859832-501c4280-ef8c-11e9-8030-98997ec235a8.png)

### Environment

<details><pre>
 - OS: Debian Buster
 - Browser: Mozilla Firefox
 - Version: 60.9.0esr (64-bit)
</pre></details>

**Comment by thilo-behnke** [comment]
@ungaralex Can this be closed?

**Comment by Garfield96** [comment]
Thank you very much for implementing/fixing this.
