### ISSUE TITLE
Communication: Different Types of Reactions

### ISSUE THREAD

**Issue by HawKhiem** [ls1intum/Artemis#9507]
### Describe the bug

![image](https://github.com/user-attachments/assets/bb90f32f-a789-43eb-acf5-6a29222e88ea)
Is it intentional that one can both upvote and downvote a message?

### To Reproduce

1. Go to any test server (I used TS3)
2. Click on any course with Communication
3. React to a message

### Expected behavior

I don't know if this is a feature of Artemis for one to both upvote and downvote at the same time but one of two sounds more reasonable for me.

### Which version of Artemis are you seeing the problem on?

7.6.1

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by sachmii** [comment]
This is not really a upvote or downvote feature but rather reacting with emojis to a message and as one can react with multiple different emojis, you can "upvote" and "downvote" at the same time.

**Comment by HawKhiem** [comment]
Ah I see, thank you!
