### ISSUE TITLE
Make "Questions and Answers" optional

### ISSUE THREAD

**Issue by Garfield96** [ls1intum/Artemis#953]
### Is your feature request related to a problem?
We would like to manage all questions regarding course topics and programming exercises on a single platform (Moodle). Unfortunately, the "Questions and Answers" tab in Artemis cannot be deactivated.  

### Describe the solution you'd like
Make "Questions and Answers" optional for each exercise.

**Comment by jerhard** [comment]
Disabling the questions and answers is also an important feature needed for the use of Artemis in electronic exams. In these situations one would not like to provide the students with a means to communicate among each other.

**Comment by krusche** [comment]
I just added a new issue that covers multiple changes to the course settings #1221 so I will close this issue.
