### ISSUE TITLE
Communication Embedded Links are duplicated

### ISSUE THREAD

**Issue by janthoXO** [ls1intum/Artemis#9530]
### Describe the bug

When posting a link in the FAQ with a preview, the preview gets displayed in different threads

### To Reproduce

1. Go to FAQ post
2. Post as a reply a link with preview e.g github
3. Click on the replies of another thread
4. See that the preview is visible there as well

### Expected behavior

The preview should only be in the thread where the link was posted

### Screenshots

https://github.com/user-attachments/assets/9631b90b-2433-415c-b485-dccfa4a63676

### Which version of Artemis are you seeing the problem on?

7.6.0

### What browsers are you seeing the problem on?

Chrome

**Comment by krusche** [comment]
Thanks for reporting this issue. We will fix it asap
