### ISSUE TITLE
Thread message not readable without toggling sidebar.

### ISSUE THREAD

**Issue by sachmii** [ls1intum/Artemis#9535]
### Describe the solution you'd like

When I open a thread in a communication channel, the text is cut off at the right edge and cannot be read. You first have to click on “toggle sidebar”. But I think it would be helpful if you could read the message directly without having to toggle the sidebar.
Browser: Safari, Artemis Version: 7.6.0

<img width="1240" alt="Bildschirmfoto 2024-10-20 um 19 51 40" src="https://github.com/user-attachments/assets/c1e57769-9be7-40a0-adb3-4d523766d877">

**Comment by PaRangger** [comment]
Fixed in #9474
