### ISSUE TITLE
Communication: Channels Open at the first message

### ISSUE THREAD

**Issue by StateofDisarray** [ls1intum/Artemis#9537]
### Is your feature request related to a problem?

This is a very small issue, but opening a message channel on artemis starts at the first message. rather than the last message. This quickly becomes inconvenient for message channels with a lot of people, such as ITP. 

I use Firefox version 131.0.3 and Safari on mobile with the latest ios version

### Describe the solution you'd like

I made a tampermonkey script to do the following

 const scrollableDiv = document.getElementById('scrollableDiv');
    scrollableDiv.scrollTop = scrollableDiv.scrollHeight;

**Comment by ahbitaqu** [comment]
+1

**Comment by StateofDisarray** [comment]
Implemented
