### ISSUE TITLE
ID of new FAQ not rendered in Popup

### ISSUE THREAD

**Issue by flbrgit** [ls1intum/Artemis#9549]
### Describe the bug

After creating a new FAQ as a tutor, the ID of the new FAQ is not rendered inside the Popup, instead the template placeholder "{{ id }}" is shown.

### To Reproduce

Follow the steps provided in PR #9477 and notice the popup after creating a new FAQ as a tutor.

### Expected behavior

The template placeholder "{{ id }}" should be replaced by a valid ID of the corresponding FAQ

### Screenshots

![Create _ Practical Course_ Interactive Learning WS24_25 - Vivaldi 20 10 2024 12_40_25](https://github.com/user-attachments/assets/d7970f2f-8913-45d1-bb81-615ad6e77806)

### Which version of Artemis are you seeing the problem on?

Artemis v7.6.1 with PR #9477

### What browsers are you seeing the problem on?

Chrome

**Comment by cremertim** [comment]
This issue was already fixed in the PR #9477, so i close this issue
