### ISSUE TITLE
[Meta] Issue labelling bot is overeager

### ISSUE THREAD

**Issue by b-fein** [ls1intum/Artemis#9563]
### Describe the bug

Many unrelated labels are added to issues automatically. They are also added again after editing the issue description. This makes it hard to see actually relevant labels.

Examples for problems:

- Every issue is labelled `text` since it contains the phrase ‘Additional Con*text*’
  - Maybe also `lecture` due to a partial match for `text unit`?
- E.g. #9541 was labelled `iris` since it contains ‘Jetbr*ai*ns’
  - This issue will probably also receive the label `iris` due to the ‘ai’ in contains.
 - Also #9541 was labelled `lti` due to containing the word ‘mu*lti*ple’
 - There are also keywords that are too generic in the labeller config:
   - `online` can not only refer to `lectures`, but could also be relevant for the online editor
   - `user` appears frequently without being related to user management (`core` label)
   - maybe `project` for label `programming`
   - `text` for label `text`
   - `drag` for `quiz` since this can also refer to the draggable assessment instructions for manual assessment

### To Reproduce

See issue list.

### Expected behavior

Probably it would be best to match on whole words instead of partial words. Additionally, the config could be refined to remove the ambiguous terms.
It’s easier to manually add additional labels once than having to remove them after each time editing the issue description.

**Comment by MaximilianAnzinger** [comment]
We've discussed this in our maintainer meeting. We came to the conclusion that every maintainer will adjust the settings for the respective features/modules.
