### ISSUE TITLE
Unauthorized Access Popup Appears Despite Full Access

### ISSUE THREAD

**Issue by Abus00** [ls1intum/Artemis#9577]
### Describe the bug

When I go to an exercise and press "View " as a tutor, a red message pops up in the upper right corner saying "You are not authorized to access this page." Despite this message, I still have full access to the exercise solutions (as expected). However, the issue is that the message still pops up and sometimes even  repeats, stacking 2 to 3 times, making it a bit annoying (espacially on a smaller screen).

### To Reproduce

1. Go to an exercise as a tutor
2. Click on 'View'
3. See the "You are not authorized to access this page" pop up

### Expected behavior

That there is no such red "unauthorized" message.

### Screenshots

![Screenshot 2024-10-24 082038](https://github.com/user-attachments/assets/b2c27b25-bb0b-4458-a237-39333348ce9a)

### Which version of Artemis are you seeing the problem on?

7.6.1

### What browsers are you seeing the problem on?

Chrome

**Comment by Strohgelaender** [comment]
Is your course using Iris? If yes, #7797 might be the cause.

**Comment by Abus00** [comment]
Yes, that’s probably it. Due to the failed Iris fetches, I reviewed the Iris issues but couldn’t find anything similar, so I assumed it might be unrelated. Closing this issue now. Thanks!
