### ISSUE TITLE
The button Open in <CodeEditor> is currently not working

### ISSUE THREAD

**Issue by alekspetrov9e** [ls1intum/Artemis#9578]
### Describe the bug

After I customized in Settings the IDE I want to use for opening programming exercises to be Intellij, I tried to use this feature but there was no result. IntelliJ was expected to open directly with the cloned repository.

### To Reproduce

1. Open a programming exercise
2. Click on </>Code
3. Click on Open in Editor

### Expected behavior

I expect my Intellij to start with the cloned repository inside.

### Which version of Artemis are you seeing the problem on?

7.6.2

### What browsers are you seeing the problem on?

Chrome

**Comment by Strohgelaender** [comment]
The open in IntelliJ button only works if you have installed IntelliJ via the JetBrains toolbox. Unfortually, IntelliJ as a standalone programm does not offer such a protocoll.
