### ISSUE TITLE
Never ending Building and empty assert message

### ISSUE THREAD

**Issue by JoejoeSt** [ls1intum/Artemis#958]
### Describe the bug
One Student had the problem that he only got a "building" but no error message after multiple submits. I as an instructor in the class see an empty assert statement under the scores tab of Artemis. Only under the build plan id on bamboobruegge.in.tum.de was the correct error message for the assert.
This also happened after a build failure because of a wrong encoding.

#### To Reproduce
1. The exercise expects two classes with a main() method each.
2. They are tested by the structure test that ist run sequential.
3. He put both classes in the same file.
4. He got a never ending build cycle.
4.1 After reloading he gets a "no result" on the front page of Artemis
5. Even after committing the classes in separate files the building message was still visible for him bit no other error message.
6. In the scores view section of Artemis appears a "build failure" message for that student and if you click on it you see the empty assert statement.
7. On Bamboobruegge is the correct error message viewable. 

#### Expected behavior
Correct output of error message

#### Screenshots
Students view:
![Selection_109](https://user-images.githubusercontent.com/38322605/67107871-92809200-f1cd-11e9-9f03-d251fa613d37.png)
![Course details - Google Chrome_112](https://user-images.githubusercontent.com/38322605/67107876-957b8280-f1cd-11e9-98e7-78c3c7852bff.png)

Errormessage on bamboobruegge:
Correct error message:
<img width="485" alt="Bildschirmfoto 2019-10-18 um 17 28 42" src="https://user-images.githubusercontent.com/38322605/67107951-b5ab4180-f1cd-11e9-8412-aa68c4fedbc7.png">

First error message before the assert error:
<img width="979" alt="Bildschirmfoto 2019-10-18 um 17 28 53" src="https://user-images.githubusercontent.com/38322605/67107956-b9d75f00-f1cd-11e9-8cf4-3df32e72c710.png">

The error message on Artemis in the scores view was something like:
"org.junit.ComparisonFailure: expected: but was: "

### Environment
<details><pre>
 Artemis 3.8.4
</pre></details>

**Comment by JoejoeSt** [comment]
The empty assert statement appeared more often even in Repositories without prior build failures.
The empty assert statement can be seen by the instructor in the scores view as well as by the student in the respective exercise.

**Comment by krusche** [comment]
This has been fixed. Wrong encodings have been the problem.
Bamboo enforces now the UTF8 encoding to prevent such issue.
