### ISSUE TITLE
Notification for direct messages I was mentioned in

### ISSUE THREAD

**Issue by sachmii** [ls1intum/Artemis#9588]
### Describe the bug

I received a notification of a direct message even though I am not part of the chat. Is this intended behaviour?

![Bildschirmfoto 2024-10-24 um 21 32 31](https://github.com/user-attachments/assets/de2d099b-c3be-4620-98bb-9e9da665ed3c)
<img width="799" alt="Bildschirmfoto 2024-10-24 um 21 35 12" src="https://github.com/user-attachments/assets/a32d48d8-0e88-4597-9a18-7eb97dc48dd9">

### To Reproduce

1. Let someone text another person (but not you) a message where your name is mentioned in.
2. See a notification.

### Expected behavior

No notification appears (i guess?)

### Which version of Artemis are you seeing the problem on?

7.6.2

### What browsers are you seeing the problem on?

Safari

**Comment by PaRangger** [comment]
This was addressed in #9814 😄
