### ISSUE TITLE
Communication: Black box in Announcement channel

### ISSUE THREAD

**Issue by HawKhiem** [ls1intum/Artemis#9597]
### Is your feature request related to a problem?

I notice there is a black region in the announcement channel. I understand this is due to the fact that people cant comment on the announcement channel, and that black region is simply the chat box, but it looks kind of odd and unaesthetic in my opinion

![Screenshot 2024-10-26 000117](https://github.com/user-attachments/assets/25310e9e-1f42-4ab6-a404-fd544da34ef9)

### Describe the solution you'd like

Should we somehow remove that region?

**Comment by PaRangger** [comment]
This was addressed in #9664. 😄
