### ISSUE TITLE
Replace proprietary solution with Mermaid

### ISSUE THREAD

**Issue by MaximilianAnzinger** [ls1intum/Artemis#9607]
### Is your feature request related to a problem?

As far as I understand Apollon uses a proprietary standard to store the diagrams. This makes the development inefficient & incompatible with essentially everything else.

### Describe the solution you'd like

Make Apollon reuse [Mermaid](https://mermaid.js.org/intro/getting-started.html) and allow users to reuse the models for various different projects.

**Comment by krusche** [comment]
Apollon is intended as a graphical modeling editor, not as a text-based one. It explicitly uses coordinates and allows users to drag elements to the desired position. As far as I can see from the Mermaid definition (which is rather compatible to PlantUML), they follow a different, more textual description. I don't think both philosophies are compatible with each other.
