### ISSUE TITLE
Communication: Add sub-groups to communication channels. 

### ISSUE THREAD

**Issue by Feras797** [ls1intum/Artemis#9621]
### Is your feature request related to a problem?

In this course the amount of sub-channels will grow and it will be annoying to scroll to the current one after some time: 
<img width="265" alt="image" src="https://github.com/user-attachments/assets/047c16fb-d7be-4207-bc1e-af7e4bf75e37">

### Describe the solution you'd like

It would be nice to have a sub-group/folder in which the channels are stored. E.g. for above example: "Past" and "Current", where both can be expanded. 

### Describe alternatives you've considered

keeping the current system works as well, but channels can get very convoluted over time.

**Comment by krusche** [comment]
Good suggestion, we can definitely take the due date into account.
A workaround is to hide channels that are not interesting to you any more
