### ISSUE TITLE
Option to remove or deregister from a course. 

### ISSUE THREAD

**Issue by raj7vasani** [ls1intum/Artemis#9630]
### Is your feature request related to a problem?

I have, or had in past registered for several courses, sometimes just to see the exercises or sometimes by accidently clicking on the enroll button. I dont know if it exists, but I would like to have an option to deregister from a course if I am no longer planning on doing it further. I keep getting unnecessary notifications for that respective course. 

### Describe the solution you'd like

A deregister button within the course so that I can remove it from my current courses. Another option would be showing a current courses list on each account which could be accessed via 'My Courses' button and there on the right side an option to deregister(somewhat similar to tumonline).

**Comment by JohannesStoehr** [comment]
This is already implemented but the instructor of the course has to activate it.
