### ISSUE TITLE
"Unenroll"

### ISSUE THREAD

**Issue by scuffed11** [ls1intum/Artemis#9632]
### Describe the bug

In some courses there is no "Unenroll"-Button making leaving them when u e. g. joined accidentally impossilble

### To Reproduce

.

### Expected behavior

Being able to leave Courses

### Screenshots

<img width="216" alt="Bildschirmfoto 2024-10-29 um 17 30 39" src="https://github.com/user-attachments/assets/8ecd92ce-a2b3-49df-a683-f71c8f98f8ae">

### Which version of Artemis are you seeing the problem on?

most recent

### What browsers are you seeing the problem on?

Safari

**Comment by Strohgelaender** [comment]
This is not a bug. The instructors can specify an unenrolment period, during which unenrollment is possible and the button is shown. If the button is not shown, this means that the Instructor set up the course such that unenrolment is currently not possible.
