### ISSUE TITLE
Communication: Show who viewed a message in group chats

### ISSUE THREAD

**Issue by Feras797** [ls1intum/Artemis#9634]
### Is your feature request related to a problem?

In the ITP course I have a private group of students that attend my tutorial. 
When I send a message I have no clue if the students read it or if I should tag them. 
This functionality is similar to e.g. Whatsapp group messages. 

### Describe the solution you'd like

For this purpose it would be great to have the option to see who viewed my message. Then I would be able to tag those students that did not read my message. 

### Describe alternatives you've considered

Add small double check-marks in a group message to signal that everyone read the message.

**Comment by krusche** [comment]
Due to data privacy reasons, we cannot implement this feature. In Slack, you also cannot see who has seen a message. You can e.g. ask them to reply with 👍 to confirm that they have read the message
