### ISSUE TITLE
Mark messages for later processing

### ISSUE THREAD

**Issue by simonbohnen** [ls1intum/Artemis#9639]
### Is your feature request related to a problem?

When I have a lot of unread messages, I would like to screen them quickly to see which ones I can answer right now. However, most of them cannot be answered instantly. Marking them for later processing would be useful.

### Describe the solution you'd like

Slack's "Catch up" feature:
<img width="195" alt="Screenshot 2024-10-30 at 10 00 09 AM" src="https://github.com/user-attachments/assets/3fb20d73-7019-4b5a-afdd-1b0a8d818e6a">

### Describe alternatives you've considered

- Marking messages as unread, e.g. like on WhatsApp
- Having a "Save for later" button like Slack:
  - <img width="432" alt="Screenshot 2024-10-30 at 10 01 22 AM" src="https://github.com/user-attachments/assets/641c19fe-3189-4a5f-a710-6bea139f1ea0">

**Comment by krusche** [comment]
We already have "Save for Later" on our roadmap and will implement this in the next months. Stay tuned
