### ISSUE TITLE
'Lecture upload PDF fail'

### ISSUE THREAD

**Issue by Santia-go** [ls1intum/Artemis#9646]
### Describe the bug

In chrome or Brave (chromium) fail the upload process to submit a PDF file as a unit. 

### To Reproduce

1. Upload a PDF in a lecture as a unit
2. Verify it fails
3. Only works with Safari

### Expected behavior

It should be possible to upload a PDF file as a unit. 

### Which version of Artemis are you seeing the problem on?

7.6.4

### What browsers are you seeing the problem on?

Chrome, Other (specify in "Additional context")

### Additional context

Brave

**Comment by florian-glombik** [comment]
This appears to be a general issue with Chroium based browsers right now and not under our control, see issue https://github.com/ls1intum/Artemis/issues/9168 and comment https://github.com/ls1intum/Artemis/issues/9168#issuecomment-2452716030
