### ISSUE TITLE
No complaint buton

### ISSUE THREAD

**Issue by xotaro** [ls1intum/Artemis#9670]
### Describe the bug

After submission and grading of an UML, I couldnt find the complaint button or even the reviews/assessments on the graph.

### To Reproduce

1. Go to UML excercise
2. Click on View result

### Expected behavior

Find Complaint button and see the assessment

### Screenshots

![image](https://github.com/user-attachments/assets/eea31c7d-632c-4497-b0f5-0675dbbc69d1)
![image](https://github.com/user-attachments/assets/330b12e0-2d8d-4625-83cb-87f834d37db6)

### Which version of Artemis are you seeing the problem on?

7.6.5

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

**Comment by maximiliansoelch** [comment]
In your screenshots, you do not have a graded result. Therefore, you also can not complain about the result.
