### ISSUE TITLE
Can't upload files for Lecture and Exercise

### ISSUE THREAD

**Issue by QKGitCn** [ls1intum/Artemis#9732]
### Describe the bug

Course instructors can't upload attachments to lecture instances.
Students can't upload PDF for their homework

### To Reproduce

[**Course Management ->**](https://artemis.ase.in.tum.de/course-management)
[**Introduction to Hardware Design Languages and Tools (WS24/25) ->**](https://artemis.ase.in.tum.de/course-management/406)
[**Lectures ->**](https://artemis.ase.in.tum.de/course-management/406/lectures)
[**Part-3 ->**](https://artemis.ase.in.tum.de/course-management/406/lectures/1234)
[**Attachments of lecture**](https://artemis.ase.in.tum.de/course-management/406/lectures/1234/attachments)

Then I choose the file that I want to upload ->

Click: Save Attachment

See error
**Http failure response for https://artemis.ase.in.tum.de/api/attachments: 400 OK**

### Expected behavior

Error: 

Bad Request.

**Http failure response for https://artemis.ase.in.tum.de/api/attachments: 400 OK**

### Screenshots

![image](https://github.com/user-attachments/assets/ca448ad4-57ee-4063-899c-21b06e7f3414)
![image](https://github.com/user-attachments/assets/e54b410e-f8a8-473b-a940-b33a7622a616)

![image](https://github.com/user-attachments/assets/33ebb1d0-e1e0-48cf-a295-e676877d3837)

### Which version of Artemis are you seeing the problem on?

7.7.0

### What browsers are you seeing the problem on?

Chrome

### Additional context

browser MS Edge doesn't work as well.

**Comment by krusche** [comment]
Thanks for reporting this issue. This is a known bug with Chrome/Chromium based browsers. It works on Firefox and Safari  and should be fixed in Chrome 132.

We are currently trying to implement a technical workaround until the new chrome version is released
