### ISSUE TITLE
Clicking on the Complain button appears to do Nothing

### ISSUE THREAD

**Issue by Malekos74** [ls1intum/Artemis#9735]
### Describe the bug

Clicking on the complain button appears to do nothing since the complain tab gets expanded down and one needs to scroll to see the contents

### To Reproduce

1. Go to a course that has a text exercice as a student
2. Start the exercice (type whatever)
3. Log in as a tutor or instructor and grade the exercice
4. Login as the original student and open your assesement
5. Click on the complain button
6. You will notice that nothing apparently happened, try scrolling down and you should see the text box where you can write the complaint.

### Expected behavior

Clicking on the complaint button should automatically expand the parent div in order to make it clear to the students that they can indeed do the complaint. Instead of having a scroll bar, the overflow should be handeled differently by showing it.

### Screenshots

Before clicking on the complain
![image](https://github.com/user-attachments/assets/4e83c71a-983e-439d-b31c-b53667e8cd25)
After clicking on the complain
![image](https://github.com/user-attachments/assets/d465ba22-832f-44b1-9088-4cf1c9e5a2e7)

### Which version of Artemis are you seeing the problem on?

7.7.0

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge, Firefox

**Comment by krusche** [comment]
A simple workaround could be to scroll down shortly after the user had clicked on the complain button

**Comment by badkeyy** [comment]
I will have a look at this

**Comment by Malekos74** [comment]
It's okay, I thought assigning myself only means that I reported the issue :)
