### ISSUE TITLE
Direct Messages no longer Working

### ISSUE THREAD

**Issue by Malekos74** [ls1intum/Artemis#9760]
### Describe the bug

This is how sending a private message is supposed to work.
![image](https://github.com/user-attachments/assets/372a3549-51e5-4c71-ae83-92cad8833670)
However the (+) is no longer visible next to the Direct Messages tab

### To Reproduce

1. Go to a course that has communication activated
2. Notice that the feature no longer works

### Expected behavior

One can create private messages when the communication is activated for the course

### Screenshots

![image](https://github.com/user-attachments/assets/4e5e0841-478b-4e92-a742-5da25a7e8f8b)

### Which version of Artemis are you seeing the problem on?

7.7.0

### What browsers are you seeing the problem on?

Chrome

**Comment by asliayk** [comment]
This feature still works; it has simply been relocated:

You can create a direct message using the + button next to the search bar.

![image](https://github.com/user-attachments/assets/8d738c38-dcc0-43d0-a4f8-fb8dfdc56175)

**Comment by Malekos74** [comment]
Thanks for the notice
