### ISSUE TITLE
Missing token when cloning exercise

### ISSUE THREAD

**Issue by carlobortolan** [ls1intum/Artemis#9770]
### Describe the bug

When starting an exercise and selecting `Token` as the cloning method, the shown URL is missing the actual token.
Currently, the URL looks like this: `https://<tum-id>@artemis.tum.de/git/<repository>.git`,
but it should look somewhat like: `https://<tum-id>:<token>@artemis.cit.tum.de/git/<repository>.git`.

### To Reproduce

1. Open an exercise (e.g., https://artemis.ase.in.tum.de/courses/377/exercises/15004)
3. Click on the `Code` button
4. Select `Token` as cloning method
5. See the wrong git URL, which is missing the token

### Expected behavior

The correct URL should be returned when selecting `Token` as the cloning method.
E.g., `https://ge42abc:<insert-token>@artemis.cit.tum.de/git/PSE24W02E04/pse24w02e04-ge42abc.git`.

### Screenshots

See this screenshot: 

![image](https://github.com/user-attachments/assets/11492e50-dc66-4738-b848-1520676ad774)

> [!note]
> I removed my tum-id in the screenshot. The full URL looks like this: `https://<my-tum-id>@artemis.tum.de/git/PSE24W03E04/pse24w03e04-<my-tum-id>.git` 

### Which version of Artemis are you seeing the problem on?

7.7.0

### What browsers are you seeing the problem on?

Microsoft Edge, Firefox, Other (specify in "Additional context")

### Additional context

Tested with the following browsers:
- Mozilla Firefox for Manjaro Linux, 131.0.3 (64-bit)
- Chromium Version 130.0.6723.116 (Official Build) Arch Linux (64-bit)
- Microsoft Edge Version 130.0.2849.80 (Official Build) Win11 (64-bit)

**Comment by b-fein** [comment]
Will probably be fixed by #9736.

/cc @SimonEntholzer
