### ISSUE TITLE
Communication: New line inside of sentence does not work. 

### ISSUE THREAD

**Issue by Feras797** [ls1intum/Artemis#9783]
### Describe the bug

When I press cmd + ⏎ inside of a sentence in a message, it does not move the text to right of the cursor to the next line. 
Instead only the cursor jumps to the next line. 

https://github.com/user-attachments/assets/c483aa27-c3ef-4651-96d1-1a77fac2a19e

### To Reproduce

1. write a message in communications
2. go move the cursor to the left
3. press cmd + ⏎

### Expected behavior

The text to the right of the cursor should move to the next line

### Which version of Artemis are you seeing the problem on?

7.7.0

### What browsers are you seeing the problem on?

Chrome

**Comment by anian03** [comment]
Have you tried using shift + ⏎? That works for me without any issue, and is the same on other websites/apps as well.
I never heard of cmd + ⏎ for doing this to be honest 😅
