### ISSUE TITLE
Artemis not working correctly at Safari

### ISSUE THREAD

**Issue by floralatz** [ls1intum/Artemis#980]
### Describe the bug

The progress of my exercise is not beeing displayed at all in safari, however, it works when opening chrome. Instead it shows a "You have no results yet"  
<img width="1199" alt="Bildschirmfoto 2019-10-23 um 09 42 31" src="https://user-images.githubusercontent.com/56912719/67371925-6ffbc980-f57d-11e9-8b30-12e62258d3b5.png">

#### To Reproduce

1. Go to Safari
2. Try to display the exercise progress

#### Expected behavior

It should display the progress as follows:
<img width="838" alt="Bildschirmfoto 2019-10-23 um 10 12 13" src="https://user-images.githubusercontent.com/56912719/67372062-9a4d8700-f57d-11e9-91b9-5f1b93b59997.png">

#### Screenshots

Console output in safari:

<img width="1237" alt="Bildschirmfoto 2019-10-23 um 09 59 55" src="https://user-images.githubusercontent.com/56912719/67372094-a3d6ef00-f57d-11e9-939d-e884fdb78df3.png">
<img width="772" alt="Bildschirmfoto 2019-10-23 um 10 02 06" src="https://user-images.githubusercontent.com/56912719/67372105-a6d1df80-f57d-11e9-98d4-670a7e0b6c80.png">

### Environment

<details><pre>
 - OS: iOS
 - Browser Safari
 - Version Version 13.0.2 
</pre></details>

#### Output in Web Console

<details><pre>
  [REPLACE THIS WITH YOUR INFORMATION]
</pre></details>

**Comment by krusche** [comment]
@lovaiible could you please have a look. Also why there are warnings related to the guided tour?!? I guess you need to check this with a student account.

Thanks!

**Comment by krusche** [comment]
@floralatz thanks for reporting the problem. We cannot reproduce the problem at the moment. Can you try to reload the page in Safari? What happens if you navigate back to the exercise overview and then again into the exercise details? Which result do you see in the exercise overview?

Thanks for helping to find to the problem!

**Comment by floralatz** [comment]
@krusche navigating back and reloading the page did not solve the problem when it occured, however, since i had the issue i closed safari and reopened a new one and when i got to artemis now it is displayed just fine!

**Comment by krusche** [comment]
@floralatz thanks for the feedback. Then it was maybe just an issue with the update to the latest release. Good that it works now!
