### ISSUE TITLE
Show Differences for Repositories

### ISSUE THREAD

**Issue by JerroyTan** [ls1intum/Artemis#9805]
### Is your feature request related to a problem?

As a tutor, it is very frustrating when having to compare solution and template repositories to have to switch back and forth, or copy it out to an IDE and have compare them manually side by side.

### Describe the solution you'd like

I think it would be a major quality of life upgrade if we could show the differences between template and solution repositories and compare them side by side, so we can make sure that the templates for students make sense and it will make things easier for exercise creators. This function would be similar to showing differences with git.
For example:
![image](https://github.com/user-attachments/assets/94ef76bc-f1b1-4ebf-aa35-a0b050e39a20)

**Comment by krusche** [comment]
This is already possible in the programming exercise details page. Just scroll down and click on the yellow **Review Changes** button.
