### ISSUE TITLE
Communication Feature - Instructors Unable to Edit Student Messages

### ISSUE THREAD

**Issue by dfuchss** [ls1intum/Artemis#9894]
### Describe the bug

In the communication feature, instructors no longer have the ability to edit (redact) messages sent by students. The only available option is to delete the message entirely. This limitation makes moderation more challenging, as instructors are forced to delete messages instead of being able to partially redact or correct problematic content.

### To Reproduce

1.	Open the communication feature as an instructor.
2.	Navigate to a message sent by a student.
3.	Attempt to edit (redact) the content of the message.

### Expected behavior

Instructors / Moderators should have the ability to edit (redact) messages to make partial adjustments while retaining appropriate content.

### Which version of Artemis are you seeing the problem on?

7.7.2

### What browsers are you seeing the problem on?

Chrome

**Comment by asliayk** [comment]
As discussed in the communication subgroup and with @krusche's awareness, it has been decided that users will only be able to edit their own messages. Messages containing problematic content can be deleted, and a message reporting feature may be added in the future.


(https://github.com/ls1intum/Artemis/pull/9830)

**Comment by PaRangger** [comment]
As stated by @asliayk the issue/bug is intended behaviour.
