### ISSUE TITLE
Improve behavior of Trigger failed button

### ISSUE THREAD

**Issue by krusche** [ls1intum/Artemis#991]
The `trigger failed` button is great, but could be further improved.
Instead of immediately triggering a new build, we should do the following instead:

1) Get the newest result from Bamboo for this build plan and check if it is the one we are looking for (e.g. because Artemis was not notified by Bamboo for some reason) 
--> We can check this based on the commit hash in the last submission
==> Save the result in the database, return it to the client and we are done!
**Note:** we already have a working implementation for this that we can reuse `retrieveLatestBuildResult(...)` in BambooService)

2) If the latest result is not what we search for, we check if the build plan has a build that is currently queued or running (maybe the build took longer than the predefined timeout, currently hard coded as 2 min)
==> If the build is queued or still running, we ask the client to wait another time span, e.g. again 2 min.
**Note:** the returned json in `retrievedLatestBuildResult(...)` contains a flag `isBuilding` that can be checked. If this is false, we can use `https://bamboobruegge.in.tum.de/rest/api/latest/queue?expand=queuedBuilds` to determine if the build is currently queued.

3) If the build plan is not running at the moment, we trigger a build
==> done

This behavior is more accurate and less error prone, because in ~90% of the cases, there is already a result on the Bamboo server (case 1), which was somehow not retrieved in Artemis. Running another build then can lead to additional problems. In addition, we would not create additional submissions then.

Also in case 2, we don't want to trigger another build, because this might lead to situations where the maximum number of builds per plan is exceeded.

**Comment by thilo-behnke** [comment]
I'll look into it.

**Comment by krusche** [comment]
@thilo-behnke I think this issue was resolved.
