### ISSUE TITLE
`Programming Exercise`: Git diff between template and solution shows incorrect number of changes

### ISSUE THREAD

**Issue by maximiliansoelch** [ls1intum/Artemis#9928]
### Describe the bug

For some files, the calculated numbers of additions and deletions are incorrect displayed.

### To Reproduce

1. Go to a programming exercise edit page 
2. Click on 'Review Changes' in the Template/Solution Comparison section
3. Look for a file where the calculated number of additions and deletions is incorrect

### Expected behavior

The number of added and deleted lines of code between the template and the solution submission should be correct.

### Screenshots

<img width="1184" alt="image" src="https://github.com/user-attachments/assets/6d99ccc2-8845-425b-9444-d1d9077e25d3">

### Which version of Artemis are you seeing the problem on?

7.7.3

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by magaupp** [comment]
@maximiliansoelch I wasn't able to reproduce your example. Could you provide the full files?

**Comment by maximiliansoelch** [comment]
> @maximiliansoelch I wasn't able to reproduce your example. Could you provide the full files?

I provided you the details over Slack
