### ISSUE TITLE
Important - HTML does not get escaped in failed test reports

### ISSUE THREAD

**Issue by MaisiKoleni** [ls1intum/Artemis#993]
### Describe the bug
If tests fails, a user (student, tutor, instructor) can click on the underlined `x of y passing` to see more details. A modal opens up and shows the error that got reported. In case of JUnit, the error looks like this internally:
```
expected:<Nieder mit den Eisb[ä]ren!> but was:<Nieder mit den Eisb[�]ren!>
```
This however is not what is shown:
![pgdpError2](https://user-images.githubusercontent.com/11130248/67664964-f858e080-f968-11e9-872f-46266a33830e.png)

Because it is not escaped, and transforms into (partly by the browser):
![pgdpError](https://user-images.githubusercontent.com/11130248/67665020-1fafad80-f969-11e9-8db0-524c0c188d95.png)

This can easily be further extended to:
![pgdpError4](https://user-images.githubusercontent.com/11130248/67665141-669da300-f969-11e9-86c4-bfca626c0dac.png)

and could lead to big problems, in addition to students not getting a helpful error message.

#### To Reproduce
1. Create Java programming exercise
2. Set it up to test for String equality (no String can contain linebreaks, otherwise the HTML is rendered differently - but still wrong - again) using `assertEquals`
3. Solve the exercise and make a mistake, but only in the middle of the String (because <[...  seems to be no problem to display)
4. Submit and take a look at the report shown by artemis, also using the dev-view of the web browser

#### Expected behavior
HTML special characters must be escaped.

### Environment
<details><pre>
 - OS: Windows 10 (1903)
 - Browser Vivaldi (2.8; Chromium 77 based)
</pre></details>

**Comment by krusche** [comment]
@thilo-behnke could you please take a look. Thanks

**Comment by krusche** [comment]
@MaisiKoleni thanks for reporting this issue, but please be careful with CRITICAL.
I agree that this should be solved quickly, but I don’t consider this as critical. So I change the title to important

**Comment by MaisiKoleni** [comment]
Ok, no problem. I was not sure how to label it, but wanted to convey that it could be misused easily. I am sorry if this was to drastic.

**Comment by thilo-behnke** [comment]
I'll look into it.

**Comment by thilo-behnke** [comment]
Thank you for the report.

The problem is that we insert build output as HTML, even though we should just stringify and insert it into the template. I don't see a use case atm to insert build output as formatted html.

**Comment by MaisiKoleni** [comment]
I thank all of you very much for the fast fix. I assume this will be integrated in the maintenance today? Because that would allow me to remove some workarounds. And thanks again.

**Comment by jpbernius** [comment]
Hi @MaisiKoleni, yes, planning to release this today.
