### ISSUE TITLE
Open tutor actions such as "view,score,participations,grading" in a new tab

### ISSUE THREAD

**Issue by alekspetrov9e** [ls1intum/Artemis#9935]
### Is your feature request related to a problem?

I am always frustrated that I cannot open the view mode f.e. (one of the tutor actions after clicking the button)  in a new tab. It always opens it in the same one.
![Screenshot from 2024-12-03 11-08-27](https://github.com/user-attachments/assets/ea2c1317-85b9-46e9-9eeb-39b5615d2434)

### Describe the solution you'd like

Having the possibility to right mouse click and open the view mode in another tab.

**Comment by laxerhd** [comment]
I would like to implement that.
